Dockerfile, build.sh
This builds and installs mantle's `ore` binary as well as some other
useful utilities like `jq` and `awscli`. Then we should be able to fully
migrate the cloud pipeline.
=> Add ore to container

.gitignore, Makefile, src/main.rs, src/treefile.rs
- Use `eprintln` for cli error
- Follow rust preferred formatting
- Add `Makefile` with `build`, `clean`, and `check`
- Ignore generated files
=> Minor updates

src/main.rs
This introduces a `BufReader` and a `BufWriter` in front of serde
operations on files, in order to reduce the number I/O syscalls.
=> main: introduce buffering for file I/O

build.sh
The `coreos-assembler` container is becoming an entry point for
building many pieces of RHCOS.  We can continue to extend its
functionality by bringing in tools necessary to run the RDGO portion
of the build.
Additionally, I've included a separate commit that changes the build
script to use `dnf` everywhere instead of `yum`
=> build: bring in additional tooling to enable building RHCOS

build.sh
I am planning to use recursive containers in some of our Jenkins jobs;
using a host temporary mount point for `/var/lib/containers` for podman,
etc.
=> build: Install podman+buildah+skopeo

build.sh
Temporary bits until https://github.com/projectatomic/rpm-ostree/pull/1460 propagates
=> build: Install more rpm-ostree deps

Dockerfile, Makefile, build.sh, coreos-oemid, coreos-virt-install
This is *way* simpler than ImageFactory, and much more widely used.
In fact it's documented in the Red Hat Customer Portal, etc.
We avoid the whole ICICLE stuff which is really irrelevant to us.
And most importantly, it Just Works in an unprivileged container
provisioned with `--device /dev/kvm`, since we use `qemu:///session`.
(I tried to pass that though ImageFactory/oz but wasn't successful).
This will allow us to build CoreOS inside containers, as we should.
=> coreos-virt-install: New script

README.md
With #9 we are using libvirt and the virt tools directly rather
than using imagefactory. Update the readme accordingly.
=> README: change imagefactory to libvirt

coreos-virt-install
This is primarily useful for local development (particularly because
RHEL7 doesn't support 9p) but it has two massive advantages if one
can use it:
- It doesn't require a dance with a webserver
- It's really, really fast (like seconds here) to pull
If we want to move forward with this it's tempting to have this
program be in control of at least the `ostreesetup` line in the kickstart.
=> virt-install: Add --local-repo option and document how to use it

build.sh
First, let's just use the latest rpm-ostree release which has
the features we need; building it (and installing the builddeps + removing them)
was really really slow.
Next, move the packages we're installing into variables that
are documented (so we know why they're there) and do them as much as possible
in one group.
=> build: Clean up/doc dependencies, stop building rpm-ostree

build.sh
Ironically, the previous fix intended to catch all packages itself
didn't catch all packages. I've triple-checked now that we definitely
caught all the Pokemo^W packages.
=> build: And put back yet more packages

coreos-oemid
If we're operating on a read-only image, make our copy writable.
(Leave it up to the caller to mark read-only again if desired)
=> oemid: Mark destination copy writable

build.sh, coreos-virt-install
I want to use `%include` for some kickstarts, and this makes it
way more convenient.
=> coreos-virt-install: Support ksflatten

build.sh
I think using these in treefiles should be a best practice,
rather than /etc/pki/rpm-gpg, as installing things there can
affect the base system.
=> Install distribution-gpg-keys explicitly

.gitmodules, Dockerfile, build.sh
This makes everything more predictable/reliable, rather than taking
whatever's in master at the time.  It will also conceptually make it
easier to share source code (in theory) across these modules.
I also reworked the `Dockerfile`/build system to use the easier-to-maintain
pattern of copying the whole srcdir.
=> Rework to use git submodules

Dockerfile, build.sh, src/cmd-build, src/cmd-init
Today it's only `rpm-ostree compose tree` that wants privileges,
so let's flip the defaults to running unprivileged.  This drops
a whole lot of hacky bits; we only `setfacl` once in `init`.
=> Use builder user by default, add sudo for rpm-ostree compose

coreos-assembler
When `coreos-assembler` is inoked without options, the command prints
out a list of options to use.  However, only a few of them are useful
to the user (`build`, `init`).  This changes the command to just print
those.
=> Print only useful commands

src/cmd-build, src/cmd-init
I thought I was being clever using ACLs, it *mostly* worked
but the problem is that some of the objects aren't world readable,
and due to the way [effective ACLs](https://unix.stackexchange.com/questions/152477/how-does-acl-calculate-the-effective-permissions-on-a-file)
work, those objects weren't readable to `builder`.
This approach of doing the chown after treecompose matches what
FAHC does too.
=> Chown everything to builder, stop using ACLs

src/cmd-build
So we don't need to hit `TAB` a lot in bash and compare numbers.
=> build: Create a `latest` symlink

src/cmd-build
I tested that the previous commit created the link, not that it
swapped correctly.
=> build: Actually replace link

coreos-assembler, src/cmd-build, src/cmd-init
To make it easier to run in pet containers, just assume that the current
user has sudo privs. But still try to `runuser -u builder` if started as
root. This also requires using `$UID` instead of `builder` in the actual
command scripts to keep it generic.
=> Allow running as current non-root user

src/cmd-build, src/cmd-init
Apparently `$UID:` isn't a valid spec, but `$USER:` is...
=> Use $USER instead of $UID

src/cmd-build, src/cmd-fetch, src/cmdlib.sh
I find it actually really annoying that `compose tree` fetches
the rpm-md each time when I want to test something.  We should
probably have a `--respect-caching` option, but even then...
there are definitely use cases to fetch the content without
builds.
Down the line for example when we integrate something rpmdistro-gitoverlay
like, `fetch` here would also invoke `rpmdistro-gitoverlay fetch`.
=> Split up `fetch` and `build`

coreos-assembler, src/cmd-run
This is a copy of my
https://github.com/cgwalters/playground/blob/master/coreos-run-qemu
script.  Which I know overlaps a lot with `kola spawn`, but as
is noted in the header:
- Uses `-snapshot` by default to avoid writing to the disk
- Contains a default  Ignition config that auto-logins on the console
Also, this runs as non-root.
The main change I made from the playground one is small but important
one:
`coreos-assembler run`
finds the latest disk image and runs it this way.  I find this *very*
convenient.
=> New command: run

src/cmd-build
This is more predictable than a datestamp and shorter to parse.
The idea of `genver` is that a bit like RPM `Release` it gets incremented
when we change the kickstart but not the ostree commit.
=> build: Use ${ostree-version}-${genver} for images

src/cmdlib.sh
It requires an absolute path for historical reasons.
=> cmdlib: Fix --touch-if-changed for rpm-ostree

coreos-assembler
if running via podman or docker the $USER var is not
set automatically. Let's set it so that the rest of
our scripts can use $USER as they please.
=> explicitly set $USER variable

README.md, src/cmd-init, src/cmdlib.sh
It's a bit too magical to have hardcoded config defaults.  We really
want anyone doing custom builds to use their own repository, and
requiring them to specify it upfront will highlight that.
For local development, it's very convenient now to just pass a
local file path, without having another clone sitting around.
Note that I pushed
https://github.com/cgwalters/fedora-coreos-config/commit/0a2c02a60589b936da0b5c0c9cce20ae9fb81f74
which is used by this.
=> init: Require specifying a config repository

src/cmd-build
Significantly extend our `meta.json` using rpm-ostree's
[new commitmeta JSON](https://github.com/projectatomic/rpm-ostree/pull/1529).
Also add the git hash of the config repo both as *input* to the OSTree commit
object (so it can be queried easily on the OS client side) and as output in
`meta.json`.
=> build: Use rpm-ostree's JSON metadata, add git input metadata

src/cmd-init
Right now, doing `init` without args on an already initialized dir fails
at `shift`. Let's strengthen handling by right off the bat requiring at
least one argument, and then also bailing out if a dir looks like it's
already been initialized.
=> cmd-init: Strengthen error conditions

coreos-assembler
Having `/sys/fs/selinux` means e.g. libvirt tries to do a
domain transition, which will fail.
See https://github.com/containers/libpod/issues/1448
=> main: Work around older podman selinux bug

Dockerfile, src/cmd-build
This is just a good idea in general (e.g. for our `shell` verb),
but it will specifically fix the issue that `virt-install` forks
`libvirt` which forks `qemu`, and libvirt won't know that a VM
is shut down until the `qemu` process is actually reaped by pid 1.
=>  Dockerfile: Wrap entrypoint with `dumb-init`

src/cmd-build
Different distros have different permissions on /dev/kvm. Recreate it
inside the container to ensure we don't hit ENOPERM.
addresses https://github.com/coreos/coreos-assembler/issues/70 
Using docker 18.03 this does not change the host `/dev/kvm` for me.
=> src/cmd-build: recreate /dev/kvm

src/cmd-build
While we know the assembler is tracking FAHC, it's still
useful information in general since the feature set of these
is changing pretty quickly.
Ref: https://github.com/projectatomic/rpm-ostree/issues/1556
=> build: Print versions of ostree/rpm-ostree

src/cmd-init
- add getopt option parser
- error if target directory is not empty
- add --force option to override above check
- add various comments
=> init: Rework error handling and options

src/gf-oemid
Requires: https://github.com/coreos/fedora-coreos-config/pull/7
Prep for dropping LVM - but in general this adds a level of flexibility,
if someone wants to use some other filesystem or LVM setup they
can just provide those same labels.
=> oemid: Use labels to discover root/boot

coreos-assembler
The idea is you should get a help message if you just type
`coreos-assembler`, but previously we errored out since
`shift` failed.
=> main: Fix the placement of `shift`

src/virt-install
We don't want Anaconda to find a network device and do DHCP,
and try to encode anything about the build environment.
Further, we want all of the content to come from the container;
nothing potentially from the Internet.  Downloading content in `%post`
is a no-no.
Since we currently inject convent via 9p, disable networking
in the installer.
This will break RHCOS builds, but we'll adapt them to use this.
Right now it's tagged to `:alpha`.
=> virt-install: Disable networking

coreos-assembler
It should be totally fine to run these tools from inside an
existing container, not a weird case.
=> main: Stop warning about non-builder users

Makefile, src/compat/coreos-oemid, src/compat/coreos-virt-install
Everything should be either using the toplevel `coreos-assembler`
entrypoint, or know what they're doing.
The RHCOS builds are tagged to `:alpha` now so won't break with this.
=> build: Drop compat/ command entrypoints

coreos-assembler
Promote the ones that operate on a "builddir" first.
`shell` is a bit special.
Then the other "utility" commands are like `virt-install` where
we expose it as its own function to make it easier for downstreams
to reuse the logic outside of `cmd-build` for more custom things.
We will need this until we implement a config file to define
which image types are built for example.
=> main: Categorize commands

src/cmd-build, src/gf-oemid
While the `build` directory acts sort of like a tmpdir, we do end
up potentially reusing things if resuming a previous failed build.
Some tasks however do require a true tmpdir.  `gf-oemid` was allocating
its own in `/tmp`.  Let's pass our tmpdir down to it and hence
saving the image is just a `rename()` rather than a full copy.
The *real* reason I'm doing this though is I got confused by the
fact that the tmpdir name was `qcow2-to-vagrant` since I cargo-culted
this code from https://github.com/cgwalters/qcow2-to-vagrant
And I ended up killing a build job that I thought was using that
incorrectly.
=> build: Allocate a tmpdir for each build

src/virt-install
We don't want this in the config repository, as it's an implementation
detail of our setup.
Bigger picture, we want to drain all of the bits out of `%post` so
that "ostree" == "image" as part of the "dd to install" flow.
=> virt-install: Hardcode creating /boot/coreos-firstboot

src/virt-install
That should just be the default. The current `%post` is trivial, though
add it anyway to increase the odds it sticks around as more things get
added.
Also fix minor typo.
=> virt-install: Use %post --erroronfail

src/cmd-build, src/cmdlib.sh
Let's verify upfront that `sudo` works along with the rest
of our preflight checks.
Then use `sudo` to do the `/dev/kvm` adjustments here rather
than just deep in `cmd-build`, so it's clearer where these
types of things happen.
=> preflight: Verify sudo works, also move /dev/kvm adjustments here

src/gf-oemid, src/libguestfish.sh
Split out the guts of `gf-oemid` that e.g. know about the `root`
and `boot` labels into a library that can be reused by other code.
Prep for further work around installation.
=> Split off a `libguestfish.sh` helper library

build.sh, src/cmd-run
`jq` checks for syntax errors, whereas `ignition-validate` also checks
for semantic errors.
=> cmd-run: Use ignition-validate instead of jq

src/cmd-build, src/cmd-fetch
The scripts are becoming more involved, and all the output we get from
`-x` mostly distracts from the meaningful output. Let's just drop those
and we can always add back some strategic `echo` statements if we feel
like any are missing.
(Note we still leave it in `cmd-clean` for now; it's much shorter and
it's an easy way to see what's getting nuked.)
=> cmd-[build|fetch]: Drop set -x

src/gf-oemid, src/libguestfish.sh
The library was referencing `${tmp_dest}` rather than an explicitly
provided variable.
=> Make input disk image explicit for guestfish bits

Makefile, coreos-assembler, src/cmd-build
`/usr/lib/$pkg` is the new trend, it's really simple
to just have one data directory and not split things up.
=> Install to /usr/lib/coreos-assembler, not libexec

src/cmd-run
Right now, we're running at the default log level, which is DEBUG (7).
The text gets interspersed with user input/program output on the tty.
Bump the default to ERROR (3).
This uses a systemd service hack instead of a `sysctl.d` drop-in. The
reason is that Ignition relabeling right now happens too late in the
process for `systemd-sysctl.service`, so it trips on SELinux issues.
Looking to fix that soon.
=> cmd-run: Add coreos-assembler-quiet-tty.service

Makefile, build.sh, deps.txt, src/cmdlib.sh
The recent requirement of `ignition` broke my workflow from
my dev container.  Let's verify upfront that everything we
expect is installed.
As a bonus, this is a text file easily parsed by other things
too rather than embedded inside shell script.
=> Create deps.txt, use it for build and runtime

deps.txt, src/cmdlib.sh
When I was originally splitting off `deps.txt` I ended up trying
to reorder/change things to use `/usr/bin` so I could test file
paths, but ended up backing that out.
In backing it out I apparently lost the dependency on the virt-install
stack.  Readd that.
And then that reveals the other problem, which is our dependencies
are a mix of file paths and packages, so support both of those.
(Potentially...we should build an rpm of our binaries
and just use `Requires:`...)
=> deps: Add virt-install bits, fix deps.txt

src/cmd-build, src/cmdlib.sh
I'm looking at writing some code to sync `builds/` to e.g. S3.
But having the `work` dir in there is ugly.
Since we added a `tmp` dir, let's rework the build process to
allocate `tmp/build` instead.  Then everything happens in there,
and at the end we just `rename()` it into place.
=> build: Drop builds/work, use tmp/build instead

src/cmdlib.sh
And require a magical comment to disable it.  We really want
people to use this by default.
=>  cmdlib: Default to --unified-core

src/cmd-build, src/cmdlib.sh, src/gf-oemid
Further rework our tmpdir story so that we have `$currentbuild/tmp`,
and place things like temporary JSON, the `-base.qcow2`, and the
kickstart files there.
This way it's all consistently cleaned up.
We drop the now-confusing `$build_tmp` variable in favor of just
referencing `tmp/` or `$(pwd)/tmp` where necessary for child
processes.
Also, no files are owned by root anymore.
Prep for publishing the results of builds.
=> build: More cleanup of tmpdir and artifacts

build-deps.txt, build.sh
Just like how we split out an easily machine-readable `deps.txt`,
do the same for our build dependencies.
However as part of adding a new developer flow to this container,
do ship those dependencies.
Ref: https://github.com/coreos/coreos-assembler/issues/75
=> Create build-deps.txt, ship them in the container too

src/virt-install
I didn't fully trace through, but I think the race is
probably either in the libvirt python bindings or core libvirt.
Related: https://github.com/coreos/coreos-assembler/issues/31
=> virt-install: Add a hack to wait for libvirt

build.sh
I'd like to use the new `postprocess` bit for RHCOS work.
=> build: Use latest rpm-ostree

src/cmd-build
If one is doing builds via oscontainer, it doesn't make sense
to use refs as well.  Rework the build process so that most
of it doesn't require specifying a ref.
Today however, Anaconda does require a ref, but we're heading
down the road of not using Anaconda.
Another thing this takes a step towards is supporting a mode
where the ref is only written "for real" when the image build
is complete - we want to support people truly binding them
together.
=> cmd-build: Preparatory work for supporting builds without refs

src/cmd-build
So that I can consistently do
$(realpath /srv/fcos/builds/latest/fedora-coreos-qemu.qcow2)
whenever I need to e.g. create a VM/export it out/etc...
Clearly useful as well once we start serving these files over HTTP.
=> build: Add unversioned stable symlink to qcow2

src/cmd-build
Sometimes I'm hacking on rpm-ostree and want to force a rebuild
to test my changes to rpm-ostree.
There are also cases where rpm-ostree today doesn't correctly
detect changes, such as with external `postprocess-script` files.
=> build: Add a --force option

src/cmd-run
Otherwise `qemu-kvm` can get confused thinking that the `,cache=unsafe`
is part of the filename:
qemu-system-x86_64: -drive if=virtio,file=/srv/fcos/builds/29.1-1/fedora-coreos-29.1-1-qemu.qcow2: Could not open '/srv/fcos/builds/29.1-1/fedora-coreos-29.1-1-qemu.qcow2,cache=unsafe': No such file or directory
=> cmd-run: Fix argument ordering for -drive

build.sh
Required to manipulate image tags on the OpenShift registry
=> build: add origin-clients

src/cmd-oscontainer
We need the default to be in the argparser, otherwise the `None`
default would override the func default.
=> oscontainer/build: Correct default for --from

build.sh
The new `oscontainer` command works better with the newer podman.
=> build: Drop podman override

src/cmdlib.sh
If the user creates a directory `overrides/rpm`, automatically
run `createrepo_c` on it every build, and generate a new
treefile that adds it as a repo.
Closes: https://github.com/coreos/coreos-assembler/issues/118
=> build: Add support for automatic overrides in `overrides/rpm`

src/virt-install
We need to consistently use binary mode.
=> virt-install: Fix crash if --kickstart-out is not specified

src/virt-install
Otherwise we may not get the firstboot file.
=> virt-install: Flush after writing

src/cmd-build
In some RHCOS Jenkins work I didn't have the ref in the `repo-build`, and
the semantics here were confusing.  Let's pull the previous checksum
out of the previous build if we do have that.
=> cmd-build: Handle case of missing ref more gracefully

src/cmd-oscontainer
`podman push` untags the image locally apparently (which is fine)
but for some RHCOS work I'm doing I really want to get the digest
of the image we built so I can add it to our build metadata.
=> oscontainer: Add a --inspect-out arg to write output container data

src/gf-oemid
This injects `coreos.oem.id` flag into the Boot Loader Specification
(BLS) configuration entry too, in order to make sure that the flag
won't get lost on further client-side re-generation.
Fixes: https://github.com/coreos/coreos-assembler/issues/123
=> guestfish: add OEM ID to BLS too

src/cmd-build, src/cmdlib.sh
This will allow e.g. an orchestrating Jenkins job to look for
the file afterwards and only trigger a `build` if something changed.
This is better than doing it in one job since then the secondary
build job will only have actual builds.
This also fixes a subtle bug in that we weren't clearing the stamp
file before doing a build, so we could spuriously think something
did change.
=> Consistently set tmp/treecompose.changed

src/cmd-build, src/virt-install
That's where it logically belongs since we're also setting up the 9p
bits there.
Prep for further 9p usage.
=> build: Move 9p fully into virt-install

src/cmd-oscontainer
Today c-a's image building bits via Anaconda requires a ref.
Let's support writing one when extracting so we can give it
to Anaconda for now, even if the long term goal is to not have a ref.
=> cmd-oscontainer: Add a --ref argument to extract

src/cmd-build, src/virt-install
This helped me debug an `ostree admin deploy` failure since then
I have `program.log`.
=> build/virt-install: Support for scraping out the Anaconda logs 

src/cmd-build, src/cmd-clean, src/cmd-fetch, src/cmd-init, src/cmd-prune
We had a bunch of copy-pasted stanzas that called out to `print_help`,
except that function is only defined in the `init` command.
Consistently define a `print_help` function, and make sure we support a
`-h/--help` option which prints it and exits nicely like in `init`.
Also explicitly check for too many args in functions that don't support
any extra positional args.
=> cmds: Properly support --help

src/prune_builds
=> prune: Use `sudo` for repo-build

src/cmd-oscontainer
Previously: `Preparing to extract cid {} ffa8d21f...`
=> oscontainer: Fix extract message

src/cmd-build, src/prune_builds
In the case where just the kickstart changed, we'd end up with
multiple builds with the same timestamp.  Fix this by adding a
`coreos-assembler.build-timestamp` metadata key, and use it
if available when sorting/pruning.
=> Add a proper build-timestamp

src/cmd-build
When I went to deploy coreos-assembler in Jenkins, I hit a
crash in the case where nothing had changed.  The reason is
that in this case the `tmp/` dir isn't saved across builds, and
we were relying on the previous build's treecompose metadata
being cached there.
Fix this by moving the detection of the "no input changes"
case to follow immediately after the treecompose "no changes" logic.
Parsing of the previous build image data, and computing the kickstart
checksum also happen before treecompose now, consistently alongside
the places where we parse the ostree data out of the previous build.
Now, there's another corner case here - in the orchestrated case,
how do we handle the case of *just* the `image.ks` changing?  What
I chose to do there is to pull the previous build's `meta.json`.
=> build: Move "no changes" logic earlier

src/cmd-init
I think this will be convenient for us working on Red Hat CoreOS;
we will need to support multiple streams, and having them in a
single git repository with subdirectories will be useful.
=> cmd-init: Support specifying a subdirectory

src/cmd-run
=> cmd/run: Use sysctl.d dropin instead of service

src/cmd-build
In the vast, vast majority of cases, it will be the ostree that
changes and not just the images.
The `-1` is very visually distracting.  Let's only append it
when it's necessary.
=> cmd-build: Only append image-genver if it's not 1

src/cmd-build
In the case where there are no previous builds, and on the first
try we do make an ostree commit, further builds would fail.
=> cmd-build: Don't crash if no previous build and no ostree changes

src/cmd-build
Our metadata should contain information about the generated images
too.  Having a manifest of what we built is useful in general, and
we want checksums in particular so that tooling can use
them to verify downloads.
=> build: Add image metadata with path+sha256

src/cmd-build
I missed this when doing
https://github.com/coreos/coreos-assembler/pull/168
AKA ec023cd5ddfaf0e35991a91cb2dcc230663ab82e
This way the image name doesn't have a weird `-0` in it.
=> cmd-build: Use buildid for image names too

src/cmd-build, src/prune_builds
For the current RHCOS pipeline I'm only syncing the previous build,
not all builds.  Planning to handle pruning separately.
=> build: Don't rewrite builds.json if not pruning

src/gf-oemid
Today we only build a qemu image.  I plan to work on
"build postprocessing" tools so that one can take an existing
build and extend it with more image types.
This is prep for that, by allowing us to replace the qemu image's
oemid.
=> gf-oemid: Support replacing oemid

src/cmd-buildextend-ec2, src/cmdlib.py, src/libguestfish.sh
This allows a build process to take an existing build, test it
locally, and then upload to EC2.
A further command might be `buildpost-ec2-plume` or so that
expands to all regions.
=>  buildextend-ec2: New command

src/cmdlib.sh
I'm using the subpath bit, and the fact that we were only copying
the subpath from the git repo broke things for me since our
base configs live in `..` from the subpath.
Actually now that rpm-ostree fixes have landed around treefile
parsing, rather than copying the whole input dir, simply make a new
one that inherits from it.  The last gap here unfixed in rpm-ostree
is finding the `.repo` files, so let's just copy those in.
=> cmdlib: Fix overrides when using subdir paths

src/cmd-build
I'm now parsing the `meta.json` in several places and it'd be
really convenient if we had this property, since then one can just
`open('builds/latest/meta.json)'` and have what one needs.
(Why not `coreos-assembler.buildid`?  Um...I dunno.  I missed
adding that to `amis` and `images` too and eh...we're not going
to collide with rpm-ostree.)
=> build: Add `buildid` to metadata

src/cmd-buildextend-ec2
So a separate CI account can do testing before making it public
for example.
=> buildextend: Pass through ore's --grant-user

src/cmd-build
This is another useful piece of data; I'm writing some scripts
to extend the AMI to multiple regions, and having the source
data here (rather than scraping it from the original AMI) would be
nicer.
Perhaps a better place for this would be in `builds.json` though?
=> build: Add `name` to metadata

src/cmdlib.sh
This way we can use `${basearch}` in the ref.  Also the way
we were doing it before didn't work with treefile inheritance.
Reinstates support for https://github.com/coreos/fedora-coreos-config/pull/24
=> build: Use rpm-ostree compose --print-only to expand ${basearch}

.gitignore, build.sh, coreos-assembler, src/cmd-build, src/cmd-clean, src/cmd-fetch, src/cmd-init, src/cmd-prune, src/cmd-run, src/cmd-shell, src/cmdlib.sh, src/gf-oemid, src/libguestfish.sh, src/supermin-init-prelude.sh, tests/check.sh
See https://github.com/koalaman/shellcheck for background
=> Fix 'shellcheck' complaints

build.sh
Since we dropped rpmdistro-gitoverlay.
Spotted by Sinny in https://github.com/coreos/coreos-assembler/pull/200#discussion_r232340931
=> build.sh: Also drop walters-buildtools-fedora

.travis.yml, src/cmd-init
This does a `shellcheck` on the bash files and tries to do a container build.
Will require one of the repo admins to enable Travis CI access.
=> Turn on simple Travis CI checks

src/cmd-build
It took me a while to debug why my newly built images had old
ostree commits in them; the summary update was removed in
https://github.com/coreos/coreos-assembler/pull/190
Let's add it back in.
=> cmd-build: Update the summary again

src/libguestfish.sh
We discussed possibly using a `var` partition for FCOS in
https://github.com/coreos/fedora-coreos-tracker/issues/18
I would like to do so for my own Silverblue install, and possibly
for Silverblue by default.
So let's mount that partition if it exists, which means the other
code that cleans out what Anaconda did in `/var` will work.
=> libguestfish: Also mount `var` if such a partition exists

coreos-assembler, src/cmd-buildextend-openstack, src/cmdlib.py
Building on the prior art of `buildextend-ec2`.  We really want
a config file or arguments for `build` or so, but for now this
fixes a regression in our switch to coreos-assembler for RHCOS
in that we need an OpenStack image.
=> buildextend-openstack: New command to add OpenStack image

.gitignore, bottlecap, bottlecap-shim
Add bottlecap as the default entry point. It will handle launching the
coreos-assembler container and optionally binding in and rebuilding
certain aspects to aid development. This is in additon to the existing
flows.
Putting this up as WIP to get some feedback, will add docs before final version
=> *: add bottlecap, an optional entry point

src/cmd-init
I found myself doing a lot of `init` operations when testing changes
related to #190 and wanted a way to skip the download of the
ISO/sha256sum.
This change introduces a new flag (`--installerdir`) that will
instruct the `init` command to look in a provided directory for the
ISO and sha256sum. If the required files are found, they'll be copied
to the `installer` directory for use later on.
If the `--force` option is provided, it downloads the ISO/sha256sum
regardless if the `--installerdir` flag is provided.
=> init: add ability to use existing ISO/sha256sum

src/cmd-build, src/gf-anaconda-cleanup
OSTree was designed from the very start to support having `/var`
be empty on boot, but for Fedora we ended up using Anaconda which
meant we had to carry a lot of hacks to run `systemd-tmpfiles`
in the root to support `%post`.  And when I say "hacks", I mean
seriously ugly hacks.
For Fedora CoreOS, since we're requiring Ignition and moving
away from Anaconda, we can use OSTree as it was designed
in a clean fashion.
For now since our build side is still using Anaconda, let's just
remove all contents in `/var` as a postprocessing step.
This is also a preparatory change for having images with a `/var`
partition pre-configured.
Requires: https://github.com/coreos/fedora-coreos-config/pull/29
=> Clean out /var for images

src/cmdlib.sh
This is a a regression from the unprivileged work.  Previously
we had two repos, and only the `repo-build` was owned by root.
Now that we have one repo, in the privileged path `rpm-ostree` still
runs as uid `0` by default, so we need to `chown` the repo to
ensure that e.g. `ostree prune` (run unprivileged) can operate
on it.
=> build: chown repo in privileged mode

src/deps.txt
shellcheck command is used in [tests](https://github.com/coreos/coreos-assembler/blob/master/tests/check.sh#L18) which is required during coreos-assembler container build.
=> deps: Include ShellCheck as dependency package

src/cmd-build, src/cmd-prune, src/prune_builds
We want to be able to prove the "freshness" of `builds.json` to consumers, so let's introduce a timestamp field.
This change causes the `build` process to insert a timestamp field on `builds.json`.  It also introduces the ability to *only* timestamp `builds.json`
I also changed `build_timestamp` in `meta.json` to match the rest.
=> support RFC3339 timestamps on `builds.json`

README.md
Make it clear right from the beginning that the fetching and the
building stages are separate by teaching the reader to run `fetch` first
and then `build`.
=> README.md: Add more details about `fetch`

src/cmd-build, src/commitmeta_to_json
This is generally useful but especially so for the pkglist alone for
higher level tools displaying releases/build outputs.
Closes: #197
=> build: Also output commitmeta.json

src/commitmeta_to_json
Otherwise all numeric values will be wonky. OSTree canonicalizes to big
endian.
=> commitmeta_to_json: Byteswap on little-endian platforms

README.md, build.sh
Just some notes I made while hacking on this before, in case they can be of use.
The boldness edit to the build error is not very crucial, as with the script already being printed out it was quick to get the problem resolved. But adding the `error:` or something like that I find helps it stick out a bit when looking for what went wrong.
=> README and build: add info on testing modified script locally, and boldness to build output error

src/cmdlib.py, src/prune_builds
The `fatal()` function provides a common way to print an error message
and exit.
The `rfc3339_time()` function generates a RFC3339 timestamp.
Snuck in some `pycodestyle` fixes too.
=> add some helper functions to `cmdlib.py`

coreos-assembler, src/cmd-tag
The `build-tag` command allows the user to list, create, delete, and
update tags in the `builds.json` metadata.
=> tag: new command to manipulate tagging

coreos-assembler, src/cmd-bump-timestamp, src/cmd-prune, src/cmd-restamp, src/cmdlib.py, src/prune_builds
Follow-up to #243. Become aware of tags and make sure not to prune
builds that are tagged. I went the path of making tagged builds *not*
counting towards the `--keep=N` limit since that felt the most natural
to me.
One tricky bit is the OSTree repo pruning. The CLI is not really geared
towards this kind of pruning since we now could have older (tagged)
commits that we care about while some newer commits on that same branch
we don't care about. For now, I just swapped it to use
`--keep-younger-than`. Though this does align well with another
improvement I'd like to make to `prune` to learn timestamp-based pruning
instead.
=> prune: Don't prune tagged builds

coreos-assembler
Split the build commands (roughly) into commands one would likely use in
the developer path vs others we'd use more likely in a pipeline context
only.
As part of that reshuffle, move `tag`, `compress`, and `bump-timestamp`
into the "utility" category since they don't create brand new artifacts,
only slightly modify existing ones. And also move `oscontainer` from the
"utility" category and into "advanced build" for the converse reason.
Finally, also remove `gf-oemid` and `virt-install` which aren't actually
user-facing commands.
Output:
```
Usage: coreos-assembler CMD ...
Build commands:
init
fetch
build
run
prune
clean
Advanced build commands:
buildextend-ec2
buildextend-openstack
oscontainer
Utility commands:
bump-timestamp
compress
tag
Other commands:
shell
```
=> entrypoint: Tweak command help output

coreos-assembler, src/cmd-buildprep
This command will pull down the strict minimum necessary to retain
commit/versioning history. This is meant to be used as is in the FCOS
pipeline:
```
$ coreos-assembler buildprep http://artifacts.ci.centos.org/fedora-coreos/prod
Fetching http://artifacts.ci.centos.org/fedora-coreos/prod/builds/builds.json
Fetching http://artifacts.ci.centos.org/fedora-coreos/prod/builds/29.16/meta.json
+ ostree remote delete --repo=repo buildprep --if-exists
+ ostree remote add --repo=repo --no-gpg-verify buildprep http://artifacts.ci.centos.org/fedora-coreos/prod/repo
+ ostree pull --repo=repo buildprep 7b130861da0267d565ae7c7c7f4279a9848731bef3cf363e007fa053f37a6e44 --commit-metadata-only
1 metadata, 0 content objects fetched; 306 B transferred in 0 seconds
+ ostree remote delete --repo=repo buildprep …
```
=> Add new `buildprep` command for preparing build

src/cmd-prune, src/cmdlib.py, src/cmdlib.sh, src/prune_builds
So right now, `prune` only knows `--keep=N` for fine-tuning the prune
operation. But humans are temporal beings and care more about the *age*
of a build rather than its index in the `builds[]` array.
This patch adds a `--keep-last-days=N` switch to accommodate this. I
initially was looking for a generic "fuzzy" parser that could parse e.g.
"2 weeks ago", and there is one (dateparser) but it's not packaged in
Fedora and I didn't want to start relying on pypi for this. Anyway, in
the prod context, I'd prefer we use something less fuzzy like
`--keep-last-days=14`.
=> cmd/prune: Add --keep-last-days=N switch

src/cmd-build
So that when rpm-ostree prints out a message to use it, it'll also work
directly with the build command.
Closes: #256
=> cmd/build: Alias --force-nocache to --force

src/cmd-init
Match the idempotency of the rest of the script by only recreating the
qcow2 if it's missing.
=> cmd/init: Only recreate cache.qcow2 if it's missing

src/cmd-buildextend-ec2
This way we can use 16GB by default for RHCOS, and FCOS isn't
tethered to 8gb.
=> Update mantle, and buildextend-ec2: Use new ore --disk-size-inspect

src/cmdlib.py, src/gf-oemid
I was mucking around with the `assembler` and tried running the `buildextend-openstack` command after I had used `compress`.  And the result was `gf-oemid` being very unhappy.
This changes `gf-oemid` to check the extension is `.qcow2` before running.  And also updates the `run_verbose()` function to catch the exception raised by a failed command.
New output for an incompatible image looks like this:
```
$ coreos-assembler buildextend-openstack 
Targeting build: 47.3
+ /usr/lib/coreos-assembler/gf-oemid builds/47.3/redhat-coreos-maipo-47.3-qemu.qcow2.gz tmp/buildpost-openstack/redhat-coreos-maipo-47.3-openstack.qcow2 openstack
fatal: Cannot change coreos.oem.id on redhat-coreos-maipo-47.3-qemu.qcow2.gz; not an uncompressed QCOW2
fatal: Error running command …
```
=> Don't allow `gf-oemid` to operate on  compressed images

src/cmd-run
Updates the MOTD to indicate that ICMP traffic is unavailable.
For example:
```sh
eth0: 10.0.2.15 fec0::5054:ff:fe12:3456
coreos login: core (automatic login)
Fedora CoreOS (preview)
https://github.com/coreos/fedora-coreos-tracker
WARNING: All aspects subject to change, highly experimental
---
ICMP traffic (ping) does not work with QEMU and user mode networking.
To exit, press Ctrl-A and then X.
```
=> Updates the MOTD to indicate no ICMP traffic

src/deps.txt, src/prune_builds
`pytz` and `dateutil` are not available for all bases we want to build
with. Instead of trying to create new packages and get them approved
this change moves to using the python standard library. While not
as pretty, the same or similar enough functionality is provided.
NOTE: All dates are treated as UTC.
=> Use stdlib for date parsing

src/cmd-buildextend-ec2, src/cmd-buildextend-openstack, src/cmd-buildprep, src/cmd-compress, src/cmd-oscontainer
Split off from #270
This changes all the places where we muck with paths to use
`os.path.join()`.  Hopefully this is start of some coding standards as
discussed in #271.
=> src/cmd*: use os.path.join() where appropriate

tests/check.sh
Split out from #270
TL;DR - ShellCheck is disabled unless version 0.4.0 or newer is
installed.
The ShellCheck test makes use of the `--external-sources` option, so
we can load in external libraries during the checks.  But that
option is only available in version 0.4.0 and newer.  Older versions
of ShellCheck will barf on the `shellcheck source=src/cmdlib.sh`
directives and trying to tell ShellCheck to exclude the raised error
was not successful.
=> tests/check.sh: disable ShellCheck if older than 0.4.0

bottlecap, bottlecap-shim
- Switch shebang to `/usr/bin/env bash`, which is most common for the
repo
- Use most of "unofficial bash strict mode" -
http://redsymbol.net/articles/unofficial-bash-strict-mode/
- Update container to latest image in use
=> bottlecap*: small tweaks for consistency

src/deps.txt
For the RHCOS use case, we need the `yaml` module for Python.
Installing it via SCL appears to be the most straightforward way to
do so.
=> deps: YAML module for python3

.travis.yml, src/cmd-run, src/cmd-shell, src/cmdlib.sh, src/libguestfish.sh, tests/check.sh
With #277 merged, this should standardize the `bash` shebang across all our shell scripts to `#!/usr/bin/env bash`.
Additionally, this changes how `tests/check.sh` runs and expands the files we are syntax checking.  This also forced me to redo how the Travis CI job ran, so now that uses the same `check.sh` script that one would use locally.
TODO:
=> clean up bash shebangs + test upgrades

src/deps.txt
For the purposes of building `coreos-assembler` and building RHCOS
images, the `ShellCheck` and `distribution-gpg-keys` are not required.
Additionally, we can get away from relying on EPEL if we switch to
installing `python-gobject` from the EL7 repos.
=> deps: drop some unneeded pkgs for EL7

src/virt-install
for KVM to work on aarch64 --cpu=host-passthrough has to be passed
to virt-install https://bugzilla.redhat.com/show_bug.cgi?id=1531076
Signed-off-by: Dennis Gilmore <dennis@ausil.us>
=> virt-install: host cpu passthrough

README.md, bottlecap
In dec465c we switched from using 9pfs to a network based solution
for sharing our ostree into the Anaconda install environment. As a
result of this we needed to predictably obtain the ip address of the
container and reliably know we could access an http server started
on the container's port 8000.
Using `--net=host` conflicts with this because it decreases the
probability of us choosing the right ip address and not requiring
us to poke holes in a firewall.
=> don't use --net=host

build.sh
Because there is no `gobject-introspection` module available to the
Python 3.6 stack from the SCL, we have to use Python 2 in the EL7
container case.  This will change the shebang on the script to use
`/usr/bin/python2` (for EL7 only), which avoids the SCL and
provides the ability to use `import gi`.
=> build.sh: switch commitmeta_to_json to python2

src/deps.txt
Add grub2-pc to make working on removing anaconda easier. This is mostly a quality of life improvement for me so I don't need to keep either installing it on container entry or rebuilding the container to keep up with master.
=> src/deps: add grub2-pc

src/cmd-init
Allow overriding the installer locations via env variables:
- INSTALLER_URL_OVERRIDE: Custom location for install ISO
- INSTALLER_CHECKSUM_URL_OVERRIDE: Custom location for sum file
/cc @imcleod
=> src/cmd-init: Allow installer overriding

src/cmd-init
If we don't substitue in a default value then we'll get
`cmd-init: line 127: INSTALLER_URL_OVERRIDE: unbound variable`.
Substitute a default value of '' so that we still fail the `-n`
check but don't error on unbound variable.
=> init: don't error out if INSTALLER_URL_OVERRIDE not set

src/virt-install
My development workflow is to install coreos-assembler inside
my dev containers which use `--net=host`.  In particular I commonly
want to hack on rpm-ostree and test it with coreos-assembler.
Dropping 9p made sense but hardcoding `eth0` broke support for
using my dev containers.  Let's detect the default route and work
in both cases.
(Though we should also probably dynamically grab a port but eh
I can easily keep 8000 free locally)
=> virt-install: Detect default route instead of hardcoding eth0

src/cmd-run
I found the /etc/sysctl.d/10-coreos.conf on my system as I was
hacking/developing and it took me a while to figure out where it
came from. This adds comments and makes things more explicit.
=> run: more verbosity for sysctl dropin

src/virt-install
Printing a line per request is quite slow and takes over
the terminal.  No need to log them, Anaconda has basic stats
that we already get.
(And we should move at least towards a virtio socket for this
anyways)
=> virt-install: Quiet HTTP logs

src/cmd-build
If we don't do this we end up with an image with MCS labels which means
that a subsequent run of a container (i.e. `coreos-assembler run`) will
fail.
With this we go from:
```
system_u:object_r:container_file_t:s0:c255,c505
```
to:
```
system_u:object_r:container_file_t:s0
```
Fixes #292
=> build: remove MCS SELinux labels from built image

README.md, build.sh
This adds the cosa bash function, which brings support for various
environment variables to tweak functionality at runtime. Having this
functionality allows us to overhaul the rest of the documentation to
use it instead of adding new aliases in various places.
=> README: add coreos-assembler bash function, overhaul docs

src/cmd-build, src/cmd-buildextend-ec2, src/cmd-buildextend-openstack, src/cmdlib.sh
It would be preferable to use just data from the build
meta.json rather than having to pickup some content from
there and some from manifest.json from the "configs" repo
which could have changed since the last build occurred.
=> buildextend*: use data from build meta.json

src/image-base.ks
This enables platforms like kubernetes to limit the storage of
containers so malicious actors in a multi-tenant environment
can't eat up a ton of storage.
https://bugzilla.redhat.com/show_bug.cgi?id=1658386
=> kickstart: enable prjquota for quota enablement

Dockerfile, Dockerfile.rhel, build.sh, src/cmd-build, src/cmdlib.sh
Embed the source and meta-data about the  container build _in_ the container as part of enabling COSA to act as a Koji Content Generator. The spec for Koji requires that we capture information about the build, including the source so that someone can re-create the build.
=> Koji Content Generator prep work

src/cmd-init
Do the checkout directly now that pushd sets the working directory
to "config". Previously gave an error on the directory "config"
not existing.
=> init: drop -C option in git checkout in --branch

src/virt-install
A lot of changes landed in f29's virt-install; among them
support for local ISOs was refactored a lot.  By passing explicitly
the path to kernel/initramfs we don't need to rely on detection
heuristics to find them.
Tested to work on both f28 and f29 (with virt-install 2.0+
from <https://bodhi.fedoraproject.org/updates/FEDORA-2019-c38a307cd5>)
See https://bugzilla.redhat.com/show_bug.cgi?id=1659242
=> virt-install: Work with f28 and f29

src/cmdlib.py
Now you can use run_verbose to retrieve the output and parse it.
```
p = run_verbose([ls], capture_output=True)
print(p.stdout)
```
=> cmdlib.py: run_verbose() allow capturing output

src/deps.txt
grub2-pc is a bios (and x86_64 only) specific package. Installing
grub2 pulls in the correct binary on all arches where grub2 is the
bootloader in use.
Signed-off-by: Dennis Gilmore <dennis@ausil.us>
=> install grub2 not grub2-pc

src/virt-install
Fixes a virt-install deprecation warning about just saying `7`.
=> virt-install: Use rhel7.6

src/cmd-build
The change to put metadata about the container in the builds
broke my development workflow; only do that if we are using
the main container.
=> build: Don't inject container build info if not present

Makefile
This makes sure `sudo make install` keeps working for folks running from
inside their pet containers.
=> Use `ln -sf` to help in-container upgrades

Makefile
My `makesudoinstall` script:
https://github.com/cgwalters/homegit/blob/89c3a7e934695ffc8da50ae100b497b1be058b46/dotfiles/bashrc#L17
broke due to the previous change to move the binary into the srcdir.
=> Makefile: Fix `make install` into empty DESTDIR

src/cmd-build
Change the code so that it's prepared to handle e.g.:
`coreos-assembler build qemu metal-uefi metal-bios openstack`.
There's more work we'll need to do for adding any more image
types, this just lays the groundwork.
=> cmd-build: Refactor to support multiple artifact types

src/cmd-build
The docs and syntax for these are confusing...need to rewrite this
in "not bash".
=> cmd-build: Fix use of bash arrays

src/cmd-init, src/cmdlib.sh
Since it's a cache, let's support deleting it.  I killed a build
that was too slow and got a stale lock file in my cache and wanted
to be able to just `rm` it.
=> Auto-recreate `cache.qcow2` if deleted

src/cmdlib.sh
This address #320 by allowing for Opendshift s2i builds to work in 3.9. Example:
```
strategy:                                                                                                                        
dockerStrategy:                                                                                                                
env:                                                                                                                         
- name: GIT_URL                                                                                                          
value: https://github.com/coreos/coreos-assembler                                                                                          
- name: GIT_REF …
```
=> src/cmdlib.sh: Work-around for OpenShift 3.9 not including .git [#320]

src/cmd-build, src/cmd-init, src/cmdlib.sh
Previously, `virt-install` was using a `*` wildcard, which would cause a failure if you had more than one ISO in the working directory.
This changes how `virt-install` is called, by providing an explicit path to the install ISO that was used during the `init` phase.
This was accomplished by moving some of the ISO logic into `cmdlib.sh` and exporting additional env vars to the rest of the tooling that way.
=> provide explicit path to ISO for `virt-install`

src/cmd-build
Since the summary could contain double quotes and JSON requires
double quotes to be escaped we need to escape them before feeding
it into `jq`.
Fixes #327
=> build: handle double quotes in summary

build.sh
The FAHC stream was absolutely critical when coreos-assembler
was actively driving fixes/development in rpm-ostree.  Today
that isn't the case as much.  While I think we should
still ship git master rpm-ostree in cosa, we don't need to do
so right at this moment.  We can wait until we solve
https://github.com/coreos/fedora-coreos-tracker/issues/84
Closes: https://github.com/coreos/coreos-assembler/issues/336
=> build: Drop FAHC

src/cmdlib.sh
Allow use of a mirror for the installer image.
=> src/cmdlib.sh: Allow use of a mirrors for getting the installer ISO.

build.sh, src/cmdlib.sh
Some versions of Openshift [1] do not include `.git` when building Docker containers [2]. In [3], we discovered that Git submodules are also affected. Further, since `mantle` run `git describe --dirty`, check on its source is insufficient. 
This is a follow-on PR to #320 that resolves #340.
=> Ensure git submodules work with Openshift [#340]

src/cmd-run, src/cmdlib.sh, src/gf-oemid
`qemu-kvm` is going away in Fedora; invoke qemu how libvirt does it.
Similarly on RHEL, it's in `/usr/libexec` as QEMU is an implementation
detail of libvirt (or something), so let's find it there.
=> Find qemu in /usr/libexec or via qemu-system-$(arch)

Makefile, README.md
This allows for us to save some keystrokes. Also added
cosa -> coreos-assembler symlink to make it support
the "running inside the container" use case as well.
Fixes #291
=> README: Use `cosa` in examples

build.sh
The update made it into stable so no longer need to pull from
updates-testing.
=> build.sh: pull virt-install from stable repos

src/cmd-oscontainer, src/deps.txt
Against my better judgement, I've been trying to get the EL7 build of the `cosa` image to be usable.  This may not be all the required changes, but it got me to a point where I could build the image and then run `fetch/build/run/shell/compress` successfully.
The last papercut noted [here](https://github.com/coreos/coreos-assembler/pull/329#issuecomment-461610378) was solved by @cgwalters suggestion to use `qemu-kvm-rhev`.  (On that note, #329 is required for these fixes to be useful)
I also had to tweak the `deps.txt` to get `syslinux` successfully installed (although, I did not test generating an ISO)
Finally, the `cmd-oscontainer` script needed a small change to use `.format()` instead of f-strings.
Depends: #329
=> EL7 compatibility fixes

Dockerfile, Dockerfile.rhel, build.sh, src/cmdlib.sh
(Updated description Feb 13)
When testing builds of the container image using different distros
(Fedora/EL7), it is possible for the image build to complete
successfully, only to find out that the `preflight()` check in
`src/cmdlib.sh` bails out because an RPM was not installed.
This change introduces `depcheck()` as a way to verify that the
requested RPMs were installed.  The new function is used in the
`build.sh` script and as part of `preflight()` in `src/cmdlib.sh`.
=> add depcheck() to verify RPMs installed

src/cmd-build
I'm often just iterating on the OSTree content itself and don't require
new images. In such cases, it's a waste of time to wait for images to be
generated when all I want is the treecompose. But using
`coreos-assembler build` is still more convenient than dropping down to
`rpm-ostree compose tree`, especially with the virtualization wrapper.
Add a new `--ostree-only` option in which we only generate a commit to
the OSTree repo. This is a natural extension of #302. Crucially though,
we still create a build directory under `builds/` with metadata about
the built commit. The only practical difference is that there are no
image files and no subkeys under `images` in `meta.json`.
(I didn't bother breaking the idempotency coupling here wrt the
kickstart since (1) it's going away, and (2) this …
=> src/cmd-build: Add `ostree` target

README.md
Update the example to only include the ca-trust directory
so that if you are using a different OS for the COSA container
vs your host (i.e. Fedora Laptop with EL7 COSA container) you
can use the rpm gpg keys from the container rather than from
your host.
=> README: improve sharing certs example

src/cmd-buildextend-installer
Moved from isolinux->installer based on code review
from a PR to fedora-coreos-config repo.
=> buildextend-installer: rename dir from configs

src/libguestfish.sh
This is prep for making `gf-oemid` work on UEFI, which we need
for e.g. aarch64.
=> libguestfish: Mount /boot/efi if present

build.sh
This fixes a regression in 1e2db9443e064573efb7902204081e629156e4d2
=> build: fix sourcing of cmdlib.sh in write_archive_info

src/cmdlib.sh
I want to be able to pass e.g. `RPMOSTREE_PRESERVE_TMPDIR`,
and also additional arguments when debugging/hacking on rpm-ostree.
=> Pass `-E` to sudo, add RPMOSTREE_EXTRA_ARGS

src/cmd-run, src/cmdlib.sh, src/gf-oemid
Also when using qemu make sure to account for arch-specific options.
WIP because it's more for awareness of the changes needed so far. I can build a FCOS image but when running it I'm not dropped into a console.
=> qemu-kvm is not available in other arches

Dockerfile, src/cmd-oscontainer, src/cmdlib.sh, src/oscontainer.py, src/supermin-init-prelude.sh, src/vmdeps.txt
@miabbott is the author; I worked with him for testing this.
Previously, `src/cmd-oscontainer` was a Python script that would run both `podman` and `buildah`. However, if you are running in unpriveldged context, both would fail. This extends the supermin appliance to include the `podman` dependencies and `src/cmd-oscontainer` invokes `oscontainer.py` using the `runvm` function when appropriate. This enables builds to happen in an unprivileged context.
=> src/cmd-oscontainer: invoke runvm when running with out priviledges

src/gf-oemid
The command returns the string `true` or `false`.
The exit code is successful if it was able to determine
the existance of the file, not if the file exists or not.
i.e. rc=0 + value == 'false' is valid.
=> gf-oemid: fix logic for `coreos_gf exists`

src/cmd-oscontainer
The wrapper script was using `set -x`, making the output very chatty.
Just print an `info` message about the unprivileged case.
=> src/cmd-oscontainer: quiet the output from wrapper script

src/cmd-oscontainer
We need to actually exec the script.
=> oscontainer: Fix the --privileged case

src/cmd-buildextend-installer
If I mount the ISO image and try to serve it over HTTP
(for PXE) I end up with some permission denied errors
because the initramfs is not world readable.
=> buildextend-installer: fix perms on initramfs.img

src/image-cloud.ks
Right now in FCOS, VMs are getting *two* IP addresses when testing
locally in libvirt. The root of the issue is that the first request in
the initrd is using a different client ID than the one from NM in the
real root. This throws off at least dnsmasq, which then refuses to give
out the same IP again. Tell NM to also use the MAC address as the client
ID, to match what `dhclient` also does in the initrd.
For more background information, see:
https://github.com/coreos/fedora-coreos-config/issues/58
Closes: coreos/fedora-coreos-config#58
=> image-cloud.ks: Use DHCP_CLIENT_ID=mac

src/cmdlib.sh, src/oscontainer.py, src/supermin-init-prelude.sh, src/virt-install
In some cases configuration files outside the supermin appliance are  needed inside. For example, `cmd/oscontainer` might need registry  credentials to push the container. RUNVM_CONFIG_FILES will take a string of NAME=FILE, where NAME will be an environment variable and FILE will point to the inside location.
Finally, this mock `sudo` to a function in the supermin appliance. Since the VM is running as root, the extra calls to `sudo` are superfluous.
=> src/cmdlib.sh: improve virt runtime environments

src/cmd-build, src/virt-install
We were still passing `--variant` even in "legacy mode" when an
external `.ks` was provided.  This injected our internal kickstarts
and could break things.
=> build: Don't inject internal KS in legacy mode

Dockerfile, build.sh, src/cmd-build, src/cmd-init, src/cmdlib.sh
It's part of the implementation detail of cosa.  Let's embed
it inside our container rather than downloading it dynamically.
This ensures that if you have the container you have *all* of the tools;
there's nothing separate to deal with and mirror.
It makes building the container more painful, but eh.
=> Include Anaconda in the container

src/cmd-build, src/cmdlib.sh, src/virt-install
For Red Hat Enterprise Linux CoreOS, we will be shipping updates
via "oscontainers"; see the `oscontainer` command history for
some more details.
Support not specifying a ref in the manifest.  The semantics
result in the ref being deleted in the disk image.
Today the RHCOS build system adds a bit in the kickstart to do
this, but we want to get away from supporting external kickstarts.
This patch is my 3rd attempt at implementing this; it turns out
to be by far easiest to override the manifest and add the ref temporarily.
Anaconda today requires a ref and not a commit.  And if we didn't
have a ref in the local repo, then the prune logic goes wrong, and
it also breaks `automatic_version_prefix` etc.
So we have a `tmpref-${name}` ref in the repo, and just strip
it from the generated disk …
=>  Support not specifying a ref in manifest

src/cmd-buildextend-ec2
`ore` will reuse snapshots that have the same name; this can
break things with "developer" jobs.  The intention here is that
developer jobs provide `--name-suffix`.
=> buildextend-ec2: Add --name-suffix

build.sh, src/cmd-buildextend-installer, src/deps.txt
This allows the ISO image we produce to support UEFI
and legacy boot at the same time.
=> buildextend-installer: add support for UEFI boot

build.sh
I have hit this on ppc64le as efi dir tree exist on /boot, but the tree is empty.
=> build.sh: add "-r" flag to xargs to not error out if no file(s)/dir(s) exist

src/cmd-build, src/gf-oemid
We were previously hitting issues with the final images having an MCS
label. This turned out to be due to the `gf-oemid` using `/tmp` within
the container. In the unprivileged path, the whole container filesystem
uses MCS and so the image created there would inherit that label.
Just fix this by making `gf-oemid` use a tmpdir in the destination path;
we're already in a temporary work directory anyway when calling it from
`cmd-build`. Staying on the same bind mount also ensures that we're not
copying the image across filesystems (and with reflinks on, even the
first copy is a no-op!), so this should make the build process a bit
faster too.
Finally, this also allows us to drop the call to `chcon`, which is
problematic for systems without SELinux enabled on the host.
=> gf-oemid: Don't use the container's /tmp

Makefile
Simplify things and have it just point to `coreos-assembler` in
the bindir.
=> build: Fix cosa link in container

src/cmd-shell
It doesn't make sense to pass an array of arguments to `bash -c`.
Fixes doing e.g. `cosa shell sleep 5`.
=> shell: Fix re-execution

src/virt-install
Seems to work well here, did a few runs.
=> virt-install: Cut Anaconda RAM to 1024

deps-aarch64.txt, deps-x86_64.txt
The arch specific deps files exist in src/deps-$arch.txt. However the
Dockerfile COPY only copies from the base dir. This PR adds symlinks in
the same way as the base deps.txt file is symlinked.
=> Fix COPY of arch specific deps

build.sh, src/cmdlib.sh
This avoids a situation where one of the deps is empty, causing depcheck
to fail. Additionally it allows the rpm -q to run against one list
instead of 2.
=> Run one depcheck for all deps

deps-ppc64le.txt, src/deps-ppc64le.txt
At this point ppc64le doesn't have specific pkg dependencies, this PR
adds a placeholder file containing a blank line to ensure the pkg
install and depcheck tasks still works.
=> Add ppc64le specific deps file

src/supermin-init-prelude.sh
Add `/dev/shm` to Supermin appliance. This was surfaced when we switched from Fedora 28 to Fedora 29 for our RHEL building.
=> src/supermin-init-prelude.sh: mount /dev/shm

src/virt-install
For UEFI domains we get the following error unless we add
`--nvram` to the call to undefine:
```
error: Failed to undefine domain coreos-inst-597-1552671442
error: Requested operation is not valid: cannot undefine domain with nvram
```
=> virt-install: fix virt undefine error

src/image-cloud.ks
Instead this will be handled by our Ignition bootloader logic:
https://github.com/coreos/ignition-dracut/pull/57/commits/c62a108c79db49cecb9f323d6567d33a86fa6dc7
=> Drop rd.neednet ip=dhcp from default kernel arguments

src/virt-install
Support different distros by adding explicit installclass option to
image.yaml, which is required for Fedora anaconda to find the correct
directory to use for EFI builds.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>
=> virt-install: add optional installclass parameter

build-deps.txt, src/deps-x86_64.txt, src/deps.txt, src/gf-oemid
Anyone wanting support for this can use the last stable tag `0.4.0`.
=> build: Drop support for el7

src/cmd-run
We already ship `coreos-useradd-core.service` in FCOS - we should
use that, now that it's not broken:
https://github.com/coreos/fedora-coreos-config/pull/69
=> cmd-run: Don't add `core` in Ignition

build.sh
We don't use `cmdlib.sh` in `build.sh` and it seems a bit wasteful to
bring in the entire library just for the `info()` function, so just
use `echo` instead.
(Otherwise, we are trying to invoke the `info` command itself)
=> build.sh: use echo instead of info()

src/build_rpm_from_dir, src/cmdlib.sh
This patch adds support for an overlay RPM defined by a rootfs in the
source repo at `overlay/`. Unlike FAH, FCOS is much more opinionated
about various things. And these opinions express themselves through e.g.
config file overlays, systemd units, Ignition base configs, etc... These
files don't clearly belong in any particular "component" package, but
rather provide the glue that makes FCOS feel like FCOS. This is similar
to CL's [init](https://github.com/coreos/init) package.
Right now, a lot of these files are just written out as part of the
postprocess script in the treefile. Splitting them out has the major
benefit of being able to track them in the rpmdb so one actually knows
where they come from. It'd also mean a cleaner manifest and easier
hacking on those files and tracking in …
=> Add support for building an overlay RPM

src/cmdlib.sh
Otherwise we'll error out if the user has no overrides.
Regression from #414.
=> cmdlib: Create overrides dir if there's an overlay

src/cmd-init
Create this directory upfront to eliminate an additional step of
creating it manually when overriding RPMs locally.
Originally brought up in #427.
=> cmd/init: Create empty overrides/rpm directory

src/build_rpm_from_dir
Just before pushing out our new RPM, just nuke all the older ones in
there so we only ever have a single overlay RPM at a time. This does
mean that we lose caching across overlays that match builds from two or
three builds ago, but that's a pretty rare case. And building this RPM
is super cheap.
=> overlay: Only keep the latest overlay RPM around

src/cmdlib.sh
Some newer aarch64 HW (e.g. osprey) doesn't support the default GICv2
used by qemu. So explicitly pass in the GIC version depending on the
host.
This fixes the following error message:
qemu-kvm: PMU: KVM_SET_DEVICE_ATTR: Invalid argument
qemu-kvm: failed to set irq for PMU
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1661976
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>
=> cmdlib.sh: fix GIC version on aarch64

src/cmd-buildextend-openstack, src/cmd-buildextend-vmware, src/cmd-compress
This unifies all the images (qemu, metal, openstack, vmware) to
provide an uncompressed size and compressed size in the `meta.json`.
This follows the same pattern of providing a SHA256 for the
uncompressed and compressed versions of the images.
=> add 'uncompressed-size' and 'size' for images to meta.json

src/cmd-build, src/virt-install
Requires: https://github.com/coreos/coreos-assembler/pull/422
For RHEL CoreOS we ship via an oscontainer; today cosa doesn't
support configuring that, and our pipeline opens up the image
and changes the origin, and fixes up the sha256sum.
There are probably other tweaks people will want to make too.
Previously those types of things ended up in a `%post` run
via Anaconda.  This hook just provides the disk image; the
caller can use e.g. `libguestfs` on it (as the RHCOS pipeline
will do).
This operates before we do the checksum, so we don't do silly
things like checksumming, edit, checksum again.
=>  Support `image-postprocess` hook in the configdir

src/deps.txt
This was broken out in https://src.fedoraproject.org/rpms/ignition/pull-request/26
=> deps.txt: just specify /usr/bin/ignition-validate

src/cmdlib.sh
This patchset fixes #410 and make it possible to build FCOS images on aarch64 using unprivileged containers. The only thing remaining to successfully run the built image is #425: using newer `ignition` package with overrides and making sure autologin is at `ttyAMA0`.
=> Fix running cosa in unprivileged mode on aarch64

src/cmdlib.sh
This addresses a regression introduced in
3f5aa3810febff5b2a929156bbb5fe86ed10cb51.
When running on non `aarch64` architectures, `arch_args` was would be
appended to the `qemu-system-x64_64` command as as ''. This causes qemu
to assume that there was an IDE CDROM attached, resulting in the error
of:
`qemu-system-x86_64: Initialization of device ide-hd failed: Device needs
media, but drive is empty`
=> src/cmdlib.sh: fix broken x86-64 supermin builds

src/cmd-compress
Add option to skip compression of image artifacts.  This is useful for
products that can use URLs directly like VMWare.
=> cmd-compress: do not compress ova files 

src/cmd-buildextend-installer
In restrictive environments `virt-make-fs` fails when prepping the
tar-in file. This change cleans up the `cmd-buildextend-insteraller` to
use explicit paths and uses a temporary tarball as input to
`virt-make-fs`. The tarball is made by hand and strips setuid, setgid
and forces ownership to root.
=> cmd-buildextend-installer: strip setgid for ISO generation

src/image-cloud.ks
With this I'll have to find a way to remove my "eth0 FOR LIFE" tattoo.
This came up in a bigger discussion with OpenStack:
https://github.com/coreos/ignition/issues/769#issuecomment-475825814
The history behind disabling persistent NIC naming in Fedora/RHEL
is...long.
I think we have an opportunity now to do a clean break with that
history.  Let's use persistent NIC naming even for cloud environments
like AWS.
This massively reduces the delta between our "metal" and "openstack"
images.  We just have console tweaks and `no_timer_check`.
Note that with https://github.com/coreos/ignition-dracut/pull/57
we actually do do DHCP on all interfaces anyways, so the hardcoded
`eth0` here made even less sense.
=> image-cloud: Use persistent NIC naming, drop eth0

src/cmd-buildextend-installer, src/cmd-compress
The installer ISO generation already pulls the initramfs and kernel
from the ostree repo so this just piggybacks off that and copies the
artifacts to the build directory.  Having the initramfs and kernel is
useful for tools like virt-install and OZ to look at a tree and boot
the kernel with fine grain control over the kernel command line.
=> buildextend: create initramfs and kernel artifacts

src/cmd-buildextend-installer
This makes all installer artifacts names consistent and scoped with
"-installer".
=> installer: rename iso artifact

src/cmd-buildextend-aws
Copy the uploaded image to our output directory, not just to AWS.  This keeps all release images in one place, and is convenient for debugging and for users who want to upload their own images.
=> buildextend-aws: remember to save the uploaded artifact

src/cmd-build, src/cmd-buildextend-openstack, src/cmd-buildextend-vmware, src/cmd-compress, src/cmdlib.sh
See discussion at https://github.com/coreos/coreos-assembler/pull/450#discussion_r270260281.
=> cmd-*: store JSON sizes as numbers rather than strings

src/gf-platformid
Everything should have switched over to ignition.platform.id.
=> gf-platformid: stop generating coreos.oem.id

src/cmd-build, src/estimate-commit-disk-size, src/image-base.ks, src/virt-install
We don't need to use a full 8GB raw for bare metal; we can shrink
it to fit the space, assuming it will expand to the real physical
disk size.
=> Estimate commit size for bare metal

src/cmd-build, src/write-commit-object
Save the raw commit object in the builddir;
it can be useful to provide the previous commit during
builds, and this avoids a need for the full OSTree repo.
Particularly for RHEL CoreOS where we ship via oscontainer, this
will help us avoid needing to fetch the previous oscontainer, when
all we need is the previous commit object.
=> build: Save raw commit object in builddir

src/cmd-build
Things should be parsing the build metadata now.
=> build: Remove unversioned qemu link

src/gf-platformid
Solves #361
Solution provided by Ben Howard
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>
=> gf-platformid: used glob for EFI grub.cfg location

src/gf-platformid
Since aarch64 has only EFI booting, the linux entry is just 'linux' not
'linux16'.
Fixes #458
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>
=> gf-platformid: inject platform.id on aarch64

src/cmdlib.sh
While we already record the commit that `coreos-assembler` is built
from, it would be useful to know what branch the commit was from, too.
=> src/cmdlib: record git branch in cosa JSON

src/libguestfish.sh
If you are using multiple invocations of the `coreos_gf_run` and
`coreos_gf_shutdown` in the same script, it would fail because the
`GUESTFISH_RUNNING` and `GUESTFISH_PID` would remain set.  This unsets
them as part of `coreos_gf_shutdown`
=> src/libguestfish: unset GUESTFISH* vars during shutdown

src/gf-platformid
Drop the workaround code we added for
https://github.com/coreos/coreos-assembler/issues/198
Due to later refactoring we started executing qemu in other places
without this wrapper.  I think probably the original reporter
should build a derived container from cosa that wraps qemu temporarily.
I also don't think we should encourage the nested virt path on VMWare/etc;
anyone who is serious about building Linux systems should be able to
get either a bare metal Linux machine somewhere locally or in the cloud
(Packet, AWS i3.metal etc.) or do e.g. GCE nested virt.
=> gf-platformid: Drop pmu=off injection and qemu wrapper

src/cmdlib.sh
I'm switching my devel environment to https://github.com/debarshiray/toolbox/
and I think having CAP_SYS_ADMIN in the Current set was just a bug in my
`podman` scripts.  We really want to check the bounding set.
It was a pleasant surprise that `cosa build` worked just fine here,
including the recursive containerization from `bwrap`.
=> cmdlib: Accept CAP_SYS_ADMIN in bounding set

src/cmd-run
Tweak the synopsis to clarify that one has to use `-d` to use a specific
image, and mention that the default behaviour is to use the latest
build.
=> cmd-run: Tweak help output

src/image-metal.ks
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/142
=> Add ignition.platform.id=metal for bare metal

src/cmd-buildextend-ec2
tmp_img_aws_vmdk is still tmp_img_ec2_vmdk in rhcos-4.1 branch
since we are on ignition v1, so the cherry-picked commit will
cause cosa to fail.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>
=> buildextend-ec2: fix var naming

src/cmd-compress
Follow up to https://github.com/coreos/coreos-assembler/pull/459
When building just ostree, the broken symlink was causing problems.
=> compress: Remove unversioned qemu symlink code

src/image-cloud.ks, src/image-metal.ks
Being able to see bootup progress and log in through the serial console
is also relevant for bare metal nodes.
=> Also connect to consoles for bare metal

src/cmd-build, src/virt-install
If we have 9p, let's use it to provide the ostree repo to Anaconda;
see ostreedev/ostree#975
I'm mainly doing this because something is breaking Anaconda's ostree
pulls in my usage of cosa inside `toolbox`; this works around it
reliably and is faster.
(We still need the webserver though; I played around with trying
to do fetches over a virtio-serial but eh...let's just wait
a bit and virtio-fs will solve this)
=>  build: Generalize 9p usage, accelerate installs if available

src/gf-anaconda-cleanup
This definitely shouldn't be in the image by default.
=> anaconda-cleanup: Remove /etc/resolv.conf

src/virt-install
The kernel/systemd spew isn't at all interesting and makes
useful stuff like the size estimate scroll off my screen.
Anaconda prefixes its log messages with `anaconda` conveniently,
so let's just show that.
=> virt-install: Only show logs from anaconda

src/cmd-build, src/image-base.ks, src/image-cloud.ks, src/image-metal.ks, src/virt-install
Followup to: https://github.com/coreos/coreos-assembler/pull/473
Since the only difference was `no_timer_check`, and we don't
care about that, let's just drop it.
Then switch to using `gf-platformid` for the metal images, which
as a side effect also ensures we inject `coreos.oem.id` which
will help Ignition spec2x systems.
(What is still different between metal and cloud is sizing, we
shrink metal disks to fit)
=> Unify metal and cloud builds further

build.sh
Since a new one that supports spec v3.0.0 isn't in Fedora proper yet.
Closes: #448
=> build.sh: Add f29-coreos-continuous repo

src/virt-install
This is simpler than forking off a process actually and ensures
lifecycle binding.
(This came out of some attempts to use virtio-serial)
=> virt-install: use an internal webserver

Dockerfile, build.sh
This will allow us to match the content we're now composing. It also
means that from this point on, f29 is strictly about Fedora Atomic Host,
while f30 is strictly about Fedora CoreOS. This means more flexibility
wrt backwards compatibility.
The odd one is Anaconda; we're still using the f29 one for now. See
comment in patch for details.
=> Rebase tree to f30

Dockerfile.dev
The production Dockerfile can take upwards of 20-30 minutes for
to build. The new Dockerfile.dev allows a developer to quickly build a
derivative image with new dependencies, Mantle and COSA without having
to wait.
=> Dockerfile.dev: add a faster Dockerfile for developer use-cases

src/cmd-dev-overlay
I want to add some more testing of OS updates to
https://github.com/openshift/machine-config-operator/
and it's not really necessary to do a full e2e build - just
adding a dummy file to the oscontainer is going to be sufficient
to start.
Related to this, requiring privileges (like `compose tree`) does
would be a huge ergonomic hit.  This script aims to improve
the code that landed for overriding the kubelet in Origin:
https://github.com/smarterclayton/origin/blob/4de957b019aee56931b1a29af148cf64865a969b/images/os/Dockerfile
Once this lands I'll do a PR to origin to change it to use coreos-assembler.
(though that image is enormous, maybe we want explicit layering for
things that don't need image building, also we really need to cut out
Anaconda)
Side note: while writing this I ended up …
=> dev-overlay: New command

src/gf-anaconda-cleanup
In particular the presence of `/etc/resolv.conf` was confusing,
even though it wasn't used.
Delete everything except `/boot` and `/ostree`.
=> gf-anaconda-cleanup: Remove cruft in /

src/gf-anaconda-cleanup
Need to prefix with `glob` otherwise it'll just try removing a file
literally named `*`.
=> Fix nuking everything in /var

src/gf-anaconda-cleanup
In particular @bgilbert pointed out that we had
`/etc/sysconfig/network-scripts/ifcfg-enp2s0` which is horrifying.
Though it turns out we need `/etc/hostname` and `/etc/vconsole.conf`,
otherwise `systemd-firstboot.service` kicks in.  We should probably figure
out having Ignition default to doing everything systemd-firstboot
does.
=> gf-anaconda-cleanup: Remove cruft in /etc

src/virt-install
I kept having to kill these in my dev container.
=> virt-install: Ensure tail process is lifecycle bound with us

src/virt-install
When I installed the OpenShift extension for VS Code that started
spawning a JVM in the background which for probably terrible
reasons listens to port `8000` by default.  We should also
do dynamic ports at some point.
Then it also turned out that Python's raw thread API has
the rather unfortunate semantics that an exception thrown in a
thread just prints to stderr and continues.
I think we really want is to use the futures suggestion from
https://stackoverflow.com/questions/2829329/catch-a-threads-exception-in-the-caller-thread-in-python
but I'm not feeling it's worth trying to figure out how to rearchitect
this code to use futures right now.
=> virt-install: Exit with error if port is in use

src/gf-anaconda-cleanup
This reverts commit 1a005c024b55f80a1e520ff91a640e277b375bbc.
See https://github.com/coreos/coreos-assembler/issues/500.
=> [rhcos-4.1] Revert "Fix nuking everything in /var"

src/virt-install
We lost this in 5571bca. We need it to get streaming Anaconda logs.
=> virt-install: Add back --console=log.file

src/gf-anaconda-cleanup
In particular @bgilbert pointed out that we had
`/etc/sysconfig/network-scripts/ifcfg-enp2s0` which is horrifying.
Though it turns out we need `/etc/hostname` and `/etc/vconsole.conf`,
otherwise `systemd-firstboot.service` kicks in.  We should probably figure
out having Ignition default to doing everything systemd-firstboot
does.
(cherry picked from commit 516de82c77f2cb903b061ada2d6f0d25dd34b9ee)
=> [backport] gf-anaconda-cleanup: Remove cruft in /etc

src/gf-anaconda-cleanup
Don't nuke all of `/var`; there are some interdependencies there with
mountpoints (see discussions in [1]). For now, just nuke Anaconda
specific things we don't want.
[1] https://github.com/coreos/ignition-dracut/pull/79
=> Nuke anaconda leftover bits from /var

src/cmdlib.sh
The first is useful for `env COSA_RPMOSTREE_GDB="gdb --args"`.  Make
the name of the second consistent.
=> Add COSA_RPMOSTREE_GDB env, change to COSA_RPMOSTREE_ARGS

src/cmdlib.sh
Previously, we would go through the motions of creating a temporary
repo if the `overrides/rpm` directory was present, even if there were
no RPMs in the directory.  This changes the process to only create the
repo if RPMs are actually present in the directory.
=> src/cmdlib.sh: only use RPM overrides if RPMs present

src/virt-install
The `setpriv --pdeathsig` doesn't seem to be working on my system. Seems
like the parent `sh -c` does get cleaned up correctly, but not *its*
child `tail` process.
Use instead the built-in `--pid` flag which tells `tail` to stop
following and exit when we die. The `grep` naturally dies when `tail`
exits since its stdin is closed (and the parent `sh` soon follows).
=> virt-install: Use tail --pid=$PID to ensure death 💀

src/cmd-build, src/cmd-buildextend-metal, src/coreos-assembler
We don't want to have to create metal images upfront if the qcow2 is
rubbish.
Addresses the major part of #405 (but not the part about making `build`
and `buildextend` work better together yet...).
=> Split out metal-{bios,uefi} into buildextend-metal

src/cmd-build
If the ref is temporary, then it shouldn't show up the final build
metadata.
Noticed this while testing #515.
=> cmd-build: Drop temporary refs from build metadata

src/cmd-run
This is useful when we want to be able to hack on a VM that has a bit
more persistence, but not necessarily go the full `virt-install` path
(or if you can't use libvirt for whatever reason). Basically make using
`cosa run` as a glorified `qemu-kvm` easier.
=> cmd-run: Add --persist-to-img IMG

src/gf-anaconda-cleanup
Drop the default `localhost.localdomain` that Anaconda writes. Just
match CL here by not having any default `/etc/hostname`. This will be
populated automatically on certain clouds, while elsewhere, it'll need
to be written through the Ignition config. (In the latter case, not
having it baked in means one doesn't need `overwrite: true`).
=> gf-anaconda-cleanup: Also nuke /etc/hostname

src/write-commit-object
Rename the OSTree commit object to `ostree-commit-object` to be more
explicit. I'd like the term "OSTree commit" to refer to the whole tree.
Split out of #515.
=> cmd-build: Rename OSTree commit object

src/image-base.ks, src/virt-install
FCOS wants to disable SMT by default; RHCOS doesn't.
https://github.com/coreos/fedora-coreos-tracker/issues/181
=> Allow image.yaml to specify extra kernel args

src/cmd-buildextend-vmware
These were both suggested by contacts at VMWare.
The change here to the "vmx" value will prevent the OVA from being used on ESX versions that are older than what we are prepared to support, and is thus a desirable change from a customer experience perspective.
The OS change may be more cosmetic.  Eventually there will also be a "rhel8" equivalent, which we may want to switch to.
=> tweak system and os_type for OVA

src/cmd-buildextend-metal
getopt requires a `:` in order to specify an option takes an
argument.
=> buildextend-metal: --build takes an argument

src/cmd-build, src/cmd-buildextend-installer, src/cmd-buildextend-metal, src/cmd-clean, src/cmd-init, src/cmdlib.py, src/cmdlib.sh, src/prune_builds
Rather than keeping OSTree data separately in the toplevel `repo/`, make
it part of the build directory. This solves a bunch of issues and makes
things conceptually clearer.
See discussions in:
https://github.com/coreos/coreos-assembler/issues/159
Still testing this, there might be some more backcompat polish needed.
=> Move OSTree commit into build directory

src/cmd-build
And also sanity check that we're not passed unsupported targets.
Minor regression from #510. I think my thinking there was that we'd have
a `buildextend-qemu` so that an OSTree-only build could still later on
be extended if one wants. Though I didn't actually get around to
splitting it out.
=> cmd-build: Fix ostree-only builds

src/gf-platformid
In UEFI based image, grub.cfg contains linuxefi instead of linux16
Signed-off-by: Sinny Kumari <sinny@redhat.com>
=> gf-platformid: Check linuxefi while appending ignition.platform.id

src/cmd-kola, src/cmd-run, src/cmdlib.sh, src/coreos-assembler
Blocked by https://github.com/coreos/fedora-coreos-config/issues/2
=> Add a `kola` verb

src/cmd-run, src/cmdlib.sh
This will make ```cosa run``` work on platforms that don't support qemu_fw_cfg, although it is kind of useless as there is no ignition config. But IMHO this clearly document it and make us able to smoke test if it boots at all locally.
=>  cmd-run: switch to qemu image layering and injection of config.ign in to the /boot

src/cmd-buildextend-gcp
(cherry picked from commit 3ab57a13264f57abe67ce509099194a4842bda82)
=> src/cmd-buildextend-gcp: fix path for GCP tarball

src/cmdlib.sh
Using ttyS0 on ppc64le leads to crash in supermin init in not privileged mode(coreos-assembler fetch/...).
```
.
.
.
.
[    0.312625] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    0.313933]  sdb: sdb1
[    0.314762] sd 0:0:0:1: [sdb] Attached SCSI disk
[    0.315320] sd 0:0:0:0: [sda] Attached SCSI disk
[    0.323285] EXT4-fs (sda): mounting ext2 file system using the ext4 subsystem
[    0.325867] EXT4-fs (sda): mounted filesystem without journal. Opts: 
[    0.771603] SELinux:  policy capability network_peer_controls=1
[    0.844211] SELinux:  policy capability open_perms=1
[    0.844625] SELinux:  policy capability extended_socket_class=1
[    0.845144] SELinux:  policy capability always_check_network=0
[    0.845656] SELinux:  policy …
```
=> cmdlib.sh: Use terminal according to arch in vmrun

src/cmd-run
No reason to print this, we didn't do so before;
I found it confusing.
=> run: Remove "Creating temporary image" message

src/cmd-kola, src/cmd-run, src/cmdlib.sh, src/incomplete-hack-ign-3to2
It would be really extremely convenient for me if I could at least
`cosa run -d /path/to/rhcos.qcow2` when using cosa git master.
This prototypes out the start of a `ign-3to2` helper which
will also be extremely useful for people working on OpenShift/RHCOS
today.  If this works out we can elevate it to a toplevel command.
=>  Detect rhcos for Ignition spec 2, add start of 3to2 converter

src/cmd-buildprep, src/deps.txt
If we're trying to `buildprep` from a remote which doesn't have any
builds yet, don't error out. To do this, just use HEAD/HeadObject and
check for a 404 response code. E.g. for AWS, we still error out if the
issue is missing credentials.
Closes: #543
=> cmd-buildprep: Handle 404 for builds.json gracefully

src/cmd-buildprep
We should verify that the bucket exists when fetching from S3. If it
doesn't then it means that the user probably mistyped it or doesn't have
privs, and the future `buildupload` would also fail.
=> cmd-buildprep: Sanity check that bucket exists

build.sh
Otherwise, if it becomes inaccessible for whatever reason, any automated
process that rebuilds the container will essentially pull in older
versions of packages, which can cause regressions in pipelines.
=> build.sh: Set skip_if_unavailable=False on continuous repo

.gitignore, src/cmd-koji-upload, src/cosalib/build.py
- Ignore `*.pyc` and `*.pyo` files in `git`
- Move `Build` into `cosalib`
- Use `BuildError` instead of base Exception
- Fix docstrings
- Don't execute `build_artifacts` during initialization
- Add `meta` manipulation
**TODO**:
=> Move Build class into it's own package

src/cmdlib.sh
This is strongly related to https://github.com/coreos/fedora-coreos-config/pull/66
For development iteration, we want the ability to directly overlay
binaries.  This depends on
https://github.com/projectatomic/rpm-ostree/pull/1830
which adds rpm-ostree ability to inject ostree refs into the build.
We could implement this in cosa by building an RPM but I think that's
silly - we end up compressing the data only to immediately decompress it.
Plus, while there are advantages to having entries for files in the RPM
database, in practice we're lying about having these files built by RPM.
So let's just directly generate an OSTree commit from them and inject
that.
(In practice for *this* use case rpm-ostree could actually learn
a way to directly consume a directory, but indirecting via OSTree …
=> Add overrides/rootfs

src/gf-anaconda-cleanup, src/virt-install
A lot of backstory here, but essentially, we want Ignition to be able to
add users in RHCOS. This requires `/var/home` existing. To do this,
we either need to run systemd-tmpfiles, like FCOS, or just leave it
hanging around after Anaconda.
Since we're already doing the latter for `/var/lib` and `/var/log`, this
patch just extends it for `/var/home`. It's just easier to do this for
now rather than more involved fixes. This will be fixed the proper way
once RHCOS is bumped to spec 3 and inherits all the work that happened
in FCOS to support it.
Some more information about this in:
https://github.com/coreos/ignition-dracut/pull/79
=> Add `save-var-subdirs-for-selabel-workaround` key in image.yaml 

src/cmd-kola
Since it's way friendlier; if I can `cosa run` as non-root I should
be able to use `kola` too.
=> kola: Automatically use qemu-unpriv if non-root

src/cmd-build, src/cmd-fetch, src/cmdlib.sh
First, add `manifest-lock.json` to the list of magical files in the
source config which we check for.
Then, teach `fetch` and `build` to respect the lockfile by default, but
add an `--update-lockfile` option to the former allow bumping the
lockfile.
Finally, always generate an output lockfile from the compose and put in
the build dir as `manifest-lock.generated.json`.
This is the first step towards actually being able to make use of
lockfiles in the FCOS pipeline.
=> Add support for reading and writing lockfiles

src/deps.txt
This is needed for installing efi grub without anaconda
=> deps.txt: add grub efi modules

src/cmdlib.sh
I use cosa in the privileged path, and was trying out the PR
to remove anaconda which always uses a VM, and this failed
because it expected the `cache.qcow2` to exist.
=> cmdlib: Only add cache.qcow2 if it exists

src/cmd-buildprep
This is useful if e.g. you need to build in a directory, but store final
artifacts in a separate directory that might be e.g. a network
filesystem.
=> cmd-buildprep: Support local paths

Makefile, src/cmd-koji-upload
In the RHCOS pipeline, we were seeing an import error when trying to
use the `koji-upload` command.  This fixes the import error for that
case.
=> fix import of cosalib.build in pipeline

src/cmd-koji-upload
When run in the RHCOS pipeline, the `koji-upload` command has trouble
sensing the correct path to do the import of `cosalib`.  This change
allows us to catch the ImportError and try an explicit path instead.
=> src/cmd-koji-upload: conditionally use an explicit path for Python imports

bottlecap, src/cmd-build, src/cmdlib.sh, src/create_disk.sh, src/gf-platformid, src/grub.cfg, src/vmdeps.txt
* Only for qemu right now. Trying to make sense of the buildextend-metal, it looks like it's running anaconda again?
* Only tested with fcos
* We ought to not use yaml for image.yaml, it's a pain to parse
* Doesn't actually remove anaconda, just switches to not using it
=> Remove anaconda

src/cmdlib.sh, src/gf-platformid, src/supermin-init-prelude.sh
=> Fixes for privileged path

src/create_disk.sh
The hard-coded values of `fedora-coreos` prevents RHCOS from building. Also, by using `udevam` the hack for `sleep 2` can removed.
=> create_disk.sh: fix os deployment; use udev to settle partitions

src/cmd-buildextend-metal, src/gf-platformid
Also fail out on unsupported arches and continue using anaconda on
aarch64.
Tested on packet (bios) and that worked with the current fcos installer, ran through a cosa build on arm64 as well to confirm this doesn't break that.
Fixes https://github.com/coreos/coreos-assembler/issues/334
=> cmd-buildextend-metal: dont use anaconda on x86_64

src/cmd-buildextend-gcp
Our model is built on "immutable" version numbers, however it
can happen that e.g. a GCP build completes but a later stage fails.
If that happens, we may reassign the version number, and the correct
thing is to overwrite the build.
So always pass `--force`, and rely on the higher level pipeline
logic not overwriting builds that were successful.
=> gcp: Always --force

.gitignore, README-devel.md, pytest.ini, src/cosalib/cli.py, test-requirements.txt, tests/test_cli.py
- Base class which can be used by other Cli classes
- Sets up the logger
- Provides an environment variable driven argument method
- Appends env variables to env args help text
- Provides common arguments for build commands
This PR also provides > 80% test coverage for the code in this PR :smile: 
```
$ pytest tests/
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /var/home/steve/Tech/GITHUB/coreos-assembler, inifile: pytest.ini
plugins: cov-2.7.1
collected 3 items                                                              
tests/test_cli.py ...                                                    [100%]
----------- coverage: platform linux, python 3.7.3-final-0 -----------
Name …
```
=> cosalib/cli.py: Cli/BuildCli class for reusability

src/cmd-buildextend-gcp
Previous commit here was incomplete.  If you want to force a re-upload,
delete the metadata from a build.
=> gcp: Remove other uses of `force` arg

src/create_disk.sh
Use 256M for /boot since it may have up to three (two?) kernels +
initramfs's. With Container Linux we could get away with 128M since our
kernels and initramfs's were smaller, but we'd likely hit issues with
the fedora ones.
Dramatically shrink BIOS-BOOT. 4M should be plenty. The grub docs refer
to 1M as being enough[1] so this should be more than adequate.
Shrink the ESP by 4M. We hardly put anything in it. Could probably stand
to be smaller but I'm not sure the ramifications right now. All that's
in it is the shim, grub efi program, and a tiny stub config.
[1] https://www.gnu.org/software/grub/manual/grub/html_node/BIOS-installation.html#BIOS-installation
cc @martinezjavier especially about esp sizing
=> src/create_disk: use more reasonable sizes

src/cmd-buildupload
I think because we upload from a tempfile, the regular auto-detection
doesn't work. So explicitly set the MIME type when uploading.
This makes a difference in the FCOS Build Browser, where trying to open
the file doesn't just display it in the browser.
=> cmd-buildupload: Mark modified meta.json as JSON

src/cmd-build
If we initialized with `buildprep`, we won't have `ostree-commit.tar`.
If `cosa build` then detects no changes to the OSTree, but only to the
image it will try to avoid tarring by copying the previous build's
OSTree tarfile, which will fail. Just add a check for the file before
enabling that optimization.
=> cmd-build: Check if previous OSTree tarfile exists before copying

src/cmd-build, src/cmd-buildextend-metal, src/cmd-buildprep, src/cmd-buildupload, src/cmd-clean, src/cmd-koji-upload, src/cmdlib.py, src/cmdlib.sh, src/cosalib/build.py, src/prune_builds
Split out of #580. See individual commit messages for details.
=> Multi-arch build layout prep patches

src/cmd-buildextend-aws, src/gf-platformid
Fix coreos.oem.id not being set on RHCOS 4.2
=> gf-platformid: set legacy coreos.oem.id properly

src/cmd-compress
Allows FCOS to support XZ-compressed output artifacts. Changes
include parameterizing the compression algorithm option and
setting the default value to `gzip`.
Closes: #445
=> cmd-compress: Improve image compression algorithm

src/cmd-build, src/cmdlib.sh
This is prep for multi-arch. We'll be storing the lockfiles for all the
archs in the config repo alongside each other. So tag on the basearch
to the lockfile we actually look for and the one we generate.
=> lockfile: Add basearch to lockfile name

src/cmd-compress
As mentioned in #558, `--compressor` is more accurate than
`--algorithm`. Since the command is still fresh, let's just change it
now while nothing depends on it yet.
=> cmd-compress: Rename --algorithm to --compressor

src/cmd-build, src/cmd-buildextend-aws, src/cmd-buildextend-gcp, src/cmd-buildextend-installer, src/cmd-buildextend-metal, src/cmd-buildextend-openstack, src/cmd-buildextend-vmware, src/cmd-buildprep, src/cmd-buildupload, src/cmd-compress, src/cmd-tag, src/cmdlib.py, src/cmdlib.sh, src/cosalib/build.py, src/prune_builds
Only the last two commits are new here. The rest are from #590.
The strategy here is to create a `Builds` class and make use of it in all the commands instead of manually synthesizing paths to build dirs. Outside of cosa, one can still (and will continue to be able to) do this of course, though once the multi-arch layout comes into effect, it will require knowing which layout one is dealing with (which should be clear for e.g. pipeline code). For cosa itself, the `Builds` class will abstract over these differences, so all commands will keep on working regardless of the actual layout.
Requires #590.
=> Create builds dir helpers and switch over to using them

src/cmd-build
AFAICT, there's no way to create just a literal `"` in the parameter
expansion brackets in a heredoc. Anyway, it's cleaner to just split that
out as a separate JSON file and let it get aggregated by `jq -s add` as
we do for the qemu image.
Closes: #598
=> cmd-build: Fix conditional vm-iso-checksum JSON entry

src/cosalib/build.py
Our Koji uploads are getting "none" as their name. The meta-data format has changed to use "name" instead of "ref".
=> cosalib: fix name reference

src/cmd-build, src/cmd-buildextend-metal, src/cmdlib.sh
Pass the disk format to runvm_with_disk instead of assuming qcow2. This
allows building raw disks without having to convert. As a bonus, raw
disks can have better performance as well.
=> src/cmdlib.sh: let runvm_with_disk accept a format

Makefile
Start building plume from mantle for use in the FCOS pipeline.
=> mantle: add plume

src/cmdlib.sh, src/supermin-init-prelude.sh
I use `ln -sr ~walters/src/redhat-coreos src/config` and the `-r`
makes a relative link which breaks this code as it tries to `mkdir -p`
on a relative path inside the supermin VM.
Rather than trying to make the path the same on the host and the VM,
add a `COSA_CONFIG_GIT` environment variable that overrides `src/config`,
and use that in the supermin path if we detect that `src/config` is
a symlink.  This way there doesn't need to be a fixed correspondence
between the host filesystem and VM (other than the rest of `workdir`
which should have all relative links contained inside it).
=> build: Fix relative links for `src/config` with supermin

src/cmd-buildprep, src/cmd-buildupload, src/cmd-compress, src/cmdlib.py, src/deps.txt, src/prune_builds
Add a new mode which allows cosa to manipulate multi-arch build layouts:
```
$ find builds
builds
builds/builds.json
builds/30.1
builds/30.1/x86_64
builds/30.1/x86_64/coreos-assembler-config.tar.gz
builds/30.1/x86_64/coreos-assembler-config-git.json
builds/30.1/x86_64/fedora-coreos-30.1-qemu.qcow2
...
```
A pipeline could e.g. dispatch builds for each architecture on different
nodes, then group them back into a single workdir and have it
manipulated by e.g. `buildupload` seamlessly.
This new layout also matches the bucket layout for FCOS (see
coreos/fedora-coreos-tracker#189).
The basic idea is to add a `schema-version` to `builds.json` and denote
the legacy behaviour as "pre-1.0.0", while `1.0.0` contains a different
schema: each element in the `builds` array is now an object, which has …
=> Add new multi-arch build layout mode

src/cmd-build, src/cmd-buildextend-metal, src/create_disk.sh
The remote config in FCOS is provided by `fedora-repos-ostree`, which
ships under the `fedora` id. We need to be able to match this when
deploying the ref in the image so that rpm-ostree can upgrade.
=> Support an `ostree-remote` knob in image.yaml

src/cmd-build
For FCOS, we need to be able to drive versioning from outside of
`cosa build` (see [1]). This will also be used in the very short-term to
manually version the first few FCOS preview releases before making it
automated.
[1] https://github.com/coreos/coreos-assembler/issues/463#issuecomment-479635190
=> cmd-build: Add --version switch

src/cmd-buildupload
Non-legacy builds no longer upload things in the build_dir, only
operating on files inside of the arch specific directories. Explicitly
upload the release.json when running non-legacy.
=> src/cmd-buildupload: upload release.json when running non-legacy

build.sh, deps-s390x.txt, src/deps-aarch64.txt, src/deps-s390x.txt, src/deps-x86_64.txt, src/deps.txt
Rather minimal changes that enable the build of the assembler container on s390x. Testing on ppc64le and x86_64 I haven't seen any breakage.
=> Patch set that enables build of the coreos-assembler container on s390x

src/create_disk.sh, src/grub.cfg
A very important piece we lost moving towards a static GRUB2 config is
the `rd.neednet=1 ip=dhcp` args which normally comes from
ignition-dracut[1].
It also included some subtle semantics which interact with
coreos-installer through the `ignition.firstboot` file so that
networking args are carried over.
Not sure if there were plans to deal with this differently, though we
need something for right now at least for FCOS preview. (And we'll want
to drop `02_ignition_firstboot` from ignition-dracut, but it's not a
hard requirement).
[1] https://github.com/coreos/ignition-dracut/blob/8551bc7fd89a80200d94d009ad3d17131fc11dcf/grub/02_ignition_firstboot
=> grub.cfg: Fix ignition.firstboot semantics

src/cmd-buildextend-azure, src/coreos-assembler
Add cmd-buildextend-azure, which creates a vhd and uploads it as
a blob to Azure.
Note that we do not actually create an Azure image off the vhd.
See: https://github.com/openshift/installer/pull/1976
builds on top of https://github.com/ashcrow/coreos-assembler/commit/060efab2bb74f9a96a318c1b066242bc5e6d4f3f
=> Azure: add cmd-buildextend-azure

src/cmd-buildextend-azure
- fix typos
- remove unused vars
- add manual tmpdir creation
- rename workdir to tmpbuilddir
Cherry-picked from master
=> cmd-buildextend-azure: fix errors

src/cmd-buildextend-azure
(cherry picked from commit eaec4c86a49e10bd5a2a3b6fe3c4806ec914859d)
=> cmd-buildextend-azure: fix incorrect extension of ore arguments

build.sh
The `X` flag does what we want here; marks executable only if
it's set for user.
=> build: Use cleaner chmod invocation

src/cmd-compress
xz compression is notoriously slow. Fortunately, it supports a
multi-threaded mode. The compression ratio is affected by this, but not
really in any significant way (see [1]).
On k8s though, we have to make sure to respect any cgroup limits set on
the CPU. (Though in CentOS right now, we run without any limits set at
all, so this will make a huge dent in our build times).
[1] https://yeah.nah.nz/misc/xz-thread/
=> cmd-compress: Use multithreading for xz

src/virt-install
https://github.com/coreos/fedora-coreos-config/commit/1842e9e309c2dfc89863705917c19f8eb85be245#diff-b56ad46b43eb108be045b7ad559c32b6 introduced the ostree-remote in to the image.yaml Add it in to the allowed keys in virt-install. This resolves issue on ppc64le.
=> virt-install: allow ostre-remote in image.yaml verification

src/cmd-buildextend-azure
This corrects the pathing for the VHD location in `meta.json`.
=> cmd-buildextend-azure: use final path for the vhd in build meta.

src/vmdeps.txt
I was missing the `chmod` on `/boot/efi` in my dev container which
broke the builds.  At first I thought it was the wrong package name,
but that wasn't it.
I guess supermin ignores nonexistent packages, but let's make the
package name correct anyways.
=> vmdeps: Fix name of shim-x64

src/cmd-buildextend-azure
This fixes the `--location` flag and explicitly uses the "westus" in the ORE command.
=> src/cmd-buildextend-azure: fix location argument for ore

src/cmd-run
This is an awful hack-around
https://github.com/coreos/fedora-coreos-tracker/issues/223
But I use `--srv` for developing a lot as it's an easy
way to get data into the VM (e.g. test RPMs), so let's
make it work so I and others can use it to develop FCOS
and even test fixes to things like this.
=> cmd-run: Make --srv work again via dependency hacking

src/cmd-build, src/cmdlib.sh
We want to have full control over the parent of an OSTree commit so it
can be driven at a higher level. IOW, cosa as used in a CI/CD setup is
not in a position to know what the parent of the commit should be. So
either it should default to *no parent*, or accept an override for a
specific parent at build time.
This will be used by FCOS at least for the time being. See:
https://github.com/coreos/coreos-assembler/issues/159#issuecomment-512594688
=> cmd-build: Add --parent

src/cmd-build, src/cmd-fetch, src/cmdlib.sh
This is needed in FCOS, where we'll have a shared base lockfile, and a
curated overrides file. For more info, see the stream tooling doc[1].
For now, we just keep separate overrides per basearch to keep things
simple (instead of having a single override as per the stream tooling
doc). We can add more enhancements in rpm-ostree to enable this, but
let's get the basics working first.
[1] https://github.com/coreos/fedora-coreos-tracker/blob/master/stream-tooling.md
=> Add support for lockfile overrides

src/cmd-buildextend-metal
Don't crash if it's not set, same as we do in e.g. `virt-install`.
I don't currently plan for Silverblue to follow FCOS and use `nosmt`.
=> buildextend-metal: Allow extra-kargs to be unset

src/cmd-buildextend-azure
build_root was changed to build_dir in cosalib. This is a diff between `master` and `rhcos-4.2` branches. we should also look to align cosalib.
Fixes: https://github.com/coreos/coreos-assembler/issues/643
=> cmd-buildextend-azure: fix build_dir reference

src/cmd-buildextend-azure, src/cmd-koji-upload, src/cosalib/build.py
Backports to make `build_root` :arrow_right: `build_dir` valid in rhcos-4.2 as well.
See:
- https://github.com/coreos/coreos-assembler/pull/646
- https://github.com/coreos/coreos-assembler/commit/f583a0d58796d9e4ef57c859ec726ede6a07091f
=> 4.2 backport build root to dir change

src/cmdlib.sh
RHCOS recently changed the version string used to look like
`42.80.20190723.0` or sometimes `42devel.80.20190723.0`, so change the
version string check appropriately.
=> src/cmdlib: relax RHCOS version check

src/cmdlib.sh
RHCOS recently changed the version string used to look like
`42.80.20190723.0` or sometimes `42devel.80.20190723.0`, so change the
version string check appropriately.
(cherry picked from commit d73f49d37c243e85cc3a1e6cab8584fac5c15fef)
=> [rhcos-4.2] src/cmdlib: relax RHCOS version check

Makefile, src/oscontainer.py
- updates `oscontainer.py` to pass `make check`/`make flake8`
- removes unused imports
- pulls code out of global scope
- enables check against the file in CI
Will need a backport to `rhcos-4.2`
=> oscontainer beautification and checking

src/cmd-basearch
The FCOS pipeline at least wants access to this, let's make it easier.
(There were at one point Java GI bindings and in theory we could use
that from Groovy maybe but...let's not go there)
See e.g. https://github.com/coreos/fedora-coreos-pipeline/pull/107/commits/6191937a53a64ce122e26166bf6d3c6145b020f3#diff-67e4a5e30b926dea6c478806ed55fe54R38
=> Add a `basearch` command

src/cmd-buildextend-installer
Instead of fetching EFI binaries from cosa container installer should have
these fetched from ostree root.
Verified that `cosa run --uefi` works on FCOS
=> cmd-buildextend-installer: fetch EFI binaries from /usr/lib/ostree-boot

src/cmd-buildextend-azure, src/cmd-buildextend-gcp
The installer team would like us to include the in-cloud object paths to the meta-data.
=> Add path information for GCP and Azure.

src/oscontainer.py
See: https://bugzilla.redhat.com/show_bug.cgi?id=1731317
For testing I:
- ran a cosa build locally
- created an oscontainer with this pr
- exported the oscontainer to a tar
- imported the tar into my host container storage
- created a container and mounted it
- checked that the pkglist.txt now existed
```
$ sudo podman load -i ./test.tar
Getting image source signatures
Copying blob 9b2483854a3e done
Copying config adb6280425 done
Writing manifest to image destination
Storing signatures
Loaded image(s): localhost/test:latest
$ sudo podman create --net=none --name os-container-test localhost/test:latest
f6a6deb6041b21544958ae2b999e9c214dfdc6a7a3ee13d7fd448e35560ff735
$ sudo podman mount os-container-test
/var/lib/containers/storage/overlay/093ddb214d0fcbd36781b80700403a95f384fcef07319b077ef9 …
```
=> src/oscontainer.py: Add pkglist.txt to container root

src/cmd-buildextend-installer
Cherrypick of https://github.com/coreos/coreos-assembler/pull/652 on `rhcos-4.2`
Instead of fetching EFI binaries from cosa container installer should have
these fetched from ostree root.
Not sure how to verify RHCOS on UEFI though
=> [rhcos-4.2] cmd-buildextend-installer: fetch EFI binaries from /usr/lib/ostree-boot

src/oscontainer.py
Before we were sorting the RpmOstreePackage objects themselves, which
don't really have an implemented ordering through the GI bindings. Just
coalesce the NEVRAs directly and sort those instead.
=> oscontainer: Sort NEVRAs before dumping pkglist.txt

src/cmdlib.sh
EDIT: Version 2
I'd like to encourage the pattern of adding e.g. `fedora-coreos-config`
as a git submodule, rather than forking it.  There are a lot
of subtle things going on here, and in practice no one wants to
"own" it.  If someone forks it even to do something as simple as add
packages, it's easy for things to diverge.
For the treefile, I think it works OK to just use `include: parent-config/blah.yaml`
in the derived treefile; we always expect people doing derivation to
make their own `manifest.yaml` anyways.
But I want to inherit from the overlay too.
My first idea here was to simply:
`ln -sr fedora-coreos-config/overlay overlay`
but that failed because (for probably bad reasons) ostree wants
a real directory as input.
Let's make this a bit more general by first adding support
for an …
=>  Support overlay.d (and symlinks)

src/vmdeps.txt
The `Provides:` here are sufficient to pull in what we need.
Closes: #660
=> vmdeps: Make EFI deps architecture independent, use meta provides

src/estimate-commit-disk-size
The code took an `isize` but neglected to actually use it.
This isn't fully accurate since e.g. we'll have inodes for the
reflinked `/etc` copy, among other things, but it's better.
Part of trying to get Silverblue building using cosa.
Obsoletes: https://github.com/coreos/coreos-assembler/pull/641
=> estimate-commit-disk-size: Actually add inodes to size estimate

src/cmd-buildextend-installer
It's pretty common to support `dd`'ing an installer ISO image to a USB stick and BIOS booting it.  syslinux has a post-processing tool for setting this up; let's run it.
Fixes https://bugzilla.redhat.com/1734374.
=> buildextend-installer: Support MBR boot of ISO image

Makefile, src/cmd-kola, src/cmdlib.py, src/cmdlib.sh
Prep for more work; such as supporting `-p aws` to read the `builds.json`
and find the AMIs there.
(Bigger picture of course the separation between cosa and mantle is increasingly
weird and awkward...)
=> cmd-kola: Port to Python

src/cmd-run
So I can easily test expanding the base disk image to play with `/var`
as a partition, etc.
=> cmd-run: Add --size argument

.cci.jenkinsfile, src/cmd-buildupload
At `buildupload` time, we're in a position to know what kind of content
we're uploading. Use this to make smarter default caching behaviours
depending on whether the file is an image artifact or a piece of
metadata.
See related discussions in
https://github.com/coreos/fedora-coreos-tracker/issues/232.
=> cmd-buildupload: Use better default caching directives

src/cmd-run, src/incomplete-hack-ign-3to2
I want to be able to use -i without having to recreate the bits that cmd-run usually does. Merge in  the config instead of replacing it.
=> cmd-run: merge configs specified with -i

src/cmd-koji-upload
With [1], Koji now supports compressed `qcow2` and `raw` disk images. This uploading these compressed artifacts.
[1] https://pagure.io/koji/c/fac81bd7bec410cbacce649ba8006704486a2f57?branch=master
=> cmd-koji-upload: add compressed qcow2 and xz compression for Koji

src/create_disk.sh
Set the disk uuid to be predictable so we can randomize it and fix the
gpt header on first boot.
Fixes https://github.com/coreos/ignition/issues/839 when combined with https://github.com/coreos/ignition-dracut/pull/93
=> create-disk: set the disk uuid to 00...1

src/incomplete-hack-ign-3to2
The previous change here broke the basic `cosa run` targeting RHCOS.
=> ign-3to2: Don't crash if there's nothing to merge

build.sh, src/create_disk.sh
Booting current FCOS, one can see that stuff under
e.g. `/sysroot/ostree/` is mostly `unlabeled_t`.
Also, there's junk in `/sysroot` that isn't necessary; I think
when I was writing `ostree admin init-fs` I was thinking of dracut
requirements at the time that the target root (before ostree pivot)
had e.g. `/dev` - that's no longer true (if it ever was).
For each mount point, add an initial hardcoded label; the physical
root is `root_t` for example.  This ensures that at least anything
created under that will have *a* label, and usually via
path transitions, the correct one.
Combining the above, we inline the bits of `init-fs` we need, namely
creating the repo and `deploy` directory.  We add the `usr_t`
label to the ostree repo, and let SELinux policy handle the rest.
Then the result is …
=> create_disk: Set up SELinux labeling fully

src/cmd-build, src/cmd-buildextend-metal, src/create_disk.sh, src/gf-anaconda-cleanup
Currently the SELinux policy in RHCOS doesn't allow systemd
to operate on `unlabeled_t`.  General agreement was
that the real fix is to do some "bootstrap" labeling in
Ignition, but the problem is the kernel doesn't currently
allow it.
For more information, see:
https://github.com/coreos/ignition-dracut/pull/79#issuecomment-488446949
For now, we just carry forward this (opt-in) workaround which already
exists in the `virt-install` path.
Closes: https://github.com/coreos/coreos-assembler/issues/581
=> build: Readd support for save-var-subdirs-for-selabel-workaround

README.md, src/cmdlib.sh
So we can add a `README.md` for example to help people understand
different ones.
=> build: Ignore non-directories in overlay.d

src/cmd-buildextend-aws
Per discussion in https://github.com/coreos/mantle/pull/1039
around garbage collection.  This way even if the AMI is deleted
we know what the underlying snapshot was.
=> buildextend-aws: Record snapshot ID too

Dockerfile, src/cmdlib.sh, src/vmdeps-aarch64.txt, src/vmdeps-ppc64le.txt, src/vmdeps-s390x.txt, src/vmdeps-x86_64.txt, src/vmdeps.txt, vmdeps-aarch64.txt, vmdeps-ppc64le.txt, vmdeps-s390x.txt, vmdeps-x86_64.txt
Add additional files that specify the dependecies for each architecture.
It has the same structure as deps-arch.txt. This is needed to install
different packages for s390x. For example for s390x, grub is not needed
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
=> deps: add arch dependent deps files for the vm

src/cmd-buildextend-aws
This way after
https://github.com/coreos/mantle/pull/1039
lands we won't reuse AMIs from previous failed builds.
=> buildextend-aws: --force ore aws upload by default

src/cmd-aws-replicate, src/coreos-assembler
Adds a new command `aws-replicate` which will replicate the AMI of a
given build to a list of regions. It utilizes the `ore aws copy-image`
command to do the actual copying, searches for the initial AMI from the
buildmeta, skips any given regions that already exist in buildmeta, and
finally updates the buildmeta with the new values.
Requires https://github.com/coreos/mantle/pull/1040
=> src/cmd-aws-replicate: Add command to replicate AWS AMI to regions

src/cmd-koji-upload
This is a rework of the file upload logic. One of the problems with Koji
Content Generators (cmd-koji-upload is such a thing) is that unless Koji
know about the content type being uploaded and the content type matches
a specific pattern than an upload will be rejected.
In the past we have uploaded uncompressed artifacts and renamed some
files to raw. A problem was hit when we tried to upload `vhd.gz` files.
We could have done the rename approach or come up with a more dynamic
solution.
This also addresses some wonky code. This refactor allow us to do the Koji
uploads, with out mucking with the rest of COSA by doing an upload
conversion for renaming true "raw" object like the kernel, and when a
supported format is not allowed to be uploaded in compressed fashion, do
a run-time decompress …
=> src/cmd-koji-upload: introduce file mutators

src/cmd-koji-upload
This is a rework of the file upload logic. One of the problems with Koji
Content Generators (cmd-koji-upload is such a thing) is that unless Koji
know about the content type being uploaded and the content type matches
a specific pattern than an upload will be rejected.
In the past we have uploaded uncompressed artifacts and renamed some
files to raw. A problem was hit when we tried to upload `vhd.gz` files.
We could have done the rename approach or come up with a more dynamic
solution.
This also addresses some wonky code. This refactor allow us to do the Koji
uploads, with out mucking with the rest of COSA by doing an upload
conversion for renaming true "raw" object like the kernel, and when a
supported format is not allowed to be uploaded in compressed fashion, do
a run-time decompress …
=> src/cmd-koji-upload: introduce file mutators [backport]

src/vmdeps-aarch64.txt, src/vmdeps-ppc64le.txt, src/vmdeps-s390x.txt, src/vmdeps-x86_64.txt
Fix: #660
Tested on x86_64 and ppc64le via ```cosa run```.
=> vmdeps: Use correct grub-efi packages on each arch

src/cmd-koji-upload
This fixes a problem where `stat` reports the size of the symlink when we want the size of the symlinks's target.
=> cmd-koji-upload: follow symlinks when getting file size

src/cmd-buildupload
We want to be able to upload only the build itself, without also
uploading `builds.json`. The use case for this in a pipeline context is
uploading new or modified files in existing build directories but still
categorically rule out racing with another job also adding a new build.
=> cmd-buildupload: Add --skip-builds-json

src/cmd-buildextend-installer, src/deps-s390x.txt
This requires fedora-coreos-config/installer/zipl.prm file for kernel
parameters.
xorrisofs tool allows building iso image on s390x, genisoimage does not
support.
Blatantly copy mk-s390-cdboot tool from lorax project.
Signed-off-by: Tuan Hoang <tmhoang@linux.ibm.com>
=> s390x: allow building iso image

src/cmd-build, src/create_disk.sh
- add zipl code in create_disk.sh. We need to implement removal of
ignition.firstboot and re-run zipl in ignition-dracut hooks.
See https://github.com/coreos/ignition-dracut/issues/84.
Signed-off-by: Tuan Hoang <tmhoang@linux.ibm.com>
=> s390x: allow cosa build and run without anaconda

src/cmd-build, src/cmd-run, src/cmdlib.sh
- use ccw as device type instead of pci
- specify s390x KVM machine type
Signed-off-by: Tuan Hoang <tmhoang@linux.ibm.com>
=> s390x: correct qemu, tty, pci device types

src/gf-platformid
Grub is not used on s390x architecture
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
=> s390x: skip grub.cfg

src/cmdlib.sh
while defaulting to pci bus for ppc64le and x86_64 pcie is needed
on aarch64 and s390x defines its own structure. The code as is is
evaluated before the arch conditionals giving aarch64 a pci bus
that does not work.
Signed-off-by: Dennis Gilmore <dennis@ausil.us>
=> move scsibus definition

src/cmd-buildupload
Currently `buildupload` doesn't actually validate that the images
described in the `meta.json` exist in the current build directory before
attempting to upload them. This can be problematic in the case where a
user has performed a `buildprep` to pull down an existing builds
`meta.json` and is now attempting to re-upload it after adding new cloud
images / artifacts.
=> cmd-buildupload: check that files exist

Makefile
The PR is to add multiarch support to kolet build and kola/kolet installation.
The PR from mantle side to have kolet build also for s390x - https://github.com/coreos/mantle/pull/1048
=> s390x: multiarch support for kolet/kola installation

README-design.md, README.md
I was explaining cosa in person to someone, and realized that
`README-design.md` (which I wanted to send as a link) had gotten
out of date.
=> README: Update the -design.md, and link to it from main README

src/cmd-koji-upload, src/cmdlib.py, src/deps.txt, tests/test_cmdlib.py
The latest Koji packages in Fedora just work with Kerberos authentication for Koji. This drops the Python2 for Python3.
=> src/cmd-koji-upload: port to Python3

src/create_disk.sh
Add the immutable bit to the physical root; we don't
expect people to be creating anything there.  A use case for
OSTree in general is to support installing *inside* the existing
root of a deployed OS, so OSTree doesn't do this by default, but
we have no reason not to enable it here.  Administrators should
generally expect that state data is in /etc and /var; if anything
else is in /sysroot it's probably by accident.
I just happened to think of this while working on
https://github.com/coreos/coreos-assembler/pull/736
=> create_disk: Add the immutable bit to the physical root

Dockerfile.buildroot, src/buildroot-buildreqs.txt, src/buildroot-reqs.txt, src/install-buildroot.sh
We've talked before about how cosa isn't useful for people
developing on e.g. rpm-ostree; this is a primary reason I personally
use cosa via installing it inside my personal toolbox container.
This PR implements something talked about before; we add a
"buildroot" container (e.g. `quay.io/coreos-assembler/coreos-buildroot:latest`)
that is basically `yum builddep` for the parts we care about.
The main reason I want to do this right now is I am working
on using cosa in rpm-ostree's CI, and having an up-to-date "buildroot"
container with the dependencies pre-installed will help a lot with that.
I ran into issues trying to use cosa as a base and do the `yum builddep`
dynamically because of the `USER builder` directive; Prow isn't expecting that.
Another reason to do this is that in the future …
=> Add a Dockerfile.buildroot

src/cmd-buildextend-metal
This metal script should work for zFCP SCSI disks on z/VM and LPAR
hypervisors, where they will be installed with coreos-installer.
For ECKD DASD disks, we probably need a similar but seperate script,
because those require a little bit of special handling for its own.
Signed-off-by: Tuan Hoang <tmhoang@linux.ibm.com>
=> s390x: allow building metal image

README.md
We stopped documenting the use of the COREOS_ASSEMBLER_PRIVILEGED
environment variable in 19ba574.
=> README: delete unused env var from documentation

src/cmd-init, src/cmdlib.sh, src/supermin-init-prelude.sh
This is a different approach from
https://github.com/coreos/coreos-assembler/pull/605 towards fixing
local src configs.
There are two core issues:
1. `COSA_CONFIG_GIT` is understood by cosa only, so it doesn't help if
the target command we want to execute is not a cosa subcommand.
2. The arguments we pass to the target command might already embed
expanded/absolute `${workdir}/src/config/...` paths.
So instead, let's just make sure we don't use relative symlinks so that
`src/config` in such cases is always a symlink to an absolute path.
Then the `mkdir -p $(readlink ...)` approach should just work.
=> Fix local src config handling in unprivileged path

src/cmd-init, src/cmdlib.sh
The support for rootfs overrides was added in c8cab23 but never
tacked on to cmd-init. It's useful to have it created so the user
doesn't have to remember the name of the dir each time he/she cleans
their local cache.
=> cmd-init: set up rootfs overrides dir during init

README.md, doc/openshift-gcp-nested-virt.md
=> Add a document for OpenShift 4.2 in GCP with nested virt

src/cmd-buildextend-installer, src/cmd-buildextend-live, src/cmd-compress, src/gf-mksquashfs, src/gf-platformid, src/libguestfish.sh
Add buildextend command to build live PXE and ISO images, with a squashfs of the root filesystem appended to the initrd.  Pursuant to https://github.com/coreos/fedora-coreos-tracker/issues/203, we'd eventually drop the separate installer images.
Part of https://github.com/coreos/fedora-coreos-config/pull/155.
=> Build live PXE and ISO images

src/cmd-build, src/cmdlib.sh
For better auditability, add a bit to the `meta.json` if
we did something with `overrides/`.  I plan to change the FCOS
pipeline to fail if this key is present in prod builds for example.
=> build: Add coreos-assembler.overrides-active if overrides/ is active

src/oscontainer.py
This would ensure `podman inspect` / `skopeo inspect` operations are retried up to 5 times with 5 sec delay.
External python deps cannot be used in `oscontainer.py` as its running inside RHCOS system
=> Retry skopeo inspect calls

src/libguestfish.sh
I added this code originally in anticipation of us possibly
shipping FCOS with a `var` partition by default.
In practice, I think we're going with a basic one-FS layout by
default, and anyone who wants something else can use Ignition-based
re-partitioning.
Mainly removing this code silences an annoying libguestfs error
about a missing `var` label that kept confusing people into thinking
things were failing.
=> libguestfish: Remove support for mounting `var` partition

src/cmd-buildextend-metal, src/cmd-oscontainer, src/cmdlib.sh
Have `runvm` accept arbitrary arguments for qemu along with
arguments for the target code.  This makes it far more
flexible.  Prep for passing `create_disk.sh` arguments via
a read-only virtio mount.
=> build: Clean up internal runvm API

src/cmd-buildextend-installer, src/gf-mksquashfs, src/virt-install
In this PR:
- Allow patching live ISO to embed Ignition config
- Allow overriding squashfs compression in `image.yaml` to support EL 8
- Ignore `README-devel.md` when copying ISO contents from config
Part of https://github.com/coreos/fedora-coreos-config/pull/171.
=> buildextend-live: More live PXE/ISO work

src/cmd-kola, src/cmdlib.py
This fixes kola test run in rhcos master pipeline - ign 3 is being used there after version bump
=> cmdlib: set ignition 2.2.0 for rhcos-43 qcows

src/cmd-buildprep, src/cmd-buildupload, src/cmdlib.py, src/deps.txt
* use boto3 for s3 uploads
* include `python3-tenacity` to retry on request and boto3 calls
TODO:
https://github.com/coreos/coreos-assembler/compare/1bdc475803058dc167044f074f19cad0e4b46a49..c611e9abf79a3ad4f87192fc3b9d9ea643a6911b:
```
Checking that 'builds.json' exists
S3Fetcher.exists_impl attempt=0
Throwing exception
Retrying after Connection was closed before we received a valid response from endpoint URL: "foo".
S3Fetcher.exists_impl attempt=1
Throwing exception
Retrying after Connection was closed before we received a valid response from endpoint URL: "foo".
S3Fetcher.exists_impl attempt=2
Throwing exception
Retrying after Connection was closed before we received a valid response from endpoint URL: "foo".
S3Fetcher.exists_impl attempt=3
Fetching: …
```
=> Handle retries during build uploads

src/cmd-build
Adds the force-image flag to rebuild the image and disregard input checks.
This is useful to just build an image and not the ostree using --force
Closes: #744
=> Add --force-image flag to cosa build

src/cmd-buildextend-installer
When building a non-live bare metal installer, the qemu key is missing
from the build metadata
Signed-off-by: Yuval Turgeman <yturgema@redhat.com>
=> installer: KeyError when building bare metal only

src/cmd-build, src/cmdlib.sh
I have `cosa fetch; and cosa build` in my shell history and use
it somewhat often.  We only need to commit the overlay directories
on actual builds, not fetch which is just about RPMs.  Mostly
doing this because:
- The overlay commit is more visual noise
- For `overrides/rootfs` it can be a nontrivial cost
=> build: Only prepare overlays when doing build, not fetch 

src/cmd-buildextend-metal, src/create_disk.sh
Our create-disk.sh commandline arguments are getting a bit hard to
grawk. To help with readability, this uses cli flags.
=> src/create-disk.sh: use flags over position arguments

src/cmd-buildextend-installer, src/gf-get-kargs
In this PR:
- Read kernel arguments from qemu image; filter and substitute into ISO bootloader configs
- Rationalize file metadata in the ISO images
- Minor cleanups
Part of https://github.com/coreos/fedora-coreos-config/pull/177.
=> Live PXE/ISO, round III

src/cmd-buildupload
The JSON files were being uploaded without a set `Content-Type` header
(except for `meta.json`), so e.g. the FCOS build browser link for
`commitmeta.json` would ask to download the file instead of opening in
the browser directly.
I think this is a minor regression from switching to uploading via boto;
previously, `aws s3 cp` would do this auto-detection for us.
=> cmd-buildupload: Auto-set ContentType for JSON files

src/cmd-buildextend-metal, src/create_disk.sh
It will be very useful in the future to be able to more rigorously
know the build that a given machine *started* from.  For example,
small tweaks like `chattr +i /sysroot` are things that won't
happen for in-place updates.
If we decide to introduce a mechanism (e.g. systemd
unit) that performs those changes even for old in-place installs,
it could be useful to know exactly what the starting state was.
I chose `/boot` since it's a relatively fixed location which
people generally won't wipe and replace without also erasing
everything else.
=> build: Add /.coreos-aleph-version.json to target 

src/cmd-buildextend-installer
#769 is now using `img_qemu` outside of `if is_live`
=> installer: set img_qemu when generate_iso is started, not in is_live

Makefile, src/cmd-buildextend-azure
We're not ready for the full flake8 (which honestly I find really
annoying anyways...) - but at least verify we're not shipping any
syntax errors.
Doing this since I saw a syntax error in an RHCOS build in
`cmd-buildextend-azure`, although I am not seeming to replicate
it locally from master at the moment.
=> build: Verify Python syntax in `make check`

src/cmd-buildextend-metal, src/create_disk.sh, src/deps.txt, src/vmdeps.txt
This will install the rootfs in a LUKS container using a null cipher. The
actual encryption of the LUKS container will be handled by a new dracut
module, tentatively named "ignition-dracut-reecrypt."
By default, the rootfs is not installed into a LUKS container. To enable
rootfs in LUKS, add the following to the recipe image.yaml:
`    luks_rootfs: "yes"`
This implements the agreed-to-design in:
https://github.com/openshift/enhancements/blob/master/enhancements/automated-policy-based-disencryption.cmd
=> cmd-buildextend-metal: support for rootfs in LUKS containers.

src/cmd-buildextend-dasd, src/cmd-buildextend-metal
The block size of QEMU raw image used for ECKD DASD needs to be 4096.
This is the interim solution for ECKD DASD. In the long terms, we would
need to have a DASD raw image instead.
=> s390x: build bare metal DASD image

src/cmd-buildextend-metal
Otherwise you get errors from qemu like:
- 'virtio-blk-ccw' is not a valid device model name`
=> cmd-buildextend-dasd: disallow building on non s390x

src/cmd-buildprep
AWS CLI has been conveniently creating missing dirs if `key` contained those. Now `download_file` would require those to write at temporary file.
Now intermediate dirs are created - this should resolve failure in FCOS pipeline. RHCOS pipeline wasn't affected, as it already had builds dir created.
=> cmd-buildprep: make necessary dirs when fetching files

src/cmd-buildextend-aws, src/cmd-buildextend-azure, src/cmd-buildextend-gcp, src/cmd-buildextend-installer, src/cmd-buildextend-openstack, src/cmd-buildextend-vmware
- Default to the latest build
- Use the same code in each implementation
=> buildextend*: unify behavior/code of `--build` option

Makefile, pytest.ini, src/cmd-buildextend-aws, src/cmd-buildextend-azure, src/cmd-buildextend-gcp, src/cmd-buildextend-installer, src/cmd-buildextend-openstack, src/cmd-buildextend-vmware, src/cmd-buildprep, src/cmd-buildupload, src/cmd-compress, src/cmd-kola, src/cmd-meta, src/cmd-tag, src/cmdlib.sh, src/cosalib/build.py, src/cosalib/builds.py, src/cosalib/cmdlib.py, src/cosalib/meta.py, src/prune_builds, tests/test_cosalib_cmdlib.py, tests/test_cosalib_meta.py
- Master rebase and test fix for https://github.com/coreos/coreos-assembler/pull/676
- cmd-meta:
```
$ cosa meta --get images.qemu.path --workdir=/srv/ --build 42.80.20190926.0
$ cosa meta --get images.qemu.path \
--get ostree-n-metadata-total \
--workdir=/srv/ --build 42.80.20190926.0
$ cosa meta --set images.qemu.path=test \
--workdir=/srv/ --build 42.80.20190926.0
$ cosa meta --set images.qemu.path=test \
--set ostree-n-metadata-total=123 \
--workdir=/srv/ --build 42.80.20190926.0
$ cosa meta --dump \
--workdir=/srv/ --build 42.80.20190926.0
```
This is an ugly WIP. Here be dragons. I want to float the idea before getting to-far into what could be a massive refactoring.
This moves:
* cmdlib.py into cosalib
* introduces a cosalib.meta as a stub for generically handling the meta.json for …
=> use COSA for all meta-data operations, introduce cmd-meta

README-design.md, src/cmd-build, src/cmd-buildextend-installer, src/cmd-buildextend-metal, src/cmd-buildprep, src/cmd-compress
We really should have the checksum for the tarfile in there so that
anyone downloading it can integrity check it. This will be used by
`coreos-ostree-importer` at least.
=> cmd-build: add `.images.ostree` to meta.json

src/cmd-buildextend-aws, src/cmd-buildextend-azure, src/cmd-buildextend-gcp
This makes it easier to test invidvidual pieces of the cloud provider
generation. It also would allow for people who want to build their own
image and then share the file with others to do so.
=> buildextend-{aws,azure,gcp}: make uploading optional

src/cmd-buildextend-installer, src/cmd-koji-upload, src/cosalib/build.py, src/virt-install
Let's use a single implementation. Considering a41e434 let's use
get_basearch() from cmdlib.
=> src: use consistent implementation for getting architecture

src/cmd-build, src/cmd-buildextend-aws, src/cmd-buildextend-azure, src/cmd-buildextend-gcp, src/cmd-buildextend-installer, src/cmd-buildextend-metal, src/cmd-buildextend-openstack, src/cmd-buildextend-vmware
We'd like to include the arch in each artifact name so that we can
disambiguate more easily. This will allow for one to download files
from different architectures into the same directory and not have
conflicts.
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/264
=> cmd-build*: add architecture into artifact names

Dockerfile, Makefile, deps-s390x.txt, src/cmd-buildextend-installer, src/cmd-run, src/cmdlib.sh, src/deps-s390x.txt, src/gf-anaconda-cleanup, src/gf-platformid, src/image-base.ks, src/virt-install, src/vmdeps-aarch64.txt, src/vmdeps-ppc64le.txt, src/vmdeps-s390x.txt, src/vmdeps-x86_64.txt, src/vmdeps.txt, vmdeps-aarch64.txt, vmdeps-ppc64le.txt, vmdeps-s390x.txt, vmdeps-x86_64.txt
Cherry picked multiarch/s390x fixes from master branch to the rhcos 4.2 branch. 
Also has a couple of commits by me which are:
- add an option for disklabel for the clearpart command
- for s390x change the guestfish labeling - which was discussed as part of https://github.com/coreos/coreos-assembler/issues/695
=> [rhcos-4.2] Port s390x/multi-arch fixes from master to rhcos-4.2

src/cmd-buildextend-aws, src/cmd-buildextend-azure, src/cmd-buildextend-gcp, src/cmd-buildextend-installer, src/cmd-buildextend-metal, src/cmd-buildextend-openstack, src/cmd-buildextend-vmware, src/cmd-koji-upload, src/cosalib/build.py, src/virt-install
Since we are using the get_basearch function we'll use basearch instead
of arch for the variable names. basearch is a yum/dnf concept to group
binary compatibile architectures and not exactly matching up with uname.
See also e02ef26
=> src/*: rename arch -> basearch and ARCH -> BASEARCH

build.sh, src/virt-install
Fedora stopped building 32-bit x86 kernels and F31 will be the first
release without i386 repos altogether:
https://fedoraproject.org/wiki/Changes/Noi686Repositories
So there won't even be bootable media to install from.
=> Drop support for i386 host systems

src/cosalib/meta.py, tests/test_cosalib_meta.py
This matches the semantics for `Builds` too. I want to make use of this
class in `cosa sign`.
This also fixes a bug where we were passing the parent dir to `Builds()`
instead of the workdir directly.
=> cosalib/meta: make workdir optional

src/cmd-init
We are supporting a pattern where projects like RHCOS use
fedora-coreos-config as a git submodule.  Clone submodules by
default to make that work more nicely.
=> init: Use `git clone --recurse-submodules`

src/cmd-koji-upload, src/cosalib/build.py
Follow up to #799
The real need is the fix to `cmd-koji-upload`; currently failing in
RHCOS pipeline.
=> src/*: more ARCH -> BASEARCH

src/cmd-koji-upload
Follow-up to #799 and #810.
Closes: #817
=> cmd-koji-upload: adapt property access for basearch

src/cmd-buildupload
We added this when the OpenShift installer was *directly* pulling
from the RHCOS build stream.  They wanted to be resilient to
"update denial attacks".  Since then, the installer pins RHCOS
and actually no customer-facing tool talks to the RHCOS cosa build
stream.
So we don't need to worry about "freshening" it.  I also
dropped the call to `--freshen` in the RHCOS pipeline a while
ago.
Prep for further work in this file around build cancellation.
=> buildupload: Drop --freshen argument

README-devel.md
They're a bit easter-egg right now but we really want cosa
to be useful for local dev as well as prod builds.
=> README-devel.md: Document use of overrides/

src/cmd-buildupload, src/cmd-compress, src/cosalib/builds.py, src/prune_builds
Depends: https://github.com/coreos/coreos-assembler/pull/811
The new build layout includes architecture-awareness.
It was really nice that we supported both for a while, but
RHCOS for 4.3 has switched to the new layout.  There's no
reason to keep around the legacy build layout code, so remove
it for at least three minutes of warm fuzzy "code deletion high".
Also prep for work around failed builds handling.
=>  Remove support for "legacy" build schema

src/cmd-build, src/cmdlib.sh, src/cosalib/builds.py
Prep for failed build handling, where we want to
determine our new version number not just from the previous
build, but use any failed/in-progress build information
in `builds.json` too.
=> build: Move buildid allocation into builds.py

src/cmd-buildprep, src/cmd-buildupload, src/cosalib/builds.py
Prep for "failed build" handling.  It is useful in general
to know what the difference is between the "upstream" and local
storage.  When we reun `buildprep`, record the URL as well as
the original `builds.json`.  When we `buildupload`, update our
cached copy.
(If we were using https://git-annex.branchable.com/ this type of
stuff would come "for free")
=> buildprep/buildupload: Track "upstream" builds.json

src/cmd-buildextend-metal, src/create_disk.sh, src/deps-ppc64le.txt, src/vmdeps-ppc64le.txt
ppc64le(pseries,PowerNV) anacondaless build.
Allow partition layout to differ per arch, i.e. to include and omit certain partitions.
Use generic Linux FS uuid for root partition as discussed in the #795
Fix: #795
=> *build*: Make ppc64le build anacondaless

src/libguestfish.sh
We need the internal libguestfs bits to work; at least
`buildextend-installer` uses them.
=> Mount RHCOS LUKS

src/create_disk.sh
cryptsetup defaults to argon2i and a memsize of half of the
physical RAM.  This means the default RAM size of 2048 for
our build VMs "leaks" into the memory requirement of the
target system.
We discovered this because libguestfs uses a smaller memory size
by default.
Explicitly specify that we want luks2 and the default argon2i
(to be resilient to changes), then drop the PBKDF memory requirement
down to 512MB to be conservative so we can boot even on smaller
systems.
(That said, this type of stuff is why we really want
to get to the end game of full Ignition support, because
that way cryptsetup could work in the way it was designed to
on the target system)
=> create_disk: Set --pbkdf-memsize to 512MB

src/cmd-fetch
It's useful sometimes to just fetch the latest metadata to see what
packages would be pulled in.
Another use case is in combination with `--update-lockfile`, so that we
can still update the lockfile without having to download the packages.
I debated a bit whether to just add a `-- "$@"` semantic where all the
remaining args are passed to `rpm-ostree`. I think we could do this,
though this specific option is useful enough I think to be a proper
`cosa fetch` one.
=> cmd-fetch: add --dry-run

doc/openshift-gcp-nested-virt.md
I stood up a new cluster and was hitting OOMs until I did this.
(We need to clean up and consolidate our memory usage)
=> doc/gcp-nested-virt: Bump memory to 3Gi

src/cmd-aws-replicate
Pass one region from the list and write meta.json if the result was a success.
This fixes the issue with meta.json containing only the original AMI if ore upload errors occurred in some regions
xref: GRPA-374
=> cmd-aws-replicate: upload to one region at a time

src/cmd-buildprep, src/cmd-buildupload, src/cosalib/aws.py, src/cosalib/cmdlib.py, src/cosalib/s3.py
These libraries contain code to work on s3 buckets (head, list, delete)
and ec2 (deregister images and snapshots)
Cherrypicked from #839, tested in the dev pipeline
=> cosalib: create libs for s3 and ec2 operations

src/cmd-kola
Requires: https://github.com/coreos/mantle/pull/1081
So the ssh agent is in a predictable place, and one doesn't
have to guess among the 10s of random `/tmp/mantle-ssh-<tmp>` directories.
This way we can document doing e.g.:
```
$ env SSH_AUTH_SOCK=tmp/kola-ssh ssh -p <port> core@127.0.0.1
```
to debug local qemu-unpriv VMs, etc.
=> kola: Set MANTLE_SSH_DIR

src/cmd-sign, src/coreos-assembler, src/deps.txt
Add a new `cosa sign` top-level command for general signing operations.
For now, it only supports one subcommand, `robosignatory`, which does
signing by RoboSignatory via fedora-messaging (see [1][2] for details).
Essentially with this, the pipeline flow will be:
```
$ cosa build ostree
$ cosa sign robosignatory --ostree ...
$ cosa buildextend-*
$ cosa buildupload
$ cosa sign robosignatory --images ...
```
[1] https://github.com/coreos/fedora-coreos-tracker/issues/198
[2] https://github.com/coreos/fedora-coreos-tracker/issues/200
=> Add `cosa sign robosignatory` for signing OSTrees and images

src/cmd-run
See individual commit messages for details. TL;DR: this allows one to do `cosa run --ssh`.
I initially developed this patchset with the intent of making use of it in rpm-ostree's CI. But I'm leaning now more towards leveraging `kola spawn` there. (I mention `kola spawn` in the last commit's message too). Though short of merging `cosa run` into `kola spawn`, having `--ssh` here too is useful.
=> cmd-run: A bunch of SSH-related enhancements

src/cmd-buildextend-aliyun
Adds a new command `buildextend-aliyun` that can both create the image
as well as upload it.
=> buildextend-aliyun: add aliyun image building

src/cmdlib.sh
This is needed on ppc64le pseries to get all OF output
=> cmdlib: Disable vga, so all output is forwarded to the console

src/buildroot-buildreqs.txt
This ensures we get e.g. `zchunk-devel` today, but is also
what we want on general principle since rpm-ostree developers
will likely need to hack on both.
=> buildroot: Add libdnf and librepo

build.sh
There's a new update awaiting karma that fixes the `statx` failures:
https://bodhi.fedoraproject.org/updates/FEDORA-2019-566ad52d5e
I strongly suspect this is also the root cause behind the recent CI
failures:
https://github.com/coreos/fedora-coreos-config/pull/201#issuecomment-542849262
https://github.com/coreos/rpm-ostree/pull/1929#issuecomment-543195228
Let's just pull it in right now so we can get things unblocked.
=> build.sh: backport latest coreutils with statx fix

src/cmd-build, src/cmd-fetch, src/cmdlib.sh
The digest fields in lockfiles have been more trouble than they're worth
so far. The major problem is signing: adding a signature to an RPM of
course changes its digest.
There are two main issues. The first is that when adding an override,
there's no way to know the digest ahead of time since the package isn't
signed yet. It becomes signed when the override is accepted and tagged
into the pool.
The second is that the same package NEVRA may be present in different
repos and signed with different keys, resulting in different hashes,
even if the payload is the same (for more details on this case, see
https://github.com/coreos/rpm-ostree/pull/1927).
One could add repo origin information as part of the lockfile, but that
does not correspond to what we actually do in FCOS, since packages …
=> cmd-{fetch,build}: strip out digests from lockfiles

src/cmd-aliyun-replicate
Adds a new command that replicates aliyun images to different regions.
Also contains a mantle bump to pick up the `ore aliyun list-regions` command, shortlog in commit.
Closes #857
=> src/cmd-aliyun-replicate: add command to replicate aliyun images

README.md, build.sh
This reverts commit 648f26c42366b61d5bd39598072ffd0e6b0e3b7b.
The package is part of the continuous tag now, so it should get pulled
in automatically.
=> Revert "build.sh: backport latest coreutils with statx fix"

src/cmd-tag
Just follow the same convention used in the other commands.
=> cmd-tag: When creating tag, default to latest build

src/create_disk.sh
s390x requires running `zipl` to regenerate the bootloader block
after changes to the BLS configuration are made.
(Note this backend doesn't exist yet, but it will)
=> create_disk: use zipl bootloader for libostree on s390x

src/cmd-kola
Rather than encoding the blacklist in three different places (the
fedora-coreos-config CI, the coreos-assembler CI, and the pipeline),
let's just teach `cosa kola` to auto-detect a `kola-blacklist.yaml` from
the src config and automatically blacklisting them when executing kola.
I proposed making this baked in kola itself with slightly different
semantics in: https://github.com/coreos/mantle/issues/1103
Though teaching this to cosa should still make things easier to maintain
for now at least.
=> cmd-kola: add support for kola-blacklist.yaml

src/create_disk.sh
The first boot arguments are just ephemeral. If we add them to BLS file,
then we have to remove them in ignition-firstboot-complete.service
during first boot, which would complicate it. Without adding them to BLS
file, an invoke of zipl without any parameters (assuming zipl.conf and
BLS files are present) is enough.
=> s390x: do not write first boot args to BLS file

src/cmd-buildextend-aliyun
Matches what other `buildextend-$cloud` commands have. This is needed in
RHCOS to support developer pipelines.
=> cmd-buildextend-aliyun: add --name-suffix

build.sh
So we have one fewer random place to change when bumping Fedora
versions.  Prep for rebasing on F31.
=> build: Use /etc/os-release rather than hardcoding distro version

src/cmd-buildextend-installer
installer: use lorax s390x templates, allow adding parameters at boot
Significant changes include:
- Use a naming convention for kernel and initramfs file, which would
help for s390x case. The reasoning is that z/VM's CMS files do not allow
names and extentions more than 8 characters. While we are renaming, lets
stick with traditional RHEL/Fedora naming so redhat.exec and generic.ins
don't require changes from lorax templates.
- Allow us to add parameters (ignition, raw image, etc.) at boot time
for s390x using 'rd.cmdline=ask' dracut parameters. It is
better to reuse lorax templates rather than adding it on our own.
- generic.ins and redhat.exec from lorax allow us to loop mount the ISO
image and expose its mount point via FTP, then LPAR and z/VM can fetch
kernel and initramfs from there …
=> installer: use lorax s390x templates, allow adding parameters at boot

src/incomplete-hack-ign-3to2
I was trying to test out some Ignition via `cosa run -i` with
RHCOS and it wasn't working.  Turns out the code to do this
introduced with
https://github.com/coreos/coreos-assembler/commit/7e2a920f70a68b0d9637feddac36db19065e1891
wasn't quite right.
=> incomplete-hack-ign-3to2: Fix translation of s/merge/append/

src/create_disk.sh, src/gf-platformid
With all arches supported in anacondaless mode, populating
grub for ppc64 can be removed. This also fixes openstack image
generation for ppc.
=> Remove populating grub.cfg for ppc64

src/cmd-run
We want to strongly emphasize use of TPM devices in CoreOS, so let's provision
one by default.
They can be used for disk encryption, secure secret storage, etc.
=> run: Add a software TPM device by default

.cci.jenkinsfile
For the purposes of testing if `coreos-assembler` can build an image
correctly, it should be sufficient to just run `fcos.basic` to
validate the image was usable.
=> ci: just run kola.basic

src/create_disk.sh
This is prep for reprovisioning the rootfs:
https://github.com/coreos/fedora-coreos-tracker/issues/94
Requires: https://github.com/coreos/fedora-coreos-config/pull/187
(Do not merge until RHCOS has also rebased to FCOS with that change)
Closes: https://github.com/coreos/coreos-assembler/issues/781
=> create_disk: Drop the root= and rootflags= kargs by default

src/create_disk.sh
This reverts commit 99f2ed566851d84af7f40d6b368b727e318a733f.
This breaks rebooting, we need to ensure the sysroot mount unit
runs on subsequent boots too.
=> Revert "create_disk: Drop the root= and rootflags= kargs by default"

src/cmd-build
I've become quite fond of `cosa tag` as of late to help with keeping
track of which build has what modifications and ensuring they don't get
pruned.
Let's take it one step further by teaching `cosa build` to tag a build
right after it's built. One other tiny advantage of this is that
scrolling back in the terminal, it's easier to see the output of which
`cosa build` invocation corresponds to which modifications.
=> cmd-build: add --tag switch

.cci.jenkinsfile
This is a follow-up to #879. Instead of only running `fcos.basic`, run
everything, but in parallel. This should drastically lower the amount of
time it takes to run it.
=> ci: run full kola testsuite in parallel 

src/create_disk.sh
This reverts commit e92be856d2546cdd9a7f509804246de94fae2011.
It will work now with https://github.com/coreos/fedora-coreos-config/pull/210
=> (take2) create_disk: Drop the root= and rootflags= kargs by default

src/cmd-init, src/cmdlib.sh
In the situation where cosa itself does the clone, it's really
useful for debugging to see directly in the logs the output of `git describe`
for the config.
=> Run `git describe` for config git on init and each build operation

src/cmd-run, src/deps.txt, src/swtpm-wrapper
Fixes for post-merge review of commit to add swtpm.  We want it
in dependencies to help make "has a TPM" the default.  And ensure
we clean up after ourselves.
=> Add swtpm to dependencies, ensure we cleanup tmpstate dir after `run`

src/cmd-init
In the case where submodules are only on a branch, then
the initial clone won't get them.  We were only not using `--branch`
because of RHEL7 support, which we no longer care about.  Pass
`--branch` to the initial `git clone` so it's cleaner, and we handle
submodules correctly.
=> init: Pass --branch to git clone command

src/cmd-prune
Just drop some debugging leftovers and cleanup some of the other
messages.
=> cmd-prune: minor logging cleanups

src/cmd-buildextend-installer, src/cmd-buildextend-metal, src/gf-anaconda-cleanup, src/gf-platformid, src/libguestfish.sh, src/virt-install
Two commits:
1.
installer: use lorax s390x templates, allow adding parameters at boot
Backport from PR #732 with some small changes.
2.
dasd: allow building and running
This requires libguestfs support for adding custom blocksize for image
file. The patch at upstream is :
https://www.redhat.com/archives/libguestfs/2019-November/msg00025.html
This patch or its later version should go to F30/F31 and eventually be
used by the cosa container.
We never had the issue with libguestfs/guestfish and custom blocksize on
master because we have moved away from anaconda before DASD support
landed.
=> [rhcos-4.2-multiarch] Backport #732, DASD work

src/virt-install
As suggested in
https://github.com/coreos/ignition-dracut/pull/117#discussion_r336516583
=> [rhcos-4.2-multiarch] virt-install: set ostree bootloader backend to zipl

src/cmd-remote-prune, src/cosalib/aws.py, src/cosalib/prune.py
Several cleanups in `cmd-remote-prune`, verified that it works on testing builds of RHCOS
=> Remote prune cleanup

build.sh
See all the details in:
https://bugzilla.redhat.com/show_bug.cgi?id=1770304
But the TL;DR is: there seems to be an issue in the way supermin creates
the root ext2 filesystem which became a hard error in 5.3.8. So for now,
let's just keep pulling 5.3.7.
=> Work around supermin + kernel + ext2 filesystem bug

src/cmd-buildextend-metal
Similar to fada24b7dd225f3419e170f4570c15e0c496b6d6
=> [rhcos-4.2-multiarch] metal: guard check for DASD and UEFI

src/create_disk.sh
This is analogous to
https://github.com/coreos/coreos-assembler/pull/652
We were hardcoding `fedora` here, pulling the EFI binaries
from the coreos-assembler container.  Change to installing
the *target* EFI binaries instead.
First, I verified this produces the same output
and `cosa run --uefi-secure` still works with FCOS.
But, this fixes `cosa run --uefi-secure` with RHCOS, and ensures
we're installing the RHEL8 EFI binaries.
Conceptually now, the only "traces" or "influence" that the
coreos-assembler content has on the target system will (should) be
in the created filesystem structure (i.e. what `mkfs.xfs` does on
disk), but not the actual *contents* of any files.
=> create_disk: Use target EFI binaries

src/cmd-run
AWS uses NVMe, and so does bare metal, so it's very important
to test with.  We regressed coreos-growpart recently on NVMe, see
https://bugzilla.redhat.com/show_bug.cgi?id=1769157
=> run: Add --disk-channel opt, support nvme

src/vmdeps-s390x.txt
s390x never actually needed haveged.
The only reason I put haveged in my patches in the early days, is
because I only had a z/VM guest to install F29, which would run another
supermin VM to run anaconda. And 3-4 nested virtualization layers made
it slow to generate SSH keys during early boot of supermin due to lack
of entropy.
Putting haveged here creates the impression that s390x actually has the
needs for haveged, compared to other architectures, which is not correct.
=> vmdeps-s390x: remove haveged

build.sh
The work around added to install kernel-core from koji will now install
the specific archs package.
=> Change kernel-core to be arch specific

src/cmd-remote-prune, src/cosalib/aliyun.py, src/cosalib/gcp.py, src/cosalib/prune.py
Remove images/snapshots on aliyun/gcp during `remote-prune` using `ore`
Azure is currently skipped, as its not yet implemented in `ore` (https://github.com/coreos/mantle/issues/1115).
Tested on dev builds of RHCOS pipeline
=> remote-prune: cleanup other platforms

src/estimate-commit-disk-size
I switched to f31 for my dev container, and `cosa buildextend-metal`
failed since Python 2 wasn't installed.
This was the last Python 2 script we shipped.
=> estimate-disk-size: Port to Python 3

.cci.jenkinsfile, Dockerfile
We should match https://github.com/coreos/fedora-coreos-config/pull/200
on general principle, but also specifically because we now also have
a buildroot container that derives from this, and we want to support
people building content in that buildroot that targets the host.
=> Dockerfile: Bump to f31

src/cmd-buildextend-metal, src/create_disk.sh
We did this before with `virt-install`; if an image build
fails, we always dispose of the disk image.  Using `cache=unsafe`
means that e.g. the `fsync` invocations that ostree makes
inside the build, as well as filesystem-internal synchronous
writes to the journal and metadata aren't passed through to the host filesystem
by default.  This allows the host filesystem to defer writeback,
speeding up image builds.
=> build: Use cache=unsafe when making disk images

src/libguestfish.sh
part-get-name works only for gpt partitions and hence will not work for s390x.
changing to use vfs-type instead.
=> Use guestfish vfs-type instead of part-get-name to identify luks fs

src/gf-platformid
Without this, there would be 2 instances of coreos.oem.id= in the
kcmdline.
=> [rhcos-4.2] gf-platformid: remove duplicated coreos.oem.id

src/gf-platformid
Without this, there would be 2 instances of coreos.oem.id= in the
kcmdline.
=> [rhcos-4.2-multiarch] gf-platformid: remove duplicated coreos.oem.id

src/cmd-remote-prune
A typo in args prevents from cleaning up Azure images
=> remote-prune: fix typo in azure params

src/cmd-buildextend-metal, src/create_disk.sh
For RHCOS with encryption, we encrypt in early boot, and it's beneficial
if the root filesystem size is small initially - distinct from the
"default disk" size that applies in clouds (and libvirt).
This helps RHCOS maintain its default 16G size for libvirt without
requiring the installer and other tools to start resizing it.
This also increases consistency across metal and virt - we now
*always* run `coreos-growfs`.
=> create_disk: Make rootfs size small even for qemu/IaaS

src/cmd-run
This way we're testing all 3 at least interactively.
We also dedup some of the uefi/uefi-secure code.
What we really want of course is to do this in kola...
but you know that gets right into the kola-vs-cosa issue
that's still lurking in the background still like the odd cousin you
didn't invite to your wedding...
=> run: If not specified, randomly pick bios/uefi/uefi-secure

src/cmd-kola
E.g. right now RHCOS doesn't need any test blacklisted at all.
=> cmd-kola: Fix blacklist handling when there are none

src/cmd-kola
E.g. right now RHCOS doesn't need any test blacklisted at all.
(cherry picked from commit 8cd87313198b4bc802d61bb862bc74a9a7ef8c9f)
=> [rhcos-4.3] cmd-kola: Fix blacklist handling when there are none

src/gf-platformid
If we run `guestfish --remote sh <command>`, guestfish would run /bin/sh
in the real rootfs - which is an ostree rootfs - and /bin/sh would be
not found. Running with `debug sh` would tell guestfish to run in
supermin's initrd space instead.
This is for helping the case where a config drive (ISO) is used to pass
Ignition config file to guests, in the case of terraform's libvirt
provider.
Related:
https://github.com/dmacvicar/terraform-provider-libvirt/pull/666
https://github.com/openshift/installer/pull/2672
Co-Authored-By: Prashanth Sundararaman <psundara@redhat.com>
=> openstack: build on s390x

src/cmd-buildextend-metal
On each s390x hypervisor, a tty would be automatically detected by the
kernel and systemd, there is no need to specify one. However, we keep
DEFAULT_TERMINAL as ttysclp0, which is helpful for building/testing with
KVM and virtio (cmd-run).
Some discussion
https://github.com/coreos/coreos-assembler/pull/700#discussion_r313281586
https://github.com/coreos/coreos-assembler/pull/733#discussion_r322117632
=> s390x: right the tty on target ostree sysroot

src/cmdlib.sh
The latest rpm-ostree now supports YAML for overrides:
https://github.com/coreos/rpm-ostree/pull/1914
Let's teach cosa to look for it so we can use it in FCOS.
=> cmdlib: add support for YAML override lockfiles

src/gf-platformid
If we run `guestfish --remote sh <command>`, guestfish would run /bin/sh
in the real rootfs - which is an ostree rootfs - and /bin/sh would be
not found. Running with `debug sh` would tell guestfish to run in
supermin's initrd space instead.
Running zipl inside ostree rootfs assumes /etc/zipl.conf exists, which
is created by anaconda in 4.2 branch.
coreos/fedora-coreos-tracker#278
This is for helping the case where a config drive (ISO) is used to pass
Ignition config file to guests, in the case of terraform's libvirt
provider.
Related:
dmacvicar/terraform-provider-libvirt#666
openshift/installer#2672
Co-Authored-By: Prashanth Sundararaman <psundara@redhat.com>
=> [rhcos-4.2-multiarch] openstack: build on s390x

src/cmd-buildupload
Automatically detect the type of data being uploaded and set the
`Content-{Type,Encoding}` headers accordingly if not overriden.
This allows one to do `curl --compressed` to decompress on the fly. Note
we don't automatically do the `Content-Disposition: inline; filename=`
trick; this was found to be more confusing than useful in practice.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/295
=> cmd-buildupload: Set Content-Type and Content-Encoding headers

src/gf-platformid
I was trying to do this in order to ensure we clearly detect
corruption.  But in an exciting plot twist, doing this appears
to work around the reflink bug at least for me!
=> gf-platformid: fsck the boot partition after changing it

Makefile, src/cmd-build, src/cmd-buildprep, src/cmd-buildupload, src/cp-reflink, src/create_disk.sh, src/gf-platformid
I spent a few hours yesterday trying to figure out why my Azure images
were failing to boot in the cloud with:
error: ../../grub-core/fs/fshelp.c:257:file `/grub2/i386-pc/normal.mod' not found.
What it came down to was whether or not we were doing a reflink copy in
`gf-platformid`. (My root filesystem is configured with reflink support,
so `--reflink=auto` would use reflinks.)
I seem to be hitting a kernel regression of some kind where reflinks +
interactions with guestfish cause the `grub2/` directory of the boot
partition to become corrupted:
```
$ guestmount -a tmp/azure.vhd -m /dev/sda1 tmp/mount && ll /srv/rhcos/tmp/mount
ls: cannot access 'grub2': Bad message
total 20
drwxrwxr-x. 2 root root  1024 Nov 19 11:55 efi
d?????????? ? ?    ?        ?            ? grub2
-rw-rw-r--. 1 root …
```
=> gf-platformid: use `qemu-img create` instead of reflinks

src/gf-platformid, src/libguestfish.sh
This is all we need; no reason to touch the other partitions
and possibly dirty their superblocks, etc.
Motivated by chasing down corruption with reflinks.
=> gf-platformid: Just mount the boot partition

src/cmd-build-validate, src/gf-fsck, src/libguestfish.sh
We're seeing corrupted images when using reflinks; this
is a standard way to help find that.
We also validate the checksum.
- https://github.com/coreos/coreos-assembler/pull/935/commits/d47d3e6c7311808a0a7938c02b083948bc4ef0f6
- https://github.com/coreos/coreos-assembler/pull/936/commits/97fc409e56f3c6cf764c5e5c0171fdcada2d20bf
Note that this only works on uncompressed images right now.
=> Add a `build-validate` command

src/cmd-buildextend-metal, src/finalize-artifact
I was recently reading `man qemu` and noticed this snippet:
```
-snapshot
Write to temporary files instead of disk image files. In this case, the raw disk image you use is not written back. You can however force the write back by pressing C-a s.
```
`cosa run` uses `-snapshot` and I heavily rely on it not mutating
the disk image.  Qemu having this magic command to mutate the disk
image could lead to really evil debugging sessions.
And I verified that in fact it works today to press `C-a s`.
Further, we use `qemu-img create -b` with backing files, and
that will completely break if the underlying backing file is
mutated.
This patch closes that down by removing write access from our
generated disk images.  When running processes as an ordinary user
without `CAP_DAC_OVERRIDE`, this denies …
=> Change access mode to remove write permission from some artifacts

src/cmd-buildextend-metal
We should not try to build uefi by default on s390x and instead build
dasd and bios only.
=> Set default metal builds for s390x to dasd/bios

src/cmd-koji-upload
Since 1.19.1 of koji the _unique_path def was officially removed,
however the progress_callback def does not exist. This causes the Except
clause to be called which then fails because _unique_path does not
exist.
We should Try/Except each import individually, to ensure we use the
appropriate import.
=> Try Except individually on module imports

Makefile
This ensures that we pass options down to the child `make`,
including the jobserver, etc.  Quiets a warning output
during build about this.
https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html#Options_002fRecursion
=> build-sys: Use $(MAKE) instead of make

src/cmdlib.sh
We may need to run some commands in e.g. `podman unshare`,
and `sudo` won't work in that scenario, but we have the privileges
we need.  So just avoid requiring `sudo` if our uid is zero.
=> cmdlib: Only check sudo if we're not root

Makefile
To pick up https://github.com/coreos/mantle/commit/ca54c767faf93b462ca355cb06e192d697efcfee
=> [rhcos-4.3] mantle: bump to current master (39bcb1b)

README.md
Writing the `cosa()` function as indicated in the README let us with an error when running the function.
```
$ cosa shell
cosa:2: bad pattern: # 
```
Removing the offending part **# so we can see what command gets run** remove this issue.
```
$ cosa shell
+cosa:3> podman run ....
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[coreos-assembler]$
```
=> remove the commented line in the cosa shell fucntion

src/cmd-buildextend-installer
Prep for splitting out the rootfs.squashfs into a separate file
in the ISO mounted independently, rather than having it be
part of the initramfs.  The main problem I hit is that doing
FSBCOS live images didn't work as the resulting initramfs is
too big.
This patch just adds a volume ID (which means inserting the
ISO shows up with a nicer `/dev/disk/by-label/` instead of
just `CDROM`), and adds a kernel argument that can be used
by code in the initramfs to find that.
=> installer: Add volume ID and coreos.liveiso= karg referring to it

src/image-base.ks, src/virt-install
Same as https://github.com/coreos/coreos-assembler/pull/932.
We only need to change what goes into Kickstart file and we can keep the
console= in virt-install since it only matters for build process, so
less conditional changes.
=> [rhcos-4.2-multiarch] s390x: right the tty on target ostre sysroot

src/cmd-aliyun-replicate, src/cmd-aws-replicate, src/cmd-buildextend-aliyun, src/cmd-buildextend-aws, src/cmd-buildextend-azure, src/cmd-buildextend-gcp, src/cmd-buildextend-installer, src/cmd-buildextend-openstack, src/cmd-buildextend-vmware, src/cmd-buildprep, src/cmd-compress, src/cmd-tag, src/cmdlib.sh, src/coreos-assembler, src/cosalib/cli.py, src/oscontainer.py
Before, we were setting it in `cmdlib.sh`, but the entrypoint (which is
the code that actually `exec`s any Python commands) doesn't source that.
Move the export directly there instead.
=> Set PYTHONUNBUFFERED=1 in the entrypoint

src/deps.txt
We ran into this recently where we thought a process was stuck.
After getting strace into the container we saw that it wasn't stuck,
just taking a really long time.
=> deps.txt: add strace for debugging running processes

src/cmd-buildextend-metal, src/virt-install
User feedback says that `bios` image is misleading for zFCP SCSI image on
s390x as in the context of comparing to DASD image, even though the
`bios` image basically is `zfcp`.
Add --zfcp option for s390x besides --dasd.
Also add a check to make sure only s390x runs --zfcp and --dasd. Other
arch continue using --bios and --uefi.
Code that depends on <work-dir>/builds/latest/meta.json should adapt for
this change.
=> [rhcos-4.2-multiarch] s390x: make zfcp as an replacement for bios on s390x

src/cmd-koji-upload, src/cosalib/build.py
With the architecture work, the Koji upload command was left a bit behind. This updates the command to be properly arch-aware and to act on multiple architectures (e.g. detached uploads).
=> cmd-koji-upload: properly support architectures #813

src/cmd-koji-upload
This fixes a number of architecture related bugs with the Koji upload
process, notably:
- No longer assumes the running host's architecture. Architecture of a
build is now discerned and enforced from the meta.json.
- Allows selection of the architecture via `--arch` flag
- When an artifact should be arch-aware, a pathing check is performed.
(cherry picked from commit 3f9bcd3133b8d5896e40a391728ff25dfdd2c88b)
=> cmd-koji-upload: properly support architectures.

src/cmd-buildextend-metal
* Include ppc64le for BIOS only
* Change the logic to 2 separate if statements, since the 2 are not
exclusively if/else.
=> Fix logic for acceptable builds per ARCH

src/cosalib/cmdlib.py
I downloaded the openstack image from
https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/4.2.0/
and used `guestfish` to hack the platformid back to `qemu`, but `cosa run`
failed because it didn't recognize the image prefix.
Detect both versions.
=> Expand RHCOS Ignition detection to handle rhcos-4.2.0- images

Dockerfile
We want to get the latest RPMs, this is the standard hack for
this absent an explicit API on the build system side to do so.
(Like how OpenShift buildconfigs have an option)
=> Dockerfile: Blow out Quay.io cache

src/cmd-koji-upload
Saw the following failure in the RHCOS pipeline:
```
+ coreos-assembler koji-upload --keytab /srv/.keytab/keytab --buildroot builds --owner rhcos-build/jenkins-redhat-coreos.cloud.paas.upshift.redhat.com@REDHAT.COM --profile brew --tag rhaos-4.3-rhel-8-build
Traceback (most recent call last):
File "/usr/lib/coreos-assembler/cmd-koji-upload", line 659, in <module>
cli()
File "/usr/lib/coreos-assembler/cmd-koji-upload", line 642, in cli
build = Build(args.buildroot, args.build, arch=args.arch)
File "/usr/lib/coreos-assembler/cmd-koji-upload", line 104, in __init__
_Build.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'arch'
```
It looks like `args.build` needs to be passed as kwarg, instead of
positional.
=> koji-upload: pass build as kwarg

src/cmd-kola
On s390x and pcc64le, there is no TPM device support in qemu. With support in
mantle to run without TPM(#970 and #971), enforcing this option for s390x and pcc64le
so kola tests can run
=> Run kola without TPM on s390x and pcc64le

src/cmd-koji-upload
Saw the following failure in the RHCOS pipeline:
```
+ coreos-assembler koji-upload --keytab /srv/.keytab/keytab --buildroot builds --owner rhcos-build/jenkins-redhat-coreos.cloud.paas.upshift.redhat.com@REDHAT.COM --profile brew --tag rhaos-4.3-rhel-8-build
Traceback (most recent call last):
File "/usr/lib/coreos-assembler/cmd-koji-upload", line 659, in <module>
cli()
File "/usr/lib/coreos-assembler/cmd-koji-upload", line 642, in cli
build = Build(args.buildroot, args.build, arch=args.arch)
File "/usr/lib/coreos-assembler/cmd-koji-upload", line 104, in __init__
_Build.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'arch'
```
It looks like `args.build` needs to be passed as kwarg, instead of
positional.
(cherry picked from commit …
=> [rhcos-4.3] koji-upload: pass build as kwarg

src/cosalib/build.py
Prior to this change, the _Build object was only aware of the
running-host's architecture. This change use the meta.json to determine
the architecture instead of blind assumptions.
(cherry picked from commit 8cf2e3327c39a123c29aea5209cd8d168be15e8b)
=> [rhcos-4.3] cosalib/build.py: make _Build object arch aware.

src/cmd-kola
Following up on #973, for the kola test runs to be successful on
s390x and pcc64le, the TPM test has to be excluded. An arches option would
be useful to list the arches to exclude. Here is an example:
- pattern: rhcos.luks.tpm
tracker: none
arches:
- s390x
- ppc64le
If no arch is specified, it means blacklist on all arches
=> Support blacklisting kola test by arch

src/cmd-buildextend-fulliso, src/cmd-buildextend-installer
Depends https://github.com/coreos/coreos-assembler/pull/927
This is a variant of the live ISO which:
- Moves the rootfs to the ISO instead of the initramfs, to avoid hitting size limitiations (affects Silverblue)
- Includes the `metal.xz` image so it can be installed to disk
=>     Add "fulliso" build type

src/cmd-build, src/cmd-buildextend-metal, src/finalize-artifact, src/write-commit-object
Following up to our previous change to `chmod a-w` the qemu image
to avoid corruption:
- Rework the `finalize-artifact` API to also move into place
so that its usage is more direct/required.
- Use it in more places
This makes a default `cosa build` + `ls -al builds/latest/x86_64`
show no write access.
=> Remove write access from more artifacts

src/cmd-sign
This code broke with the change to have artifacts read-only (#986).
Really, we shouldn't be editing the tarfile in-place like this. Use the
standard copy, modify, rename pattern instead.
=> cmd-sign: use copy and rename pattern for OSTree tarball

src/cosalib/cmdlib.py
RHCOS 4.4 will continue to use Ignition spec2, so update the function
accordingly
=> cosalib: detection of Ignition version for RHCOS 4.4

src/cmd-run
We'd like to support IPv6 only environments; make it convenient
to do that with `cosa run`, also prep for testing a kola patch.
However, I can't get `ip=dhcp6` to work with this, seems like
nothing is responding on the qemu side.  Learned a bit about
slirp, but haven't debugged it yet.
=> run: Add --ipv6only

src/cmd-buildextend-metal, src/create_disk.sh
I'd like to move in the direction of using fs-verity.  First, if
we detect the target kernel has `CONFIG_FS_VERITY`, we use it
unconditionally for `/boot` since that's already ext4, and we don't
need reflinks there.
To aid further development work here, add `rootfs: verity` as an option
in `image.yaml`.  But this isn't the default because we don't
want to trade off incomplete security for performance (reflinks).
=> Add support for 'rootfs: verity'

src/cmd-sign
RoboSignatory signing is normally pretty fast. We've hit the worst case
scenario however today, where our request was queue behind a request to
sign texlive, which has ~6000 subpackages...
Ideally, it'd be able to handle multiple requests at once. Though for
now, just adapt for this. Note that this is different from signing
failures; RoboSignatory does reply back if something went wrong with
signing. So we won't just sit there for 1hr if e.g. we didn't send a
proper request or something.
=> cmd-sign: bump timeout to 1 hour

src/create_disk.sh
Let's opt-in to this by default.
See https://github.com/ostreedev/ostree/issues/1265
This currently is a no-op if the required ostree support hasn't
landed yet, so I think we can safely merge this PR first.
=> create_disk: Enable read-only /sysroot

src/cmd-buildextend-metal
The metal dasd images were huge - 17G which was causing OOMs when trying to
install the images on a zVM. Fixed it to use estimated size rather than use
the one from image.yaml
=> Fix DASD image size for s390x

src/cmd-buildextend-metal
The metal dasd images were huge - 17G which was causing OOMs when trying to
install the images on a zVM. Fixed it to use estimated size rather than use
the one from image.yaml
(cherry picked from commit 9893a8305a3d9d79fc69a78038e4b4f44588f9bc)
=> [rhcos-4.3]: Fix DASD image size for s390x

.cci.jenkinsfile
So that if tests fail, we can actually try to diagnose the failure.
=> ci: always archive kola results

src/gf-platformid
We can't use backing files since we can't rely on users to have
them.
Another approach would be flattening after, but I think the
copy approach is clearer.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/327
=> platformid: Copy (reflink) rather than use qemu-img snapshots

src/cmd-meta, src/cmd-run, src/cosalib/meta.py
Will simplify the rpm-ostree test suite which also grew some shell/`jq`
for this similar to the removed code in `cmd-run`.
=> Add `cosa meta --image-path`

src/cmd-buildupload
https://github.com/coreos/coreos-assembler/pull/862#issuecomment-567069130
This regressed OpenShift on OpenStack installs, which had adjusted
to deal with the lack of `Content-Encoding` and a switch to add `.gz`
to images.
Basically, if we're going to say things are explicitly compressed,
let's not also tell people to *transparently* decompress them because
it's easy to end up with a file named `.gz` that was decompressed.
=> buildupload: Don't set Content-Encoding for gzip

src/cmd-build
Alternative pull request to https://github.com/coreos/ignition-dracut/pull/145
=> Updated platformid to force openstack for s390x on 4.2

src/cmd-compress
Even if they're compressed by a different compressor.
(How many more derivatives of the word `compress` can we fit in this
commit message?)
This came up with `buildextend-gcp`, which currently hardcodes `tar.gz`,
because that's what the cloud wants when uploading. But then we'd
recompress it again with `xz` at the `compress` stage, which probably
gains us some space, but having a `.tar.gz.xz` is pretty confusing.
=> cmd-compress: skip compressing already compressed files

Dockerfile, build.sh
As the new comment says:
Yes, this is a hack that loses sane auditing around what git commit
we used to build fcct, etc.  In the future we'll probably give in and package
it or something, see also https://github.com/coreos/fedora-coreos-tracker/issues/235
But for now I want to have it in cosa by default so we can use it;
see also https://github.com/coreos/coreos-assembler/pull/670
=> Build and add fcct

src/cmd-buildextend-rojig
For Fedora Silverblue I want to possibly switch to rojig by default.
There are a few reasons for this; among them that on more "pet"
systems package layering is natural and rojig becomes advantageous
then.
This small buildextend just wraps up the rpm-ostree glue for
this into the cosa model.
=> buildextend-rojig: New command

src/cmdlib.sh
Make it match the name of the directory it was synthesized from to make
it easier to tell where it comes from. Doing this mostly to aid
debugging, though this name does also actually end up in the tree too in
`/usr/share/rpm-ostree/treefile.json`.
=> cmdlib: rename overrides/rootfs ref

src/cmd-buildextend-metal, src/cmd-offline-update, src/cmdlib.sh, src/offline-update-impl
We need to do some upgrade testing.  My specific goal here
is to be able to use `kola`, which is oriented around providing
Ignition - so we need to do the update fully "offline".  I wrote
the quick/obvious script to do this and ran up against the need
for absolutely horrid hacks if grub2-mkconfig is still needed.
But anyways, it works.
=> Add `offline-update` command

src/cmd-compress
=> compress: Skip rojig too

src/cmd-buildextend-rojig
It's `sha256` and not `checksum`; this caused `cosa compress` to fail.
=> rojig: Use correct name for sha256 checksum

src/cmd-buildprep
The immediate use case here is using `buildextend-aws` on a previous
build to add it to a new AWS region.
But this is also useful for any other custom changes to a previous
build, including adding to entirely new clouds, or testing changes.
=> buildprep: Add support for fetching a particular build

src/cmd-sign
Run the process that will publish the message from a new process rather
than just a fork so that we don't inherit e.g. the Twisted state.
This is a quick fix until we rework this differently for better sharing
with other tools in the FCOS pipeline that will need to interact with
the fedmsg bus.
For details, see: https://github.com/coreos/fedora-coreos-pipeline/issues/178
=> cmd-sign: Publish message in fresh process

src/deps-aarch64.txt, src/deps-x86_64.txt, src/vmdeps-aarch64.txt, src/vmdeps-x86_64.txt, src/vmdeps.txt
Recent move to unify deps+vmdeps broke ppc64le as
`shim` was in pure `vmdeps` but it's arch dependent.
#1018 (comment)
This reveals more duplication between the two; move bootloader
bits consistently into `vmdeps-$(arch).txt`.
=>  Move shim dependencies into vmdeps-$(arch).txt

src/offline-update-impl
This is all so elegant if the bootloader just reads BLS files in `/boot`...
but we don't live in that world yet.
`zipl` needs to be rerun when that changes.
=> offline-update: Handle zipl too

src/incomplete-hack-ign-3to2
I hit this in a config that only writes `systemd` units.
=> hack-ign-3to2: Don't crash if no storage section is defined

src/buildextend-rojig-impl, src/cmd-buildextend-rojig
Trying to actually deploy this in the FSBCOS pipeline, it failed
because it wants privileges, just like the main compose path.
Tweak things so that we do the same "run in VM if not privileged"
that main composes do.
The code/logic for this stuff really needs cleaning up and deduping,
it's quite messy.  Particularly because the supermin API is only
in shell.
We had some duplicates between `deps.txt` and `vmdeps.txt`; let's
consistently have the rpm-ostree bits in `vmdeps.txt`.  We
specifically need `rpm-build` in `vmdeps.txt` for rojig.
=> buildextend-rojig: Support unprivileged mode

src/cmd-test-coreos-installer
We have no coverage of coreos-installer today.  This was a quick
hacky shell script I wrote a few months ago and posted as a gist:
https://gist.github.com/cgwalters/bf6f5b6f788d01211dbe6cd362309a0d
This could obviously be cleaned up and de-duped with kola and
other cosa bits, but for now, let's just get some coverage.
Specifically e.g. one thing I want to do is support running
a specific kola suite (maybe just `basic`) against the newly installed image.
=> Add cmd-test-coreos-installer

.cci.jenkinsfile, src/cmd-buildextend-installer
In FCOS, we're looking to drop the installer ISO in favour of the live
images:
https://github.com/coreos/fedora-coreos-tracker/issues/203
https://github.com/coreos/fedora-coreos-config/pull/261
AFAIK, RHCOS should be able to follow suit once the new
coreos-installer binary makes it there.
Until then though, rather than entirely drop support for building it, at
least check upfront that the `installer/` directory exists so we don't
do a bunch of work for nothing.
=> buildextend-installer: error out early if missing src config

Dockerfile
This is essentially the same as 88c17bc
We want the `rhcos-4.3` tag to have the latest version of `rpm-ostree`
so folks can pull and build locally if they want to.  But the last two
attempts to rebuild the container are using the cached RPM layer and
therefore pulling in and older version of `rpm-ostree`
(rpm-ostree-2019.6.24.gfec61ce5-1.fc31.x86_64)
=> [rhcos-4.3] Dockerfile: blowout quay.io cache

src/cmd-buildextend-metal, src/create_disk.sh
ext4 fs-verity requires the fs block size to be the same as the kernel page
size, and different architectures use different page sizes. So, we have to
query the host page size and use that as the block size when fs-verity is
enabled.
We also have to take the block size into account in the rootfs size estimation,
since larger blocks waste more disk space with internal fragmentation.
Fixes #1031
=> create_disk.sh: Query the host page size when fs-verity is enabled

src/cmd-ore-wrapper
We were using `startswith()` directly on `argv[0]` to know which symlink
we were called as, but that might be the full path to the script. So
pass through `basename()` first.
Closes: #1039
=> cmd-ore-wrapper: fix using basename to auto-detect command

src/cmd-ore-wrapper, src/cosalib/aliyun.py, src/cosalib/aws.py, src/cosalib/azure.py
This addresses un-intended consequences with the refactor:
- reraise exceptions with the @retry wrapper
- use arg.region since '--region' and '--regions' are synonyms
- use the old meta.json 'amis' instead of 'aws'
- introduce wrapper for `ore` call `run_ore' to de-duplicate the
the logging code and support use of --config-file
=> cmd-ore-wrapper: fix publication regressions

src/cosalib/gcp.py
Use GCP's regex to enforce the naming of GCP uploads.
=> cosalib/gcp.py: check the name for an upload against GCP's regex.

src/cosalib/aliyun.py
Further fall out from the massive refactoring. This adds back in the --name-suffix and s/write_meta/meta_write.
end-to-end tested with the RHCOS pipeline.
=> cosalib/aliyun.py: re-add --name-suffix and correct meta_write

src/gf-platformid
If we run `guestfish --remote sh <command>`, guestfish would run /bin/sh
in the real rootfs - which is an ostree rootfs - and /bin/sh would be
not found. Running with `debug sh` would tell guestfish to run in
supermin's initrd space instead.
This is for helping the case where a config drive (ISO) is used to pass
Ignition config file to guests, in the case of terraform's libvirt
provider.
Related:
https://github.com/dmacvicar/terraform-provider-libvirt/pull/666
https://github.com/openshift/installer/pull/2672
Co-Authored-By: Prashanth Sundararaman <psundara@redhat.com>
(cherry picked from commit f2c39f404a5222b23a3ecbf8def68b3405891b59)
=> [rhcos-4.3] [backport] - openstack: rerun zipl after changing platformid on s390x

src/cmd-kola
Right now we're kind of in a messy situtation where we have some args
for `cosa kola`, and other args that we want to pass through to `kola`.
Unfortunately, argparse isn't very good for this use case. Using `--`
helps sometimes, but the issue arises when we want to pass flags to
*both* cosa and kola. The obvious `--cosa-arg -- --kola-arg` doesn't
work (https://bugs.python.org/issue15112).
Instead, just use `parse_known_args()` to tell argparse to leave the
unknown args untouched. We then pass those through as is to `kola`. This
also avoids us having to use `--` entirely. The caveat is that it can be
confusing if we support a `cosa kola` arg that `kola` natively supports,
but let's say we're not going to do this, or if we do, it's to just pass
it through to kola as well as do some …
=> cmd-kola: transparently pass unknown flags to kola

src/cmd-koji-upload, src/cosalib/aliyun.py, src/cosalib/azure.py, src/cosalib/build.py, src/cosalib/gcp.py
This fixes two problems:
- Azure was missing the `ore` command. 
- GH-1049: for RHCOS builds the commitmeta.json is present, however, only Koji uploads generally require it. This changes the `cosalib.build._Build` to have conditional checks on the required artifacts needed to parse the meta-data.
=> cosalib: fix azure and required meta-data

src/cmd-meta, src/cosalib/build.py, src/cosalib/meta.py, tests/test_cosalib_meta.py
Drop the meta.json reading, writing and parsing function in favor of the GenericBuildMeta class. This moves all `cosalib` functions around the GeneraicBuildMeta instead of having two handlers.
This also changes the interface for `GenericBuildMeta.{get,set}` to support the `dict` such that it can used like a standard `dict` or as a nested one. The `get` and `set` functions now use `arg[0]` to determine the path.
=> cosalib/build.py: drop 'meta.json' handling infavor GenericBuildMeta

src/cmd-run
For FCOSB, we don't have a `core` user by default (since we always
expect gnome-initial-setup to make one) in the usual path.  And
right now `cosa run`'s Ignition isn't automatically adding the `core`
user it says to the `wheel` group.
In a lot of cases it's much more convenient to directly log in
as the `root` user anyways.  So let's support `cosa run --user=root`.
=> run: Support --user root
