src/create_disk.sh
src/grub.cfg

Backport of https://github.com/coreos/coreos-assembler/pull/1067.
---
That way, it'll work on both IPv4 and IPv6 networks.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1793591

[rhcos-4.3] grub.cfg: set ip=dhcp,dhcp6

---

src/cmd-buildextend-metal

This breaks the use case of `coreos-installer` being run
from an older system like e.g. Debian stable.
We're not actually making use of verity yet, so let's back
off from that, keeping the code as an option:
`bootfs: ext4verity` in `image.yaml`.
We will revisit this when the verity research plays out more.

Don't enable verity for /boot by default

---

src/create_disk.sh

When we added the `rootfs` variable for the path that overwrote the earlier
one which is now called `rootfs_type`.  This wasn't noticed because
only the verity path checked for the type after filesystem creation.

create_disk: Fix conflicting "rootfs" variables

---

src/cosalib/aliyun.py

If no config is given, we don't want to pass the empty string as a
separate argument. Split out that logic so we only append the arg if
it's provided.

aliyun: fix passing '' to `ore aliyun copy-image`

---

src/cosalib/gcp.py

Get the URL from what mantle computed rather than trying to re-compute
it here.
Closes: https://github.com/coreos/coreos-assembler/issues/1078

gcp: Fix invalid URL in metadata

---

src/create_disk.sh

It's still experimental, update per review in
https://github.com/ostreedev/ostree/pull/1959

create_disk: Update to use ex-fsverity OSTree option

---

src/cmd-kola

The rationale for this is that it's a different "kind" of test, and so
it shouldn't clobber the results of a previous `cosa kola run`
invocation. It also makes it easier to run in parallel with it.

cmd-kola: change default output dir for upgrade testing

---

.cci.jenkinsfile
Makefile
fixtures/rhcos.json
src/cmd-meta
src/coreos-assembler
src/cosalib/meta.py
src/deps.txt
src/schema/v1.json
tests/test_cosalib_meta.py

Change the interaction of in `cosalib` to prevent writing and reading in invalid `meta.json`
This changes:
- cosalib/meta.py: added validators
- schema/*: added schema and example`meta.json`
For example, after _intentially_ corrupting `meta.json`:
```
$ cosa meta --build latest --get "coreos-assembler.basearch"
jsonschema.exceptions.ValidationError: '' does not match '^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3'
Failed validating 'pattern' in schema['properties']['coreos-assembler.build-timestamp']:
{'$id': '#/properties/coreos-assembler.build-timestamp',
'default': '',
'examples': ['2020-01-15T19:32:19Z'],
'pattern': '^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\,
'title': 'Build …
```

Introduce and enforce `meta.json` schema 

---

src/create_disk.sh

The PreP partition needs to be the first partition for installation on most ppc systems
including powerVM which IBM is testing openshift installations on.

Make PreP partition the first partition for ppc64le

---

src/cmd-virt-install

As the comment says this code is bits we eventually want
in the main `virt-install` program.  However, my immediate
motivation here is to use libvirt with `qemu:///system` to test ipv6.
We could also use libvirt for other scenarios of course.

cmd-virt-install: New wrapper for virt-install

---

src/cmd-buildextend-vultr
src/coreos-assembler
src/cosalib/cli.py
src/cosalib/qemuvariants.py
src/cosalib/vultr.py

* Build a raw image with the Ignition provider set to vultr to correspond with https://github.com/coreos/ignition/pull/918
With this, I was able to build a new coreos-assembler and use it to build a `fedora-coreos-31.20200128.dev.0-vultr.x86_64.raw` that claims to have the `vultr` platform id set. No change to Ignition yet, so its not of practical use yet, but its something.
```
cosa build
cosa buildextend-vultr
```

src/cmd-buildextend-vultr: prepare a Vultr raw image

---

src/schema/v1.json

I install coreos-assembler inside my existing toolbox so that
I can have one place to develop on e.g. rpm-ostree and other
tools.  This needs to be supported, even if not a primary path.
In this scenario we won't have the bits from `Dockerfile` builds,
so remove those from the required metadata keys.

schema: Unmark container-config* keys as required

---

Makefile
fixtures/fcos.json
src/cosalib/meta.py
src/schema/v1.json
tests/test_cosalib_meta.py

This adds support for discerning whether or not a sub-schema should
exist based on the name in 'meta.json' to support variants.
The new behavior to treat the main schema file as a basename. Any schema
that is found in the same directory with the basename is loaded. The
"name" field is then used to find any sub schemas. For example, given
"v1.json" with a build name of "fedora-coreos", a schema named
"fedora-coreos-v1.json" in the same directory will be applied.
fixtures/fcos.json: defined test JSON for Fedora CoreOS
src/schema/{fedora-coreos,rhcos}-v1.json: stub out for the different
schemas. This is to support the FCOS use of:
"fedora-coreos.parent-version" and
"fedora-coreos.parent-commit" keys.
tests/test_cosalib_meta.py: support testing both FCOS and RHCOS schemas
- looks for all …

cosalib/meta.py: support sub schemas

---

src/cosalib/build.py

We changed this behaviour during the refactor. There's quite a bit of
history here on why do this. But a major one at least is that we want to
be able to just `rename(2)` the final build artifacts into place. This
saves a bunch of time and I/O.
I noticed this due to the fact that we were losing sparsity from the
output of `qemu-img convert` because `shutil.move` doesn't do the
equivalent of `cp --sparse=auto`. This patch fixes that, though I think
we should also be able to change that call to a simple `os.rename()` in
a follow-up to make it explicit.
Related: https://github.com/coreos/fedora-coreos-tracker/issues/361

cosalib/build: Use workdir tmp/ as tempdir

---

src/cosalib/qemuvariants.py

GCP is picky about the tarball contents. They must:
- be in a tarball with gzip compression
- use the Old GNU format
- be sized correctly
- members must be sized right
With the new method of generating qemu variant images, CLI tar commands
were replaced with pythonic methods; this produces invalid tarballs from
GCP's perspective. To support GCP, the method of tarball creation is
reverted to using the CLI.

qemuvariants: fix regression in GCP tarball format 

---

src/cmd-artifact-disk
src/coreos-assembler
src/cosalib/build.py
src/cosalib/cli.py
src/cosalib/meta.py
src/cosalib/qemuvariants.py

This fixes the "COSA_META_SCHEMA" to support the value of `NONE`, while I work out the nuances of the schema. 
To skip the meta.json validation: set the `COSA_META_SCHEMA=NONE`
To change the json: `COSA_META_SCHEMA=<path to your schema>`
Or on the CLI: `cosa <cmd> --schema=none`
This should negate the immediate need of https://github.com/coreos/coreos-assembler/pull/1087

cmdlib: Add logic for default meta.json schema or skipping validation 

---

src/schema/v1.json

Support overrides as optional.

schema: add missing coreos-assembler-overrides-active key

---

src/oscontainer.py

And if present, inject the OpenShift labels for `machine-os`.
Currently this is inlined for OKD (FCOS) in
https://github.com/openshift/release/blob/27a5d056b53aba5818795c2ee03d053f754d75da/ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml#L533
This will be used for RHCOS to have its version appear in the
release image.
xref https://github.com/openshift/oc/pull/209#issuecomment-564876535

oscontainer: Add support for --display-name

---

src/cmd-koji-upload
src/cmd-ore-wrapper

coreos-assembler today is a mix of Go, Python (two different kinds)
and shell.
The Go and shell script don't output timestamps in logs, and neither
do other Python scripts.
Having just the newer Python code print timestamps looks odd.
Further, higher level tooling such as Jenkins and the systemd journal
already gather timestamps.  There's no need for us to do it here as
a general rule.
And we're realistically never going to have the whole code base
be just one form.
I think in general what would be nicer is if Python's logging
framework supported having `log.info()` => `print()`, and only
emit the log level if it's not INFO.

ore,koji: Remove timestamps from Python log formats

---

src/cmd-sign
src/cosalib/fedora_messaging_request.py

This PR re-factors out the code that sends requests to fedora
releng/infra via fedora messaging messages into a library. It can
then be called by the code in src/cmd-sign as well as new consumers
in the future.
Also implements request_id for fedmsg passing in cmd-sign.

refactor fedora message sending into cosalib/fedora_messaging_request.py

---

src/create_disk.sh

Ensure that all the efi binaries are included from the target.
Fixes https://github.com/coreos/coreos-assembler/issues/1090
We have a couple problems with our UEFI Secure Boot story:
1. The full UEFI/EFI binaries were not copied over. In order to do a
compliant EFI boot, BOOT<ARCH>.EFI should be there.
2. /usr/lib/ostree-boot/efi/BOOT/BOOT<ARCH>.EFI is a symlink
to /usr/lib/ostree-boot/efi/<VENDOR>/shim<ARCH>.efi.
This requires that a copy be made.
3. /boot/efi/EFI/<VENDOR>/grub2.cfg was not complete. It needed to
load the /boot/grub2/grub2.cfg file and then boot.
4. Without mmx64.efi, Secure Boot will not work since key-regristration does not happen.

create_disk: fix UEFI secure boot

---

.cci.jenkinsfile

Same rationale as https://github.com/coreos/fedora-coreos-pipeline/pull/187
Motivated by ensuring we're covering proposed changes like
https://github.com/coreos/coreos-assembler/pull/1105
in CI here too.

ci: Run --basic-qemu-scenarios

---

src/create_disk.sh

create_disk: put $ignition_firstboot last on kernel command line
Since $ignition_firstboot is expanded at runtime and also can be
used to add more kernel command line arguments [1] we should make it
last on the line so that it's possible to override other kargs. This
should fix the ordering issue mentioned in [2]
[1] https://github.com/coreos/coreos-assembler/blob/7f7965de5d6233b99c6a3f841d86be92dab6100e/src/grub.cfg#L43-L58
[2] https://github.com/coreos/fedora-coreos-tracker/issues/353#issuecomment-583165021

create_disk: put $ignition_firstboot last on kernel command line

---

src/cosalib/aliyun.py
src/cosalib/aws.py

On both AWS & Aliyun `ore` can resume in the middle of the process.
Switch up the logic to default to not passing force.

src/cosalib: don't always force uploads for aws & aliyun

---

src/cmdlib.sh

The error if this is missing isn't obvious; this came up
with someone trying a custom build.

cmdlib: Require automatic-version-prefix in manifest

---

src/cmd-test-coreos-installer

A simple change that demos `kola qemuexec`, centralizing more
of the qemu logic into kola.

test-coreos-installer: Use kola qemuexec

---

src/cosalib/cmdlib.py
src/cosalib/qemuvariants.py
src/cosalib/vmware.py

cosalib.vmware overrode mutate_image and then called
QemuVariant.mutate_image with the callback. While working a seperate
issue, I started to define another class to use the call-back mechanism.
Rather than introduce another Class, this change allows for a class
attribute of "mutate_callback" to be defined which is used by default
unless `mutate_image(callback=foo)` is called.
The advantage to this approach is that VMware's OVA can be a bit
simpler.
Finally, a format check was added to ensure that the format is
appropriately changed. In some cases, 'qemu-img convert' will produce
'raw' images instead of compliant VHD's.

qemuvariants: simplify VMware OVA generation by using callback

---

src/schema/v1.json

Use a more liberal pattern for FCOS parent version.

schema: use liberal pattern for FCOS parent version.

---

src/cmd-buildextend-ibmcloud
src/coreos-assembler
src/cosalib/qemuvariants.py

This adds a new qcow2-based image for the `ibmcloud` platform,
which can be booted on IBM Cloud VPC Generation 2.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/277
Closes: https://github.com/coreos/coreos-assembler/issues/1119

qemuvariants: add ibmcloud

---

build.sh

To avoid hitting "sudo: /etc/sudoers.d/wheel-nopasswd is world writable" in cosa.

build.sh: Contents of /etc/sudoers.d need not to be world writable

---

Dockerfile

We want to pull in the v2020.1 version of `rpm-ostree` for the
`exclude-packages` support[0].  @jlebon was nice enough to rebuild
`rpm-ostree` with that support in F30, so blow out the cache to make
sure we pick it up.
[0] https://github.com/coreos/rpm-ostree/pull/1980

[4.2] Dockerfile: blow out quay.io cache

---

src/cmd-list
src/coreos-assembler
src/cosalib/builds.py

This is useful in the dev workflow to quickly fetch the buildid of a
previous build, as well as just look at all the builds one has available
locally, how stale they are, and their associated tags. Kind of like a
`git status` or `rpm-ostree status` for `cosa`.

Add `cosa list` to list basic info of local builds

---

src/gf-platformid

A previous change to make the PreP partition as the first partition for ppc64le
broke openstack image generation.

Fix e2fsck on boot partition for ppc64le

---

src/cosalib/cmdlib.py
src/cosalib/qemuvariants.py
tests/test_cosalib_cmdlib.py

Per [1] Azure VHD's require to be:
- size aligned to 1MB
- subformat of 'fixed'
In the docs, Microsoft indicates that the VHD must be 1MB aligned. Per
[2], "force_size" creates an aligned disk by calculating CHS values and
forcing the size to align. The "hack" for doing manually resizing to 1MB
is supperfulious in the case `force_size`. Further COSA creates MB
aligned disks too.
Confirmed that this produces bootable disk images for Azure.
[1] https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic
[2] https://git.qemu.org/?p=qemu.git;a=commitdiff;h=fb9245c2610932d33ce14

qemuvariants: produce fixed disks for Azure

---

src/cmd-run

The value of `run` today is you get dropped directly into a console
and can do things like change the kernel cmdline interactively,
debug dracut etc.
We had a lot of duplication of qemu code here which got drained
into qemu; close the loop here and finally get rid of all the
shell logic for qemu, reusing the exposed kola qemu CLI args.
Drop the SSH support, as it duplicates `kola spawn`.

 run: Use kola qemuexec, drop ssh support

---

src/cmd-test-coreos-installer

This is the first PR for non x86 arches support for the coreos installer test. This is mainly
needed for the pipeline to build rhcos and so ppc64le and s390x are the main focus. Used grub for
netbooting ppc64le since I am not sure about pxe support in ppc64le although there are some conversations I have had with folks who seem to think there is pxe support.
TBD: s390x does have pxe support although it's taking a bit of figuring out , but this PR should set the stage for easily adding s390x support - which I am investigating.

Support coreos installer test for non-x86 arches starting with ppc64le

---

src/cosalib/build.py

Correct invalid key of 'sha256sum' to 'sha256', which was invalid per
the schema.

cosalib/build.py: fix invalid sha256sum key to sha256

---

src/deps.txt

I plan to migrate the installer test to mantle and it will
use this.  And eh let's include it on general principle so
people using cosa have it automatically.

deps: Add coreos-installer

---

src/cmd-meta

So I can shell out to it from kola.  (Yes, this is a great example
of the pain of mantle vs cosa that I'm encountering working on
enhancing testing)

cmd-meta: Add --ignition-version

---

src/cosalib/qemuvariants.py

Minor regression from #1136. The `ustar` format only supports uids up to
2097151. This of course blows up in OpenShift where we run with much
higher uids.
Really though, we don't want to encode the OpenShift uid either anyway.
Instead just canonicalize to uid and gid 0. On extraction, tar defaults
to extracting files as the running user.

qemuvariants: always ship tarfiles with uid/gid=0

---

Dockerfile
build.sh
src/cmd-koji-upload

We want to pull in the v2020.1 version of `rpm-ostree` for the
`exclude-packages` support[0].  @jlebon was nice enough to rebuild
`rpm-ostree` with that support in F30, so pull in the necessary commits for us to us the F30 coreos-continuous repo.
[0] https://github.com/coreos/rpm-ostree/pull/1980

[4.1] start using F30 coreos-continuous repo

---

src/cosalib/qemuvariants.py
src/cosalib/vmware.py
src/vmware-template.xml

Addresses wrong VMDK file size and `Did not find an .ovf file at the beginning of the OVA package` from https://github.com/coreos/fedora-coreos-tracker/issues/391.
Tested on VMware Workstation 15.5.1 and vSphere 6.7.0.
I also have a commit (not in this PR) that generates a manifest file, but it doesn't work.  `ovftool` correctly parses the VMDK hash out of the manifest, but then concludes that the digest of the actual VMDK has some other value.  Manual verification of the VMDK from the tarball shows that the manifest is correct.  I'm not sure why this is happening, and absent other ideas I'm planning to file a draft PR and ignore for now.

vmware: Several fixes and cleanups

---

src/create_disk.sh
src/gf-platformid

Recently it was seen that the s390x openstack images don't run ignition
at all. This was because when zipl was rerun after changing the platformid
the firstboot options weren't included. This fixes the bug.

gf-platformid: Add firstboot options before zipl rerun for s390x

---

src/create_disk.sh
src/gf-platformid
src/grub.cfg

We need more patches in dracut for this to work properly. So just revert
it for now so that pure-IPv4 environments work correctly, which are much
more common than mixed IPv4/IPv6 setups.
This reverts commit d7329ab162277775e90c450a8fb37b60a57634a3.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1803926

Revert "grub.cfg: set ip=dhcp,dhcp6"

---

src/schema/v1.json

The goal for this is to remove duplicated items and prep the schema for
code generation.

schema: clean-up for use with schematyper

---

.cci.jenkinsfile
tests/test_pruning.sh

Minor adjustments to move CI from the previous projectatomic-ci to the
new coreos-ci.
At the same time, split out the pruning tests into its own script to
clean things up a bit.
Requires: https://github.com/coreos/coreos-ci/pull/5

ci: migrate to new coreos-ci project

---

Makefile

When I'm simultaneously working on cosa and mantle it's really
annoying to have my mantle changes blown away when I `makesudoinstall`
in cosa. (This is yet another pain point of the projects being separate)

build-sys: Add SKIPMANTLE environment variable

---

src/cmd-buildextend-exoscale
src/coreos-assembler
src/cosalib/cli.py
src/cosalib/exoscale.py
src/cosalib/qemuvariants.py
src/schema/v1.json

Add Exoscale provider to build the qcow2 for ignition Exoscale
https://github.com/coreos/ignition/pull/922
Can be tested:
```shell
cosa build
cosa buildextend-exoscale
```
https://github.com/coreos/fedora-coreos-tracker/issues/384

Add exoscale provider

---

src/buildroot-buildreqs.txt
src/buildroot-specs.txt
src/install-buildroot.sh

For rpm-ostree, we keep the canonical spec file upstream. Use that
instead of the latest deps of the last release since it's going to be
more up to date.

buildroot: support list of spec files to builddep

---

src/buildroot-buildreqs.txt

Followup to https://github.com/coreos/coreos-assembler/pull/1154/commits/afbff9584cd1bf15076d7f3e861fc0083ad59d03
libdnf currently is pulling in the older one, and anyways we
should have its transitive dependencies from rpm-ostree.

buildroot: Remove libdnf's requirements in favor of rpm-ostree

---

.gitmodules
bottlecap
build.sh
src/deps.txt
src/estimate-commit-disk-size

While we're in the mood for deleting git submodules, let's also delete
the ostree-releng-scripts. In practice, we don't use it in cosa itself,
and it's trivial for anyone who wants a script from there while e.g.
debugging from a cosa container to `git clone` it.
This also allows us to clean up the build script a bit.

Drop ostree-releng-scripts git submodule

---

mantle/generate

Now that cosa/mantle are merged, we no longer need to awkwardly
have mantle fetch something from cosa.

mantle: Tweak schema generation script to use local cosa

---

mantle/cmd/kola/kola.go
src/cosalib/cmdlib.py

Drop the duplication between mantle/cosa here.  Which - not
to totally beat this dead horse but - notice how trivial this is
as one nice single commit.
Also drains more Python into Go, continuing the crude but
straightforward "exec kola as subprocess" model.

Use sdk.TargetIgnitionVersionFromName() from mantle

---

mantle/.gitattributes

To hint that these are generated and shouldn't show up in Github
PR renderings.

mantle: Add .gitattributes for vendor/

---

src/cmd-buildextend-installer
src/deps-ppc64le.txt

The ppc64le iso image generated thus far was broken because ppc64le doesn't support efi booting.
Use grub2-mkrescue to generate a grub eltorito style iso which uses xorriso underneath

cosa:Generate bootable installer iso for ppc64le

---

src/cmd-buildextend-installer
src/deps-ppc64le.txt

The ppc64le iso image generated thus far was broken because ppc64le doesn't support efi booting.
Use grub2-mkrescue to generate a grub eltorito style iso which uses xorriso underneath
(cherry picked from commit 8f244bed88e05f8237c2e415cbf8e6d7e147e86e)

[rhcos-4.3] cosa:Generate bootable installer iso for ppc64le

---

mantle/kola/cluster/cluster.go
mantle/kola/harness.go
mantle/kola/tests/crio/crio.go
mantle/kola/tests/docker/docker.go
mantle/kola/tests/upgrade/basic.go

I'm trying to add `kola run-ext-bin` which doesn't quite
want `TestCluster` which is tied in with a `Harness` and a suite
of tests.  Lower these methods to functions that operate on
an array of machines.

kola: Rework scpKolet and dropFile to be generic APIs

---

mantle/network/ssh.go

Tracking down why the outputdir was being removed in some
kola code I'm writing took me...way too long.  I was setting
`MANTLE_SSH_DIR` and the agent code here was then assuming
ownership of this dir.  I think that's wrong; if the dir
was externally provided then we don't own it.

mantle: Don't delete agent dir if MANTLE_SSH_DIR is specified

---

mantle/cmd/kola/bootchart.go
mantle/cmd/kola/console.go
mantle/cmd/kola/kola.go
mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/spawn.go

We had the pattern of a "do" function wrapping a "run" function
that returned `error` in a few more places.

kola: Port more main functions to Run*E*

---

mantle/cmd/kola/testiso.go

Code cleanup, and also fix build since a recent PR
to the rest of kola conflicted.

kola/testiso: Port to Run*E*

---

Makefile

It no longer has a reason to exist now that mantle isn't a git
submodule.

build-sys: Remove SKIPMANTLE environment variable

---

src/schema/v1.json

It's a boolean, not a string (the former was overriding the latter).
Noticed this in VS Code which has a generic "duplicate key in JSON"
linter.

schema: Fix duplicate key in overrides-active

---

.dependabot/config.yml

We don't use git submodules anymore, so drop this.
Closes: #1186

 tree: delete Dependabot config

---

mantle/sdk/ignversion.go
src/cmd-run

We're still carrying Ignition spec v2 for RHCOS 4.5, so update the
code appropriately.

mantle: update Ignition spec detection for RHCOS 4.5

---

mantle/cosa/cosa_v1.go
src/schema/v1.json

In looking to teach `ore` how to directly interact with the schema, I
found that there is a huge a problem with cross-language support for
"patterns" (the GoLang validators only support a subset) and then the
"anyOf" and "if/then/else" support is spotty at best.
Further, I came to find that the Python validator doesn't _really_ work
as we expected and is buggy.
In light of needing to support GoLang and Python, simplifying the schema
seems to be the best course for the time being.

End schema complexity experiment; simplify the schema for x-lang support

---

mantle/Makefile

This really hurts the edit-compile-debug cycle; not sure why
we started doing that.

mantle: Stop cleaning every build

---

mantle/cmd/kola/testiso.go
src/cmd-test-coreos-installer
src/gf-mksquashfs

The `testiso` command now supports testing both `live-initramfs`
and `initramfs` (legacy installer).
TODO:
- Support testing the "just run Live" case - maybe try to figure out
how to have main `kola` tests apply?
- Test `coreos-install iso embed` path

testiso: Add support for testing live path too

---

mantle/cmd/kola/qemuexec.go
mantle/platform/qemu.go
src/cmd-run

Add support for explicitly configuring the hostname as provided
from DHCP - prep for testing this.

 run/kola-qemuexec: Add DHCP hostname support

---

src/gf-mksquashfs

`cosa buildextend-live` was failing due to the LUKS container,
update `gf-mksquashfs` to use the new internal guestfish wrapper
which knows how to handle it.  Plus it's simpler.

gf-mksquashfs: Use API to run+mount to fix RHCOS case

---

mantle/kola/tests/ignition/mount.go

As with mounting disks, the same change is needed for mounting partitions for s390x. A little
delay in pushing this because of this issue in ignition: https://github.com/coreos/ignition/pull/930
which is now fixed

mantle: kola: use by-partuuid instead of by-partlabel for mount test

---

src/create_disk.sh
src/gf-platformid
src/grub.cfg

This reverts commit 055f5585750dfa93b123a9ef99f01148dbde9719.
Packages are almost in place for this to work now. And we're not going
to update bootimages again until then. So let's get this back in so
we're ready to go once all the packages make it.

Revert "Revert "grub.cfg: set ip=dhcp,dhcp6""

---

mantle/cmd/kola/kola.go
mantle/cmd/kola/spawn.go
mantle/platform/util.go

Right now, `kola spawn` immediately kills the node once we leave the SSH
session. This is nice most of the time for quick testing. But it
basically throws out the window anything that requires rebooting (which
oddly makes it more limiting than `cosa run`, which does). And sure,
there's always libvirt for more persistence, but I think there's room
for another gradation level here.
Add a new `--reconnect` switch which can handle this. In this mode, we
constantly try to reconnect to the node after getting disconnected. One
can simply do Ctrl-C to kill the node.

kola/spawn: add --reconnect switch

---

mantle/cmd/kola/testiso.go

Micah hit this trying to test locally.  While we're here
also validate both the kernel/initramfs exist too.

testiso: Validate that we have a `metal` image

---

mantle/cmd/kola/spawn.go

Follow-up to #1214.
Otherwise, exiting with Ctrl-C can cause cloud instances to leak. (We
could install signal handlers for this... but really we should have
stronger binding with the underlying resource so that one doesn't have
to Ctrl-C at all).

kola/spawn: restrict --reconnect to qemu platform

---

mantle/cmd/kola/qemuexec.go
mantle/platform/qemu.go

This is useful for quickly testing static IP addresses on the
kernel cmdline without actually having to catch the GRUB
prompt or go through a whole series of `coreos-installer iso embed`
etc.

 kola/qemu: Support injecting kernel network arguments

---

mantle/cmd/kola/switchkernel.go

Adds a sub-command that uploads the RT Kernel RPMs to a machine and switch between kernels using `rpm-ostree`.  The logic used to switch between Default Kernel and RT Kernel is defined in  https://github.com/openshift/machine-config-operator/blob/f363c7be6d2d506d900e196fa2e2d05ca08b93b6/pkg/daemon/update.go#L651.
Closes: https://issues.redhat.com/browse/GRPA-1439
Signed-off-by: Allen Bai <abai@redhat.com>

kola/switch-kernel: add a test for switching between rt and default kernel

---

mantle/cmd/kola/spawn.go
mantle/harness/suite.go
mantle/kola/harness.go
mantle/platform/journal.go
mantle/platform/machine/azure/flight.go
mantle/platform/machine/esx/machine.go
mantle/platform/platform.go
mantle/platform/qemu.go

It's better since it avoids e.g. accidentally forgetting the `%v`
at the end and allows accessing the underlying error.
By porting some of the existing code we increase the likelihood
that people use it in new code.

mantle/*: Use errors.Wrapf() in more places

---

src/libguestfish.sh

We were using `mount-ro`, but weren't passing `--ro` to guestfish
itself, so it would still try to reopen all disk images passed to it as
rw. This will fail of course if the image file is read-only.

libguestfish.sh: actually use --ro for read-only runs

---

src/libguestfish.sh

This reverts commit 42e429332448c0ca364bb00a4892bf8b50136062.
It's causing at least one of our images (aws) to not get the
right platform.id set in the BLS configs that grub sources.
This means AWS doesn't look in the right place for the user-data
and no ignition config gets applied.

Revert "libguestfish.sh: actually use --ro for read-only runs"

---

mantle/cmd/kola/options.go
mantle/sdk/ignversion.go
src/cmd-kola

This drains more code from assembler into mantle.

kola: Use --cosa-build for Ignition version inference automatically

---

mantle/kola/tests/ignition/mount.go
mantle/util/common.go

Revert to using by-partlabel for non s390x arches since that is the supported method. Required a bit
of refactoring to achieve this. This would probably also help mitigate https://bugzilla.redhat.com/show_bug.cgi?id=1812233
as we started seeing more failures with not being able to find the device after moving to partuuid.

kola: Use by-partlabel for mount tests except on s390x

---

src/cmd-build
src/cmd-fetch

Right now, we ignore the override lockfile if a base lockfile isn't
present. This mostly works, but it prevents the case of bodhi-updates
where we want to override only some packages but leave the "base"
unlocked.
Tweak things so that both the base and override lockfiles can be used
independently.

Allow having only an overrides lockfile

---

mantle/cmd/kola/switchkernel.go

This one was missed as it was developed concurrently.

kola/switchkernel: Add SilenceUsage

---

mantle/cosa/build.go

Previously we'd just say "fails validation", which isn't very
helpful for debugging.

mantle: Actually display schema errors

---

src/cmd-run

This helps debugging when trying to figure out what `cosa run` is
actually doing, and if one wants to drop down to `kola qemuexec`
directly.

cmd-run: print kola qemuexec command before running

---

mantle/cmd/kola/testiso.go
mantle/platform/metal.go

Today `kola testiso` is pretty hardcoded.  I think it was @arithx 
suggested making things more generic, and this implements
that.  The core mantle `platform/` bits have an API to start
a PXE install, and the precise Ignition that gets passed in
is provided by a higher level test.
I also cleaned things up a bit in preparation for supporting
ISO testing and not just the PXE path.  (Though the code
is still messy in this respect, but this is a preparatory step)
A possible next step here is to actually implement the `Machine`
interface instead of having a custom `InstalledMachine`, that'd
make it even easier to have something like:
`kola run --pxe basic`

 mantle: Move core metal logic into platform/, use for testiso

---

build.sh
mantle/cmd/kola/options.go
mantle/cmd/kola/qemuexec.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/machine/unprivqemu/flight.go
mantle/platform/qemu.go
src/cmd-buildextend-metal
src/cmd-buildextend-metal4k
src/cmd-run
src/coreos-assembler
src/create_disk.sh

First, add a new `buildextend-metal4k` command to create 4k disk images.
Then, teach `kola` and `cosa run` to read these images.
To test:
host$ cosa run -I metal4k
...
vm$ sudo fdisk -l /dev/vda
...
Sector size (logical/physical): 4096 bytes / 4096 bytes
...
One potentially controversial bit here is that this requires a newer
libguestfs which isn't in f31 yet, so we pull it from f32 for now.
Closes: coreos/fedora-coreos-tracker#385

Add support for 4k metal images

---

build.sh

Add `f32-coreos-continuous` to the list of repos we get packages from.
This fixes the now obvious issue with hardcoding x86_64 in the
libguestfs f32 URLs.
Closes: #1248

build.sh: use f32-coreos-continuous for libguestfs

---

src/cmd-build
src/cmd-fetch

cmd-{build,fetch}: fix log message referencing wrong lockfile

---

mantle/cosa/schema.go

In PR #1225, the schema was enforced by default, changing the behavior
in the handling of meta.json. To make the developer UX a little better,
this option allows for invalid meta.json to be consumed. By default, the
schema is still enforced.
Example:
` kola --cosa-build meta.json --enforce-schema=false ...`

mantle/kola: allow invalid meta.json as a user option

---

mantle/cmd/kola/options.go
mantle/sdk/distros.go
src/cmd-kola

This way `cosa kola` thins out even more; helps running
`kola` directly and will also be useful for tests.

Move distribution detection into mantle

---

src/schema/v1.json

Now that metal4k is supported, add it to the schema
(Also noticed tests failing when metal4k image is present as it was missing from the schema)

schema: add metal4k to the schema

---

mantle/build

My pet container is currently based on F30 (yeah, I know...) and only
has `golang` 1.12 available.  When trying to `mantle/build ore`, the
build failed because the binary name was missing.
Adding the name of the binary to the parameters of `go build` fixed it
for me.  And `golang` 1.13 doesn't seem to mind the change, either.

mantle/build: explicitly specify schematyper binary name

---

mantle/cosa/cosa_v1.go

This was missed in the schema PR.

mantle/cosa: Regenerate schema for 4knative

---

mantle/kola/tests/misc/users.go

So, Fedora 32 systemd has a new interface for querying user databases so
that e.g. `getent passwd` can show dynamic users. Interestingly, this is
implemented via varlink:
https://systemd.io/USER_GROUP_API/
Anyway, there seems to be a bug right now where the `root` user shows up
twice:
https://github.com/systemd/systemd/issues/15160
And this is throwing off this test. Work around this.
While initially looking into this, I was tempted to just rip out this
test. Though it *did* catch a legitimate bug and in the process raised
awareness to an important change (I'm actually surprised this isn't
mentioned in https://fedoraproject.org/wiki/Releases/32/ChangeSet).

kola/fcos.users.shells: work-around root user NSS bug

---

mantle/system/arch.go

A lot of our code uses the portage architecture, which no longer
makes sense.  Now, the more correct code for this is part of
rpm-ostree but I'm not sure we want to go to forking off that yet.
Since the build system only supports this set of architectures
currently, let's just inline the Go -> RPM translation here.

mantle/system: Add RpmArch API

---

src/cmd-kola

So that this Just Works.  See:
https://github.com/coreos/coreos-ci-lib/pull/16#issuecomment-601271102

kola: Automatically add src/config/tests/kola if it exists

---

src/gf-platformid

Guestfish tries to create a temporary /dev when doing a chroot, so mounted this explicitly as the
filesystem is ro.

gf-platformid: Mount a temporary /dev needed for s390x when running zipl in chroot

---

src/cmd-build

I spend a lot of my time building different branches of
fedora-coreos-config to debug issues. One problem is that when changing
refs like this, there's no guarantee that rpm-ostree won't re-use the
same version string. If that happens, the build will fail with `EEXIST`
at the end when trying to move the builddir in its final place.
Work around this corner-case by pointing the new ref at the old ref. As
mentioned in the comment, this is a crude not-technically-correct hack
which in practice shouldn't really break anything. We also force a
rebuild (which should happen anyway since at least the commit metadata
changed) to be sure the ref is updated.

cmd-build: Add hack for composing across refs

---

mantle/cmd/kola/kola.go
mantle/cmd/kola/options.go
mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/testiso.go
mantle/kola/tests/ignition/mount.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/metal.go
mantle/platform/qemu.go

Fedora/RHEL are *defined* to be self hosting; which means
cross compliation is not at all the default.  See also
https://blog.verbum.org/2012/10/13/building-everything-from-source-vs-self-hosting/
The mantle code was just using Portage architecture because
of CL; unifying on the RPM architecture names as are already used
by cosa will help consolidate things.
Further, we don't need to pass a "Board" all the way down
the stack; since we don't support cross compliation there's no
reason not to just call the new global API to get it.

 mantle: Rework various bits to use new RpmArch() API

---

mantle/cmd/kola/options.go
src/cmd-run

As part of eventually making `cmd-run` go away, and also
aiding using `kola run` against 4k drives etc.

Move the "4k implies uefi" logic into kola

---

src/cmd-buildextend-installer

I was looking at this to figure out why `console` was omitted,
and noticed we could trim some cruft here.  We no longer use
`root` or `rootflags` etc. since we reworked rootfs discovery
in https://github.com/coreos/fedora-coreos-config/pull/187
etc.

buildextend-installer: Remove unnecessary kargs exclusions

---

mantle/cmd/kola/qemuexec.go
mantle/platform/qemu.go
src/cmd-run

For the use case of enabling systemd debugging, etc.
https://github.com/coreos/coreos-assembler/pull/1263#issuecomment-601419408

Support `cosa run --kargs`

---

mantle/platform/metal.go

Two prep patches extracted from https://github.com/coreos/coreos-assembler/pull/1268

Testiso actually iso prep

---

mantle/cmd/kola/options.go
mantle/cmd/kola/qemuexec.go
mantle/platform/conf/conf.go
src/cmd-run

I want to use this for live ISO testing, since being able to debug
on the console is super useful.
Also, this helps drain `cmd-run` into mantle.
`qemuexec` is slowly becoming something nontrivial...but most
of that mess is the Ignition conversion bits which are duplicated
around.

 Drain autologin bits into mantle

---

mantle/cmd/kola/options.go

I did a `cosa run` without a qemu image (had just done a
`cosa build metal`) and it crashed.

kola: Avoid SEGV if no qemu image

---

.cci.jenkinsfile

This races because we were doing builds/pruning in
parallel with the testiso command trying to test a build.

ci: Run testiso before test_pruning.sh

---

mantle/system/arch.go

The previous code here wasn't right for ppc64.
https://github.com/coreos/coreos-assembler/pull/1257#issuecomment-603259804

system/arch: Canonicalize ppc64, ppc64le => ppc64le

---

mantle/cmd/kola/options.go
mantle/sdk/repo.go
src/cmd-kola

The current `mantle/cosa` directory is a bit circular, we
basically have `cosa/mantle/cosa` then.  It made sense before
the projects were merged but less so now I think.
Second, the `mantle/cosa/builds.go` is really about the `meta.json`
file but we also need the *directory* for a build.  What's
going on in kola is quite weird because we basically need
to keep around the pair of (directory, parsed meta).
Enhance the `mantle/sdk` to learn about a `LocalBuild` struct
and teach kola how to use it to synthesize the other two if
`.` looks like a coreos-assembler root.
This drains more logic from `cmd-kola` in cosa, trending
towards removing it!

Teach mantle/kola how to automatically find cosa builds

---

.cci.jenkinsfile
mantle/cmd/kola/testiso.go
mantle/platform/metal.go
mantle/platform/qemu.go

Confusingly, the `testiso` command was (is) actually testing PXE installs.
It still does, but now the `platform/metal` infrastructure has a new
API to do an install via an ISO (scripting embedding an Ignition
config with `coreos-installer iso embed`).

metal/testiso: Also support installs via `coreos-installer iso embed`

---

mantle/kola/tests/misc/network.go

We switched to NetworkManager and removed dhclient in
https://github.com/coreos/fedora-coreos-config/commit/90ce41141f9349432a0621c6f0e00748e20c840f

kola/tests: Swith to expecting Networkmanager vs dhclient

---

mantle/cmd/kola/kola.go
mantle/cmd/kola/options.go
mantle/cmd/kola/testiso.go
mantle/kola/harness.go
mantle/kola/tests/upgrade/basic.go
mantle/platform/metal.go
mantle/platform/platform.go
mantle/sdk/repo.go
src/cmd-kola

Instead of keeping separate the build metadata object and the build
directory, let's instead raise the visibility of `sdk.LocalBuild`, which
bundles those two things together already.
What I initially set out to solve was that `cosa kola --build ID` no
longer worked, because we weren't passing `--cosa-build` to kola
anymore. But even if we did, it's silly to have `cosa kola` dig into
build dirs to fetch the path to the `meta.json` when `kola` now knows
how to do that.
Concretely, this changes three things:
1. we add a `--cosa-workdir` to allow specifying a cosa dir other than
the current working dir.
2. the `--cosa-build` argument is now a build ID, not a path to a
`meta.json`.
3. `kola.CosaBuild` is now a `LocalBuild` so that we also have access to
the build directory everywhere.

kola: promote concept of sdk.LocalBuild throughout

---

mantle/platform/qemu.go

Switching to version "max" will pick the highest correct version, allowing running test suite on wider range of aarch64 hosts.

kola/qemu: Use max supported gic version on the aarch64 host

---

src/print-dependencies.sh

If no line is selected by grep, non-zero code is returned, ignore it for archful deps, allowing for empty archfull deps files. This fixes build of cosa image on aarch64.

deps: Allow empty archful deps files

---

src/cmdlib.sh

Qemu has convenient shorthand CLI arguments to do what we
want here.  We're explicitly not using virtio because supermin
hardcodes `/dev/sda` sadly.
Prep for changing this code to use `kola qemuexec`.

cmdlib: Use -hda/-hdb instead of virtio-scsi incantations

---

mantle/cmd/kola/options.go
mantle/cmd/kola/qemuexec.go
mantle/platform/qemu.go
src/cmd-run

Since the lifetime of the temporary file we generate needs
to be bound to the qemu process, teach the qemu API to
take an Ignition config directly and do a conversion as necessary.
This drops all the now unnecessary conversion stuff from `cmd-run`.

Move Ignition conversion into qemu API

---

mantle/Makefile
mantle/kola/harness.go

While not a comprehensive fix as suggested here: https://github.com/coreos/coreos-assembler/pull/1257#issuecomment-603281524
this helps to unblock kola tests on non x86 arches

kola: Use RpmArch() instead of architecture()

---

mantle/cmd/kola/qemuexec.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/metal.go
mantle/platform/qemu.go

First, we don't hard require a config, so there's no reason
to force people to pass the empty string if they don't want one.
Second, this is prep for further work on 9p mounts which want
to build up a config and qemu arguments simultaneously.

mantle/qemu: Rework API to allow setting Config after creation

---

mantle/cmd/kola/qemuexec.go
mantle/go.mod
mantle/platform/conf/conf.go
mantle/platform/qemu.go
src/cmd-run

Drain another thing out of `cmd-run`.  This is prep for making
`cmd-run` be a tiny wrapper around `kola qemuexec`.
Also, using 9p mounts can be very useful for testing; i.e. this
helps unlock having qemu-specific tests that bind mount in data
without copying.
(One thing I'm thinking for example is that we support pulling
container images from the host)

 Move 9p mount logic into QemuBuilder/qemuexec

---

src/cmdlib.sh

This reverts commit ad728abd00cc631a3484ba7156313f0485545b02 because
it apparently doesn't work on s390x/ppc64le:
https://github.com/coreos/coreos-assembler/pull/1288#issuecomment-605094147

Revert "cmdlib: Use -hda/-hdb instead of virtio-scsi incantations"

---

mantle/kola/harness.go

Followup to previous commit; `boardToArch()` is now dead code,
and we might as well just have `scpKolet` get the arch rather
than its callers.

kola: Minor arch cleanup

---

src/cmd-ore-wrapper
src/cosalib/aws.py

When replicating AMIs across regions, the default is to use the first
region + AMI ID pair in the list of AMIs in `meta.json`.  This is
typically `us-east-1`.
When trying to replicate AMIs to AWS China regions, the RHCOS pipeline
uses a separate set of credentials that does not have the ability to
copy the AMI from `us-east-1`.  In this case, we want to be able to
specify a source region in AWS China where the AMI can be copied from.

aws: provide way to select source-region

---

mantle/kola/tests/ignition/units.go

This PR is not mergeable until  (https://github.com/coreos/ignition/pull/934) PR gets merged.

kola/tests/ignition: add test for systemd instantiated units

---

mantle/Makefile
mantle/build

Previously we were generating the Go schema source each time
`make` is run, which forces the Go compiler to do more work
and slows down iteration.
`Makefile` rules are designed for this, so use that instead.

build-sys: Only build schema if source changed

---

src/cmd-buildextend-installer

We don't technically *need* this anymore; I've changed RHCOS
to fully use the `-diskful` targets.
But, filtering out that karg would have also fixed the core
bug of the LUKS bits trying to kick on the live system,
and it's just cleaner to have it filtered out.
(I wrote this before fixing RHCOS to use the `-diskful` targets)

buildextend-live: Also filter out rhcos.root kernel argument

---

mantle/cmd/kola/kola.go
mantle/cmd/kola/options.go
mantle/cmd/ore/packet/create-device.go
mantle/cmd/ore/packet/packet.go
mantle/fcos/metadata.go
mantle/platform/api/packet/api.go
mantle/platform/api/packet/fcos-x86_64.ipxe

Unlike CL, FCOS allows us to override the platform ID of the PXE image.  That allows us to put the installer Ignition config into userdata, which lets us drop the requirement to upload files to a remotely-accessible URL.  Instead, allow the user to pass an URL to an iPXE script (which references the installer kernel/initrd) and an URL to the image to be installed.
By default, mantle will use an iPXE script URL that points to the cosa GitHub repository, and an image URL fetched from FCOS stream metadata.  This means we'll use a static installer image, but that seems like a reasonable tradeoff in order to avoid implementing a webapp or requiring mantle to upload a file.
Drop the "board" abstraction within Packet code and use Fedora arch names.  This means we have to call amd64 "x86_64". …

mantle/*/packet: rework for FCOS

---

mantle/cmd/ore/aws/upload.go
mantle/cmd/plume/prerelease.go
mantle/platform/api/aws/ami.go
mantle/platform/api/aws/images.go

FCOS/RHCOS have never used them.  There's a small behavior change: `ore aws upload` no longer appends `-hvm` to the AMI name.
Also drop some CL SDK defaults from `ore aws upload`.

mantle: Drop support for PV AMIs

---

mantle/cmd/kola/qemuexec.go
mantle/platform/qemu.go
mantle/system/nproc.go
src/cmd-run

Today if you type `cosa run` you get the host CPUs, but
all invocations of `kola` (including `kola spawn` to log in
via SSH, as well as all tests) use exactly 1 processor.
This doesn't make sense - it's just a historical artifact.
This continues the move of cosa qemu logic into mantle so
we can use it for tests.  For now though, `kola qemuexec` learns a
`-C` argument to guess the number of CPUs.
Yes, the technical debt reduction from the mantle/cosa merger
is STILL GOING!
With a few more patches `cmd-run` will turn into just
`exec kola qemuexec [a few args]`.

Move "detect host CPUs" into mantle

---

.cci.jenkinsfile
mantle/cmd/kola/options.go
mantle/cmd/kola/testiso.go
mantle/platform/metal.go
mantle/platform/qemu.go

The `-boot once=d` technique only works with some bootloaders. OVMF is
not one of those. Instead, do what libvirt also does, which is to use
`bootindex=N` flags, which both SeaBIOS and OVMF understand. Though the
libvirt VM installation workflow goes one step further here and sets the
`bootindex=1` for the CD-ROM only on first boot, then turns off the
machine, changes the boot order (and ejects the CD media entirely), then
boots it back up. Here instead, we're just relying on the primary disk
being unbootable on first boot to avoid having to stop QEMU and starting
it again with slightly different args (which is totally possible for us
to do, just more complex).
This fixes `kola testiso -P --qemu-firmware=uefi` (and by extension,
`--qemu-native-4k` too). But note UEFI PXE booting still …

platform/{metal,qemu}: use bootindex=N instead of `-boot once=d`

---

mantle/cmd/kola/options.go
mantle/cmd/kola/qemuexec.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/machine/unprivqemu/flight.go
mantle/platform/qemu.go
src/cmd-run

While looking at providing support for Multipath, I needed the ability to setup Multipathed disks.

Kola: add support for multipath devices

---

mantle/cmd/kola/testiso.go
mantle/platform/metal.go
mantle/platform/qemu.go

First, add an API for creating channels that give a pipe
to the Go side, so we don't need to write to temp files that
we then read.
Now, I'm still trying to fine-tune the interface between the
"metal" API and the more hardcoded "testiso".
Tweak things so that the install path supports being provided
a builder object, but add an API that creates a default one
that mostly just sets up the default max memory.
(Also, I stopped trying to special case a lower memory for
the legacy install because that's going to go away anyways)

mantle: Rework testiso/metal to use new qemu channel API

---

mantle/cmd/kola/options.go
mantle/cmd/kola/qemuexec.go
mantle/platform/machine/unprivqemu/flight.go
mantle/platform/qemu.go
mantle/system/exec/exec.go
src/cmd-run

This changes up the multipath support by using a NBD server to open the
the qcow2 disks.
This was explored due to https://github.com/coreos/coreos-assembler/pull/1296#issuecomment-606956427

Qemu: use nbd sockets for multipath disks

---

mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/testiso.go
mantle/kola/tests/ignition/qemufailure.go
mantle/platform/machine/aws/machine.go
mantle/platform/machine/azure/machine.go
mantle/platform/machine/do/machine.go
mantle/platform/machine/esx/machine.go
mantle/platform/machine/gcloud/machine.go
mantle/platform/machine/openstack/machine.go
mantle/platform/machine/packet/machine.go
mantle/platform/machine/unprivqemu/machine.go
mantle/platform/platform.go
mantle/platform/qemu.go
mantle/platform/util.go

Pairs with https://github.com/coreos/ignition-dracut/pull/146
What we really want is to use this in kola, will do as a
separate followup.

qemu: Support monitoring for failures in the initramfs

---

src/cosalib/aws.py

Noticed this when I did `cosa buildextend-aws` (without `--upload`)
and then tried to do `cosa aws-replicate`.  Without this change, it
would blow up with a KeyError since the AMIs were never uploaded.

cosalib/aws: check for 'amis' key in buildmeta

---

src/cmd-buildprep

Just treat 403 as ENOENT too; this is common for APIs to do (like AWS)
and we don't support HTTP basic auth here anyway.

cmd-buildprep: also treat HTTP 403 as ENOENT

---

src/cmd-artifact-disk
src/cosalib/build.py
src/cosalib/qemuvariants.py
src/cosalib/vmware.py

Passing --build= isn't working. I fixed it using this but I think
there is probably a better fix in order somewhere.

cosalib: fix --build= argument passing

---

src/cmd-koji-upload

This is some fallout from 3c32c70. Convert cmd-koji-upload to
also use just kwargs for everything.

cmd-koji-upload: update to all kargs for _Build from cosalib

---

mantle/cmd/ore/gcloud/upload.go
src/cosalib/gcp.py

Some cleanup in here to remove CL specific bits and change the code from mutating the image name on upload. See the individual commit messages for more info.
- mantle/ore: gcloud: clean up a lot of CL specific bits in upload.go
- mantle/ore: gcloud: remove bucket subpath from GCE image name

mantle/ore: gcloud: clean up upload.go, stop mutating image name

---

mantle/platform/qemu.go

Just a code cleanup that we can do now that both PRs
have landed.

qemu: Use new channel API for initramfs failure

---

src/cmd-run

Let's provide a hostname by default, because the default
`ibm-p8-blah-blah-blah` is just too long.  This was a subtle
fallout from the `cmd-run` gutting.

run: Set hostname to `cosarun`

---

mantle/cmd/ore/gcloud/deprecate-image.go
mantle/cmd/ore/gcloud/upload.go
mantle/platform/api/gcloud/api.go
src/cosalib/gcp.py

In GCP we'd like to use Image Families [1] so that a user can specify an
Image Family (like `fedora-coreos-stable`) and that will always reference
the latest stable Fedora CoreOS GCP image. The way image families work
is that when the image family is referenced the latest non-deprecated
image from that Image Family is returned. We'd like to have only the
latest released image be in a non-deprecated state in our image families
at any given time.
The strategy for how we use this mechanism is that we create images
in our pipeline when the pipeline runs. The image will be associated
with an image family at that time (unfortunately you can't associate
an image with an image family afterwards), but we will immediately
mark it as deprecated so it won't be used. Upon running the release
pipeline …

mantle/ore: gcp: add image family support, add deprecate image functionality

---

mantle/cmd/ore/gcloud/upload.go
src/cosalib/gcp.py

GCP expects a certain image description to be attached to images in the
format of `DISTRO, DISTRO RELEASE, VERSION, INFO`. We need to be able to
specify a description for our images when they are created.

mantle/ore: glcoud: add ability to specify image description for gcp uploads

---

mantle/kola/tests/upgrade/basic.go

This works around a subtle issue in rpm-ostree/libostree dropping D-Bus
transactions due to `mount` causing a cache flush and hanging for a
while due to slow I/O.
As mentioned in the comment there, we should drop this in the future and
rework things in the stack proper instead so we're not susceptible to
this.
See https://github.com/coreos/coreos-assembler/issues/1301.

fcos.upgrade.basic: sync after untarring OSTree tarball

---

src/cosalib/gcp.py

This is a revert of f2f6f65. The downstream pipeline has been changed
to provide `gs://` in the bucket argument so we're good now.

cosalib/gcp: remove compat code for callers providing --bucket  gs://*

---

mantle/cmd/ore/gcloud/create-image.go
mantle/cmd/ore/gcloud/upload.go
mantle/cmd/plume/release.go
mantle/platform/api/gcloud/image.go
src/cosalib/gcp.py

We consider the VIRTIO_SCSI_MULTIQUEUE, UEFI_COMPATIBLE,
and SECURE_BOOT flags to be standard now so we can
unconditionally add them to GCP images we create and get
rid of the --fcos option.

mantle/api: gcloud: remove FCOS specific image GuestOSFeatures

---

src/cmdlib.sh
src/supermin-init-prelude.sh

I'd like to rework our build process to use `kola qemuexec`
and complete the move all the core qemu logic into mantle.
Today our build logic ends up hardcoding specific devices like
`/dev/sdb1` which is extremely fragile.  Let's use labels instead,
and start with the cache device.
Rename the cache to `cache2.qcow2` and remove the old one so we
can reliably find the label.

Use an explicit `cosa-cache` label for cache2.qcow2

---

mantle/cmd/kola/testiso.go
mantle/platform/qemu.go

I initially thought we could just scrape the text serial
console but the ISO doesn't output there by default cry
Instead, this now depends on coreos/fedora-coreos-config#339

 kola: Test interactive ISO login without networking

---

mantle/cmd/kola/kola.go
mantle/cmd/kola/options.go
mantle/kola/harness.go
mantle/network/ssh.go
src/cmd-kola

If we have a cosa workdir active, use it.  This makes
things consistent so directly running `kola` does the same
thing as `cosa kola`.

 Drain more logic from cmd-kola into kola

---

src/cmd-prune
tests/test_pruning.sh

I'm working on supporting `cosa build -S overrides` to fast-path
committing changes in `overrides/`.  If the most recent build
was a shortcut build though I want to prune it explicitly.  Add
support for that.
And also fix `prune` to update the `latest` symlink correctly.

prune: Support --prune=<id>

---

src/supermin-init-prelude.sh

Regression from: https://github.com/coreos/coreos-assembler/pull/1342
We'd die in pid 1 if the cache disk isn't found, which happens in
the privileged case.

build: Fix case with privileges and no cache

---

mantle/cmd/kola/testiso.go

The RHCOS pipeline is failing because it uses `-SKL` which
excludes the first two but not the `iso-live-login` case.  Make
excluding `iso-install` also exclude `iso-live-login`.

testiso: If iso-install is excluded, also exclude iso-live-login

---

mantle/cmd/kola/testiso.go

For s390x in pXE mode, the network device has the bootindex 1. Add a disk
without specifying it as a primary disk with bootindex.
Had to open this anew because #1336 couldn't be reopened because i rebased it .

testiso: Do not add disk as primary disk for s390x pXE test

---

mantle/kola/tests/upgrade/basic.go

We allow nodes to switch streams using `rpm-ostree rebase`. Let's make
our upgrade test reflect that. One cool thing to note is that the
`upgrade-from-current` test does still use Zincati, so this still does
some sanity-checking of Zincati on the new stream.
This goes together with the previous commit, in which we've added some
support for selecting a separate starting stream.

 fcos.upgrade.basic: support rebasing to different stream

---

Dockerfile
build.sh
src/deps.txt

We ship fcct in Fedora now, so let's just add it as any other dep
instead of building it manually.

Stop building fcct, add it as a dep instead

---

mantle/cli/cli.go

There is an open issue in spf13/cobra where if a child possesses a
PreRun or PreRunE function the parent's functions are ignored. As we are
only starting logging at the top level command this causes the logging
parameters to be ignored in multiple commands today. Instead just always
call startLogging inside of the WrapPreRun function.
Closes #1321

cli: always call startLogging in WrapPreRun

---

src/cmd-compress

So we can change the pipeline to `cosa compress --artifact=metal`, then run
`cosa kola testiso` and not pay the cost of compressing the `metal`
image for each testiso job, and *then* later compress it again.

compress: Add support for --artifact

---

mantle/platform/qemu.go

It's normal for this to happen on instance shutdown.
Closes: https://github.com/coreos/coreos-assembler/issues/1354

qemu: Ignore journal fd closure in WaitIgnitionError

---

src/cmd-prune
tests/test_pruning.sh

Using `add_mutually_exclusive_group` only makes sense if there are
multiple options within the group. The `keep_options` one actually
should've been dropped as part of #943.
But we do want it now anyway to make `--keep-last-n` conflict with
`--prune`. (One could easily imagine using both options being valid,
though the code doesn't support that right now, so let's reflect that on
the CLI).

cmd-prune: fix use of add_mutually_exclusive_group

---

mantle/cmd/kola/testiso.go
mantle/platform/conf/conf.go
mantle/platform/metal.go

I think what happened here is I added conversion code for
PXE at one point, and had it in my head that all of the
paths supported it.
A few things going on here.  First, pass *parsed* Ignition types
into the `metal.go` APIs rather than strings - this is just generally
saner.
Push down Ignition conversion into `metal.go`, a lot like what
we did with `qemu.go`.
Add a helper to our handy "ignition abstraction" `conf.go` to
do what we need in a bunch of places in `metal.go` which is
to serialize and optionally convert in one go.

 Handle Ignition spec2x conversion for metal

---

mantle/cmd/kola/testiso.go

I need to debug https://github.com/coreos/fedora-coreos-config/pull/339#issuecomment-613000050
and it's blocking CI on other projects right now:
https://github.com/coreos/coreos-installer/pull/216#issuecomment-615213338

testiso: Don't run iso-live-login scenario by default

---

mantle/cmd/kola/devshell.go
mantle/cmd/kola/qemuexec.go
src/cmd-run

This finally unifies the advantages of `cosa run` and `kola spawn`.
I kept getting annoyed by how serial console sizing is broken
(e.g. trying to use `less` etc.).  Using `ssh` via `kola spawn`
addresses that, but it means you can't debug the initramfs.
Now things work in an IMO pretty cool way; if you do e.g.
`cosa run --kargs ignition.config.url=blah://` (or inject a bad
Ignition config) to cause a failure in the initramfs,
you'll see a nice error (building on
https://github.com/coreos/ignition-dracut/pull/146 ) telling you
to rerun with `cosa run --devshell-console`.
Things are also wired up cleanly so that we support rebooting
with the equivalent of `kola spawn --reconnect` (which we should
probably remove now).  You can exit via *either* quitting SSH
cleanly or using `poweroff`, and …

Introduce kola qemuexec --devshell, make `cosa run` use it

---

mantle/cmd/kola/testiso.go

So we're not stuck for a long time if we hit issues.

testiso: Time out after 15 minutes

---

mantle/kola/cluster/cluster.go
mantle/kola/harness.go

The motivation for this is that there's a race in upgrade testing on AWS where we try to start the kolet httpd service *before* we actually had time to `chcon -t bin_t`. The service of course then fails to start due to SELinux violations.

kola/cluster: use "write to separate file then rename" pattern

---

.cci.jenkinsfile
src/cmd-build
src/cmd-fetch
tests/test_pruning.sh

This makes use of rpm-ostree's new `--ex-lockfile-strict`. We really
want this for FCOS CI and release builds. For more background, see:
coreos/fedora-coreos-tracker#454
This also drops the printing of lockfiles and the `sleep 1` bit,
since... I think by now people should be pretty familiar with lockfiles
and rpm-ostree prints them already (and it's easily viewable while
libsolv is loading its cache).

cmd-build: add --strict for building in strict mode

---

src/cmd-virt-install

I want to be able to `cosa virt-install --image tmp/fastbuild/fastbuild-qemu.qcow2`
just like I can `kola run`.

virt-install: Support --image too

---

src/create_disk.sh

I was looking at the ignition-dracut code and this, and I think
this deserves to be a documented value in this code.

create_disk: Hoist fixed GPT UUID to a documented constant

---

Dockerfile

We want it to pick up the new rpm-ostree.

Dockerfile: invalidate Quay.io cache for new --strict switch

---

mantle/platform/machine/unprivqemu/machine.go
mantle/platform/qemu.go

This took a bit to figure out.
Closes: https://github.com/coreos/coreos-assembler/issues/1354

qemu: Correctly check for ErrClosed on journal pipe

---

src/cmd-build
src/cmdlib.sh
src/supermin-init-prelude.sh

This is part of speeding up `cosa build-fast`; here the `dhclient`
run takes about a second out of 11 (after other speedups) so
that's a 9% win.  After rebasing on
https://github.com/coreos/coreos-assembler/pull/1289
I'll also drop out the virtio-net NIC entirely which will help
us ensure tasks that shouldn't pull external content don't.

Add RUNVM_NONET which skips dhclient in helper VM

---

.cci.jenkinsfile
src/cmd-fetch

Similar to b2355e7 for `cosa build` let's add a --strict for
fetching in strict mode. Without this we were seeing issues where
fetching would fetch a different set of packages than "build" needed
in order to do the build.

cmd-fetch: add --strict for fetching in strict mode

---

mantle/cmd/kola/devshell.go
mantle/platform/qemu.go

It's better than seconds of silence, and if e.g. we get stuck
in the initramfs then it's more obvious.
Closes: https://github.com/coreos/coreos-assembler/issues/1367

devshell: Print status as we're booting

---

mantle/cmd/kola/devshell.go
mantle/cmd/kola/qemuexec.go
mantle/platform/qemu.go

Today for architectures without `-fw-cfg` we end up rendering
the Ignition config when `SetPrimaryDisk()` is called.  This
is a confusing trap because it forces us to call `SetConfig()`
before that.
Rework the API to render the config lazily, which doesn't
fix the problem yet - but we can do so by then delaying
injecting the config to `Exec()` time which I'll do as a followup.
Also while we have the patient open, use the new
`conf.SerializeAndMaybeConvert()` API.

qemu: Lazily convert passed Ignition config

---

mantle/cmd/kola/qemuexec.go

As suggested in https://github.com/coreos/coreos-assembler/issues/1367.
(Though I went with `-c` instead of `-C` for deluxe typing speed and
comfort).

devshell: make -c a shortcut for --devshell-console

---

mantle/platform/api/gcloud/image.go

According to GCP, this feature flag is deprecated and does nothing.
cc @dustymabe

mantle/platform/gcloud: drop SECURE_BOOT GuestOsFeature

---

src/cmd-build
src/cmd-fetch
src/cmdlib.sh

The recent "no network for builds" change broke the case where
one hadn't done at least one fetch; previously this worked
because rpm-ostree would fall back to fetching, but it can't
without networking.
Explicitly error out if a fetch hasn't been done.

build: Require an explicit fetch stage

---

Makefile
src/cmd-artifact-disk
src/cosalib/aliyun.py
src/cosalib/build.py
src/deps.txt

pylint is pretty good in general at finding basic Python errors like
passing too many arguments to a function or referencing an unknown
variable, etc...
Let's make use of it.

Makefile: run `pylint -E` as part of `pycheck`

---

mantle/platform/qemu.go

f31/32's qemu doesn't yet support tpm emulation on ppc64le, missed that in my testing... This can be reverted after cosa will be using f33/qemu5.0 .

kola/qemu: Revert swtpm for ppc64le for now

---

mantle/cmd/kola/options.go
mantle/kola/harness.go
mantle/kola/register/register.go
mantle/kola/tests/crio/crio.go
mantle/kola/tests/ignition/empty.go
mantle/kola/tests/ignition/execution.go
mantle/kola/tests/ignition/mount.go
mantle/kola/tests/ignition/passwd.go
mantle/kola/tests/ignition/qemufailure.go
mantle/kola/tests/ignition/resource.go
mantle/kola/tests/ignition/security.go
mantle/kola/tests/ignition/sethostname.go
mantle/kola/tests/ignition/ssh.go
mantle/kola/tests/ignition/systemd.go
mantle/kola/tests/ignition/units.go
mantle/kola/tests/ostree/basic.go
mantle/kola/tests/ostree/unlock.go
mantle/kola/tests/rhcos/luks.go
mantle/kola/tests/rpmostree/deployments.go
mantle/kola/tests/rpmostree/status.go
mantle/kola/tests/upgrade/basic.go

Adds the ability to tag tests with a list of strings that can be used as
an alternative to pattern matching.
With the current implementation a test can be valid to be ran if either
the pattern matches OR if a tag directly matches.
Originally discussed in https://github.com/coreos/rpm-ostree/pull/2061#discussion_r408985429

kola: add tags to test structure

---

src/offline-update-impl
src/supermin-init-prelude.sh

A lot of our code wants things like `/dev/disk/by-X`.  Extracted
from https://github.com/coreos/coreos-assembler/pull/1244/

build: Run udevd in supermin appliance

---

src/cmd-buildextend-metal
src/cmdlib.sh
src/create_disk.sh

And this final commit gets rid of all of the qemu hardcoding in
cmdlib, so e.g. architecture specific changes only need to happen
in one place.
(Well, of course arch changes also end up in libvirt which we
use indirectly too, but at least *we* only have one place)

 cmdlib: Use kola qemuexec, delete qemu-kvm code

---

src/cmd-koji-upload

Regression from #1384.
The koji upload code re-uses the `_Build` class, though the latter is
more geared towards actually building new artifacts. I was tempted to
just not make it use the `_Build` base class at all here and just write
out the procedural code for this (just like `cmd-buildupload`). But
let's go with a quick fix for now.

cmd-koji-upload: set dummy platform attribute

---

mantle/cmd/kola/options.go
src/cmdlib.sh

Regression from https://github.com/coreos/coreos-assembler/pull/1289
that probably explains other mysterious problems I was seeing too.
Basically, if a qemu image already existed, we would auto-load it
with `kola qemuexec`.  In the case of builds, we absolutely do not
want to do that.
I probably didn't see this *initially* when working on this because
my build didn't have a qemu image yet.

build: Don't auto-load qemu image when building

---

src/offline-update-impl

We shouldn't hardcode `/dev/vda` anymore since it conflicts
with the rootfs, and we now have udev.

offline-update: Make use of udev now

---

src/cmd-build-fast
src/cmdlib.sh

Part of the implementation of
https://github.com/coreos/coreos-assembler/issues/1341
This is useful for me hacking on ostree/rpm-ostree.  Here we
don't need to regenerate the initramfs (usually), we just want
new ostree binaries in `/usr`.  But we *do* want the OS to be
set up as a "proper" OSTree commit, i.e. not `rpm-ostree usroverlay`.
Here this completes a qemu image (overlaid on previous) in 13 seconds,
compared to 147 seconds for a full build; 11x faster *and* we're
not writing `O(sizeof(coreos))` bytes to my SSD, but
`O(sizeof(change) + sizeof(metadata(coreos))`.
With this a workflow looks like:
```
$ cd /src/ostree
$ make && make install DESTDIR=/path/to/cosa/overrides/rootfs
$ cd /path/to/cosa
$ cosa build-fast
$ cosa run --qemu-image tmp/fastbuild/fastbuild-qemu.qcow2
```
(Or, …

cmd-build-fast: New command to iterate on content quickly

---

src/cmd-fetch

I'm working on a lockfile updater[1], and I'd like it to just be able to
do `cosa fetch --update-lockfile` the same way a human would. This
normally would run `rpm-ostree compose tree` without passing any
lockfiles and blocking out the pool so that all packages come from the
base repo.
Sadly, that doesn't currently work for FCOS right now because we have an
override for crypto-policies from f32 so that we don't pull in Python.
And because we also have an `exclude-packages` for Python, without the
f32 crypto-policies, we can't get a depsolve from just the base f31
repos. (This is the same issue that killed bodhi-updates[2].)
As a short-term hack, just include the overrides for now. This dillutes
the meaning of a "base" lockfile of course, because it will now include
the packages from the …

cmd-fetch: include overrides when updating lockfile

---

mantle/platform/qemu.go

Disable the tpm emulation on aarch64 for now, with same reasons as on ppc64le(too much rawhide qemu for me). 
And improve the smp detection code so it is not using float casts and math package. Float casts are not generally safe as they are implementation/platform depended. For me it manifests, I assume, by seeing "16" cores on 8 core aarch64 box, resulting in qemu failure. This patch fixes it for me.
```
+ kola qemuexec -m 2048 --auto-cpus -U -- -no-reboot -nodefaults -serial stdio -kernel /srv/tmp/supermin.build/kernel -initrd /srv/tmp/supermin.build/initrd -drive if=virtio,format=raw,snapshot=on,file=/srv/tmp/supermin.build/root,index=1 -virtfs local,id=workdir,path=/srv,security_model=none,mount_tag=workdir -append 'root=/dev/vda console=ttyAMA0 selinux=1 enforcing=0 autorelabel=1' …
```

AArch64 build fixes

---

mantle/cmd/kola/testiso.go
mantle/platform/metal.go

So I can use e.g.
`kola testiso -S --scenarios=pxe-install --pxe-kargs rd.break=cmdline`
to debug things.
The metal API here already accepted kargs, it just didn't work
and wasn't exposed.

Support passing kernel args to PXE installs

---

mantle/cmd/kola/testiso.go

I added `--pxe-kargs` and then accidentally edited my command
history to omit it but passed a value, and was confused
why it wasn't working.

testiso: Accept zero args

---

mantle/cmd/kola/qemuexec.go

Previously if one had just `cosa build ostree` then
`cosa run`, qemu just stalls out confused.
(But this would be a bit better with
https://github.com/coreos/coreos-assembler/pull/1380
so someone review that please!)

devshell: Fatally error if there's no disk

---

mantle/platform/qemu.go

We had separate code cleaning up:
- disk snapshots
- rendered ignition config
- swtpm
Since the swtpm code was already always making a directory, just
generalize that and use it for everything so we only have one
directory to remove.
Came out of discussion in
https://github.com/coreos/coreos-assembler/pull/1393

qemu: Use a single temporary directory

---

mantle/platform/qemu.go

Reopened on top of https://github.com/coreos/coreos-assembler/pull/1399
---
I ran out of space in `/tmp` today and it turned out I had
a whole lot of `/tmp/mantle-qemu` files, including some
really big disk images.  This is a combination of changes
from #1338
and the multipath PR #1296
Basically if we get interrupted by Ctrl-C which is a lot more
likely now when qemu isn't owning the serial console from the
start, we will leak our tmpfiles.
We probably need to install a `SIGINT` handler but that's a whole
mess that's avoided if we just let the kernel clean up our
resources for us, which is what was happening before the multipath
PR (well, at least for files and not the swtpm tmpdir, but that's
small).
And actually
#1380
does install a `SIGINT` handler so someone please review that
and we …

 qemu: Unlink non-multipath/nbd disks

---

src/cosalib/builds.py

This fixes get_local_builds error, for cmd-prune and other possible uses of get_local_builds.
Traceback (most recent call last):
File "/usr/lib/coreos-assembler/cmd-prune", line 45, in <module>
scanned_builds = get_local_builds(builds_dir)
File "/usr/lib/coreos-assembler/cosalib/builds.py", line 186, in get_local_builds
multiarch_build.basearches += [basearch_entry.name]
AttributeError: can't set attribute
+ rc=1
+ set +x
Tuples are immutable ;)

cosalib/builds: Fix get_local_builds for multiarch

---

mantle/cmd/kola/devshell.go
mantle/platform/qemu.go

This is a followup to the previous progress status for
https://github.com/coreos/coreos-assembler/issues/1367
Rather than trying to parse the serial console, just print it as
is, except strip control characters/newlines so that it becomes
effectively a progress bar.  This way, we don't corrupt the terminal,
and we don't fill up its history either.
And, go a step farther and dump the whole serial console in the
case where we get Ctrl-C before a successful login.  This aids
in debugging.

devshell: Print serial console as status line, dump when interrupted

---

src/cmdlib.sh

In https://github.com/coreos/coreos-assembler/pull/1338
we fixed the problem of having one's terminal be corrupted
by the serial console.
This fixes the same problem for `cosa build` which ends up
running a VM too.  First, there's no real reason to dump
the kernel bootup output to the terminal (or build logs) - it's
totally uninteresting stuff that we only want to see if
something fails.
Gather the serial console to one log file, and the output of
the *command* we run in the VM to another.  Fork off a
`tail` process to follow just the command output.  (When
we rewrite this in a better language we will do this properly
async)

cmdlib: Don't dump serial console to stdout

---

mantle/sdk/distros.go

RHCOS 4.6 is currently using Ignition spec v2, so update this func
accordingly.

sdk/distros: update TargetIgnitionVersionFromName for RHCOS 4.6

---

src/cmd-buildextend-installer

This is needed for https://github.com/coreos/coreos-installer/pull/220
in the PXE case to distinguish whether or not we're in the initramfs
image designed for the legacy installer.

installer: Inject stamp file /etc/coreos-legacy-installer-initramfs

---

src/cmd-fetch

By default, `cosa fetch` ignores overrides in `overrides/rpm` since
those are meant to be temporary and might be e.g. locally built
packages. (Otherwise, for example, removing a cosa override might cause
`cosa build` to fail since the no longer overridden package was never
actually downloaded).
However, it can be useful sometimes to not ignore it if we know that
it's not a "temporary" package and that it won't be found otherwise from
the regular repos. This is the case in the CI of `fedora-coreos-config`
where we use `overrides/rpm` to test composes with overrides without
having to tag them into the pool first.
Related: https://github.com/coreos/fedora-coreos-config/pull/365
Closes: #1117

cmd-fetch: add --with-cosa-overrides

---

src/cmdlib.sh

Instead of using `tail -qF`, just write the output to a virtio-serial
port and tell qemu to output that on its stdout. That way, we don't have
to worry about cleaning up the `tail` process at all.
This also fixes an issues we've been seeing where `tail` is killed
before it had a chance to print the entire command output, which
crucially might omit the final error message.

cmdlib: let qemu write command output on its stdout

---

mantle/platform/qemu.go

FCOS pipeline is seeing `swtpm/` directory in the working dir:
https://github.com/coreos/coreos-assembler/pull/1399#issuecomment-620179231
I didn't reproduce but this should fix it.

qemu: Ensure tmpdir is allocated for swtpm

---

mantle/kola/harness.go

Adds a new log file for external tests containing the journal output of
the unit under test.
Additionally contains another minor patch to tag external tests with
the `external` tag.
Closes #1408

kola/harness: log external test journal output to file

---

mantle/cmd/kola/testiso.go
mantle/platform/metal.go
src/cmd-buildextend-installer
src/osmet-pack

This is the server side required for osmet packing:
https://github.com/coreos/coreos-installer/pull/187
We run `osmet pack` when creating the live ISO and include the osmet
binary as part of the CPIO containing the root squashfs.
One thing to note is that the metal image is now always required before
building the live ISO. This is because the whole point of osmet is to
efficiently pack the metal image.
Since osmet obsoletes the `fulliso` artifact, this PR also removes
support for it.

Add support for osmet packing

---

mantle/platform/qemu.go

I passed `--qemu-image /path/to/nofile.qcow2` and got a confusing
error because we weren't propagating errors here.  One of those
things that I miss from Rust where the compiler knows to
warn about unused results.

qemu: Propagate errors from disk attachment

---

mantle/cmd/kola/devshell.go

It's a normal thing on termination.

devshell: Don't print error on EOF from serial console

---

mantle/platform/metal.go

I'd like to get coverage for
https://github.com/coreos/coreos-installer/pull/197 before it merges and
we do a release with it.
To do that, I want to test that the default installation path no longer
requires Internet access. Here, "default" means we pass neither
`--offline` nor `--stream` nor `--image-url` to
`coreos-installer install`.
Change the new `iso-offline-install` scenario to cover this; all we need
to do is remove the explicit `--offline`.
This scenario will only pass for now if the build under test has that PR
and the live ISO has the osmet files (which right now is gated behind
`--osmet`).
Once that PR is in FCOS proper, we can make `--osmet` the default and
this test will then always pass.

kola/testiso: test that default path is fully offline

---

mantle/platform/cluster.go
mantle/platform/machine/unprivqemu/cluster.go

Similarly to https://github.com/coreos/coreos-assembler/pull/1324
I was reading a systemd journal from kola and the `ibm-p8-blah-blah-blah`
is just too long.  Set a hostname so we have less to read.

mantle/qemu: Set a short hostname

---

build.sh
mantle/cmd/kola/qemuexec.go
mantle/kola/tests/rhcos/luks.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/platform.go
mantle/platform/qemu.go
src/deps.txt
src/tang/tangdw

~~This PR builds on top of #1405~~ Closed in favor of this PR.
Two main things in this PR:
-  Enable forwarding of multiple host ports.  Host port forwarding allows the host machine to communicate to the guest machine through the local host address. It also allows the guest machine to communicate with the host machine through the gateway address. With two guest machines, we can bridge the two guests through the host machine with port forwarding.  For example, Host A can run a webserver on port 8080 and Host B can access Host A's webserver through its gateway (host machine) address http://10.0.2.2:8080.
- Changing the Tang test to use host port forwarding to run Tang inside a contain on a separate machine.  This eliminates the need to have Tang in coreos-assembler itself and fixes …

 kola/tests/luks: Use separate machine as Tang server

---

mantle/cmd/kola/devshell.go
mantle/platform/qemu.go

This came up in https://github.com/coreos/ignition-dracut/pull/146
and since then we've been doing more "ad hoc unit writing to virtio"
in mantle, but let's add a general API that streams the journal.
This is just better for what devshell wants - we can more precisely
watch for sshd starting.  And more code in e.g. `testiso.go` could
use it too which can come later.
The immediate motivation here is I may add another kola test
which could use this.

Add qemu API to stream journal, use it in devshell

---

src/cmd-buildextend-installer

Post-`fulliso` removal we can simplify this even more; all the
code is either `is_live = True` or it's `False`.

installer: More code cleanup

---

Dockerfile

@mike-nguyen @cgwalters FYI ```build.sh intall_tang``` invocation has been forgotten(I assume) in the Dockerfile. It breaks the cosa image build. It is surprising this didn't get picked up by the CI.
```b8c73e7d1e42c20ec6d28786b79352f91d2cdd346c2bf0a32917566012f7801b
STEP 10: RUN ./build.sh configure_user
++ pwd
+ srcdir=/root/containerbuild
+ '[' 1 -ne 0 ']'
+ configure_user
+ groupadd -g 78 -o -r kvm78
+ groupadd -g 124 -o -r kvm124
+ groupadd -g 232 -o -r kvm232
+ useradd builder --uid 1000 -G wheel,kvm,kvm78,kvm124,kvm232
+ echo '%wheel ALL=(ALL) NOPASSWD: ALL'
+ chmod 600 /etc/sudoers.d/wheel-nopasswd
f9cf02abe21562c9d79f59f27e4cdf03559a2aa94e2b1b5145689757db1c581c
STEP 11: RUN ./build.sh install_tang
++ pwd
+ srcdir=/root/containerbuild
+ '[' 1 -ne 0 ']'
+ install_tang
./build.sh: …
```

dockerfile: drop install_tang step, cleanup after PR#1407

---

mantle/kola/tests/rpmostree/deployments.go
mantle/kola/tests/upgrade/basic.go
mantle/kola/tests/util/rpmostree.go

On production streams, we should never have to force Zincati updates to
be on since that should already be the default. So remove that from the
Ignition config and dynamically check this when testing.
We check twice here because we need to account for the case where we're
first rebasing from e.g. `testing-devel` to `next` (where we do have to
force updates) and then an update on `next` itself (where we shouldn't
have to force updates).
This would have caught a regression in `next` where Zincati updates were
disabled: https://github.com/coreos/fedora-coreos-tracker/issues/473.

fcos.upgrade.basic: only force updates on if required

---

src/cmd-oscontainer
src/cmd-upload-oscontainer
src/coreos-assembler

This code lives today in the RHCOS pipeline (internal gitlab);
to be honest, I have no idea why only the "core" oscontainer bits
ended up in cosa upstream and the script lived downstream.
Let's fix that, moving all of the logic here.  Prep for
further work.

upload-oscontainer: New command

---

mantle/platform/machine/unprivqemu/machine.go
mantle/platform/qemu.go
mantle/platform/util.go

We are seeing the `rhcos.fips` test fail occasionally; the
console is the usual mess of corrupted/overwritten text.
We have the new virtio dump stuff, but until now we have
been discarding the output.  Change the test framework to
save it.
(And in the future we should parse it and try to find
actual error messages)

kola: Write ignition-virtio-dump.txt to test dir

---

.cci.jenkinsfile
src/cmd-buildextend-installer

This is the final step in ratcheting osmet into place for offline
installs by default. We drop the `--osmet` optional flag and now always
perform osmet packing when generating the live ISO.
(We could leave the switch around for a while just for compatibility,
but meh... the only other place this exists right now is the
coreos-installer CI, where we can trivially update it once this merges.)
Though because RHCOS doesn't yet support osmet, we add support for an
`osmet` knob in `image.yaml` which the RHCOS pipeline can use to turn it
off for now.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/352

buildextend-live: turn on osmet packing by default

---

src/cmd-supermin-shell
src/cmdlib.sh

While working on the oscontainer stuff in supermin I really
found myself needing a shell in the supermin environment.
Add a handy command for that.
In order to share code between the two paths, rework
the supermin argument handling to build up a single
array of extra arguments for qemu.
(Hopefully it won't be long before we replace this with
something saner like running a proto-CoreOS w/systemd
and using virtio-fs for the rootfs)

Add cosa supermin-shell

---

src/cmdlib.sh

Surprisingly, AFAICT there is nothing in libdnf today which
automatically lowers the cost of local repos vs remote ones. Let's give
it some help by adding a `cost=500` here (the default is 1000). This
will allow libsolv to always pick the RPM from the overrides repo, even
if the same NEVRA is available from a remote repo.

cmdlib: Lower cost of cosa RPM overrides repo

---

mantle/cosa/cosa_v1.go
mantle/cosa/schema_doc.go
src/schema/v1.json

This adds JSON schema definitions covering Vultr artifacts.
Ref: https://github.com/coreos/fedora-coreos-pipeline/pull/231

schema: add vultr artifacts

---

mantle/kola/tests/ignition/journaldEntry.go

This test will validate the changes in https://github.com/coreos/ignition/pull/958 to see if we're successfully sending the journald log entry for a `user-provided` config.

kola/tests/ignition: add test for checking journald logs

---

mantle/Makefile

One really terrible thing about Go is there's no standard build
system - contrast with Rust's cargo.  Here our hand-rolled
`Makefile` + shell script inhibits parallelism.
Rework the binaries to be separate jobs; this cuts a clean build
from 9s here to 5s.

mantle: Build binaries in parallel

---

mantle/kola/harness.go

We should have symmetrical support for metadata in internal/external
tests.

kola: Support distros and tags in external test metadata

---

mantle/cmd/kola/options.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/machine/unprivqemu/flight.go

Currently we default to 1024MiB for tests, but trying out this
patch with:
```
$ cosa kola run -- --parallel 8 --qemu-memory 512
```
The *only* test which fails is `rpmostree.install-uninstall`, probably
because the Fedora package metadata is enormous.
The main thing limiting test parallelism in our CI pipeline is RAM,
so if we can e.g. use 512 by default then that would nearly double test execution
speed.
This is prep for a future patch which will try to assign "instance type requests"
to tests, so both qemu and other platforms like AWS can use smaller instances.
For example in AWS we could use `t2.nano` for some tests instead of `m4.large`;
the pricing difference is large.  `t2.nano` in `us-east-2` is $0.0058, and
`m4.large` is $0.10, a savings of 95%.

kola: Add option to configure RAM

---

mantle/kola/tests/ignition/journaldEntry.go

[context] --- FAIL: coreos.ignition.journald-log (22.90s)
journaldEntry.go:44: Ignition didn't write 57124006b5c94805b77ce473e92a8aeb
/cc @ashcrow

Exclude rhcos distro from the journaldEntry test

---

src/cmd-runc

This stubs out launching a `bwrap` container targeting the commit.
Much faster than launching a VM for e.g. read-only queries of
filesystem state.  Potentially could be useful for testing in
the future.
(This is just a start, lots of potential improvements here)

runc: New command

---

src/cmd-buildinitramfs-fast

This is parallel to [build-fast](https://github.com/coreos/coreos-assembler/pull/1371)
which is about quickly iterating on userspace.
Here is the opposite - we just want to take our new code and
get it into the initramfs as fast as possible.  An example use
is demonstrated in the comment at the top of the file.
Here this takes about 5 seconds to run, which is fast enough
that at least I would probably stay at the terminal and not e.g.
context switch to code review or check Twitter or whatever.

buildinitramfs-fast: New command to iterate on initramfs quickly

---

src/cmd-buildextend-installer

VS Code is running pylint and warning about this.

buildextend-live: Squash unused variable

---

mantle/Makefile

This reverts commit afeb3c3f7dd80e5db4e55d1e8a213770f484d0ea - it
broke incremental builds.  I tried to fix it but just ran out
of Makefile-fu and want to work on more important things.

Revert "mantle: Build binaries in parallel"

---

src/cmd-buildextend-installer

For FSBCOS¹ a while ago I added the `fulliso` variant here
that was removed with the osmet rework.
`fulliso` did two things:
- Embedded the "metal" image inside the ISO
- Moved the rootfs squashfs out of the initramfs and into the ISO
The osmet work obsoleted the *first* bit in a much better way,
but the second problem still remains - the initramfs generated
for FSBCOS is just too large to boot.
But can have the best of both worlds; for the ISO case,
always put the rootfs on the ISO and not the initramfs, because
we still have the code to mount it in fedora-coreos-config.  It
makes us start the initramfs noticably faster too.
For the PXE case, we continue to embed the squashfs in the initramfs.
But for Silverblue I don't care about PXE (or if you want to do that,
PXE boot FCOS and use …

installer: Put rootfs on ISO

---

mantle/cmd/ore/gcloud/upload.go
src/cosalib/gcp.py

In RHCOS we upload images to GCP but no one ever uses them because
the openshift-installer just downloads the image from the URL in the
metadata and then recreates the image from scratch. Add the
--create-image boolean option (defaults to true) so we can specify
`--create-image=false` for the RHCOS pipeline and stop wasting time
and resources doing the image creation.

mantle/ore: glcoud: add --create-image option to upload.go

---

mantle/kola/harness.go

This is a regression from https://github.com/coreos/coreos-assembler/pull/1440
which is breaking the Ignition CI here
https://jenkins-coreos-ci.apps.ci.centos.org/job/github-ci/job/coreos/job/ignition/job/PR-968/35/console

kola: Avoid losing "external" tag

---

Makefile
mantle/cmd/kola/kola.go
mantle/kola/README-kola-ext.md
mantle/kola/harness.go

In continuing work on external tests, passing `-E` gets awkward
for a few reasons.  First, it ties the tests too heavily to the
source directory.
This supports a model like https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests
and Debian autopkg test etc. where the tests are installed.
This ensures a clean separation from the source directory,
which also helps us in e.g. supporting built binaries as is done
in https://github.com/ostreedev/ostree/pull/2048
For example, one thing we can do after this is extend the
coreos-assembler container with the results of `make install-tests`
from relevant git repositories (or make RPMs of them).

kola: Support loading tests from /usr/lib/coreos-assembler/tests/kola

---

mantle/platform/qemu.go

We want to keep it going as long as possible during shutdown or
if e.g. the system enters `emergency.target`.

qemu: IgnoreOnIsolate=true for journal streaming

---

src/create_disk.sh

Right now we allocate a random UUID on each build,
but everyone starting from a particular build will have
the same one...so they're not unique.
This will pair with a new version of
https://github.com/coreos/ignition-dracut/pull/183
so that we can regenerate them on firstboot and ensure
that they are actually unique (as much as possible)
across running systems.

create_disk: Add known UUIDs for /boot and /root

---

mantle/kola/harness.go
mantle/kola/register/register.go
mantle/platform/platform.go
mantle/platform/util.go

I saw this in the journal and wondered about it, it's a legacy
from CL which didn't have SELinux enabled by default.  FCOS/RHCOS
do, so let's stop pointlessly calling `setenforce 1`.

mantle: Remove setenforce 1 by default

---

mantle/cmd/ore/gcloud/upload.go

Previously we could miss detecting errors because err != nil was only
checked properly for the "already exists" error case. It then wasn't
checked again until after err was overwritten again by `err = ioutil.WriteFile`.
While going in to work on this I found the entire logic a bit confusing
so I refactored it to first identify if the image exists before ever
calling api.createImage.

mantle/ore: gcloud: fix error detection, add some error checking

---

mantle/cmd/ore/gcloud/upload.go
src/cosalib/gcp.py

In order to get a dashboard with metrics and such we need to attach
our images to "licenses" in GCP. These aren't software licenses but
rather how billing and such is done for images that cost money. Ours
don't cost anything so it's purely for counting purposes.

mantle/ore: gcloud: add ability to attach license to image

---

mantle/cmd/kola/options.go
mantle/platform/qemu.go

Adds UEFI support in to kola/qemu for aarch64. Change a bit kola options around uefi and swtpm(default to off). I hope I have not missed any places. Tested on x86_64, aarch64 and ppc64le.

Fixes related to kola/qemu on aarch64

---

mantle/cmd/ore/gcloud/image.go
mantle/cmd/ore/gcloud/promote-image.go
mantle/cmd/plume/release.go
mantle/platform/api/gcloud/api.go
mantle/platform/api/gcloud/image.go

In our build/release workflow for GCP we build and upload/create
a GCP image in the build pipeline. We deprecate the image (because
we haven't decided to release it yet) and then add it to the
corresponding image family for the stream it was built against.
The promote-image command will be used in the release pipeline to
undeprecate the image now that we have decided to release it. Since
we only want one image visible in an image family at any given time,
the promote-image command will then deprecate all other images in
the specified image family.

mantle/ore: gcloud: add promote-image command

---

src/cmdlib.sh

Prep for adding support for multiple variants/build types.

cmdlib: Don't hardcode manifest path in overrides

---

src/cmd-kola

This fixes it so that passing --platform= also works.

cmd-kola: also detect --platform=

---

src/cmd-oscontainer
src/cmd-upload-oscontainer
src/supermin-init-prelude.sh

We were passing `--workdir /host/container-work` to `oscontainer.py` in
the unprivileged case, but that path isn't actually mounted from the
host.
And actually, even if it were mounted, buildah wants to be able to
`chown` things in its container storage, which it won't be able to over
9p.
Instead, let's just point it at the cache qcow2 to do its work. That
way it can do whatever privileged operations it wants there, and plus we
get to cache the base `--from` image this way. Other temporary files are
nuked on exit, and otherwise, on the next run of `oscontainer.py` (in
practice, pipelines don't currently cache the qcow2 in between runs
anyway, but we should be nice to the unprivileged developer path).
(Again, we could also bump the supermin root instead, but I think as a
general pattern we …

cmd-oscontainer: put workdir in cache qcow2 in unprivileged path

---

mantle/cmd/kola/kola.go
mantle/kola/tests/rhcos/upgrade.go

I really think osmet is key for the RHCOS Live ISO experience and
we don't have that right now because of the LUKS container
thing.
I thought then about putting the LUKS header in `/boot`
and dropping the LUKS container by default
(that came up before) so we could also skip the dm-linear
thing.  That way it'd be the same as FCOS.
I started looking at that code but then I was reminded of a
moment of fear I had when something related came up last week -
we have absolutely no testing of upgrades around it, and that
is *highly* likely to break if we start trying to make any
fundamental changes.
This paves some of the infrastructure for a bit more "real" upgrade
testing where we boot the old OS with a target Ignition (in
this case the LUKS config), then reboot into the new OSTree
commit.  This …

kola: Add RHCOS LUKS upgrade test

---

mantle/cosa/cosa_v1.go
mantle/cosa/schema_doc.go
src/cosalib/gcp.py
src/schema/v1.json

When starting an image in GCP you need to specify the project associated
with the image. We should publish this information and also the image
family in case someone wants to just use the image family instead.

cosalib/gcp: Add more gcp information to meta.json

---

mantle/cmd/kola/testiso.go
mantle/platform/metal.go
mantle/platform/qemu.go
src/cmd-buildextend-installer

Few fixes to get the iso-install case working for ppc64le
- add volid to grub2-mkrescue command
- use -cdrom instead of ide-cd as ide-cd is not supported on ppc64le/s390x. It achieves the same effect as
what was done using the ide-cd device.
Closes: #1463

testiso: Fix iso-install and iso-live-login for ppc64le

---

src/cmdlib.sh

Nothing is using this right now.  Noticed this while looking
at variant builds.

cmdlib: Stop parsing rojig/license

---

mantle/cmd/kola/kola.go
mantle/fcos/metadata.go

Just a random side cleanup while looking at fetching builds
metadata for RHCOS upgrade testing.

mantle: Move the FCOS stream URL from kola into mantle

---

mantle/cmd/kola/kola.go
mantle/cosa/build.go

We want to run upgrade tests in the pipeline now.

kola: add gce support for --find-parent-image 

---

mantle/kola/harness.go

Fixes: https://github.com/coreos/coreos-assembler/issues/1464

kola: don't error if external tests directory doesn't exist

---

mantle/cmd/kola/kola.go
src/cmd-meta
src/cmd-virt-install
src/cmdlib.sh
src/cosalib/cmdlib.py

All of this is cruft now that lots of logic has moved into mantle.
We ended up with a pretty amazing chain where shell script would
load Python which in turn would exec kola.  No need for that
anymore.

Remove dead code relating to detecting Ignition version

---

src/cmd-buildextend-metal
src/create_disk.sh
src/gf-platformid
src/grub.cfg

This removes the hardcoded network configuration kargs from grub,
moving them into handling within initramfs by `dracut-cmdline.service`.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/460
Ref: https://github.com/coreos/fedora-coreos-config/pull/427

grub: de-hardcode firstboot network configuration

---

mantle/cmd/kola/options.go
mantle/kola/harness.go

The Docker Hub recently decided that us pulling the `nginx` image
over and over many times a day was abusive and started rate limiting
us.
For OSTree's test suite at least, there's no good reason for us
to run podman's tests at all.  Similarly for e.g. Ignition.
And just as a general rule I think it's useful to cleanly separate
tests that can be run fully offline from those that require
Internet access.

kola: Add --no-net flag

---

mantle/cmd/ore/gcloud/upload.go
mantle/platform/api/gcloud/image.go
src/cosalib/gcp.py

This will allow us to specify our normal fedora-coreos-$stream
license as well as the nested virtualization license:
https://compute.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx

mantle/ore: gcloud: support specifying multiple image licenses

---

src/cmd-supermin-shell

So I can more easily debug an attached disk image via e.g.:
```
$ cosa supermin-shell -drive if=virtio,read-only,file=(pwd)/builds/latest/x86_64/rhcos-46.82.202005261954-0-qemu.x86_64.qcow2,format=qcow2
```

supermin-shell: Support passing through qemu arguments

---

mantle/cmd/kola/testiso.go

ppc64le: pxe-install does not work: https://github.com/coreos/coreos-assembler/issues/1457
s390x:   pxe-install does not work because the bootimage used today is built from the rhcos 
kernel+initrd since s390x does not have a pre-built all in one image. For the pxe case, this 
image turns out to be bigger than the allowed tftp buffer. iso-install does not work because 
s390x uses an El Torito image

testiso: Prune test scenarios for ppc64le/s390x

---

src/create_disk.sh

Trying to get osmet to work with RHCOS, I kept being unable to
mount the rootfs and it turned out that while the code I'd added
to unpack the LUKS bits was working fine, mounting the rootfs
was failing because the block device was read-only, but XFS
wanted to replay the journal.
And for some reason I haven't traced through yet, this apparently
isn't affecting FCOS, but the unclean journal is breaking osmet
w/RHCOS.
This of course is the *second* time I've hit this problem of
"ext4 flushes the journal on umount, XFS doesn't" - see
also https://github.com/ostreedev/ostree/pull/1049/
Adding the necessary invocation of `xfs_freeze` ensures
that our firstboot has a clean XFS journal for `/` which
is just a good idea anyways.

create_disk: Ensure filesystem journal on rootfs is clean

---

src/create_disk.sh
src/gf-platformid

This somehow tries to forward firstboot kargs from a GRUB script
to a zipl configuration.
Ref: https://github.com/coreos/coreos-assembler/pull/1373#discussion_r430414499
/cc @jlebon

disk/s390x: inject firstboot kargs (ignition-network-kcmdline)

---

mantle/platform/qemu.go

I would like to propose to switch to virtio-blk for default ignition injection for non fw_cfg platforms. It should be more performant than injecting the ignition directly in to the VM image and IMHO it will be more resilient going forward. I'm currently not aware about any significant drawbacks compared to the current solution. I have tested this on x86_64, ppc64le, aarch64 and s390x with FCOS build/tests and have not observed any regressions.
CC'ing @Prashanth684
To add, I have recently started to see random kola test failures with FCOS(usually ~5 out of all kola tests) on non-fw_cfg platforms, caused by ignition failures. IIRC there has been reason why CoreOS nowadays preferred "non disk" based ignition injection, right? This seems to prevent these from happening. 
Log snippet of noted …

kola/qemu: Pass ignition via blk device on non-fw_cfg platforms by default

---

src/cmd-buildextend-installer
src/cmd-compress
src/cmd-sign
src/cmd-upload-oscontainer
src/cosalib/cmdlib.py
src/cosalib/digitalocean.py
src/cosalib/qemuvariants.py

With RHCOS we need to place our builds on their own mount point.
os.rename is used by shutil when on the same file system. This change
allows for some directories to be hosted on another mount point.

Use shutil.move over os.rename in python code.

---

src/osmet-pack

Prep for RHCOS osmet support.  This doesn't work on its own,
but gets us to the point where `coreos-installer osmet pack`
crashes trying to find the partition size.

osmet-pack: Mount RHCOS LUKS rootfs

---

src/cmd-buildextend-installer

Wanted to sanity-check this while debugging
https://github.com/coreos/fedora-coreos-tracker/issues/496.

buildextend-live: check exit code of cpio/find/gzip

---

src/cmd-buildextend-installer

Super subtle but evil regression from #1423. By switching to `find` to
feed filenames to `cpio`, we were passing it `.`. And `cpio` dutifully
made note of the permissions of `.`, which at the time it is run are
those of the temporary directory we allocated, which is naturally 0700.
This in turn breaks Ignition's `files` stage, which purposely runs
things like adding SSH keys as the target user, and thus it can't even
access the directories in `/` when doing the equivalent of `mkdir -p
/sysroot/var/home/core/.ssh/...`.
Instead, use `-mindepth 1` here so we always skip the root of the
temporary directory itself.
This resolves coreos/fedora-coreos-tracker#496
but not marking as `Closes:` because we should really add a basic live
PXE + SSH key test.

 buildextend-live: use `find . -mindepth 1` for cpio 

---

src/osmet-pack

When running osmet-pack in supermin:
- $TMPDIR needs to be an absolute path
- udev info may not have been populated
- blkid is failing

osmet-pack: patches for running in supermin

---

mantle/cmd/kola/testiso.go

After a bit of trial and error it looks like the minimum needed is 10G for
the legacy-install to run successfully. I will continue investigating this
through https://github.com/coreos/coreos-assembler/issues/1489, but looks like
with anything less than 10G, the qemu process gets killed abruptly during the
start of the reboot phase.

testiso: Tweak qemu memory for s390x

---

Dockerfile

Since the creation of the "buildroot" container derived from cosa
which we're using in CI, we really need cosa to somewhat match
the target system.
Also, we might as well do this on general principle.

Dockerfile: Switch to f32

---

.cci.jenkinsfile

Now that we've bumped cosa to f32, we want to make sure CI is also
targeting that. (Ideally, we'd just build from the Dockerfile and run
tests on the resulting image. That's something we can easily do with
Prow, though we should be able to do this via the OpenShift Jenkins
plugin too.)

ci: run on Fedora 32 image

---

src/deps-ppc64le.txt

grub2 in f32 is not pulling in grub2-tools-extra on ppc64le anymore.
Other architectures get it via their platform specific grub sub-packages.

deps: Add grub2-tools-extra on ppc64le for grub2-mkrescue

---

build.sh

The cryptsetup upstream maintainers seem to be telling
us to stop doing what we're doing.  Which, hopefully
we will soon!  But for now let's downgrade.
I thought about hardcoding the header, but I worry that
there might e.g. be differences across architectures.
Closes: https://github.com/coreos/coreos-assembler/issues/1496

build: Downgrade cryptsetup to 2.30-1.fc32

---

Dockerfile
build.sh

Just tagged coreos-installer-0.2.1-2.fc32 into f32-coreos-continuous to
unblock upgrade testing (we now sign `testing-devel` images with the f32
key, but the public key was added in 0.2.1 so it's failing to verify).
Let's blow the Quay.io cache to force it to re-install the RPMs.

Dockerfile: blow cache for new coreos-installer

---

mantle/platform/qemu.go

We see this race occasionally in builds/CI.  I didn't
reproduce locally, but this should fix it.

qemu: Wait until swtpm starts up

---

.cci.jenkinsfile
mantle/cmd/kola/testiso.go
src/cmd-buildextend-installer
src/osmet-pack

Start building and shipping osmet files for metal4k images so that those
users can also do offline installs.
This completes the osmet work.

buildextend-installer: add metal4k osmet support

---

mantle/kola/README-kola-ext.md
mantle/kola/harness.go

Having a separate JSON file for the metadata is annoying, let's
support it inline.
(This is of course somewhat tricky for compiled binaries to support,
but we'll deal with that when we get there)

kola: Support inline metadata JSON

---

mantle/cosa/cosa_v1.go
mantle/cosa/schema_doc.go
src/cmd-build
src/schema/v1.json

Right now, the FCOS download page is using the pkgdiff from the
`meta.json` files to print the changelog. However, this diff is against
the previous build, not the previous release. This distinction is
important since e.g. we might do multiple `testing` builds, but only
release one.
Ideally, the JS client code would perform the diff, though parsing and
comparing RPM versions and getting this correct is no fun. Let's just
also output in the metadata the diff against the parent if it's
provided.

cmd-build: add --parent-build to replace --parent

---

mantle/cmd/kola/devshell.go
mantle/cmd/kola/testiso.go
mantle/util/common.go

Fixes https://github.com/coreos/fedora-coreos-tracker/issues/515 
This fix will add a test in CI for live ISO/PXE artifacts to validate if an ssh key is setting up appropriately for the `core` user when provided via ignition config.

testiso: add ssh key info in ignition config for testing live ISO/PXE artifacts

---

mantle/cmd/kolet/kolet.go
mantle/kola/README-kola-ext.md
mantle/vendor/github.com/coreos/go-systemd/v22/journal/journal.go
mantle/vendor/modules.txt

The "assume SIGTERM means reboot" was pointed out in code
review as a bit too implicit, but we didn't change anything.
This adds a "stamp file" approach to make things more
explicit; once this lands I'll adapt ostree's tests.
Prep for adding another `/run/kola-force-powercycle` so we
can easily test force poweroffs in ostree's CI.
Also, the log messages here were being swallowed because
`kolet` is run over ssh and we were discarding stdout.  Fix
that by explicitly logging to the journal.

 kola: Support explicit /run/kola-reboot stamp file

---

mantle/cmd/kola/testiso.go

We're hitting a `testiso` timeout right now in the FCOS pipeline and
it has to wait 15m each time before erroring and publishing artifacts.
Given that all our install tests transfer files within localhost to the
QEMU instance (or in the case of the offline tests, don't transfer files
at all), we really expect it to take much less time. There's still disk
I/O of course, but even so 10m should be enough.
We can revisit if we ever add `testiso` support for e.g. Packet or some
KNI setups where we're actually testing against real bare metal.

testiso: lower install timeout to 10m

---

mantle/cmd/kola/testiso.go

The argument to kola is `--build`, not `--cosa-build`.

mantle/kola: correct error message from kola testiso

---

mantle/platform/metal.go

In trying to debug why the pipeline metal4k offline install tests were
failing, neither the console nor the journal logs were very useful. The
first because ISO installs don't output to serial by default (and we
currently don't have an easy way to override that), the second because
we were redirecting `coreos-installer` to the console, which we can't
capture.
Drop the `StandardOutput`/`StandardError` overrides so that output goes
to the journal, where we can collect it over virtio.

metal: don't redirect coreos-installer output to console

---

src/osmet-pack

We've had udev running inside `supermin-init-prelude.sh` for a
while.  I am seeing the udev calls hanging sometimes (often)
for me locally.
Removing them seems to make the process more reliable for me,
and is less code!

osmet-pack: Remove unnecessary duplicate udev invocations

---

mantle/cmd/kola/options.go
mantle/cmd/kola/testiso.go

The pipeline for ppc64le fails on the metal4k tests as UEFI is not supported.
Change to use UEFI only for aarch64 and x86 metal 4k test.For s390x, this test is
skipped but in the pipeline it fails because there are no scenarios to test.
Change that message to just a print.
Thanks @cgwalters for the suggestion to fix the test for ppc64le!

kola: switch qemuoptions to bios for all arches except aarch64 and x86 for metal 4k

---

src/cmd-build

```
commit 3fb5f99687ddd0981d2feb2333d01ef14a730265
Date:   Thu Jun 11 09:16:43 2020 -0400
cmd-build: Only keep last three commits in tmp/repo
The default otherwise is to keep all the commits, even if the associated
builds were long gone.
commit ad2b096715a0ad8bc3189f25efb0f43e5a3cb662
Date:   Thu Jun 11 09:10:51 2020 -0400
cmd-build: Mark parent commit as partial
Otherwise, commands like `ostree prune` will think the full commit is
present and try to traverse it.
I hadn't hit this when originally adding `--parent-build` because I did
have the full commits available in my `tmp/repo`. But the pipeline OTOH
always starts from scratch.
```

Mark parent commit as partial and prune tmp/repo more aggressively

---

mantle/README.md
mantle/cmd/kola/options.go
mantle/kola/harness.go
mantle/kola/register/register.go
mantle/kola/tests/misc/files.go
src/cmd-kola

The use of the term "blacklist" to describe things we want to exclude
is archaic and not representative of the social values we want to
support in this project.  Similarly, "whitelist" as a term for
inclusion has the same problems.
This changes the code to use a format of `denylist` and `allowlist`
across the project.  It does not attempt to change any of the
vendored modules.

Use better terms for exclusion/inclusion

---

src/cmd-upload-oscontainer

At one point I was trying to drag the oscontainer code
out of the RHCOS pipeline, but stalled on that.
While I was doing that, we added `--display-name` logic
in the downstream version.
When I went to switch everything to upstream, that
change got lost.
The previous downstream change hardcoded passing
`--display-name=<osname>` in the pipeline.
Let's do better and automatically extract `os-release`
and use it.

upload-oscontainer: Automatically inject --display-name

---

src/cmd-upload-oscontainer

At one point I was trying to drag the oscontainer code
out of the RHCOS pipeline, but stalled on that.
While I was doing that, we added `--display-name` logic
in the downstream version.
When I went to switch everything to upstream, that
change got lost.
The previous downstream change hardcoded passing
`--display-name=<osname>` in the pipeline.
Let's do better and automatically extract `os-release`
and use it.
(cherry picked from commit 53fd6a7edd20fc796e76f38f6c1a492f6282e88a)

[4.5] upload-oscontainer: Automatically inject --display-name

---

src/cmd-upload-oscontainer

At one point I was trying to drag the oscontainer code
out of the RHCOS pipeline, but stalled on that.
While I was doing that, we added `--display-name` logic
in the downstream version.
When I went to switch everything to upstream, that
change got lost.
The previous downstream change hardcoded passing
`--display-name=<osname>` in the pipeline.
Let's do better and automatically extract `os-release`
and use it.
(cherry picked from commit 53fd6a7edd20fc796e76f38f6c1a492f6282e88a)

[4.4] upload-oscontainer: Automatically inject --display-name

---

mantle/cmd/kola/testiso.go

In the legacy path, we never boot into a live environment, so the only
signal we should expect is the completion signal from the installed
system.
Regression from #1524.

testiso: fix legacy-install scenario

---

src/cmd-koji-upload

Koji/Brew forces us to recompress files which uses a lot of
space and is exacerbating disk space issues with the RHCOS pipeline.
We want a broader fix where we generally write directly into `builds/`
for images but for now, this quick hack should get us using
a larger PVC for the RHCOS pipeline.

koji-upload: Use builds/ for tempdir

---

mantle/platform/qemu.go

- POWER8 with RHEL7 does not support vsmt change causing the error:
"On PPC, a VM with 1 threads/core on a host with 8 threads/core requires the use of VSMT mode 1. This KVM seems to be too old to support VSMT."
On POWER8 the vsmt default is 8, when on POWER9 it is 1.
This patch change the vsmt=8 in order to restore the default value for
POWER8. It is also compatible with POWER9

mantle: change vsmt default value for Power

---

src/cmd-upload-oscontainer

The previous change to automatically add the display name
appeared to work when I tested locally, and I thought the
quotes in the output of `podman inspect` were added by podman
itself.
But since the file is in "shell syntax", it can have shell-style
quotes, so let's use the shell to parse it.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1847886

upload-oscontainer: Correctly strip quotes from name

---

.cci.jenkinsfile
ci/run-kola-self-tests
mantle/cmd/kolet/kolet.go
mantle/kola/harness.go
tests/kola-ci-self/tests/kola/autopkgtest-reboot

As I was working on extending some of ostree's destructive
test suite to do reboots:
https://github.com/ostreedev/ostree/pull/2127
I realized that the Debian autopkgtest API for rebooting is
better, because it allows *saving state external to the host*.
Rather than having the test count boots as ostree is doing
today, the "mark" allows us to more reliably dispatch.
And further, becase we don't rely on writing anything to disk
on the target, we can add clean support for "forced reboots"
that might kill the OS before we write to persistent storage there.
The "between reboot" state lives in the test runner's memory instead.
We retain support for the previous (two!) reboot APIs here for now.
I tested this with basically the example script
from the Debian autopkgtest specification:
```
set …
```

kola: Support the Debian autopkgtest reboot API

---

build.sh

The cryptsetup upstream maintainers seem to be telling
us to stop doing what we're doing.  Which, hopefully
we will soon!  But for now let's downgrade.
I thought about hardcoding the header, but I worry that
there might e.g. be differences across architectures.
Closes: https://github.com/coreos/coreos-assembler/issues/1496
Adjusted backport of #1497 for Fedora 31 - the newer cryptsetup does
cause issues with builds on ppc64le and s390x. 2.2.1-1 is the version
that is available to downgrade to.

build: Downgrade cryptsetup to 2.2.1-1.fc31

---

src/cmd-upload-oscontainer

The previous change to automatically add the display name
appeared to work when I tested locally, and I thought the
quotes in the output of `podman inspect` were added by podman
itself.
But since the file is in "shell syntax", it can have shell-style
quotes, so let's use the shell to parse it.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1847886
(cherry picked from commit c7a16b5634ed6a2e2d47ac9da410ca4b9f9ec97c)

[4.5] upload-oscontainer: Correctly strip quotes from name

---

src/cmd-upload-oscontainer

The previous change to automatically add the display name
appeared to work when I tested locally, and I thought the
quotes in the output of `podman inspect` were added by podman
itself.
But since the file is in "shell syntax", it can have shell-style
quotes, so let's use the shell to parse it.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1847886
(cherry picked from commit c7a16b5634ed6a2e2d47ac9da410ca4b9f9ec97c)

[4.4] upload-oscontainer: Correctly strip quotes from name

---

README.md

This came from https://github.com/coreos/coreos-assembler/pull/282
which actually we don't strictly need for builds anymore because
we rely on 9p.
But some people may want it for e.g. kola.  It is tempting to
make `--net=host` the default particularly because SLIRP is a
performance hit but let's just document this for now.

README.md: Add a note about `--net=host` here.

---

src/coreos-assembler

Kelvin is seeing `umount: /sys/fs/selinux: not mounted` when
trying to use cosa; I didn't try to debug it but let's replace
this bit with the code that coretoolbox has been using, which
should be more robust because it doesn't depend on the underlying
mount hierarchy.

entrypoint: Use mount --bind for /sys/fs/selinux

---

build.sh

During image generation 'grubby' package is getting uninstalled,
but this in turn also removes other 'dependent' packages.
Signed-off-by: Nikita Dubrovskii <nikita@linux.ibm.com>

build.sh: preserve s390-base.rpm package from uninstalling

---

mantle/cmd/kola/qemuexec.go

Add a new option (-D/--aditional-disks) that will provide a given number
of additional 1G disks.

kola/qemuexec: add option to create additional disks

---

mantle/cmd/kolet/kolet.go
mantle/kola/harness.go

This has broken a few recent kola runs, e.g.
https://jenkins-coreos-ci.apps.ci.centos.org/blue/organizations/jenkins/github-ci%2Fostreedev%2Fostree/detail/PR-2137/1/pipeline/202
Bug introduced in previous reboot handling.  The code is
a mess here (reboots are hard) and I hope to clean this up
after we can remove the previous reboot APIs.

kola: Remove stray stdout logging

---

src/cmd-oc-adm-release
src/coreos-assembler

This is specific to OpenShift, but should be extensible for OKD as well.
The intent of this script is to publish oscontent against a current
release for testing with updated content.
When running this in the context of a build, the corresponding CI
command might be:
```
cosa release-ocp \
--to-url horcux.dev/rhcos/rhcos-ocp-test
--authfile auth.json \
--fetch-bin
```

cmd-oc-adm-release: new tool for release origin/ocp payloads

---

mantle/kola/tests/fips/fips.go
mantle/kola/tests/rhcos/luks.go
mantle/kola/tests/rhcos/sssd.go
mantle/kola/tests/rhcos/upgrade.go

Split from https://github.com/coreos/coreos-assembler/pull/1532 that will keep only the revert that will be merged only when we are ready to commit to Ignition spec 3 in RHCOS.
This should be ready to merge.

kola: Add Ignition spec 3 configs for RHCOS

---

Dockerfile

Added the new rpm-ostree to f32-coreos-continuous to unblock
https://github.com/coreos/fedora-coreos-tracker/issues/540.

Dockerfile: tickle Quay for rebuild

---

src/cmd-sign

Now that RoboSignatory knows to auto-select the right GPG key to use for
signing, we can be more strict here when verifying signatures and use
the specific key matching the release version.
See also: https://github.com/coreos/fedora-coreos-tracker/issues/296

cmd-sign: verify signature using specific GPG key

---

mantle/kola/tests/crio/crio.go

Correctly trim only the ".0/16" suffix from CRI-O subnet.
Fixes: 59e4449 kola: tests/crio: Update for 1.18 release compatibility

kola: tests/crio: Fixup 1.18 test update

---

mantle/platforms.md
src/cmd-artifact-disk
src/cmd-buildextend-azurestack
src/cosalib/qemuvariants.py
src/schema/v1.json

- Use the same disk format as Azure
- Change the platform id
- Be more like OpenStack in just generating a disk image, not
wrapping ore, because users need to upload this on premise
Also fix a bug in the CLI wrapper which was erroneously matching
`azure` first.

Add initial azurestack platform

---

mantle/cmd/kolet/kolet.go
mantle/kola/harness.go
mantle/platform/util.go
tests/kola-ci-self/tests/kola/autopkgtest-reboot

Builds on top of https://github.com/coreos/coreos-assembler/pull/1572
I want to add testing of forced poweroff (i.e. `reboot -ff`)
into OSTree's test suite so we can reliably verify that
it lives up to what it claims on the tin.
The autopkgtest already has a "prepare" API which is exactly
what we want here.  Implementing this though is somewhat
tricky because we need to synchronously get the mark (i.e. state)
out to the harness.  I added a big comment about this.

Reboot force

---

mantle/kola/harness.go
mantle/kola/tests/podman/podman.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/platform.go

In https://github.com/coreos/coreos-assembler/pull/1478 we
discussed Internet access and tests, adding a flag to disable
tests which are flagged as requiring it.
This flips things around and *enforces* no Internet access for
qemu tests by default unless the test is flagged as requiring
it.
Unsurprisingly it turns out several tests are missing the flag.
(And we also don't presently have a way to flag external tests
as requiring Internet, which is another issue)

tests: Enforce no Internet in qemu unless flagged

---

src/cosalib/aws.py

We want our release jobs to be idempotent so that we can keep re-running
it if there's a flake. Hit this bit which currently breaks that model.
This matches the behaviour of `cosa aliyun-replicate`.

aws-replicate: exit 0 if no new regions detected

---

mantle/cosa/cosa_v1.go
mantle/cosa/schema_doc.go
src/schema/v1.json

This adds a new optional schema element for 'payload-release' for use with OCP/OKD releases. On the RHCOS side, the targeted intention is to add the location of the OCP testing payload for the machine-os-content.
It also:
- fixes a bug in the schema definition of the pkgdiffs
- updates the mantle cosa structs (includes the AzureStack recent changes)

schema update: add new field for 'payload-releases'

---

mantle/kola/tests/fips/fips.go

Some parts of the extended FIPS test are QEMU specific thus avoid running them on all the other platforms.
This temporarily duplicates tests until we have FIPS support directly in Ignition.

kola: test/fips: Split test in two to properly support all platforms

---

mantle/cmd/kola/spawn.go
mantle/kola/README-kola-ext.md
mantle/kola/harness.go
mantle/kola/register/register.go
mantle/kola/tests/ignition/mount.go
mantle/kola/tests/misc/raid.go
mantle/kola/tests/rhcos/luks.go
mantle/platform/machine/aws/cluster.go
mantle/platform/machine/azure/cluster.go
mantle/platform/machine/do/cluster.go
mantle/platform/machine/esx/cluster.go
mantle/platform/machine/gcloud/cluster.go
mantle/platform/machine/openstack/cluster.go
mantle/platform/machine/packet/cluster.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/platform.go
mantle/platform/qemu.go

Add the ability to specify additional disks in `kola.json` for use by
external tests. This will be useful for testing the new rootfs
reprovisioning work.
For now, this only supports the qemu platform.
Closes: #1565

kola: add additionalDisks support in kola.json

---

src/cmdlib.sh

Be nice to users who add SRPMs in the `overrides/rpm` repo (since some
tools will download them too), and just ignore them.
Closes: #1577

cmdlib: ignore SRPMs when finding override packages

---

mantle/kola/tests/rhcos/luks.go

The Tang and SSS tests require internet to pull the Tang container.

kola/tests/rhcos/luks: add NeedsInternet tags to Tang and SSS

---

ci/run-kola-self-tests
mantle/cmd/kolet/kolet.go
mantle/kola/harness.go

Followup to review comments in
#1575
And also for some reason I didn't fully debug, the reboot
acknowlegement was failing on RHCOS, so let's switch to
using FIFOs for IPC instead of doing "IPC via systemd DBus unit files".

kola: Avoid "sleep infinity" unit

---

mantle/cmd/kola/options.go
mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/testiso.go
mantle/kola/harness.go
mantle/platform/machine/qemuiso/cluster.go
mantle/platform/machine/qemuiso/flight.go
mantle/platform/machine/qemuiso/machine.go
mantle/platform/metal.go
mantle/platform/qemu.go

Lower the bits to do "inject Ignition via coreos-installer embed iso"
into the qemu layer.  Copy the "qemu-unpriv" platform code into a
"qemu-iso" platform (both are mostly thin wrappers around `qemu.go`).
This makes it completely trivial to get a `ssh` shell in an ISO:
`cosa run -p qemu-iso --memory 8192`
And even better means we can start running a lot of the kola tests
directly against the ISO (though not everything will work, e.g.
tests that reboot can't persist state).   I did verify this works:
`kola run -p qemu-iso --qemu-memory 8192 basic`

Add a qemu-iso platform

---

mantle/kola/tests/ignition/qemufailure.go

Now that https://github.com/coreos/ignition-dracut/pull/146 PR has merged, we can leverage this test.

mantle/kola/tests/ignition: don't skip ignitionFailure test

---

mantle/platform/api/gcloud/compute.go

Addresses https://github.com/coreos/coreos-assembler/issues/1587, where
request for new GCE instances fails due to the requested disk size being
smaller than the RHCOS disk size of 16GB.

platform/api/gcloud: Bump requested disk size to 16GB

---

mantle/cmd/kola/kola.go
mantle/cmd/kola/options.go

```
commit eca576068f79b8df16715f5651a0310b33b8cbe8
Date:   Mon Jul 13 16:24:49 2020 -0400
kola: resolve directory when using `-E .`
Otherwise the generated tests will have funny names like `ext...foobar`.
commit 0ab5a4a45898d2d34bceedba754d5dfde715e17f
Date:   Mon Jul 13 16:24:50 2020 -0400
kola: add ext tests in current dir if no -E given
E.g. when hacking on Ignition tests, I want to be able to just do
`kola run --workdir /srv/fcos ext.ignition.foobar` from the Ignition git
repo.
```
Found these useful when hacking on #1589 for tests for https://github.com/coreos/fedora-coreos-config/pull/503.

kola: tweaks around handling of external tests

---

mantle/cmd/kola/spawn.go

Regression from #1514. `kola spawn` is for users, so just always enable
Internet access there. In the future we could have `--no-net` control
this knob too if the need arises.
This is needed by the rpm-ostree CI which uses `kola` to bring up nodes.

kola/spawn: enable internet access

---

mantle/kola/tests/crio/crio.go
mantle/kola/tests/misc/network.go
mantle/kola/tests/podman/podman.go

Update kola tests to use ss instead of the deprecated netstat,
and adjust tests to expect ss output.
This should fix https://github.com/coreos/fedora-coreos-tracker/issues/552.
The following tests have been updated:
fcos.network.listeners
crio.network
podman.network-multi (currently disabled)

kola: update tests to use ss instead of netstat

---

Dockerfile.buildroot

Anyone using this image as a pet container for building lots of things
really wants this.
Related: https://github.com/coreos/coreos-ci-lib/pull/33

Dockerfile.buildroot: use dumb-init

---

mantle/kola/README-kola-ext.md

Since it turns out I broke the ostree tests after
https://github.com/coreos/coreos-assembler/pull/1514

README-kola-ext.md: Document `needs-internet` and tags

---

mantle/kola/tests/misc/network.go

Remove extraneous pid information in fcos.network.listeners test's
error message.

kola: tests/misc/network: Update error message

---

mantle/kola/tests/misc/network.go

In [1] we started using NM in the initrd and removed dhclient (dhcp-client
rpm). In f741af4 this test was switched to look for NetworkManager listening
on port 68 instead of dhclient. With the switch to F32 NetworkManager no longer
listens on port 68 (not sure why). We can remove NM from the list of listeners.
[1] https://github.com/coreos/fedora-coreos-config/commit/90ce41141f9349432a0621c6f0e00748e20c840f
Notes from my investigation:
31.20200310.2.0
- last testing release with dhclient (dhcp-client rpm)
- ami-0baff6eba668fe0ae
```
Netid   State    Recv-Q   Send-Q     Local Address:Port     Peer Address:Port   Process
udp     UNCONN   0        0                0.0.0.0:68            0.0.0.0:*       users:((\"dhclient\",pid=1021,fd=6))
udp     UNCONN   0        0              127.0.0.1:323 …
```

mantle: kola: Remove NetworkManager from list in fcos.network.listeners

---

mantle/kola/tests/misc/network.go

This test was disabled in 67b9c0d. I just tested and the test runs
and passes on the qemu-unpriv platform. I don't know of a good reason
to have it disabled so let's try enabling it.

mantle: kola: Enable fcos.network.listeners test on qemu-unpriv platform

---

mantle/cmd/kolet/kolet.go
mantle/kola/harness.go
tests/kola-ci-self/tests/kola/autopkgtest-reboot

I was working again on OSTree's destructive tests and I tried
switching to serializing JSON via Rust's serde into
the `AUTOPKGTEST_REBOOT_MARK` field so I could more easily
pass data between reboots.
Well, that turned out to be a mess; of course we had multiple
levels of quoting bugs in multiple places.  I initially tried just shell quoting
it - it took me a little while to realize that we *also* need
to quote it for systemd to parse from the environment file.
Rather than dealing with quoting in ssh I ended up just base64
encoding because hey, it works.

kola: Handle quotes in autopkgtest reboot mark

---

mantle/cmd/ore/gcloud/upload.go
mantle/platform/api/gcloud/image.go
src/cosalib/gcp.py

This adds support for marking images with public ACLs when they are
created. Doing this isn't necessary for projects that have been marked
as public on the GCP backend by GCP engineers (like the `fedora-coreos-cloud`
project), but is for other projects to share images publicly.
Fixes https://github.com/coreos/coreos-assembler/issues/1561

mantle: gcp: add ability to make gcp images public

---

mantle/sdk/distros.go

RHCOS is moving to ignition spec v3.
This reverts commit f3b34bc679220ba9d48529bf1f6070816053d10e.
Do not merge until we have completed all the specv3 changes.

Revert "sdk/distros: update TargetIgnitionVersionFromName for RHCOS 4.6"

---

.cci.jenkinsfile
src/cmd-buildextend-installer

Split refactoring patches out of https://github.com/coreos/coreos-assembler/pull/1608 and add a couple more cleanups.

buildextend-installer: refactoring for separate rootfs image

---

mantle/kola/harness.go
mantle/kola/register/register.go
mantle/kola/tests/coretest/core.go

Support excluding distributions in native tests run by kolet. 
Add native function tests to basic to verify that `rhcos-growpart.service` and `ignition-ostree-growfs.service` have run successfully.
Check that the root filesystem is at least 15 GB in RHCOS and 7 GB in FCOS.

kola: Validate growpart

---

src/cmd-buildextend-installer
src/osmet-pack

If `--fast` is specified, do two things:
- Use LZ4 compression for the squashfs, producing a substantially larger image.  This only works on FCOS, as RHCOS doesn't have kernel support.  On my machine this reduces the squashfs build time from 4m10s to 15s.
- Pass `--fast` to `coreos-installer osmet pack` (requires https://github.com/coreos/coreos-installer/pull/307).  On my machine this takes another 58s off the build time.

buildextend-installer: add --fast option

---

mantle/cmd/kola/kola.go
mantle/kola/harness.go

For example in RHCOS we are seeing `fips.enable.partitions` apparently
race, so with this I can now do:
`kola run --multiply 8 fips.enable.partitions --parallel 8`
to more easily provoke races, while still having all logs in one
place and reusing any future logic we add around managing qemu
concurrency.

kola: Add support for --multiply N to run a test multiple times

---

mantle/cmd/kola/devshell.go
mantle/cmd/kola/kola.go
mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/testiso.go
mantle/kola/tests/ignition/qemufailure.go
mantle/platform/machine/qemuiso/cluster.go
mantle/platform/machine/qemuiso/machine.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/machine/unprivqemu/machine.go
mantle/platform/metal.go
mantle/platform/qemu.go
mantle/system/exec/exec.go

If we fill up tmpfs, things stop working.  Based on what I've seen locally, I suspect this is the cause of some of the testiso timeouts in CI.

mantle: fix tempdir leaks and move large tempdirs to /var/tmp

---

mantle/cmd/kola/options.go

`cosa run -p qemu-iso --qemu-iso fedora-coreos-32.20200715.2.2-live.x86_64.iso`
has at least one too many `.iso`.

kola: Make --qemu-iso automatically imply -p qemu-iso

---

mantle/platform/metal.go

The new installer can handle uncompressed images just fine.

mantle/platform/metal: only compress metal image for legacy-install test

---

mantle/platform/qemu.go

All of our uses of qemu are ephemeral, so let's speed
things up.
See also a1c6bc9bca1bed7ee11fbf6f4ce6b34da087d361

qemu: Default to cache=unsafe for disks

---

mantle/cmd/kola/options.go

This fixes a regression from 51d94a3 where the kolaPlatform would
get set to `qemu-unpriv` even if the user had passed --platform gce
or any other valid value. I noticed that the GCE and AWS tests started
failing with a weird error like:
```
--- FAIL: podman.network-single (0.01s)
harness.go:900: Cluster failed starting machines: lstat
/home/jenkins/workspace/fedora-coreos/fedora-coreos-fedora-coreos-pipeline-kola-aws/builds/32.20200725.20.0/x86_64/fedora-coreos-32.20200725.20.0-qemu.x86_64.qcow2.xz:
no such file or directory
```
It's because they were inappropriately trying to execute qemu tests. The
error message we got is because the qemu artifact didn't exist in the local
test environment because we don't sync them down (they're not necessary).

mantle: kola: stop ignoring user provided --platform option

---

fixtures/fcos.json
mantle/cmd/kola/testiso.go
mantle/cosa/cosa_v1.go
mantle/cosa/schema_doc.go
mantle/fcos/metadata.go
mantle/platform/metal.go
src/cmd-buildextend-installer
src/cmd-compress
src/schema/v1.json

For live images, add PXE `rootfs` image containing osmet files and the root squashfs.  This can be appended as a second initrd or fetched by the initramfs at runtime.  Write the build ID into flag files in the initramfs and rootfs so the initramfs can confirm that both came from the same build.  Store the hash of the rootfs into the PXE initramfs so rootfs integrity can be verified after a runtime fetch.
If `--legacy-pxe` is specified, continue as we were before, but generate a rootfs image containing only a flag file.  This allows a transition period where the initramfs can check for the flag file and warn that the rootfs hasn't been provided.
For https://github.com/coreos/fedora-coreos-tracker/issues/390.

buildextend-installer: move PXE squashfs and osmet to separate initrd

---

mantle/kola/tests/rhcos/luks.go

There have been intermittent failures in the Tang/SSS tests starting
the Tang container.  The error message is a bit cryptic saying the
Process exited with status 125.  This commit will print out stderr
to facilitate debugging.  The error is suspected to be caused by an
issue pulling from docker.io.  Lets switch to quay.io to see if that
alieviates the failures, if not stderr should give more clues on
the failures.

kola/rhcos/luks: pull tang container from quay.io

---

mantle/cmd/kola/testiso.go

coreos/fedora-coreos-config#528 has landed.
/hold for RHCOS submodule update

mantle/testiso: test PXE with coreos.live.rootfs_url by default

---

src/cmd-fetch
src/cmd-prune

Added "cosa prune --pkgcache" command to prune refs packages from the pkgcache, which are not present in the builds and modified over 30 days.
"cosa fetch" runs "cosa prune --pkgcache" if "cache/pkgcache" is more than 5GB.
This fixes https://github.com/coreos/coreos-assembler/issues/1495.

prune --pkgcache: Prune refs packages from the pkgcache

---

src/cosalib/gcp.py

Per comment from a GCP engineer, this is basically saying our
OS supports KVM, which it does.
We're enabling this only in the FCOS pipeline right now but
it makes sense to enable for RHCOS too.
See https://github.com/openshift/installer/pull/3808

gcp: Enable nested virt by default

---

src/oscontainer.py

This speeds up the oscontainer build for more noticeably; there's
no reason to fsync here because the container build process
should handle it.

oscontainer: Disable fsync when pulling

---

src/oscontainer.py

I regularly develop on coreos-assembler outside of a container,
this key needs to be optional.
Regression from 237b6d7e1a23fc98e89aa708b0dd7ba8f5c178f6
See also e.g. ded997b8634b0026899306d86d7ce688d0934bee

oscontainer: Skip cosa commit if not present

---

src/gf-mksquashfs

The two features currently overlap and the new ostree
breaks the Live ISO.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/589

Remove sysroot=readonly on the Live media

---

mantle/kola/tests/ignition/symlink.go

this adds kola test to write absolute symlinks via Ignition.
Fixes https://github.com/coreos/coreos-assembler/issues/1632

mantle/kola: add kola test for writing absolute symlinks via Ignition

---

src/cmd-prune

I don't recall exactly how I hit this, but basically `cosa fetch`
was failing for me because I had no builds, and we were trying
to look at `builds/latest`.
Fix the prune code here to handle the case where there are no
builds.

prune: Handle no-builds case when cleaning pkgcache

---

mantle/kola/tests/ignition/symlink.go

this changes kola test of writing absolute symlinks via Ignition to use
`readlink /etc/localtime`.

mantle/kola: improve ignition symlink test

---

mantle/platform/qemu.go

Now that we support injecting kernel arguments in the ISO, let's make
use of it by default when booting a live ISO to inject the appropriate
serial console karg. This is more convenient for manual testing (because
one no longer has to interrupt the boot process to type it in), but also
has the major advantage of ISO tests now being able to capture console
output.
In the future, we can also hook up the `--kargs` option to this.

qemu: Automatically inject serial console karg into ISO

---

src/cmd-buildextend-installer

@dustymabe discovered that the kernel does allow uncompressed appended initrds; it just needs them to start on a 4-byte boundary.  This allows us to refactor the live ISO as a wrapper around bit-for-bit copies of the live PXE artifacts.  That's useful because Fedora and RHEL users may expect to be able to copy PXE artifacts out of the ISO image.
Switch to an uncompressed rootfs image; pad the initramfs image appropriately so the two can still be concatenated.  Move the ISO Ignition padding area to a separate file so the PXE initramfs artifact doesn't need to include padding.  Move the kernel and initramfs to the paths within the ISO that Fedora and RHEL conventionally use, and put the rootfs image next to them.  Put the rootfs stream hash in the initrd, and the osmet files in the rootfs, …

buildextend-installer: ship live PXE artifacts inside live ISO

---

src/cmd-buildextend-installer

`coreos-installer download` refuses to download any artifact smaller than 1 MiB.  To avoid breaking deployed versions of coreos-installer, pad the legacy PXE rootfs to 1 MiB.  The kernel is fine with padding, bsdtar is fine with it, and the artifact will only exist for two months anyway.
Also stop compressing the legacy rootfs.  The compression is technically a bug, though it turns out not to matter.

buildextend-installer: pad legacy PXE rootfs to 1 MiB

---

src/cmd-buildextend-installer

`coreos-installer download` refuses to download any artifact smaller than 1 MiB.  To avoid breaking deployed versions of coreos-installer, pad the legacy PXE rootfs to 1 MiB.  The kernel is fine with padding, gunzip is fine with it, and the artifact will only exist for two months anyway.

[fcos-stable] buildextend-installer: pad PXE rootfs to 1 MiB

---

mantle/platform/qemu.go

This reverts commit 2a7f32f21165fb89c1006dd8c19c817186483c94.
Let's just keep this out for now because it looks misleading in
`testiso` test failure. We'll bring it back in once the functionality
needed eventually lands in a coreos-installer release.

Revert "qemu: Automatically inject serial console karg into ISO"

---

mantle/kola/README-kola-ext.md
mantle/kola/harness.go
mantle/kola/register/register.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/platform.go

For the root reprovisioning work, we need to be able to temporarily save
the rootfs into RAM. This means we need at least 4G of RAM.
Add a new `minMemory` field which tells the platform to make sure the
machine provisioned has at least that amount of memory. On QEMU, this
directly controls the memory of the machine. On cloud platforms, it
would affect the instance type to use. But for now, we only actually
handle this field on QEMU.

kola: add minMemory in kola.json (external tests)

---

src/cmd-buildextend-aws

Backport of #1574
Update mantle submodule for required code (from newly created branch https://github.com/coreos/mantle/tree/rhcos-4.3)

[4.3] aws: Add ability to grant snapshot volume permission to users

---

Dockerfile
build.sh

The packages should all exist within the stable repos so we shouldn't
need the fast-track packages from the continuous repos.
This is a manual backport of 32966347b19aa82de00f932664d2b2f6f234a9c9
since no other repos are setup for rhcos-4.3 we can remove the function
entirely.

[4.3] Remove "configure_yum_repos" function

---

build.sh

Aside from the f32 specific packages that are required we should only
need the packages that exist in the stable repo.
(cherry picked from commit 32966347b19aa82de00f932664d2b2f6f234a9c9)

[4.4] Remove f31 coreos-continuous kojipkgs repo

---

build.sh

Aside from the f32 specific packages that are required we should only
need the packages that exist in the stable repo.

[4.5] Remove f31 coreos-continuous kojipkgs repo

---

src/deps.txt

Adding python3-flufl as a dependency for potential NFS-safe file locking.
flufl.lock is not used right but is being proposed as a means to do file
locking for meta.json merging. Should flufl.lock not be used, this
commit should be reverted at a later time.
This dependency only adds 59K to the COSA container and will make CI
happy for the huge PR's coming later.

deps.txt: add python3-flufl

---

mantle/kola/harness.go

Update `registerTestDir()` to warn about discovering non-executable files with a shebang in externally defined test directories, since those files are probably meant to be executable tests.

kola/harness.go: Warn about non-executable files with shebang

---

src/cosalib/meta.py
tests/test_cosalib_meta.py

This is a much simpler version of
https://github.com/coreos/coreos-assembler/pull/1663
that will also reliably work even for code that's not using `GenericBuildMeta`.

meta: Use timestamp on meta.json to detect read-modify-write conflicts

---

src/cosalib/build.py
src/cosalib/cmdlib.py
src/cosalib/meta.py
src/deps.txt

This imposes a lock on the cmdlib.load_json and cmdlib.write_json
functions via an NFS safe lock. In order for the lock across namespaces
(e.g. different pods) and read by other COSA processes, the lock is
written to the same path as the target file.
The lock will lock until released with a max lifetime of 15s.
Implements: cosa-20200805
https://github.com/coreos/enhancements/pull/2

cosalib: lock meta.json before reading and writing

---

mantle/cmd/ore/aws/upload.go
mantle/platform/api/aws/images.go
src/cosalib/aws.py

Backport of #1574
The GrantVolumePermission function grants permission to access an EC2
snapshot volume (referenced by its snapshot ID) to a list of AWS users
(referenced by their 12-digit numerical user IDs).
This functionality is being made accessible through a new
`grant-user-snappshot` flag on the `ore aws upload` command.

[4.4] mantle: Add ability to grant snapshot volume permission to users

---

mantle/cmd/ore/aws/upload.go
mantle/platform/api/aws/images.go
src/cosalib/aws.py

Backport of https://github.com/coreos/coreos-assembler/pull/1574
The GrantVolumePermission function grants permission to access an EC2
snapshot volume (referenced by its snapshot ID) to a list of AWS users
(referenced by their 12-digit numerical user IDs).
This functionality is being made accessible through a new
`grant-user-snappshot` flag on the `ore aws upload` command.

[4.5] mantle: Add ability to grant snapshot volume permission to users

---

src/oscontainer.py

Since this code gets invoked with `sudo`, if we fail in the middle
it means higher level code running as non-root can fail to clean
up the temporary files.

oscontainer: Clean up directory on failure

---

src/cmd-offline-update

This way it's easier to hack on "generate OSTree commit, update
disk image to it".

offline-update: Also accept an arbitrary commit for updating

---

src/oscontainer.py

I'm working on synthesizing an update from an existing oscontainer
and doing that I don't have a cosa build for it handy.
If we don't find a `builds.json`, assume we're not in a cosa
directory and skip adding the metadata.

oscontainer: Handle being run without a cosa build

---

src/oscontainer.py

We fixed the core issues around pushing the oscontainer, so
this has been dead code for a while.

oscontainer: Remove unused retry code

---

mantle/cmd/kola/testiso.go

Now that the rootfs has been separated from the initramfs, the size of initramfs is small enough for tftp to accept it.

testiso: enable pxe-install for s390x

---

src/oscontainer.py

I kept running into failures trying to run this in an
unprivileged container; basically the containers stack
seems to want to try to `chown()` files based on the UIDs,
but we don't care about that at all for this.
What we really want is the functionality of `oc image extract`
but that doesn't exist yet in the podman stack and today
cosa doesn't include `oc` (that's a big discussion).

oscontainer: Use skopeo, not podman to extract

---

mantle/cosa/cosa_v1.go
mantle/cosa/schema_doc.go
src/schema/v1.json

Added two new keys to the schema:
- coreos-assembler.meta-stamp: to version meta.json
- coroes-assembler.delayed-meta-merge: boolean for determining when
and if meta.json should be written to artifacted paths.
Break out from 
https://github.com/coreos/coreos-assembler/pull/1675
Partially Implements: cosa-20200805
https://github.com/coreos/enhancements#2

schema: update for meta.json merging

---

mantle/platform/qemu.go

They don't, it's totally valid to do e.g.:
`cosa run --qemu-size=20G` which uses the build as a backing file
and also resizes - this works today.

qemu: Remove outdated comments about backingfile/size conflicting

---

.cci.jenkinsfile
src/cmd-build
src/cmd-buildextend-installer
src/cmd-buildextend-metal
src/cmd-meta
src/cmdlib.sh
src/cosalib/build.py
src/cosalib/cmdlib.py
src/cosalib/meta.py
src/cosalib/qemuvariants.py
src/create_disk.sh
tests/test_cosalib_cmdlib.py
tests/test_cosalib_meta.py

Instead of blindly overwriting meta.json, this adds support for merging
the on-disk version with the in-memory version.
`write_json` has been given a `merge_func` callback. This enables the lock to be held in one spot. `write_json` calls the `merge_func` with the on-disk version with the version being merged, preserving the lock. The version with the higher stamp is the base version for the merge. 
Partially Implements: cosa-20200805
https://github.com/coreos/enhancements/pull/2

cosalib/meta: implement meta.json merging

---

mantle/kola/harness.go

mantle/kola: increase log lines printed when exttest fails

---

src/create_disk.sh
src/vmdeps.txt

Part of creating Fedora Silverblue based on FCOS (FCOSB); see
https://fedoraproject.org/wiki/Changes/BtrfsByDefault
(Ignition supports reprovisioning, but this is about setting the
default)

create_disk: Add support for btrfs

---

src/cmd-build

In a Jenkins build environment, compose.json may not exist.

cmd-build: ensure that compose.json exists

---

src/cmd-buildextend-metal

This prevents parallel builds from breaking due races around
tmp/kernel-config.

cmd-buildextend-metal: fix race condition for kernel config

---

mantle/kola/README-kola-ext.md
mantle/kola/harness.go

If the user adds a subdirectory they are doing it for a reason, and
it's confusing to omit the name of the executable.
I forget now why we were even special casing this in the first place.

kola: Don't special case "one executable in directory"

---

src/cmdlib.sh

This fixes a problem where the FCOS pipeline attempts to upload the
supermin container.

cmdlib: cleanup supermin output from runvm

---

mantle/cmd/kola/devshell.go
mantle/cmd/kola/kola.go
mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/testiso.go
mantle/kola/harness.go
mantle/kola/tests/ignition/qemufailure.go
mantle/platform/conf/conf.go
mantle/platform/metal.go
mantle/platform/qemu.go

Second part of Ignition spec 3.1.0 support for mantle & kola.
This makes most Ignition config handling independent of the config spec version.
Fixes: https://github.com/coreos/coreos-assembler/issues/1430

mantle & kola: Full ignition spec 3.1.0 support

---

mantle/cmd/kola/kola.go
mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/testiso.go
mantle/cmd/ore/do/create-image.go
mantle/cmd/ore/packet/create-device.go
mantle/kola/harness.go
mantle/kola/tests/ignition/qemufailure.go
mantle/platform/cluster.go
mantle/platform/conf/conf.go
mantle/platform/conf/conf_test.go
mantle/platform/metal.go

Seeing the two `""` in most of our calls like
`conf.Ignition("").Render("", kola.IsIgnitionV2())`
felt confusing - I had to go look up what those strings meant.
For the `Render()` case the main reason we're still carrying
some CL code is because some of the tests we'd eventually
like to port still refer to it.  But we're not actually
using it, so split off a separate API for the unusual case.
And make an `EmptyIgnition()` API instead of providing the empty
string.

mantle: Avoid two empty string `""` in most Ignition calls

---

mantle/platform/qemu.go

Use virtio-scsi on correct bus on each arch and suppress the warning clutter that occurs on all arches.

Fixes most of the multipath tests on the s390x

---

mantle/kola/tests/rhcos/luks.go

Virtual TPM support is not yet present in qemu for aarch64. It will land as part of qemu5.0 i believe.

kola/test/luks: disable luks test for aarch64

---

src/cmd-buildextend-metal
src/cmdlib.sh

Followup to previous PR; change things so that on a successful
image build the last thing we see is e.g.:
`Successfully generated: fedora-coreos-32.20200903.dev.0-7-qemu.x86_64.qcow2`
And if we're on a tty, color the `fatal:` text red.

Make success/failure even more obvious

---

src/cmdlib.sh

A race that's started happening now that we're trying to do
builds in parallel; the cache disk is only relevant today
for the rpm-ostree-in-VM operations, so only provide it for
that run.  This way we won't have multiple VMs mounting
the same disk writable which qemu detects and errors out on.

Only add cache disk for rpm-ostree builds

---

mantle/cmd/kola/testiso.go
mantle/platform/metal.go
mantle/platform/qemu.go
mantle/platform/qmp_util.go

As a follow up to #1700 also support iso tests on aarch64

testiso : Support iso-install tests on aarch64

---

README.md

It's useful to use `coreos-assembler` to run pre-built qcow2 images or
custom Ignition files, so let's provide some simple examples.

README: add docs about using qemuexec

---

src/cmd-build

I made a f33 toolbox container and this fell over because
it didn't include python 2.  This was the only thing that
needed changing at least to `cosa build`.

build: Switch to python3

---

mantle/platform/metal.go

with the removal of the legacy installer, this is no longer needed as the new installer works well with the default 4G.

testiso: Remove special casing of memory for s390x

---

.cci.jenkinsfile
src/coreos-assembler

Before leveraging the new parallel support in pipelines, let's make sure
we're testing it here.
This patch changes things in various ways:
- Separates out a bit more clearly the different stages with more
appropriate labels. This is important to be able to more easily read
the results in the BlueOcean dashboard. Nesting stages/parallel steps
don't render well.
- Turns on upgrade tests.
- Harmonizes on coreos-ci-lib's way of doing some things, like archiving
test results. I'd like to rework this eventually to use the standard
`fcosBuild` and `fcosKola`, though we need to add support there for
running as a separate user.
- Builds the metal and metal4k images in parallel.
- Builds the cloud images in parallel.

ci: restructure and parallelize

---

mantle/kola/harness.go

kola: use filepath.Base() for `test.sh` special-case

---

.cci.jenkinsfile

Now that we build lots of artifacts, this should make CI go faster.

ci: use `compress --fast`

---

src/cmd-kola

Multi-arch is not able to run --basic-qemu-scenarios using nvme and uefi
due some issues:
- The uefi is not supported on multi-arch (POWER and s390x);
- The nvme qemu emulation is not supported in Fedora for s390x;
- POWER has a bug to support qemu nvme emulation in a Fedora guest.

Run only basic tests without nvme and uefi on multi-arch

---

mantle/platform/qemu.go

Let's answer the "why not libvirt" first.
I think syzkaller is a cool project in particular, and was
curious about how they do kernel testing, so I recently spent
a bit of time looking at their code.
And kata also has a lot of strongly related bits.
So hopefully in the future we can share ideas if not actual code.

qemu: Add comment discussing libvirt and links to related projects

---

mantle/cmd/kola/devshell.go
mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/testiso.go
mantle/kola/tests/ignition/qemufailure.go
mantle/platform/machine/qemuiso/machine.go
mantle/platform/machine/unprivqemu/machine.go
mantle/platform/qemu.go

This introduces a tree of context values in the QEMU driver,
in order to link waiting methods together and to make them
cancellable in a uniform way.

platform/qemu: wire waiting methods via a context tree

---

build.sh

This should fix some partitioning issues we're seeing with 5.8.8. See
issue for more details.
Closes #1723.

build.sh: cherry-pick kernel-5.8.9

---

.cci.jenkinsfile

Then we can diff the rpmdb from two CI runs to help debug issues. That's
more or less what I did to investigate #1723, but this should make it
trivial.

ci: archive rpmdb listing for easier debugging

---

mantle/cmd/kola/qemuexec.go
mantle/go.sum
mantle/kola/tests/ignition/qemufailure.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/qemu.go

A few times I've ended up with a non-bootable qcow2, and
the behavior of `cosa run` is that you end up hanging at
`[Link:up, TX:0 TXE:0 RX:0 RXE:0]`
which is the TFTP fallback.
Add an API and use it so that for the cases where we know
we're booting a qcow2, we tell the firmware only to boot
from a hard drive, so we end up hanging at:
`Boot failed: not a bootable disk`
which is at least a much more obvious failure.
(I think with QMP we might be able to detect this and
error, needs investigation)

qemu: Make primary disk required, don't TFTP etc.

---

mantle/platform/qemu.go

This should little bit better reflect real HW and avoids situations
when udev can't assign predictable names to NICs. Fixes kola qemu
test ext.config.misc-ro detecting eth* names.

mantle/platform: switch aarch64 to pci bus for virtio devices

---

build.sh

That package is in the stable repos now so let's stop pinning it while
it's still fresh in our minds.

build.sh: drop kernel 5.8.9 override

---

mantle/platform/metal.go
mantle/platform/qemu.go
mantle/platform/qmp_util.go

With #1714 landing, needed a better way to differentiate blk devices as the cdrom is also a pci
device in aarch64. Used the `query-block` qmp query to detect blk devices and identify them that way.

qemu: differentiate blk devices when switching boot order

---

src/create_disk.sh
src/vmdeps-aarch64.txt
src/vmdeps-x86_64.txt

See https://github.com/coreos/bootupd
and coreos/fedora-coreos-tracker#510
Basically in order to handle *updates*, bootupd also
takes care of installation.  For example this also generates a JSON
file with the versions.
In order to sanely "ratchet" this change, only use bootupd if
we find the ostree deployment is using it.

 create_disk: Use bootupd to install uefi if configured

---

src/cmd-virt-install

With `--console`, we immediately hook into the VM's console once it's
started. This is different from dropping `--noautoconsole` which would
make it want to connect to the VGA (one can use `--nographics` on top of
that to force it to connect to the serial port instead, but sometimes
you do also want to be able to see the VGA output).

cmd-virt-install: add --console

---

src/cmd-buildextend-live

Followup to https://github.com/coreos/coreos-assembler/pull/1695/commits/56336550e7d3e959d9dd103107f0422097da43d4
Caught in CI for https://github.com/coreos/fedora-coreos-config/pull/595

buildextend-live: Support bootupd

---

mantle/cmd/kola/options.go

I've run into a few times where I have tried to use `cosa run
--qemu-image` without having done a local build first and it errors
out looking for a `meta.json`. This improves how we handle the lack
of local build metadata when a disk image is provided.

kola: improvements for lack of local build metadata

---

mantle/kola/tests/ignition/units.go

Related to https://github.com/coreos/ignition/issues/1064 
This change will ensure to cover the `systemd instantiated timer` test case in CI.
Needs to get in these two changes:
1.  [testing](https://github.com/coreos/fedora-coreos-config/pull/630)
2. [next](https://github.com/coreos/fedora-coreos-config/pull/631)

mantle/kola/tests/ignition: add systemd instantiated timer test

---

mantle/cmd/kola/qemuexec.go
mantle/cmd/kola/testiso.go
mantle/platform/machine/qemuiso/cluster.go
mantle/platform/machine/unprivqemu/cluster.go
mantle/platform/qemu.go
src/cmdlib.sh

This restores access to the monitor via `Ctrl-A C` and allows passing
through `Ctrl-C` to the guest as before.
This used to be what QEMU did by default, but when we added an explicit
QMP socket in #1705 it disabled that sugar.
Closes: #1725

mantle/qemu: explicitly add `-serial mon:stdio`

---

mantle/cosa/cosa_v1.go
mantle/cosa/schema_doc.go

Otherwise it's not in the golang generated code.
Follow-up to #1740.

mantle: run `make schema-update` for ibmcloud

---

src/create_disk.sh

Regression from bootupd support.
Closes: https://github.com/coreos/coreos-assembler/issues/1746

create_disk: Install grub config on aarch64

---

mantle/kola/tests/ignition/qemufailure.go
src/cmd-buildextend-metal

For aarch64, drop the tty as the default console is ttyAMA0. specifying the tty causes devshell console
to get stuck in the initramfs phase when there is a failure. Also specify firmware in the ignition failure
kola test as aarch64 is uefi.

drop tty for aarch64 and specify firmware in kola ignition failure test

---

mantle/network/ssh.go
mantle/platform/conf/conf_test.go

Upstream SSH has been claiming [1] for a few releases now that:
```
It is now possible to perform chosen-prefix attacks against the
SHA-1 algorithm for less than USD$50K. For this reason, we will be
disabling the "ssh-rsa" public key signature algorithm by default in a
near-future release.
```
In Fedora we switched recently [2] to disallow ssh-rsa so we need to
switch our tools to a different type of key.
[1] https://www.openssh.com/txt/release-8.3
[2] https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/commit/b298a9e107b7e9699b36879eca031d1900ded1c4

mantle: make kola use ecdsa SSH keys

---

src/cmdlib.sh

Fixes a failure with:
```
$ cp /path/to/rpm overrides/rpm
$ cosa build
$ rm -rf overrides/rpm/*.rpm
$ cosa build`
error: Couldn't find locked package '<package you removed>' (pkgs matching NEVRA: 0; mismatched checksums: 0)
```

build: Remove local overrides lock when removing RPMs

---

src/build-deps.txt

Adding an extra build dependency. My plant is to use `golint` for `entry` as an extra code-quality check.

src/build-deps.txt: add golint as a build dep

---

src/cmd-kola

This seems odd on the surface but meshes well with how config files are
synced between FCOS branches. This will allow us to exclude a test for
a specific stream only.

cmd-kola: allow excluding tests for specific branch

---

mantle/kola/tests/misc/network.go

We now have systemd-resolved which listens on ports 53 and 5355.

mantle: kola: Update fcos.network.listeners test for Fedora 33

---

mantle/cmd/kola/testiso.go

The new Kernel change is causing testiso to fail.
We need to skip this test until we have a final
solution.
Check https://github.com/coreos/coreos-assembler/issues/1757

[4.5] Skip testiso for POWER

---

mantle/cmd/kola/testiso.go

The new Kernel change is causing testiso to fail.
We need to skip this test until we have a final
solution.
Check #1757

[4.4] Skip testiso for POWER

---

mantle/platform/qemu.go

To get rid of the deprecation warning:
```
+ kola testiso -S --scenarios pxe-install,pxe-offline-install,iso-install,iso-offline-install --output-dir tmp/kola-testiso-metal
Testing scenarios: [pxe-install pxe-offline-install iso-install iso-offline-install]
Successfully tested scenario pxe-install for 32.20201005.dev.0 on bios (metal)
Successfully tested scenario pxe-offline-install for 32.20201005.dev.0 on bios (metal)
`iso embed` is deprecated; use `iso ignition embed`.  Continuing.
```
We need to update to `coreos-installer iso ignition embed`.

mantle: platform: update iso embed call

---

mantle/kola/tests/podman/podman.go

Sometime between podman 1.x and 2.x podman started putting
full 64 character IDs into the json output. Dynamically detect
the length of the ID and compare that number of characters.
We haven't noticed this test failing because we've been denylisting
the test in the pipeline: https://github.com/coreos/coreos-assembler/pull/1478

mantle: fix podman.workflow stop test

---

src/cmd-buildextend-live

When that key is on, we use the coreos-installer from cosa instead of
the target system. This is a temporary hack to unblock the f33 rebase in
next.
See #1761 for details.

buildextend-live: add osmet-pack-with-cosa-coreinst image.yaml key

---

src/cmd-buildextend-live

It's no longer used on any FCOS stream.

buildextend-live: drop --legacy-pxe option

---

src/cmd-buildextend-live
src/cmd-compress
src/cmd-list
src/cmd-sign
src/cosalib/fedora_messaging_request.py
src/cosalib/qemuvariants.py
src/osmet-pack

We're not quite ready to move to Fedora 33 for COSA, but
I did a test run and noticed some build check failures, so we
might as well fix them now.

fix flake8 and shellcheck failures when moving to f33

---

mantle/network/ssh.go
mantle/platform/conf/conf_test.go

This reverts commit 5c036d17c9b0fd561642af8f602a61eff84f403e.
That commit broke `kola` on AWS, because that platform only supports
RSA keys.
Ref: https://github.com/coreos/coreos-assembler/pull/1749#issuecomment-704091353
/cc @dustymabe @jlebon

Revert "mantle: make kola use ecdsa SSH keys"

---

entrypoint/Makefile
entrypoint/ocp/build.json
src/deps.txt

This turns on golint for entrypoint and adds bsdtar.
bsdtar is needed to support OpenShift binary builds.
Makefile also includes a `devtest` target to mocking an OpenShift
Build environment, which is suitable for testing.

entrypoint: build dep and Makefile improvement

---

build.sh
mantle/cmd/kola/testiso.go

Looks like the issue with testiso failing wasn't really an issue with the kernel but a grub update which caused the legacy
install to break. Downgrading grub fixed the issue. Tracked by: https://bugzilla.redhat.com/show_bug.cgi?id=1884854

[4.5] Revert #1759 and downgrade grub for ppc64le

---

build.sh
mantle/cmd/kola/testiso.go

Looks like the issue wasn't really with the kernel but a grub update which caused the legacy
install to break. Downgrading grub fixed the issue. Tracked by: https://bugzilla.redhat.com/show_bug.cgi?id=1884854

[4.4] Revert #1760 and downgrade grub for ppc64le

---

mantle/kola/harness.go

Re-provisioning tests fail on ppc64le due to lack of the memory, bumping it
beyond 6G makes them succeed. Most probably caused by slightly higher overhead
of the 64k pages in combination with slightly bigger size of COS on ppc64le.

kola/ext: bump minimum of memory to 8G on 64k page arches, ppc64le for now

---

mantle/kola/harness.go

Otherwise using patterns in `kola-denylist.yaml` won't always work since
`src/config` might be a repo or might be a symlink.
Let's just standardize on `config` being the name of "the repo which is
at src/config" so that we don't have to think about this when adding
tests to the denylist.

kola: don't resolve symlinks for ext test naming

---

entrypoint/Makefile

I do `make && sudo make install` and golang wants to rebuild the
binaries as root, which fails because the Go environment isn't set up
there.
There are ways to deal around this (using eg. Colin's `makesudoinstall`:
https://github.com/cgwalters/homegit/blob/735331bb748c71c5b2fac36a10c891381e38e0ae/dotfiles/bashrc#L21),
though it's good to clean up the `install` target to have it actually
key off of the binary. This matches the mantle Makefile.

entrypoint: avoid triggering `build` at `install` time

---

src/cmd-virt-install

This way it works to use this outside of a cosa builddir.
Same rationale as other similar PRs for kola with `--qemu-image.

virt-install: Only allocate Builds if --image is not passed

---

exttests/Dockerfile
exttests/README.md
exttests/build.sh

This is aiming to finally, finally close the loop around
running upstream tests as part of our CI.
We landed support for "exttests" in here for a while and
since then we are successfully running upstream test suites
using kola on upstream pull requests.
But we also want the inverse: run upstream tests on builds outside of PRs to those repos.
For example,
I really want to run ostree's "transactionality" test on FCOS builds so that if a kernel change breaks it, we know that.
In practice, it's likely that down the line we
will need to version at least some of our tests along
with the OS content - by building them as RPMs or
sticking them in containers that are versioned with the OS
or something.
But for now, building fixed upstream releases will
give us a lot of reproducibility/control, at …

exttests: New container image with upstream tests

---

mantle/kola/tests/ignition/resource.go

The CL AWS account which hosted the `kola-fixtures` bucket is going
away. Move the test to a new bucket in a different account.

kola/tests/ignition: update resource test to use different bucket

---

src/cmdlib.sh

Storing overlay files in git is very convenient, but
introduces possible umask issues; for example see
https://github.com/coreos/fedora-coreos-config/pull/543
This sidesteps the problem for executables by removing
the write bit entirely.
(The problem remains for non-executables; that's
trickier)

cmdlib: Ensure overlay files have read-only executables

---

src/cmd-build
src/cmd-fetch
src/cmdlib.sh

Even without `--with-cosa-overrides`, `cosa fetch` would still pick up
the stale lockfile at `tmp/override/local-overrides.json` leftover from
a previous run.
Let's just always run `prepare_compose_overlays` which already takes
care of deleting the lockfile if no cosa overrides are present. We just
need to wire `--with-cosa-overrides` through for the `cosa fetch`
semantics we want.

cmd-fetch: better ignore cosa overrides by default

---

docs/kola/adding-tests.md

All else equal, we prefer test contributors to use the external test
model where tests can live alongside the OS definition over adding more
"native" kola tests.
See previous discussions about this in
https://github.com/coreos/coreos-assembler/pull/1273.

docs/kola: mention external tests are preferred

---

docs/kola/external-tests.md
mantle/kola/harness.go

Increases the ergonomics of writing external tests.

kola: Support config.fcc for external tests

---

src/cmd-build
src/cmd-prune

I'm not sure why we didn't do this from the start.  The immediate
motivation here is I was trying to diff two builds and the ostree
commit previously was pruned while the cosa build still existed.
Now yes I could import the ostree tarball but this seems clearly
better.
With this we can also drop the `tmpref-` hack we have for RHCOS
and just use the build ID as a ref.

Write out a ref with the build ID

---

mantle/kola/tests/ignition/empty.go
mantle/network/ssh.go
mantle/platform/conf/conf_test.go
mantle/platform/machine/aws/flight.go

In 5c036d1 we swtched to ecdsa keys for the new crypto
policy change. In fdcfbbc we switched it back because
when we create new ssh keys on AWS we'd get an error because
that platform only accepts rsa keys:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#how-to-generate-your-own-key-and-import-it-to-aws
For now let's disable the `fcos.ignition.v3.noop` on AWS and
just use a fake key for that platform to satisfy the requirement.
Eventually we'll switch back to RSA keys once the golang library
has been updated.
See https://github.com/coreos/coreos-assembler/issues/1772

mantle: work around for ssh crypto policies change

---

mantle/cmd/kola/options.go
mantle/platform/api/aws/ec2.go
mantle/platform/api/aws/network.go
mantle/platform/machine/aws/machine.go

```
commit 7d1623a8d36d3084e3dd5a0eef3112ae1aed8808
Author: Colin Walters <walters@verbum.org>
Date:   Wed Jun 3 16:47:48 2020 +0000
kola: Bump default instance type to m5.large
m4 is old and shouldn't be the default; this came up as
part of https://github.com/coreos/fedora-coreos-tracker/issues/507
commit af4b81290a8ed57cfcecad1d5b6c80e8c1ef598c
Date:   Fri Jun 19 14:11:46 2020 -0400
mantle: platform: don't start instances in "us-east-1c"
That region doesn't support the m5.large hardware type which
we want to use now.
```

kola: Bump default instance type to m5.large

---

src/create_disk.sh

The 4.5 pipeline for s390x was failing kola tests because of an updated ostree in the cosa container. This contained the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1867601 which made the root file systems immutable. But the ostree version of RHCOS does not contain the fix causing rollbacks and upgrades to fail.
Removed the immutability bit to fix it as suggested by @cgwalters. Also opened a BZ to include fix in ostree for RHCOS 4.5
Co-Authored-By: Colin Walters <walters@verbum.org>

[4.5]create_disk: remove immutable bit for s390x

---

.travis.yml

Using coreos-assembler:master to save time in ci execution was
causing some package dependency issues since python2 support was
dropped in Fedora 32.  CI will have to take a little longer now.

[rhcos-4.3] ci: use Fedora 31 image

---

Dockerfile

There's a binding between the bootupd version in cosa vs the one in the
tree, and we think this is causing an issue in CI. Let's make sure cosa
pulls in the latest bootupd.
Ref: https://github.com/coreos/fedora-coreos-config/pull/711

Dockerfile: blow out cache to force full Quay rebuild

---

src/cmdlib.sh

This is breaking `supermin --build` for me because it doesn't know what
to do with `etc/resolv.conf` in the prepare dir.
But anyway in user-mode networking, Slirp already takes care of DNS
forwarding in the supermin VM to the host's DNS provider so we shouldn't
need to copy `resolv.conf` at all.

cmdlib: stop copying resolv.conf

---

src/create_disk.sh

The 4.4 pipeline for s390x was failing kola tests because of an updated ostree in the cosa container. This contained the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1867601
which made the root file systems immutable. But the ostree version of RHCOS does not contain the fix causing rollbacks and upgrades to fail.
Removed the immutability bit to fix it as suggested by @cgwalters.
Co-Authored-By: Colin Walters <walters@verbum.org>
(cherry picked from commit 8964218106488f3d72be45cbe8be0fd4c4502e83)

[4.4]create_disk: remove immutable bit for s390x

---

src/cmd-buildextend-metal
src/create_disk.sh
src/gf-platformid

We've now reached the end of the conditional networking 🌈 rainbow 🌈.
We can rip out the legacy default network firstboot kargs from cosa.
These now live in the config repo. E.g.:
https://github.com/coreos/fedora-coreos-config/blob/be456c437d4181435022ce47079b587f5bcb0319/overlay.d/05core/usr/lib/dracut/modules.d/15coreos-network/50-afterburn-network-kargs-default.conf
For more details, see:
https://github.com/coreos/coreos-assembler/pull/1373
https://github.com/coreos/fedora-coreos-config/pull/426

Drop support for ignition-network-kcmdline

---

mantle/lang/maps/sorted_test.go

This cleans up lang/maps/sorted_test.go in mantle according to
golangci-lint, which improves the readability. And we can bring in
golanci-lint to check both Mantle and Entrypoint.

mantle: clean up code base

---

mantle/kola/tests/rhcos/upgrade.go

This cleans up unused plog in kola/tests/rhcos/upgrade.go.

kola: clean up unused plog

---

mantle/kola/tests/rhcos/luks.go

This cleans up kola/tests/rhcos/luks.go.

kola: clean up luks

---

src/cosalib/fedora_messaging_request.py

This function will be used for sending informational messages (i.e. for
which we don't expect a reply) other services may care about. The new
fedmsgs are, with prefix omitted:
- `build.state.change`: to signal build start and finish
- `stream.release`: to signal stream release
- `stream.metadata.update`: to signal stream metadata change
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/225

cosalib/messaging: add broadcast_fedmsg function

---

src/cmd-generate-hashlist
src/coreos-assembler

This set of patches adds a new command called `generate-hashlist`. This is an alternate implementation of https://github.com/coreos/coreos-assembler/pull/1790 based on feedback.
See: https://github.com/keylime/enhancements/blob/master/16_remote_allowlist_retrieval.md
cc @lukehinds @mpeters @font @lkatalin @puiterwijk

Add Keylime HashList generation support OSTree Style

---

mantle/cmd/kola/kola.go

The comment says that `--build` is required, but what we really mean is
that a cosa build is required. Whether that build is auto-discovered or
given explicitly via `--build` doesn't matter. Move the check for a cosa
build down to after `syncOptionsImpl()` to reflect this.
This also fixes a missing `return` which Jing originally had in #1826.
Co-authored-by: Jing Zhang <jingzhan@redhat.com>
Closes: #1827

kola: fix upgrade tests handling cosa build

---

mantle/auth/google.go

This cleans up auth/google.go.
Fixes part of https://github.com/coreos/coreos-assembler/issues/1813:
```
auth/google.go:71:26: SA1019: oauth2.NoContext is deprecated: Use context.Background() or context.TODO() instead.  (staticcheck)
ts := conf.TokenSource(oauth2.NoContext, tok)
^
auth/google.go:101:28: SA1019: oauth2.NoContext is deprecated: Use context.Background() or context.TODO() instead.  (staticcheck)
tok, err = conf.Exchange(oauth2.NoContext, code)
^
auth/google.go:123:21: SA1019: oauth2.NoContext is deprecated: Use context.Background() or context.TODO() instead.  (staticcheck)
return conf.Client(oauth2.NoContext, tok), nil
^
auth/google.go:133:26: SA1019: oauth2.NoContext is deprecated: Use context.Background() or context.TODO() instead.  (staticcheck)
return …
```

mantle: clean up auth

---

src/cmd-build
src/cmdlib.sh

Otherwise once we detected a change, we'll keep thinking there's
a new ostree commit for every subsequent build.
This breaks the idempotency of `cosa build`.

build: Clear out change stamp file

---

mantle/kola/harness.go

This would've caught
https://github.com/coreos/fedora-coreos-tracker/issues/660.

kola: check for systemd ordering cycles in console

---

mantle/cmd/kola/qemuexec.go

This cleans up cmd/kola/qemuexec.go:
```
cmd/kola/qemuexec.go:95:4: S1023: redundant break statement (gosimple)
break
^
cmd/kola/qemuexec.go:231:17: Error return value of `builder.AddIso` is not checked (errcheck)
builder.AddIso(kola.QEMUIsoOptions.IsoPath, "")
^
```

mantle: clean up qemuexec

---

mantle/platform/api/aws/images.go

Don't hardcode `[0]` when trying to get the snapshot ID, the ephemeral
device might be first. Use the `getImageSnapshotID()` helper instead
which was made to handle this.

mantle/aws/images: support Ebs blockdev not being first

---

mantle/cmd/kola/kola.go

This cleans up cmd/kola/kola.go.

mantle: clean up cmd kola

---

mantle/cli/cli.go

This cleans up cli/cli.go, drop deadcode.
Fixes part of https://github.com/coreos/coreos-assembler/issues/1813:
```
cli/cli.go:73:6: `setRepoLogLevel` is unused (deadcode)
func setRepoLogLevel(repo string, l capnslog.LogLevel) {
^
```

mantle: clean up cli

---

src/cmd-build
src/cmd-buildextend-metal
src/cmdlib.sh
src/create_disk.sh

This is a general cleanup followup to the previous PR
to add a "buildid" as a ref always.
In most cases actually where we were using the ref we can
just use the commit.
But switch a few things to use the buildid, and drop the
`ref_is_tmp` hack.

Use build ref or commit, drop "ref_is_tmp" hack

---

mantle/cmd/kola/switchkernel.go

This cleans up cmd/kola/switchkernel.go:
```
cmd/kola/switchkernel.go:93:34: Error return value of `cmdSwitchKernel.MarkFlagRequired` is not checked (errcheck)
cmdSwitchKernel.MarkFlagRequired("kernel-rt")
^
cmd/kola/switchkernel.go:180:2: S1038: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (gosimple)
fmt.Println(fmt.Sprintf("%s", stderr))
^
cmd/kola/switchkernel.go:181:2: S1038: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (gosimple)
fmt.Println(fmt.Sprintf("%s", stdout))
^
cmd/kola/switchkernel.go:210:2: S1038: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (gosimple)
fmt.Println(fmt.Sprintf("%s", stderr))
^
cmd/kola/switchkernel.go:211:2: …
```

mantle: clean up switchkernel

---

src/cmd-build
src/cmd-buildextend-metal
src/cmdlib.sh
src/create_disk.sh

This reverts commit e734a6e696dac0f9014dc6ed5da9caaba46a496e.
It breaks change detection for RHCOS, needs rpm-ostree API.

Revert "Use build ref or commit, drop "ref_is_tmp" hack"

---

mantle/go.mod
mantle/platform/api/openstack/api.go

This is a followup to b5eb5d6. We need to set $OS_CLIENT_CONFIG_FILE
to the value given by the user, which is the path to the clouds.yaml
on their local system.

mantle: openstack: fix passing of openstack config file path

---

mantle/cmd/kola/testiso.go
mantle/platform/metal.go

Following up on comment in #1700 to split the functionality to trigger the boot order
switch to metal.go making it generic.

metal: add new virtio-channel for switching boot order

---

mantle/cmd/ore/aws/upload.go

This cleans up cmd/ore/aws/upload.go:
```
cmd/ore/aws/upload.go:185:18: Error return value of `API.RemoveImage` is not checked (errcheck)
API.RemoveImage(uploadAMIName, s3BucketName, s3ObjectPath)
```

mantle: clean up cmd/ore/aws

---

src/cmdlib.sh

We should be able to `cosa init` and `cosa buildprep` without requiring
KVM. For example, in the FCOS pipeline, we do this when running kola
against various clouds.

cmdlib: only require kvm for building

---

mantle/kola/tests/ignition/ssh.go

It's failing for now. We can re-enable when this is fixed:
https://github.com/coreos/fedora-coreos-tracker/issues/662

mantle: exclude openstack from coreos.ignition.ssh.key test

---

entrypoint/Makefile

golangci-lint will occasionally timeout in lower performant environments, especially those that are IO constrained.
Run usually takes around 90s, so let's bump it to 5m, arbitrary number >90s, to make sure we don't timeout.
For the record default timeout is 1m.

entrypoint: Extend timeout for the golangci-lint

---

entrypoint/Makefile
entrypoint/cmd/build.go
entrypoint/cmd/ci.go
entrypoint/cmd/entry.go
entrypoint/ocp/bc.go
entrypoint/ocp/ci.go
entrypoint/ocp/cosa-pod.go
entrypoint/ocp/k8s.go
entrypoint/ocp/ocp.go

Requiring COSA to run as a buildConfig is not always feasible, since it requires
running as a fully-capable build pod. This change allows any COSA pod to become
a build pod. 
For example:
entry --jobspec jobspec.yaml ci
The pod running entry, must be launched with a service account that can
create pods (i.e. the Jenkins SA). OpenShift deployed Jenkins instances
are capable.
The results of run will be put in /srv. It's envisioned that Jenkins
Pipelines and Prow could use this interface, while developers and ART
pipelines can use the BuildConfig interface. One major difference with
this interface is that cannot use the binary source interface yet.
To ensure parity, the CI mode mock's the OpenShift Build v1 API.

Entrypoint: CI mode for buildConfig-less runs

---

entrypoint/cmd/builder.go
entrypoint/remote/archive.go

This creates tar ball with directories in cosa, and runs oc command to
start bc/cosa-runner-master.
By having COSA as a buildConfig, we can now have a cosa remote command that:
- creates a devel.tar of src, overrides, and local COSA hacks with a JobSpec and build.steps
- call oc start-build bc/cosa-priv --from-archive=devel.tar --follow=true
Details: https://github.com/coreos/coreos-assembler/blob/master/entrypoint/README.md#cosa-remote

entrypoint: add `cosa remote`

---

mantle/cmd/ore/do/create-image.go

This cleans up cmd/ore/do/create-image.go:
```
cmd/ore/do/create-image.go:111:21: Error return value of `API.DeleteKey` is not checked (errcheck)
defer API.DeleteKey(ctx, keyID)
^
cmd/ore/do/create-image.go:118:25: Error return value of `API.DeleteDroplet` is not checked (errcheck)
defer API.DeleteDroplet(ctx, dropletID)
^
```

mantle: clean up cmd/ore/do

---

src/cmd-buildextend-metal
src/create_disk.sh
src/image-default.yaml

The way we parse an `image.yaml` and then convert it
into arguments for `create_disk.sh` is unwieldy.
Instead, convert `image.yaml` into JSON, inheriting default values
from a separate `image-default.yaml` we ship.  Then pass
that JSON to `create_disk.sh`.
This only converts the `rootfs` argument, but if people
are OK with this I can go ahead and convert everything
else - getting us to where the only argument to `create_disk.sh`
is a JSON file that's already been pre-validated.

Add an image-default.yaml, pass JSON to create_disk.sh

---

src/create_disk.sh

After RHCOS switches for 4.7, we can drop the old code.

create_disk: Remove support for non-bootupd systems

---

mantle/cmd/ore/gcloud/create-image.go

This cleans up cmd/ore/gcloud/create-image.go:
```
cmd/ore/gcloud/create-image.go:95:21: SA1019: storage.New is deprecated: please use NewService instead. To provide a custom HTTP client, use option.WithHTTPClient. If you are using google.golang.org/api/googleapis/transport.APIKey, use option.WithAPIKey with NewService instead.  (staticcheck)
storageAPI, err := storage.New(api.Client())
^
```

mantle: clean up gcloud create-image

---

src/cmd-buildextend-metal
src/create_disk.sh

The offset of the BIOS boot partition gets encoded into the boot sector, and that offset is currently 512 MiB, which is awkward if we're going to support rearranging boot-related partitions.  Move the BIOS boot partition to partition 1 at the beginning of the disk, and move `/boot` to partition 3 on all platforms (including `ppc64le`, where it was overridden to partition 2).
In addition, create an unused BIOS boot partition on 4Kn disks.  This reduces the number of distinct partition layouts we need to support.
For https://github.com/coreos/fedora-coreos-config/pull/718, but shouldn't be required by it.  Closes https://github.com/coreos/fedora-coreos-tracker/issues/669.

create_disk: move /boot to partition 3; move BIOS-BOOT to 1 and always create it

---

mantle/cmd/plume/plume.go

This cleans up cmd/plume/plume.go:
```
cmd/plume/plume.go:42:6: `getGoogleClient` is unused (deadcode)
func getGoogleClient() (*http.Client, error) {
^
```

mantle: clean up cmd/plume/plume

---

Dockerfile

Let's get the latest rpm-ostree in.

Dockerfile: Blow out quay.io cache for package updates

---

mantle/cosa/build.go

This cleans up cosa/build.go:
```
cosa/build.go:94:14: Error return value of `errors.New` is not checked (errcheck)
errors.New("data is not compliant with schema")
^
```

mantle: clean up cosa/build

---

src/create_disk.sh

Followup to ca97e50c6de870664f576f9427f377749a2ee19e
This doesn't change anything today because `/boot` is ext4
which flushes the journal on unmount.  But I was just reading
this script and noticed that we should be doing the same thing
for `/boot` that we do for root.

create_disk: Also xfs_freeze /boot

---

mantle/kola/cluster/cluster.go

This cleans up kola/cluster/cluster.go:
```
kola/cluster/cluster.go:160:20: Error return value of `platform.Manhole` is not checked (errcheck)
platform.Manhole(m)
^
```

mantle: clean up kola/cluster

---

gangplank/ocp/cosa-pod.go

This fixes OpenShift 3.x clusters.

Gangplank: fix OCP cluster defaults for 3.x

---

mantle/kola/tests/rhcos/luks.go

That test does not work correctly. It used to pass because of a bug in
clevis which was fixed in the latest version we now ship.
Let's disable it for now to make the pipeline green again, but it will
be reworked in https://github.com/coreos/coreos-assembler/pull/1870.

kola: temporarily disable rhcos.luks.sss.t1

---

mantle/cosa/schema.go

This cleans up cosa/schema.go:
```
cosa/schema.go:65:10: ineffectual assignment to `err` (ineffassign)
result, err := schema.Validate(
^
```

mantle: clean up cosa/schema

---

mantle/cmd/ore/gcloud/upload.go

This cleans up cmd/ore/gcloud/upload.go:
```
cmd/ore/gcloud/upload.go:53:28: Error return value of `cmdUpload.MarkFlagRequired` is not checked (errcheck)
cmdUpload.MarkFlagRequired("bucket")
^
cmd/ore/gcloud/upload.go:55:28: Error return value of `cmdUpload.MarkFlagRequired` is not checked (errcheck)
cmdUpload.MarkFlagRequired("name")
^
cmd/ore/gcloud/upload.go:57:28: Error return value of `cmdUpload.MarkFlagRequired` is not checked (errcheck)
cmdUpload.MarkFlagRequired("file")
^
cmd/ore/gcloud/upload.go:100:21: SA1019: storage.New is deprecated: please use NewService instead. To provide a         custom HTTP client, use option.WithHTTPClient. If you are using google.golang.org/api/googleapis/transport.API        Key, use option.WithAPIKey with NewService instead.  (staticcheck) …
```

mantle: clean up cmd/ore/gcloud/upload

---

src/create_disk.sh

It came up in conversation with @bgilbert and @arithx that the partition
table we have here for s390x is actually transformed by coreos-installer
at install-time.
Let's add a comment to keep that in mind here.

create_disk.sh: add comment re. s390x partition table

---

mantle/kola/tests/crio/crio.go

This cleans up kola/tests/crio/crio.go:
```
kola/tests/crio/crio.go:364:25: S1039: unnecessary use of fmt.Sprintf (gosimple)
subnet := c.MustSSH(m, fmt.Sprintf("jq --raw-output '.ipam.ranges[0][0].subnet' /usr/etc/cni/net.d/100-crio-bridge.conf"))
^
```

mantle: clean up kola/tests/crio

---

mantle/cmd/ore/gcloud/upload.go

Minor regression from #1864. We lost the bit which passes the
authentication info to GCP API. Restore it using new not-deprecated API.

ore/gcloud/upload: fix GCP authentication

---

gangplank/Makefile

This is covered by `make check` already, and it makes iterating on
!gangplank slower because every `make` wants to rerun the tests. (And
for some reason right now those tests are failing when building on f33).

gangplank: don't test at build time

---

mantle/kola/tests/misc/files.go

This cleans up kola/tests/misc/files.go:
```
kola/tests/misc/files.go:45:29: S1019: should use make([]string, 0) instead (gosimple)
badfiles := make([]string, 0, 0)
^
kola/tests/misc/files.go:62:6: S1002: should omit comparison to bool constant, can be simplified to `!valid` (gosimple)
if valid != true {
^
```

mantle: clean up kola/tests/misc/files

---

mantle/kola/tests/ignition/qemufailure.go

This cleans up kola/tests/ignition/qemufailure.go:
```
kola/tests/ignition/qemufailure.go:92:12: Error return value of `inst.Kill` is not checked (errcheck)
inst.Kill()
^
```

mantle: clean up kola/tests/ignition/qemufailure

---

src/gf-fsck
src/libguestfish.sh

EFI partition is no longer 1(but 2), so we have to find it and mount accordingly:
```
fedora-coreos-33.20201120.dev.0-metal.x86_64.raw1    BIOS boot
fedora-coreos-33.20201120.dev.0-metal.x86_64.raw2    EFI System
```
On the other hand, on s390x(because images do not contain EFI and 1st partition now is /dev/sda3) it fails now with:
```
++ guestfish --remote -- part-get-gpt-type /dev/sda 1
libguestfs: error: part_get_gpt_type: /dev/sda: sgdisk output did not contain 'Partition GUID code'
+ '[' '' = C12A7328-F81F-11D2-BA4B-00A0C93EC93B ']'
```

guestfish: fix mounting of '/boot/efi'

---

docs/working.md

Made this one a while ago but now the `cosa run --bind-ro /usr/bin,/run/hostbin` examples are not working anymore. Not sure why.

docs: Improve 'bind-ro' section when running in a container

---

mantle/cmd/kola/devshell.go
mantle/cmd/kola/qemuexec.go
mantle/kola/tests/ignition/qemufailure.go
mantle/platform/metal.go
mantle/platform/qemu.go

This led me down the wrong path before in debugging
https://github.com/coreos/coreos-assembler/issues/1851
The variable in qemu is dead code since the rework of
Ignition handling.  The `Conf` type now holds either
instead of being spec3 and only downconverted
at the last moment.

Remove unused spec2 argument for qemu

---

mantle/kola/tests/ostree/unlock.go

This cleans up kola/tests/ostree/unlock.go:
```
kola/tests/ostree/unlock.go:257:12: printf: Fatalf call has arguments but no formatting directives (govet)
c.Fatalf(`Rollback did not remove hotfix mode; got: $q`, rollbackStatus.Deployments[0].Unlocked)
```

mantle: clean up kola/tests/ostree/unlock

---

mantle/kola/tests/rpmostree/status.go

This cleans up kola/tests/rpmostree/status.go:
```
kola/tests/rpmostree/status.go:89:13: ineffectual assignment to `err` (ineffassign)
reVersion, err := regexp.Compile(rpmOstreeVersionRegex)
```

mantle: clean up kola/tests/rpmostree/status

---

mantle/kola/tests/upgrade/basic.go

This cleans up kola/tests/upgrade/basic.go:
```
kola/tests/upgrade/basic.go:277:3: printf: Fatalf format %v reads arg #1, but call has 0 args (govet)
c.Fatalf("failed to marshal graph: %v")
^
```

mantle: clean up kola/tests/upgrade/basic

---

mantle/kola/tests/rpmostree/deployments.go

This cleans up kola/tests/rpmostree/deployments.go:
```
kola/tests/rpmostree/deployments.go:302:4: printf: Fatal call has possible formatting directive %d (govet)
c.Fatal("Expected %d deployments, got %d", 2, len(postUninstallStatus.Deployments))
^
```

mantle: clean up kola/tests/rpmostree/deployments

---

mantle/kola/tests/ostree/basic.go

This cleans up kola/tests/ostree/basic.go:
```
kola/tests/ostree/basic.go:217:4: printf: Fatalf format %d has arg osRemoteListSplit of wrong type []string (govet)
c.Fatalf(`Did not find expected amount of ostree remotes: %q. Expected %d`, string(osRemoteListOut), osRemoteListSplit)
^
```

mantle: clean up kola/tests/ostree/basic

---

mantle/kola/tests/ignition/resource.go

This cleans up kola/tests/ignition/resource.go:
```
kola/tests/ignition/resource.go:384:11: Error return value of `w.Write` is not checked (errcheck)
w.Write([]byte("kola-http"))
^
kola/tests/ignition/resource.go:394:15: Error return value of `r.ReadFrom` is not checked (errcheck)
r.ReadFrom(bytes.NewBufferString("kola-tftp"))
```
Since the errors were not dealt with before, just make tiny changes to pass golang-ci lint.

mantle: clean up kola/tests/ignition/resource

---

src/cmd-buildextend-metal
src/create_disk.sh
src/image-default.yaml

Followup to https://github.com/coreos/coreos-assembler/pull/1787/commits/b769f56560b099396f84a9ce694ae3586ddcfe41
All of the parsing and re-parsing of the image YAML into an argument
list for `create_disk.sh` was messy.  Particularly things like
having the defaults hardcoded in the middle of code and using `NONE`
for the empty value, etc.
Add almost everything into JSON that we pass in so we don't need
to "stringify" everything.
The main thing I didn't touch here was kargs but that should also
be better with this because we can cleanly pass an array.

More draining of create_disk args into JSON passing

---

mantle/cmd/kola/kola.go
mantle/kola/tests/rhcos/upgrade.go

Added a test for the migration of rootfs from crypt_rootfs with dm-linear mapping to the non LUKS root filesystem which will
be the default going forward. This test will only be useful so long as we upgrade from pre 4.7 systems to 4.7 and beyond. This
is good to have for also testing multi-arch upgrades which can now be enabled as part of the pipeline.

kola: support basic (non LUKS) rhcos upgrade test for all arches

---

mantle/network/journal/format.go

This cleans up network/journal/format.go:
```
network/journal/format.go:60:17: Error return value of `io.WriteString` is not checked (errcheck)
io.WriteString(s.w, "-- Reboot --\n")
```

mantle: clean up network/journal

---

mantle/network/ssh.go

This cleans up network/ssh.go:
```
network/ssh.go:117:23: Error return value of `agent.ServeAgent` is not checked (errcheck)
go agent.ServeAgent(a, conn)
^
```

mantle: clean up network/ssh

---

mantle/network/mockssh/mockssh.go

This cleans up network/mockssh/mockssh.go:
```
network/mockssh/mockssh.go:161:20: Error return value of `newChannel.Reject` is not checked (errcheck)
newChannel.Reject(ssh.UnknownChannelType, "unknown channel type")
^
network/mockssh/mockssh.go:181:13: Error return value of `req.Reply` is not checked (errcheck)
req.Reply(false, nil)
^
network/mockssh/mockssh.go:187:14: Error return value of `req.Reply` is not checked (errcheck)
req.Reply(false, nil)
^
network/mockssh/mockssh.go:190:14: Error return value of `req.Reply` is not checked (errcheck)
req.Reply(true, nil)
^
network/mockssh/mockssh.go:197:14: Error return value of `req.Reply` is not checked (errcheck)
req.Reply(false, nil)
network/mockssh/mockssh.go:201:14: Error return value of `req.Reply` is not checked (errcheck) …
```

mantle: clean up network/mockssh/mockssh

---

mantle/lang/bufpipe/pipe_test.go

This cleans up lang/bufpipe/pipe_test.go:
```
lang/bufpipe/pipe_test.go:268:10: Error return value of `w.Write` is not checked (errcheck)
w.Write([]byte{})
^
lang/bufpipe/pipe_test.go:272:13: Error return value of `io.ReadFull` is not checked (errcheck)
io.ReadFull(r, b[0:2])
^
lang/bufpipe/pipe_test.go:279:10: Error return value of `w.Write` is not checked (errcheck)
w.Write(nil)
^
lang/bufpipe/pipe_test.go:283:13: Error return value of `io.ReadFull` is not checked (errcheck)
io.ReadFull(r, b[0:2])
```

mantle: clean up lang

---

mantle/network/ntp/protocol_test.go

This cleans up network/ntp/protocol_test.go:
```
network/ntp/protocol_test.go:90:18: Error return value of `h.MarshalBinary` is not checked (errcheck)
h.MarshalBinary()
^
network/ntp/protocol_test.go:100:20: Error return value of `h.UnmarshalBinary` is not checked (errcheck)
h.UnmarshalBinary(d.Raw)
^
network/ntp/protocol_test.go:111:20: Error return value of `h.UnmarshalBinary` is not checked (errcheck)
h.UnmarshalBinary(d)
^
```

mantle: clean up network/ntp

---

mantle/kola/tests/ignition/security.go

This cleans up kola/tests/ignition/security.go:
```
kola/tests/ignition/security.go:159:10: Error return value of `w.Write` is not checked (errcheck)
w.Write(customFile)
```

mantle: clean up kola/tests/ignition/security

---

mantle/network/nsdialer.go

This cleans up network/nsdialer.go:
```
network/nsdialer.go:49:14: Error return value of `nsExit` is not checked (errcheck)
defer nsExit()
^
```

mantle: clean up network/nsdialer

---

mantle/kola/tests/misc/network.go

This cleans up kola/tests/misc/network.go:
```
kola/tests/misc/network.go:150:10: Error return value of `m.Reboot` is not checked (errcheck)
m.Reboot()
```

mantle: clean up kola/tests/misc

---

src/cmd-tag

Much more convenient than manually calling `delete --tag` for every tag.

cmd-tag: support `delete --all`

---

mantle/network/mockssh/mockssh_test.go

This cleans up network/mockssh/mockssh_test.go:
```
network/mockssh/mockssh_test.go:34:9: Error return value of `s.Exit` is not checked (errcheck)
s.Exit(0)
^
network/mockssh/mockssh_test.go:50:9: Error return value of `s.Exit` is not checked (errcheck)
s.Exit(42)
^
network/mockssh/mockssh_test.go:89:9: Error return value of `s.Exit` is not checked (errcheck)
s.Exit(0)
^
network/mockssh/mockssh_test.go:111:17: Error return value of `io.WriteString` is not checked (errcheck)
io.WriteString(s.Stdout, "Stdout")
^
network/mockssh/mockssh_test.go:112:17: Error return value of `io.WriteString` is not checked (errcheck)
io.WriteString(s.Stderr, "Stderr")
network/mockssh/mockssh_test.go:113:9: Error return value of `s.Exit` is not checked (errcheck)
s.Exit(0)
^ …
```

mantle: clean up network/mockssh/mockssh_test

---

mantle/build

Right now, we're building kolet in the cosa buildroot and then copying
it into the target system. This worked for a while by pure chance,
because it's really easy to hit a library mismatch between the cosa and
target environments. And now we do hit this case when using f33 to build
RHCOS due to symbol versioning in glibc.
The proper way to fix this would be for cosa to build kolet in a
buildroot that matches the target OS. This is resolvable, though it
would significantly affect the developer experience because devs would
now have to also download and maintain the target buildroot.
Target-specific buildroots are still something valuable to have (because
for dev and CI you do want a matching buildroot when hacking on host
components) but purely for cosa given that kolet is the only …

kola: build kolet statically

---

mantle/platform/api/gcloud/pending.go

This cleans up platform/api/gcloud/pending.go:
```
platform/api/gcloud/pending.go:57:30: S1012: should use `time.Since` instead of `time.Now().Sub` (gosimple)
err := p.Progress(p.desc, time.Now().Sub(start), op)
```

mantle: clean up platform/api/gcloud/pending

---

mantle/platform/api/gcloud/compute.go

This cleans up platform/api/gcloud/compute.go:
```
platform/api/gcloud/compute.go:29:11: Error return value of `rand.Read` is not checked (errcheck)
rand.Read(b)
^
```

mantle: clean up platform/api/gcloud/compute

---

mantle/platform/api/gcloud/api.go

This cleans up platform/api/gcloud/api.go:
```
platform/api/gcloud/api.go:73:11: ineffectual assignment to `err` (ineffassign)
client, err = auth.GoogleClientFromJSONKey(b)
^
platform/api/gcloud/api.go:82:15: SA1019: compute.New is deprecated: please use NewService instead. To provide a custom HTTP client, use option.WithHTTPClient. If you are using google.golang.org/api/googleapis/transport.APIKey, use option.WithAPIKey with NewService instead.  (staticcheck)
capi, err := compute.New(client)
^
```

mantle: clean up platform/api/gcloud/api

---

mantle/platform/api/azure/storage_mit.go

This cleans up platform/api/azure/storage_mit.go:
```
platform/api/azure/storage_mit.go:190:11: ineffectual assignment to `err` (ineffassign)
md5Hash, err := getBlobMD5Hash(client, containerName, blobName)
^
```

mantle: clean up platform/api/azure/storage_mit

---

mantle/platform/api/do/api.go

This cleans up platform/api/do/api.go:
```
platform/api/do/api.go:167:18: Error return value of `a.DeleteDroplet` is not checked (errcheck)
a.DeleteDroplet(ctx, dropletID)
^
platform/api/do/api.go:264:16: Error return value of `a.DeleteImage` is not checked (errcheck)
a.DeleteImage(ctx, imageID)
^
```

mantle: clean up platform/api/do

---

mantle/platform/api/aws/ec2.go

This cleans up platform/api/aws/ec2.go:
```
platform/api/aws/ec2.go:203:23: Error return value of `a.TerminateInstances` is not checked (errcheck)
a.TerminateInstances(ids)
^
```

mantle: clean up platform/api/aws

---

mantle/platform/api/azure/instance.go

This cleans up platform/api/azure/instance.go:
```
platform/api/azure/instance.go:150:22: Error return value of `a.TerminateInstance` is not checked (errcheck)
a.TerminateInstance(name, resourceGroup)
^
```

mantle: clean up platform/api/azure/instance

---

mantle/cosa/schema_test.go

This cleans up cosa/schema_test.go:
```
cosa/schema_test.go:34:5: SA5011: possible nil pointer dereference (staticcheck)
b.Name = ""
^
```

mantle: clean up cosa

---

mantle/platform/api/azure/network.go

This cleans up platform/api/azure/network.go:
```
platform/api/azure/network.go:116:3: SA4004: the surrounding loop is unconditionally terminated (staticcheck)
return publicIP, *conf.PrivateIPAddress, nil
^
```
I think it's great before changes. Added `else` to pass golang-ci lint.

mantle: clean up platform/api/azure/network

---

src/cmd-upload-oscontainer
src/download-extensions

Pairs with openshift/os#455
Add an `oscontainer.yaml` which allows configuring (currently) just
the `FROM` line equivalent.  This helps keep things declarative
in the config instead of part of the pipeline.
And since extensions are now a core part of OpenShift 4 (particularly RT kernel)
which also uses the oscontainer, let's lift the logic to generate
those bits of the oscontainer into this repo and out of the config git.
Both of these are part of the general philosophy we've had that:
- config git is declarative config
- coreos-assembler is the mechanism
- a pipeline just scripts coreos-assembler in a way that's
easy to reproduce with plain podman too

  upload-oscontainer: Support oscontainer.yaml and extensions.yaml

---

.cci.jenkinsfile
Dockerfile
build.sh

It's in testing now, and the blocker that was preventing us from moving
is gone (see https://github.com/coreos/coreos-assembler/issues/1496).

Move to Fedora 33

---

mantle/platform/machine/aws/machine.go

This cleans up platform/machine/aws/machine.go :
```
platform/machine/aws/machine.go:152:15: Error return value of `f.WriteString` is not checked (errcheck)
f.WriteString(am.console)
^
```

mantle: clean up platform/machine/aws

---

gangplank/ocp/cosa-pod.go

When creating the pods in podman mode we need to override cosa's
entrypoint to run `gangplank builder` (just like the inCluster pod
creation) so gangplank can run correctly.

gangplank: override entrypoint and command for podman mode

---

mantle/platform/journal.go

This cleans up platform/journal.go:
```
platform/journal.go:96:18: Error return value of `j.recorder.Wait` is not checked (errcheck)
j.recorder.Wait() // Just need to consume the status.
^
```
The error is not vital, so just assign to blank in order to pass the golang-lint ci.

mantle: clean up platform/journal

---

mantle/platform/machine/openstack/machine.go

This cleans up platform/machine/openstack/machine.go:
```
platform/machine/openstack/machine.go:131:15: Error return value of `f.WriteString` is not checked (errcheck)
f.WriteString(om.console)
^
```

mantle: clean up platform/machine/openstack/machine

---

mantle/platform/platform.go

This cleans up platform/platform.go:
```
platform/platform.go:276:2: ineffectual assignment to `out` (ineffassign)
out, stderr, err := m.SSH(fmt.Sprintf("sudo mkdir -p %s", dir))
^
platform/platform.go:308:2: ineffectual assignment to `out` (ineffassign)
out, stderr, err := m.SSH(fmt.Sprintf("sudo mkdir -p %s", shellquote.Join(destdir)))
^
```

mantle: clean up platform/platform

---

src/cmd-build
src/cmdlib.sh

Apparently using `$(...)` inside a heredoc loses `set -e`; another
spectacularly evil shell script trap.  Noticed in
https://github.com/coreos/coreos-assembler/issues/1954
We do want to fail if any of these commands fail, rather than
emitting invalid JSON.

cmdlib: Run commands external to inline file generation

---

mantle/sdk/download.go
mantle/update/generator/full.go
mantle/update/generator/generator_test.go
mantle/update/generator/info.go
mantle/update/operation.go
mantle/update/updater.go

This cleans up `os.SEEK_SET is deprecated` in update package:
```
SA1019: os.SEEK_SET is deprecated: Use io.SeekStart, io.SeekCurrent, and io.SeekEnd.  (staticcheck)
```

mantle: clean up update

---

mantle/platform/machine/qemuiso/cluster.go

This cleans up platform/machine/qemuiso/cluster.go:
```
platform/machine/qemuiso/cluster.go:115:16: Error return value of `builder.AddIso` is not checked (errcheck)
builder.AddIso(qc.flight.opts.IsoPath, "")
^
```

mantle: clean up platform/machine/qemuiso

---

mantle/platform/local/cluster.go

This cleans up platform/local/cluster.go:
```
platform/local/cluster.go:40:25: func `(*LocalCluster).hostIP` is unused (unused)
platform/local/cluster.go:56:14: Error return value of `nsExit` is not checked (errcheck)
defer nsExit()
^
```

mantle: clean up platform/local/cluster

---

src/cmdlib.sh

While we wait for a more complete solution for #1954 in the form of
changes to the PSI cluster, let's use an alternative way to determine
the size of the tarball.
The `find` syntax was suggested by ShellCheck - https://github.com/koalaman/shellcheck/wiki/SC2012

cmdlib: use find instead of stat

---

.dockerignore

I ran into a gnarly error building the image locally when I had a
`mantle/_kola_temp` directory present.  The tail of the message:
`error generating tar header for /mantle/_kola_temp/agent.1924868 (): archive/tar: sockets not supported`
Using dockerignore to exclude the directory prevents this error from
being encountered.

dockerignore: exclude kola_temp directory

---

mantle/platform/machine/do/cluster.go
mantle/platform/machine/openstack/cluster.go
mantle/platform/machine/packet/cluster.go

This cleans up platform/machine:
```
platform/machine/do/cluster.go:100:11: Error return value of `rand.Read` is not checked (errcheck)
rand.Read(b)
^
platform/machine/packet/cluster.go:124:11: Error return value of `rand.Read` is not checked (errcheck)
rand.Read(b)
^
platform/machine/openstack/cluster.go:92:11: Error return value of `rand.Read` is not checked (errcheck)
rand.Read(b)
^
```
Put the same issue into one PR to make it clear. 
Since it's no harm to log the error with detailed information, update to log the errors.

mantle: clean up platform/machine

---

mantle/platform/machine/gcloud/machine.go

This cleans up platform/machine/gcloud/machine.go:
```
platform/machine/gcloud/machine.go:110:15: Error return value of `f.WriteString` is not checked (errcheck)
f.WriteString(gm.console)
^
```

mantle: clean up platform/machine/gcloud

---

mantle/platform/local/flight.go

This cleans up platform/local/flight.go:
```
platform/local/flight.go:70:14: Error return value of `nsExit` is not checked (errcheck)
defer nsExit()
^
platform/local/flight.go:108:24: func `(*LocalFlight).newListenPort` is unused (unused)
```

mantle: clean up platform/local/flight

---

mantle/sdk/download.go
mantle/sdk/repo.go
mantle/sdk/verify.go

This cleans up sdk package:
```
sdk/download.go:48:15: SA1019: storage.New is deprecated: please use NewService instead. To provide a custom HTTP client, use option.WithHTTPClient. If you are using google.golang.org/api/googleapis/transport.APIKey, use option.WithAPIKey with NewService instead.  (staticcheck)
api, err := storage.New(client)
^
sdk/download.go:114:29: SA1019: os.SEEK_SET is deprecated: Use io.SeekStart, io.SeekCurrent, and io.SeekEnd.  (staticcheck)
if _, err := dst.Seek(0, os.SEEK_SET); err != nil {
^
sdk/download.go:131:30: SA1019: os.SEEK_SET is deprecated: Use io.SeekStart, io.SeekCurrent, and io.SeekEnd.  (staticcheck)
if _, err := dst.Seek(pos, os.SEEK_SET); err != nil {
^
sdk/download.go:180:6: `getUrlStream` is unused (deadcode)
func getUrlStream(url string, client …
```

mantle: clean up sdk

---

mantle/platform/api/esx/api.go

This cleans up platform/api/esx/api.go:
```
platform/api/esx/api.go:448:2: ineffectual assignment to `nets` (ineffassign)
nets = append(nets, types.OvfNetworkMapping{
^
```

mantle: clean up platform/api/esx

---

Makefile
ci/prow.sh
gangplank/Makefile

The golangci-lint can be expensive and our arbitrary `--timeout 5m`
is causing builds to fail in quay.io.
xref https://github.com/coreos/coreos-assembler/issues/1972
Add a `ci/prow.sh` so we can only do the static analysis on pull
requests, separate from container builds from the `Dockerfile`.

Split off `make staticanalysis`, add ci/prow.sh

---

mantle/cmd/ore/gcloud/promote-image.go

This cleans up cmd/ore/gcloud/promote-image.go. The issue in gcloud is
fixed. Drop the nolint comments in cmd/ore/gcloud/promote-image.go
after the errors are gone.

mantle: clean up cmd/ore/gcloud/promote-image.go

---

mantle/platform/qemu.go
src/libguestfish.sh

POWER build are failing with the error:
Error: Firmware Assisted Non-Maskable Interrupts(FWNMI) not supported by
KVM.
For more info check QEMU #ec010c00665

Disable FWNMI for POWER

---

mantle/kola/harness.go
mantle/kola/tests/ignition/luks.go
mantle/kola/tests/rhcos/upgrade.go
mantle/platform/qemu.go

With the move to f33, TPM is supported in qemu for ppc64le and aarch64. s390x does not support a
TPM backend, so that is still disabled. Had to adjust memory for aarch64 because it also uses 64K
pages.

kola/tests: Enable Tang tests for ppc64le and aarch64

---

src/coreos-assembler

For example when using `cosa build-fast`, a useful workflow is to
provide `COSA_DIR=` when working on a single project.

src/coreos-assembler: Preserve environment variables

---

src/create_disk.sh
src/grub.cfg

If `/boot` is on a RAID, have GRUB read from that RAID as much as possible, rather than a component partition.  This allows us to be more resilient to bad sectors or flaky drives.
Enable RAID support in the BIOS GRUB image.
Fixes [RHBZ 1909455](https://bugzilla.redhat.com/show_bug.cgi?id=1909455).  Discussion in coreos/fedora-coreos-config#718 and design doc update in coreos/enhancements#4.  Followup in https://github.com/coreos/fedora-coreos-tracker/issues/702.

grub: read from md/md-boot if it exists

---

src/create_disk.sh

If we're doing e.g. `buildextend-qemu` against a build which isn't the
latest one, `create_disk` would still deploy the latest one (or more
accurately, whatever the ref is currently pointing to in the `tmp/repo`
OSTree repo). This used to work, so we probably regressed at some point.
Let's just always pull by commit, and then in the remote case create a
remote ref for it.

create_disk: fix ref handling when not targeting latest build
