coreos/coreos-assembler

- build.sh
This way we can use kola from this container - making a bit more
like an SDK.
> Build/include kola, and use from arithx's PR

- build.sh
coreos/mantle#888 merged, switch back to upstream mantle
> build.sh: switch to upstream mantle

- build.sh
These were dropped out during the switch to using variables for packages
in #16. Fix this by going one step further and defining the list of
packages only once.
> build: Put back awscli and jq

- build.sh
For now, I don't want to have to wait until we do an rpm-ostree official
release and plumb that through all of the koji/bodhi stuff until
we have it in our `:latest` assembler image.  I've been landing fixes
in YAML treefile parsing for example that I want to use right now.
This may change over time of course; perhaps down the line things
will settle again and we'll switch back to just grabbing latest stable.
Implementation notes:
- `xargs` which was used by the package installs
is part of `findutils` which apparently we were somehow
pulling in indirectly before
- We hadn't explicitly listed `rpm-ostree` in the packages list
> build: Use FAHC (git master of ostree/rpm-ostree)

- README.md
The latest is now on `:latest`.
> README: Fix container ref

- src/cmd-clean
I don't want to accumulate too much history locally.  Also just
useful in general when testing.
> clean: New verb

- README.md
- Add `--userns=host` since apparently this helps Docker
- Fix the config src git
- Document the `run` command, inputs etc.
> README: Various additions and fixes

- build.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1625641
> build: yum distro-sync before doing anything else

- build.sh
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1625641 for
us.
> build: Distro-sync before installing

- src/cmd-oscontainer
> oscontainer: Also unbuffer stdout

- src/cmd-build
I'm debugging something and this would have been useful.
> cmd-build: Print previous build

- RELEASE.txt
This should help us make our releases more consistent and also
add instructions for what to do when things get more complex.
> RELEASE: Add RELEASE.txt file for instructions

- Makefile
- tests/check.sh
Just does syntax verification for now.
> Add `make check`

- src/prune_builds
> prune: Don't crash on initial commit

- build.sh
It's nearly free at the moment, so we might as well.
> build.sh: Run `make check` during container build

- src/cmdlib.py
- src/prune_builds
> Factor out a new Python cmdlib

- README-design.md
- README.md
Overdue, I know I need to write more docs.
> Add a README-design.md

- .travis.yml
Github status is how things should work.
> travis: Disable email notifications

- src/cmd-buildextend-openstack
> buildextend-openstack: Fix `checksum` → `sha256`

- src/cmdlib.sh
This fixes up a few issues introduced by the shellcheck changes we did recently. See individual commit messages for explanations.
> unpriv: fixup a few regressions

- src/cmd-init
- init: add some checking for --installerdir 
- init: allow --force with --installerdir
> init: `--installerdir` enhancements

- src/libguestfish.sh
Since that's an expected scenario.
> libguestfish: Silence error if no LABEL=var

- src/virt-install
Also update links to ignition-dracut repo in comments
Depends on: https://github.com/coreos/ignition-dracut/pull/30
> Rename `/boot/coreos-firstboot` to `/boot/ignition-firstboot`

- src/cmd-build
- src/cmd-prune
- src/prune_builds
Adds timestamp support to `rhcos` branch
> pull in PR #224

- src/cmdlib.sh
So one major issue with caching the VM is that it doesn't carry over
well with updates of the container image: the `supermin.build/kernel`
symlink points to the `/lib/modules/<kver>/vmlinuz` file, which of
course will be broken as soon as the container is updated.
We could make caching smarter to handle this but... I don't know,
maintaining this cache invalidation logic doesn't seem worth it if
building it from scratch is not that much overhead.
This also makes e.g. hacking on ostree/rpm-ostree easier.
> cmdlib: Always rebuild supermin VM

- src/cmd-buildextend-openstack
- src/cmdlib.py
Split out of #246. See individual commit messages.
> Miscellaneous patches

- src/deps.txt
This is a new dep introduced by #252.
> deps.txt: Add python3-pytz

- src/cmdlib.py
- Add `load_json`
- Add `fatal` as is in cmdlib.sh
- Update `info` as is in cmdlib.sh
- Add docstrings for developer understanding
> src/cmdlib.py: Closer in line to cmdlib.sh

- src/cmd-run
This was part of the initial `run` code merged here; probably
I didn't fully finish testing it.
To make this work need to provide the virtio device too.
> cmd-run: Fix --srv

- build.sh
See 337c8dbdd70a2d8e7b3ab6d0548c61be474e5a71
> build.sh: switch cmd-oscontainer to python2

- src/cmdlib.sh
This reverts commit 0bec0caa8a0c235283d32a88c2df37c727cc84b2, reversing
changes made to 6c20f9378658833d6f72189ba4f01899cce2a755.
> Revert "Merge pull request #335 from darkmuggle/mirror_iso"

- README.md
Adds note regarding changes in #145 - personally found this helpful
when testing Ignition changes in FCOS.
> README: Add note on overriding RPMs locally

- src/cmd-buildextend-ec2
Backport of #385 onto 0.4.0-maipo branch.
> buildextend-ec2: Add --name-suffix [from #385]

- README.md
Don't reference Anaconda stuff.
> README.md: Update for image.yaml

- src/cmd-buildextend-installer
WIP because I haven't tested this yet. Just checking if you agree with the approach.
> buildextend-installer: make installer multi-arch aware

- src/supermin-init-prelude.sh
(cherry picked from commit d5b26d69a1f2b350525b7e0b9077cf49d21e96b9)
> src/supermin-init-prelude.sh: mount /dev/shm

- src/virt-install
> virt-install: Silence ostree ls on EFI dir

- src/cmd-build
- src/gf-anaconda-cleanup
- src/virt-install
We don't need this anymore, anyone who wants to do something different
can fork cosa for now.
Prep for further changes.
> Remove Kickstart support

- src/cmd-build
- src/cmd-buildextend-ec2
- src/cmd-buildextend-openstack
- src/cmd-buildextend-vmware
- src/gf-platformid
fixes for https://github.com/coreos/coreos-assembler/issues/428
Quote from @dustymabe 
> Any work for this should not be merged until we have switched to ignition spec 3x.
> gf-oemid: Rename gf-oemid to gf-platformid

- src/cmd-buildextend-aws
- src/cmd-buildextend-ec2
- src/coreos-assembler
- src/gf-platformid
Requires, and is required by, Ignition 2 (and Afterburn if used).
> *: rename "ec2" platform ID to "aws"

- src/cmd-run
This reverts commit b6df6c75fbf33ad5443cb23778abe34c3a80be06.
> Revert "cmd-run: update Ignition config to spec 3.0.0"

- src/oscontainer.py
When doing `podman pull` and `skopeo inspect`, you may need to provide
credentials to access the registry.  The `--authfile` option allows
users to pass in a `config.json` style file.  Alternately, if
`REGISTRY_AUTH_FILE` is configured, that will be used for
`--authfile`.
> src/oscontainer: add option for specifying authfile

- src/oscontainer.py
When doing `podman pull|push` and `skopeo inspect`, you may need to provide
credentials to access the registry.  The `--authfile` option allows
users to pass in a `config.json` style file.  Alternately, if
`REGISTRY_AUTH_FILE` is configured, that will be used for
`--authfile`.
(cherry picked from commit b7479dca8ce17852ea11438b4cc990f4853dc3e9)
> [backport] src/oscontainer: add option for specifying authfile

- src/gf-anaconda-cleanup
- src/virt-install
People keep not realizing they exist, so let's print
a message about it.
> virt-install: Tell user where to find anaconda logs

- src/gf-anaconda-cleanup
This is a backport of #492 and #494
> [backport] cleanup of / and /var

- Dockerfile.dev
- README.md
- src/virt-install
A few minor fixes/updates in passing.
> Minor doc updates/fixes

- src/cmd-build
- src/cmd-init
- src/cmdlib.sh
- src/coreos-assembler
- src/virt-install
> Prep patches for split metal

- README-devel.md
- README.md
> README[-devel].md: Docs for updating mantle

- README.md
- build-process-mermaid.md
- build-process.svg
After reading the setup steps for the first time, I didn't have an understanding of how the coreos-assembler works. But after watching this talk 
[DevConf talk: Fedora CoreOS Build Tooling by Andrew Jeddeloh](https://www.youtube.com/watch?v=qg3tnxHZu80)
It helps to understand the build process for anyone getting started with the cores-assembler setup process. I think it would be helpful to add this diagram.
> adding build process illustration

- src/cmd-buildextend-gcp
- src/coreos-assembler
This enables the ability to produce GCP Artifacts.
> GCP: add cmd-buildextend-gcp for uploads to Google

- src/cmd-buildextend-gcp
- src/coreos-assembler
Add GCP support to the 4.1 branch.
(cherry picked from commit 690348e4d94058f251afcbca500fc0e0eb9347e7)
> buildextend-gcp: New command to upload to GCP.

- src/cmd-build
> cmd-build: Fix new builds from scratch

- src/cmd-buildextend-aws
- src/cmd-buildextend-installer
- src/cmd-buildextend-openstack
- src/cmd-buildextend-vmware
- src/cmd-buildprep
- src/cmd-buildupload
- src/cmd-compress
- src/cmd-tag
- src/cmdlib.py
- src/coreos-assembler
- src/prune_builds
This is mostly an "upstreaming" of some internal code we had in the
RHCOS pipeline. Among other tweaks, I made it more generic so we could
feasibly support other remote types in the future.
> buildupload: New command to upload builds

- src/cmd-run
Add options to make running in uefi and uefi with secure boot easier
> cmd-run: add --uefi and --uefi-secure options

- src/create_disk.sh
- src/deps.txt
- src/grub.cfg
- src/vmdeps.txt
Use the already-signed shim and fedora grub efi images.
> src/create_disk: add shim for secure boot

- src/cosalib/build.py
Instead of recreating this in each subclass, let's call methods when needed.
> cosalib/build.py: Add temp work directory functionality

- src/cmdlib.sh
This speeds up things running in supermin. It's not really noticable on
my laptop but it is when running on a many-cored arm server.
> src/cmdlib: use more cores with supermin

- src/cmd-buildextend-gcp
Backport of https://github.com/coreos/coreos-assembler/pull/582
> gcp: Always --force

- src/cmd-buildextend-gcp
Backport of https://github.com/coreos/coreos-assembler/pull/584
> gcp: Remove other uses of `force` arg

- src/cmdlib.sh
We recently added `devel` to one of our pipelines, teach
the version detection about it.
> cmdlib: Detect rhcos-devel

- src/cmd-build
- src/create_disk.sh
- src/grub.cfg
Fix build failures looking for a now nonexistent anaconda. Fix grub getting lost with more than one disk.
> Misc fixes

- bottlecap-shim
- src/cmd-build
- src/cmd-buildextend-metal
- src/create_disk.sh
> Remove anaconda on arm

- .travis.yml
- Dockerfile.dev
- Makefile
- pytest.ini
- src/cmdlib.py
- src/cosalib/build.py
- src/deps.txt
- test-requirements.txt
- tests/test_cmdlib.py
https://github.com/coreos/coreos-assembler/pull/610 through a container
> Better travis testing in container

- src/cmd-buildextend-azure
- src/coreos-assembler
> Azure: add cmd-buildextend-azure

- src/cmd-buildextend-azure
(cherry picked from commit 64ff053e4b70922fcd32b4fc0a36657b47307eef)
> cmd-buildextend-azure: use final path for the vhd in build meta.

- src/cmd-buildextend-azure
(cherry picked from commit 91a87fd50d67db91b4ece50788110fdf65f2e0c6)
> src/cmd-buildextend-azure: fix location argument for ore

- Makefile
- src/oscontainer.py
Backport of https://github.com/coreos/coreos-assembler/pull/655
> 4.2 backport oscontainer fixing

- src/oscontainer.py
Backport of #661
/cc @jasinner
> src/oscontainer.py: Add pkglist.txt to container root

- src/oscontainer.py
> oscontainer: Sort NEVRAs before dumping pkglist.txt

- README.md
This should be higher up on the README.md before we start talking about
how to rebuild it locally for development purposes.
> README.md: Mention quay.io pullspec

- doc/aws.md
- src/cmd-buildextend-aws
Extracted from some internal RHCOS docs.  Just trying to upstream
stuff.
> Add a doc/aws.md

- .cci.jenkinsfile
- src/cmd-kola
This was causing issues in the FCOS pipeline.
> cmd-kola: Actually handle --output-dir

- src/cmd-run
Depends on https://github.com/coreos/coreos-assembler/pull/681
Not sure if there's a better way to do this.
> Better console

- src/cmd-koji-upload
(cherry picked from commit 16c193e75a6cffe88826259510cf03dfef3db038)
> src/cmd-koiji-upload: fix issue with renaming upload

- build.sh
> build.sh: check if /boot/efi is present[backport]

- src/cmd-fetch
- cmd-fetch: add --write-lockfile-to option
- cmd-fetch: make --update-lockfile be non-interactive
> cmd-fetch: add lockfile option, make non-interactive

- src/deps-s390x.txt
Add s390x dependencies
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
> deps: add s390x dependencies

- README.md
Map the rest of the UIDs in the namespace so we have full coverage.
See https://github.com/debarshiray/toolbox/commit/cfcf4eb31e14b3a300804840d315c62bc32e15ae for more details.
> README: update --uidmap call on podman invocation

- .github/ISSUE_TEMPLATE/feature.md
Adds a feature template per meeting.
/cc @darkmuggle @ajeddeloh @lucab @vrutkovs @arithx
> Add feature template

- src/cmd-buildextend-metal
- src/cmd-run
- src/cmdlib.sh
- src/image-base.ks
- src/virt-install
This helps to get full console output on respective arches in anaconda,... aiding in debugging.
> virt-install: use correct console on each arch

- src/cmdlib.sh
We switched FCOS a while ago, RHCOS now uses `overlay.d` as well.
Let's ensure people have ported over.
> build: Drop support for overlay/ dir

- src/cmdlib.sh
This way (1) we don't require users to play around with lockfiles, and
(2) we ensure rpm-ostree will pick the override RPMs, even if their
NEVRAs are lower than in the other repos.
Closes: #740
> Synthesize lockfile for local RPM overrides

- src/cmdlib.sh
> cmdlib: Fix RPM overrides handling

- src/cmd-buildextend-azure
- buildextend-azure: fix meta.json update
- buildextend-azure: add 'azure' to the image filename
> a few fixes for azure

- src/coreos-assembler
Otherwise, it's like an easter egg command.
> entrypoint: add buildextend-live to command list

- src/cmd-aws-replicate
> cmd-aws-replicate: update cmdlib imports

- src/cosalib/cmdlib.py
> Minor prep patches for `cosa sign robosignatory`

- tests/test_cosalib_meta.py
> tests/cosalib_meta: make multi-arch() aware

- Makefile
- src/cmd-aws-replicate
- src/cmd-buildextend-aws
- src/cmd-buildextend-azure
- src/cmd-buildextend-gcp
- src/cmd-buildextend-installer
- src/cmd-buildextend-openstack
- src/cmd-buildextend-vmware
- src/cmd-buildprep
- src/cmd-compress
- src/cmd-dev-overlay
- src/cmd-meta
- src/commitmeta_to_json
- src/estimate-commit-disk-size
- src/incomplete-hack-ign-3to2
- src/prune_builds
- src/virt-install
- src/write-commit-object
Several imports are no longer used
Worked on RHCOS pipeline build
> Run flake8 tests on all python files

- README-devel.md
Address review comments, also just try to clarify more.
> README-devel.md: A few tweaks to overrides doc

- src/create_disk.sh
- src/libguestfish.sh
Fully tested against LUKS and non-LUKS roots.
> Fix regressions in LUKS devices.

- README-devel.md
> README-devel.md: Document cosa run --srv dev workflow

- src/create_disk.sh
Minor typo fix for aarch64 builds
> Fix typo to get aarch64 working

- src/cmd-tag
Noticed this while trying to use it.
> cmd-tag: Fix Builds library import

- src/create_disk.sh
Deduplicate this code; prep for a change to use the target EFI binaries
for RHCOS.
> create_disk: Dedup UEFI code for x86_64|aarch64

- src/cmd-compress
So it's easier to time which ones are taking a long time.
> compress: Print when we complete compression of a file

- src/cmd-remote-prune
- src/cosalib/azure.py
- src/cosalib/prune.py
This adds new params to cmd-remote-prune and cosalib/prune to remove 
Azure images via ore
> Remote prune: suport azure

- src/cmd-run
This reverts commit 28ddfde918c97672427223833ffc159f9c43611e.
There wasn't full consensus on this yet.
> Revert "run: If not specified, randomly pick bios/uefi/uefi-secure"

- build.sh
For production ready s390x support through the pipeline, we need to patch guestfs
for supporting generation of DASD metal images and also a patched Fedora build for
anaconda with zipl support. Refer to:
Guestfish support for DASD devices:
https://www.redhat.com/archives/libguestfs/2019-November/msg00025.html
Anaconda with zipl support:
https://bugzilla.redhat.com/show_bug.cgi?id=1741908
Builds generated by @ausil
> [rhcos-4.2-multiarch]Use patched libguestfs build and anaconda build to support s390x prod builds

- src/cmd-prune
- src/cmd-tag
- src/cosalib/builds.py
See individual commit messages. The most important one is:
https://github.com/coreos/coreos-assembler/commit/c03db45f1750e6aafdc3f524927b919d603809cd
> Some prune/tag fixes and enhancements

- src/oscontainer.py
As of recently, the podman stack better supports being
invoked recursively.  Hence, it works to just
`podman unshare cosa oscontainer build ...` inside an existing
container for me.
We can hence now just write to the primary container storage, if
we want to - and I think doing so is more ergonomic for development/testing
at least.  And we could consider doing this in prod builds as well;
conceptually the build user's homedir is transient anyways.
> oscontainer: Don't require a workdir

- src/create_disk.sh
I've noticed there's always a `rootfs/` dir leftover in my cosa workdir.
This is actually getting created by `create_disk.sh`. Just move it into
`tmp/` and clean up after ourselves (and make it a variable while we're
here).
> create_disk.sh: Move rootfs mountpoint to tmp/

- README.md
> Some README tweaks

- src/oscontainer.py
For RHCOS we plan to ship additional RPMs inside the oscontainer
that an admin can optionally install.
> oscontainer: Support injecting additional content

- src/cmd-koji-upload
(cherry picked from commit 5b8667bdea69faf34d2083e7fe067509b32eb0ef)
> [rhcos-4.3] cmd-koji-upload: fix regression with upload types

- build.sh
Now that https://bugzilla.redhat.com/show_bug.cgi?id=1770304 is fixed.
> build: Unpin kernel

- src/deps.txt
- src/vmdeps.txt
So what's going on is a bit more obvious.
> deps: Add comments to the top of the files

- src/supermin-init-prelude.sh
Prep for a rojig change which will "wrap" itself via supermin
and this allows it to detect that.
> build: Add /etc/cosa-supermin

- src/cmd-kola
Let's at least ensure we boot with nvme and UEFI etc.
> kola: Add --basic-qemu-scenarios

- src/cmd-kola
We do this automatically in mantle now
https://github.com/coreos/mantle/pull/1154
> kola: Remove swtpm arch dependency checking

- src/cosalib/aws.py
This is a follow-up to #825. We go back to letting ore upload to all
regions in parallel, but make use of ore's streaming output so that we
do write down the regions that did upload successfully.
Note also that `ore aws copy-image` is idempotent, so even if an error
occurs that somehow prevents us from writing down the uploaded AMIs,
we'll eventually converge on the right final state (esp. now that we
retry by default).
This also bumps mantle to include the required change in `ore aws
copy-image` (coreos/mantle#1162). Shortlog:
```
Colin Walters (1):
kola/qemu: Fix leaking qemu instances
Jonathan Lebon (1):
ore/aws/copy-image: stream results back to stdout
Stephen Lowrie (2):
Merge pull request #1163 from cgwalters/qemu-leaks
Merge pull request #1162 from jlebon/pr/ore-copy-image-json
``` …
> aws-replicate: run in parallel

- src/offline-update-impl
Fallout from a recent change to make it executable.
> offline-update: Fix shellcheck warnings

- src/create_disk.sh
- src/grub.cfg
That way, it'll work on both IPv4 and IPv6 networks.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1793591
> grub.cfg: set ip=dhcp,dhcp6

- .cci.jenkinsfile
- src/cmd-kola
See individual commit messages!
Once we get this in, I'll do the same for the the FCOS config repo too.
> Add `cosa kola --upgrades` and turn on upgrade testing in CI

- OWNERS
> OWNERS: add Ownersfile

- src/cmd-artifact-disk
This fixes a typo I noticed while browsing through this part of cosa.
I did NOT manually check whether the logic actually work.
> artifact-disk: fix variable name

- README.md
The instructions in the `README.md` around this duplicate those in
`README-devel`. Just link to that one, which has more details.
> README.md: link to README-devel.md for testing patches

- src/cmd-artifact-disk
- src/cosalib/cli.py
Followup to 53aa9c314e47ca7018e601358a5444dbed903774 - I somehow
missed the copy-paste into these places too.
> disk,cli: Remove timestamp from logging

- Dockerfile
So we get the newer rpm-ostree.
> Dockerfile: Blow out quay.io cache

- src/cosalib/vmware.py
This ensures that the OVA files are spec compliant per [1]:
- use the actual and virtual sizes from qemu-img
- use the correct tar format of ustar.
Fix for https://github.com/coreos/fedora-coreos-tracker/issues/391
Local testing confirmed that the OVA file imports correctly.
[1] https://www.dmtf.org/sites/default/files/standards/documents/DSP0243_1.1.0.pdf
> cosalib/vmware.py: fix OVA generation to meet spec

- src/cmd-test-coreos-installer
A pxe boot solution for s390x. Took a bit of tweaking since the pxe image needed
to be built manually.
> Support coreos-installer test for s390x

- mantle/cmd/kola/kola.go
Rather than duplicating the "print error and exit non-zero" glue,
use the built-in `runE` instead of `run`.
> kola: Use runE

- mantle/kola/harness.go
- Return an `error` on general principle - we should only do the
"log error" bit at toplevel API in my opinion, this maximizes
flexibility for callers.
- Drop the distribution check as all distributions we care about
have SELinux today, if that changes we should do it in a different
way anyways.
Prep for potentially reusing this for `kola run-ext-bin`.
> kola: Cleanup scpKolet a bit

- mantle/cmd/plume/prerelease.go
> plume: Remove unused CL code

- README-devel.md
And simplify kola hacking instructions.
> README-devel.md: drop mantle bump instructions

- src/cmd-run
This runs through the code path in `qemuexec` that we want.  Prep
for adding more configuration.
> run: Explicitly enable usermode networking

- Makefile
- mantle/Makefile
- mantle/platform/qemu.go
- mantle/system/copy_test.go
- mantle/test
This closes an important gap in CI since the merge.
> build-sys: Also run mantle unit tests in `make check`

- mantle/platform/cluster.go
It aids doing `ssh` directly, which is helpful some times for
debugging things.  This will also help rpm-ostree which
carries code to do this from the JSON fd:
https://github.com/coreos/rpm-ostree/blob/b424c92ac18b7760bce194a1896049e5de692dfb/tests/common/libvm.sh#L56
> mantle: Generate ssh-config in output dir

- mantle/platform/cluster.go
Using port `22` is the normal case, it's just `unprivqemu` that's
weird.
> mantle: Don't crash if there's no port in spawned machine

- mantle/cmd/kola/qemuexec.go
- mantle/cmd/kola/testiso.go
- mantle/platform/machine/unprivqemu/cluster.go
- mantle/platform/machine/unprivqemu/flight.go
- mantle/platform/qemu.go
- src/cmd-buildextend-metal
- src/cmd-run
Split out of #1130. See individual commit messages.
> Prep patches for 4k drive support

- mantle/platform/cluster.go
> mantle: Really avoid crashing if no port is set for SSH

- .cci.jenkinsfile
> ci: Test `kola testiso`

- mantle/cmd/kola/testiso.go
- mantle/platform/metal.go
Followup to https://github.com/coreos/coreos-assembler/pull/1239
> mantle: Adjust testiso/metal for ptr values in cosa.Build

- mantle/platform/conf/conf.go
This only shipped with CL, no need to carry it here.
Further code reduction in prep for enhancing this code
to handle more of Ignition spec 2 vs 3.
> mantle/conf: Remove Ignition spec 1 support

- mantle/cmd/kola/qemuexec.go
I noted in a PR review that the low-level qemu API supports
being passed no config, but I broke that property in the
`qemuexec` CLI more recently.
Support being provided no config, so we can test that case.
> qemuexec: Support providing no config

- mantle/cmd/kola/qemuexec.go
I'm trying to test an Ignition config doing partitioning for RHCOS
and the model of trying to handle everything as spec 3 internally
and convert isn't going to work.  (Or at least, I don't want
to try to debug conversion code at the same time as this)
Add an option to say "just pass this config to the instance directly".
> qemuexec: Support --ignition-direct

- src/cmd-build
Puts it on equal footing with `metal`.
> cmd/build: allow `cosa build metal4k`

- src/buildroot-reqs.txt
For https://github.com/coreos/rpm-ostree/pull/2046
> buildroot: Add rustfmt

- mantle/platform/qemu.go
Fix swtpm device declaration for aarch64 and add it for ppc64le.
Question for the record. Do we have any tpm based tests for FCOS in kola?
> kola/qemu: Fix swtpm device for aarch64 and ppc64le

- mantle/cmd/kola/testiso.go
I plan to add more "scenarios", specifically at least `iso-offline-live`
which doesn't do an install, just verifies we can get to a prompt
offline.
The `--no-X` bools don't scale; we can remove them after RHCOS 4.5
switches to the ISO (along with code to test the legacy path).
> testiso: Add --scenarios argument

- Dockerfile
- build.sh
- mantle/kola/tests/rhcos/luks.go
- src/deps.txt
- src/tang/tangd.xinetd
- src/tang/tangdw
This PR 
- Installs Tang server in coreos-assembler using xinetd
- Adds simple tests for Tang and SSS
> mantle/kola/tests: add tang and sss tests

- mantle/kola/tests/rhcos/luks.go
Running on OpenShift exposed some race conditions with the xinetd
pid file and the tang/sss tests.  In the first scenario, the tests
would try to read the pid file before the xinetd process forked
and created the pid file.  In the second scenario, the tests would
read a pre-existing pid file and then fail killing a non-existent
process.  The tests now deletes any existing pid file and waits
until the file exists before continuing.
> kola/tests/luks: fix xinetd pid file race

- mantle/cmd/kola/kola.go
A new stream doesn't have any releases yet, so we can't do upgrade
testing within that stream. Instead, let's just fallback to upgrade
testing from `testing-devel`, which should always work since in theory all
the new streams we will be introducing are "ahead" in content from
testing-devel.
This is also a first step towards supporting cross-stream upgrade
testing. The next commit will add enablement for testing this in
`fcos.upgrade.basic`. The follow-up to this then is simply exposing the
base stream to use on the CLI).
> kola: fall back to upgrade testing from testing-devel for new streams

- mantle/cmd/kola/devshell.go
I think what was racing and causing corruption sometimes
is that we'd print a trailing newline in some cases.
- Ensure that the output is valid UTF-8
- Omit empty lines
- Trim lines to 100 characters
- Remove the unnecessary checks for newlines/carriage returns
since those were already covered by `IsGraphic()`.
>  devshell: More output validation

- src/create_disk.sh
The OSTree version that contains it has long since been
released so we can use it now.
> create_disk: Use ostree admin init-fs --modern

- src/cmdlib.sh
The base lockfile is directly output from rpm-ostree, which is in JSON.
Let's make sure we use the right extension to represent this if we're
creating the lockfile for the first time.
See also: https://github.com/coreos/fedora-coreos-config/pull/378
> cmdlib: default to JSON for base lockfile

- src/cmd-buildextend-installer
Split from https://github.com/coreos/coreos-assembler/pull/1420
(There's more code cleanup wound up in the last patch but it's annoying to round trip test so I'd only like to split it all out if I really have to)
> Iso initramfs split prep

- .cci.jenkinsfile
- mantle/cmd/kola/testiso.go
- mantle/platform/metal.go
So we can debug failures just like the main kola runs.
> testiso: Gather logs

- src/oscontainer.py
So that e.g. buildah uses it for temporary storage and doesn't blow
through the tiny supermin appliance rootfs (and sure... we could just
bump that from 5G, though that bumps it for everything else, and I think
it's cleaner to take `--workdir` at face value).
This should resolve issues the RHCOS pipeline is hitting where `buildah
commit` is hitting `ENOSPC`.
> oscontainer: use workdir as temporary directory if provided

- mantle/cmd/kola/testiso.go
Really need to add `metal` to the main `kola` so that this
code isn't duplicated in as many places.
This also removes some leftover cruft.
> testiso: Also capture initramfs virtio dumps

- mantle/cmd/kola/kola.go
- mantle/sdk/download.go
`coreos-installer` carries all the "download with progress" + "verify",
now that we include it in coreos-assembler let's just use it.
> kola: Replace download code with executing coreos-installer

- mantle/cmd/kola/testiso.go
We were seeing a failure to write the virtio dump in `testiso`
added in https://github.com/coreos/coreos-assembler/pull/1462
I noticed that we were accidentally using the *global* `outputDir`
when we meant to write into subdirectories.  Argh.  Global
mutable state is *evil*.  EVIL.
Seriously why would someone designing a language entirely around
"lots of concurrent lightweight threads" even think about having
global mutable state?
> testiso: Fix use of global `outputDir`

- README-devel.md
> README-devel.md: Document `oc rsync` trick

- mantle/platform/qemu.go
Prep for restricting internet access in tests.
> qemu: Add an API to request restricted networking

- mantle/kola/README-kola-ext.md
Introduced by https://github.com/coreos/coreos-assembler/pull/1528/commits/d57185122c00a4cc7150f11bb063fdefc1eca457
> README-kola-ext: Document new autopkgtest reboot API

- mantle/kola/tests/crio/crio.go
Fix the crio.base/networks-reliably test following the changes in the
CRI-O 1.18 release.
* Explicitely add the NET_RAW capability to the containers to be able to
run ping as it was removed by default. See
https://github.com/cri-o/cri-o/commit/63b9f4ec986da267a18f73d4b1ef13282d103e00
* Dynamically generate the host IP on the crio bridge to account for the
change to a new subnet. See
https://github.com/cri-o/cri-o/commit/f4214be7c14cada0164f2391a90e1baff9ee1170
> kola: tests/crio: Update for 1.18 release compatibility

- src/libguestfish.sh
The libguestfish calls need to have the vsmt fixed.
On POWER8 the vsmt default is 8, when on POWER9 it is 1.
This patch change the vsmt=8 in order to restore the default value for
POWER8. It is also compatible with POWER9
> Fix libguestfish for Power

- mantle/kola/tests/crio/crio.go
Fix the crio.base/networks-reliably test following the changes in the
CRI-O 1.18 release.
* Explicitely add the NET_RAW capability to the containers to be able to
run ping as it was removed by default. See
https://github.com/cri-o/cri-o/commit/63b9f4ec986da267a18f73d4b1ef13282d103e00
* Dynamically generate the host IP on the crio bridge to account for the
change to a new subnet. See
https://github.com/cri-o/cri-o/commit/f4214be7c14cada0164f2391a90e1baff9ee1170
Cherry-picked from: https://github.com/coreos/coreos-assembler/pull/1557
> [rhcos-4.5] kola: tests/crio: Update for 1.18 release compatibility

- README-devel.md
A few things missing from here and also `--srv` was broken with
the `cosa run` changes.
> README-devel.md: Update with more tips

- src/oscontainer.py
Tackle this issue https://issues.redhat.com/browse/GRPA-2086.
> Add cosa commit and rhcos commit as labels in oscontainer

- mantle/cmd/kolet/kolet.go
- mantle/kola/harness.go
Drop the previous two reboot APIs:
- send `SIGTERM` to self
- write `/run/kola-reboot`
They're obsoleted in favor of the Debian autopkgtest API.
This allows us to clean up the code significantly.  Most
notably, the harness ↔ kolet communication is now based
on serializing a JSON object on stdout (currently with just one member)
rather than having the harness go in and run `ssh` again to invoke
`cat`.
> kola: Clean up reboot handling

- mantle/cmd/kola/testiso.go
- mantle/platform/metal.go
I was going to change this code and noticed the redundancy.
> testiso: Drop duplicated code with platform/metal

- mantle/platform/util.go
This one isn't a new bug I introduced, I swear!  The ostree
test suite seems to hit this more often for some reason
I didn't fully debug though.
As I note in the comment I think we can clean this up in a
much better way in the future, but for now I'd like to paper
over this one and move on to getting OSTree's CI going again.
> mantle: Paper over another reboot failure mode

- .cci.jenkinsfile
> ci: enable 4k disks when testing 4k disks

- README-custom.md
- README.md
This is just a first draft, needs approval from the CoreOS team.
> README-custom.md: New file describing state of building derivatives

- mantle/platform/qemu.go
On filesystems like btrfs, qcow2 files can become much more fragmented
if copy-on-write is enabled.  We don't need that, our disks are ephemeral.
https://gitlab.gnome.org/GNOME/gnome-boxes/-/issues/88
https://btrfs.wiki.kernel.org/index.php/Gotchas#Fragmentation
https://www.redhat.com/archives/libvir-list/2014-July/msg00361.html
> qemu: Use nocow=on by default for qcow2

- mantle/cmd/kola/testiso.go
- src/cmd-buildextend-installer
Split out of https://github.com/coreos/coreos-assembler/pull/1637. See individual commit messages for detail.
> Prep patches for karg embed area support

- mantle/cmd/kola/testiso.go
- mantle/platform/metal.go
Adds a new scenario targeting PXE offline which passes the --offline
flag to coreos-installer.
> mantle/cmd/kola/testiso: add pxe-offline scenario

- mantle/kola/README-kola-ext.md
Add an example of how to create a kola external test.
> kola/README-kola-ext.md: Add quickstart example

- src/cmdlib.sh
See https://pagure.io/centos-infra/issue/48 and
https://github.com/coreos/coreos-ci-lib/commit/45762ba5aded40365a4777cfa462e76b737f60ad
> Error on unset umask

- mantle/kola/README-kola-ext.md
A fast edit-compile-debug cycle is very important.
> kola: Document cosa build-fast combined with kola

- mantle/platform/machine/qemuiso/cluster.go
- mantle/platform/machine/unprivqemu/cluster.go
- mantle/platform/qemu.go
- mantle/platform/qmp_util.go
This fixes a few minor linting warnings that golint is highlighting.
/cc @jlebon @arithx
> platform/qemu: misc linting fixes

- src/cmdlib.sh
Reorder buildprep so that we create the per-build temporary
directory much earlier.  We can then use this for things like
the temporary manifest JSON file we create there.
> cmdlib: Generate temporary manifest in tmp_builddir

- mantle/platform/qemu.go
QEMU 5 (in f33) will warn if `backing_fmt` is unspecified.  Expose
an API for clients to tell us (in theory e.g. `cosa run` could
know this from the cosa metadata), but let's do the easy thing
and push qcow2 autodetection into our code.
> qemu: Autodetect qcow2 backing format

- src/cmdlib.sh
We're not doing this and I plan to change this code to add
optional dependencies.
> cmdlib: Remove a remnant of the rhel-based cosa

- src/cmdlib.sh
Recent changes to parallelize builds have turned up a whole
lot of race conditions.   This is one; we only need to create
`cache2.qcow2` for the main `cosa build ostree`.  While here
I also added locking on general principle.
Partially fixes https://github.com/coreos/coreos-assembler/issues/1716
> cmdlib: Move cache2.qcow2 creation to be locked

- mantle/go.mod
- mantle/go.sum
- mantle/vendor/github.com/coreos/ignition/v2/config/v3_0/types/node.go
- mantle/vendor/github.com/coreos/ignition/v2/config/v3_0/types/storage.go
- mantle/vendor/github.com/coreos/ignition/v2/config/v3_1/types/node.go
- mantle/vendor/github.com/coreos/ignition/v2/config/v3_1/types/storage.go
- mantle/vendor/github.com/coreos/ignition/v2/config/v3_2_experimental/types/node.go
- mantle/vendor/github.com/coreos/ignition/v2/config/v3_2_experimental/types/schema.go
- mantle/vendor/github.com/coreos/ignition/v2/config/v3_2_experimental/types/storage.go
- mantle/vendor/modules.txt
We need this for the latest `wipeVolume` key to support in-place
root-on-LUKS.
> mantle: vendor latest 3.2-experimental Ignition spec

- src/cmd-buildextend-metal
- src/create_disk.sh
Not necessary now that RHCOS is on Ignition v2/spec3.
> build: Remove var-subdirs hack

- mantle/kola/harness.go
That way if the Ignition config references an unsupported version, we
don't error out. This technically duplicates the `filterTests` function,
but mehh...
> kola: deny external tests before parsing Ignition config

- src/cmdlib.sh
- src/supermin-init-prelude.sh
This code path is suspected in breaking the RHCOS builds. Reverting out of caution. 
/cc @mike-nguyen
> Revert mounting /etc/pki in Supermin

- src/cmd-fetch
Follow-up to #1785.
Reported-by: Colin Walters <walters@verbum.org>
> cmd-fetch: assuage ShellCheck

- Makefile
> Makefile: fix minio installation

- mantle/cmd/kola/console.go
- mantle/cmd/kola/kola.go
- mantle/cmd/kola/qemuexec.go
- mantle/cmd/kola/spawn.go
- mantle/cmd/kola/testiso.go
VSCode highlights these.  It wants "URL" to be capitalized,
de-indented `return` inside `else`, etc.
> kola: Fix various golint warnings

- mantle/platform/qemu.go
- src/cmdlib.sh
No one should really use this for anything production; the
speed hit is huge and there are emulation corner cases that
one can hit.
That said for just "trying things out" the dependency on
KVM can be annoying.  Our current OpenShift CI cluster doesn't
have GCP nested virt enabled (that's coming), and people
in the past have ended up in nested virt situations etc.
> Support COSA_NO_KVM=1

- mantle/cmd/kola/devshell.go
This cleans up cmd/kola/devshell.go:
```
cmd/kola/devshell.go:199:18: Error return value of `serialLog.Seek` is not checked (errcheck)
serialLog.Seek(0, os.SEEK_SET)
^
cmd/kola/devshell.go:206:8: S1005: unnecessary assignment to the blank identifier (gosimple)
case _ = <-readychan:
^
cmd/kola/devshell.go:219:9: S1005: unnecessary assignment to the blank identifier (gosimple)
case _ = <-serialChan:
^
cmd/kola/devshell.go:311:16: Error return value of `proc.Signal` is not checked (errcheck)
proc.Signal(os.Interrupt)
^
```
> mantle: clean up devshell

- mantle/cmd/kolet/kolet.go
This cleans up cmd/kolet/kolet.go:
```
cmd/kolet/kolet.go:143:11: Error return value of `cmd.Usage` is not checked (errcheck)
cmd.Usage()
^
cmd/kolet/kolet.go:160:15: Error return value of `cmd.Usage` is not checked (errcheck)
cmd.Usage()
^
cmd/kolet/kolet.go:197:19: Error return value of `sdconn.StartUnit` is not checked (errcheck)
sdconn.StartUnit(unitname, "fail", nil)
^
cmd/kolet/kolet.go:300:20: Error return value of `dispatchRunExtUnit` is not checked (errcheck)
dispatchRunExtUnit(unitname, sdconn)
^
```
> mantle: clean up kolet

- ocp/Dockerfile.buildconfig
Fixes an incorrect workdir. 
/cc @bh7cw
> ocp/Dockerfile.buildconfig: fix workdir

- mantle/cmd/ore/azure/upload-blob-arm.go
This cleans up cmd/ore/azure/upload-blob-arm.go:
```
cmd/ore/azure/upload-blob-arm.go:104:3: SA4004: the surrounding loop is unconditionally terminated (staticcheck)
break
^
cmd/ore/azure/upload-blob-arm.go:107:2: ineffectual assignment to `err` (ineffassign)
err = json.NewEncoder(os.Stdout).Encode(&struct {
^
```
> mantle: clean up cmd/ore/azure

- gangplank/ocp/sa_secrets.go
Setup more secret mappings so we can build and publish to more
clouds.
> gangplank: add more cloud secrets support

- gangplank/ocp/cosa-pod.go
On some version of OCP, the cluster version has a "+" in the name.
> Gangplank: improve cluster detection

- mantle/cmd/kola/testiso.go
This cleans up cmd/kola/testiso.go:
```
cmd/kola/testiso.go:171:18: Error return value of `builder.AddDisk` is not checked (errcheck)
builder.AddDisk(&platform.Disk{
^
cmd/kola/testiso.go:177:25: Error return value of `builder.AddPrimaryDisk` is not checked (errcheck)
builder.AddPrimaryDisk(&platform.Disk{
^
cmd/kola/testiso.go:355:13: S1039: unnecessary use of fmt.Sprintf (gosimple)
msg := fmt.Sprintf("entered emergency.target in initramfs")
^
cmd/kola/testiso.go:370:3: S1021: should merge variable declaration with assignment on next line (gosimple)
var err error
^
cmd/kola/testiso.go:458:20: Error return value of `mach.Destroy` is not checked (errcheck)
defer mach.Destroy()
^
cmd/kola/testiso.go:499:20: Error return value of `mach.Destroy` is not checked (errcheck)
defer mach.Destroy() …
```
> mantle: clean up testiso

- mantle/cmd/plume/prerelease.go
This cleans up cmd/plume/prerelease.go:
```
cmd/plume/prerelease.go:97:22: Error return value of `flags.MarkDeprecated` is not checked (errcheck)
flags.MarkDeprecated("channel", "use --stream instead")
^
cmd/plume/prerelease.go:103:9: S1005: unnecessary assignment to the blank identifier (gosimple)
for k, _ := range platforms {
^
cmd/plume/prerelease.go:106:2: S1032: should use sort.Strings(...) instead of sort.Sort(sort.StringSlice(...)) (gosimple)
sort.Sort(sort.StringSlice(platformList))
^
cmd/plume/prerelease.go:395:70: SA4009: argument imageName is overwritten before first use (staticcheck)
func awsUploadToPartition(spec *channelSpec, part *awsPartitionSpec, imageName, imageDescription, imagePath string) (map[string]string, error) {
```
Fixes part of …
> mantle: clean up cmd/plume/prerelease

- src/build-deps.txt
> src/build-deps.txt: dependency commit for #1862

- mantle/harness/harness.go
This cleans up harness/harness.go:
```
harness/harness.go:124:26: Error return value of `outputBufferCopy.WriteTo` is not checked (errcheck)
outputBufferCopy.WriteTo(p.w)
^
harness/harness.go:235:17: Error return value of `c.logger.Output` is not checked (errcheck)
c.logger.Output(3, s)
^
harness/harness.go:393:17: S1012: should use `time.Since` instead of `time.Now().Sub` (gosimple)
t.duration += time.Now().Sub(t.start)
^
```
> mantle: clean up harness

- src/cmd-generate-hashlist
See https://github.com/keylime/enhancements/pull/32
cc @mpeters @lukehinds
> keylime: Update hashlist schema

- mantle/kola/tests/docker/docker.go
This cleans up kola/tests/docker/docker.go:
```
kola/tests/docker/docker.go:385:18: Error return value of `cluster.DropFile` is not checked (errcheck)
cluster.DropFile(c.Machines(), oldclient)
^
kola/tests/docker/docker.go:497:12: Error return value of `util.Retry` is not checked (errcheck)
util.Retry(12, 6*time.Second, func() error {
^
```
> mantle: clean up kola/tests/docker

- gangplank/ocp/cosa-pod.go
- gangplank/ocp/sa_secrets.go
- gangplank/ocp/volumes.go
The ports the bulk of the RHCOS pipeline secrets out Groovy and into Gangplank.
> Gangplank: understand RHCOS pipeline secrets

- mantle/go.mod
- mantle/go.sum
- mantle/platform/conf/conf.go
- mantle/vendor/github.com/coreos/ign-converter/translate/v32tov24/v32tov24.go
- mantle/vendor/modules.txt
Fixes: https://github.com/coreos/coreos-assembler/issues/1851
> kola: Support converting spec 3.2 to 2.4

- mantle/kola/tests/ignition/luks.go
with ignition based LUKS landing, there is no reason why LUKS shouldn't work on other
arches with tang. Just had to build the tang container image similar to x86. Also had to
change the lookup of devices to not use by-partlabel for s390x because of the endianness
issue in naming.
> kola: enable tang based LUKS test for all arches

- mantle/kola/harness.go
This cleans up kola/harness.go:
```
kola/harness.go:154:11: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
match: regexp.MustCompile("ignition\\[[0-9]+\\]: failed to fetch config: context canceled"),
^
kola/harness.go:159:11: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
match: regexp.MustCompile("initrd-cleanup\\.service: Main process exited, code=killed, status=15/TERM"),
^
kola/harness.go:164:11: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
match: regexp.MustCompile("mm/pgtable-generic.c:\\d+: bad (p.d|pte)"),
^
kola/harness.go:547:27: SA5008: unknown JSON option "architectures" (staticcheck)
Architectures   string …
```
> mantle: clean up kola/harness.go

- mantle/kola/tests/podman/podman.go
This cleans up kola/tests/podman/podman.go:
```
kola/tests/podman/podman.go:193:6: S1002: should omit comparison to bool constant, can be simplified to `!found` (gosimple)
if found == false {
^
kola/tests/podman/podman.go:214:6: S1002: should omit comparison to bool constant, can be simplified to `found` (gosimple)
if found == true {
^
kola/tests/podman/podman.go:290:6: `podmanNetworkTest` is unused (deadcode)
func podmanNetworkTest(c cluster.TestCluster) {
^
```
> mantle: clean up kola/tests/podman

- gangplank/ocp/filer.go
With 6a84c3a6ffabdabb50b820c982ed8c03dcffc004 `minioServer.kill` was
added, which should have addressed the problem. To really make sure
minio dies, this uses `exec.Cmd` `SysProcAttr` to kill when Gangplank
dies.
Fixes: #1869
> Gangplank: ensure minio always dies

- mantle/kola/tests/upgrade/basic.go
This enhances upgrade test logic, by retrying metrics queries
against Zincati. This makes sure that there is enough stabilization
time for metrics that are only set later on during service startup.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/686
/cc @jlebon @dustymabe @bh7cw
> kola: improve Zincati metrics check

- mantle/platform/api/packet/api.go
This cleans up platform/api/packet/api.go:
```
platform/api/packet/api.go:181:18: Error return value of `a.DeleteDevice` is not checked (errcheck)
a.DeleteDevice(deviceID)
^
platform/api/packet/api.go:188:17: Error return value of `a.DeleteDevice` is not checked (errcheck)
a.DeleteDevice(deviceID)
^
platform/api/packet/api.go:194:17: Error return value of `a.DeleteDevice` is not checked (errcheck)
a.DeleteDevice(deviceID)
^
platform/api/packet/api.go:200:17: Error return value of `a.DeleteDevice` is not checked (errcheck)
a.DeleteDevice(deviceID)
^
platform/api/packet/api.go:458:20: Error return value of `conn.SetDeadline` is not checked (errcheck)
conn.SetDeadline(deadline)
^
platform/api/packet/api.go:469:37: S1012: should use `time.Since` instead of `time.Now().Sub` (gosimple) …
```
> mantle: clean up platform/api/packet

- gangplank/README.md
> gangplank: fixup words in README

- README.md
- `cosa-working.md` :arrow_right: `working.md`
- `cosa-devel.md` :arrow_right: `devel.md`
- `cosa-design.md` :arrow_right: `design.md`
> README.md: Update devel/working links

- mantle/platform/api/openstack/api.go
This cleans up platform/api/openstack/api.go:
```
platform/api/openstack/api.go:151:17: ineffectual assignment to `err` (ineffassign)
networkClient, err := openstack.NewNetworkV2(provider, gophercloud.EndpointOpts{
^
platform/api/openstack/api.go:325:17: Error return value of `a.DeleteServer` is not checked (errcheck)
a.DeleteServer(serverID)
^
platform/api/openstack/api.go:334:18: Error return value of `a.DeleteServer` is not checked (errcheck)
a.DeleteServer(serverID)
^
platform/api/openstack/api.go:341:18: Error return value of `a.DeleteServer` is not checked (errcheck)
a.DeleteServer(serverID)
^
platform/api/openstack/api.go:344:22: Error return value of `a.deleteFloatingIP` is not checked (errcheck)
a.deleteFloatingIP(floatingip.ID)
^
platform/api/openstack/api.go:350:18: Error …
```
> mantle: clean up platform/api/openstack

- mantle/platform/metal.go
This cleans up platform/metal.go:
```
platform/metal.go:280:3: S1023: redundant break statement (gosimple)
break
^
platform/metal.go:287:3: S1023: redundant break statement (gosimple)
break
^
platform/metal.go:292:3: S1023: redundant break statement (gosimple)
break
^
platform/metal.go:311:13: Error return value of `http.Serve` is not checked (errcheck)
http.Serve(listener, mux)
^
platform/metal.go:383:19: Error return value of `ioutil.WriteFile` is not checked (errcheck)
ioutil.WriteFile(filepath.Join(pxeconfigdir, "default"), pxeconfig, 0777)
^
platform/metal.go:404:3: S1023: redundant break statement (gosimple)
break
^
platform/metal.go:415:19: Error return value of `ioutil.WriteFile` is not checked (errcheck)
ioutil.WriteFile(filepath.Join(t.tftpdir, "boot/grub2/grub.cfg"), …
```
> mantle: clean up platform/metal

- mantle/platform/util.go
This cleans up platform/util.go:
```
platform/util.go:44:24: Error return value of `terminal.Restore` is not checked (errcheck)
defer terminal.Restore(fd, tstate)
^
```
> mantle: clean up platform/util

- gangplank/ocp/worker.go
Prep work for enabling pod mode to send binary input over stdin.
> Gangplank: allow for sending of binary input over stdin

- mantle/platform/qemu.go
This cleans up platform/qemu.go:
```
platform/qemu.go:84:2: `fd` is unused (structcheck)
fd             *os.File // builder file descriptor location, e.g. /proc/self/fd/
^
platform/qemu.go:98:2: `tmpConfig` is unused (structcheck)
tmpConfig          string
^
platform/qemu.go:222:18: Error return value of `inst.swtpm.Kill` is not checked (errcheck)
inst.swtpm.Kill() // Ignore errors
^
platform/qemu.go:227:16: Error return value of `nbdServ.Kill` is not checked (errcheck)
nbdServ.Kill() // Ignore errors
^
platform/qemu.go:252:17: Error return value of `monitor.Connect` is not checked (errcheck)
monitor.Connect()
^
platform/qemu.go:253:26: Error return value of `monitor.Disconnect` is not checked (errcheck)
defer monitor.Disconnect()
^
platform/qemu.go:1020:28: S1039: unnecessary use of …
```
> mantle: clean up platform/qemu

- src/download-extensions
> download-extensions: Create repodata in extensions/ dir

- mantle/platform/qemu.go
This is mostly a revert of
#1652, though with a spin
on it: we automatically detect if the `coreos-installer` in the cosa
container has coreos/coreos-installer#341.
This will allow us to test the functionality in that PR's CI before
merging, as well as avoiding ugly warnings until it gets into cosa
proper. (This addresses the original reason for the revert.)
Another difference is that we capture the stderr and make it part of the
warning to make it less scary if operating on an older CoreOS ISO and to
make it clear that it's non-fatal.
> qemu: automatically inject serial console karg into ISO

- docs/kola.md
> docs/kola: Fix kola quickstart link

- mantle/kola/tests/upgrade/basic.go
This gives more time for the basic upgrade test to check for
Zincati liveness, in order to avoid flaking on missed deadlines
due to VM load.
> kola/tests/upgrade: bump delay between Zincati checks

- mantle/cmd/kola/qemuexec.go
Let's make `qemuexec` slightly less opinionated in the spirit of being
more low-level: if we're not using any fancy features (like bind mounts
or auto-login), let's avoid even generating an empty Ignition config and
pass none.
This helps `kola qemuexec -p qemu-iso` a lot, because (1) it avoids
having to create a secondary ISO only to inject a no-op config (and
wasting developer time doing so), (2) we already have an auto-login
shell by default in the ISO if no Ignition config is provided and
providing an empty one breaks that, and (3) it works around Ignition
config mismatch issues like #1976 (in my case, I'm debugging the 4.6
live ISO).
> qemuexec: default to no Ignition config

- src/cmd-build
- src/cmd-fetch
- src/cmdlib.sh
- src/coreos-assembler
- src/oscontainer.py
Split out of #2028. See individual commit messages.
> Extensions prep patches

- src/deps.txt
We intend to share code in the future.
> Install osbuild-composer

- mantle/kola/harness.go
This will allow sharing external host tests between FCOS and RHCOS more
easily.
> kola: follow symlinks when collecting external host tests

- Dockerfile
So https://github.com/coreos/rpm-ostree/pull/2644 will work.
> Dockerfile: Blow quay.io cache to pick up newer librepo

- gangplank/ocp/k8s.go
> Gangplank: fix defer order in pod IP check

- docs/kola/external-tests.md
- mantle/cmd/kolet/kolet.go
Start an HTTP server to serve the contents of the file system
Usage:
kolet httpd [flags]
Flags:
-h, --help          help for httpd
--path string   path to filesystem contents (default "./")
--port string   port (default "80")
> kolet: Add httpd command

- docs/gangplank/usage.md
Add documentation for newest Gangplank features for:
- sharing minio between Gangplank instances
- new artifact dependency declarations
This documents https://github.com/coreos/coreos-assembler/pull/2095 and https://github.com/coreos/coreos-assembler/pull/2091 features. Hold pending #2095.
> Docs: Update Gangplank documentation

- src/create_disk.sh
This matches the RPM.  Came up on internal chat around `rpm -V`.
> create_disk: Make /boot/grub2 mode 0700

- gangplank/ocp/bc.go
The error handling logic is prone to a deadlock since it was both
writing to and receiving from the same channel. To fix this, the logic
has been broken out into a func, that is the only writer to the
terminate channel.
> Gangplank: fix hang on worker error

- docs/gangplank/usage.md
> Fix gangplank documentation

- gangplank/cosa/build.go
- gangplank/spec/stages.go
This gives Gangplank the ability to work with extensions.
> Gangplank: add understanding of extensions

- gangplank/ocp/sa_secrets.go
- gangplank/spec/clouds.go
- gangplank/spec/jobspec.go
- gangplank/spec/stages.go
Add ability to publish artifacts to the cloud providers.
> gangplank: add publication

- gangplank/ocp/bc.go
- gangplank/ocp/cosa-pod.go
- gangplank/ocp/k8s.go
- gangplank/ocp/pod.go
- gangplank/ocp/worker.go
A few clean-ups to better follow GoLang conventions
> Gangplank: go-lang convention clean-ups

- gangplank/cmd/commonflags.go
- gangplank/cmd/generate.go
- gangplank/cmd/main.go
- gangplank/spec/kola.go
- gangplank/spec/stages.go
This adds both the a CLI and jobspec short hand for testing.
> Gangplank: add Kola Test definitions

- Dockerfile
- src/cmd-kola
- src/deps.txt
> Move to Fedora 34!

- mantle/cmd/kola/qemuexec.go
Qemu allows passing disk images directly, but this bypasses all of our snapshot
infrastructure and it's too easy to accidentally do `cosa run foo.qcow2` instead of
the more verbose (but correct) `cosa run --qemu-image foo.qcow2`.
Anyone who wants persistence can add it as a disk manually.
This came out of almost a full hour of debugging; I somehow got `cosa run foo.qcow2`
in my shell history and the thing is it *looks* right.  So let's make
it right.
> qemuexec: Make `cosa run foo.qcow2` correctly use snapshots

- mantle/cmd/kola/devshell.go
I was debugging a failure to ssh, and this would have helped (a bit).
> devshell: Try to ssh one final time, and print stderr

- mantle/cmd/kola/testiso.go
- mantle/platform/metal.go
Split out of https://github.com/coreos/coreos-assembler/pull/2172. See individual commit messages.
> Prep patches for testiso multipath support

- mantle/cmd/kola/qemuexec.go
- mantle/kola/tests/misc/network.go
- mantle/platform/machine/unprivqemu/cluster.go
- mantle/platform/qemu.go
This PR follows the design suggested on #2121 to allow adding additional NICs
with cosa kola qemuexec.
> cosa, Add secondary-nics option

- gangplank/ocp/cosa-pod.go
- gangplank/ocp/cosa-podman.go
The need for debugging verbosity has passed.
> Gangplank: remove verbosity on dumb-init

- src/cmd-buildupload
Minor regression from #946. Noticed this today as I was interactively
uploading a scratch build.
> cmd-buildupload: print progress as we upload

- mantle/platform/qemu.go
switch boot order for multipath disks when running testiso with `qemu-multipath`. there was a regression in the arm64 rhcos pipeline with testiso failing with:
```
+ kola testiso -S --qemu-native-4k --qemu-multipath --scenarios iso-install --output-dir tmp/kola-metal4k
Testing scenarios: [iso-install]
Error: scenario iso-install: switching boot order failed: Could not set bootindex for blkdev: Running QMP command: Device '' not found; <nil>
2021-06-03T08:32:21Z cli: scenario iso-install: switching boot order failed: Could not set bootindex for blkdev: Running QMP command: Device '' not found; <nil>
```
the disk device for multipath was not recognized when switching bootorder causing this to fail.
(cherry picked from commit b9f7c779d18a6f310335d4c1d91e909ffcf54385)
> [rhcos-4.8] platform/qemu: switch boot order for multipath disks

- src/cmdlib.sh
Follow-up to #2204. The cosa bash alias mounts the source config
read-only, so we can't modify those files. Let's just copy it to a
tmpdir instead to avoid touching the source config repo.
Reported-by: Dusty Mabe <dusty@dustymabe.com>
> cmdlib: change perms on overlay dir copy when stripping bits

- ocp/cosa-bc.yaml
- ocp/cosa-image.yaml
- Updated to reflect new main naming convention
- Bump caching to include F33 and F34
> ocp: Update templates for OCP

- mantle/build
- mantle/harness/reporters/json.go
- mantle/platform/qemu.go
- mantle/platform/qmp_util.go
Fixes for races in Kola:
- turns on race detection by default
- fix for race in the JSON reporter
- fix for race in qmp.Socket commands
> Mantle: race detection and fixes for Kola

- ocp/cosa-image.yaml
Include the branch names in the image tags.
> OCP: updated the Gangplank yaml files to include branch names

- docs/gangplank/usage.md
> Docs: update Gangplank docs

- docs/cosa.md
s/artifcats/artifacts
s/functionnal/functional
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>
> docs: fix two typos

- docs/cosa.md
Rendered at: https://travier.github.io/coreos-assembler/cosa/
> docs: Improve build-extend section

- docs/gangplank/usage.md
couldn't help noticing a few things that needed tweaking :)
> usage.md: minor copyediting

- mantle/cmd/kola/testiso.go
Part of https://github.com/coreos/fedora-coreos-tracker/issues/889.
> testiso: check that /boot/ignition was nuked

- src/cmdlib.sh
If an `overlay.d` directory contains a file called `statoverride` at the root, pass it to `ostree`.  This allows overlay files to have permission bits that aren't tracked by Git.
`statoverride` files don't support comments.  For convenience, filter out lines starting with `#`.
This backports https://github.com/coreos/coreos-assembler/pull/2293, with a somewhat different implementation.  This should be a no-op for 4.8, and will be useful for 4.9 until we switch that back to the `main` branch.
> [rhcos-4.8] cmdlib: support statoverride file in root of an overlay.d directory

- mantle/platform/qemu.go
Now that the live ISO supports modifying kargs, let's wire it through.
This makes e.g. `kola qemuexec --kargs foobar` work.
> platform/qemu: support passing additional kargs to ISO

- mantle/go.mod
- mantle/go.sum
- mantle/vendor/github.com/coreos/stream-metadata-go/fedoracoreos/fcos.go
- mantle/vendor/github.com/coreos/stream-metadata-go/release/release.go
- mantle/vendor/github.com/coreos/stream-metadata-go/release/translate.go
- mantle/vendor/github.com/google/renameio/tempfile.go
- mantle/vendor/modules.txt
To get azurestack translation.
> mantle: Bump coreos/stream-metadata-go

- gangplank/cmd/gangplank/commonflags.go
- gangplank/cmd/gangplank/generate.go
- gangplank/cmd/gangplank/pod.go
- gangplank/internal/ocp/ssh.go
- gangplank/internal/spec/jobspec.go
> gangplank: Allow gangplank remote to run with custom port

- src/deps.txt
- src/pkcs7encrypt
Backports #2280 adding a command to encrypt build logs.
> [rhcos-4.8]: Backport pkcs7encrypt from main

- Makefile
- gangplank/Makefile
- gangplank/cmd/gangplank/pod.go
- gangplank/internal/ocp/filer_test.go
- gangplank/internal/ocp/return_test.go
- gangplank/internal/ocp/ssh.go
Fix-up commit from running `make test` locally.
> Gangplank: gofmt fixups

- src/cosalib/ibmcloud.py
The force flag was set for ore which is incorrect. it should be inside upload.
> cosalib/ibmcloud.py: move force flag inside upload command

- mantle/cosa/cosa_v1.go
- mantle/cosa/schema_doc.go
- src/schema/v1.json
- It is missing the schema changes needed by Koji
> Fix koji backport done in #2314

- gangplank/cosa/v1.go
- mantle/cosa/cosa_v1.go
- mantle/cosa/schema_doc.go
- src/schema/v1.json
- It is missing the schema changes needed by Koji
> [4.7] Fix koji backport done in #2314

- mantle/cmd/kola/options.go
> kola: Move aws arch defaults to generic code

- gangplank/internal/ocp/cosa-podman.go
Prior to this, Gangplank used `containers.Attach` for capturing the logs
from worker containers; this was done since the old Podman API was
nearly unusable for watching logs.
However, using `Attach` will fail while losing logs if the container
exits before the attach completes. Since 3.2 Podman API does not have
the performance penalty, the prudent course is to use the Log API call
to ensure that all logs are captured.
> Gangplank: use log API for logs

- Makefile
- mantle/Makefile
> Tweak, cleanup, and improve mantle-related Makefile targets

- gangplank/internal/ocp/bc.go
- gangplank/internal/ocp/filer.go
- gangplank/internal/ocp/ssh.go
This time we'll go ahead and use the remote chosen port locally as
well. This is because the minio bucket is consulted by the local running
process for required artifacts before even starting a pod on the remote
(i.e. why start the pod until the artifacts exist that it needs?). If
they use different port numbers then we'd have to track them separately
and behave differently whether we're running in the remote podman cosa or
in the local cosa. Let's just use the same port locally as well since it
is highly unlikely to have a port conflict locally because we're running
in a container with no other services running.
To achieve this goal we submerge the starting of the minio server into
the ssh port forwarding code so we can detect the port before we start
the server and set up the proxy.
> gangplank: take two on ssh port forwarding

- mantle/kola/tests/docker/docker.go
- mantle/kola/tests/etcd/rhcos.go
- mantle/kola/tests/ignition/resource.go
- mantle/kola/tests/ignition/security.go
- mantle/kola/tests/misc/aws.go
- mantle/kola/tests/misc/nfs.go
- mantle/kola/tests/misc/tls.go
- mantle/kola/tests/util/containers.go
Noticed while doing another refactoring.
> kola: Replace RunCmdSync(fmt.Sprintf()) with RunCmdSyncf

- src/create_disk.sh
We decided to try to keep the partition numbers in sync across our
x86_64, aarch64, and ppc64le platforms. Previously we skipped partition
numbers on some architectures (for example there was no sda1 by default
on aarch64) and this caused a few issues:
- user confusion
- it is a common misconception that partition numbers need to start
at one and increment
- it can be surprising if the disk layout changes when you go from
one architecture from the other and re-use the same ignition config
- tooling bugs
- the butane templates for device boot mirroring didn't include
partition numbers and ended up with inconsistent behavior on
aarch64/ppc64le versus x86_64
Keeping the partition numbers in sync will help alleviate some of these
issues.
Fixes: …
> create_disk: add reserved partition entries to aarch64,ppc64le

- mantle/cmd/ore/openstack/create.go
- mantle/cmd/ore/openstack/delete.go
- mantle/platform/api/openstack/api.go
This will allow us to protect an image from deletion when we upload
it to VexxHost.
> mantle/ore: openstack: support setting image protection

- mantle/kola/harness.go
External tests are executed in test VMs via systemd units. When
we use the multiply flag with non-exclusive tests we duplicate
tests and their systemd units in one VM. This creates services
with the same name.
We fix this by generating the non-exclusive wrapper test _before_
the tests are duplicated. This way the wrapper test is duplicated
instead of the tests within the wrapper. We avoid having multiple
services with the same name in one VM.
> kola/harness.go: fix multiply flag with non-exclusive tests

- docs/gangplank/usage.md
- gangplank/internal/ocp/sa_secrets.go
- gangplank/internal/ocp/volumes.go
> gangplank: Add/fix doc information for secrets

- ci/Dockerfile
It's GA and Fedora CoreOS in also moving.
> Move to Fedora 35!

- mantle/platform/api/do/api.go
DigitalOcean custom images must use IPv4:
https://docs.digitalocean.com/products/networking/ipv6/\#limits
> mantle/platform/api/do: use IPv4 when using custom images

- mantle/cmd/ore/openstack/openstack.go
Prep for https://github.com/coreos/fedora-coreos-pipeline/issues/422
> mantle/platform/api/openstack: add flag to override region

- mantle/cmd/kola/devshell.go
As of https://gitlab.gnome.org/GNOME/glib/-/commit/10c490cdfe3ae042f747bd00f787492e2bdb7ed0
GLib uses "smart quotes" in some strings.
For some reason, `journalctl -o json` seems to output these (non-ASCII)
as byte arrays.
As soon as one of these messages shows up in the journal, it causes
an unending spew of error messages about failing to unmarshal a string
to the terminal, rendering it nearly unusuable.
Fix this by always parsing events as byte arrays, since all we do
with them is compare them.
> devshell: Avoid error spew if binary message in systemd journal

- mantle/kola/tests/misc/network.go
This PR is a wip to support the changes [0] suggested on rchos-slb repo.
[0] https://github.com/RHsyseng/rhcos-slb/pull/34
> mantle/kola/tests, Add restart test

- ci/prow-rhcos.sh
`BRANCH` is the cosa branch name, `RHCOS_BRANCH` is the mapped branch to
use for checking out the RHCOS config.
> ci/prow-rhcos.sh: fix branch handling

- mantle/platform/conf/conf.go
- mantle/platform/machine/aws/cluster.go
Recently non-exclusive tests have grown to a point such that
the associated ignition config has become too large to be passed
to AWS via user-data. The base64 encoding of the config is larger
than 16 KB. While we look for a more permanent solution to this
issue, compressing the config will decrease how often we run into
it. It will also unblock currently broken non-exclusive tests on AWS.
related: https://github.com/coreos/fedora-coreos-tracker/issues/1030
> kola/platform: compress userdata before passing to aws

- mantle/cmd/kola/testiso.go
- mantle/platform/metal.go
With `--add-nm-keyfile`, we inject a NM keyfile into the ISO and enable
`--copy-network`. We then add a systemd service to verify that it took
effect.
Essentially, this verifies that with `coreos-installer iso network
embed` and `--copy-network`, it's possible to specify the NM keyfile
*once* and have that apply to: the live initrd, the live rootfs, the
target initrd, and the target rootfs.
I debated whether to make this a scenario instead of a switch. I ended
up making it a switch because it's another "axis" to the install
(similarly to `--qemu-multipath`). And while this currently only take
effect on ISO installs, nothing stops us from also supporting it for
PXE, even though it's less relevant there (hence why I left it as a
follow-up for now).
> testiso: add --add-nm-keyfile for NM keyfile propagation testing

- mantle/kola/tests/upgrade/basic.go
IIRC, it started initially as a way to sanity-check that Zincati
auto-updates were turned on and that we wouldn't just wait in vain for
it to update.  But for some reason, sometimes `socat` simply fails to
find Zincati's UNIX socket, even though the latter says that it created
it and goes on with staging the update. For more information, see:
https://github.com/coreos/fedora-coreos-tracker/issues/756.
We should dig into this further, but strictly speaking, it's not even
necessary for this test to have the socket available. So let's just nuke
that check. The `runFnAndWaitForRebootIntoVersion` function will still
time out after 2 minutes if the machine hasn't rebooted by then.
> kola/upgrade/basic: drop metrics.promsock check

- mantle/kola/tests/misc/boot-mirror.go
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/763
> tests/boot-mirror: ensure SSH is working after removing primary block device

- mantle/kola/tests/util/rpmostree.go
We have a case where the rpm-ostree status command is failing
for the ostree.hotfix test and we don't know why:
https://github.com/coreos/fedora-coreos-tracker/issues/942
Let's run it once and check the failure. If it fails we will
always return a failure because we want to know, but we will
also run it with some retries to see if it succeeds in a
successive try for some reason or if it continues to fail.
> mantle/kola: retry rpm-ostree status for extra info

- mantle/kola/harness.go
We frequently have provider timeouts (especially on VexxHost
(OpenStack)). We want to consider a provider timeout as something
we can retry. One easy way to get this is to use the "big hammer"
and just retry once any failure to bring up machines.
Fixes https://github.com/coreos/coreos-assembler/issues/2637
> mantle/kola: try twice to bring up machines

- mantle/kola/tests/ostree/unlock.go
I.e. https://github.com/coreos/fedora-coreos-tracker/issues/942.
See individual commits.
> tests/ostree/unlock: try more things to help debug ostree.hotfix

- mantle/cmd/kola/testiso.go
Adding `miniso-install-nm` scenario to install with `-add-nm-key-keyfile` switch to test the `--copy-network` path
Discussion Ref: https://github.com/coreos/coreos-ci-lib/pull/102
Issue: https://github.com/coreos/coreos-assembler/issues/1987
> testiso: Add miniso-install-nm scenario

- src/cosalib/aliyun.py
This extends the `aliyun-replicate` and `buildextend-aliyun`
commands to support a `--public` option, which will mark any
uploaded images as publicly available.
Requires #2670
>  cosalib/aliyun: extend commands to mark images public

- src/cmd-compress
- src/cmd-list
- src/cmdlib.sh
> Miscellaneous patches to better support the `cosa buildfetch && cosa decompress && cosa run` workflow

- mantle/kola/harness.go
External tests don't seem to be timeout aware when
run-test-unit is running. This is because we execute the
command via `platform.Machine.SSH` and not `cluster.TestCluster.SSH`,
the latter of which is timeout aware.
> kola/harness.go: ensure external tests check for timeouts

- mantle/cmd/kola/devshell.go
During SSH bringup, we print the serial console output as it happens.
This output is currently clipped at a hardcoded 100 characters. So on
smaller screens/tmux panes, we'll spill over new lines easily.
Instead, query the terminal size and use that. While we're use, tweak
things in `displayStatusMsg` so that the clipping happens last so we
account for e.g. the status bit and stripped control characters.
> kola/devshell: clip status text to terminal width

- mantle/platform/platform.go
The `--json` option for `busctl` wasn't added until `systemd` v240, so
RHCOS based on RHEL 8 is unable to use that to look for failed units.
Change the logic to detect the `systemd` version and use the
appropriate method to find the failed units.
See: openshift/os#749
> mantle/platform: detect systemd version before checking for failed units

- mantle/kola/tests/misc/boot-mirror.go
- mantle/kola/tests/misc/multipath.go
The EFI dropins are not available on s390x and ppc64le.
The `/boot` dropin is not available on s390x.
Fixes f27b8aa00 ("kola/multipath: check bootfs dropins from
`rdcore bind-boot`").
Fixes 71edc49c0 ("kola/boot-mirror: check bootfs dropins from
`rdcore bind-boot`").
Fixes https://github.com/openshift/os/issues/760.
> kola/tests: make bootfs dropins check arch conditional

- gangplank/vendor/github.com/coreos/coreos-assembler-schema/cosa/cosa_v1.go
- gangplank/vendor/github.com/coreos/coreos-assembler-schema/cosa/schema_doc.go
- mantle/vendor/github.com/coreos/coreos-assembler-schema/cosa/cosa_v1.go
- mantle/vendor/github.com/coreos/coreos-assembler-schema/cosa/schema_doc.go
- schema/cosa/cosa_v1.go
- schema/cosa/schema_doc.go
- schema/v1.json
Fixes: 82701e472a01 ("Add VirtualBox OVA image").
> schema: regenerate and revendor for VirtualBox

- src/cosalib/kubevirt.py
Multiple additional image tags can be added to KubeVirt container images
when pushing with scopeo. This allows cusomizations like tagging images
with the stream name.
As a consequence it would be possible to e.g. reduce the documentation on how to get a working coreos image for kubevirt to a single command like this:
```
skopeo copy docker://quay.io/official/fcos:stable docker://quay.io/myorg/myfcossnapshot:snapshot1
```
> Allow adding additional tags for the final KubeVirt image

- mantle/platform/platform.go
Check the NRestarts value of the systemd unit which is activating 
state, if >=2 then report it is stuck in activating
See:
- https://github.com/coreos/coreos-assembler/issues/2798
> Add kola to detect when a systemd unit is stuck activating

- ci/prow-rhcos.sh
Hopefully will fix the `ci/prow/rhcos` context here.
> ci/prow-rhcos: Adjust for recent changes in openshift/os

- src/cosalib/ova.py
- src/image-default.yaml
Having a string boolean is more confusing and we should just convert the
boolean to string.
> ova: change string boolean to boolean

- README.md
The goal is to have this PR trigger the pipeline code here https://github.com/coreos/fedora-coreos-pipeline/blob/902419afd9a465a857c70f7d13880c720faa3f67/jobs/build-cosa.Jenkinsfile#L47-L79
> [rhcos-4.11] Little change README.md  to trigger a rebuild

- mantle/cmd/kola/options.go
Allow automatically parallelizing to the number of available CPUs.
> kola: support `auto` argument to `-j`/`--parallel`

- src/cmd-buildextend-metal
- src/create_disk.sh
Split out of https://github.com/coreos/coreos-assembler/pull/3039.
> Prep patches for s390x secex dm-verity

- mantle/platform/api/aws/ec2.go
We hit `InsufficientInstanceCapacity` when a zone does not have enough instances available. Adding functionality to iterate over other zones to look for available instances
Fixes: https://github.com/coreos/coreos-assembler/issues/3030
> mantle/kola: Search different zones if an instance type is unavailable

- mantle/platform/api/azure/api.go
In some cases (especially when Azure infra is having trouble)
resource groups can get created without some necessary tags. Let's
handle the case when a group doesn't have a "createdAt" tag so we
clean that resource group up and don't panic/segfault.
Fixes https://github.com/coreos/coreos-assembler/issues/3057
> mantle/platform: handle improperly created azure resource groups

- src/create_disk.sh
These repository options should be set from the start to ensure
they're honored for the initial deployment too.
Prep for using `sysroot.bootprefix = true` from
https://github.com/ostreedev/ostree/pull/2705
> create_disk: Set repository options early

- mantle/cmd/kola/kola.go
Tags are growing in importance and the output from this command
is already pretty wide.
> kola: List tags for tests by default

- src/create_disk.sh
On every architecture except s390x we rely on BLS i.e.
`sysroot.bootloader=none`.
However apparently there's a bug here if we try to deploy
with the `bootloader=zipl` from the start, instead of doing
it later.  I think that's an ostree bug, but for now rework
the code so that it works the same as before on s390x.
Closes: https://github.com/coreos/coreos-assembler/issues/3067
> create_disk: Fix s390x regression from previous change

- mantle/platform/api/azure/instance.go
In a recent test run in FCOS CI, we
noticed function CreateOrUpdate hung and took
30 minutes to terminate. Let's gate this piece
of code with a timeout.
> platform/azure/instance.go: make CreateOrUpdate timeout aware

- cmd/coreos-assembler.go
- cmd/update-variant.go
cosa: Fix buildextend- subcommands display in help
Also add the missing buildextend-extensions command.
---
cosa: Add update-variant sub command
Utility sub command to quickly set a variant to a given version.
> cosa: Add update-variant sub command

- mantle/platform/qemu.go
Still untested, opening draft now for visibility
> Explicitly set `-cpu Nehalem` on qemu when `COSA_NO_KVM=1`

- cmd/build-extensions-container.go
- src/build-extensions-oscontainer.sh
This came up as part of: https://issues.redhat.com/browse/ART-4750
> build-extensions-container: add version label to container

- mantle/cmd/kola/kola.go
multi-arch upgrade tests fail when there is no parent build available for that arch. 
Adding functionality to fetch the parent build and incase there is no parent build, default to testing-devel
Fixes: coreos/coreos-assembler#3017
> mantle/kola: fetch parent version for multi-arch upgrades

- Dockerfile
- build.sh
Blah, I guess I should have actually tested the full `Dockerfile` build.
Add a note for the unwary so it's less likely someone in the future makes the same mistake.
(cherry picked from commit b5ff922c99931b3ccc50b636213b8cbde175a77f)
dustymabe: had to manually fix merge conflict with nocache comment.
> [rhcos-4.9] Dockerfile: Also invoke `install_ocp_tools`

- mantle/cmd/kola/testiso.go
- mantle/platform/qemu.go
- mantle/platform/qmp_util.go
- src/cmd-buildextend-live
Split out of https://github.com/coreos/coreos-assembler/pull/3283. See individual commit messages.
> Prep patches for s390x ISO work

- src/build-extensions-container.sh
Fixes: https://github.com/openshift/os/issues/1080 for 4.12
Needs: https://github.com/openshift/os/pull/1081
(cherry picked from commit 7be86988e0f736bdf18e81f0dc42915ba34ad342)
See: https://github.com/coreos/coreos-assembler/pull/3274
> build-extensions-container: Pass variant as a container build argument

- mantle/kola/tests/rhcos/upgrade.go
The cincinatti graph is used to determine the latest OCP release. It was assumed that only the latest node would have no upgrade path in the graph but that is not the case. When upgrades are blocked, there can be two nodes that no have upgrade path. We need to choose the newest one in the upgrade test.
(cherry picked from commit 48f57ce00e1698c5c22279e8142d81afe9658ca0)
jlebon: trivial conflict resolution in import list
> [rhcos-4.11] tests: choose latest y-stream versioning for rhcos upgrade

- mantle/kola/harness.go
We have a case in https://bugzilla.redhat.com/show_bug.cgi?id=2164765 where we want to for now ignore a kernel warning across *all* tests.
Add a special case pattern `skip-console-warnings` that implements this.
I tested this by doing:
```
echo '<0>Oops: synthetic' > /dev/kmsg
```
in a test, and verified that the test fails without the pattern set, and succeeds with it.
xref https://issues.redhat.com/browse/COS-2000
> kola: Add `skip-console-warnings` for `kola-denylist.yaml`

- mantle/platform/api/aws/network.go
Aashish was getting an error when trying to run kola in a different AWS account where it was complaining about an incorrect IPv6 CIDR:
```
2023-01-30T20:50:05Z cli: Spawning instance failed: error resolving
security group: creating subnets: creating subnet: InvalidSubnet.Range:
The IPv6 CIDR '2600:1f18:edb:e906::/64' is invalid.
```
After some inspection it was apparent that he was seeing more security groups than I was in the `us-east-1` region. It turns out this is because local and wavelength availability zones exist [1].
I'm assuming the IPv6 CIDR error message is actually not the problem but more that a local zone exists that doesn't support IPv6. This is an untested theory.
Either way, let's just ignore non primary availability zones for now.
[1] …
> mantle/platform/aws: ignore local and wavelength availability zones

- go.mod
- go.sum
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/hpack/hpack.go
- vendor/golang.org/x/net/http2/server.go
- vendor/modules.txt
The newer version was missed in #3377.
> go.mod: update golang.org/x/net to 0.7.0

- mantle/kola/tests/misc/selinux.go
See: https://github.com/coreos/coreos-assembler/issues/3369
> tests/selinux.go: Remove SELinux Enforce

- docs/kola.md
> docs/kola: Doc `skip-console-warnings`

- mantle/kola/harness.go
- mantle/kola/register/register.go
- mantle/kola/tests/coretest/core.go
- mantle/kola/tests/crio/crio.go
- mantle/kola/tests/etcd/rhcos.go
- mantle/kola/tests/ostree/basic.go
- mantle/kola/tests/ostree/unlock.go
- mantle/kola/tests/podman/podman.go
- mantle/kola/tests/rhcos/upgrade.go
- mantle/kola/tests/rpmostree/deployments.go
> mantle/kola: drop RequiresInternetAccess Flag; add misc updates

- build.sh
- The Fedora 35 repository was archived, update it to the new location
> [rhcos-4.10] Update Fedora 35 repository location 

- build.sh
The Fedora repository was archived, update it to the new location
> [rhcos-4.9] build: Update Fedora repository location

- mantle/kola/harness.go
It's almost impossible to figure out if a test is denylisted or just
filtered out via arch/platform/tag exclusions. Let's break the
denylist processing to a separate function. Then we can do checks
before and after the denylist processing happens and we'll know
if the tests set is empty because of denylist processing or not.
> mantle/kola: rework denylist error/non-error cases again

- mantle/kola/tests/coretest/core.go
After rawhide was updated to systemd 254+ we started seeing failures in ppc64le/s390x where checking the ignition-ostree-growfs.service (part of the `basic/FCOSGrowpart` test would fail because multiple entries (lines) would be returned in the
`journalctl -o json MESSAGE_ID=39f53479d3a045ac8e11786248231fbf UNIT=ignition-ostree-growfs.service` call:
```
--- FAIL: basic (41.40s)
cluster.go:94: kolet:
2023-08-16T03:42:44Z kolet: Error getting journalclt output for ignition-ostree-growfs.service: invalid character '{' after top-level value. Out: {"JOB_ID":"68","SYSLOG_IDENTIFIER":"systemd","PRIORITY":"6","__SEQNUM":"384","__SEQNUM_ID":"18eec6fe008c40a9a6cffc2e9397e0b6","CODE_LINE":"796","_TRANSPORT":"journal","TID":"1","__REALTIME_TIMESTAMP":"1692157339095636","_SELINUX_CONTEXT":"kernel","SYSL …
```
> mantle/kola: workaround checkService race condition on systemd 254+

- mantle/kola/tests/ostree/basic.go
This test was trying to cross-check `ostree admin status` and `rpm-ostree status` which is well-intentioned but parsing the former with regexps is just not sustainable and actively broke with trying to switch to a container deployment in https://github.com/openshift/os/pull/657
I don't think this check is really worth maintaining; if we somehow broke `ostree admin status` a whole lot of other upstream tests would start failing.
> tests: Drop `ostree.basic`

- build.sh
This reverts commit 60ea871211b4606c530df0544767c0835be9cc65.
The underlying issue has now been resolved:
https://pagure.io/releng/issue/11499#comment-870249
> [rhcos-4.9] Revert "Temporarily use kojipkgs compose locations for F34 updates repos"

- mantle/cmd/kola/testiso.go
Add a test case that verifies the new ISO+FIPS code works; this covers the code that lives in openshift/os.
Depends: https://github.com/openshift/os/pull/1356
> testiso: Add FIPS test (RHCOS only right now)

- mantle/platform/qemu.go
The context is to hacky code to test https://github.com/openshift/os/pull/1346
According to Colin's pointer
https://github.com/openshift/os/pull/1350#issuecomment-1708486101
The cdrom should be `scsi-cd`, as `ide` device can not be hotplugging. So should not pass `-cdrom` to qemu as it is `ide` by default which could not work.
```
[coreos-assembler]$ env COSA_TEST_CDROM_UNPLUG=5s cosa run qemu.qcow2 --debug -- \
-drive id=cdrom0,if=none,readonly=on,file=/srv/test.iso \
-device virtio-scsi-pci,id=scsi0 \
-device scsi-cd,bus=scsi0.0,drive=cdrom0
...
2023-09-12T10:54:08Z platform: get cdrom id /machine/peripheral-anon/device[2]
[STARTUP] '2023-09-12T10:54:13Z platform: delete cdrom
...
[core@cosa-devsh ~]$ ls /dev/sr0
ls: cannot access '/dev/sr0': No such file or directory
```
> qemu: add `env COSA_TEST_CDROM_UNPLUG` to test cdrom unplug

- mantle/cmd/kola/testiso.go
Backports now that 4.14 is branched.
> [rhcos-4.14] backport testiso FIPS test

- mantle/kola/harness.go
Today we see an issue when trying to do a rerun when a tag was provided because of the filtertests function logic where all the tests matching the tag get rerun, not just the tests that failed. Let's limit the testsBank when doing the rerun so only failed tests can possibly get selected/run.
Fixes https://github.com/coreos/coreos-assembler/issues/3041
> mantle/kola: limit testbank when doing a rerun

- build.sh
- src/0001-create-org.osbuild.bootupd-stage.patch
- src/0001-mounts-ostree.deployment-rework-unmounting.patch
- src/0001-osbuild-mpp-fix-float-correction.patch
- src/0001-stages-org.osbuild.mkfs.ext4-add-ext4-options.patch
- src/0001-stages-org.osbuild.ostree.config-support-bls-append-.patch
- src/0002-mounts-ostree.deployment-rename-var-root-deploy_root.patch
- src/0002-stages-bootupd-add-schema-test.patch
- src/0003-mounts-ostree.deployment-use-target-instead-of-tree.patch
- src/0003-stages-bootupd-add-tests-for-existing-behavior.patch
- src/0004-mounts-ostree.deployment-support-deployments-on-moun.patch
- src/0004-stages-bootupd-refactor-test-to-separately-test-beha.patch
- src/0005-Create-stages-org.osbuild.chattr-stage.patch
- src/0005-stages-bootupd-support-installing-to-a-partition-of-.patch
- src/cmd-buildextend-metal
- src/cmdlib.sh
- src/coreos.osbuild.mpp.yaml
- src/create_disk.sh
- src/runvm-osbuild
This builds on top of https://github.com/coreos/coreos-assembler/pull/3694#discussion_r1453678384
> osbuild: updates and rework to support more image.yaml config values

- .cci.jenkinsfile
- Dockerfile
- src/cmdlib.sh
Incorporate the platforms JSON file into the container,
as it is essential for our OSBuild requirements.
> [rhcos-4.15] Add platforms JSON as part of the container

- build.sh
- src/0001-mount-ostree.deployment-Fix-ostree-deployment-call.patch
- src/0001-ostree-add-convenience-function-for-using-default-OS.patch
- src/0001-stages-org.osbuild.qemu-make-qcow2-compression-optio.patch
- src/cmdlib.sh
- src/coreos.osbuild.aarch64.mpp.yaml
- src/coreos.osbuild.ppc64le.mpp.yaml
- src/coreos.osbuild.s390x.mpp.yaml
- src/coreos.osbuild.x86_64.mpp.yaml
> osbuild: backport a few upstream PRs; use snapshot qcow for extensions

- build.sh
To test out composefs faster.
xref https://github.com/coreos/fedora-coreos-config/pull/2856#issuecomment-1946960419
> build: Also pull in ostree from updates-testing

- mantle/cmd/kola/spawn.go
This will allow us to pass commands directly to kola spawn. It will then run the command on the brought up instance and exit success or failure based on that. Example:
```
[coreos-assembler]$ cosa kola spawn ls /root/
kola -p qemu spawn ls /root/ --output-dir tmp/kola
<<<< STDOUT >>>>
<<<< STDERR >>>>
ls: cannot open directory '/root/': Permission denied
<<<<<<<<>>>>>>>>
Error: running command failed: Process exited with status 2
2024-04-11T15:03:40Z cli: running command failed: Process exited with status 2
failed to execute cmd-kola: exit status 1
```
> mantle/kola: support running commands via kola spawn

- src/cosalib/aws.py
Add the ability to add `aws-credentials` file to `list-regions` and `copy-image` commands for aws_run_ore_replicate.
> Add aws-credentials to `list-regions` and `copy-image`

- mantle/cmd/kola/resources/iscsi_butane_setup.yaml
- mantle/cmd/kola/testiso.go
I had originally started going through iscsi_butane_setup.yaml without the help of the description in testiso.go and I decided to document things myself. Later I found the better description in testiso.go, so let's mention it at the top of the Butane config.
Also made a few tweaks.
> mantle/kola: add a few comments/tweaks to iscsi test

- mantle/kola/tests/crio/crio.go
- mantle/kola/tests/misc/network.go
See individual commit messages. 
Part of https://github.com/openshift/os/issues/799.
> Various test tweaks to make compatible with `--oscontainer`

- Dockerfile
Since our stuff depends on this.
> build: Add ENV container=oci

- build.sh
- docs/kola/external-tests.md
- mantle/cmd/kolet/kolet.go
- mantle/kola/cluster/cluster.go
- mantle/kola/harness.go
- mantle/kola/tests/ignition/resource.go
- mantle/kola/tests/ignition/security.go
- mantle/kola/tests/upgrade/basic.go
- src/0001-hacks-for-coreos-selinux-issues.patch
- src/0001-stages-coreos.platform-use-shutil.copy.patch
- src/0001-stages-selinux-don-t-require-file_contexts-if-labels.patch
- src/cmdlib.sh
- src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml
- src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml
- src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml
- src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml
- src/secex-genprotimgvm-scripts/runvm.sh
cherry pick of d3302e0fc9bedec2d4e935e3528eb5abd44e7ae8 with some merge conflict resolution
> [rhcos-4.16] workaround selinux issues with osbuild

- mantle/kola/tests/ostree/sync.go
Fixes https://github.com/openshift/os/issues/1744
> test: make `ostree.sync` + `composefs` working

- build.sh
Otherwise we get a use of unitialized variable in the s390x case.
> build.sh: set frozendeps to some value

- src/osbuild-manifests/platform.ibmcloud.ipp.yaml
- src/osbuild-manifests/platform.openstack.ipp.yaml
We needed the zipl pieces for s390x. Fixes 79210da 224bef3.
> osbuild: fix openstack/ibmcloud s390x images

- src/cmdlib.sh
We often want to be able to fast-track packages from later releases into earlier composes. But we can't just enable the whole repo because that'll pull in *every* package.
So far, we've taken the approach of (1) asking ART to tag some package in the plashet, and then (2) add that package under a copy of the plashet definition in its `includepkgs=` directive so that it effectively becomes a "RHEL-versioned" view of the plashet. The problems with that are:
1. It's painful and slow to have to routinely tag packages via request tickets.
2. It's error-prone. Nothing prevents rpm-ostree from still picking an rhaos version of the package if it's higher NEVRA.
3. It's extremely painful to keep the production repo definitions and the CI definitions in sync. In practice, they just go out of skew. …
> cmdlib.sh: add support for a `fast-tracks.yaml` in src config

- OWNERS
Add tlbueno user as an approver
> OWNERS: Add tlbueno to approvers

- .cci.jenkinsfile
- src/cmd-buildextend-aliyun
- src/cmd-buildextend-applehv
- src/cmd-buildextend-aws
- src/cmd-buildextend-azure
- src/cmd-buildextend-azurestack
- src/cmd-buildextend-digitalocean
- src/cmd-buildextend-exoscale
- src/cmd-buildextend-gcp
- src/cmd-buildextend-hyperv
- src/cmd-buildextend-ibmcloud
- src/cmd-buildextend-kubevirt
- src/cmd-buildextend-nutanix
- src/cmd-buildextend-openstack
- src/cmd-buildextend-vultr
- src/cmd-imageupload-aliyun
- src/cmd-imageupload-aws
- src/cmd-imageupload-azure
- src/cmd-imageupload-gcp
- src/cmd-imageupload-powervs
- src/cmd-ore-wrapper
> switch osbuild defaults; add cosa imageupload-<platform> commands

- mantle/kola/tests/ostree/sync.go
Improve the code according to Dusty's pointer:
https://github.com/openshift/os/issues/1720#issuecomment-2695148917
Before doing the reboot, drop NFS port traffic on server to get more logs from client, instead of down the NIC.
> test: improve `ostree.sync` to get more logs from the system

- mantle/cmd/kola/testiso.go
We adjust test to be compatible with both mpath friendly and non-friendly names.
> kola/testiso: Adapt test for mpath name variations

- src/download-overrides.py
- Add option `--downloaddir` (default is `overrides/rpm`)
- Add option `lockfiledir` (default is `src/config`)
Inspired by JB's comment:
https://github.com/coreos/fedora-coreos-config/pull/3581#discussion_r2189434897
Co-developed: dmabe@redhat.com
> overrides: remove the required `builds` and `src/config`
