mantle/platform/qemu.go
This is helpful to make sure kola is passing the args one expects, as
well as a quick and easy way to sanity-check e.g. how much memory the
VMs are taking.
=> platform/qemu: add debug logging of qemu lifecycle and args

mantle/kola/harness.go
With #1768, on ppc64le and aarch64, we now request 8G of RAM for *all*
external tests, even trivial ones like `misc-ro`.
We already have platform defaults in `platform/qemu`. Let's rely on
those if the test doesn't declare any memory requirements (this is done
implicitly by this code by having 0 * 2 still being 0). If it *does*,
then as a heuristic, just multiply by 2 for ppc64le and aarch64 to a max
of 8G.
Obviously long term, we need to clean this up by having the test provide
a more symbolic requirement rather than a specific memory amount. (This
could be "flavours", or it could just be e.g. tags like
"reprovisions-root"). (There's also [the zram
change](https://github.com/coreos/fedora-coreos-config/pull/768) which
should help a lot lowering the memory requirements for …
=> kola: stop requesting 8G of RAM for all external tests on ppc64le and aarch64

src/cmd-buildextend-live
Collect ISO files which include karg embed areas, then inject their
offsets into the System Area right behind the initramfs header. This
information will be used by `coreos-installer iso embed-kargs`.
=> buildextend-live: add karg embed area offsets to header

src/cmd-buildextend-live
That should make it even faster to iterate on the live ISO, because we
don't incur the upfront cost of generating a metal4k image, as well as
the recurring cost of osmet generation at each iteration.
=> buildextend-live: make metal4k image optional if --fast

src/cmd-buildextend-live
I.e. make it of length `$karg_embed_area_length` with the overflow area
being `#` so that we can use the same function on the coreos-installer
side to read them.
=> buildextend-live: make default kargs file look the same

src/cmd-buildextend-live
For BIOS systems, we're already adding an MBR and boot sector to the ISO image so it can be dd'ed to a USB stick and booted as a hard disk.  For UEFI systems, we're already generating an ESP and setting it as an additional El Torito image.  For some UEFI firmware (e.g. EDK II) that seems to be sufficient, but we should also create a GPT with an ESP wrapping that El Torito image, for firmware that doesn't support El Torito on hard disks.
For https://github.com/coreos/fedora-coreos-tracker/issues/707.
=> buildextend-live: hybridize live ISO for UEFI boot

mantle/fcos/metadata.go
Prep for rebasing on https://github.com/cgwalters/stream-metadata-go
=> mantle: Clean up exported functions for stream/releases

mantle/cmd/plume/release.go
The imported package will be `release.` so rename this local
variable to avoid a clash.
=> plume: Rename internal variable in prep for using stream-metadata-go

src/cmd-buildextend-live
E.g. on PowerPC, we delete a bunch of files from the ISO which we don't
need. This throws off the dictionary mapping we previously built which
assumes all the files with karg embed areas still exist.
Add a filtering step to drop the files which no longer exist before
writing out the header in the System Area.
=> buildextend-live: fix crash when running on !x86_64

src/cmd-buildextend-live
We need to omit the last comment character from the karg embed area so a maximum-size embed doesn't cause the bootloader to try to execute `COREOS_KARG_EMBED_AREA` as a command.
While we're here, change the karg embed area magic number so ISOs built without the previous commit or b48e428 can be rejected by coreos-installer.
=> buildextend-live: fix off-by-one calculating karg embed area size; change magic number

mantle/cmd/kola/kola.go, mantle/cmd/plume/release.go, mantle/fcos/metadata.go, mantle/go.mod, mantle/go.sum, mantle/platform/api/packet/api.go, mantle/vendor/github.com/coreos/stream-metadata-go/LICENSE, mantle/vendor/github.com/coreos/stream-metadata-go/fedoracoreos/fcos.go, mantle/vendor/github.com/coreos/stream-metadata-go/fedoracoreos/internals/fcosinternals.go, mantle/vendor/github.com/coreos/stream-metadata-go/release/release.go, mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream.go, mantle/vendor/modules.txt
The idea is https://github.com/cgwalters/stream-metadata-go/
moves to the coreos/ GH org and becomes the canonical place
for this stuff, shared between our own internal tools as well
as used by 3rd parties.
=>  Use coreos/stream-metadata-go

mantle/cmd/kola/options.go, mantle/fcos/metadata.go, mantle/platform/platform.go
This makes use of the new stream-metadata-go bindings to
automatically fetch the latest AMI for a stream.
E.g. this full command works for me:
```
$ kola spawn --stream stable -b fcos -p aws --aws-profile openshift-dev --aws-region us-east-2
```
I added a convenience internal API to fetch the artifacts for
the current architecture, but actually in the case of AWS
we *could* launch cross-architecture - if we had `aarch64`
FCOS AMIs, which we don't yet.
I'm targeting AWS for this because the whole "find AMI ID" thing
is a great use case for dynamic streams.
Now, generalizing this more is really going to want to
dedup code with
https://github.com/coreos/fedora-coreos-stream-generator/
which will come later.
=> kola: Add support for `kola --stream stable -p aws ...`

src/cmd-generate-release-meta
This is a straight up import of almost-exactly the contents
of https://github.com/coreos/fedora-coreos-releng-automation/blob/master/coreos-meta-translator/trans.py
Prep for adding more stream tooling into coreos-assembler as
part of https://github.com/openshift/os/issues/477
=> Import FCOS trans.py that converts meta.json → release.json

mantle/kola/tests/coretest/core.go
Make it check `ignition-ostree-growfs.service` now just like FCOS. Keep
the tests separate still so that we can check different sizes.
See: https://github.com/openshift/os/pull/484#issuecomment-760511370
=> kola: fix RHCOS growpart test

src/grub.cfg
Petitboot doesn't support `-e` and doesn't support testing for a bare device without a path component.
https://bugzilla.redhat.com/show_bug.cgi?id=1915540#c7
=> grub: make boot RAID check Petitboot-compatible

docs/build-process-mermaid.md, docs/building-fcos.md
Fixes: 5d5dae62 docs: Fix build-process.svg linking in building-fcos.md
=> docs: Use fixed img path to workaround GitHub/Jekyll rendering

mantle/kola/tests/misc/multipath.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/qemu.go
This is a straightforward test which boots a QEMU instance with a
multipathed primary disk, and then verifies that it can reboot into
multipath mode fine with the right kargs added.
=> kola: add multipath test

src/cmd-generate-release-meta
Should be `build_id`, not `build`. See:
https://github.com/coreos/fedora-coreos-streams/issues/247#issuecomment-762360677
=> cmd-generate-release-meta: fix field name

mantle/platform/metal.go
path of s390image has changed in the latest packages to `/usr/bin`. Found this when testing #2014.
=> testiso: update mk-s390image path

build.sh
The 5.10 kernel causes a regression where we lose virtio ports on s390x,
which breaks builds. Instead of freezing it only on s390x, let's just do
it across the board to be consistent.
=> build.sh: freeze kernel to 5.9.16-200.fc33

build.sh
The 5.10 kernel causes a regression where we lose virtio ports on s390x,
which breaks builds. Instead of freezing it only on s390x, let's just do
it across the board to be consistent.
(cherry picked from commit e08e7665bbfee7aa00fe9889b4933fdab711fd4c)
=> [4.6] build.sh: freeze kernel to 5.9.16-100.fc32

src/cmd-artifact-disk
Fixing:
```
cosa artifact-disk manual --image_format xxx --image_suffix xxx --platform xxx
```
The command above did not work because of an error in arg parsing:
`"manual" in args` was always `false`, because `manual` was the name of a subparser,
not an arg of the parser.
=> cmd-artifact-disk: fix cosa artifact-disk manual

mantle/cmd/plume/cosa2stream.go, mantle/go.mod, mantle/go.sum, mantle/vendor/github.com/coreos/stream-metadata-go/release/release.go, mantle/vendor/github.com/coreos/stream-metadata-go/release/translate.go, mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream.go, mantle/vendor/modules.txt, src/cmd-generate-release-meta
Part of implementing https://github.com/openshift/os/issues/477
For now I decided to go directly from cosa to a stream because:
- The cosa2release code is in a separate repo in Python
- The RHCOS pipeline currently generates "one big build" anyways
=> plume: add cosa2stream

mantle/go.mod, mantle/go.sum, mantle/vendor/github.com/coreos/stream-metadata-go/release/release.go, mantle/vendor/github.com/coreos/stream-metadata-go/release/translate.go, mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream.go, mantle/vendor/modules.txt, src/cmd-generate-release-meta
This updates the vendor of stream-metadata-go and adds
translation for `uncompressed-sha256` so we can use it in
`openshift-install`.
See https://github.com/coreos/stream-metadata-go/pull/11
=> Add uncompressed-sha256 to release -> stream translation

gangplank/ocp/worker.go
Gangplank was panicking in unbounded pod mode because it was
attempting to access fields of a nil pointer to a struct.
=> gangplank:  fix runtime panic in unbounded pod mode

mantle/cmd/plume/cosa2stream.go, mantle/go.sum, src/cmd-generate-release-meta
Trying to port `openshift-install` we have all 3 of x86_64/s390x/ppc64le,
but they have different build IDs.
Now this works:
```
$ plume cosa2stream --name rhcos-4.7 https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.7/47.83.202012030221-0/x86_64/meta.json https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.7-s390x/47.83.202012030410-0/s390x/meta.json https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.7-ppc64le/47.83.202012030110-0/ppc64le/meta.json | jq .
```
=> plume: Allow architecture divergence for releases

src/cmd-build-fast
There are some metadata fields that Zincati requires during
its initialization, namely `coreos-assembler.basearch` and
`fedora-coreos.stream`. Add these fields so Zincati works in
images built using `cosa build-fast`.
=> cmd-build-fast: Keep metadata from previous commit

src/cmd-buildextend-live, src/create_disk.sh, src/gf-fsck, src/libguestfish.sh, src/osmet-pack
This is obsolete now that RHCOS has moved to LUKS-via-Ignition:
https://github.com/openshift/os/pull/436
Let's remove those paths to clean up the code.
=> Fully drop support for building images with root-on-LUKS

build.sh
This reverts commit e08e7665bbfee7aa00fe9889b4933fdab711fd4c.
Fixed kernel landed via https://bodhi.fedoraproject.org/updates/FEDORA-2021-e04cde3ff0
Fixes: #2003
=> Revert "build.sh: freeze kernel to 5.9.16-200.fc33"

src/buildroot-reqs.txt
I want to get a sanitizer build of ostree/rpm-ostree going
again, let's add these to the CI buildroot.
Also pull in parallel/gjs which are used by both projects, so
we can avoid using package installs in the CI happy path.
=> buildroot: Add libasan, libtsan and parallel+gjs

Dockerfile
For https://bodhi.fedoraproject.org/updates/FEDORA-2021-937b45bf55,
which is in the continuous tag.
=> Dockerfile: tickle Quay.io caching

src/buildroot-reqs.txt
Like ASAN/UBSAN, static analysis should be part of every C/C++
project.
=> buildroot: Add clang-analyzer

mantle/platform/platform.go
We shouldn't ship an OS that boots up and has a SELinux denial
by default; it makes us look less than fully competent.
The motivation for this is
https://bugzilla.redhat.com/show_bug.cgi?id=1900898
Though it turns out we do have a SELinux denial in FCOS by
default now, that's
https://bugzilla.redhat.com/show_bug.cgi?id=1903335
So this can only merge once that's fixed.
=> mantle: Check for SELinux AVCs just like systemd failed units

src/cmd-artifact-disk, src/cosalib/qemuvariants.py
Add the ability to set the virtual size in the qemu variant configuration or via a switch in manual mode when using `cmd-artifact-disk`. This also sets the default virtual size for `ibmcloud` artifacts to 100G per request.
Done via a local build off the main branch.
```
$ cosa build qemu
<snip/>
$ cosa buildextend-ibmcloud
<snip/>
$ cosa buildextend-openstack
<snip/>
[coreos-assembler]$ find . -name "*qcow2*"
./builds/.../rhcos-48...-qemu.x86_64.qcow2
./builds/.../rhcos-48...-ibmcloud.x86_64.qcow2
./builds/.../rhcos-48...-openstack.x86_64.qcow2
$ for x in `find . -name "*qcow2*"`; do echo -n `basename $x` " "; qemu-img info $x | grep "virtual size"; done
rhcos-48...-qemu.x86_64.qcow2      virtual size: 16 GiB (17179869184 bytes)
rhcos-48...-ibmcloud.x86_64.qcow2  virtual size: 100 GiB …
```
=> Allow for setting virtual_size per qemu variant

mantle/cmd/kola/options.go, mantle/sdk/repo.go, src/cmd-build-fast
Having a toplevel file for the `fastbuild-$x.qcow2` clutters
things; let's stick the file in a `.cosa` dir that can be more
easily added to upstream `.gitignore`.
And while we're here, change kola to automatically detect
the presence of a `.qcow2` here if no other option is specified.
This then works:
```
$ cosa build-fast
$ cosa run
```
=> build-fast: Use .cosa dir, honor in cosa/kola

src/cmd-artifact-disk, src/cosalib/qemuvariants.py
Backport of https://github.com/coreos/coreos-assembler/pull/2041. Same local test was done.
Add the ability to set the virtual size in the qemu variant configuration or via a switch in manual mode when using `cmd-artifact-disk`. This also sets the default virtual size for `ibmcloud` artifacts to 100G per request.
Done via a local build off the main branch.
```
$ cosa build qemu
<snip/>
$ cosa buildextend-ibmcloud
<snip/>
$ cosa buildextend-openstack
<snip/>
[coreos-assembler]$ find . -name "*qcow2*"
./builds/.../rhcos-48...-qemu.x86_64.qcow2
./builds/.../rhcos-48...-ibmcloud.x86_64.qcow2
./builds/.../rhcos-48...-openstack.x86_64.qcow2
$ for x in `find . -name "*qcow2*"`; do echo -n `basename $x` " "; qemu-img info $x | grep "virtual size"; done
rhcos-48...-qemu.x86_64.qcow2      virtual …
```
=> 4.7: Allow for setting virtual_size per qemu variant

docs/mantle/plume.md, mantle/cmd/plume/fcos.go, mantle/cmd/plume/fedora.go, mantle/cmd/plume/prerelease.go, mantle/cmd/plume/types.go, mantle/sdk/repo.go, mantle/system/arch.go
It's a CL remnant.  The last user is plume pre-release, which has been using it to set and then override a default command-line argument.  Fix that, and while we're here, have plume stop using the term `board`.
=> mantle: drop PortageArch()

mantle/cmd/kola/options.go
This should fix rpm-ostree CI that was broken by
https://github.com/coreos/coreos-assembler/pull/2040
Basically we need to ignore the empty string (meaning "not found")
as a return value if there's no local build.
Also while we're here, strengthen the check to not even look
for a local build if the qemu disk is already set.
=> kola: Fix localbuild detection

Dockerfile
For rawhide builds, we want newer fedora-gpg-keys:
https://github.com/coreos/fedora-coreos-config/pull/859#issuecomment-781648455
=> Dockerfile: echo 1 > /quay.io/coreos-assembler/drop_caches

src/deps.txt
Prep for https://github.com/coreos/coreos-assembler/pull/2028. (Had to
split this out because Prow tests don't rebuild the container from
scratch but use the buildroot image.)
=> deps.txt: add python3-createrepo_c

docs/working.md
For clusters "born in" 4.6 the bootimage enables nested virt
by default.  And I forked the kvm-device-plugin and cleaned
it up, which is what we've since enabled on the "build02" cluster
in the "api.ci" OpenShift Prow cluster.
=> docs: Update GCP instructions for 4.6 and my kvm-device-plugin fork

src/cmd-build-fast
I intended there to be just one so e.g. one can just glob `*.qcow2`
to find the latest.
=> build-fast: Fix removal of previous builds

mantle/cmd/kola/options.go, mantle/kola/harness.go, mantle/platform/platform.go
This will allow us to e.g. bypass SELinux denials when we need
to, e.g.  https://github.com/coreos/fedora-coreos-tracker/issues/751
The intention is that for FCOS releases we would drive this declaratively
in the pipeline, something like a:
```
kola:
no-default-checks: 33.20210201.3.0
```
to automatically suppress checks for builds with that version number.
=> kola: Add --no-default-checks

mantle/cmd/plume/cosa2stream.go, src/cmd-generate-release-meta
When I was writing this originally I was focused on the goal
of converting cosa metadata to stream format, hence the name etc.
However upon trying to use this for openshift/installer I realized
something important: *after* we do the switch, the installer git
will be a "source of truth" for the pinned bootimages.
The expected user story here will be e.g. "update x86_64 to &lt;version&gt;".
So now we support this flow:
```
$ plume cosa2stream --distro rhcos --output data/data/rhcos.json x86_64=48.83.202102192019-0 s390x=47.83.202102090311-0
```
which hardcodes the URL we use now, and makes the arch+version mapping
explicit.  We also paper over the fact that currently for RHCOS
there are separate cosa builds per architecture; the non-x86_64 ones
are named e.g `rhcos-4.8-s390x` instead of …
=> cosa2stream: Rework to better optimize openshift/installer flow

.cci.jenkinsfile
buildImage will build coreos-assembler
and create an imageStream for it.
In this way we can have two distinct phases,
building cosa and using it in the other stages.
=> Use buildImage from coreos-ci-lib

.cci.jenkinsfile
Use coreos-ci-lib to eliminate code duplicity across the CIs
=> Use coreos-ci-lib to run Build FCOS

.cci.jenkinsfile
=> Use coreos-ci-lib to run Kola QEMU

src/cmdlib.sh
Working on https://github.com/coreos/rpm-ostree/pull/2619
I wanted to `yum -y remove rpm-ostree` before installing our
override binaries, but that breaks things because of this cosa
check for installed packages.
Yes...we could change the rpm-ostree CI flow to build RPMs but
that has a wide array of tradeoffs and I don't want to hard require
it.  (Among the tradeoffs for example is that RPM insists on compressing
everything into an archive, which if you're then in an edit-compile-debug
cycle you immediately uncompress, which is silly)
Also incidentally this "rpm -q all the things" is one of the top
contributors to the CLI latency on cosa commands.
=> Add COSA_SUPPRESS_DEPCHECK to turn off "rpm -q all the things"

.cci.jenkinsfile
=> Use coreos-ci-lib to build metal artifacts

gangplank/cmd/pod.go, gangplank/ocp/bc.go, gangplank/ocp/cosa-pod.go, gangplank/ocp/filer.go, gangplank/ocp/return.go, gangplank/ocp/worker.go, gangplank/spec/stages.go
To prepare for doing distributed builds via Gangplank, stages need to be
simplified. Previously, work assigned to pods was a calculated from all stages;
this proved to be buggy. Rather, each stage is assigned its own pod.
Further enhancements:
- If a stage fails, remaining stages are aborted.
- If a required artifact is defined, stages will wait for it to appear
on the master pod. A future PR will will build on this.
- SHA256 and size is used to determine whether to upload a remote file
that already exists when overwrite is set to true.
- Minio's working files are pruned after minio is completely shutdown.
- The finalize does not require any artifacts.
- Cloud stages only require qemu.
=> Gangplank: Prepare for Distributed Builds

gangplank/ocp/bc.go, gangplank/ocp/cosa-pod.go
This prevents Podman mode from swallowing errors and continuing execution.
=> Gangplank: make podman mode errors fatal

.cci.jenkinsfile
=> Use coreos-ci-lib to run cosa commands

mantle/cmd/kola/options.go, mantle/kola/harness.go, mantle/platform/platform.go
This reverts commit fe010b25a5ec4f4e16999e926f90b4995e8525eb.
This is causing us a lot of pain because there isn't a way to override
failures.
We'll re-add it once we have that ability.
=> Revert "mantle: Check for SELinux AVCs just like systemd failed units"

.cci.jenkinsfile
=> Use coreos-ci-lib to run `kola testiso`

mantle/kola/tests/misc/boot-mirror.go
The same reasoning that applies to `coreos.boot-mirror.luks` also
applies to `coreos.boot-mirror`: today we're hardcoding an Ignition
config which is x86 specific.
=> coreos.boot-mirror: only run on x86_64

.cci.jenkinsfile
=> Use coreos-ci-lib to run parallel commands

.cci.jenkinsfile
After the refactor done to use coreos-ci-lib we
don't need this anymore.
=> Remove cosa_cmd function

gangplank/cmd/main.go, gangplank/ocp/worker.go, gangplank/spec/render_test.go, gangplank/spec/stage_test.go, gangplank/spec/stages.go, gangplank/spec/tmpl.go
This change extends the templating by using a new struct `RenderData` to hold both the JobSpec and discovered meta.json. The JobSpec fields accessible via `{{.JobSpec.<PATH>}}` and meta.json as `{{.Meta.<PATH>}}`
This change should make the work for creating synthetic publication commands via templates. 
TODO: this lays the foundation for having Gangplank operate on different builds, not just the latest.
=> Gangplank: Allow access in template to JobSpec and meta.json

src/cmd-build, src/cmd-fetch, src/cmdlib.sh
In FCOS, we use "override" lockfiles to pin packages to certain
versions. Right now, we have separate overrides for each base arch we
(eventually want to) support. But that makes maintaining the overrides
cumbersome because of all the duplication.
Now that rpm-ostree supports this, let's make use of it. Add support for
a `manifest-lock.overrides.yaml` arch-independent override file.
=> Add support for arch-independent lockfile overrides

gangplank/cmd/pod.go, gangplank/ocp/cosa-pod.go, gangplank/ocp/worker.go, gangplank/spec/jobspec.go, gangplank/spec/jobspec_test.go
This gives Gangplank the ability to fetch and use a remote yum/dnf
repository via the jobspec OR a CLI flag.
Example:
gangplank pod -A base --repo http://base-4-8-rhel8.ocp.svc.cluster.local
All worker pods will have the repo(s) exposed at `src/config/*.repo`.
=> Gangplank: installation repos via JobSpec or CLI

src/cmd-init
This skips dotfiles from empty directory check logic in init. That
way, it allows using coreos-assembler together with existing `.envrc`
local configuration.
Ref: https://direnv.net/
=> cmd/init: ignore dotfiles in working directory

Makefile, gangplank/cosa/v1.go, mantle/cosa/cosa_v1.go, mantle/cosa/schema_doc.go, src/schema/v1.json
While working on Gangplank, I wanted to add in a validation function.  The problem, though, the schema converts `integars` to `int` for GoLang which caps the max size to ~2.4Gb files. The only usable type is `number` which corresponds to a `float64`. This isn't too bad consider that GoLang [1] uses `float64` when unmarshalling "json numbers" into an interface.
This also fixes drift in the Gangplank understanding of the schema.
[1] https://golang.org/pkg/encoding/json/#Unmarshal
=> Schema: change size to float64

src/cmd-buildextend-metal, src/cmdlib.sh, src/libguestfish.sh
POWER builds are failing to run `coreos-assembler buildextend-extensions` due libguestfish call
- POWER needs to use the libguestfish wrapper in order to fix
the SMT value.
- For more info check: https://github.com/coreos/coreos-assembler/pull/1553
=> cmdlib: fix impl_rpmostree_compose for POWER

Dockerfile
I want to get v2021.3 into cosa for
https://github.com/coreos/fedora-coreos-config/pull/884.
=> Dockerfile: defenestrate Quay.io cache for new rpm-ostree release

gangplank/cosa/build.go, gangplank/cosa/schema_test.go, gangplank/ocp/bc.go, gangplank/ocp/return.go, gangplank/ocp/worker.go
Gangplank has never handled running `cosa build` against the same build
directory well. This fixes that by ensuring that all builds have known
build meta (ostree-commit-object, manifest-lock, and commitmeta.json)
uploaded to the worker pods.
=> Gangplank: allow multiple builds in the builds dir

gangplank/spec/stages.go
When creating synthetic stages via the commandline, only a single
artifact can be built in a stage. This change allows for N artifacts to
be created in the same stage. Builds are orderd.
```
$ gangplank generate -A base+metal4k+metal -A aws -A gcp -A finalize
INFO[0000] Gangplank: COSA OpenShift job runner, 2021-03-17.4b525923~dirty
job:
strict: true
recipe:
git_ref: testing-devel
git_url: https://github.com/coreos/fedora-coreos-config
stages:
- id: Generated Stage in Execution Order 1
description: Stage 1 execution for base,metal4k,metal
build_artifacts: [metal4k, metal, base]
execution_order: 1
- id: Generated Stage in Execution Order 3
description: Stage 3 execution for aws
requires_artifacts: [qemu]
build_artifacts: [aws]
execution_order: 3
- id: Generated Stage in Execution Order 3 …
```
=> Gangplank: allow for creating multiple artifacts in the same stage

gangplank/Makefile
This fixes a problem where a newer version of other COSA components
causes a Gangplank to change its build date and commit tag. Instead, the
commit date and the last commit short hash of the last Gangplank change
will be used.
=> Gangplank: use git date and last change for version

mantle/platform/qemu.go
In f34, the SELinux policy prevents a systemd service with
`ExecStart=journalctl` from watching the journal logs, which means that
our `mantle-virtio-journal-stream.service` doesn't work. This in turn
breaks `cosa run`'s SSH logic.
Hack around this by just wrapping it in a bash instance.
For more information, see the linked RHBZ.
=> mantle/qemu: hack around SELinux violation in virtio journal service

mantle/platform/api/aws/images.go
With the ongoing effort to put the pieces together for supporting OCP ARM cluster on AWS,
this is an essential piece needed to build the VM image through the `cosa buildextend-aws`
command.
Partly addresses https://github.com/coreos/coreos-assembler/issues/2076
=> mantle/aws/images: Support building aarch64 VM images and AMI

gangplank/cmd/minio.go, gangplank/cmd/pod.go, gangplank/ocp/bc.go, gangplank/ocp/filer.go, gangplank/ocp/filer_test.go, gangplank/ocp/pod.go, gangplank/ocp/remotes_test.go, gangplank/spec/jobspec.go
With our current CI stages for RHCOS and FCOS builds, each build
generates logs per-stage. Gangplank is perfectly capable of running
stages itself and keeping logs straight. However, in our CI runners,
those stages would visually appear as single "stage."
To allow for multiple Gangplanks to run:
- A new CLI target of `minio` launches minio and writes its
configuration to disk
- Other Gangplank instances can `-m <cfg file>` to access tthe
standalone Minio.
- Gangplank no longer requires port 9000. Instead, the first port at or
above 9000 is used.
- Relavant tests have been introduced.
For the Jenkins pipelines, I envision having Minio running in its own pod.  For Prow, multiarch and ART builds, I envision Gangplank running as it does today and using a bespoke Jobspec. 
Signed-off-by: Ben …
=> Gangplank: shareable minio via minio only mode

docs/working.md, src/cmd-build, src/cmd-buildextend-live, src/cmd-buildextend-metal, src/cmdlib.sh, src/cosalib/cmdlib.py, tests/test_cosalib_cmdlib.py
This will be needed in FCOS to make it easier to have kernel arguments
that are specific to some streams, while still sharing the bulk of
`image.yaml`:
https://github.com/coreos/fedora-coreos-tracker/issues/292#issuecomment-806099932
=> Add support for `include: <path>` key in image.yaml

gangplank/cmd/minio.go, gangplank/ocp/bc.go, gangplank/ocp/const.go, gangplank/ocp/filer.go, gangplank/ocp/filer_test.go, gangplank/ocp/remotes.go, gangplank/ocp/remotes_test.go, gangplank/ocp/return.go, gangplank/ocp/return_test.go, gangplank/ocp/worker.go, gangplank/spec/stages.go
In order to have Gangplank handle building metal and oscontainer builds,
its needs to have more nuanced dependencies.
This change introduces two concepts:
- {Returns,Requires,Requests}{Cache,CacheRepo} to the stage definition. When
defined, {Returns,Requires,Requests}Cache will return/request a tarball of
/srv/repo, while {Return,Requires}CacheRepo will handle /srv/tmp/repo
- RequestArtifacts are optional dependencies are artifacts can be requested,\
but are required.
The cache and repo tarballs can be saved between builds and serves the
same functional goal of the cache qemu disk. This should help with RHCOS
build pipeline which is does not persist a cache.
=> Gangplank: improved dependencies for base builds 

mantle/cmd/plume/cosa2stream.go, src/cmd-generate-release-meta
For RHCOS We don't yet have this in place by the time we go to pin in
the installer; we may end up relying on the installer's GPG
signature covering the stream metadata.
=> plume/cosa2stream: Add --nosignatures

src/cmd-build
So we don't forget.
(There's a right fix here but hacking on the pipeline and reproducing
the error is painful)
=> build: Link to issue if we fail to import

mantle/cmd/plume/stream_mirror.go, mantle/go.mod, mantle/go.sum, mantle/vendor/github.com/coreos/stream-metadata-go/stream/artifact_utils.go, mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream_utils.go, mantle/vendor/github.com/google/renameio/.golangci.yml, mantle/vendor/github.com/google/renameio/CONTRIBUTING.md, mantle/vendor/github.com/google/renameio/LICENSE, mantle/vendor/github.com/google/renameio/README.md, mantle/vendor/github.com/google/renameio/doc.go, mantle/vendor/github.com/google/renameio/go.mod, mantle/vendor/github.com/google/renameio/tempfile.go, mantle/vendor/github.com/google/renameio/writefile.go, mantle/vendor/modules.txt
For RHCOS we will have a multi phase process where:
1. Build is produced
2. PR to openshift/installer is created proposed new pinned stream metadata that
refers to artifacts stored in "maybe production" staging location
3. PR lands after main OpenShift CI passes
4. Content is synced from openshift-installer pinned data to mirror.openshift.com
To implement phase 4, we need to rewrite the stream metadata
after it's been officially mirrored so the URLs aren't referring to the staged
location.
(Actually ideally, we get the stream content mirrored into the official
mirror.openshift.com *before* bumping the pinned installer, but that's
more complicated right now)
=> Add `plume stream-mirror`

gangplank/ocp/filer.go, gangplank/ocp/remotes_test.go
The elder Arches (s390x and ppc64, although technically ppc64el is a newer variant) have hit a few snags with Minio. 
These commits are aimed at making the startup of minio more robust by checking that minio is ready before returning from `start()` as well as adding extra checks on the newness logic for remote files.
=> Gangplank: minio tweaks for the Elder Arches

ocp/cosa-bc.yaml
Rather than using a buggy-custom role, we should use a standard cluster
role for the Gangplank processes.
This is the same role used for Prow permissions via https://github.com/openshift/release/pull/17257/commits/5d284363583f7cae00143129bbd181c64d7e13fd
=> ocp: use a cluster role for Gangplank

gangplank/cmd/build.go, gangplank/cmd/main.go, gangplank/ocp/bc.go, gangplank/ocp/cosa-pod.go, gangplank/ocp/k8s.go
This fixes two big problems encountered while putting Gangplank into
production:
- hangs caused by orphaned go-routines after an os interrupt (ctrl-c)
- when running in-cluster, errors would not break execution
The job control code was refactored to ensure only one part of the code
handled the issuance of termination from all termination signals (context,
os interrupt or error handling). Instead, a termination channel signals
worker go-routines that they should terminate and individual go-routines
no longer care about context or os signals. Further, the
workerFunction() was simplified and now only takes a termination channel
as the argument.
The in-cluster pod watch function was simplified and cleaned up as well.
If a pod failed early or was unschedudable, then Gangplank would hang. To …
=> Gangplank: refactor job control and logging to fix hangs

gangplank/cmd/pod.go, gangplank/ocp/cosa-pod.go, gangplank/ocp/k8s.go, gangplank/ocp/sa_secrets.go
This allows Gangplank to be executed is another namespace, which is needed for Prow execution.
=> Gangplank: allow for cross-namespace execution

mantle/kola/tests/podman/podman.go
Those aren't supported in cgroups v2. Rather than make them conditional,
let's just drop them since we'll move over everything to cgroups v2
soon-ish anyway.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/791
=> kola/podman.base: drop cgroupsv2-unsupported `podman run` resource switches

mantle/cmd/kola/qemuexec.go, mantle/platform/qemu.go
Add a new `--butane` option analogous to `--ignition` which
automatically converts the Butane config to an Ignition config.
=> kola/qemuexec: add support for directly passing Butane configs

Dockerfile
I'd like to get rpm-ostree v2021.4 into cosa for the advisory bits:
https://github.com/coreos/rpm-ostree/pull/2695
And the SRPM locking:
https://github.com/coreos/rpm-ostree/pull/2680
=> You won't believe this one simple trick to clear out the Quay.io cache

gangplank/spec/clouds.go
This address problems via `make staticanalysis`
spec/clouds.go:131:3: S1039: unnecessary use of fmt.Sprintf (gosimple)
fmt.Sprintf("--auth $AZURE_CONFIG"),
^
spec/clouds.go:133:3: S1039: unnecessary use of fmt.Sprintf (gosimple)
fmt.Sprintf("--profile $AZURE_PROFILE"),
^
spec/clouds.go:186:3: S1039: unnecessary use of fmt.Sprintf (gosimple)
fmt.Sprintf("--json $GCP_IMAGE_UPLOAD_CONFIG")}
^
spec/clouds.go:61:2: structtag: struct field tag `yaml:"grant_user_snapshot,omitempty" json:grant_user_snapshot,omitempty"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value (govet)
GrantUserSnapshot []string `yaml:"grant_user_snapshot,omitempty" json:grant_user_snapshot,omitempty"`
^
(cherry picked from commit 551ac2923d6762bb3f0f08e5a913b910bf0c4d84)
=> Gangplank: update spec/clouds.go for static analysis checks

mantle/cmd/kola/options.go, mantle/rhcos/metadata.go
Now that we have stream metadata for RHCOS, this closes a huge
gap in that we now have a convenient command to spawn an RHCOS
instance shell in AWS:
```
$ kola spawn -b rhcos --stream master -p aws
Resolved distro=rhcos stream=master platform=aws to release=48.83.202103221318-0 (region us-east-1, ami ami-0146091f9e1b5ec3f)
...
[bound] -bash-4.4$ rpm-ostree status
State: idle
Deployments:
* ostree://328a44d7c259ca1e3ed31ae020f09d922f460be998657a92f684f6760443077b
Version: 48.83.202103221318-0 (2021-03-22T13:22:02Z)
[bound] -bash-4.4$
```
=> kola/spawn: Add support for stream metadata for rhcos

gangplank/cmd/build.go
The buildconfig log was broken with the cluster context work.
=> Gangplank: fix broken cluster object

gangplank/cmd/commonflags.go, gangplank/cmd/generate.go, gangplank/cmd/main.go, gangplank/cmd/pod.go
Instead of having a useless "runCmd" target, this change enables
"podless" more for executing Gangplank directly. The use cases are:
- developers testing inside a pet-container for JobSpec testing
- Prow (while we tease out permissions)
Example invocation:
gangplank podless --init -A base -A metal4k
When running in podless mode Gangplank only parse the jobspec and
executes the task.
=> Gangplank: add podless mode

ocp/Dockerfile.buildconfig, ocp/Makefile
Plan E for Prow via Gangplank is to use a custom build strategy via `oc
start-build` due to permission issues. This change ensures that OCP
build images has the OC binary.
=> ocp: add 'oc' bin to OCP Dockerfile and fix Makefile

gangplank/cosa/cosa_v1.go, mantle/cosa/cosa_v1.go, mantle/cosa/schema_doc.go, src/cmd-koji-upload, src/schema/v1.json
- Allow Koji to create a build reservation and use it after.
- Add the build_id into the build metadata.
- The reason behind it: We need to add the build_id
in the metadata in order to allow CVE automation for RHCOS.
Co-authored-by: Stephen Milner <smilner@redhat.com>
=> cmd-koji-upload: Refactor it to allow Koji build reservation

gangplank/cmd/generate.go
Fix regression introduced in #2133 where the spec file passed in from
the command line was not being used.
=> gangplank: allow specs passed in from cli

src/cosalib/digitalocean.py, src/cosalib/qemuvariants.py
cmd-compress doesn't process the DO artifact because we special-case gzip compression in the mutate callback.  But the artifact is still a regular compressed disk image, so we should still set the uncompressed size/sha256.  Have the mutate callback do that as well.
Do not apply a similar change to the GCP `tar.gz` artifact, since the uncompressed tarball isn't useful on its own.
=> digitalocean: set uncompressed-{size,sha256}

src/cmd-buildextend-live, src/cmd-kola
Fix cmd-buildextend-live for s390x to use mk-s390image instead of mk-s390-cdboot. Apparently there was a bug in cdboot where it would overwrite the kernel with the initrd if the intrd was too large.
Fix cmd-kola to use qemu-system-{arch} instead of qemu-kvm to check for nvme bootindex as qemu-kvm is not present on non x86 arches
=> cmd-* : multi-arch fixes after f34 move.

docs/gangplank/usage.md, gangplank/ocp/k8s.go, gangplank/ocp/ocp.go, gangplank/ocp/worker.go, gangplank/spec/cli.go, gangplank/spec/jobspec.go
This adds the ability to push to arbitrary registries to support the
production builds for ART and ProdSec use cases.
Changes:
- Added 'publish_oscontainer' as a jobspec field
- Added 'registry' struct to describe registry publication. Each
registry can have its own secret and TLS verification policy.
Example:
```
publish_oscontainer:
buildstrategy_tls_verify: true
registries:
- url: "first.registry.example.com/stream/name:tag"
secret_type: token
tls_verify: false
- url: "second.registry.example.com/stream/name:tag",
secret_type: inline
secret: "<STRING>"
- url: "third.registry.exmaple.com/stream/name:tag",
secret_type: cluster
secret: builder-secret
```
=> Gangplank: support pushing ostree to registries

gangplank/spec/stage_test.go, gangplank/spec/stages.go
Prior commit broke the shorthands for "base" and "finalize"
=> Gangplank: fix shorthands for pseudo artifacts

gangplank/go.mod, gangplank/ocp/pod.go
This fixes a problem where two instances of Gangplank running in Minio
mode can start with the same pseudo build number.
=> Gangplank: use UUID in pod mode

gangplank/ocp/bc.go, gangplank/ocp/remotes.go, gangplank/ocp/return.go, gangplank/ocp/return_test.go, gangplank/ocp/worker.go, gangplank/spec/cli.go, gangplank/spec/jobspec.go, gangplank/spec/jobspec_test.go, gangplank/spec/override.go, gangplank/spec/override_test.go, gangplank/spec/stages.go
These changes make using Gangplank easier to use by third parties (such as ART and the Node team) by:
- providing for inline definitions of repositories in the jobspec
- providing a method of pushing overrides rootfs and rpm overrides
The goal is to help ART produce embargoed/clandestine builds and the Node/Runtime teams be able to produce custom machine-os-content with overrides or phashet builds that can be used in E2E tests.
=> Gangplank: support for overrides and inline repository definitions

src/cmd-build
We might want to add a specific option to directly set `RPMOSTREE_PRESERVE_TMPDIR` for debugging but that can come later (and should be much easier to discover with this updated help text).
=> cmd-build: Update help text and mention rpm-ostree debug env options

mantle/kola/tests/upgrade/basic.go
This lowers Zincati steady refresh interval to 20s, possibly
making the agent more reactive and test runs shorter.
---
I did not test this, but it could possibly help with timeout issues in https://github.com/coreos/fedora-coreos-tracker/issues/756 (if that is the case).
=> tests/upgrade-basic: speed up Zincati ticks

src/cmd-koji-upload
- It allows brew to use package name as packagename-arch,
- This change is necessary to create one package for each arch in brew tree.
=> Attach architecture with name in the meta.json

src/cmd-build
s/Additionnal/Additional
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>
=> cmd-build: fix a typo in the help text

src/cosalib/digitalocean.py, src/cosalib/qemuvariants.py
build/gcp: Add uncompressed-checksum
I'm working on https://github.com/cgwalters/coreos-diskimage-rehydrator/
and a goal is to regenerate *exactly* the artifacts.  But right
now because we gzip the GCP tarball at build time, we don't
have `uncompressed-sha256` in the metadata.  Which means the
rehydrator can't verify it.
Add a declarative way to express that an artifact needs to be gzipped.
---
digitalocean: Use new `gzip: True` field
Now there's no need for custom code, which means we can drop
the OO-inversion of having generic code import "subclass" code
too.
---
build: Remove mutate-callback
No need for this anymore, and it was mixing declarative with
a generic imperative escape hatch.  Since this code is trying
to be declarative let's do that.
---
=> build/gcp: Add uncompressed-checksum

gangplank/Makefile, gangplank/spec/stages.go
Since the gangway binary executes commands, disabling CGO is breaking
all sorts of commands like tar. In a deep dive, I suspect that this is a
problem with the syscall for ForkExec, although I can't pinpoint it.
Regardless, switching from static for Gangway fixes shell-out commands
while preserving the reason for the switch in the first place.
The tl;dr is that we're in for some fun with the recent changes to
container runtimes with permissions.
=> Gangplank needs CGO for Gangway

mantle/cmd/kola/devshell.go
I had this in a local change but missed committing it.  And nothing
in CI covers `cosa run` because it requires a tty/interactivity
right now.
Without this `cosa run` just exits because it invokes `true`
instead of waiting in a shell.
=> devshell: Fix previous commit

mantle/cmd/kola/devshell.go
Bug in previous commit, we need to stop reading when we
hit an error, and also don't fall through.
=> devshell: Break out of pipe loop on error

src/cmd-koji-upload
Reservation data name must match with build name, otherwise
the name reservation will be used as package name.
=> Fix reservation name

mantle/cmd/kola/qemuexec.go, mantle/cmd/kola/testiso.go, mantle/platform/metal.go
Now when using `--qemu-multipath`, the ISO-based install scenarios will
test installing on top of a multipathed device.
This will exercise the OS side of first boot support for multipath:
coreos/fedora-coreos-config#1011
Note here we don't use `coreos-installer iso kargs` to add the
`rd.multipath` karg. First, we don't strictly need multipathing enabled
from the initrd of the live environment, so we instead test manually
enabling it in the real root (which is in fact a precursor for
eventually supporting custom configs). Second, the ISO tests right now
don't leverage embedded kargs at all (apart from the harness itself
adding `console=ttyS0`), so it seems unrealistic to mix and match.
I think we should though have a new `iso-kargs-install` scenario now
which uses ISO kargs to inject …
=> testiso: handle --qemu-multipath for ISO tests

gangplank/ocp/return.go
```
commit 217c582655058e82b66278cb292e486a0229be6f
Date:   Thu May 20 16:59:40 2021 -0400
gangplank: let tar create the file
I was getting a permission denied when the file already existed.
Let's delete the temporary file and let tar create it instead.
commit 3fbbb145933a5363ae3917786ea495a4b4e687d4
Date:   Thu May 20 16:03:45 2021 -0400
gangplank: fix arguments to tar for tarball creation
Was passing in the directory and not the target file name
to `-f`.
```
=> gangplank: fix a few issues with tar invocation

Dockerfile, src/cmd-kola
This reverts commit ade62766e487db586d2f4c893fb4553b2c7abf07.
The NVMe fix was backported:
https://bugzilla.redhat.com/show_bug.cgi?id=1956429
https://bodhi.fedoraproject.org/updates/FEDORA-2021-303ad002d2
Rather than wait until the bomb goes off, I tagged the qemu build into
f34-coreos-continuous so we can defuse it now.
=> Revert "cmd-kola: temporarily stop testing on NVMe"

src/cmd-buildextend-metal, src/cmdlib.sh
Conceptually `image.yaml` is the configuration for coreos-assembler
specifically, distinct from `manifest` and `overlay` etc. which
end up being fed into rpm-ostree.
First, this is part of addressing
https://github.com/coreos/rpm-ostree/pull/2842#discussion_r635542478
so that e.g. we can migrate the `name:` into this file instead
of the rpm-ostree manifest.
But I also want to hook other things off here, such as whether
to use the new ostree-container format instead of our tar-of-archive-repo.
=> build: Parse image.yaml early on and convert to JSON

gangplank/ocp/bc.go
The find command was useful for debugging, but now its cruft.
=> Gangplank: remove unneeded find shell command

mantle/kola/tests/misc/raid.go
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/838
On `Fedora-34` and previous releases, `lsblk` displays only one mount point, however, there's a change in the way `Mountpoints` being displayed on `Fedora-35`, which breaks backward compatibility. 
For example:
```
[core@cosa-devsh ~]$ cat /etc/os-release | grep "VERSION="
VERSION="34.20210524.dev.0 (CoreOS Prerelease)"
[core@cosa-devsh ~]$ lsblk --json
{
"blockdevices": [
{"name":"sr0", "maj:min":"11:0", "rm":true, "size":"1024M", "ro":false, "type":"rom", "mountpoint":null},
{"name":"vda", "maj:min":"252:0", "rm":false, "size":"10G", "ro":false, "type":"disk", "mountpoint":null,
"children": [
{"name":"vda1", "maj:min":"252:1", "rm":false, "size":"1M", "ro":false, "type":"part", "mountpoint":null},
{"name":"vda2", …
```
=> mantle: fix mountpoint details to address `boot-mirror` tests failure

src/osmet-pack
Shellcheck fails with SC1091 when executing make check.
=> Disable shellcheck SC1091 in src/osmet-pack

src/osmet-pack
Shellcheck fails with SC1091 when executing make check.
(cherry picked from commit bde4b69297073d78f02bc9ec2a20148d590ce7a1)
=> [rhcos-4.8] Disable shellcheck SC1091 in src/osmet-pack

src/osmet-pack
Shellcheck fails with SC1091 when executing make check.
(cherry picked from commit bde4b69297073d78f02bc9ec2a20148d590ce7a1)
=> [rhcos-4.7] Disable shellcheck SC1091 in src/osmet-pack

mantle/cmd/kola/qemuexec.go, mantle/cmd/kola/testiso.go, mantle/platform/metal.go
Backport of https://github.com/coreos/coreos-assembler/pull/2172 because we'll need coverage for https://github.com/coreos/fedora-coreos-config/pull/1011 when we backport that to 4.8.
=> [rhcos-4.8] testiso: handle --qemu-multipath for ISO tests

src/supermin-init-prelude.sh
Should make the warning about degraded performing go away and possibly
even give us better performance!
```
qemu-system-x86_64: warning: 9p: degraded performance: a reasonable high
msize should be chosen on client/guest side (chosen msize is <= 8192).
See https://wiki.qemu.org/Documentation/9psetup#msize for details.
```
Fixes: https://github.com/coreos/coreos-assembler/issues/2171
=> supermin: bump msize for 9p mounts

src/cmd-init
I feel like workers(bots) who are running builds for FCOS/RHCOS don't
need the full git commit history. Let's save energy and not waste the
bandwidth.
=> init: do a shallow clone of git repo

gangplank/.gitignore, gangplank/.vscode/settings.json, gangplank/Makefile, src/build-deps.txt
When Gangplank gain awareness of how to run local podman, a bunch of
devel libraries came along for the ride (gpgme, btrfs-progrs,
device-mapper and libblock) all of which are not used by Gangplank. This
commit corrects the unfortante side effect.
=> Gangplank: drop need for CGO devel libraries

gangplank/cmd/gangplank/commonflags.go, gangplank/cmd/gangplank/generate.go, gangplank/cmd/gangplank/pod.go, gangplank/ocp/ssh.go, gangplank/spec/jobspec.go
```
commit 430e2c0d686a18cc2a2c947d1c8d64ef64ca95e0
Date:   Tue Jun 1 15:16:32 2021 -0400
gangplank: pod --podman --remote: fully support SSH key path
This adds in the plumbing to support using an SSH key to authenticate
with a remote podman instance. Using an SSH Agent worked before but pure
keyfile based auth needed a few fixups.
commit fc5bbd73ace0f91ee999c6a714f73d6e1cfa0604
Date:   Tue Jun 1 14:26:03 2021 -0400
gangplank: ssh: set StrictHostKeyChecking=no on port forward
In fresh container environments no user would have had the chance
to interactively respond "yes". Let's just set StrictHostKeyChecking=no
unless there is a better alternative.
commit 52f8c8fd3ce0da2735e00717ab0ea4e9ce49cc07
Author: …
```
=> gangplank: followups to podman remote support

src/cmdlib.sh
Let's settle on 0022 as the umask we use to run rpm-ostree composes.
That way, we get consistent results regardless of our setup in the
build/dev environment and other parts of cosa.
This fixes liberal umasks like 0002 leaking into the bwrap environment
of scriptlets rpm-ostree runs and affecting the mode of files these
scriptlets create.
See: https://github.com/coreos/fedora-coreos-tracker/issues/829
=> cmdlib: always run rpm-ostree composes with umask 0022

src/cmdlib.sh
We should match the rest of the OS, even for /usr content which is ro
anyway. Doing it in cosa means we get consistent modes regardless of
what the umask was in the build/dev environment when the repo was
cloned.
See: https://github.com/coreos/fedora-coreos-tracker/issues/829
=> cmdlib: strip write bit for group+other on all overlay files

gangplank/cmd/gangplank/generate.go, gangplank/cmd/gangplank/pod.go, gangplank/cosa/build.go, gangplank/cosa/builds.go, gangplank/cosa/cosa_reader.go, gangplank/ocp/bc.go, gangplank/ocp/filer.go
This change enables the use of a remote Minio or S3 object store and breaks the need for running Gangplank where the files are returned. For example, if running Gangplank over SSH it may be more desirable to have the workers return the results to a remote location.
The idea came from @dustymabe using Gangplank over low-bandwidth SSH connections (e.g. the 'hood coffee shop). 
Example:
```
$ cat minio.cfg
{
"accesskey": "F0rTh3Luv0fLoki",
"secretkey": "SrlyLikeWhy?",
"host": "horcrux.dev",
"port": 9000,
"external_server": true,
"region": ""
}
$ gangplank pod --podman -m minio.cfg -A base
```
=> Gangplank: use minio for origin gangplank file io

src/cmd-build, src/cmd-buildextend-live, src/cmd-buildextend-metal, src/cmd-buildprep, src/cmd-upload-oscontainer
This has been reshuffled a few times, and I plan to do so again
using the new `rpm-ostree ex-container export` bits.  Remove
the now long dead `ostree-commit.tar` bits; the schema has required
the `ostree` entry in `meta.json` for a long time now (since FCOS
from the start, and as of OpenShift 4.3+).
=> Drop support for no longer used `ostree-commit.tar`

docs/kola/external-tests.md, mantle/kola/harness.go
I'm trying to write a test for kdump which intentionally causes
a kernel panic and hence warning on the console.  Without this
the harness errors out.
=> tests: Add skip-base-checks tag

src/cmd-kola
This reverts commit d64c16fae0250140e8dddab8b85ba3f562a63391.
This is fixed now in the latest seabios build:
https://bodhi.fedoraproject.org/updates/FEDORA-2021-2904475482
Closes: #2184
=> Revert "cmd-kola: temporarily skip NVMe testing in basic scenarios"

Dockerfile
Follow-up to https://github.com/coreos/coreos-assembler/pull/2208.
Otherwise Quay.io probably won't pick up the new seabios package with
the fix.
=> Dockerfile: tickle Quay.io's cache for new seabios package

mantle/platform/qemu.go
switch boot order for multipath disks when running testiso with `qemu-multipath`. there was a regression in the arm64 rhcos pipeline with testiso failing with:
```
+ kola testiso -S --qemu-native-4k --qemu-multipath --scenarios iso-install --output-dir tmp/kola-metal4k
Testing scenarios: [iso-install]
Error: scenario iso-install: switching boot order failed: Could not set bootindex for blkdev: Running QMP command: Device '' not found; <nil>
2021-06-03T08:32:21Z cli: scenario iso-install: switching boot order failed: Could not set bootindex for blkdev: Running QMP command: Device '' not found; <nil>
```
the disk device for multipath was not recognized when switching bootorder causing this to fail.
=> platform/qemu: switch boot order for multipath disks

src/cmd-buildextend-extensions, src/cmd-buildextend-live, src/cmd-generate-hashlist, src/cmd-sign, src/cosalib/cmdlib.py, tests/test_cosalib_cmdlib.py
I'm going to be reworking this to use `rpm-ostree ex-container`
and it's easier if the callers pass the build metadata directly,
rather than each one parsing it separately.
=> build: Clean up internal import_ostree_commit helper function

gangplank/cmd/gangplank/generate.go, gangplank/cmd/gangplank/pod.go, gangplank/cosa/build.go, gangplank/cosa/builds.go, gangplank/cosa/builds_test.go, gangplank/cosa/cosa_reader.go, gangplank/cosa/schema_test.go, gangplank/go.mod, gangplank/ocp/bc.go, gangplank/ocp/filer.go, gangplank/ocp/return.go, gangplank/ocp/ssh.go, gangplank/ocp/worker.go, gangplank/spec/jobspec.go
Prior to this Gangplank supports S3 in theory -- that is if S3 region
was empty, or in the extremely unlikely event that the caller has the
buckets 'builds' and 'cache.' The reason it worked with Minio is that
the Minio instance was neither shared nor did it remain after the build.
This change allows for Ganplank to use S3 or shared Minio backends by:
- Moving all minio specific information into its own struct
- Requires a bucket, and supports a path prefix for using sub-paths
inside a bucket.
- Supports S3 secure connections.
=> Gangplank: use bucket and path prefix for remote objects

gangplank/cosa/build.go, gangplank/spec/stages.go
This was previously not working because `cosa buildextend-live-iso`
isn't a valid command. `cosa buildextend-live` is and produces multiple
artifacts (kernel, initramfs, rootfs, iso).
The error I was seeing was:
```
INFO[0219] Executing rendered script  cmd=/bin/bashrendered=/tmp/rendered030160414
+ cosa buildextend-live-iso
Unknown command: buildextend-live-iso
```
=> gangplank: fixup building of live artifacts

gangplank/go.mod, gangplank/ocp/bc.go, gangplank/ocp/filer.go, gangplank/ocp/ssh.go
Hack-day project: the use of shell-SSH has bothered me -- it was a hack.
For hack-day, I figured de-hacking the SSH to use pure-Go SSH would be a
fitting project.
This borrows from the libpod GoLang implement of SSH code. Since our
needs a different (they use an http client over ssh to a socket) and we
need to proxy, the sshClient function was modified to return an
ssh.Client.
This ensures that similar code paths are used between remote podman _and_ the minio forwarding.
Oh, this also makes Minio faster by enabling compression.
=> Gangplank: use pure-Go SSH forwarding

src/cmd-build, src/cmdlib.sh, src/cosalib/cmdlib.py, tests/test_cosalib_cmdlib.py
Part of implementing https://github.com/coreos/fedora-coreos-tracker/issues/812
A whole lot of the story of coreos-assembler is threaded
with the tension between ostree and disk images.  They
have fundamentally different tradeoffs.  And now I'm trying
to add container images to the mix.
The idea of capturing an ostree repo in archive mode as a tarball
is a cosa invention.  We don't actually ship anything that way.
The proposal in the above linked issue is to "productize" support
for shipping ostree-in-container, because containers are just
slightly fancy tarballs.
This patch adds support for:
`echo 'ostree-format: oci' >> image.yaml`
in the config git.
When enabled, the `images/ostree` is replaced with an `oci-archive`
format of an "ostree-in-container", which we might shorten to …
=> Support `ostree-format: oci` in `image.yaml`

.cci.jenkinsfile, mantle/build
This code is new and we're still squashing races. Let's gate it behind
an env var so it's not enabled in production builds since this can cause
failures (see: https://github.com/coreos/coreos-assembler/pull/2219).
This way it's still easy for local devs to enable it and we can still
opt into it for our upstream CI.
=> Don't enable `go build -race` by default

mantle/build
Missed this in #2224. And now actually tested locally.
=> mantle/build: really don't enable `-race` by default

.cci.jenkinsfile
This way we validate that it's just a cache.  Prep
for using ostree-containers.
=> ci: Clear out tmp/repo to test ostree repo re-import

src/create_disk.sh
Add support for a bootfs_metadata_csum_seed image.yaml knob that tells
us to enable the metadata_csum_seed ext4 filesystem feature.
This is gated behind an image.yaml knob because support for this feature
flag was only recently added to grub.
https://lists.gnu.org/archive/html/grub-devel/2021-06/msg00031.html
This helps us not have to run a filesystem check before running tune2fs
to randomize the filesystem UUID on first boot. See
https://github.com/coreos/fedora-coreos-tracker/issues/735 for more
context.
The knob in image.yaml will look like:
```
bootfs_metadata_csum_seed: true
```
=> create_disk: add support for bootfs_metadata_csum_seed image.yaml knob

src/create_disk.sh
This is a follow up to dd3225f. The addition of a non empty string
value for bootargs before this point means we need to add to the
existing value.
=> create_disk: add spacing in bootargs

src/cmd-build-fast
In a git worktree, `.git` is a file, not a directory. Loosen up that
check.
=> cmd-build-fast: support project git worktrees

src/cmd-upload-oscontainer
Add the architecture to the default push tag for two reasons:
- The release team for RHCOS has requested that the image tag include
the architecture.
- `aarch64` builds are planned to share the build id. Unless the images
are pushed to separate tags, one build could step on another.
The better solution would be to use "fat manifests", however, they
are not universally supported yet. Quay plans on providing this in the
4.8 time-frame. Until such time, this is the cleanest path.
=> src/cmd-upload-oscontainer: use arch in the push tag

mantle/cmd/kola/qemuexec.go, mantle/kola/tests/ignition/qemufailure.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/metal.go, mantle/platform/qemu.go
The name 'NewBuilder' in the context of platform is vague.
=> Mantle: rename platform.NewBuilder to NewQemuBuilder

mantle/cmd/kola/kola.go
This is needed for the rhcos-4.8 branch as RHEL COSA is currently stuck on F33 based COSA.
Cherry-picked from: 1d01a752fa2468ccaf5f1a882f522cad6926ac85
=> mantle/kola: Update upgrade test to use an Ignition spec 3 image

src/create_disk.sh
We should pass a file containing the kargs here, but not the `options`
key we grepped out of the BLS. Otherwise, I think we'll literally end up
with an `options` karg (which thankfully should have been harmless).
Filter through `cut` to remove that.
We regressed on this at some point. The original commit which added
s390x support didn't do this:
https://github.com/coreos/coreos-assembler/commit/100c2e512ecb89786a53bfb1c81abc003776090d
=> create_disk.sh: remove `options` from s390x parmfile

mantle/kola/tests/ignition/empty.go, mantle/kola/tests/ignition/ssh.go
`coreos.ignition.ssh.key` uses the same test function as the tests in `empty.go` but wants the opposite result: verifying that Afterburn did not inject keys.  Give it its own test function.
Fixes #2238.
=> kola/tests: fix `coreos.ignition.ssh.key`

mantle/kola/tests/misc/network.go
This PR is adding a test that will check DHCP propagation over a bond of two veth pairs.
test network chart attached
=> kola/tests/misc/network: Add dhcp test with veth

mantle/cmd/kola/devshell.go, mantle/platform/qemu.go
Instead of using timers to decided when to connect over SSH, this uses
console events to determine when to connect to SSH. Rather than parsing
the virtio-console for ready-status, this uses the console for
determining state.
=> Mantle: refactor devshell to be event based

mantle/platform/platform.go, mantle/platform/platform_test.go
mantle/platform: Ignore some non-fatal unit failures in RHCOS
Special case to ignore some non-fatal unit failures frequently seen in
flakes. This is for RHEL 8 only as this has been fixed upstream in
systemd but not fixed in RHEL 8.
Tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1914362
=> mantle/platform: Ignore some non-fatal unit failures in RHCOS

mantle/platform/conf/conf.go, mantle/platform/conf/conf_test.go
When stabilizing an Ignition spec in the presence of external kola tests using the experimental spec, three things must be stabilized in lockstep for CI to stay green: Ignition, mantle, and the external tests.  CI can add workarounds for the external tests (by running `sed` over the configs) but stabilizing mantle is harder, especially since vendoring the new Ignition into mantle also requires stabilizing the Ignition spec inside the vendored Butane.
Teach `platform/conf` to handle the next stable spec via a trick: create an empty config using the current stable spec and add the provided config to it as a merged child via a `data:` URL.  That way we can still add our config fragments without understanding the provided config.
This allows stabilization to proceed without immediately …
=> mantle/platform/conf: support wrapping the next stable spec

src/cmd-artifact-disk, src/cmd-ore-wrapper, src/cosalib/qemuvariants.py
The RHCOS pipeline is trying to add an `azurestack` artifact and
that's blowing transient disk usage past the the 50Gi PVC.
There's no real reason not to compress right after building
artifacts that we're not going to immediately test locally (e.g.
like we do with `qemu`) so add an option to compress directly.
=> buildextend-*: Add `--compress`

mantle/platform/platform.go, mantle/platform/platform_test.go
Special case to ignore some non-fatal unit failures frequently seen in
flakes. This is for RHEL 8 only as this has been fixed upstream in
systemd but not fixed in RHEL 8.
Tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1914362
Cherry-picked from: a542f266 mantle/platform: Ignore some non-fatal unit failures in RHCOS
=> [4.8] mantle/platform: Ignore some non-fatal unit failures in RHCOS

Makefile
Since Gangplank is breaking CI, let's disable it for now.
=> Gangplank: disable tests pending Minio fix

mantle/cmd/ore/aws/upload.go, mantle/cmd/plume/prerelease.go, mantle/platform/api/aws/images.go, src/cmd-ore-wrapper, src/cosalib/aws.py, src/cosalib/build.py, src/cosalib/meta.py, src/cosalib/qemuvariants.py
This adds the ability to specify an architecture to buildextend-aws
so that we can upload an aarch64 AMI even if we're on x86_64.
=> cosalib, ore: add ability to cross upload aarch64 AMIs

src/cmd-meta
Useful for meta merging when you don't want to spin up gangplank
to talk to another machine just to merge some json together. Ex:
```
cosa meta --finalize --arch aarch64
```
=> cmd-meta: add support for specifying a different architecture

Dockerfile
Now that https://github.com/coreos/fedora-coreos-config/pull/1063
has landed we need the new grub2 so that our image builds don't fail.
=> Dockerfile: tickle Quay.io's cache for new grub2 package

Dockerfile
And here we are, again.  Changing a comment string as
an important part of our release pipeline.
This is to pick up https://bodhi.fedoraproject.org/updates/FEDORA-2021-c761456766
=> Dockerfile: Invalidate quay.io cache for new rpm-ostree

src/cmdlib.sh
Around start of the June, builds of FCOS on Power 8 host started to fail due to the kernel page allocation failures. I haven't noticed any obvious issues so I assume that some combination of overhead of radix mode, 64k pages and possibly in connection to some changes in Fedora, rpm-ostree causing this. Power 9 is unaffected.  Bumping the memory resolves this issue.
CC'ing @Prashanth684
=> cmdlib: Bump ppc64le memory to 4G, due to page faults on Power 8

gangplank/internal/ocp/filer.go, gangplank/internal/ocp/filer_test.go
This includes two fixes for addressing the CI failures with Minio:
- A new check function has been brought back by looking for a response between 200 and 500. This check is not perfect due to supporting AWS and Minio. 
- Retry up to three times for fetching and putting files
/cc @jlebon
=> Gangplank: fixes for Minio timeouts seen in CI

src/cmd-koji-upload
Backport from main #2159
- It allows brew to use package name as packagename-arch,
- This change is necessary to create one package for each arch in brew tree.
=> koji: Backport - Attach architecture with name in the meta.json

src/cosalib/aws.py
Also populate `--arch` value from build.basearch.
=> cosalib/aws: include architecture in AMI name/description

src/cmd-build, src/cmd-buildextend-metal, src/cosalib/meta.py
This change uses the meta locking to prevent a RW operation from
happening at exactly the same time. In CI, was observed that another
process could be emitting a new meta.json at the same time a seperate
bash script could be reading from meta.json.
Fixes #2277.
=> metal: fix read-race condition when updating metadata

gangplank/spec/jobspec.go, gangplank/spec/jobspec_test.go
Correctly interpret HTTP-Error Codes as errors.
Use mirrors.kernel.org as domain as fedora.com is currently on sale.
=> [rhcos-4.8] Gangplank: Fix jobspec bad repo test for rhcos-4.8

src/cmd-build-fast
In the case we're running this in the cosa dir and not a project dir, we
want to output to `$workdir/tmp`. If we just use `tmp`, it'll output to
the temporary build dir, which is nuked on exit.
=> cmd-build-fast: fix output to $workdir/tmp

Makefile, gangplank/internal/cosa/schema_test.go, gangplank/internal/ocp/filer.go, gangplank/internal/spec/jobspec.go, gangplank/internal/spec/jobspec_test.go, tools/generate-schema.sh
Three fixes to Gangplank failing in CI:
```
commit d346a21b7f1088698bd0f37854edf1e159c858e9 (HEAD -> pr/minio-ci-fix, me/pr/minio-ci-fix)
Author: Ben Howard <ben.howard@redhat.com>
Date:   Thu Jul 8 16:41:30 2021 -0600
Gangplank: fix broken URL tests
The prior URL testing relied on actual HTTP servers which is flawed. In
some CI cases, this test fails. This makes Gangplank a much better
netizen by mocking the response instead.
commit aa5e17f086cdf2a13f9666e0f11d88254ce217be
Author: Ben Howard <ben.howard@redhat.com>
Date:   Thu Jul 8 14:49:04 2021 -0600
Gangplank: fix schema location
commit 58af0be4409f8cf247dc2755bbd5973103c5c16c
Author: Ben Howard <ben.howard@redhat.com>
Date:   Thu Jul 8 13:44:30 2021 -0600
Gangplank: fix minio startup …
```
=> Gangplank CI fixes

src/cmdlib.sh
If an `overlay.d` directory contains a file called `statoverride` at the root, pass it to ostree.  This allows overlay files to have permission bits that aren't tracked by Git.
`statoverride` files don't support comments.  For convenience, filter out lines starting with `#`.
=> cmdlib: support `statoverride` file in root of an `overlay.d` directory

src/deps.txt, src/pkcs7encrypt
This will be used in the RHCOS pipeline to encrypt build logs before they are uploaded to S3.
=> pkcs7encrypt: Added a command for encrypting files using openssl

ci/Dockerfile
Latest rpm-ostree release with
https://github.com/coreos/rpm-ostree/pull/2990 is in the continuous tag.
Rebuild to get it into cosa.
Closes: https://github.com/openshift/os/issues/552
=> ci/Dockerfile: bump Quay.io nocache hack

docs/kola.md, mantle/kola/harness.go, src/cmd-kola
Before introducing more functionality to deny listed tests, we want to have the deny list logic contained in a single location (kola).
=> kola: Move kola-denylist.yaml related sugar from cmd-kola to kola

src/cmdlib.sh
We need to use the same `src=` annotation we use in
other places to work on a pristine build before `make install`
has run.
=> cmdlib: Fix shellcheck for libguestfish.sh

src/cmd-generate-release-meta
We really need to fix the number of places that need to be
touched when adding a new platform.
=> generate-release-meta: Add azurestack

src/cosalib/ibmcloud.py
The default auth file path is ~/.bluemix/ but this provides an option for the user to override that which will be usefult for the pipeline
=> cosalib/ibmcloud.py: add optional option for the authorization file

mantle/kola/cluster/cluster.go, mantle/kola/tests/upgrade/basic.go
I'm trying to debug a failure in the upgrade test and not getting
any logging around the invocations of commands makes it really hard.
Because we always capture the target system journal by default,
add a new wrapper for `MustSSH` that prints the command to the
journal too.
I considered changing `MustSSH` by default but that's used
in a *lot* of places and I'd like to try this out in
just the upgrade test to start.  If this works OK we can
consider a tree-wide change.
=> kola: Add RunCmdSync that logs cmd to target journal, use in upgrade test

Makefile
Gangplank checks are broken on Prow. Since Ganplank is not a full-production tool, let's disable for now.
=> Makefile: disable Gangplank, again

src/cmdlib.sh
We need to use the same `src=` annotation we use in
other places to work on a pristine build before `make install`
has run.
(cherry picked from commit 8a13c56b847fd95960d829f2db1940286b3ec70f)
=> [rhcos-4.8] cmdlib: Fix shellcheck for libguestfish.sh

src/cosalib/ibmcloud.py, src/cosalib/qemuvariants.py
This is a followup to 835cd92. I couldn't get
`cosa buildextend-* --compress` to work without it.
=> cosalib: Add compress option for qemuvariants, ibmcloudvariants

mantle/kola/tests/upgrade/basic.go
Part of https://github.com/coreos/fedora-coreos-tracker/issues/812
The code here is unfortunately actually *more* complicated,
but that's due to an ostree/ostree-ext bug.
It was easier to use `sudo` for everything instead of doing the
---
=> kola: teach upgrades about oci-archive

docs/kola.md, mantle/kola/harness.go
Add snooze support for tests as described [here](https://github.com/coreos/coreos-assembler/issues/2237).
=> mantle/kola/harness.go: add snooze support for tests

src/cmd-koji-upload
Backport from #2134 and #2159:
Allow Koji to create a build reservation and use it after.
Add the build_id into the build metadata.
Attach architecture with name in the meta.json
=> koji: Backport - Refactor it to allow Koji build reservation

mantle/platform/platform.go, mantle/platform/platform_test.go
mantle/platform: Remove unneeded breaks
---
mantle/platform: Fix unit failures ignore path
Use the stable DBus interface instead of parsing systemctl output.
Fixes: a542f266 mantle/platform: Ignore some non-fatal unit failures in RHCOS
=> mantle/platform: Fix FCOS support in non-fatal unit failures ignore path

src/cmdlib.sh
OpenShift CI sets `ARTIFACT_DIR` as a place to put log files.
Let's always copy the console there if set; this will help
debug things like OOM issues.
=> build: Honor ARTIFACT_DIR for supermin

gangplank/cmd/gangplank/commonflags.go, gangplank/cmd/gangplank/generate.go, gangplank/internal/ocp/cosa-podman.go, gangplank/internal/ocp/return.go, gangplank/internal/ocp/worker.go, gangplank/internal/spec/cli.go, gangplank/internal/spec/stages.go
```
commit 320e4bef1406441db9aaa19d3a40ca35f60ee8b6
Date:   Mon Jul 26 14:33:07 2021 -0400
gangplank: add a ReturnFiles stage
Allows for users to request files to be returned back to the minio
server. One case where this is useful is in our lockfile bumper
where we run `cosa fetch --update-lockfile` and want to get just the
json file copied back. Example usage:
```
gangplank pod --podman --singleCmd "cosa fetch --update-lockfile --dry-run" --returnFiles src/config/manifest-lock.aarch64.json
```
or as part of a spec:
```
job:
strict: true
miniocfgfile: ""
recipe:
git_ref: testing-devel
git_url: https://github.com/coreos/fedora-coreos-config
stages:
- id: ExecOrder 1 Stage
execution_order: 1
description: Stage 1 execution base
post_commands:
- cosa …
=> gangplank: add a ReturnFiles stage

.cci.jenkinsfile, Dockerfile
We support building this image in many places; in OpenShift
clusters, locally via `podman` as well as in the special `quay.io`
build environment.  The gangplank tests are failing in the latter.
In practice, don't need to re-run unit tests in quay.io.  Code
landing via PRs is already tested.
=> Dockerfile: Stop running unit tests

src/cmdlib.sh
We should allow memory here to be configurable so that
one doesn't need to hack the code to tweak things.
xref https://github.com/openshift/os/issues/594
=> build: Add COSA_SUPERMIN_MEMORY env variable

src/cmd-build-fast, src/cmd-offline-update, src/offline-update-impl
In some situations, scripts or tests expect a single deployment to exist
since it's presumably the first boot. Since this is likely the common
case, start undeploying by default, and add an option to skip it if
wanted.
=> cmd-build-fast: add --no-undeploy

docs/kola.md, mantle/kola/harness.go
This should make it easier for us to manage the policy in the FCOS
configs rather than having to update the go tests.
=> mantle/kola: add support for denylisting platforms

mantle/kola/tests/misc/network.go
Don't try to independently mount the boot partition. We'll race with the
regular but read-only boot mount. Instead, depend on the latter, then
remount it read-write in a mount namespace.
Closes: #2326
=> tests/rhcos.network.*: fix /boot mount handling

src/cmd-sign
```
commit e8bc539458b2a310fa699ab64d181f36a913fa6a
Date:   Fri Jul 30 15:07:21 2021 -0400
cmd-sign: conditionalize ostree commit import
Let's only re-import back into tmp ostree repo if it exists. In some
cases the build may have happened remotely and the tmp repo won't exist.
commit 8a98016066c112bea705bb9233b8d615a0fe1fe1
Date:   Fri Jul 30 15:05:53 2021 -0400
cmd-sign: update to accept architecture as an argument
Also update the locations in s3 for temporary file passing
to be architecture specific so we don't stomp on each other
if multiple runs are going at the same time.
```
=> cmd-sign: update to accept architecture as an argument

src/cmd-koji-upload
The tag passed to cmd-koji-upload was only verified as a valid tag but
never used to tag builds. Lets start tagging the builds if the principle
has permissions to do so.
I couldn't actually test the tagging because the principle I use does not
have permissions to tag builds.
=> cmd-koji-upload: tag brew builds

src/cmd-buildprep
Adds a `--arch` argument for achieving this goal.
=> cmd-buildprep: handle fetching data for specific architecture

mantle/cmd/kola/testiso.go
Default to ignore signing verification when running with development build to pass the testiso/iso-install tests
=> kola/testiso.go: Added test signing by default when running in dev build

src/cmd-buildprep, src/cmd-buildupload
```
commit f11a9761be763b199e737eddf27616a3f090f613
Date:   Wed Aug 4 15:56:15 2021 -0400
cmd-buildprep: return early if no artifacts for build+arch
In the case there aren't any built artifacts for the particular
architecture for this build id return early.
commit 61951149fdfe3af5439cba29d6d419d5ac9532f9
Date:   Wed Aug 4 11:48:21 2021 -0400
cmd-buildupload: only re-upload images if forced
Right now buildupload will s3_copy all of the images without
checking if they exist already in s3. Let's make it default to
not do that, but allow it to be forced with --force.
```
=> buildprep, buildupload fixes to prep for aarch64 work

src/cmd-buildupload
Will help us to surgically upload just the ostree tar file in the early
stages of our pipeline and later upload the rest.
=> cmd-buildupload: add --artifact for specifying which artifacts to upload

src/cmdlib.sh, src/cosalib/builds.py
```
commit 44a4821ce974de2f3a41b9f98a60557696f0fad6
Date:   Thu Aug 5 12:33:55 2021 -0400
cmdlib: add support for arch to insert_build
This will allow us to call insert_build with an optional
target architecture, which is then passed on to insert_build
from the builds python library.
Also updated an error message in builds.py.
commit a74a4f922796f811fc7c2195bd794c6659305b4d
Date:   Thu Aug 5 11:51:00 2021 -0400
cmdlib: modify insert_build to use passed in argument for directory
Previously the $dir was not used and we only got lucky because the
single caller of this function was also using a variable named
$workdir.
```
=> cmdlib: add support for arch to insert_build

mantle/cmd/kola/devshell.go, mantle/cmd/kola/qemuexec.go
Add a generic `--ssh-command` switch which overrides the SSH default of
spawning the user's shell. This can be useful for example if you just
want to run a single command and get out, or if you want to line up a
command in the VM so it's already underway by the time you context
switch back to it.
Example usage:
```
$ cosa run -x 'rpm-ostree status'
[QEMU guest is booting] cosa-devsh login: core (automatic login)
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/testing-devel
Version: 34.20210726.dev.0 (2021-07-26T18:15:29Z)
Commit: a698c7a3f189c6ccc3cdc5352cf2f06d150eb7412f4bd318e32d400ab0e2658b
GPGSignature: (unsigned)
[SESSION] Clean exit from SSH, terminating instance
```
Or sounding the bell when a command is done:
```
$ cosa run -x 'some long command; echo -e "\a"; …
```
=> kola/qemuexec: add --ssh-command

ci/prow-rhcos.sh
The goal is to test an e2e RHCOS build, in the same way that PRs
to openshift/os do.
This PR will do nothing when merged; the actual execution will
be enabled via a PR to openshift/release.
---
=> ci: Add prow-rhcos.sh

ci/prow-rhcos.sh
In rehearsal I'm seeing
`Unhandled base ref: master` which I *think* may be
due to the fact rehearsal is a very special case that is
simulating a PR, and it doesn't know the default branch is `main`.
Let's just pass through `master` as the identity even though
we shouldn't need it later.
=> ci/prow-rhcos.sh: Also map `master` → `master`

mantle/go.mod, mantle/go.sum, mantle/vendor/github.com/coreos/stream-metadata-go/release/release.go, mantle/vendor/github.com/coreos/stream-metadata-go/release/translate.go, mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream.go, mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream_utils.go, mantle/vendor/modules.txt
This gets us support for Aliyun images that have been uploaded to the
cloud and replicated across regions.
=> mantle: bump coreos/stream-metadata-go

mantle/cmd/kola/devshell.go
Follow-up to #2338.
Otherwise, our logic here will keep trying to reconnect and rerun the
command if it exited with non-zero.
While we're here, propagate the error up so that `kola qemuexec` itself
returns non-zero if the command exited non-zero.
=> kola/qemuexec: always exit after --ssh-command exits and propagate error

src/cmd-buildprep
Add support for the user specifying --arch=all, which will inspect
the builds.json for a particular build and download the meta.json
and ostree commit object for all architectures related to that build.
This is useful when doing things like generating the release.json
which needs information from each of the architecture builds in
order to give a complete release.json.
=> cmd-buildprep: allow for --arch=all

src/cmd-build, src/cmdlib.sh, src/cosalib/builds.py
If there is ever a case where there are missing architectures for
a given build then the pipeline will buildprep the meta.json from
the last released build for that architecture. Now we need to be
able to tell init_build_meta_json that the parent for the given
architecture might not be the latest build, in which case we'll
specify the parent build ID directly.
=> cosalib: support parent_build argument to init_build_meta_json

src/cmd-buildupload, src/cmd-compress
When we're operating on separate builders for different architectures
it's valid that build directories for the other architectures won't
exist locally on the machine. In that case let's have
`compress_one_builddir()` and `s3_upload_build()` return early.
=> cmd-compress,cmd-buildupload: return early if meta.json missing for arch

mantle/kola/tests/upgrade/basic.go
This is needed because https://github.com/coreos/zincati/issues/558 would
like to sanity check the stream of the newly deployed release before
finalizing.
=> fcos.upgrade.basic: keep metadata in new commit

mantle/cmd/kola/options.go, mantle/platform/platform.go, mantle/sdk/repo.go
```
commit d0aad530476227f69c8993f7bb55573bfb6b3f02
Date:   Tue Aug 10 12:26:01 2021 -0400
mantle/kola: pick up AMI from the build meta
Right now we have to specify --aws-ami even if we have build metadata.
This doesn't make a lot of sense since it's in the build metadata and
we shouldn't have to fish for it twice. Let's pull it from there
if the user didn't specify it.
commit bf459a30df40746cbbab80297a980dc9b0e06cb7
Date:   Tue Aug 10 10:44:38 2021 -0400
mantle/kola: switch AWS instance type based on arch
This will allow us to run against aarch64 without having to
specify the instance type each time.
commit a09a22e5fbfeb5fc37be95479b8e2aeaae56a766
Date:   Tue Aug 10 …
```
=> mantle/kola: a few additions for --arch

mantle/kola/tests/misc/boot-mirror.go
On those architectures, the root partition is placed on partition 3 instead of partition 4 due to a [Butane bug](https://github.com/coreos/fedora-coreos-tracker/issues/855#issuecomment-896387343) that's difficult to fix.
=> mantle/kola/tests: disable RAID tests on aarch64/ppc64le

src/cmd-sign
```
commit c99d7e9e94efbd8868a3ee662ae8cba48d261bbd
Date:   Wed Aug 11 14:06:30 2021 -0400
cmd-sign: require passing in the build id
Now that we have multipe architectures building let's be very explicit
what build ostree/artifacts we want signed by requiring the user to
tell us.
commit b98eb9acbfd905f60d12a00b5bfa06f3b502d82f
Date:   Wed Aug 11 14:04:51 2021 -0400
cmd-sign: fix arch handling in cmd_robosignatory
I missed this one in 62fae82.
```
=> cmd-sign: fix arch handling in cmd_robosignatory

src/cmd-sign
I didn't realize there was a later `build.write()` which
isn't supported when it's purely json (which is what's
returned by `builds.get_build_meta()`).
=> cmd-sign: switch back to cosalib.meta library

src/cmd-generate-hashlist
This allows us to switch based on the architecture and get
the appropriate meta.json.
=> cmd-generate-hashlist: support passed in --arch

src/cmd-generate-release-meta
If a build includes Aliyun images uploaded/copied to multiple
regions, they should be included as part of the `release.json`
=> generate-release-meta: add support for uploaded Aliyun images

src/cmd-generate-hashlist
Since the qemu image isn't used in hashlist generation at all
and the ostree tarball is, let's include the filename of the tarball
in the metadata instead.
Also, there's no need for it being a relative path versus just a
filename so make it just the filename.
Also, add in the architecture into the metadata, because why not?
This yields something like the following at the beginning of the
json output:
```
{
"release": "34.20210811.dev.0",
"meta": {
"generator": "coreos-assembler-64649ca8a328b7599d90207b2ab6406e2a4564d0",
"timestamp": "2021-08-12T14:15:19.685588",
"ostree": "fedora-coreos-34.20210811.dev.0-ostree.aarch64.tar",
"arch": "aarch64"
},
```
=> cmd-generate-hashlist: use ostree, not qcow in metadata

mantle/kola/tests/misc/boot-mirror.go
In 6796eeb we added support for kola --arch so the comments
weren't 100% true any longer. Tweak them to be more accurate
because we do still assume the same architecture for QEMU tests.
=> mantle/kola: fixup comments about architecture assumption

mantle/Makefile, mantle/build, mantle/kola/harness.go
```
commit 2286ef173bbfa2fb43c844b7e17dd5f4ff503ffe (HEAD -> dusty-kolet-multi-arch, origin/dusty-kolet-multi-arch)
Date:   Wed Aug 11 16:09:27 2021 -0400
mantle: cross build kolet
This will enable us to run tests on our aarch64 AWS instances from
COSA running in our main openshift/jenkins pipeline (x86_64).
commit 6843431ba1429de56914ee82c30449bc9abfab06
Date:   Wed Aug 11 16:08:12 2021 -0400
mantle/kola: pick up arch from kola options
`kola --arch` was added in 6796eeb and we can use it now if the user
is targeting an alternative architecture to the one they are
currently running on.
commit 4020ce20728dab9d8493074e6edd371350b340bc
Date:   Wed Aug 11 16:05:32 2021 …
```
=> mantle/kola: add back in cross building of kolet

mantle/kola/tests/crio/crio.go
As mentioned here: https://bugzilla.redhat.com/show_bug.cgi?id=1986239#c3, the pod spec has a namespace option and is requesting a container level pid namespace whereas the container spec is requesting a pod level pid namespace.
=> kola: tests/crio: add namespace_option to container spec

gangplank/internal/ocp/return.go
We look for them in cosaSrvDir, "tmp" so let's try to copy them
from there too.
=> gangplank: grab logs from same location we checked for them at

mantle/cmd/kola/options.go
This will prevent us from having to specify the image on the command
line every time.
=> kola/options: auto pickup GCP image from meta.json

gangplank/internal/ocp/worker.go
ART and RHCOS-devel use opaque secrets for push registries. 
=> Gangplank: support opaque secrets for push secrets

mantle/cmd/kola/options.go
That way one can just type `-p iso`.
=> kola: alias `iso` to `qemu-iso`

ci/Dockerfile
To pick up coreos-installer-0.10.0-2.fc34 from the continuous tag.
For https://github.com/coreos/coreos-installer/pull/599
=> ci/Dockerfile: bump Quay.io nocache hack 20210819

gangplank/cmd/gangplank/pod.go, gangplank/internal/ocp/bc.go, gangplank/internal/ocp/filer.go, gangplank/internal/ocp/ssh.go
If we try to use port 9000 for every ssh forwarded minio then we
can only run one gangplank at a time because the remote host only
has one port 9000. Let's have SSH dynamically choose the port and
then update our configs based on that.
=> gangplank: use dynamically selected port for ssh port forwarding

gangplank/internal/ocp/ssh.go
We need to re-use the one that was created outside of the for loop
not create a newly scoped version of remoteSSHport. This meant the
port got changed to 0:
```
INFO[0000] Changing minio port for local and remote (forward) from 0 to 0
```
and since there was already special handling to assign the port to 9000
if it was 0 then it made it through. Fix this now.
=> gangplank: fix subtle creation of new remoteSSHport var

mantle/cmd/kola/kola.go, mantle/fcos/metadata.go
This allows us to get the build URL based on the passed in
architecture to `kola --arch=$arch`. It will allow us to run
upgrade tests for aws even from an x86_64 cosa.
=> mantle: pass in the kola arch for GetCosaBuildURL

ci/Dockerfile
This should work around the osbuild-composer upgrade issues breaking CI.
Closes: #2382
=> ci/Dockerfile: force rebuild of cosa-buildroot:latest

src/cmd-buildprep
I was debugging an issue with S3 earlier and it was helpful
to understand which case I was hitting.
=> buildprep: Print different message between "not found" and "empty"

mantle/cmd/kola/qemuexec.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/kola/tests/misc/multipath.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/azure/cluster.go, mantle/platform/machine/do/cluster.go, mantle/platform/machine/esx/cluster.go, mantle/platform/machine/gcloud/cluster.go, mantle/platform/machine/openstack/cluster.go, mantle/platform/machine/packet/cluster.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/metal.go, mantle/platform/platform.go, mantle/platform/qemu.go
The two key commits are:
```
tests/multipath: add multipath.day1 test
Rename the existing test to `multipath.day2` and add a new
`multipath.day1` test which leverages the new `MultiPathed` test knob to
tell kola to provision a multipathed boot disk.
```
---
```
tests/multipath: add multipath.partition test
There have been requests to support multipath on specific partitions
instead of the whole disk. There are some caveats, but this should work.
Add a test for this which verifies that `/var/lib/containers` can be on
multipath.
The huge annoyance here is that we can't use Ignition to format the
disk. I'm hoping we can clean this up eventually, but it's intimately
tied to how multipath itself works and how FCOS/RHCOS integrates it.
Related: …
```
=> Enhance multipath support and add more multipath tests

gangplank/internal/ocp/cosa_init.go, gangplank/internal/ocp/worker.go, gangplank/internal/spec/cli.go, gangplank/internal/spec/jobspec.go, src/cmd-init
```
commit 8220836713617ef039b2c82887fe0b6728364678
Date:   Fri Aug 27 22:02:27 2021 -0400
gangplank: allow for specifying configs git commit
This exposes the `cosa init --commit` flag into the jobspec, which
allows one to force a commit on the specified branch to be used. This
is useful in pipeline builds when later subordinate (multi-arch)
pipelines run and we want them to target the same git commit as the
earlier x86_64 pipeline run.
commit a5f2d12cd04aec5f5c237a2c0f26b58e111c1d32
Date:   Fri Aug 27 16:21:32 2021 -0400
cmd-init: support --commit
Useful for reseting the local branch of the recently cloned config
git repo to a specific commit (full SHA-1).
This is most useful in a automated environment …
```
=> cmd-init,gangplank: allow for specifying git commit on branch

mantle/kola/cluster/cluster.go, mantle/kola/tests/ostree/unlock.go
The original goal of this new API was just to log the command invocation
to the journal, but looking at things further here, the common path
is to *not* capture the output.
Fix things here so that we log both the command stdout+stderr
as a unified stream into the journal, and then capture the last 20
lines from the journal for `kola` as a Go error message.
(In practice, we should probably not capture the journal text into
`t.Fatalf()` but just say "see the journal" and then have a higher
level pass which gathers relevant failures from the journal
from all machines)
My immediate motivation is improved debugging for hotfix
failures: https://github.com/coreos/fedora-coreos-tracker/issues/942
=> kola: Change RunCmdSync to log command output to journal too

mantle/kola/tests/crio/crio.go, mantle/kola/tests/docker/docker.go, mantle/kola/tests/etcd/rhcos.go, mantle/kola/tests/ignition/empty.go, mantle/kola/tests/ignition/execution.go, mantle/kola/tests/ignition/resource.go, mantle/kola/tests/ignition/security.go, mantle/kola/tests/ignition/ssh.go, mantle/kola/tests/ignition/units.go, mantle/kola/tests/misc/aws.go, mantle/kola/tests/misc/boot-mirror.go, mantle/kola/tests/misc/multipath.go, mantle/kola/tests/misc/network.go, mantle/kola/tests/misc/nfs.go, mantle/kola/tests/misc/tls.go, mantle/kola/tests/ostree/basic.go, mantle/kola/tests/ostree/unlock.go, mantle/kola/tests/podman/podman.go, mantle/kola/tests/rhcos/sssd.go, mantle/kola/tests/rhcos/upgrade.go, mantle/kola/tests/rpmostree/deployments.go, mantle/kola/tests/rpmostree/status.go, mantle/kola/tests/upgrade/basic.go, mantle/kola/tests/util/containers.go
Probably 70% of the invocations of `MustSSH` weren't actually
capturing stdout, so it would just get lost.  Instead, use
`RunCmdSync` for this which keeps everything consistently in
the systemd journal in order.
This will help debugging because often one needs to consult
the journal, and having log messages there will help.
=> kola: Replace all non-capturing MustSSH with RunCmdSync

Dockerfile, ci/Dockerfile
The internal RHCOS pipeline is rebuilding cosa due to multiarch, and
there was a subtle difference that crept in between the two `Dockerfile`s;
notably the main one wasn't configuring the `-continuous` repo
where we'd bypassed the manual Bodhi stuff to fast track
a new `rpm-ostree`.
We need that for https://github.com/openshift/os/pull/603
Sync the two `Dockerfile`s and also require the updated version.
=> build: Keep Dockerfile + ci/Dockerfile in sync, require rpm-ostree v2021.10

docs/kola/external-tests.md, mantle/cmd/kolet/kolet.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/platform/conf/conf.go
Originally discussed here: [issue](https://github.com/coreos/coreos-assembler/issues/2236)
We want to be able to run tests that do not conflict with each other in one VM. We have labeled such tests as "NonExclusive". Instead of bringing up a cluster and destroying it for each test, we bring up a cluster and run all tests before destroying it. We will first merge the ignition/butane configs for each non-exclusive test to run them on the same machine .
Marked this as draft because their is some code that I would like to refactor before merging.
=> Add support for running non-exclusive tests in one VM

src/cmd-buildextend-live
#1990 added an ESP to the ISO's hybrid GPT to help EFI systems that won't boot El Torito from a hard disk.  However, when booting from the ESP, GRUB won't read the `grub.cfg` from the main ISO image, and just drops to a grub prompt.  Add a stub `grub.cfg` that points GRUB to the right place.
Fixes: #1990
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/724
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/953
=> buildextend-live: add stub `grub.cfg` to `efiboot.img`

src/cmd-build
For rpm-ostree, we currently need the two colons `:` in e.g.
`rpm-ostree rebase oci-archive:/path/to/blah:latest` to know
that we're rebasing to a container image (as opposed to just
`rpm-ostree rebase oci-archive:/path/to/blah` which may be
an ostree remote named `oci-archive`.
However, unlike the docker registry transport, by default
no tag `:latest` is emitted into the archive unless specified.
=> build: Add a `:latest` tag to ociarchive export

src/download-extensions
xref BZ https://bugzilla.redhat.com/show_bug.cgi?id=2000195
librepo writes these xattrs, but unfortunately Linux `tmpfs`
doesn't support `user.*` xattrs.  And the OpenShift MCO
falls back to doing `podman cp` in some cases, which fails
when these xattrs are present.
Since the xattrs are just cache data and not functional,
just strip them out.
Closes: https://github.com/coreos/coreos-assembler/issues/2401
=> [4.7] download-extensions: Strip out user.* xattrs

src/cmd-buildextend-live
At runtime it's immediately overwritten by the GRUB menu, but it shows up in console logs.  This will help validate automated tests.
=> buildextend-live: log a message when booting via the stub grub.cfg

mantle/kola/tests/rhcos/upgrade.go, mantle/kola/tests/upgrade/basic.go
I forgot that we forked the upgrade tests between FCOS/RHCOS
when doing https://github.com/coreos/coreos-assembler/pull/2300
The ugly hack here is to downconvert the oci image on the kola
container side to the old tar format, because the rpm-ostree
in RHEL8 is too old to natively accept the ociarchive.
Once that is fixed, (which will be helped by us testing
this end-to-end) then this code will get nicer.
=> kola: Add support for .ociarchive to RHCOS upgrade test

mantle/kola/harness.go
fixes: https://github.com/coreos/coreos-assembler/issues/2407 
Failure of a non-exclusive test would result in a golang panic. We were
using a TestCluster object that references the parent's harness.H. Thus, on
error, the parent's goroutine would incorrectly be terminated.
To fix the problem we create a new TestCluster for each test. This will
reference the correct harness.H object for its corresponding test.
=> kola/harness.go: fix panic on non-exclusive test fail

mantle/cmd/kola/options.go
Now that we've got console=ttyS0 in the aarch64 images they can boot
on all aarch64 instance types (see [1]). The c6g.xlarge is not a bare
metal instance type and thus will boot much faster so let's go with
that.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/920)
=> mantle/kola: set c6g.xlarge default aarch64 aws instance type

mantle/platform/api/openstack/api.go
For some reason the instances in VexxHost started taking longer than
5 minutes to come up and it's causing test failures. Let's increase
the timeout to 10 minutes to see if that helps.
=> mantle/platform/openstack: wait 10 minutes for instances to come up

src/cmd-buildextend-live
Backport https://github.com/coreos/coreos-assembler/pull/2404 and https://github.com/coreos/coreos-assembler/pull/2409.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2000696.
=> [rhcos-4.8] buildextend-live: add stub `grub.cfg` to `efiboot.img`

src/cmd-buildextend-live
Backport #2404 and #2409.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2000697.
=> [rhcos-4.7] buildextend-live: add stub `grub.cfg` to `efiboot.img`

mantle/cmd/kola/options.go, mantle/cmd/kola/qemuexec.go, mantle/cmd/kola/testiso.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/qemuiso/flight.go, mantle/platform/metal.go, mantle/platform/qemu.go
We support writing the live ISO to a USB stick and booting that way, but that path exercises different bootloader code and we should test it explicitly.  Add a flag `--qemu-iso-as-disk` and a testiso scenario `iso-as-disk` that do so.  QEMU's UEFI firmware would still try to boot via El Torito, but some hardware prefers or requires booting via the ESP in the hybrid GPT, so overwrite the El Torito signature in this case to force QEMU to boot via the ESP.
`iso-as-disk` is based on `iso-live-login`, which has been disabled by default for 17 months with a comment saying that it doesn't work.  Re-enable the latter by default; let's see whether that's still true.
=> mantle/kola: add testiso scenario for ISO copied to USB stick

mantle/kola/cluster/cluster.go, mantle/kola/tests/fips/fips.go, mantle/kola/tests/ignition/mount.go, mantle/kola/tests/ignition/sethostname.go, mantle/kola/tests/ignition/symlink.go, mantle/kola/tests/ignition/systemd.go
Followup to previous work on `RunCmdSync` which is aiming
to clean up how we run processes.
The rationale for this helper is much the same as APIs like
https://pkg.go.dev/github.com/stretchr/testify@v1.7.0/assert#Contains
It encapsulates this common pattern in a single line.
Also unlike `MustSSH`, we log the command to the systemd journal
too.
=> kola: Add an AssertCmdOutputContains

mantle/platform/conf/conf.go
Every time I go to `cosa run rhcos-4.6.qcow2` I keep being confused
by the failure in the initramfs, which is just because we inject
a too-new Ignition version.
I am sure we will want this for FCOS too - being able to conveniently
boot older disk images is very useful for bisection for example.
Ideally we make this configurable/autodetected, but for now
this hidden environment variable is enough to unblock me.
=> mantle: Add `COSA_IGNITION_DEFAULT_VERSION` envvar mainly for `cosa run`

src/oscontainer.py
I'm seeing this in my f34 toolbox trying to use `upload-oscontainer`:
```
+ podman --root=./tmp/containers-storage --storage-driver vfs push --tls-verify --authfile=/var/home/walters/.docker/config.json registry.ci.openshift.org/coreos/walters-rhcos-47:47.84.202109021332-0 --digestfile=tmp/oscontainer-digest
Error: failed to open 2048 locks in /libpod_lock: permission denied
```
I didn't dig deep into it; tried adding `--runroot` but that
didn't help.  Anyways, since `buildah` is I think better
tested for this purpose (nested container builds) let's use just
it instead of both `buildah` and `podman`.
This fixes the above bug.
=> oscontainer: Only use buildah to work around nested `podman push` bug

mantle/kola/tests/ignition/systemd.go
I missed the inverted logic here.  Strengthen the test
to actively check the service state instead of checking for the
absence of `inactive` in the output text.
=> kola/systemd: Fix regression in previous commit

mantle/kola/cluster/cluster.go, mantle/kola/tests/misc/boot-mirror.go, mantle/kola/tests/misc/selinux.go, mantle/kola/tests/ostree/basic.go, mantle/kola/tests/podman/podman.go, mantle/kola/tests/rpmostree/deployments.go, mantle/kola/tests/rpmostree/status.go
kola: Port more tests to AssertCmdOutputContains
In some cases this slightly weakens the assertion, but this
time I did look more carefully around substring matching.  Motivated
mainly by removing code.
---
kola: Add AssertCmdOutputMatches
This regexp based version can be more precise than just `Contains`,
and we had other tests that were doing this manually.
---
=> More assert output

src/cmd-upload-oscontainer
Add the architecture to the default push tag for two reasons:
- The release team for RHCOS has requested that the image tag include
the architecture.
- `aarch64` builds are planned to share the build id. Unless the images
are pushed to separate tags, one build could step on another.
The better solution would be to use "fat manifests", however, they
are not universally supported yet. Quay plans on providing this in the
4.8 time-frame. Until such time, this is the cleanest path.
(cherry picked from commit 44999096d5e22623356e2d0c50e39f31c8a63390)
=> [rhcos-4.7] src/cmd-upload-oscontainer: use arch in the push tag

src/cmd-upload-oscontainer
Add the architecture to the default push tag for two reasons:
- The release team for RHCOS has requested that the image tag include
the architecture.
- `aarch64` builds are planned to share the build id. Unless the images
are pushed to separate tags, one build could step on another.
The better solution would be to use "fat manifests", however, they
are not universally supported yet. Quay plans on providing this in the
4.8 time-frame. Until such time, this is the cleanest path.
(cherry picked from commit 44999096d5e22623356e2d0c50e39f31c8a63390)
=> [rhcos-4.6] src/cmd-upload-oscontainer: use arch in the push tag

mantle/cmd/kola/testiso.go
Move `iso-as-disk` to a separate function.  Log console and journal output from `iso-as-disk`, and console output from `iso-live-login`.
=> testiso: some `iso-as-disk` refactoring; log console and journal where we can

.cci.jenkinsfile
https://github.com/coreos/coreos-ci-lib/pull/91 drops the `basicScenarios` argument.
=> ci: kola basic scenarios are run by default now

src/cmd-sign
Part of: https://github.com/coreos/fedora-coreos-tracker/issues/812
We need to support signing ostree-native container images in
addition to our custom "ostree-archive-in-tar".  To keep both
paths aligned, first export the archive (whether tar or ostree-container)
to an unpacked `tmp/repo`.
This repo then takes the place of the previous temporary repo where
we added a dummy remote to use to verify the signature generated.
Use public OSTree APIs to read/write commit metadata instead
of doing it by hand.  But in the tar case, we keep the optimization of just
reflinking and appending to the archive.
=> sign: Add support for ociarchive

mantle/cmd/kola/options.go
Now that our stream metadata has mutli-arch images let's be able to
switch on that now as well. For example now we can pick up the aarch64
AMI with something like:
```
cosa kola spawn -b fcos --stream stable --arch=aarch64 -p aws --aws-credentials-file /srv/creds
```
=> mantle/kola: grab AWS images for aarch64 from stream metadata

mantle/cmd/kola/qemuexec.go
Seems like a natural thing to do, so let's support it.
See: #2430
=> qemuexec: allow specifying `--kargs` multiple times

ci/Dockerfile
To pick up newer ostree.
Again.
=> ci/Dockerfile: Blow out quay.io cache

mantle/cmd/kola/testiso.go, src/cmd-buildextend-live, src/cmd-generate-hashlist, src/cosalib/cmdlib.py
The EFI boot image currently looks like this:
EFI/BOOT/BOOTX64.EFI
EFI/BOOT/fbx64.efi
EFI/fedora/BOOTX64.CSV
EFI/fedora/fonts/
EFI/fedora/grub.cfg
EFI/fedora/grubx64.efi
EFI/fedora/mmx64.efi
EFI/fedora/shim.efi
EFI/fedora/shimx64.efi
Refactor the EFI boot image under the expectation that we never want to …
=> buildextend-live: drop shim fallback.efi from ISO; simplify EFI image

src/cmd-buildextend-live
Drop fallback.efi and its associated CSV from the EFI image.  Replace it with a copy of GRUB in the right place for shim to chain to it.
This is a lightweight backport of https://github.com/coreos/coreos-assembler/pull/2435.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2004449
=> [rhcos-4.9] buildextend-live: drop shim fallback.efi from ISO

src/cmd-buildextend-live
Drop fallback.efi and its associated CSV from the EFI image.  Replace it with a copy of GRUB in the right place for shim to chain to it.
This is a lightweight backport of https://github.com/coreos/coreos-assembler/pull/2435.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2004449
=> [rhcos-4.8] buildextend-live: drop shim fallback.efi from ISO

src/cmd-buildextend-live
Drop fallback.efi and its associated CSV from the EFI image.  Replace it with a copy of GRUB in the right place for shim to chain to it.
This is a lightweight backport of https://github.com/coreos/coreos-assembler/pull/2435.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2004449
=> [rhcos-4.7] buildextend-live: drop shim fallback.efi from ISO

mantle/cmd/ore/openstack/create.go, mantle/go.mod, mantle/kola/tests/ignition/ssh.go, mantle/platform/api/openstack/api.go, mantle/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/doc.go, mantle/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go, mantle/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/results.go, mantle/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/urls.go, mantle/vendor/modules.txt
```
commit fe65d83bb67a89b0a62a4508fa84764917c9c02c
Date:   Thu Sep 16 13:55:11 2021 -0400
mantle/openstack: add ability to mark visibility for uploaded images
Eventually we want our uploaded images to stay in VexxHost so users
there can use them. For now we delete them every time. Let's expose
a flag so that the image visibility can be exposed at image creation
time.
commit c17deee4181bf357f1cb9e05b508fe4bc4aca82e
Date:   Thu Sep 16 10:27:06 2021 -0400
mantle/openstack: support specifying image architecture
This adds an --arch argument to `ore openstack create-image`
and will allow us to create images with the "architecture"
property. This means we can create "aarch64" images and then
test them in VexxHost. …
```
=> mantle/openstack: various openstack updates

mantle/platform/qemu.go
On a loaded CI system, there can be latency spikes due to
contention on I/O for example.
Since the kola tests already have overall timeouts, bump this timeout
much higher to reduce the flake rate.
If we start going past 30s, it seems likely that instead of bumping
this timeout we need to reduce parallelism on the CI system.
=> qemu: Bump timeout for qmp connection

mantle/platform/qemu.go
When using a qemu with commit ccd3b3b8112b ("qemu-option: warn for
short-form boolean options"), "cosa kola run" throws deprecation
warnings:
qemu-system-s390x: -chardev socket,id=qemu-qmp,path=...,server,nowait: warning: short-form boolean option 'server' deprecated
Please use server=on instead
qemu-system-s390x: -chardev socket,id=qemu-qmp,path=...,server,nowait: warning: short-form boolean option 'nowait' deprecated
Please use wait=off instead
Fix up the 'server' and 'nowait' options accordingly.
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>
=> mantle/platform/qemu: update deprecated -chardev options

src/cmd-buildextend-live
Drop fallback.efi and its associated CSV from the EFI image.  Replace it with a copy of GRUB in the right place for shim to chain to it.
Unlike 4.7+, the 4.6 live ISO doesn't attempt to support UEFI booting when copied to a USB stick (except for firmware that can do so via El Torito).  Fixing this is a …
=> [rhcos-4.6] buildextend-live: drop shim fallback.efi from ISO

src/cmd-buildextend-live
coreos-installer will soon be able to access ISO 9660 contents by path (https://github.com/coreos/coreos-installer/pull/620).  Add a JSON file to the ISO with the embed area details.  This paves the way for eventually removing the custom ISO 9660 System Area headers.
This change won't affect existing releases of coreos-installer.
=> buildextend-live: add JSON file to the ISO with kargs embed info

src/deps.txt
I'd like to use the official Fedora prod OSTree repo config shipped in
FCOS to pull down commits in the release pipeline. But it's obviously
useful to have it available too for manual testing.
=> deps: add fedora-repos-ostree

gangplank/internal/ocp/return.go
- Return the config-git file as default to minio.
- In situations like koji-update the coreos-assembler-config-git.json is
required. Since it is a really small file, let's make it default as well.
=> gangplank: Add coreos-assembler-config-git.json as default

mantle/kola/harness.go
We'd like to know when these pop up.
=> mantle/kola: detect kernel circular locking dep warning

gangplank/vendor/github.com/coreos/coreos-assembler-schema/cosa/cosa_v1.go, gangplank/vendor/github.com/coreos/coreos-assembler-schema/cosa/schema_doc.go, mantle/cmd/ore/ibmcloud/copy-object.go, mantle/platform/api/ibmcloud/s3.go, mantle/vendor/github.com/coreos/coreos-assembler-schema/cosa/cosa_v1.go, mantle/vendor/github.com/coreos/coreos-assembler-schema/cosa/schema_doc.go, schema/cosa/cosa_v1.go, schema/cosa/schema_doc.go, schema/generate-schema.sh, schema/v1.json, src/cmd-generate-release-meta, src/cosalib/ibmcloud.py, src/v1.json
This PR includes the following changes to support replication of IBMCloud images across regions:
- Add a `copy-object` command to `ore/ibmcloud` to copy an image from a bucket in one region to a bucket in another region
- Change schema of IBMCloud/PowerVS to an array rather than object to support multiple entries for the different buckets and regions
- Add replication functionality to `cosalib/ibmcloud.py` which can be leveraged in the pipeline.
- Add IBMCloud/PowerVS uploaded images to release.json
=> support replication of images across regions for IBMCloud and PowerVS

mantle/kola/tests/misc/multipath.go
In the `multipath.partition` test, we mount a multipath device on
`/var/lib/containers`, and rely on systemd to create the mountpoint. But
because we we weren't deterministically ordered against
`ostree-remount.service`, in rare cases we can run approximately at the
same time and systemd will try to create the mountpoint during that
short window of time when `/var` is read-only. So then the test failed
like this:
```
systemd[1]: Found device /dev/disk/by-label/dm-mpath-containers.
systemd[1]: var-lib-containers.mount: Failed to check directory /var/lib/containers: No such file or directory
systemd[1]: Mounting Mount /var/lib/containers...
mount[983]: mount: /var/lib/containers: mount point does not exist.
systemd[1]: var-lib-containers.mount: Mount process exited, code=exited, …
```
=> tests: squash ro `/var` race in multipath.partition

docs/building-fcos.md
It is easy to miss updating the local COSA container and trigger weird
issues during local development.
Add a check to the cosa shell alias looking at the container creation
time and printing out a warning (with a sleep 10) if it is more than a
week old and thus most probably outdated.
Do this only if no specific container image is set as it is the case
were most changes could be creating issues.
Fixes: https://github.com/coreos/coreos-assembler/issues/2434
=> docs: Add cosa container age check in cosa alias

src/cmd-buildextend-live
```
```
`35coreos-live/live-generator` creates `run-media-iso.mount`, which mounts the ISO from `/dev/disk/by-label/rhcos-<version>`.  The latter should point to `/dev/sda1`, but in this case it's pointing to `/dev/sda2`, which is `efiboot.img`. …
=> buildextend-live: fix `/run/media/iso` mount flake booting from disk

src/cmd-buildextend-live
```
```
`20live/live-generator` creates `run-media-iso.mount`, which mounts the ISO from `/dev/disk/by-label/rhcos-<version>`.  The latter should point to `/dev/sda1`, but in this case it's pointing to `/dev/sda2`, which is `efiboot.img`.  `/dev/sda2` does …
=> [rhcos-4.6] buildextend-live: fix `/run/media/iso` mount flake booting from disk

src/cmd-buildextend-live
```
```
`35coreos-live/live-generator` creates `run-media-iso.mount`, which mounts the ISO from `/dev/disk/by-label/rhcos-<version>`.  The latter should point to `/dev/sda1`, but in this case it's pointing to `/dev/sda2`, which is `efiboot.img`. …
=> [rhcos-4.7] buildextend-live: fix `/run/media/iso` mount flake booting from disk

src/cmd-buildextend-live
```
```
`35coreos-live/live-generator` creates `run-media-iso.mount`, which mounts the ISO from `/dev/disk/by-label/rhcos-<version>`.  The latter should point to `/dev/sda1`, but in this case it's pointing to `/dev/sda2`, which is `efiboot.img`. …
=> [rhcos-4.9] buildextend-live: fix `/run/media/iso` mount flake booting from disk

src/cmd-buildextend-live
```
```
`35coreos-live/live-generator` creates `run-media-iso.mount`, which mounts the ISO from `/dev/disk/by-label/rhcos-<version>`.  The latter should point to `/dev/sda1`, but in this case it's pointing to `/dev/sda2`, which is `efiboot.img`. …
=> [rhcos-4.8] buildextend-live: fix `/run/media/iso` mount flake booting from disk

src/cmd-buildextend-live
#2429 re-introduced the problem fixed by #1994: some arches remove bootloader configs after the config file list has been generated.  Defer writing out `kargs.json` until later, and filter out files that no longer exist.
Also fix the path to `grub.cfg` on ppc64le.
cc @coreos/multi-arch
=> buildextend-live: fix `kargs.json` for multi-arch

mantle/cmd/kola/options.go
Otherwise, we get a classic NULL pointer dereference. This isn't an
issue for AMIs because the default value is an empty list, so `range`
handles it fine.
=> kola/options: don't derive GCP options if build has no GCP image

src/cmd-build-fast
I did a `cosa build-fast` in my ostreedev/ostree git repo, which
failed because I'd also imported a container into `tmp/repo` which
creates a ref like `ostree/container/blob...`, but this code tried
to create a ref just named `ostree` - and that would require `ostree`
to be both a file and directory.
A general best practice for refs is namespacing; here, let's use
`cosa/fastbuild/`.
=> fastbuild: Better namespace for refs

ci/Dockerfile
Blow out the Quay cache to pick up `rpm-ostree-2021.11-3.fc34`
=> ci/Dockerfile: tickle Quay cache 2021-Oct-01

mantle/kola/tests/rhcos/upgrade.go, mantle/kola/tests/upgrade/basic.go, src/cosalib/cmdlib.py
https://github.com/coreos/rpm-ostree/pull/3129 redid the container
image handling in the experimental API we're using.
Closes: https://github.com/openshift/os/issues/645
=> Use `ostree-unverified-image:` with `rpm-ostree import`

ci/Dockerfile
Blow out the Quay cache to pick up `rpm-ostree-2021.11-3.fc34`
(cherry picked from commit f4981a44079854c52f5a24f0dc51a419c79d33b2)
=> [rhcos-4.9] ci/Dockerfile: tickle Quay cache 2021-Oct-01

docs/kola/external-tests.md, mantle/kola/harness.go, src/deps.txt
Updated the fcc instances in cosa repo to butane
Issue: https://github.com/coreos/coreos-assembler/issues/2456
=> Updated the fcct instances to butane

mantle/cmd/kola/testiso.go, mantle/platform/metal.go, src/cmd-buildextend-live
This switch enables the new minimal ISO packing feature (see
coreos/coreos-installer#559).
Once a coreos-installer version with miniso support is present in RHCOS
and FCOS, we can make it unconditional and drop the switch. For now,
this will allow testing in the coreos-installer upstream CI.
=> buildextend-live: add --miniso switch

mantle/kola/tests/util/rpmostree.go
That way we automatically get the `--ssh-on-test-failure` integration if
the command failed without having to re-implement it.
=> kola/util/rpmostree: use c.MustSSH instead of c.SSH to query rpm-ostree

build.sh
In openshift/os#646 it was reported that the s390x downstream builds
were failing to build the 4K metal image. This seems to be a
regression in the 5.14 version of the kernel.
This changes forces the use of the last successful 5.13 kernel. Of
note, the kernel packages have to be excluded from the `distro-sync`
operation or we end up with two versions of the the kernel installed
in the image.
(cherry picked from commit b3373de2a07c9037eb4a88bf0963a01036553b55)
=> [rhcos-4.9] build.sh: pin to kernel < 5.14 to unblock s390x builds

mantle/cmd/plume/cosa2stream.go, mantle/go.mod, mantle/go.sum, mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream.go, mantle/vendor/modules.txt
For the same reason as in fedora-coreos-stream-generator, it's useful to record the cosa version that was used to generate RHCOS stream metadata.
xref coreos/fedora-coreos-stream-generator#32
=> mantle/plume/cosa2stream: set metadata.generator field

src/cmd-artifact-disk, src/cosalib/ova.py
It's not really VMware-specific.
Broken out of #2489.
=> cosalib.vmware: rename to `ova`

src/cosalib/ibmcloud.py, src/powervs-template.xml
Remove the meta file that previously contained some metadata which was used by the IBMCloud UI to identify the os type for ova images. After discussions with the team it looks like they only recognize certain types of strings like 'rhel', 'centos', etc.. As of now rhcos/fcos (the strings) are not recognized as supported types and changes need to be made on the powervs side for this. Setting this to rhcos/fcos today causes problems when importing the image into the powervs instance.
Also change the ovf id to 80 which is recognized as rhcos/fcos.
=> ibmcloud: remove meta file for PowerVS and set ovf id to 80

ci/Dockerfile
To pick up new ostree 2021.5 for https://github.com/coreos/enhancements/pull/7
=> ci: Blow out quay.io cache

.github/dependabot.yml
We want to keep stream-metadata-go fresh for the same reason as in https://github.com/coreos/fedora-coreos-stream-generator/pull/27.  In addition, the release processes for Butane and Ignition vendor the new version here, so while we're at it, add some automation to help with that.
=> Enable Dependabot checks for Butane, Ignition, stream-metadata-go

mantle/kola/tests/coretest/core.go, mantle/kola/tests/coretest/helpers.go, mantle/util/common.go
Let's try to be more strict about how we use goroutines to make sure that we're not leaking a bunch of them as side-effects. This PR starts the process for a couple of callsites. There's more, but this is a start.
```
commit 01c355dc6dcfa56b37fdc3abdebca1770c88ac07
Date:   Mon Nov 1 13:15:37 2021 -0400
kola/coretest: factor out function to run cmd and timeout
Add a new `RunCmdTimeout` which runs a command but abandons if it's not
done after a certain timeout. Use it in coretest to dedupe `podman` and
`docker` runs. Additionally, the new code has no chance of leaking
goroutines (which... doesn't really matter here since it's native tests
running via kolet invocations, but just on principle).
commit eafd874952fcd2a9e0dd7dd77630c466fdf6c739
Date:   Mon Nov 1 12:06:53 2021 -0400 …
```
=> kola/coretest: tighten a bunch of uses of goroutines

src/cmdlib.sh
In the FCOS pipeline, we run with an unprivileged SCC and compose in an
emptyDir. So OpenShift sets the setgid bit so that we can actually write
to it, which ends up getting into the compose itself. We could upgrade
permissions there, but it seems simpler and more robust to consistently
strip out those bits here. We could probably fold this into ostree as
e.g. `--ugo-mode-bits-only` or something.
See: https://github.com/coreos/fedora-coreos-tracker/issues/1003
=> cmdlib: strip any setuid/setgid bits in overlay dirs

docs/kola/external-tests.md, mantle/kola/harness.go, mantle/kola/register/register.go
I'd like to add some tests which shouldn't run by default. Let's
leverage tags for this by having a new special `requiredTag` field which
makes the test be skipped unless the required tag is specified.
=> kola/harness: add support for required tags

docs/kola/external-tests.md, mantle/harness/harness.go, mantle/harness/harness_test.go, mantle/harness/suite.go, mantle/harness/test.go, mantle/harness/test_test.go, mantle/harness/timeout_test.go, mantle/kola/cluster/cluster.go, mantle/kola/harness.go, mantle/kola/register/register.go
Each test has an adjustable timeout and by default all tests have a 10 min
timeout. If a test is running a subtest, the timeout is ignored.
As requested here: https://github.com/coreos/coreos-assembler/issues/2350
=> mantle/harness, mantle/kola: Add test specific timeouts

mantle/kola/tests/ignition/resource.go, mantle/kola/tests/ignition/security.go, mantle/kola/tests/podman/podman.go
Some tests have been failing since timeouts were added. 
Let's readjust their timeouts.
=> kola/tests: bump timeout to 20 mins

build.sh
This reverts commit 7852f67f640ce31f629a15f0dd7a9e6ea95ac66c.
This should be fixed now in 5.14.14 which is in Fedora 34.
Closes: https://github.com/openshift/os/issues/646
=> Revert "build.sh: pin to kernel < 5.14 to unblock s390x builds"

mantle/platform/metal.go
This matches the latest syntax supported by
https://github.com/coreos/coreos-installer/pull/559.
=> platform/metal: update `coreos-installer iso extract minimal-iso` call

mantle/kola/tests/rpmostree/deployments.go, mantle/kola/tests/util/rpmostree.go
`bird` package we were using from EPEL was no longer available. This
is the third time we have had to deal with a package on a remote repo
that no longer worked for the `install-uninstall` use case.
This change moves away from using a remote yum repo and instead does
an install with a locally downloaded RPM. This uses the `aht-dummy`
RPM that was used in the `atomic-host-tests` of yesteryear. It has no
external dependencies and should work across all arches.
=> kola/tests/rpmostree: refactor install-uninstall test

mantle/kola/cluster/cluster.go, mantle/kola/tests/fips/fips.go, mantle/kola/tests/ignition/mount.go, mantle/kola/tests/ignition/sethostname.go, mantle/kola/tests/ignition/symlink.go, mantle/kola/tests/ignition/systemd.go, mantle/kola/tests/misc/selinux.go, mantle/kola/tests/rpmostree/deployments.go, mantle/kola/tests/util/rpmostree.go
```
commit bc7a0a1f8
Author: Micah Abbott <miabbott@redhat.com>
Date:   Tue Nov 9 12:32:43 2021 -0500
kola/tests/rpmostree: refactor install-uninstall test
`bird` package we were using from EPEL was no longer available. This
is the third time we have had to deal with a package on a remote repo
that no longer worked for the `install-uninstall` use case.
This change moves away from using a remote yum repo and instead does
an install with a locally downloaded RPM. This uses the `aht-dummy`
RPM that was used in the `atomic-host-tests` of yesteryear. It has no
external dependencies and should work across all arches.
(cherry picked from commit 91050be95226a5b47abb620c35dadf5d981f5d03)
commit e832ed1af
Author: Colin Walters …
```
=> [rhcos4.9] backport patches to refactor `rpmostree.install-uninstall`

mantle/kola/cluster/cluster.go, mantle/kola/tests/fips/fips.go, mantle/kola/tests/ignition/mount.go, mantle/kola/tests/ignition/sethostname.go, mantle/kola/tests/ignition/symlink.go, mantle/kola/tests/ignition/systemd.go, mantle/kola/tests/misc/selinux.go, mantle/kola/tests/rpmostree/deployments.go, mantle/kola/tests/upgrade/basic.go, mantle/kola/tests/util/rpmostree.go
The cherry-picks are getting more numerous...
```
commit 5ac7e0b9d
Author: Micah Abbott <miabbott@redhat.com>
Date:   Wed Nov 10 08:35:01 2021 -0500
tests: assert that the NFS service is active
When the `coreos.ignition.systemd.enable-service` was changed to use
`AssertCmdOutputContains`, the test started asserting that the output
of `systemctl status` had the `inactive` string. However, the Ignition
config is explicitly enabling the NFS service, so we should assert
that the service is actually `active`
(cherry picked from commit 37bd17dbcb9f5802f3949ea9bfb7297d5027ed0a)
commit b5fac38a9
Author: Micah Abbott <miabbott@redhat.com>
Date:   Tue Nov 9 12:32:43 2021 -0500
kola/tests/rpmostree: refactor install-uninstall test …
```
=> [rhcos4.8] backport patches to refactor rpmostree.install-uninstall

mantle/kola/tests/ignition/security.go
=> kola/tests/ignition/security.go: drop do and packet platform exclusions

mantle/build
It's annoying to have to build kolet for e.g. s390x locally. Let's add
an env var to allow configuring this. Now, a developer can do e.g.
```
make kolet KOLET_ARCHES=x86_64
```
=> mantle/build: allow overriding kolet arches to build

mantle/kola/tests/rpmostree/deployments.go
It was observed that RHCOS 4.8 builds were failing the
`rpmostree.install-uninstall` test after the backport (#2554)
had landed. I observed that the dummy RPM wasn't being written to the
filesystem. Further investigation showed that the Ignition
configuration be passed to the system was missing the test snippet
entirely. After changing the UserData to use V3, the merged Ignition
configuration was correctly generated and the test passed.
(Not sure how I missed this as part of #2554...)
=> [rhcos4.8] tests/rpmostree: use UserDataV3 for Ignition config snippet

docs/building-fcos.md, docs/gangplank/usage.md
Wrap code blocks containing Go templates with `{% raw %} ... {% endraw %}` to prevent Jekyll from interpolating Go templates as Liquid tags.
Fixes #2515
=> docs: fix go templates formatting

mantle/kola/cluster/cluster.go, mantle/kola/tests/fips/fips.go, mantle/kola/tests/ignition/mount.go, mantle/kola/tests/ignition/sethostname.go, mantle/kola/tests/ignition/symlink.go, mantle/kola/tests/ignition/systemd.go, mantle/kola/tests/misc/selinux.go, mantle/kola/tests/rpmostree/deployments.go, mantle/kola/tests/upgrade/basic.go, mantle/kola/tests/util/rpmostree.go
```
commit 9ad131d10
Author: Micah Abbott <miabbott@redhat.com>
Date:   Wed Nov 10 08:35:01 2021 -0500
tests: assert that the NFS service is active
When the `coreos.ignition.systemd.enable-service` was changed to use
`AssertCmdOutputContains`, the test started asserting that the output
of `systemctl status` had the `inactive` string. However, the Ignition
config is explicitly enabling the NFS service, so we should assert
that the service is actually `active`
(cherry picked from commit 37bd17dbcb9f5802f3949ea9bfb7297d5027ed0a)
commit df97cf935
Author: Micah Abbott <miabbott@redhat.com>
Date:   Tue Nov 9 12:32:43 2021 -0500
kola/tests/rpmostree: refactor install-uninstall test
`bird` package we were using from EPEL was no …
```
=> [rhcos-4.7] backport patches for `rpmostree.install-uninstall` refactor

mantle/platform/platform.go
Kola tars and gzips up the data directory and extracts it over an SSH
connection.  If the data directory contains relative symlinks to a
location out of the data directory, it will be a dangling symlink once
it is copied into the test machine. Adding the `-h` flag will follow the
symlinks and adds the actual files. This is useful for things such as
shared libraries between external tests.
=> kola: follow symlinks for kola external data dir

mantle/platform/api/aws/api.go, mantle/platform/api/aws/network.go
EC2 is eventually consistent.  When creating network resources and tagging them immediately afterward, we were hitting `NotFound` errors like:
harness.go:1213: Cluster failed starting machines: error resolving security group: error creating tags: InvalidVpcID.NotFound: The vpc ID 'vpc-0c11b5ac46ad8dc80' does not exist
harness.go:1213: Cluster failed starting machines: error resolving security group: creating subnets: error creating tags: InvalidSubnetID.NotFound: The subnet ID 'subnet-02d91caef7b71e4d5' does not exist
harness.go:1213: Cluster failed starting machines: error resolving security group: creating RouteTable: creating internet gateway: error creating tags: InvalidInternetGatewayID.NotFound: The internetGateway ID 'igw-0b35ecf4dfe47f621' does not exist
It's possible to specify …
=> mantle/platform/api/aws: tag network resources atomically

mantle/kola/cluster/cluster.go, mantle/kola/tests/fips/fips.go, mantle/kola/tests/ignition/mount.go, mantle/kola/tests/ignition/sethostname.go, mantle/kola/tests/ignition/symlink.go, mantle/kola/tests/ignition/systemd.go, mantle/kola/tests/misc/selinux.go, mantle/kola/tests/rpmostree/deployments.go, mantle/kola/tests/upgrade/basic.go, mantle/kola/tests/util/rpmostree.go
```
commit 1a643019a
Author: Micah Abbott <miabbott@redhat.com>
Date:   Wed Nov 10 08:35:01 2021 -0500
tests: assert that the NFS service is active
When the `coreos.ignition.systemd.enable-service` was changed to use
`AssertCmdOutputContains`, the test started asserting that the output
of `systemctl status` had the `inactive` string. However, the Ignition
config is explicitly enabling the NFS service, so we should assert
that the service is actually `active`
(cherry picked from commit 37bd17dbcb9f5802f3949ea9bfb7297d5027ed0a)
commit 66b47b15a
Author: Micah Abbott <miabbott@redhat.com>
Date:   Tue Nov 9 12:32:43 2021 -0500
kola/tests/rpmostree: refactor install-uninstall test
`bird` package we were using from EPEL was no …
```
=> [rhcos-4.6] backport patches for `rpmostree.install-uninstall` refactor

src/cmd-buildextend-live
When building RHCOS live iso with '--fast', this will use 'lz4' compressed filesystem that RHEL kernel not support. In this case, script should exit without building live iso. The right command  is 'cosa buildextend-live'.
=> src/cmd-buildextend-live: Exit when building RHCOS live iso using 'cosa buildextend-live --fast'

mantle/kola/harness.go, mantle/kola/register/depdirmap.go, mantle/kola/register/register.go
Recently, a need for DependencyDir in non-exclusive tests has arised.
Kola external tests are able to specify data (dependency dir) to sync with a
destination folder on a test VM. Previously, all external tests were exclusive
(each has its own VM). Thus, all dependency dirs could be mapped to the same
folder. In the case of non-exclusive tests,  this creates conflicts. Let's
modify the current framework so that non-exclusive tests have unique dependency dir
and destination dir pairs.
Due to the addition of non-exclusive tests, it is possible
that a single test will have multiple dependency dirs. Since
some tests may have the same dependency directory, non-exclusive
test wrapper may contain the same dependency directory that maps
to different destination directories. So we need to use both …
=> kola/register, kola/harness: Add DependencyDir support for non-exclusive tests

src/cmd-buildfetch
- Get all existing artifacts for the given build.
- In particular cases (brew improvements) we do want to
downlaod all available artifacts.
=> buildfetch: Allow 'all' in --artifact argument

Dockerfile
We currently need to hardcode the base Fedora image on the Prow side as
well, so let's add a comment in the `Dockerfile` as a reminder that it
needs to be bumped at the same time.
While we're here, fix the `/go` hack and add a comment to explain more.
See: https://github.com/openshift/release/pull/23744
=> Dockerfile: link to Prow job and fix chmod hack

mantle/platform/qemu.go
Fix another qemu deprecation warning when running "cosa run" with a 9p device.
Spotted in some test output that @miabbott recently posted into slack.
=> mantle/platform/qemu: update deprecated 'readonly' option

src/create_disk.sh, src/grub.cfg
This adds support for a `boot_uuid` dropin sitting alongside both the
BIOS and EFI GRUB configs to specify the UUID to scan for instead of
relying on labels.
Part of https://github.com/coreos/fedora-coreos-tracker/issues/976.
=> grub: support searching for boot by UUID

mantle/kola/tests/misc/network.go
The following tests also run in setups where it takes
~10 min/test to run:
rhcos.network.multiple-nics, rhcos.network.bond-with-dhcp, rhcos.network.bond-with-restart.
In order to avoid falling in the
border of the current timeout default (=10min), increasing
the tests to 20 minutes.
Signed-off-by: Ram Lavi <ralavi@redhat.com>
=> mantle/kola/tests, Add timeout to network tests

mantle/cmd/kola/kola.go, mantle/harness/reporters/json.go, mantle/kola/harness.go
Reruns are not always needed (such as in local testing). Lets
disable reruns by default and add an option to enable them.
Since reruns are not enabled by default, we can seralize the rerun data
so that it may be read again via `kola rerun` command. Rerun data is
stored in tmp/kola/rerun-data, where each line is the name of a failed
test.
=> kola: only rerun failed tests if --rerun provided

schema/cosa/cosa_v1.go, schema/v1.json, src/cmd-buildextend-nutanix, src/cmd-generate-release-meta, src/coreos-assembler, src/cosalib/qemuvariants.py, src/v1.json
Related to https://github.com/coreos/fedora-coreos-tracker/issues/1007
Build a raw image with the Ignition provider set to `nutanix` to correspond with https://github.com/coreos/ignition/pull/1284
I'm not sure if there's a way to upload a qcow2 image to Nutanix AHV via some external APIs. Let me get some confirmation before making those changes.
=> Add Nutanix platform 

Makefile
The Prow flow is really oriented towards building a container
and then testing it.  It's really maximally convenient if that
container ships the test code too.  This is distinct from what
we're doing with Jenkins which makes it easy to just inject code
into a running a container.
coreos-assembler is huge, these scripts are tiny, so let's just ship
them unconditionally.  Prep for testing cosa `rhcos-4.9` via OpenShift
Prow.
=> build: Ship `ci/` directory installed

Dockerfile, mantle/cmd/kola/testiso.go, src/cmd-buildextend-live
Now that we have coreos-installer v0.11.0 in cosa, we can drop the
`--miniso` switch and always turn it on. The only place which used it is
the coreos-installer CI, which will stop using it once this is merged.
Patch best viewed with whitespace ignored.
Closes: coreos/fedora-coreos-tracker#868
=> buildextend-live: always enable miniso

Dockerfile
Which contains https://github.com/coreos/coreos-installer/pull/694 for
https://github.com/coreos/coreos-assembler/issues/2583.
Closes: https://github.com/coreos/coreos-assembler/issues/2583
=> Dockerfile: tickly Quay.io cache for rust-coreos-installer-0.11.0-2

src/cmd-buildinitramfs-fast
Otherwise `qemu-img create` will just refuse to operate now.
=> cmd-buildinitramfs-fast: specify backing image format

mantle/kola/harness.go
```
commit 9095a8a76192eb50c97815cfb75db54f7b95eb7a
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Wed Dec 1 15:33:37 2021 -0500
harness: fix handling of required tags
I didn't fully retest this while reworking #2505. We need to treat the
required tag as just another tag. I.e. we need to set `tagMatch` so that
the if-statement that follows this hunk doesn't skip over it.
```
```
commit fd2c85df46915749e067d4955d86c2ec8b5a1b85
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Wed Dec 1 15:42:37 2021 -0500
harness: run tests with required tags if specified by name
Even if a required tag was not given, I think it's more ergonomic to
still run that test if the name was provided.
```
=> harness: fixes and tweaks related to required tags

mantle/kola/tests/ignition/mount.go
This is an alternative take on re-gaining coverage for `by-partlabel` on s390x - and feels much better than https://github.com/coreos/fedora-coreos-config/pull/1285. We'll still need to deny-list the tests in RHCOS for a little while until an updated `gdisk` has landed (see https://bugzilla.redhat.com/show_bug.cgi?id=1899990).
Note that I kept the `by-partuuid` infrastructure around for now, in case we want to make future use of it. Or for additional coverage maybe mount one disk with `by-partlabel`, and the second with `by-partuuid`? Opinions?
=> kola: also use by-partlabel for mount tests on s390x

mantle/kola/harness.go
As mentioned during review of https://github.com/coreos/coreos-assembler/pull/2593, these conditionals are pretty dense. Let's do some renaming and add some comments to help.
=> Make test filtering logic easier to understand

ci/prow-rhcos.sh
In rehearsal CI jobs on PRs to openshift/release, the first will be
correct but not the second (which will instead be the base ref of that
repo).
=> ci/prow-rhcos.sh: check both OPENSHIFT_BUILD_REFERENCE and PULL_BASE_REF

docs/cosa/buildextend-aws.md
This was the policy we ended up using when the GovCloud work was
recently done in the RHCOS build pipeline.
=> docs: provide complete AWS IAM policy example

src/cmd-build
Part of https://github.com/coreos/enhancements/blob/main/os/coreos-layering.md
I think we've now shaken out everything depending on this, so let's
flip the default.  In particular, this will ensure we're using it
on all FCOS branches.  Once it hits stable, we can drop all the old
tar code in coreos-assembler.
=> build: Default to ociarchive for ostree

docs/kola/external-tests.md, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/platform/api/aws/ec2.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/platform.go
For the Kubernetes node external test, we want to be able to run it in
both QEMU and AWS. But it's a storage heavy test, so the default 10G
image size is not enough. There's `additionalDisks` which works on QEMU,
but not on AWS. But really, we don't need it to be an additional disk.
Having the root disk itself be larger works just as well.
Add a new `minDisk` knob for this and plumb it through QEMU and AWS.
=> kola/external-tests: add support for `minDisk` field

src/cmd-buildextend-live
When `coreos-installer {iso|pxe} customize` runs, it would like to know what features are supported by the OS image it's customizing.  Most of that information is inside the squashfs, where coreos-installer can't easily get to it.  Collect that info (currently only one flag) and write a JSON file inside the initramfs image, where coreos-installer can find it in both the ISO and PXE images, and where it's not too easy for other random code to start depending on it.
=> buildextend-live: add `features.json` to live initrd image

src/deps.txt
We'll need the Aliyun CLI so we can do things like make images
public.
=> deps: install Aliyun CLI

gangplank/internal/ocp/sa_secrets.go
- We need to properly mount koji secret as 3 files:
keytab, principle and config.
=> ganplank: Fix koji secret

docs/kola/external-tests.md, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/kola/tests/misc/network.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/azure/cluster.go, mantle/platform/machine/do/cluster.go, mantle/platform/machine/esx/cluster.go, mantle/platform/machine/gcloud/cluster.go, mantle/platform/machine/openstack/cluster.go, mantle/platform/machine/packet/cluster.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/platform.go, mantle/platform/qemu.go
Add the ability to specify additional nics in kola.json for use by
external tests. This will be useful for testing with multiple nics.
Refer to the secondaryNics work in https://github.com/coreos/coreos-assembler/pull/2122
For now, this only supports the qemu platform.
Feature Request: https://github.com/coreos/coreos-assembler/issues/2602
=> kola/external-tests: add additionalNics support in kola.json

src/cmd-buildextend-live
Feature added by https://github.com/coreos/fedora-coreos-config/pull/1371.
=> buildextend-live: add `features.json` flag for live OS firstboot-network

mantle/kola/harness.go
We want to fix the bugs described below.
Change 1:
We had previously decided that only the non-exclusive test that failed
should be rerun with the wrapper as opposed to all of the nonexclusive 
tests being rerun. This functionality was missing so let's add it.
Note: reruns invoked via `kola rerun` already work as intended
Change 2:
Currently, a test is checked for failure after the `runTest` function
has finished running. However, it is possible that a test is marked as
failed after the execution of the `runTest` function is completed. For example,
a test takes too long to clean up resources and a timeout occurs; the test will
be marked as failed after we check whether the test should be rerun.
To fix this problem, let's only check whether a test has failed *after* we are
certain that the …
=> kola/harness.go: fix rerun bugs

mantle/cmd/kola/testiso.go
Harmless but confusing copy/paste remnant.
Fixes: d5dc0c502 ("testiso: add --add-nm-keyfile for NM keyfile propagation testing")
=> testiso: remove `[Unit]` from NM keyfile

docs/kola/external-tests.md, mantle/cmd/kola/qemuexec.go, mantle/kola/tests/misc/network.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/qemu.go
This is to follow https://github.com/coreos/coreos-assembler/pull/2606 to rename the switch `--secondary-nics` to
`--additional-nics` to be consistent, also change the related `secondayNics`
to `additionalNics`
=> kola: rename `secondary-nics` to `additional-nics`

src/cmd-buildextend-live
The ISO and PXE images share an initramfs, which ships `features.json` so `coreos-installer pxe customize` can read it.  This was thought to be sufficient for `coreos-installer iso customize` as well, and it is, but it requires `iso customize` to decompress the entire initramfs just to extract that file.
To avoid that, add a second copy directly to the ISO.  This wastes 2 KiB of space and makes `features.json` a more visible API, but we already have other semi-private APIs in the same ISO directory (`kargs.json`, `miniso.dat`).
On my system, with a release build of coreos-installer, this saves 1.25 seconds for a no-op `iso customize` run.
=> buildextend-live: add `features.json` directly to ISO

mantle/platform/platform.go
Tests for CentOS Stream 9 should behave the same way as they do on RHCOS
9 thus use the same logic for now.
=> mantle/platform: Consider 'centos-coreos' like rhcos for now

mantle/platform/api/aliyun/api.go
During recent testing of the Aliyun stage of the RHCOS pipeline, we
ran into a timeout error:
`Copying image to region "ap-northeast-1": copying image: [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Read timeout. Please set a valid ReadTimeout.`
~This introduces a flag to set the `ReadTimeout` for the Aliyun requests.~
This bumps the ReadTimeout to 30s and while we are here, bump the ReadTimeout to 15s.  (Both are a 3x increase from the API defaults.)
=> mantle/platform/aliyun: bump default request timeouts

mantle/platform/api/azure/instance.go, mantle/platform/machine/azure/cluster.go, mantle/platform/machine/azure/flight.go
Azure requires that either a username/password be set or an SSH key.
Previously we were unconditionally passing an SSH key but we have tests
(like coreos.ignition.ssh.key) that don't want an SSH key to be passed
via the API and set a NoSSHKeyInMetadata flag for that.
Let's start passing a username/password via the API so we can then bring
up instances without having to specify an SSH key. The username/password
we give won't be used because we don't install their agent.
=> mantle/platform: azure: allow for not passing SSH key through API

mantle/harness/harness.go, mantle/harness/timeout_test.go, mantle/kola/cluster/cluster.go, mantle/kola/harness.go, mantle/platform/api/gcloud/compute.go, mantle/util/retry.go
In some cases, there is significant discrepency between provisioning times
on different platforms (ie. QEMU vs AWS). This forces us to cater timeouts
to the lowest common denominator between the platforms. To circumvent this
issue we will move the timeout so that it is started *after* the provisioning
process.
More specifically, the timeout is started when instances are brought to a
"running" state (i.e ignition begins provisioning). We ensure that another
"provisioning" timeout is checking for flakes between the "provisioning" and
"running" states of an instance.
=> mantle/kola: add platform specific (provisioning) timeouts

src/cmdlib.sh
We are adding the buildindfo data to the json file to be able to identify which repos were used to build RHCOS. The repo names used in manifest would match names in[ reposistory-to-CPE.json](https://www.redhat.com/security/data/metrics/repository-to-cpe.json) published by Red Hat
Got buildinfo from `content_sets.yaml` which resides under `redhat-coreos` repo and is copied over to `src/config/`. Extracted the repo names and mapped to their corresponding pulp repository IDs to add it to our `content_manifest.json` for buildinfo. The file `content_manifest.json` will be available under `/usr/share/buildinfo/` after `cmdlib.sh` running is completed.
Issue: https://issues.redhat.com/browse/GRPA-3731
Discussion: https://github.com/coreos/coreos-assembler/issues/2540
=> Extract buildinfo from yaml file and create content_manifest.json

docs/kola/external-tests.md, mantle/cmd/kola/qemuexec.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/azure/cluster.go, mantle/platform/machine/do/cluster.go, mantle/platform/machine/esx/cluster.go, mantle/platform/machine/gcloud/cluster.go, mantle/platform/machine/openstack/cluster.go, mantle/platform/machine/packet/cluster.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/platform.go, mantle/platform/qemu.go
Add the ability to specify kernel arguments to append to the default
kernel arguments set in the image. This will be useful when testing
workflows that use kernel arguments for network configuration.
For now, this only supports the qemu platform.
Fixes https://github.com/coreos/coreos-assembler/issues/2621
=> kola/external-tests: add appendKernelArgs support in kola.json

src/cmd-buildextend-live
The coreos-installer repo includes minimized versions of the ISO image from various eras, allowing the embed commands to be tested with older metadata.  Rather than maintaining the minimization patch separately, let's just carry it here.
=> buildextend-live: add option to generate coreos-installer test fixture

mantle/cmd/kola/testiso.go, mantle/platform/metal.go
Instead of overriding `coreos-installer.service` and `coreos-installer-reboot.service`, we can now write a YAML config file into `/etc/coreos/installer.d` containing the parameters we want to pass to coreos-installer.
As a result, ISO installs now approach `coreos-installer.target` instead of `multi-user.target`, so the dependencies of some of our units need to be adjusted.
=> mantle/kola/testiso: use coreos-installer config file for ISO installs

Dockerfile
To pick up newer rpm-ostree which we want for layering work, in
particular it will ensure our OCI images pick up https://github.com/ostreedev/ostree-rs-ext/pull/196
=> Blow out quay.io cache

mantle/platform/util.go
When we run the kdump test using online platforms we get the `reboot failed: :dial tcp xx.xx.xx.xx:xx: connect: connection refused` error which is not catched in the `WaitForMachineReboot` function. Adding the above change makes sure we don't return and exit with that error while the machine reboots.
Linked issue: https://github.com/coreos/fedora-coreos-tracker/issues/860
=> mantle/platform/util.go: catch 'dial tcp' error during reboot

mantle/kola/tests/rhcos/upgrade.go, mantle/kola/tests/upgrade/basic.go, src/cmd-build, src/cmd-sign, src/cosalib/cmdlib.py, src/create_disk.sh, src/image-default.yaml
We can do this now that ostree 2022.1 is out with
https://github.com/ostreedev/ostree/pull/2500
There are two notable aspects to this:
- Previously the code here was a mix of `ostree` and `rpm-ostree`;
but it's all "pure ostree stuff", and now it is all much more
consistent.  This also helps us eventually put more functionality
in `ostree` that was formerly in `rpm-ostree`.
- We're kind of implicitly saying the container bits aren't experimental
anymore, which...they probably shouldn't be in rpm-ostree side
either.
=> Switch from `rpm-ostree ex-container` to `ostree container`

mantle/kola/tests/rhcos/upgrade.go, mantle/kola/tests/upgrade/basic.go, src/cmd-build, src/cmd-sign, src/cosalib/cmdlib.py, src/create_disk.sh, src/image-default.yaml
This reverts commit e45761755aa1cb4f35b79365adf755f669f4f48d.
A version of `ostree container` isn't available in our prod streams
yet so those builds with older rpm content will fail upgrade tests
until they get the newer ostree. We need to either wait until those
streams have the newer ostree or create a git tag we can build COSA
containers from and reference.
=> Revert "Switch from `rpm-ostree ex-container` to `ostree container`"

src/cosalib/fedora_messaging_request.py
With the changes in the latest fedora-messaging package, pylint gets
confused that `addErrback` isn't a member of the consumer returned by
`twisted_consume`.
But the API is still valid and the code still works in a local test, so
let's just silence pylint.
Closes: #2649
=> cosalib/messaging: disable pylint check on addErrback

src/cmdlib.sh
I was trying to drop an updated `skopeo` in `overrides/rpm` but
it was failing because cosa generates a lockfiles that includes it,
but in rhcos we're installing the `virt-tools` module, which filters
out everything that's not in that module.
Allow the overrides repo to override things.
=> Enable `module_hotfixes=true` for overrides/rpm

mantle/kola/tests/rpmostree/deployments.go
The error of interest here is `rebootErr`, not `err`.
=> tests/rpmostree: fix printing the wrong error var

mantle/kola/cluster/cluster.go, mantle/kola/tests/ostree/basic.go, mantle/kola/tests/ostree/unlock.go
Use the new `JournalLog` function to add a new `RunLogged` function to
`TestCluster` which has the same semantics as `Run`, i.e. starting a
subtest, but additionally logs in the machines' journals on entry and
exit of the subtest.
Use this in `ostree.basic` and `ostree.hotfix`, the latter of which has
been giving us issues. This should make it easier to read the logs.
=> kola: add subtest runner which logs entry and exit

src/cmd-sign
The F36 mass rebuild is going on right now and robosignatory is super
backed up. Let's extend the timeout in an effort to get some build
signing working.
=> cmd-sign: extend ROBOSIGNATORY_REQUEST_TIMEOUT_SEC

src/cmdlib.sh
When this file is present in the config dir, coreos-assembler will still
automatically commit the `overlay.d` subdirectories to the OSTree repo,
but will not automatically add them to the treefile.
This provides more flexibility on the config side, where e.g. overlays
may be conditionally added or may only be added on certain streams.
This has come up multiple times already in FCOS, more recently as part
of the `iptables-nft` migration work.
See also: https://github.com/coreos/fedora-coreos-config/pull/180#issuecomment-534706218
So this is sort of a halfway approach between what we have now and
teaching rpm-ostree about the overlay directories directly (via a new
e.g. `add-dirs` file, see previous discussions about this in
#639). Except that this
is much easier to do and doesn't require …
=> cmdlib: support `overlay.d/cosa-no-autolayer` option

mantle/vendor/github.com/coreos/coreos-assembler-schema/cosa/cosa_v1.go, mantle/vendor/github.com/coreos/coreos-assembler-schema/cosa/schema_doc.go, schema/cosa/cosa_v1.go, schema/cosa/schema_doc.go, schema/v1.json, src/cmd-build, src/cmd-buildextend-live, src/cmd-compress, src/cosalib/ova.py, src/cosalib/qemuvariants.py, src/v1.json
There are three cases where `cmd-compress` won't compress an artifact:
1. it's in `imgs_to_skip`,
2. it's precompressed by `qemuvariants.py`,
3. it was already compressed by an earlier `cmd-compress` run.
Case 2 currently covers `digitalocean` and `gcp`, since those platforms have opinions about which compression algorithm to use.  Case 1 covers the ostree, live artifacts, and `vmware` OVA.  Cases 2 and 3 are handled by the same test: `cmd-compress` looks for a known compression suffix.
Case 2 artifacts must not be decompressed for testing etc., since the compression is part of the definition of the artifact.  However, we don't currently write that down anywhere.  The `meta.json` `uncompressed-*` fields would have been useful for this, but #2158 added those to case 2 artifacts as well. …
=> Add `skip-compression` field to `meta.json`

gangplank/vendor/github.com/coreos/coreos-assembler-schema/cosa/cosa_v1.go, gangplank/vendor/github.com/coreos/coreos-assembler-schema/cosa/schema_doc.go
This gets the vendored schema under gangplank to match
the rest of the copies of the schema. Fixup for 015fd34
(Nutanix platform add) and 1893293 (addition of
skip-compression field).
=> schema: sync up shema updates to gangplank vendor dir

src/cmdlib.sh
Both RHCOS and FCOS have been migrated now, so we can stop supporting
this. We still need support for injecting OSTree layers since the
`content_sets.yaml` stuff uses it.
=> cmdlib: drop support for `overlay.d/cosa-no-autolayer`

mantle/kola/harness.go, mantle/platform/journal.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/aws/machine.go, mantle/platform/machine/azure/cluster.go, mantle/platform/machine/azure/machine.go, mantle/platform/machine/do/cluster.go, mantle/platform/machine/do/machine.go, mantle/platform/machine/esx/cluster.go, mantle/platform/machine/esx/machine.go, mantle/platform/machine/gcloud/cluster.go, mantle/platform/machine/gcloud/machine.go, mantle/platform/machine/openstack/cluster.go, mantle/platform/machine/openstack/machine.go, mantle/platform/machine/packet/cluster.go, mantle/platform/machine/packet/machine.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/qemuiso/machine.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/machine/unprivqemu/machine.go, mantle/platform/platform.go, mantle/util/retry.go
There are a few commits in here that should be reviewed individually. THe main commit is
```
mantle/{kola,platform}: include Ignition runtime in test timer
platform.StartMachine() blocks on SSH being available:
StartMachine()
|-> StartMachineAfterReboot()
|-> j.Start()
| -> util.Retry() <- ssh retry
So if we call it as part of our NewMachine() bringup there's
no way to start the test execution timer and have it include
the time it takes to execute Ignition (which has to complete
before SSH will become available).
Let's add a Machine Option (SkipStartMachine) that will tell the
NewMachine code to skip the call to StartMachine() and return as
soon as the platform thinks the machine is running. Then in our
test code we can start the timer and then call StartMachine()
(via the new …
```
=> mantle/{kola,platform}: include Ignition runtime in test timer

src/cmdlib.sh
This reverts commit 73a7eb6be0a0a82d2d3478746a53c03e04a9a554.
Because of the classic cosa <--> FCOS binding issue, we actually need to
wait until manifest updates propagate to all the production streams
before we remove support for the previous method.
=> Revert "cmdlib: drop support for `overlay.d/cosa-no-autolayer`"

mantle/kola/harness.go
The denylist logic incorrectly uses the base system architecture 
instead of the architecture that is passed in. Let fix this
=> kola/harness.go: fix denylist architecture detection

mantle/kola/harness.go, mantle/platform/conf/conf.go
Currently test ignition configs are merged into a single V3.4.0
(experimental) config so that they may be run non-exclusively on
one VM. This will become an obstacle when we want to stabilise
the experimental spec, potentially causing issues with CI. Lets
change the code to use the latest stable spec instead.
Original discussion here: https://github.com/coreos/coreos-assembler/pull/2588#discussion_r759541692
=> mantle/platform: use stable spec for non-exclusive test config merging

docs/cosa/run.md
There's a lot of cool things `cosa run` can do. Let's add some example
invocations to make it easier for newcomers to wield it. (Strongly
related is https://github.com/coreos/fedora-coreos-tracker/issues/235 to
extract it to a lighter more dedicated container.)
=> docs: add page dedicated to `cosa run`

mantle/cmd/ore/aliyun/copy-image.go, mantle/platform/api/aliyun/api.go
In my experience, trying to operate on an image immediately after it
had been copied to a region can be unreliable. The `CopyImage()` API
call is "fire and forget", with no native way to monitor the status of
the request. (Unlike `ImportImage()`, which returns a TaskID that
*can* be monitored).
This change introduces a new function that checks the status of an
image until it becomes available or a timeout (10min). This is made
available to the `ore aliyun copy-image` command via a new
`--wait-for-ready` flag that causes the command to wait until the
image can be operated on.
Requires: #2648
=> mantle/aliyun: allow CopyImage to wait for image readiness

docs/gangplank/usage.md
+ Clarified requirement for the architecture flag when building separate
architectures remotely
Closes #2675
=> Updated Gangplank usage

src/cmd-sign
This reverts commit abd4dc67a7ea6747e70a8f35e0ba84f8aa01c3ac.
Now that the mass rebuild is over we should be OK back with the
old robosignatory timeouts.
=> Revert "cmd-sign: extend ROBOSIGNATORY_REQUEST_TIMEOUT_SEC"

src/cmd-compress, src/cmd-decompress, src/cmd-uncompress
Add inverse operation to the compress that decompresses the images,
verifies their integrity against the metadata and updates metadata.
This function can be invoked via mode switch in compress command or
via new decompress/uncompress command, symlink to the compress
command.
Simplifying moving builds between hosts and running kola tests.
=> cmd-compress: add decompression ability

mantle/kola/tests/misc/boot-mirror.go
As of https://github.com/coreos/butane/pull/278 in Butane 0.14.0, Butane RAID templates now create reserved partitions on aarch64 and ppc64le to keep partition numbers aligned across platforms.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/855.  Reverts #2354.
=> mantle/kola/tests: re-enable RAID tests on aarch64/ppc64le

src/cmd-buildupload
Added `--endpoint-url` as an `s3` sub-command flag under the `buildupload` command.
```sh
$ cosa buildupload --artifact=ostree s3 --endpointurl=http://s3host.internal builds/
```
This allows `buildupload` to use non-AWS storage servers like Minio. Useful for local development or environments where AWS S3 doesn't fit.
Tested with local external Minio server and credentials loaded automatically by `boto3` client.
=> cmd-buildupload: Add flag for s3 server selection

gangplank/go.mod, gangplank/go.sum, gangplank/vendor/modules.txt
3 github.com/containerd/containerd vulnerabilities found in gangplank/go.sumon Nov 18, 2021
- require github.com/containerd/containerd v1.5.8
More info:
https://github.com/advisories/GHSA-c2h3-6mxw-7mvq
https://github.com/advisories/GHSA-c72p-9xmj-rx3w
https://github.com/advisories/GHSA-5j5w-g665-5m35
=> gangplank: Update containerd due vulnerabilities

docs/kola/external-tests.md, mantle/cmd/kola/kola.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/aws/flight.go, mantle/platform/machine/azure/flight.go, mantle/platform/machine/do/flight.go, mantle/platform/machine/esx/flight.go, mantle/platform/machine/gcloud/flight.go, mantle/platform/machine/openstack/flight.go, mantle/platform/machine/packet/flight.go, mantle/platform/machine/qemuiso/flight.go, mantle/platform/machine/unprivqemu/flight.go, mantle/platform/platform.go
Add support for multiple non-exclusive test buckets (or VMs). Tests can specify
whether another non-exclusive test is conflicting and kola will automatically
resolve these tests into different buckets.
We have seen in the past that the non-exclusive tests' merged config can
become too large to pass to cloud providers. To fix this issue we compressed
configs (for AWS), but this is only a temporary fix.
If a non-exclusive test bucket's config becomes too large, let's split the
bucket into two buckets to lower the config size.
=> kola: extend non-exclusive tests to multiple buckets

mantle/cmd/kola/qemuexec.go, mantle/platform/conf/conf.go
One really annoying thing when using the serial console is that you have
to manually set (and update if you resize your terminal) the terminal
size.
I found
https://wiki.archlinux.org/title/Working_with_the_serial_console#Resizing_a_terminal
which has a function to resize the terminal which seems to work well. It
doesn't fix everything (e.g. you still get commands overwriting each
other if it gets too long), but helps a lot with for example command
output.
Create a new `autoresize` Ignition fragment which shoves a Bash-adapted
version of the function in a `profile.d` dropin and gets called on every
command prompt.  Automatically inject the fragment when using serial
console devshell.
=> qemuexec: automatically resize the terminal on serial

src/cmd-buildupload
Create `boto3.client` in the main function and pass it down instead of creating a new `client` for every S3 operation.
As previously suggested in https://github.com/coreos/coreos-assembler/pull/2678#pullrequestreview-867962488.
=> cmd-buildupload: refactor s3 client

docs/kola/external-tests.md, mantle/cmd/kola/qemuexec.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/azure/cluster.go, mantle/platform/machine/do/cluster.go, mantle/platform/machine/esx/cluster.go, mantle/platform/machine/gcloud/cluster.go, mantle/platform/machine/openstack/cluster.go, mantle/platform/machine/packet/cluster.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/platform.go, mantle/platform/qemu.go
```
commit 97249401af27d1596a3189e6a1dee03d1369a32f
Date:   Tue Feb 1 20:54:33 2022 -0500
kola/external-tests: add appendFirstbootKernelArgs support in kola.json
Add the ability to specify firstboot kernel arguments to transiently
append to the default kernel arguments for the first boot of the machine.
This will be useful when testing workflows that use kernel arguments
for network configuration.
For now, this only supports the qemu platform.
commit 87eda63f8cee17626d1a1a048e8ea073cf7f2ea6
Date:   Tue Feb 1 20:34:32 2022 -0500
mantle/platform: qemuexec: rename --knetargs to --firstbootkargs
This is a little more inline with what's being done, which is to
apply the given arguments to the first boot of the …
```
=> mantle/platform: rename IgnitionNetworkKargs to AppendFirstbootKernelArgs and expose to ext tests

mantle/platform/api/aliyun/api.go
This adds tags indicating that `mantle` created the image in the
Aliyun cloud. This matches the behavior when we do `CopyImage()`
during replication operations and makes the discoverability of images
uploaded via `mantle`/`ore` easier.
=> mantle/aliyun: add tags when doing ImportImage

mantle/kola/tests/ostree/unlock.go
`all` means debug logging for the whole stack, and ostree can be really
noisy when traversing commits. This makes archived test logs fat enough
that we're approaching the PVC cap in prod.
Of course, eventually we'll remove this once we fix that flake but
short-term let's at least reduce logging to what we need.
=> tests/ostree/unlock: use G_MESSAGES_DEBUG=rpm-ostreed

mantle/cmd/kola/qemuexec.go, mantle/cmd/kola/testiso.go, mantle/cmd/ore/do/create-image.go, mantle/cmd/ore/packet/create-device.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/kola/tests/ignition/qemufailure.go, mantle/platform/cluster.go, mantle/platform/conf/conf.go, mantle/platform/conf/conf_test.go, mantle/platform/machine/aws/flight.go, mantle/platform/metal.go, mantle/platform/platform.go
Currently we're ignoring Ignition validation warnings and logging Butane validation warnings.  However, one external test in fedora-coreos-config (`ext.config.root-reprovision.swap-before-root`) intentionally uses a config which produces a warning on current Butane.
Allow the caller to select whether we log warnings, ignore them, or fail.  In commands that take a user-provided config, report warnings.  Otherwise fail unless the new `AllowConfigWarnings` flag is set (`"allowConfigWarnings": true` for external tests), in which case we ignore.  For simplicity, forbid ignoring warnings in non-exclusive tests.
=> platform/conf: allow selecting render behavior on config warnings

mantle/kola/tests/misc/multipath.go
Verify that `multipath.conf` is populated in both the day-1 and day-2
workflows.
Verifies https://github.com/coreos/fedora-coreos-config/pull/1476.
=> tests/multipath: check for /etc/multipath.conf

src/cmd-push-container, src/coreos-assembler
This is just very small syntatic sugar for directly pushing
the container image we have.  We don't need any of the
layers of complexity going on in the previous RHCOS-specific
old format oscontainer.
=> `cosa push-container`: New command

.github/workflows/bump-nocache-line.yml
- switch to git-core to prevent installing a bunch of deps
- install git first
- otherwise GH actions won't actually download full git repo
but an archive with the following log message:
- "The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher
to the PATH"
- configure the git username and email
- Add comment to "fetch-depth: 0"
=> workflows: more fixes for bump-nocache-line workflow

mantle/platform/conf/conf.go
Now that external tests have been updated, we can treat warnings as hard errors by default.
Finishes implementation of #2686.
=> Revert "platform/conf: temporarily disable failing on config warnings"

Dockerfile, build.sh
build: Pull rpm-ostree from updates-testing
To get the new authselect fixes, among other things.  I think
we want to do this in general going forward.  In the future really
we should track rpm-ostree git main (at least, make it easy to do so).
---
Dockerfile: Blow out quay.io cache
To get the new rpm-ostree.
---
=> Bump rpm ostree

src/cmdlib.sh
The RHCOS 4.9 Power pipeline is hitting the second variant in
https://github.com/openshift/os/issues/594#issuecomment-1033000457.
This is worked around in more recent pipelines by the move to OCI
containers, but 4.9 doesn't have this code and it seems risky to
backport. So let's just bump the memory there for that release.
=> [rhcos-4.9] cmdlib.sh: bump supermin VM to 8G of RAM on ppc64le

mantle/cmd/ore/aliyun/copy-image.go, mantle/platform/api/aliyun/api.go, src/cosalib/aliyun.py
```
cosalib/aliyun: extend commands to mark images public
This extends the `aliyun-replicate` and `buildextend-aliyun`
commands to support a `--public` option, which will mark any
uploaded images as publicly available.
Requires #2670
(cherry picked from commit a6e8c0fd097473ed601c3229aa50cc692ffa8611)
```
```
mantle/aliyun: allow CopyImage to wait for image readiness
In my experience, trying to operate on an image immediately after it
had been copied to a region can be unreliable. The `CopyImage()` API
call is "fire and forget", with no native way to monitor the status of
the request. (Unlike `ImportImage()`, which returns a TaskID that
*can* be monitored).
This change introduces a new function that checks the status of an
image until it becomes available or a timeout (10min). This is …
```
=> [rhcos-4.10] backports of Aliyun ehancements to ore

Dockerfile
Triggered by bump-nocache-line [GitHub workflow](https://github.com/coreos/coreos-assembler/actions/workflows/bump-nocache-line.yml) ([source](https://github.com/coreos/coreos-assembler/blob/main/.github/workflows/bump-nocache-line.yml)).
=> Dockerfile: bump nocache line 🪴

src/cmdlib.sh
Make a helper for committing OSTree layers which contains all the
canonicalization flags. Notably `--timestamp` which ensures that we get
a consistent checksum for the same source git commit.
Fixes: https://github.com/openshift/os/issues/712
Fixes: https://github.com/coreos/coreos-assembler/pull/2603
=> cmdlib: consistently commit layers with same options

build.sh
There seems to be a regression in the 5.16 kernel causing intermittent
compose failures. For the full details, see:
https://github.com/coreos/coreos-assembler/issues/2707
We still need to actually investigate what exactly regressed here. But
at least for now let's unblock CI.
=> build.sh: freeze on kernel-5.15.18-200.fc35.x86_64

mantle/kola/harness.go
Recently we have seen non-exclusive tests panicking due to
runtime.Goexit executing, but somehow harness.finished being false.
This problem was occurring because we pass tcluster to collectLogsExternalTest
instead of newTC. tcluster has a reference to the harness of the wrapper test,
thus harness.finished is incorrectly set to true for the wrapper test's harness
instead of the non-exclusive subtest's harness.
closes: https://github.com/coreos/coreos-assembler/issues/2701
=> kola/harness.go: fix kola panics

src/cmd-buildextend-live
coreos-installer now knows how to locate `ignition.img` and `kargs.json` directly in the ISO 9660 filesystem, so we don't need the custom `coreiso+` and `coreKarg` headers anymore.
Requires https://github.com/coreos/coreos-installer/pull/622 to land in a coreos-installer release and ship in Fedora CoreOS for a reasonable period of time.
=> buildextend-live: drop legacy embed headers

mantle/platform/qemu.go, src/libguestfs-ppc64le-wrapper.sh
Add a workaround for the issue:
https://github.com/openshift/os/issues/720
The kola tests failing are using guestfish, for some
reason the libguestfs is not able to create the wrapped to
add the vmst value, required for the POWER8 cluster.
Until we can debug it better, let's unlock the power builds
=> Add libguestfs workaround for ppc64le

src/cmd-buildextend-live, src/osmet-pack
We need to wait until coreos-installer 0.13.1 is in FCOS stable.
This reverts #2631.
=> Revert "Update for renamed osmet/miniso pack subcommands"

src/cosalib/ibmcloud.py
Now if someone runs `cosa buildextend-ibmcloud --arch=s390x` it
will get honored.
This is really only useful if there was a s390x qcow2 natively that
someone downloaded and then wanted to make an ibmcloud artifact out
of (IBM Cloud now has s390x instances).
This bit was missed in 539a63b.
=> cosalib: make ibmcloud.py pick up on provided --arch

src/libguestfish.sh
- It is a follow up for the issue https://github.com/openshift/os/issues/720  and for #2714
- POWER never really used the newGuestfish function in
mantle/platform/qemu.go, with the new tests now using setupPreboot function
that was recently added, the issue happened because there is no call for the
POWER wrapper in the newGuestfish. Nonetheless, it is not a libguestfish issue
since POWER8 (cluster) needs the vsmt set to 8.
=> Clean up POWER wrapper in libguestfish

src/cmdlib.sh
This reverts commit fc8c5f07e80ff623753ed7456d816d69607cde59.
The `stable` stream now has the manifest changes needed now, so we can
drop support for this again.
=> Revert "Revert "cmdlib: drop support for `overlay.d/cosa-no-autolayer`""

docs/working.md
`-i` silently drops fields it doesn't know about, including fields added to the experimental spec by the change being tested.
=> docs/working: mention `--ignition-direct` for working on the Ignition spec

src/cmd-upload-oscontainer, src/oscontainer.py
There was a big quay.io update recently, and the new version supports
OCI natively.  Which is awesome and will unblock other things
such as OCI artifacts.
However...it turns out some of the OCP tooling around disconnected
installs only works with Docker schema v2s2, not OCI.
Let's use v2s2 by default for *this* code which is currently
OCP/RHCOS specific.
But let's continue to use OCI by default for the new
"ostree native container" format push code which lives in
`cosa push-container`.
=> oscontainer: Push in v2s2 format by default

src/cmd-upload-oscontainer, src/oscontainer.py
There was a big quay.io update recently, and the new version supports
OCI natively.  Which is awesome and will unblock other things
such as OCI artifacts.
However...it turns out some of the OCP tooling around disconnected
installs only works with Docker schema v2s2, not OCI.
Let's use v2s2 by default for *this* code which is currently
OCP/RHCOS specific.
But let's continue to use OCI by default for the new
"ostree native container" format push code which lives in
`cosa push-container`.
(cherry picked from commit 2c8eda187408f4818d2858846ac1a6888e9e322d)
=> [rhcos-4.10] oscontainer: Push in v2s2 format by default

src/cmd-upload-oscontainer, src/oscontainer.py
There was a big quay.io update recently, and the new version supports
OCI natively.  Which is awesome and will unblock other things
such as OCI artifacts.
However...it turns out some of the OCP tooling around disconnected
installs only works with Docker schema v2s2, not OCI.
Let's use v2s2 by default for *this* code which is currently
OCP/RHCOS specific.
But let's continue to use OCI by default for the new
"ostree native container" format push code which lives in
`cosa push-container`.
(cherry picked from commit 2c8eda187408f4818d2858846ac1a6888e9e322d)
(cherry picked from commit c9e5375ef98c6872fb1cec02685b17307da87084)
=> [rhcos-4.7] oscontainer: Push in v2s2 format by default

src/cmd-clean
xref https://github.com/coreos/rpm-ostree/issues/3473
Today how rpm-ostree caches packages has problems, we need to make
it a bit more obvious how to also blow away all of our cached data.
=> clean: Add --all option to also remove `cache/`

src/cmd-upload-oscontainer, src/oscontainer.py
There was a big quay.io update recently, and the new version supports
OCI natively.  Which is awesome and will unblock other things
such as OCI artifacts.
However...it turns out some of the OCP tooling around disconnected
installs only works with Docker schema v2s2, not OCI.
Let's use v2s2 by default for *this* code which is currently
OCP/RHCOS specific.
But let's continue to use OCI by default for the new
"ostree native container" format push code which lives in
`cosa push-container`.
=> [rhcos-4.6] oscontainer: Push in v2s2 format by default

src/cmd-push-container
Modifies `cosa push-container` to tag the container with the current build ID and architecture if a tag is not provided.
=> push-container: tag with build id and arch by default

.cci.jenkinsfile
We can't use `sudo` here because we're running as a fully unprivileged
user. I'm not sure how this worked before.
=> ci: don't use sudo to run test_pruning.sh

src/cmd-buildupload
Right now, when we use `--artifact` to only upload some artifacts, we
still reference them in the `meta.json`. This is bad though, because
consumers will assume that they're present.
Just scrub them out of the custom `meta.json` we upload if they're not
present in the bucket.
=> buildupload: scrub skipped missing images from meta.json 

mantle/kola/harness.go
In https://github.com/coreos/fedora-coreos-config/pull/1538 we changed
manifest.yaml to specify the stream in a toplevel variable and we moved
the `add-commit-metadata: fedora-coreos.stream` information into a
shared manifest. This broke the denylist parsing of the `stream`.
Let's update to handle the changes.
=> mantle/kola: update manifest.yaml parsing to account for recent change

src/cmd-buildupload
In the FCOS pipeline, we sometimes run `buildupload` because e.g.
`meta.json` for a specific architecture changed. However, right now this
also implies re-uploading the `meta.json` for every architecture, which
is unnecessary and possibly opens the door to races.
Add an `--arch` flag to fix this.
=> buildupload: add support for --arch option

src/cmd-buildextend-live, src/osmet-pack
coreos-installer 0.13.1 has now landed in FCOS stable.
This reverts #2717.
=> Revert "Revert "Update for renamed osmet/miniso pack subcommands""

mantle/kola/tests/misc/multipath.go
Otherwise, `/var/lib/containers` may not exist yet and the mount will
fail. It's usually created via tmpfiles, but we run earlier than that.
Fixes part of: https://github.com/openshift/os/issues/743
(cherry picked from commit d04cc2f2c3ffcf78b63f77af5253add76dfc8da1)
=> [rhcos-4.10] tests/multipath.partition: create /var/lib/containers before mount

mantle/kola/tests/misc/multipath.go
Otherwise, `/var/lib/containers` may not exist yet and the mount will
fail. It's usually created via tmpfiles, but we run earlier than that.
Fixes part of: https://github.com/openshift/os/issues/743
(cherry picked from commit d04cc2f2c3ffcf78b63f77af5253add76dfc8da1)
=> [rhcos-4.9] tests/multipath.partition: create /var/lib/containers before mount

mantle/network/ssh.go
The `Agent` interface doesn't support `SignWithFlags`. So when trying to
use `ssh` with the mantle agent to SSH into a VM, the signing request
during handshake has its flags stripped:
https://cs.opensource.google/go/x/crypto/+/3147a52a:ssh/agent/server.go;l=133-137
This causes the wrong algorithm to be used, which leads to:
agent key RSA SHA256:<hash> returned incorrect signature type
The reason kola itself doesn't hit this is because it doesn't go through
the socket.
The underlying `keyring` object does implement `ExtendedAgent` though,
which does support `SignWithFlags`, so just cast it.
Fixes: dcd432d2a ("mantle: switch back to RSA SSH keys")
=> mantle/network/ssh: use ExtendedAgent for SSHAgent

src/cosalib/ova.py, src/image-default.yaml, src/vmware-template.xml
FCOS and RHCOS want to set different VMware hardware versions and OS type IDs.  Read both from `image.yaml`, defaulting to the values we currently use.
OVF images created by VMware Workstation 16.2.3 respectively record Fedora and RHEL 8 guests as:
```
<OperatingSystemSection ovf:id="100" vmw:osType="fedora64Guest">
<OperatingSystemSection ovf:id="80" ovf:version="8" vmw:osType="rhel8_64Guest">
```
The `ovf:id` values are defined to come from `CIM_OperatingSystem.OsType`, which defines 80 as `RedHat Enterprise Linux 64-Bit` and 100 as `Linux 2.6.x 64-Bit`.  (2.6.x seems to be the last explicit kernel version listed in the spec.)  `ovf:version` appears to be the major version of the OS.  VMware's `ovftool` doesn't seem to care about either of those fields, only the `vmw:osType`, so we …
=> cosalib/ova: template VMware HW and OS versions from `image.yaml`; enable UEFI

.cci.jenkinsfile
Something changed recently (maybe just the codebase getting larger)
where the golang compiler is hitting up more easily against its
allocated limit of CPU threads.
Let's explicitly request some amount of CPU for the image build and and
also set `GOMAXPROCS` to respect it.
=> ci: set cpu requests and `GOMAXPROCS` when building image

src/vmware-template.xml
The `iopl(2)` issue is worked around upstream in https://github.com/coreos/ignition/pull/1332, and until that lands in a release, both FCOS and RHCOS are shipping downstream patches.
=> cosalib/ova: enable Secure Boot in VMware OVA

src/cmd-buildextend-metal, src/create_disk.sh
This should fix https://github.com/openshift/os/issues/594
Basically I think 9p has a bug where under memory pressure, having
it *free* an inode requires allocation, which can fail.
This works around that bug by pulling the ostree-container archive
instead, which is a single big file.
Note that this code path does *not* change the semantics at all
for the generated disk.  The information about the pulled container
is discarded and lost.  Actually making use of the container bits
natively is the `deploy-via-container` image option which is
still experimental, but will be used when we progress the
ostree native containers work.
=> create_disk: Pull ostree-container over 9p, instead of pull-local

mantle/cmd/kola/devshell.go
By default, SSH will try the public keys from the SSH agent if one is
running. Surprisingly, SSH will try all the keys in the agent *before*
trying the key we explicitly passed in via `-i`.
In my case, I have quite a few keys in my agent. Because the SSH server
in the guest will close the connection if too many unauthorized keys are
tried, the client never even gets to the actual private key we passed
in, and SSH just fails.
This doesn't happen if using cosa as a container since no SSH agent
exists inside. I started hitting this after moving my pet container
environment to toolbox, where the `SSH_AUTH_SOCK` env var is forwarded
and the GNOME Keyring dir is bind-mounted in.
Instead of creating a custom SSH key to pass it to SSH, use the built-in
support for spawning an agent with an …
=> kola/devshell: use built-in SSH agent

docs/kola.md, mantle/kola/harness.go
Whether or not tests compiled in kola can be marked as nonexclusive
has been ambiguous thus far. Since tests compiled in kola should be
complex and thus exclusive, let's disallow this scenario and make
it explicit.
=> docs/kola, kola/harness: non external tests must be exclusive

src/cmd-build, src/cmdlib.sh
build: Drop hardcoded `--cmd /usr/bin/bash`
Depends https://github.com/coreos/fedora-coreos-config/pull/1484
Also while we have the patient open, use the new preferred verb
`encapsulate` instead of `export`.
---
build: Add more metadata into exported container
Today we gather the input config git repository and commit hash
and inject them into our homegrown object-storage+JSON schema.
But OCI containers have standard annotations for this, so inject
that.
Also, include the image checksum bits; this will hopefully get
us to the point where we can `cosa buildprep docker://quay.io/...`
xref
https://github.com/coreos/coreos-assembler/issues/2685
---
=> build: Drop hardcoded `--cmd`, add more metadata into exported container

src/cmdlib.sh, src/supermin-init-prelude.sh
This is the case in the RHCOS pipeline today, and we can support
it in the same way we support `src/config` being a symlink to
outside the workdir.
Note: This only works for absolute symlinks today.
Side note: At some point we should use virtiofs which AIUI will
just fix this by supporting symlinks natively.
Closes: https://github.com/openshift/os/issues/754
=> build: Support `builds/` in workdir being a symlink outside workdir

mantle/kola/tests/misc/boot-mirror.go, mantle/kola/tests/misc/multipath.go
```
commit 8282d2be344aa122fc9555c51e2ab261572088ea
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Thu Dec 2 12:03:31 2021 -0500
kola/boot-mirror: simplify check for RAID1 mountpoint
To check if a mountpoint is on RAID1, instead of going from the top and
querying all devices on the system, we can directly check the type of
the device backing the mountpoint.
```
```
commit a9fd9e4253d328bcead42c48437f5dd30c8d681c
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Thu Dec 2 12:04:08 2021 -0500
kola/boot-mirror: check bootfs dropins from `rdcore bind-boot`
This is similar to the tests added in `ext.config.reboot` as part of
https://github.com/coreos/fedora-coreos-config/pull/1316, but for the
boot mirroring tests.
Specifically, it adds coverage for ESP devices discovery in a RAID1 …
```
=> Add RAID1 and multipath coverage for bootfs dropins from `rdcore bind-boot`

build.sh, src/cmd-oc-adm-release
The immediate motivation is https://github.com/openshift/release/blob/master/ci-operator/config/openshift/os/openshift-os-master.yaml#L77
For RHEL CoreOS related stuff in particular it's just really useful to have
the `oc` binary in coreos-assembler to streamline things like
"build a new release image that overrides the OS" etc.
I suspect this would help OKD too.
---
=> Install `oc`

src/cmd-build, src/cmd-sign, src/cosalib/cmdlib.py, tests/test_cosalib_cmdlib.py
The container bits should have propagated everywhere we care about now.
=> Drop support for writing ostree as `tar`

src/create_disk.sh, src/image-default.yaml
Add the infrastructure for the config git repository to extend
the options passed to `mkfs.$fs`.
My intention is to add `-m bigtime=1` for xfs.
=> build: Add support for `rootfs-args`

mantle/cmd/kola/kola.go, mantle/harness/harness.go, mantle/harness/reporters/json.go, mantle/harness/reporters/reporter.go, mantle/kola/harness.go, mantle/kola/register/register.go
Add the failed subtests of non-exclusive wrapper to report.json. The subtests
allow us to use them for re-run purposes via --rerun arg and kola rerun command
Fixes: coreos#2638
=> kola: Add failed subtests to report.json

src/cmd-build, src/cmd-buildextend-metal, src/cmdlib.sh, src/image-default.yaml
Move `image-default.yaml` merge into main build
A while ago we added an `image-default.yaml`, but were only using
it in the disk image builds.  Move it into the main build setup,
so we can consistently refer to values that may have defaults there
too.
Prep for extending `ostree-format`.
---
build: Add support for `ostree-format: oci-chunked`
This *opts in* to using https://github.com/coreos/rpm-ostree/pull/3478
so we can safely ratchet in the change, and more easily test in
in non-production CI configurations but still using coreos-assembler.
---
=> build: Add support for `ostree-format: oci-chunked`

gangplank/internal/ocp/bc_test.go, gangplank/internal/ocp/filer_test.go, gangplank/internal/ocp/remotes_test.go, gangplank/internal/ocp/return_test.go, gangplank/internal/spec/jobspec_test.go, gangplank/internal/spec/stage_test.go, mantle/harness/harness_test.go, mantle/system/copy_test.go, schema/cosa/builds_test.go, schema/cosa/schema_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `T.TempDir` to create temporary test directory

src/cmd-build
As the comment says, this is something that `rpm-ostree container-encapsulate`
does by default.
But we aren't shipping that yet.  This will help me bridge the
two worlds by ensuring they contain identical metadata.
=> build: Copy `rpmostree.inputhash` key for current container flow

src/create_disk.sh
This requires https://github.com/ostreedev/ostree-rs-ext/pull/275
When `deploy-via-container: true` is used in combination with
the new `rpm-ostree container-encapsulate` from
https://github.com/coreos/rpm-ostree/pull/3478
We need to use the ostree-container synthetic merge commit to find
the deployment.
(Actually, what we want is something more like `ostree admin status --json`,
or I guess for now `rpm-ostree status --json` to work offline; but
for now this is good too)
=> create-disk: Handle layered container image deploys

mantle/kola/harness.go
Previous change was updating the nonExclusiveTestsStarted bool for the child test's
harness whereas it should update the wrapper itself. This change would update
the bool for wrapper instead of individual child test's harness
Should fix the wrongful re-running of unneeded child tests such as in [#424](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/424/) build
=> harness.go: Update the testStarted bool for parent wrapper

mantle/kola/harness.go
The only Fedora kernels built with lockdep enabled are non-rc Rawhide kernels, and we don't intend to actively pursue any warnings that occur in those.  Drop the check for lockdep warnings so they don't cause CI failures.
In addition, the kernel 4.14.11 bug is long gone, and we no longer ship a unit described as `CoreOS Static Network Agent`.  Drop those checks.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1152.
=> kola/harness: drop obsolete log checks and the check for lockdep warnings

src/cmd-buildextend-virtualbox, src/cmd-generate-release-meta, src/coreos-assembler, src/cosalib/ova.py, src/v1.json, src/virtualbox-template.xml
xref https://github.com/coreos/ignition/pull/1269
=> Add VirtualBox OVA image

src/cmd-build, src/cmd-buildextend-live, src/cmd-buildextend-metal, src/cmdlib.sh, src/cosalib/cmdlib.py, src/cosalib/ova.py, src/image-default.yaml
build: Ensure JSON is sorted for reproducibility
Prep for sticking the rendered `image.json` into the ostree commit;
we want reproducibility here to avoid spurious rebuilds.
---
buildextend-metal: Parse image JSON, not YAML
We're centralizing the input to disk image generation as JSON.
Also, this way we'll correctly honor the defaults.
---
build: Move `extra-kargs` default into `image-default.yaml`
The `image-default.yaml` file should act as the canonical
reference for possible keys, along with their default values.
---
build: Checksum image JSON, not YAML
Part of canonically processing the merged JSON so we correctly
honor defaults.
---
build: Clean up image JSON generation, use it consistently
A few more places were parsing the image YAML, change things
so that we generate the …
=> Prep patches for storing `image.json` in the ostree

mantle/kola/tests/rpmostree/deployments.go
The manual `ostree commit` is dropping all metadata from the
previous commit, including key bits like `coreos-assembler.basearch`
which zincati needs.  We could fix that, but in this flow zincati
won't be useful anyways, so just disable it.
=> tests/rpm-ostree: Mask zincati when we're doing a synthetic commit

src/grub.cfg
To allow users to make changes to the GRUB configuration
we will source a user created user.cfg in the statically defined
grub.cfg.
=> src/grub.cfg: Source user.cfg in grub.cfg

src/cmdlib.sh
I was trying to do stuff related to C9S and this code was just
in my way.  Detecting specific distributions this way is really
an anti-pattern and we should stop it.  Most of this should
be replaced with feature detection, but in *this* case the
code is just a dead relic of a previous attempt to do a RHEL8-based
coreos-assembler.
(I personally do think a C9S-based coreos-assembler could make
sense, but that's a future topic)
=> cmdlib: Drop dead "is fedora" or "is RHEL" detection code

mantle/cmd/kola/testiso.go
=> kola/testiso: make output more like `kola run`, print test duration

src/cmd-push-container
For similar reasons as https://github.com/coreos/coreos-assembler/pull/2726
we need to support pushing our containers in v2s2 format, not oci.
(Unlike that patch, we don't flip the default though here)
=> push-container: Support `--format`

mantle/cmd/kola/options.go, mantle/cmd/kola/qemuexec.go, mantle/util/distros.go
kola: Add SCOS distribution as alias for RHCOS
Add a new distribution option but keep as an alias for RHCOS for now.
---
kola: Setup 9p mounts only for non-SCOS & non-RHCOS
Keep this as a long denylist of conditions to try to use 9p by default
and only not use it in cases where we know it won't work.
=> kola: Add SCOS distribution as alias for RHCOS

mantle/kola/harness.go
Verify that oom-killer does not show up in the console.
https://bugzilla.redhat.com/show_bug.cgi?id=1931467
=> kola/harness: check console for oom-killer

mantle/kola/tests/rhcos/upgrade.go
When running the `rhcos.upgrade.from-ocp-rhcos` test in an
unprivileged pod in the Prow clusters, the test fails during the
unpacking of the `oc` binary because it is trying to use `sudo` to
write to `/usr/bin`.
To work around this, remove the use of `sudo` and split the `curl` and
`tar` commands into separate calls. (Using `bash -c` wasn't working
for me locally or in cluster)
=> tests/rhcos/upgrade: drop use of sudo for unpriv pods

pytest.ini, src/cmd-buildextend-live, src/cmd-buildextend-metal, src/cmdlib.sh, src/cosalib/cmdlib.py, src/cosalib/ova.py, src/cosalib/qemuvariants.py, src/create_disk.sh, src/image-default.yaml
Depends https://github.com/coreos/coreos-assembler/pull/2806
---
Serialize `grub-script` literally into image.json
Prep for injecting `image.json` into the ostree commit.  To make
that meaningful, it has to be entirely independent of coreos-assembler.
This bit is crucial for being able to do image builds in a manner
independent of coreos-assembler's content, using solely the ostree
commit as input.
---
Insert generated image.json into the ostree commit
This is part of https://github.com/coreos/fedora-coreos-tracker/issues/1151
Our generated disk images are largely just a "shell" around the egg
of an ostree commit.  There is almost nothing that lives
in the disk image that isn't in the commit.
(This is especially true now that a preparatory commit previous to
this moved the *content* of …
=> Insert generated image.json into the ostree commit

src/cmdlib.sh
When building RHCOS and generating the `content_manifest.json` file,
the permissions on the file and containing directory included the
`g+w` bit, which causes the directory/file to be flagged by the
`ext.config.shared.files.file-directory-permissions` test. Add a step
in the creation of the ostree layer to set the permissions on the
directory + file before the ostree layer is committed.
Hat tip to @jlebon for the help!
=> cmdlib: set permissions on /usr/share/buildinfo

src/cmd-push-container
In the RHCOS pipeline, we want to be able to push the legacy
oscontainer and the new base-image container using the same image
reference (i.e. `quay.io/openshift-release-dev/ocp-v4.0-art-dev:411.86.202205021327-0-x86_64`).
When the base-image container is pushed to the same `image:tag`
reference, it overwrites the existing digest (as expected). But this
ends up breaking some of the ART automation around the
`machine-os-content` promotion, because the `sha256` digest in
`meta['oscontainer']['digest']` is still pointing to the digest from
the oscontainer push.
To workaround this for now, let's just provide a flag to append the
`-base-image` string to the image name of the base-image container that
is getting pushed.
i.e. `quay.io/openshift-release-dev/ocp-v4.0-art-dev:411.86.202205021327-0-x …
=> push-container: add option to extend image name

src/cmd-buildextend-live, src/cmd-buildextend-metal, src/cmdlib.sh, src/cosalib/cmdlib.py, src/cosalib/ova.py, src/cosalib/qemuvariants.py
This reverts commit e0c32968778f93aacc834da9b34ece439d5c196c.
This broke the `next` stream release at the `cosa aws-replicate` step:
https://github.com/coreos/fedora-coreos-streams/issues/496#issuecomment-1116285820
=> Revert "Insert generated image.json into the ostree commit"

mantle/kola/tests/ignition/resource.go
=> [rhcos-4.10] mantle/kola/tests: move S3 test fixtures to a new bucket

mantle/kola/tests/ignition/resource.go
=> [rhcos-4.9] mantle/kola/tests: move S3 test fixtures to a new bucket

mantle/kola/tests/ignition/resource.go
=> [rhcos-4.8] mantle/kola/tests: move S3 test fixtures to a new bucket

mantle/kola/tests/ignition/resource.go
=> [rhcos-4.7] mantle/kola/tests: move S3 test fixtures to a new bucket

mantle/kola/tests/ignition/resource.go
=> [rhcos-4.6] mantle/kola/tests: move S3 test fixtures to a new bucket

mantle/README.md, mantle/auth/google.go, mantle/cmd/kola/options.go, mantle/cmd/ore/gcloud/gcloud.go, mantle/platform/api/gcloud/api.go
The OAuth client ID corresponds to an app registration that's been dead for a while now.  We can't usefully create a new registration because the out-of-band credential flow has been [disabled for new apps](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob).
The recommended alternative is to have OAuth redirect to a web server listening on localhost, but we usually run in a container, so that would be awkward.  In practice, we just use `--gce-json-key` these days, so it's not worth trying to fix this functionality.  Default to reading a key from `~/.config/gce.json` instead.
Also change the default GCP project from the defunct `coreos-gce-testing` to `fedora-coreos-devel`.
=> mantle/platform/api/gcloud: drop interactive OAuth flow

build.sh
This reverts commit d226eb2b07a3c522ab0f2225ab987000873f1bb7.
We've frozen on this long enough; f36 is about to be released. Let's
unpin and find out if the original issue causing this is still present.
=> Revert "build.sh: freeze on kernel-5.15.18-200.fc35.x86_64"

mantle/kola/harness.go
If only one of two conflicting tests is ran an error will occur.
Let convert this error to a debugging message.
=> kola/harness.go: fix kola conflicts bug

src/cosalib/qemuvariants.py
Add a `-c` convert option for Nutanix image which will help reduce
size of the image for Nutanix.
This PR also sets `skip_compression` value to True for Nutanix variant
in order to ensure `cosa compress` doesn't gzip the image.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1191
=> lib: Add internal qcow2 compression for Nutanix image

mantle/cmd/kola/kola.go, mantle/kola/harness.go
Add support for accepting re-run passes as success.We consistenly have some provider flakes; specifically in Openstack and using the above flag would solve that problem by returning as a success when the tests pass during the reruns.
The flag will be in the command as `cosa kola run --rerun --allow-rerun-success`
Issue: https://github.com/coreos/coreos-assembler/issues/2853
=> kola: Add allowrerunsuccess option to kola run

Dockerfile, src/cosalib/aws.py
It's GA and Fedora CoreOS has already moved.
=> Move to Fedora 36!

.github/workflows/bump-nocache-line.yml
When running Git in a containerized job, we need to tell it that repos not owned by the current user are safe.
[Sample failing run](https://github.com/coreos/coreos-assembler/actions/runs/2312652823).
=> workflows: fix bump-nocache-line with current Git

mantle/cmd/kola/options.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/platform/api/aws/ec2.go, mantle/platform/api/gcloud/api.go, mantle/platform/api/gcloud/compute.go, mantle/platform/api/gcloud/pending.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/gcloud/cluster.go, mantle/platform/platform.go
In order to test authenticated GCS fetches from instances, we need to attach some service account with GCS read access to each instance.  Use the project's default service account unless the command line specifies otherwise.
Also allow tests to disable service account attachment in GCE and instance profile attachment in EC2, so that we can verify that anonymous fetches S3 -> EC2 and GCS -> GCE work without credentials.  (This has been a [problem in the past](https://github.com/coreos/ignition/pull/1363).)
This change requires kola's GCP service account to have Service Account User permission for the instance service account.  Otherwise, the GCP SDK will fail with a helpful error message.
=> mantle/kola: optionally attach GCP service account/AWS instance profile to instances

build.sh
The existence of /etc/security/limits.d/95-kvm-memlock.conf
causes sudo not to work on ppc64le which means we will never
execute our "privileged" path.
Let's delete the file so sudo can work on ppc64le while we discuss
in the bug our options.
https://bugzilla.redhat.com/show_bug.cgi?id=2082149
=> build.sh: fix sudo on ppc64le

docs/working.md
This wants explicit documentation in general, and has changed
a bit now that the ostree container exists.
=> docs: Describe testing an in-place OS update

build.sh
Clean up Go cache to keep the COSA image as small as possible.
Fixes: https://github.com/coreos/coreos-assembler/issues/2872
From top to bottom: build with this, build without, image from quay:
```
localhost/coreos-assembler                 latest      3ca60570e4ac  46 minutes ago  4.38 GB
<none>                                     <none>      c6ebb222c0ba  2 hours ago     6.84 GB
quay.io/coreos-assembler/coreos-assembler  latest      2e56de22ca96  5 days ago      5.76 GB
```
=> build.sh: Remove Go cache after build

mantle/kola/tests/misc/multipath.go
This fixes the same race condition in a previous PR #2457 [0]. The
difference is that in PR #2758 [1], `mpath-var-lib-containers.service`
uses mkdir to create `/var/lib/containers` and in some cases it will race
against `ostree-remount.service` during the short window `/var` is
read-only. Have `mpath-var-lib-containers.service` run after
`ostree-remount.service` to resolve this.
[0] https://github.com/coreos/coreos-assembler/pull/2457
[1] https://github.com/coreos/coreos-assembler/pull/2758
=> tests: fix /var race in multipath.partition part 2

ci/prow-rhcos.sh, mantle/kola/tests/misc/multipath.go
This fixes the same race condition in a previous PR #2457 [0]. The
difference is that in PR #2758 [1], `mpath-var-lib-containers.service`
uses mkdir to create `/var/lib/containers` and in some cases it will race
against `ostree-remount.service` during the short window `/var` is
read-only. Have `mpath-var-lib-containers.service` run after
`ostree-remount.service` to resolve this.
[0] https://github.com/coreos/coreos-assembler/pull/2457
[1] https://github.com/coreos/coreos-assembler/pull/2758
(cherry picked from commit 46e7d0c)
=> [rhcos-4.9] tests: fix /var race in multipath.partition part 2

mantle/kola/tests/misc/multipath.go
This fixes the same race condition in a previous PR #2457 [0]. The
difference is that in PR #2758 [1], `mpath-var-lib-containers.service`
uses mkdir to create `/var/lib/containers` and in some cases it will race
against `ostree-remount.service` during the short window `/var` is
read-only. Have `mpath-var-lib-containers.service` run after
`ostree-remount.service` to resolve this.
[0] https://github.com/coreos/coreos-assembler/pull/2457
[1] https://github.com/coreos/coreos-assembler/pull/2758
(cherry picked from commit 46e7d0c)
=> [rhcos-4.10] tests: fix /var race in multipath.partition part 2

src/create_disk.sh
While reviewing some related code, I realized that `$ignition_firstboot`
was literally being embedded into the kernel command-line on s390x. We
don't use GRUB there, so it will never get evaluated. Having it there
doesn't break anything but it's useless and can cause confusion, so
remove it.
We already handle the `ignition.firstboot` karg in all the places we
need to for s390x.
=> create_disk: fix literal `$ignition_firstboot` karg on s390x

mantle/platform/api/aws/api.go, mantle/platform/api/aws/network.go
When we go in and create the VPC and various other networking resources
let's make them IPv6 capable.
Also, let's add Name tags to resources we create.
=> mantle/platform/aws: add IPv6 support

continuous/Dockerfile, continuous/fcos-continuous.repo
Right now, I want to test the new ostree code to inject signatures:
https://github.com/ostreedev/ostree-rs-ext/pull/301
And I want to do it *before* releasing a new rpm-ostree.
Add a new Dockerfile with pulls from our continuous COPR.
This is effectively the coreos-assembler dual of
https://github.com/coreos/fedora-coreos-config/pull/1710
=> ci: Add Dockerfile.continuous

mantle/kola/tests/podman/podman.go
Now if we will have more than or equal to 98/100 passes the test `podman.network-single` will be considered as a PASS. It should fix the frequent test failure on kola-azure CI.
Pipeline failure: [kola-azure-#97](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/kola-azure/detail/kola-azure/97/pipeline/)
=> kola/podman.go: Decrease the threshold of podman run passes for podman.network-single test

src/cmdlib.sh
In https://github.com/openshift/release/pull/29031 we are
debugging very slow build times.  Of the approximately 3h build
time, 30 minutes is compressing all the files into the archive repo
in `tmp/repo`.
This is all essentially wasted time, because we now canonically represent
the ostree commit as an ociarchive, which is re-compressed again
differently.
Eventually, we should drop `tmp/repo` and have `cache/repo-build`
be the canonical uncompressed cache.
In the short term though, ostree makes it easy to turn down the
zlib compression level, which can have a dramatic impact here.
Locally on my desktop:
Before:
```
$ time sudo ostree --repo=tmp/repo pull-local cache/repo-build/ 988a1ffb47df4dda08df4d97d8e5f39f34c624d5c54b9c870f696203011758ef
3009 metadata, 19604 content objects imported; …
```
=> build: Lower zlib compression level for tmp/repo

build.sh, src/cmdlib.sh
The RHCOS 4.10 Power pipeline is hitting the second variant in
openshift/os#594 (comment).
This is worked around in more recent pipelines by the move to OCI
containers, but 4.10 doesn't have this code and it seems risky to
backport. So let's just bump the memory there for that release.
=> [rhcos-4.10] cmdlib.sh: bump supermin VM to 8G of RAM on ppc64le

Makefile
We're not heavily using/developing gangplank right now, and the
unit tests suddenly started failing for reasons that aren't
obvious to me.
Turn them off by default for now.
=> build-sys: Drop `gangplank-check` out of `make check`

src/cosalib/cmdlib.py
CI hit a race where parallel `buildextend-*` would race to generate
`tmp/image.json`.
We need to lock this for efficiency (avoid duplicate work) and
correctness.
=> build: Use lockfiles to guard ostree repo and `image.json` extraction

build.sh
We have `errexit` in `build.sh`, but that has no effect on `make` here
because it's part of a command list.
Closes: #2897
=> build.sh: fix error-handling for `make`

ci/prow-rhcos.sh, src/cmd-buildextend-live
This is an adapted backport of a bug fix in https://github.com/mrcxavier/coreos-assembler/commit/0846cfc66c3005e02653f570d5eee89ae4d4d011.
It was reporting "Error: No karg embed areas found; corrupted CoreOS ISO image."
Now it is inserting the correct path as also cleaning the dict.
We decided do not backport since 4.9 does not have the kargs.json file
Signed-off-by: Marcio Xavier <marcioas@br.ibm.com>
=> [rhcos-4.9] buildextend-live: fix grub.cfg path in kargs.json on ppc64le

mantle/kola/tests/coretest/core.go
The functionality is now moved to external tests in
https://github.com/coreos/fedora-coreos-config/pull/1768.
Also we no longer need to exclude the test on s390x as the
files mentioned in https://github.com/coreos/mantle/issues/1132
don't exist anymore in /etc/sysconfig/network-scripts/ on s390x
in RHCOS.
=> tests: remove basic/NetworkScripts test

mantle/kola/tests/misc/network.go
Now that we have an ipv6 enabled VPC in AWS we need to update our
test to account for Networkmanager listening on port 546 for DHCPv6.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1216
=> kola/tests: account for ipv6 in `fcos.network.listeners`

ci/prow-rhcos.sh, src/cmd-init, src/cmdlib.sh
init: Add `--transient` flag for ephemeral builds
We go to a lot of effort to create various caches of builds, and this
is very useful for local incremental development to avoid re-downloading
RPMs and rewriting data.
Conversely, it is useless for CI builds that discard everything when they're done, and actually slows things down.
Add a `cosa init --transient` flag that for now just disables `fsync()`
on `tmp/repo`.
There's more we can do here in the future, for example we need to
propagate this too into `cache/repo-build` and `cache/pkgcache-repo`,
and actually in general we don't need the pkgcache repo at all here.
---
init: Add a success message
To make it clearer that things worked.
---
=> init: Add `--transient` flag for ephemeral builds

Makefile, tools/Makefile
The new version is causing issues with files being transferred back
being directories and not files and other general issues.
See https://github.com/coreos/coreos-assembler/pull/2895#issuecomment-1145558105
=> tools: freeze minio on RELEASE.2022-05-26T05-48-41Z

mantle/cmd/kola/switchkernel.go, src/cmd-buildextend-metal, src/cosalib/qemuvariants.py, src/create_disk.sh, src/gf-set-platform, src/grub.cfg
Stop specifying `console=` kernel arguments by default, except on specific arch/platform pairs where we know we need them.  Do the same with console configuration in `grub.cfg`.  More info in coreos/fedora-coreos-tracker#567.
Read `platforms.yaml` from the config repo (https://github.com/coreos/fedora-coreos-config/pull/1181) to determine what console settings should be applied for each arch/platform.  Convert the table for the current arch to JSON and copy it to `/boot/coreos/platforms.json` in the image, since coreos-installer needs the same data when overriding the platform ID at install time (https://github.com/coreos/coreos-installer/pull/605).  If `platforms.yaml` is missing, continue applying the previous defaults.
We do this in two places: `create_disk.sh` configures console …
=> Configure the console by default only on particular platforms

src/cosalib/cmdlib.py
Linux `tmpfs` still doesn't support `user.` xattrs, and so for
toolbox-like containers that use a (proper!) `tmpfs` for `/tmp`
instead of having it be `overlayfs`, we need to ensure that
we create our tempdir in `$workdir/tmp` - the workdir must have
`user.` xattr support for the `cache/repo-build` anyways.
Closes: https://github.com/coreos/coreos-assembler/issues/2904
=> cmdlib: Ensure bare-user tmpdir is in $workdir/tmp

docs/cosa.md, docs/working.md
docs: Delete reference to `cosa runc`
Was gone in previous commit.
---
docs: Document `cosa build-fast`
I was surprised this was omitted.  Came up in chat.
---
=> Two docs patches

src/cmd-sign
Part of actually shipping chunked format, see
https://github.com/coreos/fedora-coreos-config/pull/1698
Not tested.
=> sign: Use `replace-detached-metadata` if available

src/cmd-sign
Regression from previous commit.
=> sign: Coerce output to UTF-8 to avoid a runtime crash

src/cmd-sign
The new flow requires the source container, so we can't delete
it before trying to inject the signature.
Rework both paths to write to a temporary path, then `rename()` into
place for consistency, and this is also closer to being an atomic
operation.
=> sign: Don't delete source container before trying to inject signature

src/cmd-build
It seems that (at least older?) containers/storage barfs on this, so let's drop
down a good bit.
(We could also change the ostree upstream default, but...mmm, perhaps
later)
=> build: Drop down to 50 layers for chunked images

src/cmd-push-container
Closes: https://github.com/openshift/os/issues/847
=> push-container: Actually use tag to push

src/cmd-push-container
The latter takes the suffix as a parameter so that we don't have to
hardcode any suffix in the codebase itself.
Addresses review comment:
https://github.com/coreos/coreos-assembler/pull/2837#pullrequestreview-959395787
(cherry picked from commit c462739e1a15cd428c865511ffa3a46434580301)
=> [rhcos-4.11] cmd-push-container: replace --base-image-name by --name-suffix

mantle/platform/platform.go
This fixes calling `checkSystemdUnitFailures` using the output from the
`systemctl` command with `activating` substituted instead of `failed`.
Fixes d4661ae49 ("Add kola to detect when a systemd unit is stuck
activating").
=> mantle/platform: fix unit failure basic check

src/cmd-push-container
I misunderstood the original intent of this switch while reworking it.
The idea is to add a suffix to the image tag, not its name.
Fix it, and rename the switch accordingly.
While we're here, add a metavar to `name` to make it clear that an
optional tag can also be provided.
Fixes c462739e1 ("cmd-push-container: replace --base-image-name by
--name-suffix").
Closes: https://github.com/openshift/os/issues/847
=> cmd-push-container: fix --name-suffix semantics

src/cmd-push-container
I misunderstood the original intent of this switch while reworking it.
The idea is to add a suffix to the image tag, not its name.
Fix it, and rename the switch accordingly.
While we're here, add a metavar to `name` to make it clear that an
optional tag can also be provided.
Fixes c462739e1 ("cmd-push-container: replace --base-image-name by
--name-suffix").
Closes: https://github.com/openshift/os/issues/847
(cherry picked from commit 80152043d7e7c614c087f4ae4fede123b176a2d1)
=> [rhcos-4.11] cmd-push-container: fix --name-suffix semantics

ci/prow-rhcos.sh
Use a COSA specifc test entry point to focus on tests relevant for COSA.
=> ci/prow-rhcos: Use COSA specific test entry point

src/cmdlib.sh
It's OK, it will just be slow.  In some cases e.g. "I just want
to inject some kernel arguments in a custom AMI building from a Mac",
the performance hit is OK.
=> cmdlib: Explain to people they can set `COSA_NO_KVM`

src/cmd-generate-hashlist
There are a lot of symlinks in the OSTree compose and initrd. Listing
them all adds noise to pipeline outputs.
=> cmd-generate-hashlist: don't print symlinks skipped

src/cmd-generate-hashlist, src/cmd-sign, src/cosalib/cmdlib.py
`flufl` requires specifying lock lifetimes, i.e. how long the lock
should be considered valid before others can also lock it. The default
is 15s. This surprisingly means that a critical section could in fact be
run concurrently if one of the locks takes more than 15s.
I don't think we want to use lock lifetimes here, so let's make sure we
always pass in a large number. The intended use case is that your
program doesn't deadlock, but I'd prefer we deadlock and have pipelines
fail instead after timing out at the Jenkins level.
This should fix the `NotLockedError: Already unlocked` error messages
we've had in the FCOS pipeline after parallelizing
`cosa generate-hashlist` and `cosa buildextend-qemu` (related:
https://github.com/coreos/fedora-coreos-pipeline/pull/554).
What would be …
=> cmdlib: make locks use long lifetimes

mantle/kola/tests/misc/users.go, mantle/platform/cluster.go
We're removing it from FCOS (https://github.com/coreos/fedora-coreos-tracker/issues/770).
Nothing in this PR should cause a behavior change with OS images that still include the pinger.
=> Drop references to fedora-coreos-pinger

src/cmdlib.sh, src/create_disk.sh
On s390x we've seen the supermin VM get the two disks attached to
it when running buildextend-qemu mixed up such that the blank 10G
disk to be populated is vda and superman fails to start because it
can't mount a blank disk. Let's mount via filesystem UUID here.
=> cmdlib: mount supermin root disk by UUID

src/cmd-buildextend-metal
It looks like the support for an argument passed to `--build` was
erroneously removed as part of 1d33f5bf4
=> buildextend-metal: fix --build to take an argument

src/cmd-build, src/cmd-fetch, src/cmdlib.sh, src/compose.sh, src/vmdeps.txt
Instead of having rpm-ostree effectively doing a `pull-local` under the
hood over 9p, change things so we compose in a local repo, export the
commit to an archive and only copy *that* over 9p.
This should greatly help with pipelines hitting ENOMEM due to
transferring many small files over 9p:
https://github.com/openshift/os/issues/594
An initial approach exported to OCI archive instead, but encapsulating
and unencapsulating are more expensive operations. Unfortunately, we
still need to unpack into `tmp/repo` given that many follow-up commands
expect the commit to be available in `tmp/repo`. If we can drop that
assumption (and get rid of `tmp/repo` entirely), we could refactor
things further so that `compose.sh` creates the final chunked OCI
artifact upfront.
In local testing, this adds …
=> Don't `pull-local` over 9p during rpm-ostree compose

build.sh
After https://github.com/coreos/coreos-assembler/pull/2943, build on s390x fails with:
```
yum -y --setopt=releasever=35 distro-sync edk2-ovmf
Fedora 35 - s390x                                18 MB/s |  72 MB     00:04
Fedora 35 openh264 (From Cisco) - s390x         1.7 kB/s | 2.5 kB     00:01
Fedora Modular 35 - s390x                       1.3 MB/s | 3.2 MB     00:02
Fedora 35 - s390x - Updates                     7.8 MB/s |  27 MB     00:03
Fedora Modular 35 - s390x - Updates             1.4 MB/s | 3.1 MB     00:02
No package edk2-ovmf installed.
Error: No packages marked for distribution synchronization.
```
Ignore the error.
=> build: don't fail if edk2-ovmf couldn't be found (s390x)

Makefile, src/cmd-fetch
This is a rework of https://github.com/coreos/coreos-assembler/commit/0ea19847cde4a6f524913c6b31e8d808556c8b72 ("cmd-fetch: pass --force-nocache").
It's wasteful to do this by default because pipelines don't have cache
and we don't want them to always fetch packages if it's going to no-op
anyway.
Let's make it a `--force` option instead to match `cosa build`.
=> cmd-fetch: make `--force-nocache` optional

src/cmdlib.sh
Like in e6b07ffb2 ("cmdlib: rename `cosa-image-json` ostree overlay"),
we need the content set overlay and the `overrides/rootfs` overlay to
use that prefix. That's how `compose.sh` knows to pull it over 9p.
Fixes: #2949
=> cmdlib: consistently use `overlay/` prefix for injected overlays

src/cmdlib.sh
In addition to a lockfile, we can be even stronger here by using
repo-packages to tell rpm-ostree that the overridden packages must come
from the generated overrides repo.
This also allows one to override RPMs which themselves are specified as
`repo-packages` in the manifests without in most cases having to edit
them.
Related: https://github.com/coreos/rpm-ostree/issues/3789
=> cmdlib: use `repo-packages` for `overrides/rpm`

mantle/cmd/kola/kola.go, mantle/platform/qemu.go
There's a bunch of other places that use `math/rand`. None of them rely
on the default seed of 1 and some cases may cause issues if the same
sequence is used. One example is creating temporary cloud resources:
we're currently investigating Azure tests failing with
```
Cluster failed: creating storage account: storage.AccountsClient#Create:
Failure responding to request: StatusCode=409 -- Original Error:
autorest/azure: Service returned an error. Status=409
Code="StorageAccountAlreadyExists" Message="The storage account named
kolasa94cb3c7856 already exists under the subscription."
```
and we think this is part of the issue.
Let's just seed the generator early during startup so that lower levels
don't have to think about whether to re-seed or not.
=> kola: seed `math/rand` earlier

src/cmd-meta, src/cmd-oc-adm-release, src/coreos-assembler
We already have fallback defaults in the code.  Avoiding global
environment variables is good on general principle; but this
is specifically prep for making the entrypoint a Go program.
=> main: Stop setting `COSA_META_SCHEMA`

src/coreos-assembler
Prep for reworking this in Go, where re-exec'ing ourself is
a bit more hairy.
Also I think this code should really, finally be dead.  We shouldn't
be seeing the host selinuxfs mount in any container setup.
---
=> main: Change `/sys/fs/selinux` handling to be a hard error

src/coreos-assembler
This reverts commit 46d5bc9a989c5ed7d43ec548add545fc5573f293.
We saw this fail on at least one s390x job run via gangplank.
=> Revert "main: Change `/sys/fs/selinux` handling to be a hard error"

ci/prow-rhcos.sh, src/cmd-build, src/cmd-buildextend-live, src/cmd-buildextend-metal, src/cmd-fetch, src/cmd-generate-hashlist, src/cmd-init, src/cmd-sign, src/cmdlib.sh, src/compose.sh, src/cosalib/cmdlib.py, src/cosalib/ova.py, src/cosalib/qemuvariants.py, src/vmdeps.txt
Backports for 4.11:
- https://github.com/coreos/coreos-assembler/pull/2889
- https://github.com/coreos/coreos-assembler/pull/2922
- https://github.com/coreos/coreos-assembler/pull/2930
- https://github.com/coreos/coreos-assembler/pull/2839
- https://github.com/coreos/coreos-assembler/pull/2886
- https://github.com/coreos/coreos-assembler/pull/2946
Revealed by: https://github.com/openshift/release/pull/29949
=> [4.11] Backports for RHCOS CI (--transient option & test entrypoint)

mantle/platform/qemu.go
We get a ton of output on the serial console of the machines because
the we're using the UEFI firmware with debug output. Let's use the
"silent" version instead.
I suspect this will also speed up our testing on qemu/aarch64.
=> mantle/platform/qemu: use non-debug UEFI firmware for aarch64

src/cmdlib.sh
This is follow-up to https://github.com/coreos/coreos-assembler/commit/8c8b7338af5e1395604498cab47227cd7c47a011 ("cmdlib: use `repo-packages` for
`overrides/rpm`").
That commit changed semantics of `overrides/rpm` such that all packages
found are forced to be installed rather than only "preferred".
This revert the semantics back to what it used to be while still
allowing `repo-packages` to be overridden.
We do this by simply only adding a `repo-packages` override for the
packages which are found in the flattened manifest.
=> cmdlib: use `repo-packages` for `overrides/rpm` only as necessary

docs/kola/external-tests.md, mantle/kola/harness.go, mantle/platform/platform.go
```
commit 0a7f0ce3a15376078ccc331de898f5f2facb9705
Date:   Fri Jul 8 10:59:44 2022 -0400
mantle/kola: extend --ssh-on-test-failure to work when systemd unit failrues are detected
It's frustrating when systemd unit failures are detected but you can't
just get a shell on the machine to investigate. This patch plumbs
through the SSHOnTestFailure information into the RuntimeConfig for the
machine object so we can use that information within CheckMachine to
dropt into a shell if desired by the user.
commit 9483eb704d8e49f850a702d6ff54cdae71edc51e
Date:   Fri Jul 8 10:30:58 2022 -0400
mantle/kola: extend the "skip-base-checks" tag to cover systemd unit failures
This will mean that if someone adds the …
```
=> mantle/kola: machine check enhancements

src/cmd-build
This will have us start making use of
https://github.com/ostreedev/ostree-rs-ext/pull/331
(Arguably rpm-ostree should default to the new one, but...eh,
at some point not too long from now we'll be ripping out support
for all the old things and just making this the default)
=> build: Default to new ostree chunked v1 (with new rpm-ostree)

src/cmd-build
We have a ton of "pipelines" today, and they all invoke
```
cosa fetch
cosa build ...
```
However, almost all the pipelines are also now using `--transient`
because we don't want to maintain a cache.  In the future, we
can optimize this case of `cosa build --fetch` to in theory
avoid writing any persistent cache data at all in the transient
case.
Also, this will help drop some duplication in the pipelines, from
just two lines to one admittedly.
=> build: Add a `--fetch` (`-F`) argument

mantle/platform/metal.go
The `-option-rom .../pxe-rtl8139.rom` used to be required but is no
longer needed because according to [1] "If no rom bar is specified,
the qemu default will be used (older versions of qemu used a default
of "off", while newer qemus have a default of "on")".
The attribute `file` which is used to pass  an [1] 
`alternative boot ROM for a network device` is optional and thus 
assumed to have a default in QEMU.
So now qemu will default to loading the option rom for the given NIC
device model.
[1] https://gitlab.com/libvirt/libvirt/-/blob/3547875f3a8cf286a03b62f5e7bdb8e4b0eeee29/docs/formatdomain.rst#interface-rom-bios-configuration
fixes: https://github.com/coreos/coreos-assembler/issues/2918
=> metal.go: remove optional rom pxe-rtl8139 

src/cosalib/ova.py, src/image-default.yaml, src/vmware-template.xml
Add toggle for secure boot in the OVA.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=2106055
=> vmware: add image.yaml toggle for secure boot

src/create_disk.sh
```
commit d4225adc39dad9b0a774057b01218fd27d8cd4c2
Date:   Tue Jul 12 17:18:12 2022 -0400
create_disk.sh: use /bin/bash interpreter
We're already using bashisms in this script, so this is just reflecting
reality.
As a plus, this makes the script no longer ignored by ShellCheck.
```
```
commit 9330b89f4368b2e9f24f859a8fd64bfe91c09eea
Date:   Tue Jul 12 17:19:32 2022 -0400
create_disk.sh: address ShellCheck lints
Nothing major here. Mostly quoting arguments where needed.
```
=> create_disk.sh: use /bin/bash interpreter and address ShellCheck lints

Makefile, ci/prow.sh, gangplank/Makefile, tools/Makefile, tools/README.md
Installing it is flaky and regularly breaks Prow and/or CoreOS CI. I
think the main issue for Prow is that the install script uses the GitHub
API anonymously and we get rate limited.
Looking at the official docs, they recommend using the GitHub Action
instead so let's do that in a follow-up (and have it run over the whole
repo instead of just the gangplank code).
=> Drop golangci-lint from image build

src/cosalib/ova.py, src/image-default.yaml, src/vmware-template.xml
Add toggle for secure boot in the OVA. This is a cherry-pick of two
commits that added the toggle for secure boot.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=2106055
(cherry picked from commit 37df48675f350539bff4bd8205f89e5ec5dc5e78)
(cherry picked from commit 27fa455d3c1925e478171ef38e3d618f015ef453)
=> [rhcos-4.11] vmware: add image.yaml toggle for secure boot

src/create_disk.sh
The use of `-p` was dropped in
9330b89f4368b2e9f24f859a8fd64bfe91c09eea to appease some ShellCheck
errors.  (Notably https://www.shellcheck.net/wiki/SC2174)
But dropping the use of `-p` causes a fatal error when the directory
already exists.
This reintroduces the use of the `-p` flag and splits out setting the
permissions on the directory as a separate operation.
Closes openshift/os#896
=> create_disk: use -p when creating grub2 directory

src/cmd-sign, src/cosalib/builds.py
```
commit 261331f642457f9cb3aa1c37a3d048a78e2614d0 (HEAD -> dusty-prep, origin/dusty-prep)
Date:   Fri Jul 15 13:46:42 2022 -0400
cmd-sign: add s3 --aws-config-file option
This will allow us to specify the AWS_CONFIG_FILE from the command
line without having to set it in the environment.
commit bb98107c1c87095ddef274ebcd9a2e2a592a724e
Date:   Fri Jul 15 10:18:28 2022 -0400
cosalib: fix init_build_meta_json for multi-arch
If we are starting out a brand new stream and the x86_64 build
has completed, but there was no build yet for $arch then the detected
previous buildid:
```
previous_buildid = parent_build or self.get_latest()
```
Will just be the build ID of the x86_64 build from `get_latest()`,
but this …
```
=> prep patches for podman-remote work

mantle/kola/tests/misc/files.go
Since [ext.config.files.setgid](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/files/setgid) and [ext.config.files.setuid](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/files/setuid)  test the same thing as filesystem/sgid and filesystem/suid respectively, we can drop them from here
=> kola/tests/files: Drop filesystem/sgid and filesystem/suid

gangplank/vendor/github.com/coreos/coreos-assembler-schema/cosa/build.go, mantle/vendor/github.com/coreos/coreos-assembler-schema/cosa/build.go, schema/cosa/build.go
This will make the error more clear when trying to run
an upgrade test where the fedora-coreos.parent-version`
is not actually a real version in the stream history.
I'm running a separate pipeline right now and so I'm
pushing dev builds into s3 and my parent version is
`36.20220716.dev.1`. That doesn't exist in the real
testing-devel stream so the code barfs like this:
```
$ cosa kola --rerun --upgrades --no-test-exit-error
kola -p qemu-unpriv --output-dir tmp/kola-upgrade run-upgrade --rerun --no-test-exit-error --qemu-image-dir tmp/kola-qemu-cache -v --find-parent-image
2022-07-16T21:52:14Z cli: Started logging at level INFO
2022-07-16T21:52:14Z cli: Started logging at level INFO
Error: failed to parse build: invalid character '<' looking for beginning of value
```
This will improve …
=> schema/cosa/build: check http response codes in http.Get

src/create_disk.sh
We should be able to ship `secex` image without baking LUKS keys and config at all.
=> s390x: remove SE luks keys from the deployment

mantle/harness/harness.go, mantle/kola/harness.go, mantle/platform/cluster.go, mantle/platform/machine/aws/machine.go, mantle/platform/platform.go
Some platforms (particularly AWS) take a long time to perform
post-termination tasks. AWS sometimes takes 5 minutes to retrieve
console logs. This is a bottle neck to how fast our tests can run.
Let's add a callback that will allow us to release a test early before
post-termination tasks, so that the next tests waiting in queue may begin.
=> platform: add an early release callback

.github/workflows/lints.yml, Makefile, src/deps.txt
This is similar to
https://github.com/coreos/coreos-assembler/pull/2977
https://github.com/coreos/coreos-assembler/pull/2978
Today we're shipping code linting tools for shell and python
as part of the coreos-assembler image, which makes little sense.
Move `ShellCheck` to a separate CI flow run via GH actions.  For local
development, this are now manual instead of run as part of
`make check`.
(I tried to move python too but `pylint` depends on half the world
being installed)
=> ci: Move ShellCheck to GH actions

src/cmd-build
It was intended to be optional, but our dynamic detection
of the availability of the option masked that bug.
This now bites us with the new rpm-ostree.
=> build: Always pass `--format-version` to rpm-ostree

mantle/platform/platform.go
See https://github.com/openshift/os/pull/901, when running kola test for scos, get error, this is to fix it
```
$ cosa kola run ostree.basic
kola -p qemu-unpriv --output-dir tmp/kola run ostree.basic
=== RUN   ostree.basic
--- FAIL: ostree.basic (57.14s)
harness.go:1443: mach.Start() failed: machine "ea43750e-e04b-4632-b966-caff659a5214" failed basic checks: not a supported instance: scos-coreos
FAIL, output in tmp/kola
Error: harness: test suite failed
2022-06-10T09:12:23Z cli: harness: test suite failed
```
=> Update centos distribution to scos as this prevents scos build testing

mantle/harness/harness.go
A followup from https://github.com/coreos/coreos-assembler/pull/2990.
Let's touch on the "why" for introducing idempotence in `H.Release`.
=> harness/harness.go: add comment for H.Release

src/cosalib/builds.py, src/deps.txt
I am working in the background a bit on a C9S-derived build of
coreos-assembler, this will help with that.
The goal is to use basically only stock python dependencies, and
overall move to using Go+vendoring.
=> Drop use of `python3-semver`

src/cmd-build, src/cmd-buildfetch, src/cmdlib.sh, src/cosalib/builds.py
```
commit a8896bc193774b2ead347e6ee75c89db187319b4
Date:   Fri Jul 22 11:56:28 2022 -0400
cmd-buildfetch: add --find-build-for-arch option
This instructs buildfetch to traverse the builds.json history to
find the most recent build for the given architecture.
commit 54cd68e0af7e796ac4cc4a30bcd1a43b6c45ac0a
Date:   Fri Jul 22 11:55:42 2022 -0400
cmd-buildfetch: bring the ostree ref delete into the loop
There will be a ref per arch so we need to do it on each loop
iteration.
commit 65e2d8b51c2bcc091803587967448347552aa435
Date:   Fri Jul 22 11:54:40 2022 -0400
cmd-buildfetch: continue loop if arch missing
The user could have passed in multiple arches so we should …
```
=> handle build with arch mismatch; support buildfetch --find-build-for-arch

build.sh
The latest coreos-installer dropped support for the legacy alias
`iso extract pack minimal-iso`, so this broke the 4.10 pipeline.
The core issue is that we run miniso packing using the coreos-installer
from cosa. We should fix this and make it use supermin to run the
packing step with the coreos-installer in the compose (like for osmet).
But for now, let's work around this by just freezing coreos-installer on
the version we're actually shipping in 4.10.
Closes: https://github.com/openshift/os/issues/916
=> [rhcos-4.10] build.sh: freeze coreos-installer to v0.12.0

mantle/cmd/kola/options.go, mantle/platform/cluster.go
Quite a while ago we added this special case code to kola
which learned how to do in-place updates to the weird bespoke
"ostree repo in container" OCP/RHCOS-specific container image.
A huge benefit of the change to use ostree-native containers
is that this approach can now be shared across FCOS/RHCOS.
(Also, rpm-ostree natively understands this, so it's much much
more efficient and less awkward than the wrappers we had in `pivot` around
rpm-ostree)
But the benefits get even larger: this issue:
https://github.com/coreos/coreos-assembler/issues/2685
proposes rethinking of our pipeline to more cleanly split up
"build OS update container" from "build disk images".
With this, it becomes extra convenient to do a flow of:
- build OS update container, push to registry
- `kola run -p stable …
=> kola: Change `--oscontainer` to use new ostree native containers

mantle/kola/harness.go
If a test is modifying kernel arguments it's almost by defnition not
friendly to other tests. Let's detect this and error out.
This would have saved me some time as I was hacking around locally.
=> mantle/kola/harness: disallow AppendKernelArgs for non-Exclusive tests

.cci.jenkinsfile, mantle/cmd/kola/kola.go, mantle/system/nproc.go, src/cmd-compress, src/cosalib/cmdlib.py, src/libguestfish.sh
The existing Go CPU-count code doesn't even attempt to report multiple CPUs if it detects Kubernetes, and the existing Python code in `cmd-compress` doesn't attempt to determine cgroup quotas unless it detects Kubernetes specifically.  Consolidate the CPU count detection into Go code, and always factor in any CPU quotas from either cgroups v1 or v2.
Use the new code to give the libguestfs VM the same number of vCPUs as the host, so mksquashfs can use all of them.  On my 6-core system, this reduces FCOS `buildextend-live` without `--fast` from 4m9s to 2m23s.
Request 8 CPUs in CoreOS CI to avoid the new default of 2 in https://github.com/coreos/coreos-ci-lib/pull/112.
=> Consolidate and reimplement CPU-count logic; enable SMP mksquashfs

mantle/kola/tests/rpmostree/deployments.go
See:
- https://bugzilla.redhat.com/show_bug.cgi?id=2113042
- https://github.com/coreos/rpm-ostree/issues/3241
=> tests: add `--cache-only` option for `rpm-ostree install` in scos testing as workaround

docs/kola/external-tests.md, mantle/kola/harness.go, mantle/kola/register/register.go
Closes: https://github.com/coreos/coreos-assembler/issues/2952
For quite a while we've been generating a "base image" container
as part of our builds, but it has basically been entirely untested
outside of its processing and use by the ostree stack.
This adds a base framework such that external tests can request
the injection of the container (`.ociarchive`).
Now, we can (and *definitely* should) also pursue "natively" testing
this container image outside of kola, which is very virtual-machine
focused.
However, that will also require a lot of pipeline changes; this
approach allows us to natively "bridge" the worlds of cosa/kola
to test the container image.
=> kola: Add support for `injectContainer`

src/cmd-buildextend-extensions
This is what we should do in general, but specifically motivated
by trying to avoid out-of-space problems for RHCOS builds right now.
=> buildextend-extensions: Clean up temporary workdir when done

docs/cosa/run.md
Those kargs are required for sysroot to actually be mounted from the
multipathed target.
=> docs/cosa/run: add missing kargs to multipath example

mantle/kola/tests/rhcos/upgrade.go
This is how we want to expose it to users, the `ex-container` CLI
is deprecated and will be removed.
=> tests/rhcos/upgrade: Switch to `ostree container`

docs/kola.md, mantle/kola/harness.go, mantle/kola/tests/ignition/luks.go, mantle/kola/tests/misc/boot-mirror.go
Support passing e.g. `--tag !foo` to exclude all tests with tag `foo`.
=> kola/harness: support excluding tests by tag

cmd/remote-session.go
```
commit 1041c620276950f44554e9d57317090fcbbb7a2e
Date:   Fri Aug 5 16:41:46 2022 -0400
cmd/remote-session: update to use `main` tag from quay.io
Both tags work but `main` maps to the branch name we use and we've
been trying to use that in more places so let's use it here too.
commit dde9d09e133a4aaa4e5b331645260353dd312acf
Date:   Fri Aug 5 16:40:05 2022 -0400
cmd/remote-session: specify --pull=always when creating container
Otherwise our remotes use their local copy of the remote container
image and it never gets updated from the first time it was pulled.
With --pull=always no work is done if the container latest version
of the container is already local (i.e. it uses the cached local
copy), but the …
```
=> cmd/remote-session: specify --pull=always when creating container

src/cmd-buildfetch
I accidentally typed `--artifact qemu --artifact qemu` and buildfetch
downloaded it twice. Let's dedupe here.
Also, let's apply "all" even if the user passed more than one argument
to `--artifact`.
=> src/cmd-buildfetch: dedupe --artifact list

mantle/platform/metal.go, mantle/vendor/github.com/coreos/coreos-assembler-schema/cosa/build.go, schema/cosa/build.go
We should not continue with any testiso scenario if we don't have the relevant local images to run it on. When we `cosa buildfetch` we end up with a `meta.json` which specifies that we have a live kernel and iso image and run the tests regardless of the actual local existence of those images. Added an additional check for those images in addition to the check that we already do with `meta.json` to give an appropriate error earlier
Fixes: https://github.com/coreos/coreos-assembler/issues/2991
=> testiso: Check local iso image and live kernel existence

Dockerfile, src/add-root-cas
Similarly to the familiar `/etc/passwd` OpenShift hack, loosen up
restrictions on `/etc/pki/ca-trust` so that the unprivileged UID can add
root certificates to the platform.
This allows cosa to be used as is to build in environments where
additional root certificates may be necessary to fetch build inputs.
Add a script which can be used instead of `update-ca-trust` (which
assumes root with `CAP_DAC_OVERRIDE`) to update the primary bundles we
really care about for our stacks.
=> Dockerfile: allow root group to add root certificates

src/update-ca-trust-unpriv
Don't support passing a directory containing root CA certs to copy.
Default to just updating the bundles like `update-ca-trust` does.
Accordingly, rename to `update-ca-trust-unpriv`.
=> Simplify `add-root-cas` script and rename

mantle/platform/qemu.go, src/libguestfish.sh
```
commit 6c25ec0fd64b82dc70f31fa7262d656021cd4ccd
Date:   Thu Aug 11 10:10:35 2022 -0400
only set LIBGUESTFS_HV for ppc64le on el7
It appears the newer P9 hardware that we are utilizing that is running
a Fedora stack doesn't need this. Local testing seems to work fine.
Let's hack around this for now while we still have el7 clusters.
commit 0eb38ebcad430c58e2e58fed5c069a638a07e73f
Date:   Mon Aug 15 16:23:49 2022 -0400
mantle/platform/qemu: fix seting of LIBGUESTFS env vars
This setting of cmd.Env was overriding the LIBGUESTFS_BACKEND=direct
that was being set just a few lines before. So the command was getting
run with just LIBGUESTFS_HV being set, which happens to have no
effect unless …
```
=> only set LIBGUESTFS_HV for ppc64le on el7

src/create_disk.sh
[Fixes petitboot on ppc64le](https://bugzilla.redhat.com/show_bug.cgi?id=2107674).  Backports 45fc1e7518e28834ecfa3c63e24bcfad0696bbfe from #2400.
=> [rhcos-4.11] Bug 2107674: Add missing trailing newline in `grub.cfg`

src/cmd-init, src/cmdlib.sh, src/supermin-init-prelude.sh
Just like the main source config, support passing an existing git
checkout to `--yumrepos` for a better local dev experience.
=> cmd-init: support `--yumrepos` being a local checkout

src/cmdlib.sh, src/supermin-init-prelude.sh
As part of https://issues.redhat.com/browse/COS-1646 podman is
going to be running inside the supermin vm, we run out of disk
quickly with 5G when loading the rhcos image in the FROM line.
Podman also needs /sys/fs/cgroup properly mounted as cgroup2.
=> supermin: double disk space of supermin vm and use cgroups2

src/image-default.yaml
Let's merge this in...say a month or so?  rpm-ostree v2022.12
should have propagated far enough by then.
=> image: Default to chunked-v1

src/create_disk.sh, src/deps-s390x.txt, src/vmdeps-s390x.txt
LUKS with `--integrity` provided us with integrity protection so that we
were sure a malicious sysadmin couldn't have tampered with the disk
image. The problem however is that then we have to think about
protecting the generic per-cosa build LUKS keys.
We don't need confidentiality here, just integrity. Switch to using
dm-verity, which is made for this. Add new partitions to store the
hashes. Run `cryptsetup format` to populate them. Put the root and boot
partition root hashes in the kernel command line. Delete code related to
the previous LUKS approach.
On first boot, we will delete the hash partitions, and reprovision the
rootfs and bootfs on top of LUKS.
=> Protect s390x secex filesystems using dm-verity instead of LUKS
