coreos/coreos-assembler

src/create_disk.sh
The new switch requires a new coreos-installer in the target systems.
Keep using the old switch for now until that happens.
The Secure Execution bit at the bottom still uses the newer
`--append-karg` because it needs latest coreos-installer anyway and no
pipeline is currently building the secex image.
Fixes 3246b72cb ("Protect s390x secex filesystems using dm-verity
instead of LUKS").
=> create_disk.sh: go back to using --kargs for `rdcore zipl`

src/cmd-build-fast
To work with https://github.com/ostreedev/ostree-rs-ext/pull/356/commits/9c4a75b3778a3f2fdece095f8f5f7a6289ab512d
which wants ostree-ext to hard require the key on container
images.
=> build-fast: Also propagate `ostree.bootable`

src/cmd-build
Following https://github.com/coreos/rpm-ostree/pull/3904/commits/60c8facfda1f79744a6a570613828772a7f93d93
=> build: Switch to `rpm-ostree compose container-encapsulate`

src/cmd-buildextend-live
Fix https://github.com/openshift/os/issues/954
=> cmd-buildextend-live: always change `EFI/{vendor}` to correct vendor id

docs/kola/external-tests.md, mantle/kola/harness.go
The *third* salvo in my battle against the duplicative and verbose
required comment metadata we've grown in fedora-coreos-config.
A key objection I have to it is that it requires specifying
the option *twice* - meaning it's easy for the actual options and
the comments to get out of date, etc.
Add support for YAML for metadata, which is just nicer to write:
- We support comments inline
- The data can span multiple Lines
So if we have comments to add, we can now do it in a better way.
=> kola: Also support inline YAML for metadata

src/cmd-remote-build-container
This should allow us to build the fcos-buildroot container from
https://github.com/coreos/fedora-coreos-config/tree/testing-devel/ci/buildroot
=> src/cmd-remote-build-container: support building from subdirectories in git repos

docs/kola/external-tests.md, mantle/cmd/kola/options.go, mantle/kola/harness.go
So in fedora-coreos-config we grew this "standard" for documenting
the tags for tests:
https://github.com/coreos/fedora-coreos-config/blob/50ee01a89075d8ef204f1f40c5d89ab060748aac/README.md#tests-layout
And we've semi-standardized on the idiom `platforms: qemu` with
a manual documentation flag.  But just look at the level
of duplication:
```
$ git grep 'This test should pass everywhere'
tests/kola/binfmt/qemu:#   - This test should pass everywhere if it passes anywhere.
tests/kola/clhm/ignition-warnings/test.sh:#   - This test should pass everywhere if it passes anywhere.
tests/kola/content-origins/test.sh:#   - This test should pass everywhere if it passes anywhere.
tests/kola/extensions/module:#   - This test should pass everywhere if it passes anywhere.
tests/kola/extensions/package:# …
```
=> kola: Add a `platform-independent` tag

cmd/build-extensions-container.go
We hit on the problem that current RHCOS pipeline uses a separate volume for `builds/`, and we can't use `rename()` across that. One thing the `finalize-artifact` wrapper does today is use `mv` which will use an efficient `rename()` if possible, otherwise fall back to a copy.
(We also now more consistently make the artifact read-only)
=> build-extensions-container: use `finalize-artifact`

mantle/kola/harness.go
We strongly prefer to have a tracking issue for each denylist entry, but
let's not display a mostly empty line when there isn't one.
=> kola: denylist: Only display tracking issue when available

mantle/kola/tests/misc/network.go
Make the update according to the default config in `/etc/dnsmasq.conf`
- Check dnsmasq config on c9s:
```
[root@cosa-devsh ~]# rpm -q dnsmasq
dnsmasq-2.85-4.el9.x86_64
[root@cosa-devsh ~]# grep "^[^#;]" /etc/dnsmasq.conf
user=dnsmasq
group=dnsmasq
interface=lo
bind-interfaces
conf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig
```
- Check dnsmasq config on rhcos8:
```
[core@cosa-devsh ~]$ rpm -q dnsmasq
dnsmasq-2.79-21.el8.x86_64
[core@cosa-devsh ~]$ grep "^[^#;]" /etc/dnsmasq.conf
user=dnsmasq
group=dnsmasq
conf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig
```
Build scos locally with PR and run `rhcos.network.bond-with-dhcp` PASSED
```
[coreos-assembler]$ kola run rhcos.network.bond-with-dhcp
=== RUN   rhcos.network.bond-with-dhcp
--- PASS: rhcos.network.bond-with-dhcp (100.60s)
PASS, …
```
=> network: disable `interface=lo` when start dnsmasq for `bond-with-dhcp`

mantle/platform/api/azure/instance.go
Apparently it's common for it to take more than 5 minutes to respond. Let's bump it to 8.
=> mantle/platform: bump timeout for Azure CreateOrUpdate

mantle/cmd/kola/switchkernel.go, mantle/kola/harness.go, mantle/util/repo.go
`ioutil.ReadDir` has been deprecated in Go 1.16. The new `os.ReadDir` is a more efficient implementation than `ioutil.ReadDir` as stated here https://pkg.go.dev/io/ioutil#ReadDir.
The full proposal can be read here: https://github.com/golang/go/issues/41467
=> mantle: use `os.ReadDir` for lightweight directory reading

src/cmd-buildextend-live
On a coreos-installer new enough to ship `example-config.yaml` (coreos/coreos-installer#976), parse that file from the image and convert it to a map of supported directives in `features.json`.  `coreos-installer iso/pxe customize` can use this to decide whether it can safely use a directive, without us having to manually add a new feature flag every time.
While we're here, drop checks for older features and assume they always exist now.
=> buildextend-live: add coreos-installer config directives to feature map

src/cmd-buildextend-extensions
Fixes: https://github.com/coreos/coreos-assembler/issues/3074
Fixes: https://github.com/coreos/coreos-assembler/pull/3045
=> buildextend-extensions: Copy repofiles to tmpdir

mantle/kola/harness.go
For example, this ugly failure has been hanging around in our
console logs for some time:
```
[    5.733962] ln:
[    5.733968] failed to create symbolic link '/run/udev/rules.d/80-coreos-boot-disk.rules'
[    5.734511] : File exists
[    5.737931] systemd[1023]: /usr/lib/systemd/system-generators/coreos-diskful-generator failed with exit status 1.
```
Let's detect these when they pop up.
=> mantle/kola: detect when systemd-generators fail

schema/generate-schema.sh
Fixes: https://github.com/coreos/coreos-assembler/pull/3069
I am pretty sure I had this working in some point in that PR, but in reworking for feedback I broke having `make schema` actually work.
Put the target files in the right place, and fix the namespace.
=> schema: Fix `make schema`

src/cmd-build
Part of https://github.com/coreos/coreos-assembler/issues/2685
I'm looking at replacing the guts of `cosa build ostree` with the new container-native `rpm-ostree compose image`.  In order for that to work, we need two things:
- The committed overlays from `overlays/` - xref https://github.com/coreos/rpm-ostree/pull/4005
- The rendered `image.json` which is also an overlay now
Basically in combination with the above PR, this works now when invoked manually:
```
$ cosa build --prepare-only
$ sudo rpm-ostree compose image --cachedir=cache/buildimage  --layer-repo tmp/repo src/config/manifest.yaml oci:tmp/fcos.oci
```
=> build: Add a `--prepare-only` flag

src/cmd-push-container-manifest
I needed to include the `buildmeta.write` inside the for loop so that all meta.json files for each arch would get updated with the reference to the manifest list.
Fixes a8259fe
=> src/cmd-push-container-manifest: make sure all meta.json files get updated

src/cmd-remote-build-container
meta.json had `unknown` for `coreos-assembler.container-image-git.origin` because remote-build-container uses `git fetch <commit>` which does not setup a remote called `origin`. This is fixed by setting up the `origin` remote first then fetching the commit.
This was affecting all cosa branch builds because the jenkins job that builds multi-arch cosa uses the coreos-assembler:main container to remotely build cosa on all the architectures.
Closes: #3095
=> remote-build-container: add remote for origin

Dockerfile, src/add-root-cas
Similarly to the familiar `/etc/passwd` OpenShift hack, loosen up restrictions on `/etc/pki/ca-trust` so that the unprivileged UID can add root certificates to the platform.
This allows cosa to be used as is to build in environments where additional root certificates may be necessary to fetch build inputs.
Add a script which can be used instead of `update-ca-trust` (which assumes root with `CAP_DAC_OVERRIDE`) to update the primary bundles we really care about for our stacks.
=> [rhcos-4.11] Dockerfile: allow root group to add root certificates

Dockerfile, src/add-root-cas
Similarly to the familiar `/etc/passwd` OpenShift hack, loosen up restrictions on `/etc/pki/ca-trust` so that the unprivileged UID can add root certificates to the platform.
This allows cosa to be used as is to build in environments where additional root certificates may be necessary to fetch build inputs.
Add a script which can be used instead of `update-ca-trust` (which assumes root with `CAP_DAC_OVERRIDE`) to update the primary bundles we really care about for our stacks.
=> [rhcos-4.9] Dockerfile: allow root group to add root certificates

Dockerfile, src/add-root-cas
Similarly to the familiar `/etc/passwd` OpenShift hack, loosen up restrictions on `/etc/pki/ca-trust` so that the unprivileged UID can add root certificates to the platform.
This allows cosa to be used as is to build in environments where additional root certificates may be necessary to fetch build inputs.
Add a script which can be used instead of `update-ca-trust` (which assumes root with `CAP_DAC_OVERRIDE`) to update the primary bundles we really care about for our stacks.
=> [rhcos-4.8] Dockerfile: allow root group to add root certificates

mantle/kola/tests/rpmostree/deployments.go
- https://bugzilla.redhat.com/show_bug.cgi?id=2113042 is fixed
- `rpm-ostree-2022.12` is included in c9s product compose
=> rpm-ostree: update comment for `rpm-ostree install`

src/cmd-build, src/cmd-buildfetch, src/cmd-buildupload, src/cmd-generate-hashlist, src/cmd-meta, src/cmd-sign, src/cmdlib.sh, src/cosalib/aws.py, src/cosalib/builds.py, src/cosalib/cmdlib.py, src/cosalib/prune.py, src/cosalib/s3.py
We recently did some golang migration [1] and happened to add the
`cosa remote-session` pieces [2] after that migration. This makes
it not easy to backport to other branches. For a period of time
let's use the latest COSA for our COSA pod for multi-arch builds
instead of the versioned COSA. We will still use the versioned COSA
on the remote so the actual building will happened with the correctly
versioned COSA (substituted below and passed as an argument to
`cosa remote-session create --image=`). However we still need to support
some of the new command line flags that were added to aid in the transition
to `cosa remote-session`. This PR backports various pieces needed.
[1] https://github.com/coreos/coreos-assembler/pull/2919
[2] https://github.com/coreos/coreos-assembler/pull/2979
=> [rhcos-4.11] support being initiated from a `cosa remote-session`

src/cmd-build, src/cmdlib.sh
I somehow completely missed that the value is used on AWS.
This should address https://github.com/coreos/fedora-coreos-tracker/issues/1300
=> build: Restore summary value

Makefile, src/cmd-buildextend-metal, src/create_disk.sh, src/secex-genprotimgvm-scripts/genprotimg-script.sh, src/secex-genprotimgvm-scripts/post-script.sh, src/secex-genprotimgvm-scripts/runvm.sh
Add the option --genprotimgvm to the secex command, which will allow it to run
genprotimg as a separate step in it's own, as a parameter defined, VM
Background: To build RHCOS Secure Execution Images, we need to use a special
hostkey, which we do not have direct access to. Therefore we need to execute
extra steps in this case.
=> buildextend-secex: Add option to use external genprotimg command

src/cmd-buildextend-metal
Fix an issue introduced by https://github.com/coreos/coreos-assembler/pull/3025:
```
qemu-system-s390x: -drive if=none,id=hostkey,format=raw,file=src/config/secex-hostkey,readonly=on: Could not open 'src/config/secex-hostkey': No such file or directory
```
=> s390x: use full path to default secex-hostkey

src/fcos-versionary, src/fedmsg-broadcast, src/fedmsg-send-ostree-import-request
We have some loose scripts in the fedora-coreos-releng-automation repo used by the FCOS pipeline. It's always been awkward however: some of the scripts import cosa Python/shell APIs, and the pipeline has to clone the repo just to use the standalone scripts.
Initially I had thought we'd eventually find a way to have a sort of sidecar container to make that cleaner, but... that never happened. Another idea was a layered cosa image, but experience since then has shown deriving the cosa image has many downsides.
Purely for practical purposes, let's just have them in cosa directly. It's not an ideal fit but OTOH we already have a lot of FCOS-specific things in here. This will allow us to clean up the pipeline code and the automation repo.
I've renamed the scripts from their original names so …
=> Move some fedora-coreos-releng-automation scripts here

src/cmd-build
The only thing we should be doing nowadays is format v1 chunked.
=> build: Drop old ostree-format support

mantle/kola/harness.go
In 83e0f42 we added support for being able to specify external test metadata inline in yaml form, as an alternative to json. However, this didn't work for struct members with casing like `requiredTag`.
Unfortunately the json tags don't just apply for yaml un-marshal.
An issue about that here: https://github.com/go-yaml/yaml/issues/424
=> mantle/kola: add yaml struct tags to externalTestMeta struct

src/create_disk.sh
Now that `rdcore zipl` supports `--append-karg` in all streams, use it.
Reverts #3051.
=> Revert "create_disk.sh: go back to using --kargs for `rdcore zipl`"

.cci.jenkinsfile
This roughly matches what we do now in e.g. the FCOS pipeline and a few other places. Otherwise, we may hit against our memory limit and get evicted.
See https://github.com/coreos/coreos-assembler/issues/3118 for more background info.
=> ci: lower CPU requests and allocate 1.5G per CPU

cmd/remote-session.go
This allows the user to specifiy what directory in the remote container we want the working directory (COSA directory) to be. This is useful when you have a particular directory you are in on your local host and you want to use the same directory in the container to keep things symmetrical.
The first use of this will be in the pipeline where we'll set --workdir equal to the Jenkins ${env.WORKSPACE}.
=> cmd/remote-session: support `cosa remote-session create --workdir`

src/cmd-buildextend-live, src/cmd-buildextend-metal, src/cmdlib.sh, src/osmet-pack, src/runvm-coreos-installer
The first commits work towards generalizing `osmet-pack` to support just running the matched `coreos-installer` in a supermin VM. The final patch makes the miniso packing step use it. Its commit message follows.
---
cmd-buildextend-live: pack miniso with composed coreos-installer
Currently, we're packing the miniso using the coreos-installer from the
cosa image. This is not ideal however, because it introduces skew
between the packing side and the unpacking side, which may be older.
Fix this by using the new `runvm-coreos-installer` to pack with the
composed coreos-installer.
For more information, see:
https://github.com/coreos/coreos-assembler/pull/3009
=> Generalize osmet-pack and use it for miniso packing

src/cmd-buildextend-live, src/runvm-coreos-installer
We keep hitting issues in the pipeline with osmet packing triggering the
9p bug. Rework it so that we use virtio-serial instead.
For some reason, the miniso packing step doesn't trigger that same
issue. Possibly because it's only modifying an existing file over 9p
rather than creating a new one? Not sure. Hopefully, we can get off 9p
soon (https://github.com/coreos/coreos-assembler/issues/1812).
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/1294
=> cmd-buildextend-live: use virtio-serial for osmet

internal/pkg/cosash/cosash.go
The `HasPrivileges()` API would hang forever because it didn't have a trailing newline in the command emitted.  This took me some time to figure out.  Let's fix this by auto-injecting a trailing newline automatically to entirely avoid the problem.
=> cosash: Ensure we always inject trailing newline into commands

src/cosalib/gcp.py
Our schema disallows creating a GCP entry without the image field set. Let's just make it clear here that we don't actually support not creating the image in GCP.
=> cosalib/gcp: disallow --create-image=false

cmd/coreos-assembler.go, src/cmd-copy-container, tests/test-cmd-copy-container.sh
This command supports copying images between registries, optionally
converting a manifest list into multiple images tagged by architecture.
This will be used by the pipeline to copy RHCOS images from their
canonical Quay.io location to registry.ci.openshift.org.
=> Add new `cosa copy-container`

cmd/remote-session.go, src/cmd-buildextend-metal
Enable buildextend-secex to run without arguments by making genprotimgvm the default path and adding a default location for the genprotimgvm qcow2 file.
Always mount the volume secex-data in cosa remote sessions.
These changes enable buildextend-secex to be run in the fcos pipeline without changes to the pipeline code.
=> buildextend-secex: Make genprotimgvm the default path

cmd/build-extensions-container.go
We don't want to compress an ociarchive (already a compressed format). Let's set it up to skip compression in the archive stage.
=> cmd/build-extensions-container: set SkipCompression to true for artifact

mantle/cmd/ore/aws/upload.go, src/cosalib/aws.py
If provided the argument will make the image and snapshot public when created.
=> mantle/ore: add `--public` argument to `ore aws upload`

cmd/build-extensions-container.go, src/buildextend-legacy-oscontainer.py, src/buildextend-legacy-oscontainer.sh, src/cmd-buildextend-legacy-oscontainer
We're seeing the classic ENOMEM error from `cosa
buildextend-legacy-oscontainer` when trying to write back the legacy
oscontainer over 9p. Instead, have the supermin VM output the final OCI
archive over virtio-serial.
=> cmd-buildextend-legacy-oscontainer: hack around broken 9p

src/buildextend-legacy-oscontainer.py, src/buildextend-legacy-oscontainer.sh
A few things that came up in review in #3139. But most importantly, add a header at the top to provide more context on this file.
=> buildextend-legacy-oscontainer.py: various minor tweaks

src/cmd-kola
This makes skipping those tests easier in downstream pipelines that call `cosa kola run --basic-qemu-scenarios`.
=> src/kola: Add '--skip-secure-boot' option to skip Secure Boot tests

cmd/build-extensions-container.go, src/cmd-buildextend-legacy-oscontainer
Log when the `extensions-container` artifact was built, and at the very end when `meta.json` was updated. This makes it easier to tell when looking at pipeline output that the command successfully finished.
While we're here, do the same for `cmd-buildextend-legacy-oscontainer`.
=> build-extensions-container: add more logging

mantle/kola/tests/util/containers.go
Starting in glibc 2.33, new hwcaps functionality was added which allows the dynamic linker to load optimized versions of libraries within a new "glibc-hwcaps" directory in the library search path.
The crio and podman tests use `ldd` to get a list of the required shared libraries and copies them into a scratch container. On power9, some of the libraries are symlinked to a specific verison of the optimized libraries. This is problematic inside the scratch container because the binaries are looking for the generic shared library name but cannot find it.
For example a snippet of `ldd /usr/bin/ping` shows:
```
libm.so.6 => /lib64/glibc-hwcaps/power9/libm-2.28.so
```
When the scratch container runs, it cannot find libm.so.6 because only libm-2.28.so is copied into the scratch container.
I found …
=> tests/util: ldd lists files not accessible in scratch container

mantle/cmd/kola/switchkernel.go, mantle/kola/harness.go, mantle/util/repo.go
Reverts coreos/coreos-assembler#3082
See https://github.com/coreos/coreos-assembler/issues/3135
I'm working on a fix for the underlying issue but revert this until it's ready.
=> Revert "mantle: use `os.ReadDir` for lightweight directory reading"

src/cmd-compress
Trying to make it explicit that what was skipped was the compress/uncompress operations.
=> cmd-compress: Clarify operation on Skipped artifacts output

src/cmd-copy-container
We need to support arch peeling even for multi-arch source containers pushed using v2s2. Thankfully, the schema is identical to the OCI schema for our purposes which makes supporting it painless.
Related: https://github.com/coreos/coreos-assembler/pull/2726
=> cmd-copy-container: handle v2s2 manifest lists

src/cmd-generate-hashlist
Rather than a custom `skipcpio | gunzip | cpio` pipeline, we can just
use `lsinitrd --unpack` here. It's simpler, but it also fixes the
command on systems that no longer use gzip for initramfs compression. It
also provides better error-handling (e.g. note that this command wasn't
failing when FCOS switched to zstd). Finally, this also fixes the fact
that `cpio` was run with `-v` which generated a lot of output in
pipeline logs.
For keylime, I'm actually not sure if this makes sense. The list of
initramfs files are hashed and included in the same JSON object keyed by
file path. This means that an initrd file could clash with a real root
file. The schema supports multiple hashes per keys, but the code isn't
appending, just replacing. To be investigated whether keylime really
wants the …
=> cmd-generate-hashlist: use `lsinitrd --unpack` to unpack initrd

src/cmd-build, src/cmdlib.sh, src/image-default.yaml
We had these in the legacy oscontainer for RHCOS, and OKD today hacks them in via a Dockerfile:
https://github.com/openshift/okd-machine-os/blob/0e9fbabbd3363bfc46d9d657bc173666e83e5d18/Dockerfile#L34
We need to carry support for this forward into the new format image, as it's what is used to display the OS version as part of the release image.
=> build: Add image.yaml option to inject OpenShift CVO annotations

src/create_disk.sh, tests/check_one.sh
The conditional always failed since it's not a valid command without the brackets. So the `sysroot.bls-append-except-default` option was not set in builds created by affected cosa versions. This means that on systems provisioned from those releases with a GRUB password set, unprivileged GRUB users can boot non-default GRUB menu entries without entering a password.
To prevent a recurrence of this bug, have the shellcheck test fail if `if $` or `if "$` appears in a shell script.  This will generate false positives if a command is being run indirectly via a shell variable, but we can work around that later if needed.
Fixes coreos/coreos-assembler#3068.  For https://github.com/coreos/fedora-coreos-tracker/issues/1333.
=> create_disk: correctly configure BLS `grub_users` setting (CVE-2022-3675)

cmd/build-extensions-container.go
=> cmd/build-extensions-container: use cosa meta to update meta.json

src/cmd-push-container-manifest
- Check if the digests are already present in the remote manifest and if you want to force or not a new manifest upload
=> Fix #3150 - Make push-container-manifest idempotent

src/cmd-push-container-manifest
- If no metajsonname exists in the meta.json then we get a KeyError so we need to fix that by using `.get()`.
- If no metajsonname entry exists then we need to upload. Right now this won't set upload = True and we end up not uploading anything.
=> cmd-push-container-manifest: fix some logic in digest checking

src/cmd-buildextend-live
Otherwise, code lower down will remove the that `grub.cfg` from the list
of kargs files. This in turn will prevent `coreos-installer iso kargs`
from affecting kargs on UEFI boots.
Fixes https://github.com/coreos/coreos-assembler/commit/3991e6f066e47cf185bc214361de8a8e092b6e7f ("cmd-buildextend-live: always change dir
`EFI/{vendor}/` to correct vendor id").
=> cmd-buildextend-live: update `kargs_json` when moving EFI `grub.cfg`

src/cmd-buildextend-live
This reverts commit 3b199c9c8ce96ad1cdd90b680358e243e45fdaa2.
Both ppc64le and s390x delete things and relied on this bit to update
`kargs_json`. Rather than having duplicate code doing essentially the
same thing this code previously did, let's just revert it.
I think the cleaner approach eventually would be to move the entire karg
file scanning bits to right before we actually write out `kargs.json`,
after we're done all filesystem manipulations.
=> Revert "cmd-buildextend-live: ensure files exist before writing `kargs.json`"

src/cmd-buildextend-legacy-oscontainer
All `meta.json` updates must use the `GenericBuildMeta` API to make sure
that concurrent writes don't race.
=> cmd-buildextend-legacy-oscontainer: don't directly write `meta.json`

cmd/build-extensions-container.go, src/build-extensions-container.sh
This is like 13a6ee49a but for the extensions container where we also
started seeing ENOMEM. We can't trust writing files back over 9p, so
hackily use virtio-serial instead.
=> cmd/build-extensions-container.go: copy ociarchive over virtio-serial

mantle/kola/tests/util/containers.go
Starting in glibc 2.33, new hwcaps functionality was added which allows the dynamic linker to load optimized versions of libraries within a new "glibc-hwcaps" directory in the library search path.
The crio and podman tests use `ldd` to get a list of the shared libraries dependencies and copies them into a scratch container. On power9, some of the libraries are symlinked to versioned filenames of the optimized libraries. This is problematic inside the scratch container because the binaries are looking for the non-versioned library name but cannot find it.
For example a snippet of `ldd /usr/bin/ping` shows:
```
libm.so.6 => /lib64/glibc-hwcaps/power9/libm-2.28.so
```
When the scratch container runs, it cannot find libm.so.6 because only libm-2.28.so is copied into the scratch container.
I …
=> [rhcos-4.11-new] tests/util: ldd lists files not accessible in scratch container

cmd/build-extensions-container.go, cmd/clean.go, internal/pkg/cosash/cosash.go, src/buildextend-legacy-oscontainer.sh
This is necessary so that the `tmp_builddir`s allocated are distinct per
artifact run. Otherwise, running the two commands in parallel will stomp
on each other as they try to use the same dir.
`buildextend-metal` already does this, so we're missing
`buildextend-extensions-container` and `buildextend-legacy-oscontainer`.
I believe this is the reason why `buildextend-extensions-container` has
been failing in the RHCOS pipeline.
I avoided a larger cleanup here around enforcing `IMAGE_TYPE` (probably
should be renamed to e.g. `ARTIFACT`) getting set in `prepare_build`.
That requires more work because we should also make sure to consistently
clean up the dir at the end. Right now, we're relying on the fact that
the same dir gets cleaned and reused each time. We'll also need to
backport this so …
=> Set `IMAGE_TYPE` when calling `prepare_build` from buildextend commands

src/create_disk.sh
9p being 9p, we're hitting ENOMEM when trying to read `platforms.json` in `install_grub_cfg()`. Yet, it works fine at the top of the file when we initially parse the kargs and GRUB cmds. So somehow initial reads do go through. Let's try to leverage this by doing an early copy of the file into the supermin filesystem and then do any further introspections from there. That way, we only access it over 9p once.
Maybe fixes https://github.com/coreos/coreos-assembler/issues/3180.
=> create_disk.sh: naively try to workaround more 9p woes

src/buildextend-legacy-oscontainer.py
@cgwalters suggested yesterday that 9p might be cause of /extensions having a high UID. By debugging the aarch image which works I noticed that the owner for /extensions/* was 1000 and not root. 
Checking the bad x86-64 oci-archive tarballs I see that the the files are also not root as the error says. 
```
do
echo "${filename}" &&  tar tvf "${filename}" |grep "extensions"                                                    
done
./sha256/22a7443c237880d209a90a96d6793e554aa01aab8f8bc4524ef9a8a3b72b0dd0
drwxr-sr-x cosa/1001020000   0 2022-11-07 18:07 extensions/
-rw-r--r-- cosa/1001020000 128 2022-11-07 18:07 extensions/.rpm-ostree-state-chksum
-rw-r--r-- cosa/1001020000 3789004 2022-11-07 18:06 extensions/edk2-ovmf-20220126gitbb1bba3d77-2.el8.noarch.rpm
```
passing `--no-same-owner` to the …
=> buildextend-legacy-oscontainer: extensions owned by UID that untars it

src/buildextend-legacy-oscontainer.sh
We're seeing `cannot allocate memory` errors pretty consistently right now on ppc64le when trying to build the legacy oscontainer. Let's throw some more memory at it for now, which seems to be working.
Here's an example of what the error looks like:
```
2022-11-11 02:08:26,095 INFO - Running command: ['ostree', '--repo=/var/lib/containers/storage/overlay/bc2dc5abbd3fd58d5db95d673ff0c30bde2e6c04963186ab42656499e2ee0023/merged/srv/repo', 'pull-local', '--disable-fsync', '/home/jenkins/agent/workspace/build-arch/tmp/repo', 'fe1abec6cd59ffc02b5ae8f616d1211614ba99e5061dd427e77d4001bfc3403e']
error: Importing 2193179e6b5b4f5040c842f6cc1f309c617e9f5705a642d234a162a681db5b51.file: fstatat(21/93179e6b5b4f5040c842f6cc1f309c617e9f5705a642d234a162a681db5b51.filez): Cannot allocate memory
```
=> bump supermin memory for building legacy oscontainer on ppc64le

mantle/cmd/kola/testiso.go, mantle/platform/metal.go, mantle/platform/qemu.go, mantle/system/exec/exec.go
Right now when QEMU gets killed during a testiso run, the error is:
FAIL: pxe-offline-install (bios + metal) (1m10.277s)
Got EOF from completion channel, coreos-installer-test-OK expected
This is accurate but doesn't hint well enough at the underlying cause.
Rework the two spots in which we wait for virtio-serial strings to also
check if QEMU was killed to provide a better error. E.g.:
FAIL: pxe-install (bios + metal) (34.483s)
QEMU unexpectedly exited while waiting awaiting completion: process killed
Related: https://github.com/coreos/fedora-coreos-tracker/issues/1339
=> testiso: improve error when QEMU is terminated

mantle/platform/api/ibmcloud/s3.go, src/cmd-powervs-replicate
```
commit 3c5516aa88a6fdf79e1fd6546029c5f0b39d7730
Date:   Sat Nov 12 16:26:18 2022 -0500
mantle/platform: fix error handling in ibmcloud/s3 CopyObject
I suspect this was a copy/paste error. `BucketAlreadyOwnedByYou` is
an error reported from createBucket(), which we aren't calling here.
commit 62f9039b63bca5c979b7a9376396de88de489118
Date:   Sat Nov 12 14:54:22 2022 -0500
add support for `cosa powervs-replicate`
All we need to do is symlink to cmd-ore-wrapper.
```
=> add support for cosa powervs-replicate; fix some error handling

src/libguestfish.sh
We've seen errors running buildextend-live on ppc64le:
```
subprocess.CalledProcessError: Command
'['/usr/lib/coreos-assembler/gf-mksquashfs',
'builds/412.86.202211102204-0/ppc64le/rhcos-412.86.202211102204-0-metal.ppc64le.raw',
'/home/jenkins/agent/workspace/build-arch/tmp/buildpost-live/initrd-rootfs/root.squashfs',
'gzip']' returned non-zero exit status 1.
```
It appears to be running out of memory inside the libgestfs VM. This may be because we are setting the smp value high on this particular machine (because it has 128 processors) with the
`coreos_gf set-smp "$(kola ncpu)"` call.
=> libguestfish: bump libguestfs VM memory size for ppc64le

mantle/platform/api/ibmcloud/s3.go, src/cmd-powervs-replicate, src/libguestfish.sh
Includes:
- https://github.com/coreos/coreos-assembler/pull/3194
- https://github.com/coreos/coreos-assembler/pull/3195
=> [rhcos-4.12] backports to get ppc64le working

mantle/platform/api/ibmcloud/s3.go, src/buildextend-legacy-oscontainer.sh, src/cmd-powervs-replicate, src/libguestfish.sh
Contains all or part of:
- https://github.com/coreos/coreos-assembler/pull/3195
- https://github.com/coreos/coreos-assembler/pull/3194
- https://github.com/coreos/coreos-assembler/pull/3191
- https://github.com/coreos/coreos-assembler/pull/3188
- https://github.com/coreos/coreos-assembler/pull/3183
=> [rhcos-4.11-new] more recent backports

Dockerfile
- We need a way to determine the ocp version for the `rhel-8-server-ose` repository configuration. It is needed in order to use a single branch for the internal redhat-coreos repo,
=> [rhcos-4.11-new] Dockerfile: Add repovar for RHCOS repos

Dockerfile
- For old releases, the feature adding support for repovars in rpm-ostree don't work. That's why we are adding it manually.
- It is need to determine the ocp version for repos like rhel-8-server-ose, in order the use a single branch for the internal redhat-coreos repo.
More info:
- coreos/rpm-ostree#4152
=> [rhcos-4.10-new] Dockerfile: Add repovar for RHCOS repos

Dockerfile
- For old releases, the feature adding support for repovars in rpm-ostree don't work. That's why we are adding it manually.
- It is need to determine the ocp version for repos like rhel-8-server-ose, in order the use a single branch for the internal redhat-coreos repo.
More info:
- coreos/rpm-ostree#4152
=> [rhcos-4.9-new] Dockerfile: Add repovar for RHCOS repos

Dockerfile
- It is need to determine the ocp version for repos like rhel-8-server-ose, in order the use a single branch for the internal redhat-coreos repo.
- It should be removed for 4.12 once we get coreos/rpm-ostree#4152 merged
=> [rhcos-4.12] Dockerfile: Add repovar for RHCOS repos

src/cmdlib.sh
On s390x we've seen the supermin VM get the two disks attached to it when running buildextend-qemu mixed up such that the blank 10G disk to be populated is vda and superman fails to start because it can't mount a blank disk. Let's mount via filesystem UUID here.
(cherry picked from commit f9332a5381a954b605ed64adde6934fde4644f9b)
=> [rhcos-4.9-new] cmdlib: mount supermin root disk by UUID

src/cmdlib.sh
On s390x we've seen the supermin VM get the two disks attached to it when running buildextend-qemu mixed up such that the blank 10G disk to be populated is vda and superman fails to start because it can't mount a blank disk. Let's mount via filesystem UUID here.
(cherry picked from commit f9332a5381a954b605ed64adde6934fde4644f9b)
=> [rhcos-4.11-new] cmdlib: mount supermin root disk by UUID

src/cmdlib.sh
On s390x we've seen the supermin VM get the two disks attached to it when running buildextend-qemu mixed up such that the blank 10G disk to be populated is vda and superman fails to start because it can't mount a blank disk. Let's mount via filesystem UUID here.
(cherry picked from commit f9332a5381a954b605ed64adde6934fde4644f9b)
=> [rhcos-4.10-new] cmdlib: mount supermin root disk by UUID

.cci.jenkinsfile, src/cmdlib.sh
Rearrange location of '-maxdepth' option to eliminate 'find' warning
See: https://github.com/coreos/coreos-assembler/issues/3199
=> coreos-assembler/src/cmdlib: rearrange option sequence

build.sh, src/create_disk.sh
Fix https://github.com/coreos/coreos-assembler/issues/3156
=> create_disk.sh: using the target system's grub2-install to install BIOS/PReP bootloader

src/cosalib/build.py
We have this lock to prevent multiple `buildextend-${platform}` from running concurrently. But it gets taken when the `_Build` object is initialized rather than when we actually need to build it.
This clashes with our use of `cosa buildextend-aws --upload`, where the artifact is already built and we just want to upload it. We should be able to support multiple concurrent uploads to different AWS partitions.
Fix this by moving locking to when we actually build the artifact so we don't take the lock during pure upload operations.
Note this is independent of the meta-update lock.
=> cosalib/build: only take artifact lock when actually building it

src/cosalib/cmdlib.py
The expected semantic when merging two e.g. `meta.json` files is that
list keys are merged together, not that one clobbers the other. We
interestingly don't have many list types in the schema, but `amis` is
one of them and hits this right now because we upload to regular AWS and
AWS GovCloud in parallel. (In retrospect, `amis` should have probably
been a `dict` too, with the region as the key name. So a future cleanup
would be to migrate the schema to that model.)
=> cmdlib: merge inner lists when merging dicts

src/cmd-push-container-manifest
When pushing with `--v2s2`, the digests will not match those in the locally-created manifest because the format will be different. So we end up putting invalid digests in the `meta.json`.
Surprisingly, `podman manifest create` does not support the `--format` switch, so we can't create the manifest from the start so we get the right digests.
Fix this by immediately doing a `skopeo inspect` of the remote repo after pushing in v2s2 mode.
=> cmd-push-container-manifest: fix wrong digest in meta.json with v2s2

src/cosalib/aws.py
If we are trying to do replication in govcloud we can't try to find what regions are available by talking to a primary AWS partition endpoint. Let's specify the region to make API calls to for the list-regions call too.
=> cosalib/aws: specify region to talk to for list-regions call

mantle/cmd/ore/aws/upload.go, src/cosalib/aws.py
If provided the argument will make the image and snapshot public
when created.
(cherry picked from commit 44a3f2a)
=> [rhcos-4.11-new] mantle/ore: add --public argument to ore aws upload

mantle/cmd/ore/aws/upload.go, src/cosalib/aws.py
If provided the argument will make the image and snapshot public
when created.
(cherry picked from commit 44a3f2a)
=> [rhcos-4.10-new] mantle/ore: add --public argument to ore aws upload

mantle/cmd/ore/aws/upload.go, src/cosalib/aws.py
If provided the argument will make the image and snapshot public
when created.
(cherry picked from commit 44a3f2a)
=> [rhcos-4.9-new] mantle/ore: add --public argument to ore aws upload

build.sh
The immediate motivation is https://github.com/openshift/release/blob/master/ci-operator/config/openshift/os/openshift-os-master.yaml#L77
For RHEL CoreOS related stuff in particular it's just really useful to have the `oc` binary in coreos-assembler to streamline things like "build a new release image that overrides the OS" etc.
I suspect this would help OKD too.
(cherry picked from commit 71bdff49d18db0f9c961ecd11c720cda2bc1f9e2)
jlebon: Trivial conflict resolution needed. Backporting this because the
pipeline uses `oc` for querying annotations.
=> [rhcos-4.9-new] Install `oc`

cmd/coreos-assembler.go, src/cmd-build, src/cmd-tag
This reverts commit 1f62f5ad9c89ff84acf67ce17bd934f01bea8075.
I find this command useful for debugging issues that require multiple cosa builds.
Let's restore its functionality for now and we can look at rewriting it in Go in the future.
=> RFC: Revert "Remove the `tag` command"

cmd/remote-session.go, docs/cosa.md, docs/cosa/buildextend-secex.md
Document both possible paths for buildextend-secex. Add secex to buildextend-metal artifacts.
=> s390x: Add documentation for buildextend-secex

src/cmd-compress
b60dc1f caused the `cosa buildfetch --artifact=ostree && cosa decompress` path to fail since there was no local ostree repo and no ociarchive that got downloaded. Let's drop the image.json search into the compress path only.
While we are here let's call import_ostree_commit (which also calls
extract_image_json) instead of extract_image_json and add a function
called get_image_json() that helps us iterate over the possible
architectures to find a build with all the pieces necessary to get
the image.json.
=> src/cmd-compress: don't require image.json for decompression

mantle/cmd/kola/options.go, mantle/cmd/kola/qemuexec.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/machine/unprivqemu/flight.go, mantle/platform/qemu.go, src/deps.txt
With this, one can e.g.:
`cosa run --qemu-image fedora-coreos-36*s390x.qcow2 --arch s390x`
This was surprisingly easy.  It's tempting to do *some* full emulation testing for s390x and ppc64le on x86_64/aarch64.
My immediate motivation however is setting up an environment to debug https://github.com/coreos/rpm-ostree/issues/4146
=> qemu: Add support for full emulation

src/cmd-buildextend-extensions
The first arg is the workdir, not the OSTree repo path. The previous version still worked because `import_ostree_commit` treated it as a blank `tmp/` and repopulated the repo, which means we were paying the cost of re-extracting the oscontainer and recompressing all the files during the pull-local into the archive repo.
=> cmd-buildextend-extensions: fix import_ostree_commit arg

mantle/platform/qemu.go
We're troubleshooting performance issues on a ppc64le machine and one of the things that came up comparing what we do to e.g. libguestfs is that the latter just does `-machine pseries,accel=kvm:tcg` whereas we have these extra args.
- `vsmt=8` was added to work around issues with RHEL7 kernels, which is no longer relevant to us
- `cap-fwnmi=off` was added in #1975; it's not clear if we still need it or not. Things seem to work fine without it in manual tests on a ppc64le machine.
Keep `kvm-type=HV` which dates from the introduction of ppc64le support in kola. Looking at the QEMU docs at
https://qemu.readthedocs.io/en/latest/system/ppc/pseries.html#switching-between-the-kvm-pr-and-kvm-hv-kernel-module it ensures that we directly use virtualization support in the CPU.
=> qemu.go: drop `vsmt=8` and `cap-fwnmi=off` qemu args for ppc64le

mantle/cmd/kola/qemuexec.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/qemu.go
Prep for switching the default to UEFI on x86_64 in https://github.com/coreos/coreos-assembler/pull/3159
- Move the logic for default firmware into the constructor
- Fix various places that were overriding it with the empty string
- Return errors instead of panic on unknown firmware
=> mantle: Clean up firmware handling

mantle/platform/api/gcloud/image.go
https://issues.redhat.com/browse/COS-1794
RHEL has supported SEV since 8.4; long term we should figure
out how to share logic with Image Builder here since the
feature set depends on the OS version.
---
=> gcloud: Enable `GVNIC` and `SEV_CAPABLE`

.cci.jenkinsfile, build.sh, mantle/cmd/kola/testiso.go, mantle/platform/metal.go
The `pxe-install` build started failing after grub2-2.06-67.fc37 entered
cosa:
Loading kernel
error: ../../grub-core/fs/fshelp.c:257:file
`/rhcos-413.86.202211301346-0-live-kernel-x86_64' not found.
Possibly the same root cause as
https://github.com/coreos/fedora-coreos-tracker/issues/1352.
Freeze on the previous version for now until we figure this out.
=> build.sh: freeze grub2 to fix PXE + UEFI tests

mantle/cmd/plume/release.go
Focus for FCOS release logic has shifted to the `release` Jenkins job. I
think we could've gone the other way and put more of the release logic
like pushing containers and promoting GCP images into plume. We might
end up there eventually, but right now the pipeline is heavily centered
around doing cosa/mantle calls for specific things, and so it's really
awkward to have this generic `plume release` call that acts like a
blackbox and does multiple things under the hood.
Let's split the `release` command into two:
- `make-amis-public`: to make all the AMIs in a specific release public
- `update-release-index`: to inject new releases into the release index
Then it's really clear what each command does. This will also allow us
to get rid of a hack we're carrying for not calling this command …
=> plume: deprecate `release`, add `make-amis-public` and `update-release-index`

cmd/coreos-assembler.go, src/cmd-buildextend-hashlist-experimental
That way we can call it using the same pattern we call other buildextend commands. It's not a bona-fide artifact (we don't add anything to `meta.json` yet) because it's still experimental. But doing it this way will allow us to easily skip running this on pipeliens where we don't need it.
Motivated by issues we're currently hitting in RHCOS with generating the hashlist being excruciatingly slow. Current theory is that the disk is rotational and the random reads that the command triggers by checking out the full commit and hashing everything is extremely expensive on hard drives. I'd like to skip hashlists in RHCOS for now until we can either move parts of it to tmpfs or ideally move to a builder with better storage.
But regardless, this will also help us clean up in the pipeline how this …
=> cmd-generate-hashlist: rename to buildextend-hashlist-experimental

mantle/cmd/kola/options.go
With the recent changes, we want to use the empty string here for !x86.
=> kola: Don't incorrectly set `bios` by default

mantle/cmd/plume/release.go
In the final command we define, we set the default region to the empty string. This takes effect regardless of the command that actually gets called and so we lose the default value of `us-east-1` on earlier commands.
I think requiring the caller to pass a region would be cleaner, but we can't break the deprecated `plume release` command yet.
Fixes d039e8830 ("plume: deprecate `release`, add `make-amis-public` and `update-release-index`").
=> plume/release: consistently add default region for `--region` switch

src/cmd-buildextend-legacy-oscontainer
These quotes are becoming literal in the final image label. I suspect this code predates e4d5d1ee0 which fixes argument quoting so that spaces survive the `runvm` -> supermin trip without having to add quotes.
This was throwing off `oc adm release new`.
Tested-by: Dusty Mabe <dusty@dustymabe.com>
=> cmd-buildextend-legacy-oscontainer: fix extra quotes in display name

src/cosalib/build.py
Commit 951d2496f makes it so that when building a QEMU variant, we delete the token file as soon as we're done building the artifact. But the `__del__()` function of the `_Build` object still also fired and called `self.unset_token()`. This resulted in a scary but non-fatal error like:
FileNotFoundError: [Errno 2] No such file or directory:
'builds/37.20221121.dev.0/x86_64/.openstack.building'
Fix this by making `self.unset_token()` idempotent by actually unsetting the `_token_file` attribute.
Fixes 951d2496f ("cosalib/build: only take artifact lock when actually building it").
=> cosalib/build: don't call os.unlink() twice

build.sh
The `pxe-install` build started failing after grub2-2.06-67.fc37 entered cosa:
Loading kernel
error: ../../grub-core/fs/fshelp.c:257:file
`/rhcos-413.86.202211301346-0-live-kernel-x86_64' not found.
Possibly the same root cause as
https://github.com/coreos/fedora-coreos-tracker/issues/1352.
Freeze on the previous version for now until we figure this out.
(cherry picked from commit 89f3070c9d1fcbe3400eeb074826d6c12155e111)
jlebon: `rhcos-4.10` is on f35, so I froze on grub2-2.06-11.fc35
instead, which was the grub2 version we were using before
https://bodhi.fedoraproject.org/updates/FEDORA-2022-7ce9378e90
was pushed.
=> [rhcos-4.10] build.sh: freeze grub2 to fix PXE + UEFI tests

src/cmd-buildextend-metal, src/create_disk.sh
This should fix https://github.com/openshift/os/issues/594
Basically I think 9p has a bug where under memory pressure, having it *free* an inode requires allocation, which can fail.
This works around that bug by pulling the ostree-container archive instead, which is a single big file.
Note that this code path does *not* change the semantics at all for the generated disk.  The information about the pulled container is discarded and lost.  Actually making use of the container bits natively is the `deploy-via-container` image option which is still experimental, but will be used when we progress the ostree native containers work.
(cherry picked from commit 0bba897ed419539086b9299e4bbf8ef584eafaa4)
jlebon: Minor conflict resolution. When that commit was made, cosa was
on f35, which matches the …
=> [rhcos-4.10] create_disk: Pull ostree-container over 9p, instead of pull-local

src/secex-genprotimgvm-scripts/runvm.sh
Currently the CI is failling, because it does not use the default /srv workdir. Remove the hardcoded assigment of the variable.
=> s390x/secex: Remove hardcoded workdir assigment in runvm.sh

src/cmdlib.sh
On s390x we've seen the supermin VM get the two disks attached to it when running buildextend-qemu mixed up such that the blank 10G disk to be populated is vda and superman fails to start because it can't mount a blank disk. Let's mount via filesystem UUID here.
(cherry picked from commit f9332a5)
=> [rhcos-4.8] cmdlib: mount supermin root disk by UUID

.cci.jenkinsfile
It doesn't work properly against these rhcos- branches anyway. Let's just limit the testing to building the container and running check and unittest tests.
=> [rhcos-4.8] .cci.Jenkinsfile: drop Fedora CoreOS testing

src/build-extensions-container.sh
Fixes: https://github.com/openshift/os/issues/1080
Needs: https://github.com/openshift/os/pull/1082
=> build-extensions-container: Pass variant as a container build argument

mantle/cmd/kola/options.go, mantle/harness/suite.go, mantle/kola/harness.go
Currently several of our pipeline executes all tests in a single pod. We've seen some cases where we're hitting the 3 hour Prow timeout. This is just not sustainable.
A standard approach to address this problem is test "sharding" or "partitioning".  See for example
https://nexte.st/book/partitioning.html
This implements only hash-based sharding (partitioning); I expect most of our pipelines to use something like
`kola run --sharding hash:n/5`, where we split the test execution across 5 scheduled pods, each choosing a value between 1 and 5.
=> kola: Add support for `--sharding`

mantle/kola/tests/coretest/core.go
Having socket units enabled in particular is standard and expected.  Every one of these should have had an explicit rationale.  In this case, the rationale is probably lost to time.
This fixes a test failure on rhel9.
Closes: https://github.com/openshift/os/issues/1016
=> tests: Stop checking for iscsid being disabled

src/secex-genprotimgvm-scripts/runvm.sh
Currently the CI is failling, because it does not use the default /srv workdir. Remove the hardcoded assigment of the variable.
=> [RHCOS 4.12] secex: Remove hardcoded workdir assigment in runvm.sh

mantle/cmd/plume/cosa2stream.go, src/cmd-generate-release-meta
The bucket layout was changed when migrating the RHCOS pipeline to use the same code as the FCOS pipeline. Using one instance of Jenkins allowed all arches to use the same build ID and therefore share the parent build directory.
Plume is used to update the boot images in the OCP installer so update it to handl the new bucket layout.
=> use new bucket layout for release stream metadata

mantle/kola/tests/rhcos/upgrade.go
The cincinatti graph is used to determine the latest OCP release. It was assumed that only the latest node would have no upgrade path in the graph but that is not the case. When upgrades are blocked, there can be two nodes that no have upgrade path. We need to choose the newest one in the upgrade test.
=> tests: choose latest y-stream versioning for rhcos upgrade

mantle/cmd/kola/options.go, mantle/platform/cluster.go, mantle/platform/platform.go
I'm trying to add some tests for bootc using kola and external tests running in Prow.  I hit the problem that the test containers we built in Prow require a pull secret to access - and we simply don't have an ergonomic way to do deal with that.
I think until now we've been glossing over this problem, but in the fully general case there may be some setup needed to run some of our tests.  (For example, proxy configuration, TLS certificates)
It'd also make sense in some cases to configure hosts to fetch content from local mirrors using e.g. `/etc/containers/registries.conf`.
This general mechanism allows injecting arbitrary Butane (i.e. Ignition) into all tests.
=> kola: Add support for injecting Butane

src/build-deps.txt
- Since it is a small package with only glib as dep, let's add the time package for easily debug cosa related issues.
(cherry picked from commit 1bd7cfedce0fb1003a8efc9a7654f5290c1cd9e2)
=> [rhcos-4.10] Add time package as a build dependence

mantle/cmd/kola/options.go, mantle/platform/cluster.go, mantle/platform/platform.go
Actually for the use case of injecting a secret, I want to use butane's local-file inclusion to avoid quoting or constructing YAML from code, so we need to support accepting Ignition too.
=> kola: Add `--append-ignition` too

src/build-deps.txt
- Since it is a small package with only glib as dep, let's add the time package for easily debug cosa related issues.
(cherry picked from commit 1bd7cfedce0fb1003a8efc9a7654f5290c1cd9e2)
=> [rhcos-4.11] Add time package as a build dependence

src/build-deps.txt
- Since it is a small package with only glib as dep, let's add the time package for easily debug cosa related issues.
(cherry picked from commit 1bd7cfedce0fb1003a8efc9a7654f5290c1cd9e2)
=> [rhcos-4.9] Add time package as a build dependence

mantle/cmd/kola/devshell.go, mantle/cmd/kola/options.go, mantle/cmd/kola/qemuexec.go, mantle/cmd/kola/testiso.go, mantle/cmd/ore/aliyun/visibility.go, mantle/cmd/ore/gcloud/promote-image.go, mantle/cmd/ore/ibmcloud/copy-object.go, mantle/cmd/plume/stream_mirror.go, mantle/kola/tests/rhcos/upgrade.go, mantle/kola/tests/upgrade/basic.go, mantle/platform/api/aliyun/api.go, mantle/platform/api/ibmcloud/s3.go, mantle/platform/api/openstack/api.go, mantle/platform/conf/conf.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/machine/unprivqemu/cluster.go, mantle/platform/qemu.go, mantle/system/copy_test.go, mantle/system/ns/enter.go, mantle/system/ns/exec.go, mantle/util/common.go
The cincinatti graph is used to determine the latest OCP release. It was assumed that only the latest node would have no upgrade path in the graph but that is not the case. When upgrades are blocked, there can be two nodes that no have upgrade path. We need to choose the newest one in the upgrade test.
(cherry picked from commit 48f57ce00e1698c5c22279e8142d81afe9658ca0)
jlebon: trivial conflict resolution in import list
=> [rhcos-4.10] tests: choose latest y-stream versioning for rhcos upgrade

src/build-deps.txt
- Since it is a small package with only glib as dep, let's add the time package for easily debug cosa related issues.
(cherry picked from commit 1bd7cfedce0fb1003a8efc9a7654f5290c1cd9e2)
=> [rhcos-4.12] Add time package as a build dependence

docs/kola/adding-tests.md
The link under description is incorrect and leads to 404 page instead of a correct one.
=> Fixing documentation link misprint

.github/workflows/lints.yml
Fixes [deprecation warnings](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) for Node.js 12.
=> workflows: update actions to current major versions

src/cmdlib.sh, src/compose.sh
The RHCOS pipeline has been intermittently hitting the classic 9p
`ENOMEM` issue during composes when moving the tarball back over 9p:
```
Wrote commit: e8087b3624055851f611a8db47601cf0dc405cd418d39e0fdc305957f805b979
mv: cannot stat '/home/jenkins/agent/workspace/build/tmp/repo/commit.tar': Cannot allocate memory
```
Until we fully move off of 9p, let's add more virtio-serial duct tape so
we don't rely on it at all.
=> cmdlib: completely avoid 9p for OSTree compose

mantle/cmd/kola/options.go, mantle/cmd/kola/qemuexec.go, mantle/platform/machine/unprivqemu/flight.go, mantle/platform/qemu.go
qemu: Remove unused Board parameter
This is a relic of CL we don't use.
---
qemu: Add `--qemu-drive-opts`
This allows passing arbitrary options to the primary disk;
specifically e.g. `--qemu-drive-opts iops_wr=1000` to simulate
slow writes, but allow fast reads to avoid simply booting being
really slow.
---
=> qemu: Add support for IOPs limits && qemu: Add `--qemu-drive-opts`

src/cmd-buildfetch
- The koji-upload cmd also requires information from coreos-assembler-config-git.json to upload to brew. Since it is a small file, let's grab it too.
=> buildfetch: Get coreos-assembler-config-git.json

mantle/kola/tests/crio/crio.go
Something changed in the crio bridge configuration format and this test started failing. It's awkward anyway for us to be digging into crio config internals. Let's just simplify things and ping localhost instead. Yes it's artificial, but the previous test was also pinging the host anyway via the bridge.
Closes: https://github.com/openshift/os/issues/1108
=> kola/tests/crio: just ping localhost

src/cmd-buildextend-metal, src/create_disk.sh
Now that both FCOS and RHCOS ship `platforms.yaml`, we can drop the fallback to the legacy console configuration when that file is missing.
=> Require `platforms.yaml` in config

src/cmd-build
build: Drop reference to `ostree container encapsulate`
We aren't going to use this.
---
build: Add `fedora-coreos.stream` to image labels
From discussion in https://github.com/coreos/zincati/pull/878
related to https://github.com/coreos/fedora-coreos-tracker/issues/1263
---
=>  build: Add `fedora-coreos.stream` to image labels

mantle/cmd/plume/release.go, src/cmd-build, src/cmd-buildfetch, src/cmd-fetch, src/cmdlib.sh
In a multi-arch build, we want to be able to provide some guarantees
that the RPM set across arches is the same (of course, save for any
arch-specific packages). The canonical way to do this is with lockfiles,
but RHCOS currently doesn't have that. However, since we currently build
x86_64 before building the multi-arch variants, what we can do is derive
a lockfile from the x86_64 build and use that in the multi-arch builds.
This patch adds a new "autolock" feature to the `fetch` and `build`
commands to do just that.
Even once RHCOS gets lockfiles, this will also be useful for development
streams where we purposely don't want to maintain lockfiles (such as
rawhide).
This isn't foolproof. Notably if a package is included in more than one
multi-arch build, but not x86_64, it's possible for …
=> cmd-fetch: support "autolocking" from an arch build

src/osmet-pack
This is a manual reimplementation of 2eb3a29b4 to avoid 9p when copying
out the osmet binary. The original commit requires too many preparatory
patches to backport as is, and this smaller patch will be easier to
backport further to older branches.
=> [rhcos-4.11] osmet-pack: hack around 9p using virtio-serial

src/cmd-kola
This has been failing in latest C9S, and we saw it at least similar symptoms in Fedora a while back too in
https://github.com/coreos/fedora-coreos-tracker/issues/1271
While this could use more triage and analysis, let's not block on it; real world use cases are usually at least 8GB of RAM etc.
=> kola: Allocate more RAM for secure boot test

src/osmet-pack
This is a manual reimplementation of 2eb3a29b4 to avoid 9p when copying out the osmet binary. The original commit requires too many preparatory patches to backport as is, and this smaller patch will be easier to backport further to older branches.
(cherry picked from commit 793ad3edb2992154e71f72752bf9d29616406e7a)
=> [rhcos-4.9] osmet-pack: hack around 9p using virtio-serial

src/osmet-pack
This is a manual reimplementation of 2eb3a29b4 to avoid 9p when copying out the osmet binary. The original commit requires too many preparatory patches to backport as is, and this smaller patch will be easier to backport further to older branches.
(cherry picked from commit 793ad3edb2992154e71f72752bf9d29616406e7a)
=> [rhcos-4.10] osmet-pack: hack around 9p using virtio-serial

src/cmd-init
In the usual case, we don't need to change the branch of the yumrepos repo since for RHCOS (the only current user), all repos for all releases are located in the default branch.
However, while reviewing the hotfix process with ART, we realized that it would be useful to support this so that we can have the yum repo definitions live in the same git repo and branch as the hotfix pipecfg definition itself.
=> cmd-init: add support for `--yumrepos-branch`

src/cmd-generate-release-meta
Having secex image as an addition to qemu was triggering:
```
failed to generate asset "Image": multiple "disk" artifacts found
```
So put it to the upper level:
```
"s390x": {
"media": {
"metal": {"artifacts": {...}},
"qemu": {"artifacts": {...}},
"qemu-secex": {"artifacts": {...}}
}
}
```
=> s390x: move 'qemu-secex' artifact from the qemu's additions to the 'images'

src/cmd-init
In the usual case, we don't need to change the branch of the yumrepos repo since for RHCOS (the only current user), all repos for all releases are located in the default branch.
However, while reviewing the hotfix process with ART, we realized that it would be useful to support this so that we can have the yum repo definitions live in the same git repo and branch as the hotfix pipecfg definition itself.
(cherry picked from commit 8b2e2887fa71e6989b908164288e4db7fbfe2e1f)
=> [rhcos-4.11] cmd-init: add support for `--yumrepos-branch`

src/cmd-init
In the usual case, we don't need to change the branch of the yumrepos repo since for RHCOS (the only current user), all repos for all releases are located in the default branch.
However, while reviewing the hotfix process with ART, we realized that it would be useful to support this so that we can have the yum repo definitions live in the same git repo and branch as the hotfix pipecfg definition itself.
(cherry picked from commit 8b2e2887fa71e6989b908164288e4db7fbfe2e1f)
=> [rhcos-4.10] cmd-init: add support for `--yumrepos-branch`

src/cmd-init
In the usual case, we don't need to change the branch of the yumrepos repo since for RHCOS (the only current user), all repos for all releases are located in the default branch.
However, while reviewing the hotfix process with ART, we realized that it would be useful to support this so that we can have the yum repo definitions live in the same git repo and branch as the hotfix pipecfg definition itself.
(cherry picked from commit 8b2e2887fa71e6989b908164288e4db7fbfe2e1f)
=> [rhcos-4.9] cmd-init: add support for `--yumrepos-branch`

src/cmd-generate-release-meta
Having secex image as an addition to qemu was triggering:
```
failed to generate asset "Image": multiple "disk" artifacts found
```
So put it to the upper level:
```
"s390x": {
"media": {
"metal": {"artifacts": {...}},
"qemu": {"artifacts": {...}},
"qemu-secex": {"artifacts": {...}}
}
}
```
Signed-off-by: Nikita Dubrovskii <nikita@linux.ibm.com>
=> [rhcos-4.12] s390x: move 'qemu-secex' artifact from the qemu's additions to the 'images'

mantle/platform/api/aliyun/api.go
We're hitting issues right now with uploading Alibaba images and it's not clear what's going on. Add some more logging.
=> platform/aliyun: log import image task state transitions

mantle/platform/api/openstack/api.go
In cases where the instance enters an error state we shouldn't wait around 10 minutes since it will never go to ACTIVE state. Let's bail out early here.
=> mantle/openstack: detect instance error before 10m timeout

src/libguestfish.sh
It seems like RHEL 9.2 content makes `mksquashfs` require enough memory to make the oom-killer bring down its mighty hammer. There's `mksquashfs` knobs that could help here, like `-mem` and `-processors` but those are not exposed by the libguestfs wrapper. And trying to call `mksquashfs` directly via the `guestfish debug` escape hatch doesn't seem worth the effort.
See also cfa0a43d7 ("libguestfish: bump libguestfs VM memory size for ppc64le") which originally bumped the default on ppc64le.
Closes: https://github.com/openshift/os/issues/1157
=> libguestfish: bump libguestfs VM memory size for  ppc64le to 3G

docs/devel.md
The previous instructions almost worked as is, except that now the
mantle binaries are output in the top level `bin/` directory. Let's
recommend the `make` targets instead to avoid the `cd`.
=> docs/devel: update kola/ore/plume build instructions

cmd/build-extensions-container.go, internal/pkg/cosa/variant.go, src/build-extensions-container.sh
We have a bug in https://issues.redhat.com/browse/OCPBUGS-7275 where we need an updated rpm-ostree on the host in order to make future upgrades work.
This adds basic support for hotfixes, which are RPMs that live in the extensions container, but are intended to be applied-live by the MCD.
They appear in `/usr/share/rpm-ostree/extensions/hotfixes` with the hotfix data (YAML) reserialized to JSON.
=> extensions: Add support for `hotfixes-$variant.yaml`

src/buildextend-legacy-oscontainer.py
Backport of: https://github.com/coreos/coreos-assembler/pull/3188
=> [4.11] buildextend-legacy-oscontainer: extensions owned by UID that untars it 

src/supermin-init-prelude.sh
We hit a case on ppc64le where this just hung forever. Let's add a timeout on it.
And since this is best effort, let's just ignore any errors from the command. If a symlink is missing, we'll just error out with a clearer error down the line anyway.
=> supermin-init-prelude: add timeout on `udevadm trigger --settle` and make non-fatal

build.sh
See https://github.com/coreos/coreos-assembler/issues/3370
=> build.sh: freeze grub2 since it's not working for ppc64le PXE tests

src/create_disk.sh
**create_disk.sh: add more details to secex pubkey user ID**
Include "Secure Execution" since `secex` might be too cryptic. Still
keep `secex` as an easy and stable handle to use. Include the build ID
the key is associated with to make it easier to tell apart multiple
secex keys.
---
**create_disk.sh: don't set an expiry date on secex pubkey**
The default is 2 years, which is much too short for us since we
theoretically need to support arbitrarily old bootimages. We don't want
users to have to e.g. fake the system time to work around this. Anyway,
since the keys are build-specific and will otherwise not be trusted
anywhere else, it seems reasonable to just not have an expiry date at
all.
=> create_disk.sh: add more details to secex pubkey user ID and remove expiration

mantle/kola/harness.go
Apparently it can start with `systemd` or `sd-execu`. I think the difference may be whether the failure happens in the initramfs or the real root. Let's detect both.
Here is an example:
```
Feb 23 21:50:38.240188 /usr/lib/systemd/system-generators/coreos-platform-chrony: line 44: /etc/sysconfig/network: Read-only file system
Feb 23 21:50:38.240195 (sd-execu[1020]: /usr/lib/systemd/system-generators/coreos-platform-chrony failed with exit status 1.
```
=> mantle/kola: fix systemd generator failure detection

mantle/cmd/kola/testiso.go, mantle/kola/harness.go
Fix https://github.com/coreos/coreos-assembler/issues/3177
Refactor testiso tests
- This is an initial step in order to try to merge kola tests and testiso,
much more work will be needed to create a final solution. Nonetheless,
for now let's start by breaking the tests and adding the same denylist
for both.
- kola testiso now allows:
- multipath, 4k, iso, pxe and firmware explicit tests;
- Denylist for the pattern above and by test.
Example:
Add the following in `kola-denylist.yaml` to deny it:
- pattern: iso-as-disk.*
- pattern: iso-as-iso-live-login.*.4k
- pattern: iso-offline-install.ppcfw.*
=> Refactor testiso by breaking tests and adding denylist

mantle/cmd/kola/testiso.go, mantle/kola/harness.go
Backport changes from [#3298](https://github.com/coreos/coreos-assembler/pull/3298)
=> [4.9] Backport: Refactor testiso by breaking tests and adding denylist

src/buildextend-legacy-oscontainer.py
Backport of: https://github.com/coreos/coreos-assembler/pull/3188
=> [4.9] buildextend-legacy-oscontainer: extensions owned by UID that untars it

src/buildextend-legacy-oscontainer.py
Backport of: https://github.com/coreos/coreos-assembler/pull/3188
=> [4.10] buildextend-legacy-oscontainer: extensions owned by UID that untars it

mantle/cmd/kola/testiso.go
- Fix test name, the pxe-online-install.4k.bios test is using the wrong firmware, it should use uefi instead due 4k.
=> [4.9] Fix kola testiso name

mantle/cmd/plume/cosa2stream.go
The stream name in the artifact URL can no longer be derived from the version string because there are streams like 4.12-9.0 and 4.13-9.2. There was already a switch for the stream name but it was not utilized.
=> plume: handle stream name parameter

src/cmd-buildextend-hashlist-experimental
With reference to the latest changes in systemd-253, on executing `cmd-builextend-hashlist-experimental` the default `tmp` dir files configuration automatically creates `/etc/credstore` with secure permissions. We are changing the `find` invocation permissions to access the `/etc/credstore` directory. `find` can't recurse into /etc/credstore, we add `x` so that it can recurse into it. With `+`, find accumulates paths and runs `chmod` once (or batched by the arg limit). But for this, we need it to `chmod` the dir before it tries to recurse into it, so we change to `;`
Fixes : https://github.com/coreos/fedora-coreos-tracker/issues/1429
=> cmd-buildextend-hashlist-experimental: make all directories in tmp checkout readable

docs/kola.md, docs/kola/external-tests.md, docs/mantle/credentials.md
kola.md: add runnning tests on `aws/gcp` examples
---
external-tests.md: fix kola platforms gcp -> gce
This looks confused as we are now using `gcp` as Google Cloud
Platform, but the mantle code is still using old `gce`, will make
them consistent when finish https://github.com/coreos/coreos-assembler/issues/3378
=> kola.md: add runnning tests on `aws/gcp` examples

mantle/cmd/kola/testiso.go
Follow-up to f98481f1f ("kola: Refactor testiso tests").
=> kola/testiso: remove stray '.' at the end of `miniso-install.nm.bios`

mantle/cmd/kola/testiso.go, src/cmd-buildextend-live
This patch series fixes the s390x live ISO so that it can successfully boot, then adds support for Ignition config embedding like on other arches, and then enables some ISO tests, which successfully pass:
```
[coreos-assembler]$ kola testiso -S --no-pxe
Skipping iso-as-disk; not supported on s390x
Skipping miniso-install and miniso-install-nm; not supported on s390x
Testing scenarios: [iso-offline-install iso-live-login]
Ignoring verification of signature on metal image
PASS: iso-offline-install ( + metal) (1m58.02s)
PASS: iso-live-login ( + metal) (10.689s)
```
I've split prep patches into a separate PR: https://github.com/coreos/coreos-assembler/pull/3284. The remaining two commits will stay here. The following is the commit message for the primary one:
---
This patch will allow users …
=> Fix s390x live ISO booting, enable Ignition embedding, enable ISO install tests

mantle/kola/tests/ignition/journaldEntry.go
Enabling `ignition.journald-log` as the test now runs and passes for RHCOS. 
Ref: https://github.com/coreos/coreos-assembler/issues/1173
=> kola: Enable ignition.journald-log for rhcos

src/cmd-virt-install
virt-install: Stop using deprecated `--os-type`
The command now says
`WARNING  --os-type is deprecated and does nothing. Please stop using it.`
---
virt-install: Add `--tpm emulator`
So we can test LUKS etc.
---
=> Misc virtinstall

src/build-extensions-container.sh
We want the `rpm-ostree compose extensions` in the build to use the same CA bundle as what we used for `rpm-ostree compose tree`.
This will allow us to stop disabling yumrepo SSL verification in pipelines where we need to inject a root CA.
=> build-extensions-container: mount `/etc/pki/ca-trust` into build

mantle/platform/api/azure/groups.go
We've been seeing an issue where images cannot be deleted in `kola-azure` jobs because their resource group is still being used. 
Block on resource group deletion so we wait to clean everything up first before proceeding.
Potentially fixes: https://github.com/coreos/fedora-coreos-tracker/issues/1444
=> mantle/platform/api: block on azure resource group deletion

src/build-deps.txt
We can use tmux to create terminal sessions that can be attached to later
Ref: https://github.com/coreos/fedora-coreos-pipeline/issues/803
=> Add tmux to cosa

Dockerfile, build.sh
Fedora by default does not have the Red Hat GPG keys in its keyring. But
we need them available so that we can verify RHEL RPMs we download when
building RHCOS. Interestingly, we get the primary release key right now
in cosa via containers-common, which ships it for its own purposes of
verifying signed RHEL images:
https://src.fedoraproject.org/rpms/containers-common/c/67fd4062
Relying on that however isn't great (that package should probably stop
modifying the public RPM keyring). Let's have our own code code that
copies the keys from `/usr/share/distribution-gpg-keys/redhat` to
`/etc/pki/rpm-gpg`.
=> build.sh: add Red Hat keys to RPM keyring

.github/workflows/lints.yml
Cache dependencies and build outputs by default.
=> workflows: switch to setup-go v4

build.sh, src/cmdlib.sh
Follow-up to dbb8cba85 ("build.sh: add Red Hat keys to RPM keyring").
The keys aren't tracked by any RPM, so supermin doesn't know to copy
it in. Add it manually via `hostfiles`.
This should fix dbb8cba85 when running unprivileged.
=> cmdlib.sh: include GPG keys in supermin VM

src/cmd-buildextend-metal
There is no need to compress the gpg public key, as that only adds more complexity for no gain.
=> ignition-gpg-key: Skip compression of ignition protection gpg key

.cci.jenkinsfile, src/cmd-buildextend-metal
There is no need to compress the gpg public key, as that only adds more complexity for no gain.
cherry-picked from #3413
=> [rhcos-4.13] ignition-gpg-key: Skip compression of ignition protection gpg key

mantle/platform/conf/conf.go
For MergeAllConfigs() let's use an older spec version to enable testing bringup on older Fedora CoreOS releases in the aid of extended upgrade testing. Specifically, now the --append-butane workflow enabled and described in [1] will work.
I chose spec 3.1.0 because it was old enough (F32 nodes support it) and it includes [2], which enabled us to not change using the Resource() type in Ignition, which didn't exist in 3.0.0.
[1] https://github.com/coreos/fedora-coreos-config/commit/2b0fe09b75c7200b538724be97081f035085164d
[2] https://github.com/coreos/ignition/commit/082b45478d18381f959ec578846a19366344268e
=> mantle/platform/conf: use 3.1.0 Ignition spec version for MergeAllConfigs()

docs/building-fcos.md
This allows devs to use the `cosa` bash alias while working with build content covered by a non-default root certificate.
=> docs/building-fcos: add `COREOS_ASSEMBLER_ADD_CERTS`

docs/building-fcos.md, docs/kola.md, docs/mantle/credentials.md, mantle/README.md, mantle/auth/google.go, mantle/cmd/kola/kola.go, mantle/cmd/kola/options.go, mantle/cmd/ore/gcloud/create-image.go, mantle/cmd/ore/gcloud/delete-images.go, mantle/cmd/ore/gcloud/destroy.go, mantle/cmd/ore/gcloud/gc.go, mantle/cmd/ore/gcloud/gcloud.go, mantle/cmd/ore/gcloud/image.go, mantle/cmd/ore/gcloud/list.go, mantle/cmd/ore/gcloud/upload.go, mantle/kola/harness.go, mantle/platform/api/gcloud/compute.go, mantle/platform/api/gcloud/image.go, mantle/platform/machine/gcloud/cluster.go, mantle/platforms.md
Now we are using new platform id `gcp` as Google Cloud Platform, so should eradicate all uses of `gce` from the mantle code base to reduce confusion.
See https://github.com/coreos/coreos-assembler/issues/3378
This PR only includes `cosmetic` changes which will not break auto and pipeline jobs.
=> Change `gce` to `gcp` (cosmetic only)

ci/prow-rhcos.sh
Current setup has broken Prow builds of RHCOS.  Maybe in the future we have both, or at least one with the other opt-in?
Closes: https://github.com/coreos/coreos-assembler/issues/3388
=> ci: Use scos (at least for now)

mantle/cmd/kola/qemuexec.go, mantle/platform/conf/conf.go
I commonly want to `cosa run` a prod image but with auto-updates disabled.
=> run: Add `noautoupdate` ignition fragment

docs/kola.md, docs/kola/adding-tests.md, docs/kola/external-tests.md, mantle/cmd/kola/kola.go, mantle/kola/harness.go, mantle/kola/register/register.go
Add `Description` property, it will show in `json` format if run `kola list --json`.
For example:
```
$ ./bin/kola -E rhcos9/src/config/ list --json | jq -r '.[] | [.Name,.Description]| @tsv'
basic	Tests basic functionality like SSH, systemd services, useradd, etc
coreos.auth.verify	Verifies invalid passwords do not grant access to the system
coreos.boot-mirror	Verifies if the boot-mirror RAID1 flow works properly in both BIOS and UEFI mode
coreos.boot-mirror.luks	Verifies if the boot-mirror+LUKS RAID1 flow works properly in both BIOS and UEFI modes
...	
ext.config.afterburn.platform-id	Verify afterburn works with kernel argument ignition.platform.id ec2(gce).
```
Fix https://github.com/coreos/coreos-assembler/issues/2509
=> kola: add `Description` property for tests

src/cmdlib.sh
Uppercase query tags broke in dnf v4.15.0. There is an upstream PR[[1]] to track restoring support for them, but since the canonical tag names are lowercase, switch to that.
Fixes https://github.com/coreos/rpm-ostree/issues/4368.
[1]: https://github.com/rpm-software-management/dnf/pull/1922
=> cmdlib: use lowercase query tags for `dnf repoquery --qf`

src/cmd-remote-build-container
When checking if a tag exists in a repo, we were using `podman search --list-tags`. However, by default it limits the number of tags to 25.
We could bump the limit, but rather than do that let's just switch to `skopeo inspect` to query the single tag since querying tags is an expensive operation. The downside is that it's somewhat hacky to handle the `ENOENT` case.
=> cmd-remote-build-container: query single tag instead of all tags

mantle/kola/tests/misc/network.go
the rhcos.network tests has been updated to use new scripts that don't run ovs-vctl commands, as the responsibility of this part of configuration has now moved to kubernetes-nmstate [manifests](https://github.com/RHsyseng/rhcos-slb/blob/161a421f8fdcdb4b08fb6366daa8fe1b75cbe095/add-slb-nncp.yaml).
As a result, the following changes are made:
rhcos.network.bond-with-dhcp and rhcos.network.bond-with-restart are removed as they were replaced by the knmstate manifests.
rhcos.network.multiple-nics is updated to only check the captured-macs script.
rhcos.network.init-interfaces-test is added to check the 'init-interfaces.sh` script that supports the kubernetes nmstate manifests.
Fixes https://github.com/coreos/coreos-assembler/issues/3376
Cloned from Ram's PR …
=> mantle/kola: Update rhcos.network tests

src/cosalib/kubevirt.py, src/cosalib/qemuvariants.py, src/runvm.sh
This should allow us to try to build kubevirt in the pipeline again (see https://github.com/coreos/fedora-coreos-pipeline/pull/846).
Also a few other fixes/cleanups in there.
```
commit aec4ea8ac6c210c4295ea364498e95b830265089
Date:   Sat Apr 15 14:01:05 2023 -0400
cosalib/kubevirt: build the kubevirt ociarchive in supermin
Since our pipeline runs unprivileged in OpenShift it won't be able
to do most "container" things, but we do have access to /dev/kvm
so let's just run the `podman build` inside a supermin VM.
commit cf3f7727a2208650bc7287732ca0adb0633588ce
Date:   Sat Apr 15 14:03:26 2023 -0400
src: add runvm.sh
This script just loads cmdlib.sh and executes runvm() with the given
command line arguemnts to …
```
=> cosalib/kubevirt: build the kubevirt ociarchive in supermin

src/cosalib/ibmcloud.py, src/cosalib/qemuvariants.py
buildextend --compress supports gzip as an alternate compression over xz using a key called "gzip" where the value is a bool.  This is now refactored to a key called "compression" with a value of "gzip", "skip", or "zip" (see below).  The "skip-compression" key is no longer applicable.
HyperV images which are used on Windows need to be compressed with zip because xz and gzip are not supported natively.  Added zip support to buildextend and set the hyperv platform compression to "zip".
Supports:
* https://github.com/coreos/fedora-coreos-tracker/issues/1411
* https://github.com/coreos/fedora-coreos-tracker/issues/1421
=> Refactor buildextend compression and add zip

mantle/platform/metal.go, src/cmdlib.sh
In both PXE and ISO tests, we aren't modifying the console settings of
the installed system. This means that the `console.txt` artifact doesn't
contain any data from the installed system when we reboot into it. This
makes debugging failing tests harder.
In ISO tests, we were already dropping a `installer.d/mantle.yaml` file
to customize the install. Extend the file to also include a `console`
key.
In PXE tests, we drive coreos-installer from the `coreos.inst.*` kargs.
There is no way to tell coreos-installer to use a specific console
setting from just kargs, so drop an `installer.d/mantle.yaml` file
containing just the `console` key.
=> platform/metal: set serial console in PXE and ISO tests

mantle/platform/metal.go
Otherwise, coreos-installer will look for a GRUB config even though
one does not exist.[[1]] Anyway, it seems like we don't need to change
anything on s390x since looking at the testiso logs, one can see that
`console.txt` does contain all the logs already. So don't even bother
setting a karg instead.
Follow-up to 694f96fd8 ("platform/metal: set serial console in PXE and
ISO tests").
[1]: https://github.com/coreos/coreos-installer/issues/1171
=> platform/metal: don't set `console` key on s390x

mantle/cmd/kola/kola.go
`kola list --distro rhcos --json` does not work as without `--json`, this is to make the result consistent.
For example:
```
$ kola list -E /srv/rhcos9/src/config/ --distro=rhcos --json | jq -r '.[].Name' | grep binfmt
ext.config.shared.binfmt.qemu --> not expected, should not list here as it is desinged for fcos.
$ kola list -E /srv/rhcos9/src/config/ --distro=rhcos | grep binfmt
--> expected
```
=> kola: support filter for `kola list --json`

src/cmd-build
Generating a tar.gz archive of the config repo uses extra space in the build directory, isn't necessary when the build can be tracked back to an exact commit (when the tree is clean), and can cause issues depending on what extra stuff might be present in the repo.  
Allow the user to optionally work around any of these problems by setting ~~`--no-config-archive`~~ `--skip-config-archive` on the `coreos-assembler build` command, skipping generating the tar.gz.
The output file isn't used anywhere else in the code, and isn't referenced by any other generated files, so it's purely for the benefit of having an exact copy of the config repo in case it was dirty.
I preserved the existing behavior as the default so it's purely an opt-in change.
EDIT: Update what the command-line is for skipping.
=> Add flag to enable(default)/disable tar.gz archive of config repo

mantle/cmd/kola/kola.go, mantle/kola/harness.go
New format is:
```
--allow-rerun-success tags=tag1[,tag2]
```
To allow all tests simply:
```
--allow-rerun-success tags=all
```
Issue: https://github.com/coreos/fedora-coreos-pipeline/issues/842
=> kola: support tags for --allow-rerun-success

src/create_disk.sh
The recommended value for swiotlob is swiotlb=262144. Set the value in the kernel cmdline during image creation.
This fixes https://issues.redhat.com/browse/OCPBUGS-11574
=> OCPBUGS-11574: s390x/Secure Execution: Set swiotlb to recommended value

src/cmd-sign, src/cosalib/fedora_messaging_request.py
There is work in Fedora infra[[1]] to use a Robosignatory queue that supports priority levels so that e.g. our artifact signing messages are handled before RPM signing of mass rebuilds.
Start setting a priority level. Set it to 4 as proposed.[[2]]
[1]: https://pagure.io/fedora-infrastructure/issue/10899
[2]: https://pagure.io/fedora-infrastructure/issue/10899#comment-854645
=> cmd-sign: set priority level on Robosignatory fedmsg

src/cosalib/qemuvariants.py
This is a fixup to 91f478e. Given this it looks like I didn't test the last change, but I swear I did. Must have been an invalid test.
=> cosalib/qemuvariants: fix compression skipping for kubevirt

mantle/kola/harness.go
Recently we saw a test with many soft lockup messages like:
```
[ 4159.779792] watchdog: BUG: soft lockup - CPU#0 stuck for 883s! [kworker/u2:0:10]
[ 4159.780488] Modules linked in:
[ 4159.780787] CPU: 0 PID: 10 Comm: kworker/u2:0 Tainted: G             L    -------  ---  6.4.0-0.rc0.20230502git865fdb08197e.11.fc39.x86_64 #1
[ 4159.780787] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.16.2-1.fc37 04/01/2014
[ 4159.780787] Workqueue: ftrace_check_wq ftrace_check_work_func
[ 4159.780787] RIP: 0010:get_symbol_pos+0x5d/0x140
[ 4159.780787] Code: 63 0c 8d 08 d0 6e a0 85 c9 79 0a 48 f7 d1 48 03 0d 50 c2 5a 01 48 39 cf 48 0f 42 f0 48 0f 43 d0 48 89 f0 48 29 d0 48 83 f8 01 <77> ca 48 85 d2 75 08 eb 4b 48 83 ea 01 74 45 8d 42 ff 48 98 48 63
[ 4159.780787] RSP: 0018:ffffb1970005bb80 …
```
=> mantle/kola: add detection for a kernel soft lockup

mantle/cmd/kola/kola.go, mantle/kola/harness.go, src/cmd-build, src/cmd-build-fast, src/cmd-buildextend-metal, src/cmd-fetch, src/cmd-init, src/cmd-offline-update, src/create_disk.sh
New format is:
```
--allow-rerun-success tags=tag1[,tag2]
```
To allow all tests simply:
```
--allow-rerun-success tags=all
```
Co-authored-by: Dusty Mabe <dusty@dustymabe.com>
Issue: https://github.com/coreos/fedora-coreos-pipeline/issues/842 
(cherry picked from commit 864cece33f7ad2287f2dd2a1d7639fcf6a3efbbe)
=> [4.12] kola: support tags for --allow-rerun-success

src/cmd-push-container-manifest
We need to use .get() here because if the key doesn't exist (which is what we are checking for) then we'll get a KeyError. Fixes a8bfe8f.
=> src/cmd-push-container-manifest: fix allowing for missing architectures

mantle/cmd/kola/kola.go, mantle/kola/harness.go, mantle/test, src/cmd-build, src/cmd-build-fast, src/cmd-buildextend-metal, src/cmd-fetch, src/cmd-init, src/cmd-offline-update, src/create_disk.sh
New format is:
```
--allow-rerun-success tags=tag1[,tag2]
```
To allow all tests simply:
```
--allow-rerun-success tags=all
```
Co-authored-by: Dusty Mabe <dusty@dustymabe.com>
Issue: https://github.com/coreos/fedora-coreos-pipeline/issues/842 
(cherry picked from commit 864cece33f7ad2287f2dd2a1d7639fcf6a3efbbe)
=> [4.11] kola: support tags for --allow-rerun-success

Dockerfile, build.sh
We still need the grub2 pin for the ppc64le issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2173015
Update it to use the latest working f38 build.
=> Bump to Fedora 38

mantle/cmd/kola/kola.go
Future cosa releases support this option. For older releases it's error-prone to backport the feature, so just add a stub.
(cherry picked from commit e6f70bb8b67639a7c5cc117933e8ee663ff01aa4)
=> [4.9] kola: add stub for '--allow-rerun-success <string>'

src/cosalib/kubevirt.py
Downstream RHCOS tooling uses this and it's probably a good idea to have it anyway.
=> cosalib/kubevirt: add the version=buildID label to the kubevirt ociarchive

mantle/cmd/kola/kola.go
We support it for `kola run` so let's support it form `kola run-upgrade` too.
=> mantle/kola: add --allow-rerun-success to `kola run-upgrade`

src/cmd-generate-release-meta
We're not currently setting all the fields of the `kubevirt` image in release metadata. Notably as per earlier discussions[[1]][[2]], we want the `image` field to use a floating tag and the `digest-ref` field to use a digest pullspec.
Determining the floating tag to use is a bit hacky right now, but safe: we find in the list of pushed tags the one which doesn't have a build ID reference to it. If we find multiple, we fail. In the future, we'll probably want to strengthen this to be more explicit.
[1]: https://github.com/coreos/stream-metadata-go/pull/46
[2]: https://github.com/coreos/fedora-coreos-tracker/pull/1172
Closes: #3456
=> cmd-generate-release-meta: fix kubevirt object in release metadata

docs/kola.md, docs/kola/adding-tests.md, docs/kola/external-tests.md, mantle/cmd/kola/kola.go, mantle/kola/harness.go, mantle/kola/register/register.go
Add `Description` property, it will show in `json` format if run `kola list --json`.
Fix https://github.com/coreos/coreos-assembler/issues/2509
This is a cherrypick of 77e3d12e8 with merge conflicts resolved.
=> [rhcos-4.13] kola: add `Description` property for tests

build.sh
4.10 is a bit old at this point.
=> build: bump OCP_VERSION to 4.12

src/cmd-generate-release-meta
This was requested in code review (#3461).
Really, this will be the same for the other container images once we add those to stream metadata as well.
=> cmd-generate-release-meta: add comment about kubevirt container

src/cmd-init
When building RHCOS, we first build for x86_64 on the latest commit
available on the stream's branch. When we trigger builds for other
arches, we want to make sure the same commit of the src config is used,
so we pass `--commit`.
However, `--commit` doesn't reset git submodule, so there's a race
condition where if a submodule bump landed between the x86_64 build and
the multi-arch builds, we would use the latest submodule, rather than
the older one.
Run `git submodule update` to fix this race.
=> cmd-init: run `git submodule update` when `--commit` is used

mantle/platform/qemu.go
Now user can inject kargs:
```
cosa kola qemuexec --firstbootkargs foo --kargs boo
```
https://github.com/coreos/coreos-assembler/issues/2776
=> kola: enable --kargs and --firstbootkargs to work on s390x

src/create_disk.sh
Currently the swiotlb argument is tied to the zipl call during image creation. Move the arg to the ostree call instead so it is written to bls-config and becomes persistent.
=> s390x/Secure Execution: Move swiotlb kernel arg to bls-config

mantle/cmd/kola/options.go, mantle/platform/api/gcloud/api.go, mantle/platform/api/gcloud/compute.go
To run tests on confidential vm on gcp using kola, like:
`kola run -d -p gcp --gcp-image=projects/fedora-coreos-cloud/global/images/fedora-coreos-38-20230507-20-3-gcp-x86-64 --gcp-json-key=/srv/tool/gcp.json --gcp-machinetype n2d-standard-2 --gcp-confidential-vm basic`
Refer to https://github.com/coreos/fedora-coreos-tracker/issues/1457
Note:
Confidential VM supports the N2D series of machine types. See https://cloud.google.com/compute/docs/about-confidential-vm
=> gcp: add `--confidential-vm` option to support confidential vm

src/cmd-fetch
Right now we call `sudo cosa prune --pkgcache` if the pkgcache is higher
than 5G, but to check its size we run `du` unprivileged. This can fail
though if e.g. there's leftover rpm-ostree dirs from an aborted compose
with mode 700 that the user can't read.
Do the size check as root too.
=> cmd-fetch: use `sudo du` for pkgcache size check

mantle/kola/harness.go
This reverts commit a487f53c1fec5ef4a3e77ba717bf6a9da1a82b44.
This has been failing too much and as pointed out by others it doesn't mean the test won't eventually succeed.
What I'd like to do soon is re-instate this check, but allows a test that failed in this way to automatically have `--allow-rerun-success` capability.
=> Revert "mantle/kola: add detection for a kernel soft lockup"

mantle/kola/tests/rhcos/upgrade.go
Originally RHCOS only had one stream named after the OCP major minor version. Around the 4.12 timeframe, the ability to produce concurrent RHCOS versions based on different RHEL content was introduced. This changed the stream name used in the mirror where this test downloads the latest released RHCOS version.
Since the stream name is not in the build metadata, the RHEL version portion of the stream name can only be inferred from the RHCOS version string. This may be cause issues when there is a three digit RHEL version.
=> kola/test: update rhcos upgrade test to new s3 dir

mantle/cmd/kola/testiso.go
Add a check to `nm` tests that configures a Linux bridge via nmstate and confirms that a) the bridge is created and b) its configuration is propagated to the installed system via `--copy-network`.
=> kola/testiso: test nmstate propagation as part of `nm` component

mantle/platform/api/gcloud/compute.go, mantle/platform/machine/gcloud/cluster.go
See https://github.com/coreos/fedora-coreos-tracker/issues/1457
=> gcp: support `additionalDisks` for GCP instance

mantle/platform/platform.go
The `CheckMachine()` call tolerates `systemctl is-system-running` returning e.g. `starting` and `initializing` in addition to the usual `running`. But by design, the command returns a nonzero exit code in those cases.
Since we're explicitly checking the output string against the acceptable states, just ignore the command exit code so that we don't fail if the system is still starting.
Prep for adding a test in which we expect the system to still be `starting`.
=> mantle/platform: allow `systemctl is-system-running` nonzero exit codes

src/cmd-koji-upload
- To store the rpm list in Brew we need to link it to an artifact, let's change it from qemu (1 GB) to the
commitmeta.json (60 KB) due the size.
- The rpm list is also generated from commitmeta.json, what make sense to have it instead.
(cherry picked from commit dd7315e13ef86bd2ec39a74147f58c1ba8ccc100)
=> [rhcos-4.12] koji-upload: Change artifact used to store the rpm list

mantle/kola/tests/ignition/mount.go, mantle/kola/tests/misc/boot-mirror.go, mantle/kola/tests/rpmostree/deployments.go, mantle/platform/api/gcloud/compute.go, mantle/platform/qemu.go, mantle/util/common.go
Refer to @jlebon's suggestion, see https://github.com/coreos/coreos-assembler/pull/3477#discussion_r1198995514
=> util: put `ParseDiskSpec` func to util

mantle/cmd/kola/console.go, mantle/harness/harness.go, mantle/kola/harness.go
This will auto enable rerun success for some failure scenarios including timeouts and some console checks.
=> mantle/kola: Auto enable rerun success in some failure scenarios

src/create_disk.sh
The recommended value for swiotlob is swiotlb=262144. Set the value in the kernel cmdline during image creation.
Docs: https://www.ibm.com/docs/en/linux-on-systems?topic=ki-secure-execution
This fixes https://issues.redhat.com/browse/OCPBUGS-11574
(cherry picked from commit 44e7b4db8bd815a488fb5f6112dae393800eb62e)
s390x/Secure Execution: Move swiotlb kernel arg to bls-config
Currently the swiotlb argument is tied to the zipl call during image creation. Move the arg to the ostree call instead so it is written to bls-config and becomes persistent.
(cherry picked from commit 3bbe77a6dec613f3aacf13b10acc4f109243dcad)
=> OCPBUGS-13942: [RHCOS-4.12] s390x/Secure Execution: Set swiotlb to recommended value

mantle/kola/harness.go
Fix : #3464 
This PR introduces a new check in coreos-assembler that notifies users when running only denylisted tests
eg output:
```
adamobrien@fedora:~/cosa/fcos » cosa kola run podman.workflow                                                                                                                                                                             1 ↵
+cosa:16> podman run --rm -ti '--security-opt=label=disable' --privileged '--uidmap=1000:0:1' '--uidmap=0:1:1000' '--uidmap=1001:1001:64536' '-v=/home/adamobrien/cosa/fcos:/srv/' '--device=/dev/kvm' '--device=/dev/fuse' '--tmpfs=/tmp' '-v=/var/tmp:/var/tmp' '--name=cosa' '-v=/home/adamobrien/cosa/fedora-coreos-config/:/srv/src/config/:ro' '-v=/home/adamobrien/cosa/coreos-assembler/src/:/usr/lib/coreos-assembler/:ro' …
```
=> mantle/kola/harness: allow success if all tests are denylisted

mantle/kola/harness.go
Fix #3479 
This PR introduces a new feature in coreos-assembler that makes sure when individual tests are run they are not bucketed
=> mantle/kola: run individual test without bucketing

docs/kola.md, docs/kola/external-tests.md, docs/mantle/credentials.md, mantle/README.md, mantle/cmd/kola/kola.go, mantle/cmd/kola/options.go, mantle/cmd/kola/spawn.go, mantle/kola/harness.go, mantle/kola/tests/coretest/core.go, mantle/kola/tests/crio/crio.go, mantle/kola/tests/docker/docker.go, mantle/kola/tests/etcd/rhcos.go, mantle/kola/tests/fips/fips.go, mantle/kola/tests/ignition/luks.go, mantle/kola/tests/ignition/qemufailure.go, mantle/kola/tests/ignition/resource.go, mantle/kola/tests/ignition/security.go, mantle/kola/tests/misc/boot-mirror.go, mantle/kola/tests/misc/multipath.go, mantle/kola/tests/misc/network.go, mantle/kola/tests/misc/nfs.go, mantle/kola/tests/rhcos/upgrade.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/machine/qemu/flight.go, mantle/platform/machine/qemu/machine.go, src/cmd-kola, src/cmd-offline-update
mantle/kola/tests: Replace 'qemu-unpriv' with 'qemu'
There is no longer a privileged 'qemu' platform and the 'qemu' and
'qemu-unpriv' platforms are the same.
Let's use qemu everywhere in order to be able to remove all
'qemu-unpriv' usage.
---
docs: Replace 'qemu-unpriv' with 'qemu'
There is no longer a privileged 'qemu' platform and the 'qemu' and
'qemu-unpriv' platforms are the same.
Let's use qemu everywhere in order to be able to remove all
'qemu-unpriv' usage.
---
kola: Remove 'qemu-unpriv' and make 'qemu' the default
There is no longer a privileged 'qemu' platform and the 'qemu' and
'qemu-unpriv' platforms are the same.
=> mantle/kola/tests: Use qemu platform only

mantle/kola/harness.go
With 8166991 we would inadvertently hit the "There are no tests to run because all tests are denylisted" case because we were passing `tests` to `allTestsDenyListed()`, but that didn't make sense because `len(tests) == 0`.
Here we make sure to pass all tests that matched patterns to `allTestsDenyListed()` so we can check against all pattern matching tests.
=> mantle/kola: enhance allTestsDenyListed detection

src/download-overrides.py
This script will be now used in cosa. It makes more sense to move it, to avoid fetching it from the automation repo.
See: https://github.com/coreos/fedora-coreos-tracker/issues/1185
See: https://github.com/coreos/fedora-coreos-releng-automation/pull/176
=> src/download-overrides: Move from fedora-coreos-releng-automation

mantle/kola/harness.go
This variable should have been scoped inside the loop. Outside the loop the `true` value can carry forward and get applied to tests that actually aren't denylisted.
Fixes ac9bd49.
=> mantle/kola: fix scope on denylisted variable

src/cmd-remote-build-container
We started seeing failures today like:
```
+ cosa remote-build-container --arch aarch64 --cache-ttl 24h --git-ref 706fa522579e5b1b95fe0b4cc160b2e70ebf39e1 --git-url https://github.com/coreos/coreos-assembler.git --repo quay.io/coreos-assembler/staging --push-to-registry --auth=****
notice: failed to look up uid in /etc/passwd; enabling workaround
2023-06-21 20:20:48,838 INFO - Translated https://github.com/coreos/coreos-assembler.git#706fa522579e5b1b95fe0b4cc160b2e70ebf39e1 into 706fa52
2023-06-21 20:20:48,838 INFO - Targetting a container image for quay.io/coreos-assembler/staging:aarch64-706fa52
2023-06-21 20:20:49,126 ERROR -  STDOUT:
2023-06-21 20:20:49,126 ERROR -  STDERR: time="2023-06-21T20:20:49Z" level=fatal msg="Error parsing image name …
```
=> cmd-remote-build-container: enhance tag existence check

build.sh
It appears copying to the archives.fedoraproject.org locations for F34 worked correctly. I have opened https://pagure.io/releng/issue/11499 to track getting this fixed.
For now let's point directly to kojipkgs so we can get the correct (latest) packages that were available for F34 before it went EOL.
=> [rhcos-4.9] Temporarily use kojipkgs compose locations for F34 updates repos

src/cosalib/qemuvariants.py
The `hyperv` ZIP has two problems:
- The disk image should be at the root of the ZIP archive, but is nested inside a stack of intermediate directories.
- The disk image should have a `.vhdx` extension, but has `.vhdx.zip` instead.
Fix both issues.
=> Fix member path in `hyperv` ZIP

src/cmd-build, src/create_disk.sh, src/image-default.yaml
This pairs with https://github.com/ostreedev/ostree/pull/2640
It's all off by default (to state the obvious).  But one can do e.g.:
```
$ cat >> src/config/image.yaml << EOF
composefs: true
EOF
```
To test out the fsverity bits, you also want
`rootfs: ext4verity`
More in https://github.com/ostreedev/ostree/issues/2867
=> Add support for composefs

mantle/util/distros.go
Make sure to use the SCOS (aliased to RHCOS) distribution for tests when called on an SCOS disk image.
=> mantle/util/distros: Add case for SCOS disk artifacts

src/cmd-koji-upload
- Add search function to look for builds by id;
- We need this feature to ensure an update was complete successfullyi, and we don't need to reupload it. An example is if some fail occurs in release job.
=> koji: Add search function

src/cmd-koji-upload
koji: Add search function
- Add search function to look for builds by nvr;
- We need this feature to ensure an update was
complete successfully, and we don't need to reupload it. An
example is if some fail occurs in the release job.
(cherry picked from commit https://github.com/coreos/coreos-assembler/commit/0eb550a5fcae30a738b5f19212a1be71e7988560)
_____________________________________________________________
koji: Change release number for NVR
- The release number doesn't need to be random.
It makes things difficult when we need to search for
a NVR name.
- Let's add our "release" version number as release number to
make things easier to search for a NVR when we need to.
Example:
Our full version number is: 413.92.202302162021.0
The …
=> [rhcos-4.11] Backport Brew changes

src/cmd-koji-upload
koji: Add search function
- Add search function to look for builds by nvr;
- We need this feature to ensure an update was
complete successfully, and we don't need to reupload it. An
example is if some fail occurs in the release job.
(cherry picked from commit https://github.com/coreos/coreos-assembler/commit/0eb550a5fcae30a738b5f19212a1be71e7988560)
_____________________________________________________________
koji: Change release number for NVR
- The release number doesn't need to be random.
It makes things difficult when we need to search for
a NVR name.
- Let's add our "release" version number as release number to
make things easier to search for a NVR when we need to.
Example:
Our full version number is: 413.92.202302162021.0
The …
=> [rhcos-4.12] Backport Brew changes

src/cmd-koji-upload
koji: Add search function
- Add search function to look for builds by nvr;
- We need this feature to ensure an update was
complete successfully, and we don't need to reupload it. An
example is if some fail occurs in the release job.
(cherry picked from commit https://github.com/coreos/coreos-assembler/commit/0eb550a5fcae30a738b5f19212a1be71e7988560)
_____________________________________________________________
koji: Change release number for NVR
- The release number doesn't need to be random.
It makes things difficult when we need to search for
a NVR name.
- Let's add our "release" version number as release number to
make things easier to search for a NVR when we need to.
Example:
Our full version number is: 413.92.202302162021.0
The …
=> [rhcos-4.13] Backport Brew changes

src/cmd-koji-upload
koji: Add search function
- Add search function to look for builds by nvr;
- We need this feature to ensure an update was
complete successfully, and we don't need to reupload it. An
example is if some fail occurs in the release job.
(cherry picked from commit https://github.com/coreos/coreos-assembler/commit/0eb550a5fcae30a738b5f19212a1be71e7988560)
_____________________________________________________________
koji: Change release number for NVR
- The release number doesn't need to be random.
It makes things difficult when we need to search for
a NVR name.
- Let's add our "release" version number as release number to
make things easier to search for a NVR when we need to.
Example:
Our full version number is: 413.92.202302162021.0
The …
=> [rhcos-4.10] Backport Brew changes 

src/cmd-buildextend-live
With https://github.com/coreos/coreos-installer/pull/1230 it allows to modify ISO kargs on `s390x`
=> s390x: add kargs embed area

src/cmd-buildfetch
- Allow fetch for non-artifact files such as:
- coreos-assembler-yumrepos-git.json - coreos-assembler-config-git.json - manifest-lock.generated.x86_64.json
- There are occasions where we may need to fetch locks/meta files, `--file` allows it.
(cherry picked from commit 2c8db986cd6525e1cb21fc9d0a9a53d460f04b28)
=> buildfetch: Add file parameter

src/cmd-buildfetch
Backport this change to rhcos-4.12.
``` 
- Allow fetch for non-artifact files such as:
- coreos-assembler-yumrepos-git.json 
- coreos-assembler-config-git.json 
- manifest-lock.generated.x86_64.json
- There are occasions where we may need to fetch locks/meta files, `--file` allows it.
```
Signed-off by: Michael Armijo <marmijo@redhat.com>
cherry-picked from commit: https://github.com/coreos/coreos-assembler/commit/2c8db986cd6525e1cb21fc9d0a9a53d460f04b28
=> [rhcos-4.12] buildfetch: Add file parameter

mantle/platform/api/gcloud/image.go
See: https://github.com/coreos/coreos-assembler/pull/3243
See: https://cloud.google.com/blog/products/identity-security/rsa-snp-vm-more-confidential
Fixes: https://issues.redhat.com/browse/COS-2343
=> gcloud: Enable `SEV_SNP_CAPABLE`

mantle/harness/harness.go, mantle/harness/testresult/status.go, mantle/kola/harness.go
https://github.com/coreos/coreos-assembler/issues/3344
We bubble denylisted tests with 'Warn: true' option as warnings rather than hard failures:
```
kola -p qemu run --parallel 8 ext.config.ntp.* --output-dir tmp/kola
⏭️  Skipping kola test pattern "ext.config.ntp.chrony.dhcp-propagation":
👉 https://github.com/coreos/fedora-coreos-tracker/issues/1508
⚠️  Warning kola test pattern "ext.config.ntp.timesyncd.dhcp-propagation", snoozing expired on Jul 20 2023:
👉 https://github.com/coreos/fedora-coreos-tracker/issues/1508
=== RUN   ext.config.ntp.chrony.coreos-platform-chrony-config
=== RUN   ext.config.ntp.timesyncd.dhcp-propagation
--- PASS: ext.config.ntp.chrony.coreos-platform-chrony-config (27.56s)
--- WARN: ext.config.ntp.timesyncd.dhcp-propagation (90.72s)
cluster.go:162: Error: Unit …
```
=> kola: support denylist Warn feature

src/cmd-koji-upload
- There are cases we can't tag a Brew build after the upload is finished. The tag is a different transction, causing a scenario where we have the Brew build without a tag.
- For this reason we  need to make sure the tag was added in build as expected. If it wasn't, we need to add the tag.
=> koji: Add functions to check/ensure the build tag 

mantle/cmd/kola/testiso.go
The offline detection in our testiso tests is not working properly meaning we are never running offline tests today. Let's fix that here by parsing it properly.
Fixes f98481f.
=> mantle: fix offline detection in testiso tests

mantle/cmd/kola/qemuexec.go, mantle/cmd/kola/testiso.go, mantle/platform/metal.go, mantle/platform/qemu.go
In https://github.com/coreos/fedora-coreos-config/pull/2544 we added a new `coreos.liveiso.fromram` kernel argument to instruct the ISO image to boot completely from memory in order to facilitate installs back to the same disk the ISO was booted from in iso-as-disk mode (i.e. dd the ISO file to a hard drive or partition on a hard drive).
Let's test here that we can boot completely from memory and that /run/media/iso is not mounted.
Currently this doesn't actually do an install to the same disk that we booted from (actually the iso-as-disk tests don't actually do installs at all, but just verify they can boot), but rather just verifies the ISO isn't mounted after the live system boots up, which should be sufficient.
=> mantle/kola/testiso: support testing coreos.liveiso.fromram installs

build.sh
- The Fedora repository was archived, update it to the new location
(cherry picked from commit 31e8b65f9244d358b6da55122f70780601e1fb9a)
=> [rhcos-4.12] build: Update Fedora repository location

mantle/cmd/kola/testiso.go, mantle/platform/qemu.go
After https://github.com/coreos/coreos-installer/pull/1230 being merged this became obsolete
```
$ cosa kola testiso -S --output-dir tmp/kola-testiso-metal
Ignoring verification of signature on metal image
Running test: iso-live-login.s390fw
PASS: iso-live-login.s390fw (13.395s)
Running test: iso-offline-install.s390fw
PASS: iso-offline-install.s390fw (45.608s)
Running test: pxe-online-install.s390fw
PASS: pxe-online-install.s390fw (34.957s)
Running test: pxe-offline-install.s390fw
PASS: pxe-offline-install.s390fw (48.485s)
Running test: miniso-install.s390fw
PASS: miniso-install.s390fw (48.38s)
Running test: miniso-install.nm.s390fw
PASS: miniso-install.nm.s390fw (51.278s)
Running test: miniso-install.4k.nm.s390fw
PASS: miniso-install.4k.nm.s390fw (50.6s)
+ rc=0
```
=> qemu: drop supportsIsoKargs check cause now all platfroms support it

build.sh
The Fedora repository was archived, update it to the new location.
=> [rhcos-4.11] build: Update Fedora repository location

cmd/coreos-assembler.go, mantle/cli/cli.go, mantle/cmd/kola/kola.go, mantle/cmd/kola/options.go, mantle/harness/harness.go, mantle/harness/harness_test.go, mantle/harness/testresult/status.go, mantle/kola/harness.go, mantle/platform/platform.go
```
=== RUN   ext.config.ntp.timesyncd.dhcp-propagation                                                                                                                                                                                            
=== RUN   ext.config.ntp.chrony.coreos-platform-chrony-config                                                                                                                                                                                  
=== RUN   ext.config.ntp.chrony.dhcp-propagation                                                                                                                                                                                               
--- PASS: ext.config.ntp.chrony.coreos-platform-chrony-config (27.13s) 
--- …
```
=> kola: return 77 on warning and use different colors to highlight tests results

mantle/cmd/kola/testiso.go, mantle/platform/qemu.go
Reverts coreos/coreos-assembler#3572
This needs to wait for a new coreos-installer upstream release that includes https://github.com/coreos/coreos-installer/pull/1230 to make it into our RPMs available to us in FCOS/RHCOS.
=> Revert "qemu: drop supportsIsoKargs check cause now all platfroms support it"

mantle/cmd/kola/options.go, mantle/harness/harness.go, mantle/harness/harness_test.go, mantle/harness/testresult/status.go, mantle/platform/platform.go
```
commit 24f81930bfe785251a5b4ba56da77f8f8e294c8a
Date:   Tue Aug 22 23:12:07 2023 -0400
mantle/kola: add --on-warn-failure-exit-77 compat option
It does nothing. This isn't a full backport. We just want to use
the same code in the pipeline for all streams.
commit a3dd717c9753e901b942130beb6e08cbd4231c3e
Author: Nikita Dubrovskii <nikita@linux.ibm.com>
Date:   Fri Jul 28 08:51:42 2023 +0200
mantle/kola: add colors to highlight tests results
Removed the "Warn" parts from the cherry pick to make it compile
because we didn't backport the warn:true stuff here.
(cherry picked from commit a1917162844d5cd4af2b19a0e6a3a0401207f611)
```
=> [rhcos-4.13] backport colors; add compat option

mantle/network/journal/format.go, mantle/network/journal/format_test.go
Same rationale as https://github.com/openshift/installer/pull/7371/commits/948df48aada21e47e9bb0d0a53366871aa21b40a
Before systemd was created, syslog was the dominant Unix logging system.
Later, systemd introduced the journal whose output intentionally exactly matched that of syslog for compatibility.
In systemd, the "unit" is the technical heart of things; yet the syslog output only includes the "syslog identifier" which might or might not look like the unit.
For many of our units that just run shell script, the syslog identifier is just "bash".
This makes it hard to distinguish what's going on.  With this patch the output will change from e.g.:
```
Jul 26 21:15:00 cvrzlbtm-bbcf1-t58lf-bootstrap release-image-download.sh[1995]: …
```
=> mantle/journal: Prefer systemd unit over syslog identifier

mantle/cmd/kola/qemuexec.go, mantle/kola/tests/ignition/qemufailure.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/metal.go, mantle/platform/qemu.go
qemu: Clarify `Memory` as `MemoryMiB`
It's generally a good idea for variable names include their units.
---
qemu: Default to allocating sharable memfd for RAM
This is needed for virtiofs.  Also, unlike the current
README, we want to use a memfd instead of `/dev/shm` because that
might be too small in e.g. a default docker/podman container configuration
which uses 64MiB.
---
=> Qemu memory improvements

src/gf-mksquashfs
This is useful in order to make the dracut FIPS module work. For ostree, we put the kernel stuff in `/boot/ostree` in order to namespace things.  But non-ostree systems tend to use `/boot` directly, and that's what the dracut module is hardcoded to do.
Now we did add some logic in the dracut module which scrapes the grub-injected `BOOT_IMAGE`, except this doesn't work for how we generate the CoreOS Live ISO today because the filenames of the kernel don't include versions etc.
In the case of the Live ISO though we don't really need to "ostree namespace" things, so just hardlink the kernel binary and the hmac file into the traditional places in `/boot`.
We *could* not do this, and do it in our dracut module in the initramfs in fips mode only for the Live ISO, but that'd be way more ugly. …
=> live-iso: Write kernel (and hmac) to /boot too

src/cmd-buildfetch
Keep RAM usage down when using `buildfetch`.  Existing code was downloading the entire file into RAM before writing it to disk, but now that ociarchive files are included that are usually 4-8 GiB that's no longer a good idea.  Lower-RAM systems choke on having too little RAM available to continue operating normally.
This instead sets a somewhat arbitrary 30 MiB chunk limit.  If the server itself is already chunk encoding it will use whatever that says instead, but in a lot (most?) cases the server probably isn't.  
---
It's confirmed to fix a problem with downloading 4 GiB ociarchive files as part of a `buildfetch` on a desktop system with only 8 GB of RAM.  The system was crashing every time during the download due to the OOM killing it for eating too much of the available RAM.  We …
=> HTTP/S `buildfetch` streams in chunks

docs/working.md, mantle/cmd/kola/qemuexec.go, mantle/platform/conf/conf.go, mantle/platform/qemu.go, src/buildextend-legacy-oscontainer.sh, src/cmd-buildextend-metal, src/cmd-run, src/cmdlib.sh, src/compose.sh, src/create_disk.sh, src/deps.txt, src/supermin-init-prelude.sh
qemu: Refactor memory to actually use memfd
The previous change here didn't break anything, but didn't
actually work for virtiofs because we need to actually reference
the device.  It appeared to work for me in local testing
because I accidentally duplicated the logic in the larger virtiofs
PR.
---
mantle/kola: Add `COSA_VIRTIOFS=1` and dual 9p/virtiofs support
In https://github.com/coreos/coreos-assembler/pull/3428 I tried
a wholesale switch to virtiofs.  That's a large change in one go;
it wasn't hard to factor things out so that it becomes a dynamic
choice, keeping the previous 9p support.
This way for e.g. local development one can now
`env COSA_VIRTIOFS=1 cosa run --qemu-image rhcos.qcow2 --bind-ro ...`
Further work can then build on this to switch to virtiofs by default,
and allow …
=> Switch to virtiofs

docs/working.md, src/cmd-build
Continue to de-brand/de-focus ostree, and increase the focus on container technology (for which we happen to use ostree as a backend today).
We already had a new team member ask "how do I have cosa build a container" - when it already does that by default now, it's just not obvious.
=> Make `cosa build ostree` an alias for `cosa build container`

mantle/util/repo.go
This is the only bit in that function that didn't use the const.
=> mantle/util: replace `.cosa` by const `fastBuildCosaDir`

src/cmdlib.sh
[#3460](https://github.com/coreos/coreos-assembler/issues/3460)
Enable RISCV64 architecture in dependencies in order to build coreos on RISCV64 CPU.
Compile and run the test suite against a native RISCV64 board. Luckily, I have a board provided by RiscV International for qualification.
=> Support `cosa build` on RISCV64

mantle/cmd/kola/options.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/machine/qemu/flight.go
I'm trying to debug
`kola run --ssh-on-test-failure ext.rpm-ostree.destructive.container-image` interactively but one problem is that because the test is classified as disconnected, we run qemu with no networking.  This makes it impossible to get remote debug tools.
With this I can `--qemu-bind-ro /usr` to get access to the debug tools in my dev container's `/usr`.  But one needs to manually mount inside the VM, because injecting the mount into the Ignition config in kola is a bit trickier.
For reference it looks like e.g.
`mount -t 9p -o trans=virtio,version=9p2000.L /kola/usr /run/hostusr` in the ssh shell.
=> kola: Add `--qemu-bind-ro`

mantle/kola/harness.go, mantle/kola/tests/ignition/luks.go, mantle/kola/tests/misc/boot-mirror.go, mantle/platform/qemu.go
These two commits together should fix both https://github.com/coreos/coreos-assembler/issues/2725 and https://github.com/coreos/coreos-assembler/issues/3360.
=> Fixes for ppc64le boot mirroring tests

src/cmdlib.sh
This can't really be safe here because we have to ensure that the stuff we write makes it to the filesystem image between a separated fetch + build process.
cc https://github.com/coreos/coreos-assembler/issues/3591 which I suspect this will fix, but didn't verify.
=> cmdlib: Drop unsafety for cache disk

mantle/platform/qemu.go
Missed this when I changed the QEMU drive name to `disk-` instead of `d`.
Fixes 75945a30f ("platform/qemu: strengthen data block device checks").
=> platform/qemu.go: fix device name check when switching bootorder

mantle/cmd/kola/testiso.go
The `iso-offline-install.$firmware` tests are the most common, "default", path that users installing CoreOS will use. Let's keep that test untouched so we make sure we always have coverage for it.
To keep the number of tests the same, combine it with the `4k` test instead, since it differs from the default path in an orthogonal way to how `fromram` differs.
Follow-up to 095510153 ("mantle/kola/testiso: support testing coreos.liveiso.fromram installs").
=> kola/testiso: combine `fromram` test with `4k` instead

mantle/kola/harness.go, mantle/kola/tests/ignition/luks.go, mantle/kola/tests/misc/boot-mirror.go
The aarch64 RHEL8 kernel used a page size of 64K. In RHEL9, this was
lowered to the usual 4K and a separate kernel was added for 64K.
For testing, this now means that we no longer need to double the memory
for aarch64 by default like we do for ppc64le. If we write tests that
make use of the 64K kernel, we can have them request more memory as
needed.
=> Stop bumping aarch64 to 8G automatically

mantle/cmd/ore/aws/upload.go, mantle/platform/api/aws/images.go, src/cosalib/aws.py, src/image-default.yaml
https://github.com/coreos/coreos-assembler/pull/3586 Option 1
=> mantle/aws: add configuration for default VolumeType, IMDSv2 support, and boot mode

mantle/platform/qemu.go
Work around https://gitlab.com/virtio-fs/virtiofsd/-/merge_requests/197
Basically virtiofsd should not be trying to drop capabilities when it can't do so, but we should be able to ask it to stop doing that.
=> qemu: Work around virtiofsd as root in pod

src/cmd-build-fast
This avoids my IDE from transiently seeing a ton of newly added files.  Same motivation as e.g.
https://github.com/coreos/cargo-vendor-filterer/pull/48/commits/aa4a3669704cf491c92158a354ed87156011d493
=> build-fast: Use target/ if available

src/gf-mksquashfs
Fixes the problem that we backported the FIPS test but not the enablement here.
---
This is useful in order to make the dracut FIPS module work. For ostree, we put the kernel stuff in `/boot/ostree` in order to namespace things.  But non-ostree systems tend to use `/boot` directly, and that's what the dracut module is hardcoded to do.
Now we did add some logic in the dracut module which scrapes the grub-injected `BOOT_IMAGE`, except this doesn't work for how we generate the CoreOS Live ISO today because the filenames of the kernel don't include versions etc.
In the case of the Live ISO though we don't really need to "ostree namespace" things, so just hardlink the kernel binary and the hmac file into the traditional places in `/boot`.
We *could* not do this, and do it in our dracut module …
=> [rhcos-4.14] live-iso: Write kernel (and hmac) to /boot too

mantle/kola/tests/misc/boot-mirror.go
Follow-up to https://github.com/coreos/coreos-assembler/pull/3611.
We're still noticing occasional kernel panics with 30s on ppc64le. Bump it to 60s to see if that helps as a last ditch effort before re-disabling these tests until someone has time to dig into it properly.
While we're here, make it specific to ppc64le.
=> kola/tests/boot-mirror: bump sleep hack to 60s

mantle/cmd/kola/devshell.go
Fixes: https://github.com/coreos/coreos-assembler/issues/3613
=> Could save console logs when running with `devshell`

mantle/platform/qemu.go
By default, `virtiofsd` uses seccomp to allow only some syscalls to be proxied from the guest. In the theme of `--sandbox=none`, let's also neuter seccomp filtering for our virtiofs usage; the workloads we run in the supermin/dev VMs are trusted.
Incidentally, this avoids issues like #3635, where some syscalls were accidentally missing from the allow list. In this case, new libostree code[[1]] running in the supermin VM when building the legacy oscontainer calls out to `fstatfs` over virtiofs, which maps to the blocked `fstatfs64` syscall on ppc64le. (I've opened an upstream patch[[2]] to fix this, but we don't strictly need it.)
Closes: #3635
[1]: https://github.com/ostreedev/ostree/commit/ba9c9dedffb953738c609fda6502b9b37ee1b6ba
[2]: …
=> mantle/qemu: neuter virtiofsd seccomp filtering

cmd/remote-session.go
cmd/remote-session: use `--init` instead of `dumb-init`
I'd like to reuse the `cosa remote-session` bits to run non-cosa images
on remote builders. Since it's mostly a wrapper around `podman --remote`,
it has very few requirements on the target image.
One of the requirements I'd like to loosen is on `dumb-init`. That one
is easy to drop since podman has built-in support for making pid 1 an
init-like system. Use that instead.
---
cmd/remote-session: add `--no-{owner,group}` to `rsync` call
It's meaningless to try to retain ownership information between the
builder and the orchestrator pod. We don't really care about that stuff,
so tell `rsync` as much to avoid a bunch of `chown` warnings.
=> cmd/remote-session: use `--init` instead of `dumb-init`

src/cp-reflink
It's been a while since we've disabled reflink. Let's re-enable it for space efficiency and we'll find out if the issue has been fixed or not.
Closes: #941
=> cp-reflink: re-enable it

src/buildextend-legacy-oscontainer.sh
Now that we're on virtiofs, we can undo this hack.
=> buildextend-legacy-oscontainer: stop using virtio-serial hack

src/create_disk.sh
It's the generic fs-independent tool.  No strong motivation, just pointed someone else at this code.
We made the equivalent change in bootc
https://github.com/containers/bootc/pull/102/commits/15de723ac2a9707523967aa4ee5c29875b94baa8
=> create_disk: Use fsfreeze

docs/cosa/run.md, mantle/cmd/kola/qemuexec.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/qemu.go
This is useful when you're nesting VMs and you want the first VM to
be able to access the host. The default host address that QEMU assigns
(e.g. 10.0.2.2, modifiable via the `host=...` netdev knob) doesn't
always work because it's not actually an IP address owned by the host,
but proxied by QEMU itself.
So the source appears to come from localhost, but in some contexts (e.g.
iSCSI), we need the host and the guest to agree that the same IP refers
to the host.
With this, one can start the first VM as usual (e.g. `cosa run`) and the
second VM within with e.g. `cosa run --usernet-addr 10.0.3.0/24` and be
able to talk back to the outer VM via the valid address 10.0.2.15.
To be clear, this can all be done with passthrough QEMU args, so this is
just about making it more convenient.
=> kola/qemuexec: allow changing guest network

mantle/cmd/kola/options.go, mantle/cmd/kola/testiso.go, mantle/kola/harness.go, mantle/platform/platform.go
This switch that allows extending all test timeouts by a given percentage. For example, `--extend-timeout-percentage 50` will increase all timeouts by 50%.
This can be useful in contexts where one is running tests in an environment much slower than the baseline (e.g. without KVM).
=> kola: add `--extend-timeout-percentage` switch

src/grub.cfg
This was in the very first commit that added a GRUB config to this repo. If set, it causes GRUB to pause output if the screen is full of messages until the user presses a key.
That's just incompatible with automation, so nuke it. Any warnings from GRUB should end up in the serial console logs still.
One way this can happen is if booting from multipath. GRUB tries each path in turn until it can read from it. For each tried path that's non- optimized, it'll log a message. So if the device has a large enough number of paths, we can trigger the pager functionality and hang boot.
Probably fixes: https://issues.redhat.com/browse/OCPBUGS-20123
=> grub.cfg: drop `set pager=1`

mantle/cmd/kola/testiso.go, mantle/platform/qemu.go
coreos-installer 0.18.0 was released, so we can enable tests again
This reverts commit 0c9789331e9ad27db64205a11364c94990e276ca.
=> Revert "Revert "qemu: drop supportsIsoKargs check cause now all platfroms support it""

mantle/platform/cluster.go
The new zincati broke the bootc CI.
---
kola: Use centralized drop-in to disable zincati
Just a drive by cleanup.
---
kola: Explicitly mask zincati
The newer zincati errors out instead of retrying; mask it
explicitly.
---
=> kola: Two zincati fixes

pytest.ini, src/cmd-build, src/cmd-buildextend-metal, src/cmdlib.sh, src/cosalib/cmdlib.py
Add option to cmdlib.import_ostree_commit to conditionally exclude the image.json extraction that overwrites.  
Add option to import_ostree_commit wrapper.  
Use import_ostree_commit exclusion of image.json option when importing after creating image.json.
/closes #3616
---
The `buildextend-*` options don't need to add the flag when they call/use `import_ostree_commit_for_build` (or equivalent, some are in Python instead of bash) because they only work if you run them after the `build` has completed.  For the `buildextend-*` then, it works like an enforcement that the `image.json`/`yaml` being used is the one from the original `build` and not one that's been modified since.  
---
An alternative I considered was just making a copy of the `tmp/image.json` before calling …
=> cmd-build: Fix wrong image.yaml after `buildfetch`

Dockerfile, build.sh, src/0001-objectstore-also-mount-etc-containers-for-host-build.patch, src/0002-Mount-boot-from-host-in-host-builder-case.patch, src/cmd-buildextend-metal, src/coreos.osbuild.mpp.yaml, src/deps.txt, src/runvm-osbuild, src/vmdeps.txt
This is proof of concept code with many things hardcoded in the coreos.osbuild.mpp.yaml that need to become more dynamically defined. To use this you can update the image.yaml to add `use-osbuild: true` to force use of this for the `cosa buildextend-qemu` command.
=> add proof of concept for building with osbuild

Dockerfile, build.sh, src/create_disk.sh, tests/test_cosalib_meta.py
Update to f39
Today the ostree CI relies on the buildroot container, cosa and FCOS
all being on the same major.
---
build: Unfreeze grub2
We will just have to stop testing ppc64le with PXE boot.
HOWEVER: An important thing we could try to do going forward
is again do a build of coreos-assembler using RHEL 9 (or CentOS Stream 9).
We're not actually that far away from this last I tried, particularly
using EPEL content.
---
=> Update to f39

src/deps-x86_64.txt, src/deps.txt
The package is noarch, but one of its dep isn't available on s390x.[[1]]
What's new in Fedora 39 is the AwsCli[[2]] change in which the `awscli`
was retired in favour of `awscli2`.
In fact, it turns out even on f38 we were pulling in `awscli2` on all
arches except s390x, where we still pulled `awscli`.
Anyway, cosa itself doesn't use the `aws` CLI but the Python/Go API
libraries directly, which *are* available on all arches.
The pipeline does use it in one spot[[3]], but that's only ever run from
the Jenkins controller, which is x86_64.
So let's just move the dep to be x86_64-specific and make it clear it's
not for cosa itself but for the pipeline and developer convenience.
[1]: https://src.fedoraproject.org/rpms/awscli2/blob/62f260a00a87/f/awscli2.spec#_41
[2]: …
=> deps: drop `awscli`, install `awscli2` on x86_64 only

src/deps.txt, src/resultsdb-report
This script will be used by CoreOS CI to report test results to ResultsDB.
The `resultsdb_conventions` package defines an opinionated way in which results should be structured. It's currently used by openQA.
=> Add `resultsdb-report` helper script

src/deps.txt
This is a new dep of python3-resultsdb_conventions-fedora in f39, but for some reason is undeclared. Add it manually for now until the package is fixed.
=> deps: add python3-fedfind

mantle/platform/metal.go
Work around #3370 as described in:
https://bugzilla.redhat.com/show_bug.cgi?id=2209435#c6
=> metal: add workaround for ppc64le PXE bug

mantle/kola/tests/ignition/qemufailure.go
See: https://github.com/coreos/coreos-assembler/issues/2953
=> tests/ignition: Modify qemufailure to include bootfs test

.devcontainer.json
This allows VSCode or any other devconatainer compliant IDE to automatically spin up a container containing the necessary dependencies.
This uses quay.io/coreos-assembler/coreos-assembler.
Requires the remotecontainer extension to be installed on VSCode [2]
With the flatpak version, set up podman remote first [3]
[1] https://containers.dev/
[2] https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
[3] https://gist.github.com/FilBot3/4424d312a87f7b4178722d3b5eb20212
=> Add support for devcontainers[1]

src/create_disk.sh
Classic missing whitespace bug when building an invocation argument list. Fixes 1c280e775 ("create_disk.sh: opt out of EXT4 orphan_file feature on older targets").
Closes: #3672
=> create_disk.sh: fix bootarg appending

build.sh, mantle/cmd/kola/testiso.go, src/deps.txt, src/kola-junit
There's a lot of friction associated with debugging pipeline kola test
failures. One must scroll a bunch and sift through the output to see
which test(s) failed, and if more information is needed, download the
archived artifacts, extract it, and look for the journal and console
there.
Let's make this easier by outputting JUnit XML files. Jenkins can
natively display test results in that format so it's much easier to see
which tests ran, which ones failed, and their outputs (in the Blue Ocean
view, it's the "Tests" tab which we haven't been using so far).
For space efficiency and to reduce noise, we default to skipping over
passed tests.
=> Add `kola-junit` script to generate JUnit XML files

build.sh
Our pipeline is hitting this for our multi-arch builds. Let's freeze it for now.
See: https://github.com/coreos/coreos-assembler/issues/3678
=> build.sh: freeze on podman-4.7.2-1.fc39

mantle/kola/tests/ignition/qemufailure.go
Fix: https://github.com/coreos/coreos-assembler/issues/3669
=> mantle/test: Modify timeout to resolve coreos.unique.boot.failure issue

mantle/kola/harness.go
While running the kola tests on cloud platforms, our architecture processing would pick the architecture of the host instead of the machine that we were running on. This caused an error where our tests were running on architectures they were not supposed to as per their `architectures:` arg in their test description.
=> kola/harness.go: Update the arch detection for kola tests

mantle/kola/tests/crio/crio.go
Cri-tools 1.29[0] now pre-validates container metadata before running with crictl[1]. The required uid field was missing in our test causing the following failure.
```
load podSandboxConfig: name, namespace or uid is not in metadata \"&PodSandboxMetadata{Name:rhcos-crio-pod-restart-test,Uid:,Namespace:redhat.test.crio,Attempt:0,}\
```
[0] https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.29.0
[1] https://github.com/kubernetes-sigs/cri-tools/pull/1274
Fixes: https://github.com/openshift/os/issues/1407
=> mantle/kola/tests/crio: update tests for new cri-tools

mantle/cmd/kola/testiso.go, src/create_disk.sh
This reverts commit c2d37f4005e0e7c98d24c5f561c149ab7fd4dfce.
We found an issue with this and need to revert it for now: https://github.com/coreos/bootupd/pull/585#issuecomment-1861130612
=> Revert "create_disk: add version field to aleph file"

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go
Here is how the test is set up (copy and pasting the code comment)
// iscsi.go contain the full butane config but here is an overview of the setup
// 1 - Boot a live ISO with two extra 10G disks with labels "target" and "var"
//   - Format and mount `virtio-var` to var
//
// 2 - target.container -> start an iscsi target, using quay.io/jbtrystram/targetcli
// 3 - setup-targetcli.service calls /usr/local/bin/targetcli_script:
//   - instructs targetcli to serve /dev/disk/by-id/virtio-target as an iscsi target
//   - disables authentication
//   - verifies the iscsi service is active and reachable
//
// 4 - install-coreos-to-iscsi-target.service calls /usr/local/bin/install-coreos-iscsi:
//   - mount iscsi target
//   - run coreos-installer on the mounted block device
//   - unmount iscsi
// …
=> iso-install-iscsi : test the "install to an iscsi target and boot it" flow 

mantle/kola/tests/coretest/core.go
Yet another instance of the same problem as https://github.com/coreos/coreos-installer/pull/1203
Motivated by enabling composefs compatibility.
=> tests: Use `findmnt /sysroot` for composefs compatibility

build.sh, src/0001-create-org.osbuild.bootupd-stage.patch, src/0002-stages-bootupd-add-schema-test.patch, src/0003-stages-bootupd-add-test-for-existing-behavior-and-re.patch, src/0004-stages-bootupd-refactor-test-to-test-bind_mounts-and.patch, src/coreos.osbuild.mpp.yaml
There were some updates from code review in [1]. Let's pull them here and also update the mpp.yaml manifest to include the ostree deployment specification.
[1] https://github.com/osbuild/osbuild/pull/1519
=> osbuild: update the org.osbuild.bootupd stage with latest upstream

src/create_disk.sh
Nowadays, the sysroot is mounted read-only anyway, so it seems unnecessary to also slap on an immutable bit. Note this is distinct from the deployment root immutable bit.
Prompted by the fact that when moving to osbuild, we don't want to have to care about this and try to replicate it.
=> create_disk.sh: stop setting immutable bit on sysroot

src/cmd-buildextend-metal, src/create_disk.sh
This patch changes the strategy to create the disk initially with the smaller disk size and then resize the disk at the end if needed to the larger disk size.
This simplifies things a bit since we don't need to pass down the rootfs size into create_disk.sh.
This is prep for some later patches that add osbuild support for dynamically setting the disk size and should simplify things since for both create_disk.sh and osbuild we won't need to pass in the rootfs size.
=> buildextend-metal: rework image size and rootfs size handling

mantle/kola/tests/misc/disk.go
Customers have requested the ability to use a separate disk for
/var/lib/containers as a day two operation.  This is a sanity
test that makes sure this can be done with systemd units as
described in the knowlege base article [0].
[0] https://access.redhat.com/solutions/4952011
=> kola/tests: add /var/lib/containers to separate disk test

src/cmd-buildextend-metal, src/create_disk.sh
In 84ce8dca0, we broke the Secure Execution build because the root filesystem takes up all the remaining space, which leaves no space for the verity partitions that need to come after.
Hack around this by making the root partition end 384M before the end of the disk (that's the sum of the sizes of the verity partitions).
Fixes 84ce8dca0 ("buildextend-metal: rework image size and rootfs size handling").
=> create_disk.sh: fix Secure Execution build

src/fedmsg-broadcast
Right now, when a new build is released, we emit the `stream.release` message once per architecture. But an important part of the release job is to "integrate" all the different arches into a single release. So it seems much more appropriate to have it emit a single fedmsg and in it, we list out all the arches in that release.
Prep for adding a consumer to that message.
=> fedmsg-broadcast: allow many basearches in `stream.release` msg

cmd/remote-session.go
This will allow us to set environment variables in the created container and have them accessible when commands are run.
Part of https://github.com/coreos/fedora-coreos-pipeline/issues/939
=> cmd/remote-session: support passing --env on create

src/cmd-build
Currently, `cosa build` will enable autolocking automatically if it detects that it's completing a multi-arch build on an unlocked stream (as is the case in RHCOS when e.g. building aarch64 after the x86_64 build).
However, there is another use case for autolocking where we want to create a new build, possibly on the same arch, but reuse the previous build as a base lockfile. This comes up in Bodhi testing, where we want to test the Bodhi update with the only change from a known working build being the new packages.
For this, add an explicit `--autolock`, because we don't want `cosa build` to try to auto-detect this.
See also: https://github.com/coreos/fedora-coreos-releng-automation/issues/181
=> cmd-build: add --autolock=VERSION

mantle/kola/tests/ignition/qemufailure.go
See: https://github.com/coreos/coreos-assembler/issues/3670
Reference: https://github.com/coreos/coreos-assembler/issues/3670#issuecomment-1899311359
=> kola/tests: use H.Tempfile() to access logs in coreos.unique.boot.failure

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go
- fix invalid After targets in iscsi services
- rename target container to targetd : Target is a systemd w
ord and seems to interfere with systemd, as running
systemctl stop target shuts the vm down
- add a wait for the targetd container to be ready before configuring the
iscsi target. this should be removed when we ship systemd 254 in rhcos
- Add a healthcheck to the target container and make sure we mark the
systemd service as started only when targetcli is ready to receive
commands. Note this is commented out due to an older systemd version in
rhcos
- update virtserial channel completion channel name to "testisocompletion"
to allow the coreos-test-entered-emergency-target.service to write to
it, as it expects this name.
This will allow correct failure detection rather than waiting for …
=> testiso - iscsi : misc fixes to improve reliability and disable the test for other arches than x86

mantle/kola/harness.go
Before, even though a test had a required tag, explicitly passing a pattern which matched that test name would still include it. I thought that would be convenient, but it makes the logic less predictable. Since we don't use many required tags today, let's instead opt for being more explicit and always actually require the tag.
Motivated by https://github.com/coreos/rpm-ostree/pull/4806#issuecomment-1918756297.
=> kola: really make `requiredTag` required

src/cmd-compress
I implemented this to investigate it as an option for https://github.com/coreos/fedora-coreos-tracker/issues/1660 so figured I may as well post the code up for inclusion.
=> cmd-compress: support zstd as an option

src/gf-set-platform
When we use bootupd to distribute the grub configs using the -with-static-configs option the console file we want to target will be /boot/grub2/30_console.cfg. Let's update gf-set-platform to handle this case.
=> gf-set-platform: handle new path for console settings

mantle/cmd/kola/resources/iscsi_butane_setup.yaml
#3705 should not have been merged :grimacing: 
targetd.sock does not exist, even when running `systemctl enable targetd.socket` so rely on `targetcli` to succeed instead. 
Tested on x86
=> [kola testiso] iscsi - fix test timeout

build.sh, src/0001-stages-copy-allow-copying-from-the-tree.patch, src/cmdlib.sh, src/coreos.osbuild.aarch64.mpp.yaml, src/coreos.osbuild.ppc64le.mpp.yaml, src/coreos.osbuild.s390x.mpp.yaml, src/coreos.osbuild.x86_64.mpp.yaml
Incorporate the platforms JSON file into the container,
as it is essential for our OSBuild requirements.
=> Add platforms JSON as part of the container

build.sh, src/0001-stages-qemu-don-t-use-internal-compression-for-now.patch
We'll open a PR upstream to make compression an option for this stage, but for now we'll just disable it in the code because we know we don't want it: https://github.com/coreos/fedora-coreos-tracker/issues/1653#issuecomment-1928342241
=> osbuild: don't compress in the qemu stage for now

src/cosalib/ibmcloud.py, src/powervs-template.xml
Enhancing visibility of OS's in PowerVS "Volumes" view includes providing additional details. IBM i, for example, names their .raw files "IBMi-\<version>-img.raw".
Task ref: https://issues.redhat.com/browse/COS-2627
=> powervs: make disk name in OVA more descriptive

src/cmd-buildupload, src/cosalib/cmdlib.py
cmdlib.py: retry on EndpointConnectionError exceptions
We hit this recently in the pipeline due to a flake in DNS resolution.
---
buildupload: bump retry period to 5 minutes
It's incredibly expensive when we flake on something at the very end of
the pipeline when uploading S3 artifacts; all the created artifacts are
lost and we have to rerun a whole new build.
We currently only retry for 10 seconds, which makes sense for truly
transient flakes but for uploads, given the stakes, let's be more
resilient to flakes that could take a bit longer to resolve as well,
like DNS resolution issues.
Retry for 5 minutes, with an exponential backoff of up to 20 seconds.
=> Retry on `EndpointConnectionError` exceptions and make uploading retry for longer

build.sh, src/0001-stages-zipl.inst-improve-kernel-initrd-path-resoluti.patch, src/coreos.osbuild.aarch64.mpp.yaml, src/coreos.osbuild.ppc64le.mpp.yaml, src/coreos.osbuild.s390x.mpp.yaml, src/coreos.osbuild.x86_64.mpp.yaml, src/create_disk.sh
This reverts commit f5677a36abbe506a04210d15f2151c9056bef454.
We're seeing some related problems. Tracked in
https://github.com/coreos/fedora-coreos-tracker/issues/1667
=> Revert "set sysroot.bootprefix true in OSTree config"

src/cmdlib.sh
Since we are now using the cache qcow2 for OSBuild we need it to be a little large to handle those duties as well as the tree compose ones. I'd like to drop the cache, but hit some trouble there; see https://github.com/coreos/coreos-assembler/pull/3720.
=> cmdlib: bump size of cache qcow2

tests/containers/README.md, tests/containers/tang/Containerfile, tests/containers/tang/README.md, tests/containers/targetcli/Containerfile, tests/containers/targetcli/README.md
Some kola tests requires additionnal images to work (isci, luks). Until now these images have been maintained by indivudual members of the coreOS team. This moves the images under coreos-assembler for sharing the maintainership, and allowing the images to be periodically rebuilt.
See https://github.com/coreos/fedora-coreos-tracker/issues/1639#issuecomment-1875832998
=> host containerFiles needed for kola tests

src/cmd-build
I'd like to move out the versionary script from this repo and into the
FCOS source config repo. This is prep for adding a versionary script to
openshift/os also and unlabeling the versionary knob in the pipeline as
a hack.
=> cmd-build: add `--versionary` switch

src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml, src/osbuild-manifests/platform.gcp.ipp.yaml
This file isn't yet being used today but holds an OSBuild image definition for the gcp platform. It currently has the x86_64 kernel arguments for console so it is only included in coreos.osbuild.x86_64.mpp.yaml for now.
=> osbuild: add gcp platform artifact definition file

build.sh, src/0001-util-Add-bls-module.patch, src/0002-Add-coreos.platforms-stage.patch, src/cmdlib.sh, src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml
This is a backport of the upstream PR [1]. This helps us close one of the final gaps when it comes to features needed for OSBuild [2]. It updates the GRUB console settings and also will update kernel arguments based on the platforms.json content.
[1] https://github.com/osbuild/osbuild/pull/1589
[2] https://github.com/coreos/fedora-coreos-tracker/issues/1654
=> osbuild: backport and use coreos.platforms stage

src/gf-set-platform
In https://github.com/coreos/fedora-coreos-tracker/issues/1671 we decided to have this file be `console.cfg` and not `30_console.cfg`.
=> gf-set-platform: use console.cfg for preferred file name

mantle/platform/metal.go
grub2-2.06-116.fc39 update is now available and it fixes the issue. The pxe-online-install.ppcfw & pxe-offline-install.4k.ppcfw tests pass without the workaround.
Ref: https://github.com/coreos/coreos-assembler/issues/3370
=> metal: drop workaround for ppc64le PXE bug

mantle/kola/tests/crio/crio.go, mantle/kola/tests/misc/network.go
This is part of https://github.com/openshift/os/pull/1445.
Those tests are all actually testing OCP components. In the new model,
they should be run against an OCP layered image instead. Add a tag on
them so that we'll be able to run them separately.
=> kola/tests: add `openshift` tag to OCP tests

src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml, src/runvm-osbuild
- Allow osbuild image creation to use also a container image. It is part of the efforce to enable podman to use osbuild.
=> osbuild: Allow deploy via container image

src/cmdlib.sh
- The current cache size for aarch64 during podman-related operations is insufficient. We require a method to expand it to enable the utilization of the cache feature by runvm. By implementing this, we can conveniently adjust the cache size as needed by passing it as a parameter.
=> runvm: Implement optional cache size parameter for 'runvm'

src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml, src/runvm-osbuild
Those fields are optional so we need to use `getconfig_def` instead.
Fixes b74e2f986 ("osbuild: Allow deploy via container image").
=> runvm-osbuild: fix handling of `container-(repo|tag)` fields

mantle/kola/harness.go
The `--oscontainer` switch takes either a filename to an OCI archive or a pullspec. In neither case is a cosa directory required.
Fixes b8f70e813 ("kola: handle `--oscontainer` imperatively") which mistakenly cargo culted that bit from surrounding code.
=> harness: don't require cosa build for `--oscontainer`

src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml
Fixes 38df1c876 ("osbuild: only deploy a single deployment").
=> osbuild: fix ppc64le mpp syntax error

src/cmdlib.sh
We switched to ext4 to get away from using reflinks (see [1]) but the problem was actually specific to XFS. It's now been fixed upstream in [2], but we need to wait for it to get back backported to stable branches. Let's switch to BTRFS for now so we can still get the space savings of reflinks, while avoiding the reflink bug in XFS.
[1] https://github.com/coreos/coreos-assembler/issues/3728
[2] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4b2f459d86252619448455013f581836c8b1b7da
=> cmdlib: use BTRFS for the cache2.qcow2

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go
The nested VM that start off the iscsi disk is started through cosa kola quemuexec. Adding a serial device to get the console output logged to a dedicated file.
It can be useful to diagnose issues on initramfs setup
=> testiso/iscsi: Add a logfile for the nested VM console

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/kola/tests/ignition/luks.go
Point test that requires containers to use images from the coreos-assembler org.
Following https://github.com/coreos/coreos-assembler/pull/3727
See  https://github.com/coreos/fedora-coreos-tracker/issues/1639
This will fail CI until this one is in :  https://github.com/coreos/fedora-coreos-pipeline/pull/959
=> use container images from coreos-assembler org

mantle/cmd/kola/resources/iscsi_butane_setup.yaml
The console output of the nested VM get truncated on slow prow CI Increase the baudrate to the max value through coreos-installer console arg
=> testiso/iscsi-install Increase nested VM console baudrate

mantle/cmd/kola/testiso.go
Openshift prow have a default limit to 3GB for the kola job
so reduce the memory for this test to 2GB, local testing showed
no issue with this amount.
See https://github.com/openshift/os/pull/1461#issuecomment-2022503532
=> testiso/iscsi: reduce VM memory to 2GB

src/cmd-prune
In cases where we buildfetch a bunch of different builds if we then want to clean some of them up easily with `cosa prune` it will fail if there is no ostree repo at `tmp/repo`. Let's just check and if nothing is there then let's not try to clean it up.
=> cmd-prune: don't prune the ostree repo if non-existant

src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml
We were blocked by https://github.com/coreos/fedora-coreos-tracker/issues/1647 but the 6.9 kernel series doesn't appear to have the same problem. The 6.8 kernel does have the problem but our kernel filenames in stable releases of Fedora (i.e. not `rawhide`) won't be long enough to trigger the bug so we should be able to safely remove this since `rawhide` has moved on to 6.9 rc kernels.
This should be the final piece to close out
https://github.com/coreos/fedora-coreos-tracker/issues/1667
=> osbuild: set sysroot.bootprefix=true for aarch64 too

docs/cosa/run.md, mantle/platform/qemu.go
Add a customizable WWN option for kola DiskSpec to have reliable links under `/dev/disk/by-id/`. With this change kola qemuxec can be run like: `kola qemuexec -D "5G:channel=scsi,wwn=007"`
Resulting in the following links:
```
[core@localhost ~]$ rpm -qa sg3_utils
sg3_utils-1.48-1.fc40.x86_64
[core@localhost ~]$ ls -l /dev/disk/by-id
total 0
lrwxrwxrwx. 1 root root  9 Apr  5 09:05 scsi-30000000000000007 -> ../../sda
lrwxrwxrwx. 1 root root  9 Apr  5 09:05 wwn-0x0000000000000007 -> ../../sda
```
This is motivated by recent changes in sg3_utils [1] which removed some udev links.
At least one of our tests [2] relying on this started failing. This patch was suggested by @jlebon [3]
[1] https://listman.redhat.com/archives/dm-devel/2023-March/053645.html
[2] …
=> kola/qemuexec: Add a wwn option for scsis disks

src/cmd-kola
Otherwise this breaks `kola list --json` because now the output is no longer purely just JSON and so e.g. piping it to `jq .` fails.
=> cmd-kola: print `kola` command on stderr instead

mantle/cmd/ore/aws/upload.go, src/cosalib/aws.py
Add the ability to add tags to AMIs when running `ore aws upload` with `--tags` flag.
Can be used as:
`cosa buildextend-aws --tags foo=bar,abc=xyz` or
`cosa buildextend-aws --tags=foo=bar --tags=abc=xyz`
=> Add tags argument parser for aws_cli

mantle/kola/tests/ignition/mount.go
On s390x, the disk order is not guaranteed, so it is better to use unique labels instead of `/dev/vda`.
Additional fixes:
- Fix spelling mistake.
- Do not assign variable name for unused argument.
=> kola/tests: Use disk label for mount partitions test

mantle/kola/harness.go, mantle/kola/tests/coretest/core.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/qemu.go, src/cmd-kola
`cmd-kola` has non-conformed basic kola tests. These tests do not benefit from the supporting functionality around kola test's such as denylisting or other functionality. reduce `cmd-kola` and conform the basic kola tests.
fixes https://github.com/coreos/coreos-assembler/issues/3418
This is a small rework on an already existing; but stale pr. Cherry-picked and made a few touches.
=> mantle/kola: copy basic tests into formal kola workflow

mantle/kola/tests/coretest/core.go
The original `--basic-qemu-scenarios` only ran it on x86_64. In testing, it seems to work at least in aarch64 so we might as well test it. On s390x, it seems like QEMU doesn't support it. On ppc64le, the bootloader complains it's "Not a bootable device!".
Follow-up to 6775ab126 ("mantle/kola: copy basic tests into formal kola
workflow") and 2f8a427b5 ("tests/basic: fix basic tests on multi-arch").
=> tests/basic: only run basic.nvme on x86_64 and aarch64

src/deps.txt, src/manifest_graph
Follow-up of https://github.com/coreos/fedora-coreos-config/pull/2940
Now that I think of it, i could add `pip install anytree` in the dockerfile so anyone could do 
`podman run -v .:/mnt/:z --rm quay.io/coreos-assembler/coreos-assembler /srv/src/manifest_graph /mnt/manifest.yaml`
opinions ?
=> Misc: add a small tool to graph manifest includes

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go
This test simply changes the kargs from `rd.iscsi.firmware=1` to `netroot=iscsi...` at the coreos-installer step.
This will ensure we support no-ibft installations.
Partial fix for https://github.com/coreos/fedora-coreos-tracker/issues/1651
=> testiso/iscsi add a manual test for no iBFT cases

Dockerfile, build.sh, src/cmdlib.sh, tests/containers/tang/Containerfile
Some of our upstream CIs (ostree, rpm-ostree) require cosa and FCOS to be on the same release. Ideally we'd fix that but there's details there and we want to move cosa anyway.
=> Bump to Fedora 40

src/cmd-buildfetch
This will allow one to just specify a build ID rather than having to specify both the stream the build was on and the build ID. This will make things slightly more convenient for things like coreos-builds-bisect [1] where the called script now doesn't need to know what stream we are on.
[1] https://github.com/coreos/fedora-coreos-config/pull/2961
=> cmd-buildfetch: allow derivation of stream from Build ID

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go, mantle/platform/qemu.go
=> add iscsi+multipath test; add some improvements to test strategy

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go, mantle/platform/qemu.go
Backports for:
- https://github.com/coreos/coreos-assembler/pull/3757
- https://github.com/coreos/coreos-assembler/pull/3789
=> [rhcos-4.16] add more iscsi test cases

src/cmdlib.sh, src/secex-genprotimgvm-scripts/runvm.sh
This is a follow-up to 79b15c89d ("cmdlib.sh: go back to using `tail -F`
for command output") which was subsequently reverted.
To summarize, it seems like in QEMU v8.2 (in f40), the guest sometimes
would hang when writing over virtio-serial if the device is hooked up to
the QEMU's stdio.
In testing, removing the `<&-` hack to close QEMU's stdin fixed it for
CoreOS CI but not Prow:
https://github.com/coreos/coreos-assembler/pull/3785#issuecomment-2087342748
I think I've narrowed it down to CoreOS CI (i.e. Jenkins) allocating a
tty and Prow not. When stdin is not a tty, QEMU would immediately gets
EOF if it tries to read anything. I'm not sure exactly what happens, but
I think the virtio-serial hang is linked to this (even though there's no
userspace code in the guest trying to read from …
=> cmdlib.sh: feed `/dev/zero` as qemu stdin

mantle/cmd/kola/testiso.go
This is required by ostree.
This sometimes worked I think because `ignition-remount-sysroot.service` has no ordering against `ostree-prepare-root.service` and so they'd race. But really, we shouldn't rely on that Ignition unit.
See also: https://github.com/coreos/coreos-assembler/pull/3789#discussion_r1591769493
=> testiso: add rw karg to iSCSI multipath test

Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=2278652 was fixed and the fedora container base image now has the container=oci environment variabled defined.
=> build: Remove ENV container=oci

ci/prow-rhcos.sh, mantle/cmd/kola/devshell.go
Commit 7b07ffe8a dropped the `-o json` argument to the journalctl query that the devshell code uses to monitor system boot and know when to SSH. Fix this by re-adding the argument but only for devshell so that the default is still to output traditional logs (as in the testiso case).
Fixes 7b07ffe8a ("mantle/platform/qemu: drop json formatting from journal output").
=> devshell: fix journal monitoring

src/cmd-buildextend-metal
Now all of our streams are ready to be switched to OSBuild and RHCOS latest streams are also switched over. Let's make it the default so we don't have to set COSA_USE_OSBUILD=1 any longer. This also has the side effect of making all CI run with OSBUild now too.
=> osbuild: make building with OSBuild the default

src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml
Otherwise, SCOS would get e.g. the `orphan_file` and `metadata_csum_seed` settings from FCOS which will break things.
This is of course a short-term fix to get CI working again (e.g. once c10s is up, it should probably match the current Fedora settings). The longer-term fix is tracked at:
https://github.com/coreos/coreos-assembler/issues/3801
=> osbuild manifests: treat SCOS and RHCOS the same

docs/cosa/run.md
Fixes: https://github.com/coreos/coreos-assembler/issues/3804
=> docs/cosa/run: Add PXE with Shim and UEFI Secure Boot example

Dockerfile, build.sh
Let's drop this since we are no longer patching. We can pull it from git history if we need it again.
=> build.sh: drop patch_osbuild()

docs/cosa/run.md
See: https://github.com/coreos/coreos-assembler/pull/3806#discussion_r1610257571
Fixes: 0b53c4e78 docs/cosa/run: Add PXE with Shim and UEFI Secure Boot example
=> docs/cosa/run: Remove unneeded rootfs in UEFI SB GRUB config

src/cmd-compress
Based on the discussion in https://github.com/coreos/fedora-coreos-tracker/issues/1660 level 10 seems to give us a good speedup versus size tradeoff.
=> cmd-compress: use level 10 for zstd compression

src/cmd-build
The env variable is pulled in runcompose_tree() from cmdlib.sh : https://github.com/coreos/coreos-assembler/blob/28a26d61315ed596112b35ff69325310e7f9b8e1/src/cmdlib.sh#L556
=> cmd-build: Fix env variable name for rpm-ostree extra args

src/cmd-buildextend-live, src/cmd-buildupload, src/cmd-compress, src/cmd-koji-upload
Notably, this includes the `CacheControl` and `ACL` args. This allows us to more easily cross-check the value of those keys with what was set higher up in the stack.
=> cmd-buildupload: log all args passed to `s3_client.upload_file`

src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml
Fix changes done in https://github.com/coreos/coreos-assembler/pull/3808 causing the podman CI to fail https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-podman-os/63/
=> osbuild: Fix changes done causing podman to fail 

build.sh
FCOS PXE 4K UEFI tests started to fail after edk2-ovmf updated to
20240524-1.fc40. Freeze on the previous version temporarily.
See also: https://github.com/coreos/coreos-assembler/issues/3815
Co-authored-by: Jonathan Lebon <jonathan@jlebon.com>
=> build.sh: freeze edk2 to fix PXE 4K UEFI tests

build.sh
We temporarily froze updates to that version due to issues with the FCOS PXE 4K UEFI tests. You can check it here: https://github.com/coreos/coreos-assembler/pull/3816. 
Now that we had a update to fix it, we can switch back to the latest version.
=> build.sh: remove edk2-ovmf version freeze 

docs/working.md
We really need to make it easier for people unfamiliar with our build processes but asked to investigate and fix some bugs to get up and running as fast as possible. They don't need to try to learn all the cosa intricacies and concepts.
Let's have an all-in-one section that, yes, overlaps with other sections, but presents in a condensed way the minimum someone needs to know to fix bugs.
Obviously, this should be shared more with fedora-bootc documentation in the future. The ergonomics are not quite there yet however (related discussions in https://github.com/containers/podman-bootc/pull/28 and https://gitlab.com/fedora/bootc/tracker/-/issues/2).
=> docs: add section for package maintainers and contributors

ci/prow-rhcos.sh, src/cmd-buildextend-metal
Now all of our streams are ready to be switched to OSBuild and RHCOS
latest streams are also switched over. Let's make it the default so
we don't have to set COSA_USE_OSBUILD=1 any longer. This also has
the side effect of making all CI run with OSBUild now too.
(cherry picked from commit 4d94dc35e6886bbc4fd03f285108e8d774def505)
4.16 is already being built with `COSA_USE_OSBUILD` today.
Cherry-picking this will allow us to clean up our pipecfg.
=> [rhcos-4.16] osbuild: make building with OSBuild the default

src/cmd-sign
This is useful to try to recover a build which was interrupted due to signing issues. E.g. the signing request went out, but Robosignatory never answered and the build failed.
If Robosignatory is eventually fixed and drains its queue, it eventually does sign the build. So we then can just pick up where we left off and verify the signatures and flip their ACLs.
=> cmd-sign: add `--verify-only`

docs/cosa/run.md, docs/kola/external-tests.md, mantle/cmd/kola/options.go, mantle/cmd/kola/qemuexec.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/platform/api/gcloud/compute.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/machine/qemu/flight.go, mantle/platform/platform.go, mantle/platform/qemu.go, mantle/util/common.go
kola/qemu: add support for simulating 512e disks
It's come up a few times now that we need to dig into 512e-specific
behaviours (most recently in OCPBUGS-35410). Let's add a knob for this
in the qemu platform just like the one we have for 4Kn.
---
kola: add support for `primaryDisk` key
Just like we have `additionalDisks`, add a new `primaryDisk` key which
takes the same "diskspec" format. This immediately unlocks all the same
knobs available to additional disks to the primary disk itself from
external tests.
E.g. with this, we can now migrate multipath tests to external tests
that use `primaryDisk: 20G:mpath`.
My immediate motivation for this however is to be able to use the
new `512e` disk option from an external test as part of fixing
OCPBUGS-35410.
=> kola: add support for simulating 512e disks and add support for `primaryDisk` key 

mantle/platform/platform.go
Instead of separately logging which systemd units are stuck and failed, just include it in the fatal error we eventually emit when we print the test failure. Otherwise it's not easy to match logged messages with failures when running tests in parallel.
=> kola: include failed/stuck systemd units in error message directly

src/cmd-buildfetch
We would write `args.url` to that file, but the user may not have passed an explicit `--url` and instead let the default logic kick in. Instead, just consistently use `args.url` in the fallback code so that the later logic that writes it out will pick up on it.
=> cmd-buildfetch: populate `tmp/builds-source.txt` when not passing `--url`

mantle/kola/tests/ignition/kdump.go
This test setups two machines to test if kdump successfully exports vmcore to a SSH destination.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1753
---
This is not fully functional yet but ready for review I think. 
The test setup works ( i can see the logs created on the remote machine) but kola fails the test somehow : 
```
[coreos-assembler]$ /mnt/cosa/bin/kola run kdump.crash.ssh --ssh-on-test-failure 
⏭  Skipping kola test pattern "fcos.internet":
👉 https://github.com/coreos/coreos-assembler/pull/1478
⏭  Skipping kola test pattern "podman.workflow":
👉 https://github.com/coreos/coreos-assembler/pull/1478
=== RUN   kdump.crash.ssh
/home/core/crash/10.0.2.15-2024-07-04-15:55:25/vmcore-dmesg.txt
/home/core/crash/10.0.2.15-2024-07-04-15:55:25/vmcore.flat
--- FAIL: …
```
=> tests: add a remote kdump test

src/cmd-buildextend-metal, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/runvm-osbuild
This fixes `No space left on device` issue when building CoreOS with `secex`
=> build: pass roofs size to osbuild

mantle/kola/tests/ignition/kdump.go
This increase the log verbosity by quite a log but is often required to investigate kdump failures.
Logs are discared on successful tests so it's not a big deal.
=> tests/kdump.crash.ssh: increase logging verbosity

cmd/coreos-assembler.go, src/cmd-cloud-prune, src/cmd-container-prune, src/cosalib/cmdlib.py
This script calls skopeo delete to prune image from a remote directory. Currently only supports the FCOS tag structure.
If no duration is specified, no image will be pruned.
See https://github.com/coreos/fedora-coreos-tracker/issues/1367 See https://github.com/coreos/fedora-coreos-pipeline/pull/995
=> cmd/prune-containers: add a GC script for containers images

OWNERS
This allows us to have permissions to `/override` prow tests among other things. Currently this is limited to repo administrator but an OWNERS files makes it easier to manage.
This is a copy from the openshift/os repo.
=> prow: add a OWNERS file

src/cmd-cloud-prune, src/cosalib/cmdlib.py
We have few older [builds](https://builds.coreos.fedoraproject.org/prod/streams/testing-devel/builds/builds.json) for testing-devel which had .dev in their buildIDs. Fixed the version check to accept that. Also fixed the return statement in `delete_gcp_image` to return empty errors list instead on returning None as needed.
=> Minor fixes: Fix FCOS version check and error return for `delete_gcp_image`

src/cmd-container-prune, src/cosalib/cmdlib.py
For `testing-devel` stream, we have older [builds](https://builds.coreos.fedoraproject.org/prod/streams/testing-devel/builds/builds.json) with `.dev` (non-int) as `tag_stream`. Lets allow that to pass as a valid FCOS version through `parse_fcos_version_to_timestamp_and_stream`
=> Allow `.dev` as `tag_stream` for fcos version

src/cmd-cloud-prune
Removed `gcp-project` switch since we can access that from `meta.json`. Also, handle AWS ami/snapshot pruning to take either of the resources to be deleted than needing both of them.
=> src/cloud-prune: remove `gcp-project` switch and handle no snapshot scenario

Dockerfile, build.sh, src/0001-stages-dmverity-make-device-objects-more-generic.patch
This carries https://github.com/osbuild/osbuild/pull/1845 until it gets to Fedora so that we can unbreak secex builds.
=> Add osbuild patch for org.osbuild.dmverity stage fix

src/cmdlib.sh
As part of the work to move the live ISO generation to osbuild and
allowing custom live ISOs, we can't have the process rely on the src
config repo. *Everything* needs to be part of the oscontainer.
The only thing `cmd-buildextend-live` needs from there is the `live/`
directory. Do like the platform stuff and shove that under
`/usr/share/coreos-assembler`.
Note we don't actually change `cmd-buildextend-live` here to copy what
it needs from there; that whole command will be gutted and rewritten to
just wrap the new osbuild code anyway.
=> cmdlib: bake src config's `live/` directory in compose

src/cmdlib.sh
Michael and I were debugging an issue where `cosa build` would still break on:
```
+ killall rofiles-fuse
+ /sbin/fstrim -v /home/jenkins/agent/workspace/bootupd_PR-706/cache
/home/jenkins/agent/workspace/bootupd_PR-706/cache: 17.8 GiB (19084976128 bytes) trimmed
+ mount -o remount,ro /home/jenkins/agent/workspace/bootupd_PR-706/cache
mount: /home/jenkins/agent/workspace/bootupd_PR-706/cache: mount point is busy.
```
which I think is because the rofiles-fuse processes haven't fully been cleaned up yet. Let's just spam retry to remount the cache, but notify the user when this is happening for more visibility.
We should be able to revert this once we fix
https://github.com/coreos/coreos-assembler/issues/3848
=> cmdlib.sh: keep trying to remount after killall hack

src/cmd-cloud-prune
Updated the process to ensure that the build order is preserved while keeping all existing builds from the `builds.json` file intact. Previously, we were updating the builds on the wrong index after we switched the enumerating of the builds in reversed order which caused us to lose the builds and also switched the ordering.
Additionally, added a step to print the updated `builds.json` during a dry run, which will be uploaded in non-dry run mode. Also, the previous version of `builds.json` is now backed up to the S3 bucket as `builds.json.bak`.
=> cmd-cloud-prune: Fixed cloud pruning and backed up `builds.json`

src/cmd-cloud-prune
For consistency, keep the json indent level to 4 and also, only compare the respective JSON's build data instead of the whole file since we do update the timestamp in the `builds.json` in `save_builds_json`.
=> cmd-cloud-prune: Fix indent-level for builds.json and compare only `builds` data

mantle/platform/machine/qemu/cluster.go
Currently, we only try to detect if the QEMU process exited by actually `wait()`ing for it in the `kola qemuexec` path. We should do it in the kola testing path as well so that it's easy to tell if e.g. it was killed while the test was running.
Note this doesn't actually stop the test early if QEMU exited. That would require some tricky wiring into the harness. But at least what it prints helps diagnose the issue when we see the test time out on SSH. And the QEMU process won't just hang there as defunct.
=> platform/qemu: detect if QEMU process exits unexpectedly

mantle/util/retry.go
- Print a little more information about the errors that are encountered on each try.
- Print out the amount of time remaining until the timeout occurs.
=> mantle/util/retry: add more debug statements to retry function

src/cmdlib.sh
This reverts commit ba45b296ec11734bafcae7728915016f17137a3d.
=> Revert "cmdlib: workaround rofiles-fuse mounts leaking"

mantle/platform/api/aliyun/api.go
There is a history of failure copying images to other regions on aliyun. Upstream code that calls the CopyImage code more than once will get a DuplicateImage error when an image with the same name already exists. Let's check to see if the image name exists in the region before attempting to copy the image to the region and return early if it already exists.
=> aliyun: make image replication idempotent

mantle/cmd/kola/kola.go, mantle/platform/api/azure/api.go, mantle/platform/api/gcloud/compute.go, mantle/platform/machine/azure/cluster.go, mantle/platform/machine/esx/cluster.go
In db803c3 we add support for ConfidentialType but we made it so that we always execute this code where we don't want to do that if the user didn't specify any ConfidentialType for GCP.
The way the code is now we can't run any GCP tests on non confidential instances.
```
failed to create instance "kola-dd144aac7413f66c85e9":
Does not support confidential type , should be: sev, sev_snp
```
=> mantle/platform/gcloud: fix confidential compute check

mantle/cmd/kola/options.go, mantle/platform/api/gcloud/compute.go, mantle/platform/api/gcloud/image.go
This requires the IDPF guest OS feature flag to be set when creating GCP images and also a TERMINATE maintenance policy and hyperdisk storage. With this change, after uploading a disk you can then test with kola with something like:
```
cosa kola run -p=gcp                        \
--gcp-json-key=key.json                 \
--gcp-project=project                   \
--gcp-machinetype=c3-highcpu-192-metal  \
--gcp-zone=us-central1-c basic
```
Related to https://github.com/coreos/fedora-coreos-tracker/issues/1794
=> mantle/gcp:  support c3 metal instance types

mantle/cmd/kola/options.go, mantle/platform/api/gcloud/compute.go, mantle/platform/api/gcloud/image.go
This requires the IDPF guest OS feature flag to be set when creating GCP images and also a TERMINATE maintenance policy and hyperdisk storage. With this change, after uploading a disk you can then test with kola with something like:
```
cosa kola run -p=gcp                        \
--gcp-json-key=key.json                 \
--gcp-project=project                   \
--gcp-machinetype=c3-highcpu-192-metal  \
--gcp-zone=us-central1-c basic
```
Related to https://github.com/coreos/fedora-coreos-tracker/issues/1794
(cherry picked from commit 93e6e82c984763f8ebcca59865cb9bae9f005bcd)
=> [rhcos-4.17] mantle/gcp:  support c3 metal instance types

mantle/kola/tests/upgrade/basic.go
We've been seeing this fail a lot more on AWS recently and we think it's because we're bumping up into this timeout. The truth is that we're not just waiting for a reboot here, but actually waiting for zincati to select the upgrade, for rpm-ostree to deploy it, finalize and reboot. Given all that I can see why this might be bumping up into the limit.
```
=== RUN   fcos.upgrade.basic
=== RUN   fcos.upgrade.basic/setup
=== RUN   fcos.upgrade.basic/upgrade-from-previous
=== RUN   fcos.upgrade.basic/upgrade-from-current
--- FAIL: fcos.upgrade.basic (495.26s)
--- PASS: fcos.upgrade.basic/setup (204.18s)
cluster.go:162: real	0m0.045s
cluster.go:162: user	0m0.006s
cluster.go:162: sys	0m0.012s
--- FAIL: fcos.upgrade.basic/upgrade-from-previous (122.05s)
basic.go:347: failed waiting for machine …
```
=> mantle/kola: increase reboot wait time for fcos.upgrade.basic

mantle/cmd/kola/options.go, mantle/cmd/kola/qemuexec.go, mantle/kola/tests/ignition/luks.go, mantle/kola/tests/util/luks.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/machine/qemu/flight.go, mantle/platform/qemu.go
This kola test is crucial for verifying the security of CEX
hardware-based LUKS encryption on root volume. It guarantees that the
encrypted device employs protected keys to encrypt and decrypt the
volume.
This is essentially testing the enablement done in
https://github.com/coreos/ignition/pull/1820.
To run this, it needs to be on a system with a CEX device with
passthrough enabled and the device's UUID exposed via KOLA_CEX_UUID. See
also https://github.com/coreos/fedora-coreos-pipeline/pull/1010.
Co-authored-by: Jonathan Lebon <jonathan@jlebon.com>
=> kola: add IBM CEX device test for the s390x build

mantle/cmd/kola/testiso.go, mantle/platform/metal.go
And also have it apply to the installed target machine (not just the
install boot) such that we can try to get more information about
failures in the first boot (Ignition boot) of that machine.
=> mantle/kola: drill COSA_TESTISO_DEBUG into platform/metal

build.sh, src/0001-hacks-for-coreos-selinux-issues.patch, src/0001-stages-coreos.platform-use-shutil.copy.patch, src/0001-stages-selinux-don-t-require-file_contexts-if-labels.patch, src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml, src/vmdeps.txt
We have a few issues right now where files in our images
don't have any selinux context (i.e. end up unlabeled_t).
Here we workaround the hidden mountpoints issue [1] with
a patch to OSBuild to hardcode some chcon calls. We
workaround the "bunch of files under /sysroot are unlabeled"
issue [2] by backported a proposed upstream change to
the org.osbuild.selinux stage [3] and then using it to
explicitly set the context on the root of the tree to
`root_t`. We also add a fix [4] for another issue where
'/boot/coreos/platforms.json' would end up with the
wrong label.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/1771
[2] https://github.com/coreos/fedora-coreos-tracker/issues/1772
[3] https://github.com/osbuild/osbuild/pull/1889
[4] https://github.com/osbuild/osbuild/pull/1888
=> workaround selinux issues with osbuild

src/cmd-cloud-prune
Extend the garbage collection to the `images` for the builds. We will prune all the images apart from what is specified in the `images_keep` list for each stream in `gc-policy.yaml`
=> cmd-cloud-prune: Prune images for builds

docs/kola/external-tests.md, mantle/cmd/kolet/kolet.go, mantle/kola/cluster/cluster.go, mantle/kola/harness.go, mantle/kola/tests/ignition/resource.go, mantle/kola/tests/ignition/security.go, mantle/kola/tests/upgrade/basic.go
I'm writing a test that verifies files on the filesystem in CoreOS machinges match the SELinux policy. Placing kolet in `/var/home/core/kolet` with a `bin_t` context is a violation of this. Let's use /usr/local/bin/. This has the side effect of the file having the right `bin_t` context as soon as it is created.
=> mantle: move kolet binary location to /usr/local/bin

src/cmd-cloud-prune
This exception was not supposed to be added there since that check was just added to make sure there isn't any build
artifacts in `meta.json` top-level keys that is in unsupported list. So far, we only prune aws and gcp. There are many top-level keys that are not artifacts-related so this check would throw the exception when not needed.
=> cmd-cloud-prune: remove the unneeded exception

mantle/kola/tests/upgrade/basic.go
I was in here trying to understand the test a bit more since we have been seeing some flakiness lately and decided to do some cleaning up. See individual commit messages.
=> mantle/kola: rework fcos.upgrade.basic

mantle/cmd/ore/aws/delete-image.go, src/cmd-cloud-prune
Added a check for when the `snapshotID` is None in the `RemoveBySnapshotTag` function. If `snapshotID` is None, the function now attempts to extract the snapshot ID from the associated AMI. If the AMI cannot be described, it is logged as pruned, and the function returns without error.
=> ore/aws: Handle missing `SnapshotID`

src/cmd-cloud-prune
Updated `prune_build` function to handle S3 object deletion using boto3's s3_client. Replaced resource-based object deletion with client-based approach using `list_objects_v2` and `delete_objects`. Added handling for cases where no objects are found under the specified prefix. Improved error handling for missing keys (NoSuchKey) and other potential ClientErrors.
=> Refactor `prune_build` to use `s3_client` for S3 object deletion

mantle/platform/qemu.go, src/libguestfish.sh, src/libguestfs-ppc64le-wrapper.sh
008e04c322e99cdb769cdb36c010810c8625376b and a6d7bbbadc8f091afbd6732b18fd4aa5a25c4590 added and used the `libguestfs-ppc64le-wrapper.sh` in order to address some failing tests on ppc64le. Using a Power10 machine with KVM enabled, tests are passing with this script removed. There was a successful test run with: `cosa kola run --tag '!reprovision'`
If we are going to use p10 for CI going forward, I think we can remove this script entirely. Otherwise, we will have to distinguish between p10 and not p10 or possibly implement a better way than relying on using `uname -r ` output searching for `el7`.
Related to issue https://github.com/coreos/coreos-assembler/issues/2473
=> [ppc64le] Remove P8 and P9 hack so tests pass for Power10

mantle/kola/tests/ignition/kdump.go
This way we have good coverage of most-used kdump features. Some context on the NFS kdump configuration https://github.com/coreos/fedora-coreos-tracker/issues/1729
=> tests/ignition/kdump: add a remote NFS kdump test

mantle/platform/qemu.go
Using this interrupt controller will remove this warning from test output:
```
qemu-system-ppc64: warning: kernel_irqchip allowed but unavailable: IRQ_XIVE capability must be present for KVM
Falling back to kernel-irqchip=off
```
The previous link was 404. More info about pseries and XICS in new link.
Related to issue https://github.com/coreos/coreos-assembler/issues/2473
=> [ppc64le] Use XICS Interrupt Controller

mantle/kola/tests/ignition/kdump.go
This reverts commit b10d8dcfe730d2e7c8a5366bfcddc7f3081be203.
The test passes on F40 but not on F41+ [1] and also it is failing on RHCOS so let's just yank it for now and re-apply when it's confirmed to be passing everywhere.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/1820
=> Revert "tests/ingition/kdump: add a remote NFS kdump test"

mantle/platform/metal.go
Otherwise only `info` level messages will go to the console of the machine.
We were digging into a new instance of [1] and found that we weren't really getting debug messages on the console of the machine (which means no new clues as to why the tests are timing out). Turns out this is why we weren't getting those new debug messages we thought we would get.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/1796
=> mantle/kola: add max_level_console=debug for COSA_TESTISO_DEBUG

tests/containers/nfs/Containerfile, tests/containers/nfs/README.md, tests/containers/nfs/run_nfs.sh
This is prep work for enabling kdump over NFS testing. The previous attempt in https://github.com/coreos/coreos-assembler/pull/3911 used an image from openshift E2E tests, but I didn't pay attention to the image and the latest tag is not a multiarch manifest, so the pipeline tripped on that.
Building the image ourselves will fix that.
=> tests/containers: add a NFS server containers

src/cmd-cloud-prune
Updated the project assignment to default to `fedora-coreos-cloud` when `gcp.get("project")` returns None or an empty value. We have a few builds where the project is not specified. This ensures a fallback project is always available.
Example: 31.20200517.20.0 [meta.json](https://builds.coreos.fedoraproject.org/prod/streams/testing-devel/builds/31.20200517.20.0/x86_64/meta.json).
=> cmd-cloud-prune: set default project when unspecified

mantle/platform/qemu.go
Running secex tests with `--parallel=auto` complains:
```
$ cosa kola run  --qemu-secex --tag secex --qemu-secex-hostkey hostkey.crt --parallel=auto
=== RUN   ext.config.shared.secex.ensure
=== RUN   ext.config.shared.secex.reboot
2024-11-01T17:28:29Z kola: retryloop: failed to bring up machines: encrypting /var/tmp/mantle-qemu2551463228/ignition_crypted.1734631171: exit status 2
```
Use mutex for `gpg --encrypt` to avoid this issue.
=> secex: guard GPG encryption of Ignition config with mutex

src/cmd-buildextend-metal, src/cmd-buildextend-qemu-secex
=> [rhcos-4.15] support `cosa buildextend-qemu-secex`

src/cmd-buildextend-metal, src/cmd-buildextend-qemu-secex
=> [rhcos-4.14] support `cosa buildextend-qemu-secex`

src/cmd-buildextend-metal, src/cmd-buildextend-qemu-secex
=> [rhcos-4.13] support `cosa buildextend-qemu-secex`

src/cmd-buildextend-metal, src/cmd-buildextend-qemu-secex
=> [rhcos-4.12] support `cosa buildextend-qemu-secex`

src/cmd-buildextend-metal, src/cmd-buildextend-qemu-secex
=> [rhcos-4.16] support `cosa buildextend-qemu-secex`

mantle/cmd/kola/testiso.go
This PR aims to address the first step of a [suggestion](https://github.com/coreos/coreos-assembler/issues/3788#issuecomment-2274389391) in the #3788 issue.
(use checkConsole to verify console.txt and journal.txt for badness)
=> testiso.go: Add check for badness

src/cmdlib.sh
It's only in the privileged path where we're composing directly to the filesystem that we care about whether we're on overlayfs or not. In the unprivileged path, the compose happens on a real filesystem on the cache qcow2 within supermin, so there's no need to restrict what filesystem the workdir itself on the outside is sitting on.
=> cmdlib: only do overlayfs check in privileged path

src/cmd-build
Over time we seem to have accumulated all sorts of crud in the build dir that were never meant to be uploaded:
```
$ aws s3 ls s3://.../$buildid/x86_64/
...
2024-10-26 10:49:16       1027 cmd.sh
2024-10-26 10:49:15        540 image.json
2024-10-26 10:49:15       8436 manifest.json
2024-10-26 10:49:15       2267 platforms.json
2024-10-26 10:49:15       2621 platforms.json.all
2024-10-26 10:49:16          2 rc
2024-10-26 10:49:16      97896 runvm-console.txt
```
There are no secrets in there, but still we should be more conscious of what we upload and keep artifacts in public build dirs to strictly what we intend.
Historically, `$tmp_builddir` was meant to be the staging area for the final contents of the build dir we would move into place and `$TMPDIR` was the truly temporary directory for …
=> cmd-build: only copy allowed files into final build dir

src/cmd-cloud-prune
Reorganized the loop structure to iterate over builds first, followed by arch and then actions, optimizing the number of meta.json downloads and reducing redundancy.
=> cmd-cloud-prune: Refactor to iterate by build, arch, then action

src/cmd-osbuild
Should have been qcow2 and not qcow.
Fixes 5509a8b
=> cmd-osbuild: fix format for disk image passed to qemu

src/cmd-build, src/cmdlib.sh
- cmdlib: bump cache size to 30G
- cmd-build: skip-compression on manifest json
=> bump cache qcow size; skip compression on manifest.json

mantle/kola/tests/coretest/core.go, mantle/kola/tests/podman/podman.go
These two tests have been denylisted in FCOS for quite some time due to rate limiting issues with the containers they are pulling.
For `podman.workflow`: use the `quay.io/fedora/fedora` container and a Python HTTP server instead of the nginx container.
For `fcos.internet`: remove it altogether as there are other tests within FCOS that test this functionality.
See: https://issues.redhat.com/browse/COS-2094
=> tests: update podman.workflow and remove fcos.internet

mantle/kola/tests/crio/crio.go
It's not really useful to write to `/tmp` from Ignition because a tmpfs gets mounted on top anyway in the real root which will mask all this. So this bit of the cri-o test's Ignition config actually had no effect. Just remove it.
Also note that when composefs lands in RHCOS, this would have become a hard error because `/tmp` would be read-only before switchroot.
=> tests/crio: don't try to write to `/tmp`

Makefile, cmd/coreos-assembler.go, docs/cosa.md, src/cmd-cloud-prune, src/cmd-coreos-prune, src/cosalib/cmdlib.py
Refactor build parsing logic and remove unused variables. Rename `cmd-cloud-prune` to `cmd-coreos-prune` since it doesn't limit the garbage collection to just cloud resources but all other resources as well.
=> cmd-cloud-prune: Refactor the code and rename the script

src/cmd-generate-release-meta
Commit 21802b618 ("cmd-generate-release-meta: inject `oci-image` key in release metadata") broke the OKD pipeline which builds the OCI image, but doesn't push it using cosa.
Down the line, this should resolve itself by having OKD and OCP's node image being built the same way as layered images.
But for now let's relax the check here and just inject the OCI image information if it's available.
=> cmd-generate-release-meta: allow missing `base-oscontainer`

src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml, src/osbuild-manifests/platform.hyperv.ipp.yaml, src/osbuild-manifests/platform.qemu-secex.ipp.yaml, src/osbuild-manifests/platform.qemu.ipp.yaml
=> osbuild: rename build pipeline; use better variable names

src/cmd-coreos-prune
Refactor policy-cleanup updates to ensure action completion across all arches. Modified to track completed actions
per arch. This bug came after we refactored the code to to iterate by build, arch, then action.
With the current code, it tries to update the builds.json for every build in the stream having the respective action in `gc-policy.yaml` not taking into consideration the datetime for eg. if the script will prune all containers that are 2weeks ago, the script will try to update every build in that stream with `"containers": true` no matter if the pruning ran on that build or not.
=> cmd-coreos-prune: Ensure action completion of each build

mantle/kola/tests/podman/podman.go
Bump the retry delay to `10*time.Seconds` which doubles the previous delay to allow for enough time to report success.
Update the container name in an error statement from nginx to Fedora which should have been done in https://github.com/coreos/coreos-assembler/pull/3939
fixes: https://github.com/coreos/fedora-coreos-tracker/issues/1835
=> mantle/podman.go: bump retry delay in podmanWorkflow test

src/cosalib/container_manifest.py
If a manifest previously exists then let's try to clean it up before continuing. We saw this in the pipeline where one run failed in the middle and then a later run failed because the manifest existed:
```
2024-11-19 14:29:26,184 INFO - Running command: ['podman', 'manifest', 'create', 'quay.io/coreos-assembler/coreos-assembler:main']
Error: creating manifest: image name "quay.io/coreos-assembler/coreos-assembler:main" is already associated with image "ffbb463bfb0e3bb0fb4c42856d2dca0ff985d1dd5d7b34f1b3ae0277287ad83d": that name is already in use
```
=> cosalib/container_manifest.py: cleanup manifest before create/push

src/cmdlib.sh
We've been abusing the `rojig` key for a long time now to carry artifact name and summary information. Since then, a more appropriate `metadata key is now supported in the treefile for our purposes.
Check the `metadata` key first, but fallback to the `rojig` key to give time for src config repos to migrate.
=> cmdlib: check for `metadata` key before `rojig`

Dockerfile
We're creating `/go` and then deleting it later on, which doesn't make sense. Stop deleting it to fix the use case of Prow using the cosa image as a buildroot.
=> Dockerfile: don't delete /go

Dockerfile
That way it's more obvious that it's empty and it's purely for OpenShift CI compatibility.
=> Dockerfile: move creation of `/go` dir lower

mantle/platform/api/aws/images.go
Possibly something changed on the AWS side, but we're seeing what looks like `SnapshotTaskDetail` structs coming back with some of the fields empty. Gracefully handle this case.
=> mantle/platform/aws: handle missing details fields

src/runvm-osbuild
The `build` pipeline was renamed to `deployed-tree` in 3a91ec2 and this should have been updated in that commit as well.
=> runvm-osbuild: checkpoint deployed-tree pipeline

src/cmdlib.sh
Match what we do for the repo and chown back `compose.json` to the build user. This should fix `cosa build --force-image`.
=> cmdlib: also chown back `compose.json` in privileged path

src/cmdlib.sh
It only gets actually written in `cosa build`, so we need to handle the `cosa fetch` case where this path is also taken.
Fixes 40a2027e8 ("cmdlib: also chown back `compose.json` in privileged path").
=> cmdlib.sh: only chown `compose.json` if it exists

cmd/coreos-assembler.go, src/cmd-diff, src/cosalib/builds.py
A lot of times when making major changes to content or how artifacts are built, it's helpful to be able to diff the before and after to make sure only what we expect to change changed. For example, this would've been useful for the `create_disk.sh` to osbuild migration or the more recent tier-x migration (where I ended up doing a lot of comparisons by hand).
Now with the move of the live ISO to osbuild, we have a need for it again.
Add a new `cosa diff` command for this.
The command supports different kinds of diffs and more can easily be added. For now, I've focused on the core ones (RPMs, OSTree content, initramfs) and the live artifacts since those are the needed currently.
```
$ cosa diff -h
usage: cmd-diff <snip>
options:
-h, --help          show this help message and exit
--from …
```
=> Add new `cosa diff` command to diff builds

src/build-deps.txt
CI was updated[0] to use coreos-assembler as a buildroot instead of the fcos-buildroot container and the openshift/os `validate` job[1] fails because shellcheck isn't installed in coreos-assembler. It cannot be installed using `sudo` when running on OpenShift so it needs to be installed directly in coreos-assembler.
[0] https://github.com/openshift/release/pull/59000/commits/68a7999da3e4fc98603b33b95cb83917b35e62d5
[1] https://github.com/openshift/os/blob/ce4da959eb3fc9477a0a96b69e6efd084a69b9ac/ci/prow-entrypoint.sh#L162
=> build-deps.txt: add shellcheck

.cci.jenkinsfile, build.sh, mantle/cmd/kola/testiso.go, mantle/platform/metal.go, mantle/platform/qemu.go, src/0001-osbuild-remoteloop-add-more-loop-device-options.patch, src/0002-osbuild-loop-make-the-loop-device-if-missing.patch, src/0003-util-osrelease.py-improve-whitespace-and-quote-strip.patch, src/0004-util-chroot-Add-support-for-custom-directory-bind-mo.patch, src/0005-stages-add-coreos.live-artifacts.mono-stage.patch, src/cmd-osbuild, src/cmdlib.sh, src/deps-ppc64le.txt, src/deps-s390x.txt, src/deps-x86_64.txt, src/deps.txt, src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml, src/osbuild-manifests/platform.live.ipp.yaml, src/runvm-osbuild, src/vmdeps-ppc64le.txt, src/vmdeps-s390x.txt, src/vmdeps-x86_64.txt, src/vmdeps.txt
This backports and takes advantage of the new
org.osbuild.coreos.live-artifacts.mono stage.
=> osbuild: Add Live ISO/PXE build support

src/deps-ppc64le.txt
It was emptied out and just a comment left in dc22a02 but the way src/print-dependencies.sh works it fails if the grep to remove comments yields nothing. Let's just empty the file for now so the `if -s` check won't succeed.
=> empty out deps-ppc64le.txt

src/cmd-build
The `--skip-config-archive` skips creating the tar.gz of the src/config. However the changes to how files are collected failed to check this before hardcoding that the output file should be collected.
----
Looks like when the rework happened to use `loose_objs`, it missed the fact that the config archive may or may not exist.  If the `--skip-config-archive` is used, the build currently fails during the collection step.
/close #3972
=> Fix --skip-config-archive.

src/cmdlib.sh
Fallout from the move to f41 and dnf5.
A few issues: first, looks like Looks like dnf5 repoquery's `--qf` acts
differently. Not only it no longer implicitly emits a newline, but also
it doesn't interpret `\t` anymore. This is tracked at:
rpm-software-management/dnf5#709
Second, `--quiet` is broken and still includes output from progress bar:
rpm-software-management/dnf5#1915
Work around this by using spaces instead of `\t`, adding `\n`, and
prefixing pkg entries with `pkg:`.
=> cmdlib.sh: fix repoquery when building overrides lockfile

src/cmd-coreos-prune
To improve the readability of GC logs, let's introduce indentation to display a nested structure as we traverse each build.
=> coreos-prune: Add indentation to log messages

mantle/cmd/ore/openstack/gc.go, mantle/platform/api/openstack/api.go
Ref: https://github.com/coreos/coreos-assembler/issues/3550
=> mantle: Expand openstack gc to keypairs

src/osbuild-manifests/platform.gcp.ipp.yaml, src/runvm-osbuild
=> osbuild: use sparse for GCP tarball; log disk usage

src/cmd-coreos-prune
We want to complete all other actions before fully pruning a build and deleting the S3 directory. This guarantees the `meta.json` file remains accessible if needed.
=> cmd-coreos-prune: Add build pruning after other actions

mantle/kola/tests/podman/podman.go
The podman.workflow test has been failing on OpenStack, likely because pulling the Fedora container takes too long. Use the `RetryUntilTimeout` function to retry every minute for up to 15 minutes to allow sufficient time to pull the Fedora container. In local testing, pulling the container on OpenStack took approximately 5 minutes before succeeding.
See: https://github.com/coreos/fedora-coreos-tracker/issues/1835
=> mantle/podman.go: use `RetryUntilTimeout` in podman.workflow

src/cosalib/cmdlib.py
Ensure compatibility with older and newer versions. We have a few builds in `testing` stream with a different format. An example is `30.20190712.0`
=> cmdlib: Support old FCOS version in parsing

mantle/kola/tests/upgrade/basic.go
This commit introduces the `waitForUpgradeToBeStaged` function to improve the stability of kola upgrade test by reducing timeout-related failures.
The new function sets up a systemd path unit to monitor updates in the `/ostree/repo/refs/heads/ostree/1/1` directory, triggering a stop on `wait.service` once changes are detected.
By ensuring we wait later in the upgrade process, we minimize the waiting period in `runFnAndWaitForRebootIntoVersion`, focusing only on the actual reboot phase.
Author : Dusty Mabe <dusty@dustymabe.com>
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1805
=> mantle/kola: Add function to enhance upgrade stability

src/cmd-coreos-prune
Xerf to https://github.com/coreos/coreos-assembler/pull/273
Fix CI failed issue:
```
src/cmd-coreos-prune:39:0: E0401: Unable to import 'pytz' (import-error)
```
=> cmd-coreos-prune: replace `pytz` to `datetime`

src/cmd-diff
This adds '--arch' argument to pass architecture you want to get information about. By default current arch is used.
```
$ uname -m
x86_64
$ cosa diff --arch=s390x --from=41.20250101.20.0 --to=41.20250114.20.0 --rpms
ostree diff commit from: c3fe29653cf0ebd1d093b1a55cf9ac79a386373e71f64c67769f904332ba0ca6
ostree diff commit to:   988aa49471f406354274bc013c1102004dad25000862df68472d6058fcb00f8b
Upgraded:
audit 4.0.2-1.fc41 -> 4.0.3-1.fc41
audit-libs 4.0.2-1.fc41 -> 4.0.3-1.fc41
...
```
Issue: https://github.com/coreos/coreos-assembler/issues/3987
=> cmd-diff: support passing in the architecture

mantle/kola/tests/misc/tls.go
These were changed to other URLs when the test moved to an external test in https://github.com/coreos/fedora-coreos-config/commit/41901c7dc5e604e0ee27ffcf60f87b1b6d7a723b
Let's update the URLs for older releases too to simplify our allow rules for external domains.
=> [rhcos-4.13] mantle/kola: change URLs for coreos.tls.fetch-urls test

mantle/kola/tests/misc/users.go
Now most of the entries are `/usr/bin/nologin`.
https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin
=> mantle/kola: update fcos.users.shells test for sbin/bin merge

mantle/kola/tests/ostree/sync.go
Add test for https://issues.redhat.com/browse/OCPBUGS-15917, to verify ostree works in the siutation with disconnected the network volume.
As we do not have ceph for testing, according to the suggestion from Colin and Joseph: `use something like NFS, we should in theory see the same error if we disconnected the NFS volume and we could not sync the filesystem.`
Xref to steps in [comment](https://issues.redhat.com/browse/ECOENGCL-91?focusedId=26272587&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26272587).
=> tests: add ostree.sync test

src/cosalib/container_manifest.py
enhance the garbage collection for the repo:tag we are trying to create a container image manifest for. In this case we were getting an error because someone had pulled the
quay.io/coreos-assembler/coreos-assembler:main image down from quay. It wasn't a manifest listed repo:tag so `podman manifest exists` wasn't returning true, but the create would fail.
The updated code here should handle this case.
This enhances the previous effort in 01e4e55.
=> cosalib/container_manifest.py: account for images that are repo:tag

build.sh
If we want to fast-track these packages we can tag them into the fXX-coreos-continous tags like any other package. Right now the version of rpm-ostree in `updates-testing` is busted and we don't want it in our builds.
[1] https://bodhi.fedoraproject.org/updates/FEDORA-2025-95492f42d2#comment-3932487
=> build.sh: stop fast-tracking rpm-ostree/ostree from updates-testing

mantle/cmd/kola/resources/iscsi_butane_setup.yaml
Pulling COSA from quay and running an install in a VM takes a good amount of time. Let's bump this so the service doesn't timeout like has been seen:
```
Jan 27 13:27:10 localhost systemd[1]: Starting Boot VM over iSCSI...
Jan 27 13:28:21 localhost chronyd[1116]: Can't synchronise: no selectable sources
Jan 27 13:28:21 localhost chronyd[1116]: Source 149.28.200.179 replaced with 67.217.246.204 (2.rhel.pool.ntp.org)
Jan 27 13:31:16 localhost systemd[1289]: Created slice User Background Tasks Slice.
Jan 27 13:31:16 localhost systemd[1289]: Starting Cleanup of User's Temporary Files and Directories...
Jan 27 13:31:16 localhost systemd[1289]: Finished Cleanup of User's Temporary Files and Directories.
Jan 27 13:31:26 localhost systemd[1]: coreos-iscsi-vm.service: start operation timed out. …
```
=> mantle/kola: use TimeoutStartSec for iscsi tests

mantle/cmd/kola/resources/iscsi_butane_setup.yaml
We've seen errors in the RHCOS pipeline where the iSCSI tests are hitting the 10m timeout. We could bump the timeout, but first let's try pulling the COSA image in a separate unit so that it can happen in parallel with the install over iSCSI so that when we're ready to start the VM the image is already there.
=> mantle/kola: use separate unit for pulling COSA in iscsi tests

mantle/cmd/kola/options.go, mantle/platform/api/gcloud/compute.go, mantle/platform/api/gcloud/image.go
I manually marked `rhcos-419-96-202501191959-0-gcp-x86-64` on GCP as `TDX_CAPABLE`, and booted a TDX confidential VM instance. Serial port sample:
```
[    0.000000] tdx: Guest detected
...
[    1.444597] process: using TDX aware idle routine
...
[    1.524482] Memory Encryption Features active: Intel TDX
...
[    3.661927] systemd[1]: Detected virtualization kvm.
[    3.661938] systemd[1]: Detected confidential virtualization tdx.
[    3.661942] systemd[1]: Detected architecture x86-64.
[    3.661945] systemd[1]: Running in initrd.
...
```
Previous work: https://github.com/coreos/coreos-assembler/pull/3547
Previous work: https://github.com/coreos/coreos-assembler/pull/3871
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/1814
Fixes: https://issues.redhat.com/browse/COS-3111
=> GCP: Mark images as `TDX_CAPABLE`

mantle/cmd/kola/qemuexec.go, mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go
In this case we'll run the podman container with --rootfs instead
of pulling a full 4+ GiB COSA image from quay for `kola qemuexec`.
This saves us quite a bit of time and bandwidth usage during a
pipeline run because we have more than 1 iscsi test.
This should also take care of https://github.com/coreos/fedora-coreos-tracker/issues/1866
because we are no longer pulling this particular container from quay.
=> mantle/kola: make iscsi tests use virtiofs mounted COSA rootfs

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go
**Backport**
In this case we'll run the podman container with --rootfs instead
of pulling a full 4+ GiB COSA image from quay for `kola qemuexec`.
This saves us quite a bit of time and bandwidth usage during a
pipeline run because we have more than 1 iscsi test.
This should also take care of https://github.com/coreos/fedora-coreos-tracker/issues/1866
because we are no longer pulling this particular container from quay.
(cherry picked from commit 8dbfe3ea8b8f571e732e8cc0ab307e983a0be1f3)
=> [rhcos-4.17]: mantle/kola: make iscsi tests use virtiofs mounted COSA rootfs

build.sh, mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go
**Backport**
In this case we'll run the podman container with --rootfs instead
of pulling a full 4+ GiB COSA image from quay for `kola qemuexec`.
This saves us quite a bit of time and bandwidth usage during a
pipeline run because we have more than 1 iscsi test.
This should also take care of https://github.com/coreos/fedora-coreos-tracker/issues/1866
because we are no longer pulling this particular container from quay.
(cherry picked from commit 8dbfe3ea8b8f571e732e8cc0ab307e983a0be1f3)
=> [rhcos-4.18]: mantle/kola: make iscsi tests use virtiofs mounted COSA rootfs

mantle/cmd/kola/resources/iscsi_butane_setup.yaml
Add more clarity on why the AddDevice option is being used.
=> mantle/kola: update AddDevice comment in iscsi_butane_setup.yaml

mantle/cmd/kola/resources/iscsi_butane_setup.yaml, mantle/cmd/kola/testiso.go
Backport https://github.com/coreos/coreos-assembler/pull/4013 to `rhcos-4.16`.
In this case we'll run the podman container with --rootfs instead
of pulling a full 4+ GiB COSA image from quay for kola qemuexec.
This saves us quite a bit of time and bandwidth usage during a
pipeline run because we have more than 1 iscsi test.
This should also take care of https://github.com/coreos/fedora-coreos-tracker/issues/1866
because we are no longer pulling this particular container from quay.
=> [rhcos-4.16]: mantle/kola: make iscsi tests use virtiofs mounted COSA rootfs

mantle/cmd/kola/resources/iscsi_butane_setup.yaml
For some reason in OCP 4.16 with podman-4.9.4-16.el9_4 AddDevice (--device /dev/virtio-ports/testisocompletion) doesn't seem to be mapping into the container correctly. Switch to Volume here.
=> [rhcos-4.16] mantle/kola: use volume for testisocompletion device

src/cmd-coreos-prune
This detection wasn't working properly and causing the `images` action to get run even for builds where the images had already been pruned.
=> cmd-coreos-prune: fix skipping of images action

build.sh, src/0001-stages-add-more-options-to-qemu-vmdk-disk-type.patch, src/0001-stages-coreos.live-artifacts-use-var-tmp-for-mkfs.er.patch, src/cmd-compress, src/cmd-osbuild, src/cmdlib.sh, src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml, src/osbuild-manifests/platform.aliyun.ipp.yaml, src/osbuild-manifests/platform.aws.ipp.yaml, src/osbuild-manifests/platform.azure.ipp.yaml, src/osbuild-manifests/platform.azurestack.ipp.yaml, src/osbuild-manifests/platform.digitalocean.ipp.yaml, src/osbuild-manifests/platform.exoscale.ipp.yaml, src/osbuild-manifests/platform.ibmcloud.ipp.yaml, src/osbuild-manifests/platform.nutanix.ipp.yaml, src/osbuild-manifests/platform.openstack.ipp.yaml, src/osbuild-manifests/platform.vultr.ipp.yaml
=> osbuild: support more platforms; reduce memory usage for mkfs.erofs

mantle/platform/api/openstack/api.go
Since Mantle seems to upload QCOW2 images, when using boot from
volume, it leaves a huge load on the remote control plane due
to the fact that the image needs to be converted from QCOW2 into
RAW and then booted.
The reason why this was initially changed was because boots
were taking a long time, but now OpenStack has a download-direct
from the storage backend which will do a distributed pull that
would be way faster than download-on-convert on a single system.
=> mantle/openstack: stop using boot-from-volume

mantle/cmd/kola/testiso.go
```
$ cosa kola testiso -S --qemu-native-4k --qemu-multipath  --output-dir tmp/kola-testiso-metal
⏭️  Skipping kola test pattern "fcos.internet":
👉 https://github.com/coreos/coreos-assembler/pull/1478
⏭️  Skipping kola test pattern "podman.workflow":
👉 https://github.com/coreos/coreos-assembler/pull/1478
Ignoring verification of signature on metal image
Running test: iso-live-login.s390fw
PASS: iso-live-login.s390fw (13.86s)
Running test: iso-live-login.4k.s390fw
PASS: iso-live-login.4k.s390fw (13.245s)
Running test: iso-offline-install.s390fw
PASS: iso-offline-install.s390fw (46.925s)
Running test: iso-offline-install.4k.s390fw
PASS: iso-offline-install.4k.s390fw (45.83s)
Running test: iso-offline-install.mpath.s390fw
PASS: iso-offline-install.mpath.s390fw (47.561s)
Running test: …
```
=> kola/testiso: enable 4k images tests for s390x

pytest.ini, src/cmd-diff, src/cmd-koji-upload, src/cmdlib.sh, src/cosalib/cmdlib.py
Being able to diff two builds is now a very lightweight:
```
cosa buildfetch --build=A
cosa buildfetch --build=B
cosa diff --rpms --from=A --to=B
```
Previously this was hundreds of MiB and now it's in the KiB range.
EDIT: Added another commit:
cmd-diff: support showing source-control diffs for two builds
Useful for trying to determine the changes that occured for two builds
that were outside of RPM changes. Example:
```
$ cosa diff --source-control --from=42.20240919.91.0 --to=42.20240920.91.0
https://github.com/coreos/fedora-coreos-config: 80f646d..051fb67
--> https://github.com/coreos/fedora-coreos-config/compare/80f646d...051fb67
https://github.com/coreos/coreos-assembler.git: d3302e0..d3302e0
--> https://github.com/coreos/coreos-assembler/compare/d3302e0...d3302e0
```
=> cmd-diff: support lightweight ostree import for RPM diff

src/cmd-osbuild
It wasn't using the right string so it was always using the default ostree-image-signed.....ociarchive value here.
Fixes 23ced5f
=> cmd-osbuild: fix parsing of container-imgref from image.json

src/cmd-osbuild, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml, src/osbuild-manifests/platform.kubevirt.ipp.yaml, src/runvm-osbuild
Also a second commit for supporting the new platforms when symlinked.
=> osbuild: support building kubevirt disks

mantle/cmd/kola/testiso.go
The `kola testiso` command supported `--pxe-append-rootfs`, but it was never used in CI, and probably was also ignored by developers. This PR drops that switch and adds 1 new test for each arch:
- pxe-[online|offline]-install.rootfs-appended
=> testiso: add new PXE tests instead of '--pxe-append-rootfs' switch

mantle/cmd/kola/testiso.go
Issue: https://github.com/coreos/fedora-coreos-tracker/issues/1883
=> testiso: disable *rootfs-appended* test on s390x

src/cmdlib.sh
It's useful to be able to just `koji download-build BUILDID` to populate `overrides/rpm` with the RPMs you want to test. Ideally you'd add e.g. `--arch x86_64 --arch noarch` to this to limit what gets downloaded.
But it should still work fine regardless if you forgot and there's a bunch of RPMs in there that are not for your arch. To handle this, limit the repoquery results to the relevant arches only. This also allows us to drop the `*.src` exclusion we had.
=> cmdlib.sh: limit overrides/rpm repoquery to specific arches

build.sh
some PXE tests are failing in ppc64le because they use the grub2 package from cosa to set up the environment. Freeze to the last working version for now.
See: https://github.com/coreos/fedora-coreos-tracker/issues/1886
=> build: freeze grub2 due to ppc64le PXE test failures

mantle/cmd/kola/testiso.go
For some reason the pxe-online-install.rootfs-appended.ppcfw test is taking 7 minutes just to transfer/load the combined initramfs plus rootfs. That's 7 minutes before the kernel even starts booting.
This means we're hitting timeouts a lot at 10 minutes. We should investigate why it's taking so long here, but for now let's bump it a little bit so we hopefully can get some stability in the pipeline.
=> mantle/kola: extend testiso timeouts to 12 minutes

src/build-extensions-container.sh, src/cmd-remote-build-container, src/cosalib/container_manifest.py, src/supermin-init-prelude.sh
We're getting ready to build the extensions container in production as part of the layered node image work. To be able to build it using `podman build` directly and not via `cosa build-extensions-container`, a few adjustments are needed.
=> Various patches to build extensions container using `podman build` in production

src/cmd-remote-build-container
This basically maps to podman's `--digestfile` option. This is useful as a way to reference the pushed image by digest instead of by tag.
=> cmd-remote-build-container: add --write-digest-to-file

src/build-extensions-container.sh
The latest openshift/os bits no longer do this, so we can drop support for it.
=> build-extensions-container.sh: stop bind-mounting `extensions.json`

build.sh, src/cmd-podman-build
See individual commit messages. Goes together with https://github.com/openshift/os/pull/1780.
=> Add CentOS Stream keys, add `cosa podman-build`

build.sh
This issue in PXE tests on ppc64le is now fixed.
Closes https://github.com/coreos/fedora-coreos-tracker/issues/1886
=> build.sh: unfreeze grub2

src/cmdlib.sh
Currently, we're only copying files, but we want symlinks too.
Follow-up to 876c466ed ("build.sh: add CentOS Stream keys into `/etc/pki/rpm-gpg`").
=> cmdlib.sh: copy all GPG keys into supermin VM

src/cmd-podman-build
In the case where you are running COSA via the alias/func [1] and not
in a custom toolbox container then `cosa podman-build node` today
won't work because running `podman` inside a rootless container
doesn't really work.
Add a new `--args` argument here to just tell `cosa podman-build`
to set up for the build (i.e. generate tmp files and necessary
arguments) and then print what would have been passed to `podman build`.
This can then be used on the host to run `podman build` with something
like:
```
node-build() {
local args=$(cosa podman-build --args node)
args=$(echo "$args" | tr -d '\r' | sed s,src/config,$COREOS_ASSEMBLER_CONFIG_GIT,g)
set -x
podman build $args
set +x
}
```
So you'd run `node-build` and it would do what you need for you.
[1] …
=> cmd-podman-build: support --args for just printing arguments

src/cmd-podman-build
This goes together with Jonathan's commit in
https://github.com/openshift/os/pull/1498 titled "build-node-image.sh: include yum repos from git as part of build".
There's no point in adding the repo files already in the git repo into the secret; the node and extension builds already have access to those. So we'd just be duplicating them.
Another way to think of this is that the secret injection we do here should be considered equivalent to `get-ocp-repo.sh` in OpenShift CI in terms of what repos get injected.
=> cmd-podman-build: stop passing the git yum repos

src/cmd-compress, src/cosalib/aws.py, src/cosalib/builds.py
As part of c61da89 we started to allow templating in the image.yaml file. This means we now need to pass the dict of things to template into flatten-image-yaml and that is now causing us issues if there are things to template but not template dict passed in.
One case we were doing this was in our AWS upload where we pick up some values from image.yaml. Except, we shouldn't have been picking them up from image.yaml in the src/config as this stage but rather the image.json that had been baked into the build.
Let's switch over cosalib/aws to pick the info up from image.json instead. As part of this add a helper the the cosalib Builds library to make this easier for us in various places to do it. This addition was conveniently stolen from cmd-compress that already had code to do this.
=> cosalib: add Builds().get_build_image_json(); drop use of flatten_image_yaml()

docs/cosa/run.md
- Mention the long option name for `cosa run -c`
- Ctrl-a x only works with lower case letter
- Mention that this is a QEMU command
=> docs/cosa/run: Mention `devshell-console` and QEMU

src/cmd-push-container-manifest, src/cosalib/container_manifest.py
- This maps to Podman's --digestfile option, allowing the manifest digest to be saved for future reference or use.
=> cmd-push-container-manifest: add --write-digest-to-file

src/cmdlib.sh
This is mostly cosmetic, but nice to have them formatted in a human readable way.
=> cmdlib: skip blank and comment lines when building fast-track repo

mantle/kola/tests/ignition/kdump.go
This was previously merged in [1] then reverted in [2] because the nfs
server container was not multi-arch, causing the pipeline to trip on it.
It's also not functionning on systemd256 (so anything f41 and above),
see [3]
This requires https://github.com/coreos/coreos-assembler/pull/3917 for
the multi-arch container, and
https://github.com/coreos/coreos-assembler/issues/3921
[1] https://github.com/coreos/coreos-assembler/commit/b10d8dcfe730d2e7c8a5366bfcddc7f3081be203
[2] https://github.com/coreos/coreos-assembler/commit/af1468c421fdedfe6c62e731eaac7fd4df720fc7
[3] https://github.com/rhkdump/kdump-utils/issues/52
=> tests: add kdump over NFS

build.sh, src/0001-stages-coreos.live-artifacts-fix-kernel-and-initrd-p.patch, src/cmd-buildextend-live
This PR fixes the paths stored in s390x ISO `generic.ins`:
```
$ cat generic.ins 
* minimal lpar ins file
images/kernel.img 0x00000000
images/initrd.img 0x02000000
```
with actual layout:
```
$ find images/pxeboot/
images/pxeboot/initrd.img
images/pxeboot/vmlinuz
```
```
$ cat generic.ins 
* minimal lpar ins file
images/pxeboot/vmlinuz 0x00000000
images/pxeboot/initrd.img 0x02000000
```
Issue: https://github.com/coreos/coreos-assembler/issues/4077
=> live: fix wrong paths in s390x ISO

Dockerfile, tests/containers/nfs/Containerfile, tests/containers/tang/Containerfile
openshift/release PR:
- https://github.com/openshift/release/pull/63986
Issue: https://github.com/coreos/coreos-assembler/issues/4078
=> Bump to F42

src/cosalib/aws.py
The s3 bucket argument is optional in ore, but when utilizing the ore-wrapper the argument is set to "None" if it doesn't exist, breaking the logic in ore that sets a default bucket. Let's make it optional here, so we don't pass "None" to ore if it's not used.
=> cosalib/aws.py: make `bucket` an optional ore argument

src/cosalib/aws.py
This should have been part of https://github.com/coreos/coreos-assembler/commit/a0921c916cedd8dcc3714b23b56601bf17e0906d. 
Don't exit when the ami has already been replicated and there are no more regions to replicate to. Now that this is in a for loop, we should continue here so we can also process aws-winli images.
=> cosalib/aws.py: fix replicate logic for amis already replicated

src/cmd-koji-upload
cmd-koji-upload is tightly coupled to the Build class and cosalib internals, which makes supporting the new node-image layout challenging.
This commit introduces a way to maintain compatibility with both the legacy and updated node-image styles for brew uploads.
This is a transitional fix — once the migration to Konflux is complete, this compatibility layer will no longer be necessary.
=> cmd-koji-upload: Add support for node-image

src/deps.txt
See https://github.com/coreos/coreos-ci/pull/86#discussion_r2056199428
=> deps: add `copr-cli` to support for copr build in coreos-ci

src/cmd-remote-build-container
We hit several caching issues in the nodeimage layered build where the arch builders were building on top of stale base images. Hard coding `--pull=always` make sense here : if we already have the image locally it's just a check, but we need to be sure.
=> cmd/podman-remote-build: always pull images

cmd/remote-session.go, docs/building-fcos.md
Updates example cosa() func to podman 4.3+ functionality.
Works with arbitrary non-root host UIDs.
=> docs: Switch example cosa() func from --uidmap to --userns

Makefile, build.sh, mantle/build, src/cmd-osbuild, src/osbuild-manifests/coreos.osbuild.riscv64.mpp.yaml
This is initial support for being able to build against a riscv64
architecture target.
xref: https://github.com/coreos/fedora-coreos-tracker/issues/1931
There is also a commit in here for limiting the number of architectures we
build `kolet` for by default. See the commit message for more details.
=> Add support for riscv

src/cmd-coreos-prune
When a tag is expired or been garbage collected in Quay, skopeo inspect returns a "unknown" error with a message like:
```
Tag <tag> was deleted or has expired. To pull, revive via time machine
```
Check for this condition and skip raising the exception, instead just return since the tag has already been GC'd.
Aims to fix: https://github.com/coreos/coreos-assembler/issues/4087
=> cmd-coreos-prune: handle expired or deleted tags in skopeo inspect

ci/prow-rhcos.sh
The repo was split such that going forward coreos/rhel-coreos-config will be used so let's update it so that we test again that repo for latest main branch of COSA.
=> ci/prow-rhcos: update for rhcos repo split

src/osbuild-manifests/coreos.osbuild.aarch64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.ppc64le.mpp.yaml, src/osbuild-manifests/coreos.osbuild.riscv64.mpp.yaml, src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/coreos.osbuild.x86_64.mpp.yaml
Now that we are building only F42+ images we are never passing in an OSTree commit. The FCOS pipeline was the only consumer of this so we can safely drop that conditional logic.
=> osbuild: drop support for building disk images from OSTree commit

.cci.jenkinsfile
We are seeing an issue where the first time we try to create a pod from a just created image it fails. Here we bake in an initial pod that we allow to fail to work around the problem while we investigate.
=> cci.jenkinsfile: add in workaround for pod pull issue

mantle/cmd/kola/options.go, mantle/cmd/kola/qemuexec.go, mantle/kola/tests/ignition/luks.go, mantle/kola/tests/util/luks.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/machine/qemu/flight.go, mantle/platform/qemu.go
This test was added to coreos-assembler before 4.19 branched, so it ended up in 4.18 but was intended for 4.19+. It recently started failing in 4.18 due to the addition of CEX configuration in RHCOS. Remove the test from 4.18 to unblock the pipeline.
This reverts commit 41e5c4a3a554706fbff86dd71906411d934cc568.
=> [rhcos-4.18] kola: remove IBM CEX device test for the s390x build

.cci.jenkinsfile, build.sh
A new version of GRUB was released right at the end of F40 before EOL and it brought in the problems described in [1] making ppc64le tests fail. We'll just pin on the older version.
See: https://github.com/coreos/fedora-coreos-tracker/issues/1886
=> [rhcos-4.18] build: freeze grub2 due to ppc64le PXE test failures

build.sh
Otherwise we get a use of unitialized variable in the s390x case.
(cherry picked from commit 5a320f7a1c6e177bdf09b6a294ba9ac766a69666)
=> [rhcos-4.18] build.sh: set frozendeps to some value

mantle/kola/tests/podman/podman.go
podman rmi only produces two lines of output without a -q option that might produce a "docker-ish" output displaying only the abbreviated image ID.
To simplify rmi success checking, indirect testing using the expected ID output was replaced with a direct reference to the image name. Bash piping with grep was also removed in favor of a single command.
=> tests/podman: podman rmi output check

build.sh
A new version of GRUB was released right at the end of F40 before EOL
and it brought in the problems described in [1] making ppc64le tests
fail. We'll just pin on the older version.
See: https://github.com/coreos/fedora-coreos-tracker/issues/1886
(cherry picked from commit 8f0ddfffec64d334ddf5c386c25dae190030e2fe)
=> [rhcos-4.17] build: freeze grub2 due to ppc64le PXE test failures

.cci.jenkinsfile
I needed to actually provide a command to run that would print the text. Fixes 456beae.
=> .cci.jenkinsfile: fix typo in shwrap

src/osbuild-manifests/coreos.osbuild.s390x.mpp.yaml, src/osbuild-manifests/platform.kubevirt.ipp.yaml
Hi,
Based on the jira ticket https://issues.redhat.com/browse/COS-3221 . 
https://issues.redhat.com/browse/OCPBUGS-54751
Have done the testing using coreos-assember image with changes in osbuild-manifests. Able to generate kubevirt archive for FCOS as well as RHCOS.
RHCOS
```
rhcos419-kubevirt]# cosa list
COREOS_ASSEMBLER_CONTAINER=quay.io/coreos/coreos-assember-kubevirt:latest
COREOS_ASSEMBLER_ADD_CERTS=y
+ podman run --rm -ti --security-opt=label=disable --privileged --userns=keep-id:uid=1000,gid=1000 -v=/root/rhcos419-kubevirt:/srv/ --device=/dev/kvm --device=/dev/fuse --tmpfs=/tmp -v=/var/tmp:/var/tmp --name=cosa -v=/etc/pki/ca-trust:/etc/pki/ca-trust:ro quay.io/coreos/coreos-assember-kubevirt:latest list
419.96.202505071254-0
Timestamp: 2025-05-07T12:59:19Z (0:33:04 ago)
Artifacts: …
```
=> osbuild-manifests: enable kubevirt image for s390x

mantle/kola/tests/misc/nfs-client.go, mantle/kola/tests/rhcos/nfs.go
1. **Add new test for verifying NFS v3 and v4 client on fcos**
Sets up a single VM with NFS server running as container. Clients mounts the same export under different mouthpaths for NFS versions 3 and 4, and checks existence of a tempfile
2. **Move existing NFS v4 test to rhcos as it requires server packages, which is not included in fcos.**
Related to: https://github.com/coreos/fedora-coreos-tracker/issues/1942
=> tests: Add new test for nfs clients for fcos and reorganize existing nfs test

mantle/cmd/kola/kola.go, mantle/cmd/kola/options.go, mantle/cmd/ore/azure/azure.go, mantle/cmd/ore/azure/create-gallery-image.go, mantle/cmd/ore/azure/delete-gallery-image.go, mantle/kola/harness.go, mantle/kola/register/register.go, mantle/platform/api/azure/api.go, mantle/platform/api/azure/disk.go, mantle/platform/api/azure/gallery.go, mantle/platform/api/azure/image.go, mantle/platform/api/azure/instance.go, mantle/platform/api/azure/network.go, mantle/platform/api/azure/options.go, mantle/platform/machine/aws/cluster.go, mantle/platform/machine/azure/cluster.go, mantle/platform/machine/do/cluster.go, mantle/platform/machine/esx/cluster.go, mantle/platform/machine/gcloud/cluster.go, mantle/platform/machine/openstack/cluster.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/machine/qemuiso/cluster.go, mantle/platform/platform.go
This PR introduces support for building and running Azure Shared Image Gallery (SIG) images, also known as "gallery images", alongside traditional managed images. ~~Both image types can now be used with either Hyper-V Generation 1 or Generation 2.~~ Both images types now default to using Hyper-V Generation 2.
Additional enhancements include:
- Support for overriding the instance type per kola test via external test configuration (useful for tests requiring specific VM sizes).
- Ability to attach additional data disks to Azure instances, as specified in kola tests.
This enables testing the Azure disk udev rules that were added in https://github.com/coreos/fedora-coreos-config/pull/3378, as NVMe support is only available on Gen2 Gallery Images.
See: https://issues.redhat.com/browse/COS-3125 …
=> mantle/platform/azure: Add support for Azure Shared Image Gallery (SIG) and other enhancements

mantle/kola/harness.go, mantle/platform/machine/qemu/cluster.go, mantle/platform/platform.go
Add a new kola tag to configure qemu with Secure Boot enabled
Fixes: https://github.com/coreos/coreos-assembler/issues/4112
Needed for: https://github.com/coreos/fedora-coreos-config/pull/3326
=> kola: add support for tests with Secure Boot enabled

mantle/kola/tests/misc/multipath.go
The test needs to be adapted so it doesn't verify that we're on multipath based on whether the device is `/dev/mapper/mpath` or not, but instead based on udevadm output.
=> mantle/kola/tests: adapt mpath verification

src/cmd-remote-build-container
Currently, `oc` looks for non-standard labels for git information, which it then places in e.g. `image-references` in the release payload.
Ideally `oc` would also check for the standard
`org.opencontainers.image.{revision,source}` labels too for this purpose but this assumption is wired in a bunch of places so let's just conform for now to it.
Add a new option to inject these labels. This can then be used when building the node image extensions image. In turn, this makes the release controller page for a release have working links for our images to the openshift/os commit they were built from, just like the other images.
=> cmd-remote-build-container: add --add-openshift-build-labels

mantle/cmd/kolet/kolet.go, mantle/kola/harness.go, mantle/platform/cluster.go
Prep for https://github.com/coreos/coreos-assembler/pull/4119
---
kolet: Capture error messages from mkfifo
The Go `exec.Command` when used naively like this captures
stderr and then it gets lost.
It turned out with soft reboot it was this `mkfifo` that was
failing but all we got is "Child process exited with code 1"
but there are like 5 different processes on two different hosts
that could be talking about, and we *really* thought it
was talking about the code-under-test, not the framework setting
it up.
---
kola: Don't drop stderr on the floor from unit starting function
Amazingly we had *two* places that dropped stderr, this was
the second. The default `c.SSH` captures logs from test failures
but this was an *infra* failure so we need to drop to the
raw ssh tool.
(This could use a big …
=> Soft reboot prep

.github/dependabot.yml
Let's let dependabot update all deps monthly in a single PR.
=> github/dependabot: enable for all deps

.github/dependabot.yml
Apparently you can't have two config entries for `gomod` so we'll have to merge these two together. I'll just compromise and go from daily in one and monthly in the other and settle on weekly for both.
Unfortunately there isn't really a way to validate your dependabot config before merging the PR and going to the dependabot tab so we'll YOLO until it works.
=> github/dependabot: merge two configs together

docs/kola/external-tests.md, mantle/cmd/kola/devshell.go, mantle/cmd/kolet/kolet.go, mantle/kola/harness.go, mantle/platform/machine/aws/machine.go, mantle/platform/machine/azure/machine.go, mantle/platform/machine/do/machine.go, mantle/platform/machine/esx/machine.go, mantle/platform/machine/gcloud/machine.go, mantle/platform/machine/openstack/machine.go, mantle/platform/machine/qemu/machine.go, mantle/platform/machine/qemuiso/machine.go, mantle/platform/platform.go, mantle/platform/util.go, tests/kola-ci-self/tests/kola/autopkgtest-soft-reboot
Implements soft-reboot capabilities for Kola,
it enables tests to use systemd's soft-reboot functionality.
The implementation follows the same pattern as regular reboots but for `systemctl soft-reboot`, tracks systemd boot
timestamps rather than kernel boot IDs for state detection.
=> kola: Add soft-reboot support for external tests

mantle/cmd/kola/testiso.go
The PXE test fails due to memory exhaustion while trying to fit the initramfs and rootfs in memory, leading to initramfs failures. Increase the memory for the testiso VM.
=> testiso: increase memory for PXE tests

mantle/cmd/kola/options.go, mantle/kola/harness.go
Kola normally requires a manifest.yaml to determine the stream for denylist filtering. This change adds support for passing the stream explicitly via the --denylist-stream flag, allowing kola to run without a manifest file.
See https://github.com/openshift/os/pull/1836#discussion_r2185930571
=> feat(kola): add --denylist-stream flag to allow running without manifest.yaml

renovate.json
According to the Mintmaker team, this format error is preventing Renovate to automerge the RPM lockfile update commit, so let's fix it.
=> konflux: fix renovate json file

renovate.json
We should use the MintMaker schema [1] and not the Renovate default one in order to apply properly the desired configuration.
[1] https://github.com/konflux-ci/mintmaker/blob/main/config/renovate/renovate.json
=> konflux: follow the Mintmaker schema

mantle/cmd/kola/kola.go, mantle/cmd/kola/options.go, mantle/platform/api/azure/instance.go, mantle/platform/api/azure/options.go
Add support for configuring user-assigned managed identities`[1]` on Azure VM instances to be able to access secure resources within Azure. Add an option to kola to set the managed identity ID and carry it through to VM instance creation.
`[1]`: https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview
see: https://github.com/coreos/fedora-coreos-tracker/issues/1871
Co-authored-by: Steven Presti <spresti@redhat.com>
=> mantle/azure: Add ability to set managed identity on Azure instances

.tekton/coreos-assembler-pull-request.yaml, .tekton/coreos-assembler-push.yaml, .tekton/coreos-assembler-renovate-push.yaml, .tekton/kola-nfs-pull-request.yaml, .tekton/kola-nfs-push.yaml, .tekton/kola-nfs-renovate-push.yaml, .tekton/kola-tang-pull-request.yaml, .tekton/kola-tang-push.yaml, .tekton/kola-tang-renovate-push.yaml, .tekton/kola-targetcli-pull-request.yaml, .tekton/kola-targetcli-push.yaml, .tekton/kola-targetcli-renovate-push.yaml
The hermeto project drop the dev-package-managers flag from the RPM backend [1]. Once the prefetch-dependencies konflux task updated to pull the new hermeto [2], we'll be able to switch back to official Konflux pipeline. But for now we have to update our own temporary pipeline (more context in [3]).
[1] https://github.com/hermetoproject/hermeto/issues/986
[2] https://github.com/konflux-ci/build-definitions/blob/116f1d3c86b8ab188e5a5aaee80f01b79398bca7/task/prefetch-dependencies-oci-ta/0.2/prefetch-dependencies-oci-ta.yaml#L165
[3] https://github.com/konflux-ci/build-definitions/pull/2421
=> konflux: update pipeline

src/cmd-prune
If the oci manifest doesn't exist locally it's probably because we
buildfetched (which pulls the builds.json for all builds in the stream)
and then did a local build (which happens to be the workflow we use in
the pipeline). Let's just skip it in that case.
Fixes fd9b7da
=> cmd-prune: don't prune blob refs from non-existant builds

src/cmdlib.sh
We've added hetzner, proxmoxve, and oraclecloud, so we're running out of space now in x86_64 pipeline runs.
=> cmdlib: bump default cache size to 45G

build.sh
I build COSA normally inside my toolbox container, and hit this on a recent re-build.
=> build.sh: use NO_NETWORK:-0 to prevent errors when NO_NETWORK is unbound

mantle/cmd/ore/aws/upload.go, mantle/platform/api/aws/images.go
This will make it so we don't have to conditionalize the function call to API.RemoveImage based on if we are uploading WinLI images or not.
This is prep for more simplification in the future.
=> mantle/aws: simplify force upload handling of s3 objects

.tekton/coreos-assembler-pull-request.yaml, .tekton/coreos-assembler-push.yaml, .tekton/coreos-assembler-renovate-push.yaml, .tekton/kola-nfs-pull-request.yaml, .tekton/kola-nfs-push.yaml, .tekton/kola-nfs-renovate-push.yaml, .tekton/kola-tang-pull-request.yaml, .tekton/kola-tang-push.yaml, .tekton/kola-tang-renovate-push.yaml, .tekton/kola-targetcli-pull-request.yaml, .tekton/kola-targetcli-push.yaml, .tekton/kola-targetcli-renovate-push.yaml
As a follow-up of [1][2], we can switch back to the official pipeline reference since [3]. 
See more details about this at the end of the thread [4].
[1] c2c1b415a804c245881d71764c51b10d52020d41
[2] b1ca0bcee92a73049a0bf84e73b14d83fd5cbbc4
[3] https://github.com/hermetoproject/hermeto/issues/986
[4] https://github.com/konflux-ci/build-definitions/pull/2421
=> konflux: switch back to official pipeline ref

build.sh, src/cmd-build, src/cmd-build-with-buildah, src/cmd-import, src/cmdlib.sh
1. If `COREOS_ASSEMBLER_BUILD_WITH_BUILDAH=1`, build ostree artifacts using buildah. Else, got the traditional way.
2. Copy source ociarchive in `cosa import` rather than importing layer by layer.
3. Force create `buildid` ref on importing ociarchive
=> Make `cosa build` support building "ostree" artifact using podman/buildah

src/cmd-build-with-buildah, src/cmd-import, src/cmdlib.sh
See individual commit messages
=> cmd-build-with-buildah: enhance version handling, add yumrepos support, add autolocking

build.sh, src/cmd-osbuild, src/runvm-osbuild
In some limited cases we don't have access to /dev/kvm. For example,
riscv just added support for KVM virtualization, but there is very
little to no hardware that actually supports it. In order to build
disk images for riscv using osbuild we'll need to support running
outside the supermin VM. This code change allows for that.
This is mostly a hack and shouldn't be used unless absolutely required.
Here is the cosa alias I used to get this to work:
```
cosa() {
env | grep COREOS_ASSEMBLER >&2
rm -f "${COREOS_ASSEMBLER_CONTAINER_NAME}-variant-config.json"
if [ "$COREOS_ASSEMBLER_CONFIG_VARIANT" != "" ]; then
cat <<EOF > "${COREOS_ASSEMBLER_CONTAINER_NAME}-variant-config.json"
{
"coreos-assembler.config-variant": "${COREOS_ASSEMBLER_CONFIG_VARIANT}"
}
EOF
fi
set -x # so we can see what …
```
=> support running osbuild as root

src/cmd-build-with-buildah, src/cmd-import, src/cmd-sign
`build-rootfs` in f-c-c learned a new `overrides/` API that matches how it works in cosa. Use that API to proxy through the cosa workdir `overrides/` dir.
=> cmd-build-with-buildah: retain overrides/ API functionality

build.sh, mantle/cmd/kola/testiso.go, mantle/platform/metal.go, src/0001-stages-coreos.live-artifacts-rework-volume-ID-handli.patch, src/cmd-build
See individual commits, but basically:
- Add the `com.coreos.osname` label to the legacy cosa build path
- Fast-track https://github.com/osbuild/osbuild/pull/2169 which teaches osbuild to use that label to determine the osname
- Add a test that verifies the volume ID
=> Fast-track osbuild patch for volume ID fix and add test

mantle/cmd/kola/testiso.go
The actual backing device used for the live ISO is arch-dependent. For example on aarch64, it actually just looks like another virtio disk (e.g. `/dev/vdb`).
But we know that it must be mounted at `/run/media/iso`, so key off of that instead to find the backing device.
Fixes 06da4920a ("kola/testiso: test volume ID has OS name prefix").
=> kola/testiso: make volume ID test arch-independent

mantle/platform/qemu.go
In https://github.com/ostreedev/ostree/issues/3513 i'm trying to ensure that all the ostree mounts are cleaned up. It turned out that it was *this* unit keeping `/var` open because the `journalctl` binary doesn't know to stop tracking the `/var/log/journal` files when the daemon has flushed.
(We could obviously fix systemd to handle this)
But anyways the main reason this exists is to forward logs from startup and especially entering emergency.target. While it's useful to get logs from shutdown, there are other ways to do that.
This makes `var.mount` reliably unmounted for me.
=> qemu: Ensure virtio journal streaming is killed on shutdown

src/cmd-import, src/cmd-list
This is used by some code in this codebase. Notably some cloud uploads and e.g. our OVAs.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/2017
=> cmd-import: proxy org.opencontainers.image.title to summary in meta.json

src/cmd-import
This includes the details of packages that are included in the commit.
Closes: https://github.com/coreos/coreos-assembler/issues/4288
=> cmd-import: write commitmeta.json to the builds dir

src/cmd-coreos-prune
The `barrier` key is under the `metadata` dict. Let's update it here and also add an assert to make sure we always get some barrier release info before continuing.
=> cmd-coreos-prune: correct barrier release info

go.mod, go.sum, mantle/cmd/plume/release.go, src/cmd-build, src/cmd-build-with-buildah, src/cmd-fetch, src/cmd-generate-release-meta, src/cmdlib.sh, vendor/github.com/coreos/stream-metadata-go/fedoracoreos/fcos.go, vendor/github.com/coreos/stream-metadata-go/release/release.go, vendor/github.com/coreos/stream-metadata-go/stream/artifact_utils.go, vendor/github.com/coreos/stream-metadata-go/stream/rhcos/rhcos.go, vendor/modules.txt
We've fully cut over to OCI now for updates so we can stop having ostree commit info in there. It'll make even less sense with the buildah path where the commit hash is synthetic.
In `cosa generate-release-metadata`, stop propagating the commit. In plume, stop propagating the commit to the release index.
=> release: stop putting ostree commits into release metadata

build.sh, mantle/cmd/plume/release.go
We already have a few other `chmod`s in `install_rpms` to loosen restrictions.
This should fix supermin for people like me who run cosa in their pet containers and only run _some_ of the build.sh commands (notably we run `install_rpms`, but not `configure_user`).
=> build.sh: move chmod /usr/lib/containers/storage/overlay-* to `install_rpms`

src/cmd-build-with-buildah
All the logic for this actually lives directly in `build-rootfs`, so just pass it through to that.
=> cmd-build-with-buildah: add `--strict`

src/cmd-build-with-buildah
Use the new inputhash label to tell if there was a meaningful change since the previous build. If not, just no-op. Unless `--force` is passed.
See also: https://github.com/coreos/fedora-coreos-config/pull/3758
=> cmd-build-with-buildah: add change detection

build.sh
This reverts commit 712634cef0e303cf5a170c0f612771354b92c897.
We can have v2025.11 in cosa now that we have new libselinux.
We don't strictly need something from it but there's no point in keeping a pin either.
=> Revert "build.sh: freeze rpm-ostree on 2025.10-2.fc42"

src/cmd-build-with-buildah, src/cmd-diff
This used to be done in the cmd-build path and some things depend on it, so let's add it back here. This also prints a diff so we'll see it in the logs in the pipeline, which can be useful.
Requires some changes in https://github.com/coreos/coreos-assembler/pull/4253
=> cmd-build-with-buildah: update meta.json with pkg/advisory diffs

mantle/kola/tests/ignition/luks.go
This fixes null pointer derefernce when VM starup fails:
```
--- FAIL: luks.cex (5.83s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75d18a]
```
=> kola: fix SIGSEGV in luks.cex test

src/cosalib/aws.py
The current logic always considers the `aws-winli` buildmeta key when present, which causes WinLI AMIs to be replicated in both the standard AWS and GovCloud cases.
Restore `aws_run_ore_replicate` `[1]` to only work on the 'amis' buildmeta key and switch to aws-winli when `--winli` is used. This ensures WinLI replication happens only when explicitly requested. Also update the CLI help text for `--winli` to clarify that it applies to replication as well as creation.
`[1]`: https://github.com/coreos/coreos-assembler/pull/4069/commits/a5bfbdefe999d5cf4ec5b6d4c1de28798b6322d6
=> cosalib/aws: only replicate WinLI AMIs when --winli is specified

src/cmd-build-with-buildah, src/cmd-import
This moves the RPM/Advisory diffing into `cosa import`, which means we'll get that info even when importing from another source.
It also changes the code such that we'll only attempt to add that info if there was something to diff against. i.e. for a first build in a stream (like when doing a local dev build for the first time) now we won't error out.
Fixes https://github.com/coreos/coreos-assembler/issues/4336
=> move diff calculations into `cosa import`
